In [1]:
import pandas as pd
import numpy as np
import torch
import matplotlib.pyplot as plt
from CBFV import composition
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import re
from ast import literal_eval
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset
from xgboost import XGBRegressor
from sklearn.multioutput import MultiOutputRegressor
from ax.service.ax_client import AxClient, ObjectiveProperties
from ax.core.arm import Arm

In [ ]:
#function used to parse Ax logs and reconstruct an AxClient with the same trials and results, useful for continuing optimization after a long run or crash
def assemble_ax_from_log(ax_client, log_path, save_path):

    OBJECTIVE_NAME = "avg_rmse_nonzero"  # the metric you want to extract for optimization
    MINIMIZE = True  # RMSE -> minimize

    # --------- 2) Parse log ----------
    gen_re = re.compile(
        r"Generated new trial\s+(?P<trial>\d+)\s+with parameters\s+(?P<params>\{.*?\})\s+using model",
        re.DOTALL
    )

    # Handles: {'avg_rmse_nonzero': (np.float32(0.377...), np.float64(0.032...))}
    # Also handles: {'avg_rmse_nonzero': (0.377..., 0.032...)}
    comp_re = re.compile(
        r"Completed trial\s+(?P<trial>\d+)\s+with data:\s+(?P<data>\{.*?\})\.",
        re.DOTALL
    )

    def _strip_np_wrappers(s: str) -> str:
        # Turn np.float32(0.1) -> 0.1, np.float64(0.2) -> 0.2, etc.
        s = re.sub(r"np\.float(?:16|32|64)\(([^)]+)\)", r"\1", s)
        s = re.sub(r"np\.int(?:8|16|32|64)\(([^)]+)\)", r"\1", s)
        return s

    with open(log_path, "r", encoding="utf-8", errors="ignore") as f:
        text = f.read()

    generated = {}
    for m in gen_re.finditer(text):
        t = int(m["trial"])
        params_str = m["params"]
        params = literal_eval(params_str)  # safe for dict literals like yours
        generated[t] = params

    completed = {}
    for m in comp_re.finditer(text):
        t = int(m["trial"])
        data_str = _strip_np_wrappers(m["data"])
        data = literal_eval(data_str)
        # Expect metric -> (mean, sem) OR metric -> mean
        val = data[OBJECTIVE_NAME]
        if isinstance(val, tuple):
            mean, sem = float(val[0]), float(val[1])
        else:
            mean, sem = float(val), None
        completed[t] = (mean, sem)

    # Align trials that have both params and completion
    trial_ids = sorted(set(generated.keys()) & set(completed.keys()))
    missing_params = sorted(set(completed.keys()) - set(generated.keys()))
    missing_results = sorted(set(generated.keys()) - set(completed.keys()))

    print(f"Recovered {len(trial_ids)} completed trials with params.")
    if missing_params:
        print(f"Warning: {len(missing_params)} completed trials missing params: {missing_params[:10]} ...")
    if missing_results:
        print(f"Note: {len(missing_results)} generated trials missing results (not completed): {missing_results[:10]} ...")

        exp = ax_client.experiment

    for t in trial_ids:
        params = generated[t]
        mean, sem = completed[t]

        trial = exp.new_trial()
        trial.add_arm(Arm(parameters=params))

        # IMPORTANT for your Ax version:
        trial.mark_running(no_runner_required=True)

        if sem is None:
            ax_client.complete_trial(
                trial_index=trial.index,
                raw_data={OBJECTIVE_NAME: mean},
            )
        else:
            ax_client.complete_trial(
                trial_index=trial.index,
                raw_data={OBJECTIVE_NAME: (mean, sem)},
            )

In [2]:
class FlexibleNN(nn.Module):
    """
    A flexible neural network with configurable architecture for hyperparameter optimization.
    
    Parameters:
    -----------
    input_dim : int
        Number of input features (CBFV features)
    output_dim : int
        Number of output targets (phase fractions at selected temperatures)
    hidden_layers : list of int
        List of hidden layer sizes, e.g., [256, 128, 64]
    dropout_rate : float
        Dropout probability (0.0 to 1.0)
    dropout_type : str
        Type of dropout: 'standard', 'alpha' (for SELU), or 'none'
    activation : str
        Activation function: 'relu', 'leaky_relu', 'elu', 'selu', 'gelu', 'tanh'
    use_batch_norm : bool
        Whether to use batch normalization
    use_layer_norm : bool
        Whether to use layer normalization (alternative to batch norm)
    weight_decay : float
        L2 regularization strength (applied in optimizer, stored here for reference)
    nf_indices : list of int or None
        Indices of output columns that are phase fractions (NF). 
        These will have softmax applied so they sum to 1.
        If None, no softmax constraint is applied.
    output_columns : list of str or None
        Column names for outputs. If provided, NF columns are auto-detected
        by checking for 'NF_' prefix. Overrides nf_indices if both provided.
    """
    
    def __init__(
        self,
        input_dim,
        output_dim,
        hidden_layers=[256, 128, 64],
        dropout_rate=0.2,
        dropout_type='standard',
        activation='relu',
        use_batch_norm=False,
        use_layer_norm=False,
        weight_decay=0.0,
        nf_indices=None,
        output_columns=None
    ):
        super(FlexibleNN, self).__init__()
        
        self.weight_decay = weight_decay  # Store for optimizer configuration
        self.output_dim = output_dim
        
        # Determine NF indices (phase fractions that should sum to 1)
        if output_columns is not None:
            # Auto-detect NF columns from column names
            self.nf_indices = [i for i, col in enumerate(output_columns) if col.startswith('NF_')]
            self.df_indices = [i for i, col in enumerate(output_columns) if col.startswith('DF_')]
        elif nf_indices is not None:
            self.nf_indices = nf_indices
            self.df_indices = [i for i in range(output_dim) if i not in nf_indices]
        else:
            self.nf_indices = []
            self.df_indices = list(range(output_dim))
        
        # Build activation function
        activation_fn = self._get_activation(activation)
        
        # Build dropout layer
        dropout_layer = self._get_dropout(dropout_type, dropout_rate)
        
        # Build the network layers
        layers = []
        prev_dim = input_dim
        
        for hidden_dim in hidden_layers:
            # Linear layer
            layers.append(nn.Linear(prev_dim, hidden_dim))
            
            # Normalization (batch norm or layer norm, not both)
            if use_batch_norm:
                layers.append(nn.BatchNorm1d(hidden_dim))
            elif use_layer_norm:
                layers.append(nn.LayerNorm(hidden_dim))
            
            # Activation
            layers.append(activation_fn())
            
            # Dropout
            if dropout_layer is not None:
                layers.append(dropout_layer(dropout_rate))
            
            prev_dim = hidden_dim
        
        # Output layer (no activation, dropout, or normalization)
        layers.append(nn.Linear(prev_dim, output_dim))
        
        self.network = nn.Sequential(*layers)
    
    def _get_activation(self, activation):
        activations = {
            'relu': nn.ReLU,
            'leaky_relu': lambda: nn.LeakyReLU(0.1),
            'elu': nn.ELU,
            'selu': nn.SELU,
            'gelu': nn.GELU,
            'tanh': nn.Tanh,
            'sigmoid': nn.Sigmoid
        }
        if activation not in activations:
            raise ValueError(f"Unknown activation: {activation}. Choose from {list(activations.keys())}")
        return activations[activation]
    
    def _get_dropout(self, dropout_type, dropout_rate):
        if dropout_type == 'none' or dropout_rate == 0:
            return None
        elif dropout_type == 'standard':
            return nn.Dropout
        elif dropout_type == 'alpha':
            return nn.AlphaDropout  # For use with SELU activation
        else:
            raise ValueError(f"Unknown dropout type: {dropout_type}. Choose from ['standard', 'alpha', 'none']")
    
    def forward(self, x):
        raw_output = self.network(x)
        
        # If no NF indices, return raw output
        if len(self.nf_indices) == 0:
            return raw_output
        
        # Apply softmax to NF (phase fraction) outputs so they sum to 1
        output = raw_output.clone()
        
        # Extract NF outputs and apply softmax
        nf_outputs = raw_output[:, self.nf_indices]
        nf_normalized = torch.softmax(nf_outputs, dim=1)
        
        # Put normalized NF values back
        output[:, self.nf_indices] = nf_normalized
        
        return output
    
    def get_optimizer(self, optimizer_type='adam', lr=1e-3):
        """
        Get an optimizer with the configured weight decay (L2 regularization).
        """
        optimizers = {
            'adam': lambda: torch.optim.Adam(self.parameters(), lr=lr, weight_decay=self.weight_decay),
            'adamw': lambda: torch.optim.AdamW(self.parameters(), lr=lr, weight_decay=self.weight_decay),
            'sgd': lambda: torch.optim.SGD(self.parameters(), lr=lr, weight_decay=self.weight_decay, momentum=0.9),
            'rmsprop': lambda: torch.optim.RMSprop(self.parameters(), lr=lr, weight_decay=self.weight_decay)
        }
        if optimizer_type not in optimizers:
            raise ValueError(f"Unknown optimizer: {optimizer_type}. Choose from {list(optimizers.keys())}")
        return optimizers[optimizer_type]()


def train_epoch(model, train_loader, optimizer, criterion, device):
    """
    Train the model for one epoch.
    
    Returns:
    --------
    float : Average training loss for the epoch
    """
    model.train()
    total_loss = 0.0
    num_batches = 0
    
    for X_batch, y_batch in train_loader:
        X_batch, y_batch = X_batch.to(device), y_batch.to(device)
        
        optimizer.zero_grad()
        predictions = model(X_batch)
        loss = criterion(predictions, y_batch)
        loss.backward()
        optimizer.step()
        
        total_loss += loss.item()
        num_batches += 1
    
    return total_loss / num_batches


def evaluate_epoch(model, val_loader, criterion, device):
    """
    Evaluate the model on validation data.
    
    Returns:
    --------
    tuple : (average loss, predictions, targets)
    """
    model.eval()
    total_loss = 0.0
    total_samples = 0
    all_predictions = []
    all_targets = []
    
    with torch.no_grad():
        for X_batch, y_batch in val_loader:
            X_batch, y_batch = X_batch.to(device), y_batch.to(device)
            batch_size = X_batch.size(0)
            
            predictions = model(X_batch)
            loss = criterion(predictions, y_batch)
            
            # Weight loss by batch size for correct averaging
            total_loss += loss.item() * batch_size
            total_samples += batch_size
            
            all_predictions.append(predictions.cpu())
            all_targets.append(y_batch.cpu())
    
    # Weighted average loss (accounts for different batch sizes)
    avg_loss = total_loss / total_samples
    all_predictions = torch.cat(all_predictions, dim=0)
    all_targets = torch.cat(all_targets, dim=0)
    
    return avg_loss, all_predictions, all_targets


def train_model(
    model,
    X_train, y_train,
    X_val, y_val,
    epochs=100,
    batch_size=32,
    optimizer_type='adam',
    lr=1e-3,
    criterion=None,
    early_stopping_patience=None,
    verbose=True,
    device=None
):
    """
    Train the model for a specified number of epochs.
    
    Parameters:
    -----------
    model : FlexibleNN
        The neural network model
    X_train, y_train : array-like
        Training data
    X_val, y_val : array-like
        Validation data
    epochs : int
        Number of training epochs
    batch_size : int
        Batch size for training
    optimizer_type : str
        Type of optimizer ('adam', 'adamw', 'sgd', 'rmsprop')
    lr : float
        Learning rate
    criterion : nn.Module
        Loss function (default: MSELoss)
    early_stopping_patience : int or None
        Stop training if val loss doesn't improve for this many epochs
    verbose : bool
        Whether to print progress
    device : str or None
        Device to train on ('cuda', 'mps', 'cpu', or None for auto-detect)
    
    Returns:
    --------
    dict : Training history with train_losses, val_losses, best_epoch
    """
    # Auto-detect device
    if device is None:
        if torch.cuda.is_available():
            device = 'cuda'
        elif torch.backends.mps.is_available():
            device = 'mps'
        else:
            device = 'cpu'
    
    device = torch.device(device)
    model = model.to(device)
    
    # Default criterion
    if criterion is None:
        criterion = nn.MSELoss()
    
    # Convert data to tensors
    X_train_t = torch.FloatTensor(X_train.values if hasattr(X_train, 'values') else X_train)
    y_train_t = torch.FloatTensor(y_train.values if hasattr(y_train, 'values') else y_train)
    X_val_t = torch.FloatTensor(X_val.values if hasattr(X_val, 'values') else X_val)
    y_val_t = torch.FloatTensor(y_val.values if hasattr(y_val, 'values') else y_val)
    
    # Create data loaders
    train_dataset = TensorDataset(X_train_t, y_train_t)
    val_dataset = TensorDataset(X_val_t, y_val_t)
    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
    val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)
    
    # Get optimizer
    optimizer = model.get_optimizer(optimizer_type=optimizer_type, lr=lr)
    
    # Training history
    history = {
        'train_losses': [],
        'val_losses': [],
        'best_epoch': 0,
        'best_val_loss': float('inf')
    }
    
    # Early stopping
    patience_counter = 0
    best_model_state = None
    
    for epoch in range(epochs):
        # Train
        train_loss = train_epoch(model, train_loader, optimizer, criterion, device)
        
        # Evaluate
        val_loss, _, _ = evaluate_epoch(model, val_loader, criterion, device)
        
        history['train_losses'].append(train_loss)
        history['val_losses'].append(val_loss)
        
        # Track best model
        if val_loss < history['best_val_loss']:
            history['best_val_loss'] = val_loss
            history['best_epoch'] = epoch
            best_model_state = model.state_dict().copy()
            patience_counter = 0
        else:
            patience_counter += 1
        
        # Verbose output
        if verbose and (epoch % 10 == 0 or epoch == epochs - 1):
            print(f"Epoch {epoch+1}/{epochs} - Train Loss: {train_loss:.6f} - Val Loss: {val_loss:.6f}")
        
        # Early stopping
        if early_stopping_patience and patience_counter >= early_stopping_patience:
            if verbose:
                print(f"Early stopping at epoch {epoch+1}. Best epoch: {history['best_epoch']+1}")
            break
    
    # Restore best model
    if best_model_state is not None:
        model.load_state_dict(best_model_state)
    
    return history

In [3]:
class PhaseFractionNN(nn.Module):
    """
    Neural network for predicting phase fractions (NF) where outputs must sum to 1.
    Applies softmax to all outputs to ensure they represent valid phase fractions.
    
    Parameters:
    -----------
    input_dim : int
        Number of input features (CBFV features + temperature)
    output_dim : int
        Number of phases to predict
    hidden_layers : list of int
        List of hidden layer sizes, e.g., [256, 512, 1024]
    dropout_rate : float
        Dropout probability (0.0 to 1.0)
    dropout_type : str
        Type of dropout: 'standard', 'alpha' (for SELU), or 'none'
    activation : str
        Activation function: 'relu', 'leaky_relu', 'elu', 'selu', 'gelu', 'tanh'
    use_batch_norm : bool
        Whether to use batch normalization
    use_layer_norm : bool
        Whether to use layer normalization (alternative to batch norm)
    weight_decay : float
        L2 regularization strength (applied in optimizer, stored here for reference)
    """
    
    def __init__(
        self,
        input_dim,
        output_dim,
        hidden_layers=[256, 512, 1024],
        dropout_rate=0.2,
        dropout_type='standard',
        activation='relu',
        use_batch_norm=False,
        use_layer_norm=False,
        weight_decay=0.0,
    ):
        super(PhaseFractionNN, self).__init__()
        
        self.weight_decay = weight_decay
        self.output_dim = output_dim
        
        # Build activation function
        activation_fn = self._get_activation(activation)
        
        # Build dropout layer
        dropout_layer = self._get_dropout(dropout_type, dropout_rate)
        
        # Build the network layers
        layers = []
        prev_dim = input_dim
        
        for hidden_dim in hidden_layers:
            # Linear layer
            layers.append(nn.Linear(prev_dim, hidden_dim))
            
            # Normalization (batch norm or layer norm, not both)
            if use_batch_norm:
                layers.append(nn.BatchNorm1d(hidden_dim))
            elif use_layer_norm:
                layers.append(nn.LayerNorm(hidden_dim))
            
            # Activation
            layers.append(activation_fn())
            
            # Dropout
            if dropout_layer is not None:
                layers.append(dropout_layer(dropout_rate))
            
            prev_dim = hidden_dim
        
        # Output layer (no activation here - softmax applied in forward)
        layers.append(nn.Linear(prev_dim, output_dim))
        
        self.network = nn.Sequential(*layers)
    
    def _get_activation(self, activation):
        activations = {
            'relu': nn.ReLU,
            'leaky_relu': lambda: nn.LeakyReLU(0.1),
            'elu': nn.ELU,
            'selu': nn.SELU,
            'gelu': nn.GELU,
            'tanh': nn.Tanh,
            'sigmoid': nn.Sigmoid
        }
        if activation not in activations:
            raise ValueError(f"Unknown activation: {activation}. Choose from {list(activations.keys())}")
        return activations[activation]
    
    def _get_dropout(self, dropout_type, dropout_rate):
        if dropout_type == 'none' or dropout_rate == 0:
            return None
        elif dropout_type == 'standard':
            return nn.Dropout
        elif dropout_type == 'alpha':
            return nn.AlphaDropout  # For use with SELU activation
        else:
            raise ValueError(f"Unknown dropout type: {dropout_type}. Choose from ['standard', 'alpha', 'none']")
    
    def forward(self, x):
        """
        Forward pass with softmax applied to ensure outputs sum to 1.
        """
        logits = self.network(x)
        # Apply softmax so phase fractions sum to 1
        phase_fractions = torch.softmax(logits, dim=1)
        return phase_fractions
    
    def get_optimizer(self, optimizer_type='adam', lr=1e-3):
        """
        Get an optimizer with the configured weight decay (L2 regularization).
        """
        optimizers = {
            'adam': lambda: torch.optim.Adam(self.parameters(), lr=lr, weight_decay=self.weight_decay),
            'adamw': lambda: torch.optim.AdamW(self.parameters(), lr=lr, weight_decay=self.weight_decay),
            'sgd': lambda: torch.optim.SGD(self.parameters(), lr=lr, weight_decay=self.weight_decay, momentum=0.9),
            'rmsprop': lambda: torch.optim.RMSprop(self.parameters(), lr=lr, weight_decay=self.weight_decay)
        }
        if optimizer_type not in optimizers:
            raise ValueError(f"Unknown optimizer: {optimizer_type}. Choose from {list(optimizers.keys())}")
        return optimizers[optimizer_type]()





# Custom loss for phase fractions - can use KL divergence or cross-entropy style loss
class PhaseFractionLoss(nn.Module):
    """
    Loss function for phase fraction prediction.
    Combines MSE with optional KL divergence to encourage proper probability distributions.
    
    Parameters:
    -----------
    mse_weight : float
        Weight for MSE component (default: 1.0)
    kl_weight : float
        Weight for KL divergence component (default: 0.0)
        Set > 0 to encourage outputs to match target distribution shape
    """
    def __init__(self, mse_weight=1.0, kl_weight=0.0):
        super().__init__()
        self.mse_weight = mse_weight
        self.kl_weight = kl_weight
        self.mse = nn.MSELoss()
        self.kl = nn.KLDivLoss(reduction='batchmean')
    
    def forward(self, predictions, targets):
        # MSE loss
        mse_loss = self.mse(predictions, targets)
        
        if self.kl_weight > 0:
            # KL divergence (predictions should already be softmax output)
            # Add small epsilon to avoid log(0)
            eps = 1e-8
            log_preds = torch.log(predictions + eps)
            # Normalize targets to sum to 1 (they should already, but just in case)
            targets_norm = targets / (targets.sum(dim=1, keepdim=True) + eps)
            kl_loss = self.kl(log_preds, targets_norm)
            return self.mse_weight * mse_loss + self.kl_weight * kl_loss
        
        return mse_loss


class DrivingForceNN(nn.Module):
    """
    Neural network for predicting driving forces (DF).
    Outputs are unconstrained real values (no softmax).
    
    Parameters:
    -----------
    input_dim : int
        Number of input features (CBFV features + temperature)
    output_dim : int
        Number of driving force outputs to predict
    hidden_layers : list of int
        List of hidden layer sizes, e.g., [256, 512, 1024]
    dropout_rate : float
        Dropout probability (0.0 to 1.0)
    dropout_type : str
        Type of dropout: 'standard', 'alpha' (for SELU), or 'none'
    activation : str
        Activation function: 'relu', 'leaky_relu', 'elu', 'selu', 'gelu', 'tanh'
    use_batch_norm : bool
        Whether to use batch normalization
    use_layer_norm : bool
        Whether to use layer normalization (alternative to batch norm)
    weight_decay : float
        L2 regularization strength (applied in optimizer, stored here for reference)
    """
    
    def __init__(
        self,
        input_dim,
        output_dim,
        hidden_layers=[256, 512, 1024],
        dropout_rate=0.2,
        dropout_type='standard',
        activation='relu',
        use_batch_norm=False,
        use_layer_norm=False,
        weight_decay=0.0,
    ):
        super(DrivingForceNN, self).__init__()
        
        self.weight_decay = weight_decay
        self.output_dim = output_dim
        
        # Build activation function
        activation_fn = self._get_activation(activation)
        
        # Build dropout layer
        dropout_layer = self._get_dropout(dropout_type, dropout_rate)
        
        # Build the network layers
        layers = []
        prev_dim = input_dim
        
        for hidden_dim in hidden_layers:
            layers.append(nn.Linear(prev_dim, hidden_dim))
            
            if use_batch_norm:
                layers.append(nn.BatchNorm1d(hidden_dim))
            elif use_layer_norm:
                layers.append(nn.LayerNorm(hidden_dim))
            
            layers.append(activation_fn())
            
            if dropout_layer is not None:
                layers.append(dropout_layer(dropout_rate))
            
            prev_dim = hidden_dim
        
        # Output layer - no activation (driving forces are unconstrained real values)
        layers.append(nn.Linear(prev_dim, output_dim))
        
        self.network = nn.Sequential(*layers)
    
    def _get_activation(self, activation):
        activations = {
            'relu': nn.ReLU,
            'leaky_relu': lambda: nn.LeakyReLU(0.1),
            'elu': nn.ELU,
            'selu': nn.SELU,
            'gelu': nn.GELU,
            'tanh': nn.Tanh,
            'sigmoid': nn.Sigmoid
        }
        if activation not in activations:
            raise ValueError(f"Unknown activation: {activation}. Choose from {list(activations.keys())}")
        return activations[activation]
    
    def _get_dropout(self, dropout_type, dropout_rate):
        if dropout_type == 'none' or dropout_rate == 0:
            return None
        elif dropout_type == 'standard':
            return nn.Dropout
        elif dropout_type == 'alpha':
            return nn.AlphaDropout
        else:
            raise ValueError(f"Unknown dropout type: {dropout_type}. Choose from ['standard', 'alpha', 'none']")
    
    def forward(self, x):
        """
        Forward pass - raw output, no constraints applied.
        Driving forces can be any real value.
        """
        return self.network(x)
    
    def get_optimizer(self, optimizer_type='adam', lr=1e-3):
        """
        Get an optimizer with the configured weight decay (L2 regularization).
        """
        optimizers = {
            'adam': lambda: torch.optim.Adam(self.parameters(), lr=lr, weight_decay=self.weight_decay),
            'adamw': lambda: torch.optim.AdamW(self.parameters(), lr=lr, weight_decay=self.weight_decay),
            'sgd': lambda: torch.optim.SGD(self.parameters(), lr=lr, weight_decay=self.weight_decay, momentum=0.9),
            'rmsprop': lambda: torch.optim.RMSprop(self.parameters(), lr=lr, weight_decay=self.weight_decay)
        }
        if optimizer_type not in optimizers:
            raise ValueError(f"Unknown optimizer: {optimizer_type}. Choose from {list(optimizers.keys())}")
        return optimizers[optimizer_type]()

In [4]:
def fourier_features(T, n_freqs=6):
    """
    Generate Fourier features for temperature values.
    
    Args:
        T: 1D tensor of temperature values (shape: [N])
        n_freqs: number of frequency components (produces 2*n_freqs features)
    
    Returns:
        2D tensor of shape [N, 2*n_freqs] where each row is the Fourier encoding
    """
    # Ensure T is 2D with shape [N, 1] for broadcasting
    if T.dim() == 1:
        T = T.unsqueeze(1)
    
    feats = []
    for k in range(n_freqs):
        freq = 2**k
        feats.append(torch.sin(2 * torch.pi * freq * T))
        feats.append(torch.cos(2 * torch.pi * freq * T))
    
    # Stack along dim=1 to get shape [N, 2*n_freqs]
    return torch.cat(feats, dim=1)

In [ ]:
df_reshaped = pd.read_csv(r'Data/F(T)_Data/calphad_alloys_train_opt_reshaped.csv')
df_reshaped.head()

,alloy_string,temperature,DF_AG2CA,DF_AG3BE8,DF_AG3CA5,DF_AG3MG,DF_AG7CA2,DF_AG9CA2,DF_AGCA,DF_AGCA3,...,NF_YSI2_H,NF_YSI2_R,NF_ZINCBLENDE_B3,NF_ZR2SI,NF_ZR3SI,NF_ZR3SI2,NF_ZR5SI3,NF_ZR5SI4,NF_ZRSI,NF_ZRSI2
0,B22.00Co4.00Fe68.00Y6.00,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,B22.00Co4.00Fe68.00Y6.00,50,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,B22.00Co4.00Fe68.00Y6.00,100,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,B22.00Co4.00Fe68.00Y6.00,150,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,B22.00Co4.00Fe68.00Y6.00,200,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
# Extract alloy strings and create formula dataframe
formula_df = pd.DataFrame({'formula': df_reshaped['alloy_string']})
print(f"Formula dataframe shape: {formula_df.shape}")
formula_df.head()

Formula dataframe shape: (44982, 1)

                    formula
0  B22.00Co4.00Fe68.00Y6.00
1  B22.00Co4.00Fe68.00Y6.00
2  B22.00Co4.00Fe68.00Y6.00
3  B22.00Co4.00Fe68.00Y6.00
4  B22.00Co4.00Fe68.00Y6.00

In [7]:
# Generate Composition-Based Feature Vectors using CBFV
# CBFV expects 'formula' column and optionally a 'target' column
# Add a dummy target for featurization (we'll drop it after)
formula_df['target'] = 0

# Generate CBFVs using the magpie element property database
X, y, formulae, skipped = composition.generate_features(formula_df, elem_prop='magpie')
print(f"CBFV features shape: {X.shape}")
print(f"Number of skipped formulas: {len(skipped)}")
X.head()

Processing Input Data: 100%|██████████| 44982/44982 [00:01<00:00, 38269.41it/s]

	Featurizing Compositions...

Assigning Features...: 100%|██████████| 44982/44982 [00:01<00:00, 31641.54it/s]

	Creating Pandas Objects...
CBFV features shape: (44982, 132)
Number of skipped formulas: 0

,avg_Number,avg_MendeleevNumber,avg_AtomicWeight,avg_MeltingT,avg_Column,avg_Row,avg_CovalentRadius,avg_Electronegativity,avg_NsValence,avg_NpValence,...,mode_NValence,mode_NsUnfilled,mode_NpUnfilled,mode_NdUnfilled,mode_NfUnfilled,mode_NUnfilled,mode_GSvolume_pa,mode_GSbandgap,mode_GSmagmom,mode_SpaceGroupNumber
0,22.2,56.28,48.044699,1926.7,8.84,3.62,124.68,1.8416,2.0,0.22,...,8.0,0.0,0.0,4.0,0.0,4.0,10.73,0.0,2.110663,229.0
1,22.2,56.28,48.044699,1926.7,8.84,3.62,124.68,1.8416,2.0,0.22,...,8.0,0.0,0.0,4.0,0.0,4.0,10.73,0.0,2.110663,229.0
2,22.2,56.28,48.044699,1926.7,8.84,3.62,124.68,1.8416,2.0,0.22,...,8.0,0.0,0.0,4.0,0.0,4.0,10.73,0.0,2.110663,229.0
3,22.2,56.28,48.044699,1926.7,8.84,3.62,124.68,1.8416,2.0,0.22,...,8.0,0.0,0.0,4.0,0.0,4.0,10.73,0.0,2.110663,229.0
4,22.2,56.28,48.044699,1926.7,8.84,3.62,124.68,1.8416,2.0,0.22,...,8.0,0.0,0.0,4.0,0.0,4.0,10.73,0.0,2.110663,229.0

In [8]:
fourier_Temp_features = fourier_features(torch.tensor(df_reshaped['temperature'].values, dtype=torch.float32))
fourier_Temp_features_df = pd.DataFrame(
    fourier_Temp_features.numpy(),
    columns=[f'fourier_{i}' for i in range(fourier_Temp_features.shape[1])],
    index=df_reshaped.index
)

In [9]:
X_combined = pd.concat([X, fourier_Temp_features_df], axis=1)
print(f"X shape: {X_combined.shape}")
X_combined.head()

X shape: (44982, 144)

,avg_Number,avg_MendeleevNumber,avg_AtomicWeight,avg_MeltingT,avg_Column,avg_Row,avg_CovalentRadius,avg_Electronegativity,avg_NsValence,avg_NpValence,...,fourier_2,fourier_3,fourier_4,fourier_5,fourier_6,fourier_7,fourier_8,fourier_9,fourier_10,fourier_11
0,22.2,56.28,48.044699,1926.7,8.84,3.62,124.68,1.8416,2.0,0.22,...,0.000000,1.0,0.000000,1.0,0.000000,1.0,0.000000,1.0,0.000000,1.000000
1,22.2,56.28,48.044699,1926.7,8.84,3.62,124.68,1.8416,2.0,0.22,...,0.000012,1.0,0.000024,1.0,0.000047,1.0,0.000094,1.0,0.000188,1.000000
2,22.2,56.28,48.044699,1926.7,8.84,3.62,124.68,1.8416,2.0,0.22,...,0.000024,1.0,0.000047,1.0,0.000094,1.0,0.000188,1.0,0.000376,1.000000
3,22.2,56.28,48.044699,1926.7,8.84,3.62,124.68,1.8416,2.0,0.22,...,0.000096,1.0,0.000193,1.0,0.000385,1.0,0.000771,1.0,0.001541,0.999999
4,22.2,56.28,48.044699,1926.7,8.84,3.62,124.68,1.8416,2.0,0.22,...,0.000047,1.0,0.000094,1.0,0.000188,1.0,0.000376,1.0,0.000753,1.000000

In [10]:
# Create 5 CV groups by clustering similar alloys together
# Standardize features for clustering
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_combined)

# Use KMeans to group similar alloys into 5 clusters
kmeans = KMeans(n_clusters=5, random_state=42, n_init=10)
cv_groups = kmeans.fit_predict(X_scaled)

#local CV, umap,

# Add group assignments to a dataframe for reference
cv_group_df = pd.DataFrame({
    'formula': formulae,
    'cv_group': cv_groups
})

print("CV Group distribution:")
print(cv_group_df['cv_group'].value_counts().sort_index())
print(f"\nTotal samples: {len(cv_groups)}")
cv_group_df.head(10)

CV Group distribution:
cv_group
0     7599
1    16014
2     6375
3    10200
4     4794
Name: count, dtype: int64

Total samples: 44982

                    formula  cv_group
0  B22.00Co4.00Fe68.00Y6.00         3
1  B22.00Co4.00Fe68.00Y6.00         3
2  B22.00Co4.00Fe68.00Y6.00         3
3  B22.00Co4.00Fe68.00Y6.00         3
4  B22.00Co4.00Fe68.00Y6.00         3
5  B22.00Co4.00Fe68.00Y6.00         3
6  B22.00Co4.00Fe68.00Y6.00         3
7  B22.00Co4.00Fe68.00Y6.00         3
8  B22.00Co4.00Fe68.00Y6.00         3
9  B22.00Co4.00Fe68.00Y6.00         3

In [11]:
# Create separate y dataframes for NF (phase fractions) and DF (driving forces)
all_cols = df_reshaped.drop(columns=['alloy_string', 'temperature']).columns.tolist()

# Split into NF and DF columns
nf_cols = [col for col in all_cols if col.startswith('NF_')]
df_cols = [col for col in all_cols if col.startswith('DF_')]

y_nf = df_reshaped[nf_cols]
y_df = df_reshaped[df_cols]

print(f"Phase Fractions (NF) shape: {y_nf.shape}")
print(f"Driving Forces (DF) shape: {y_df.shape}")
print(f"\nNF columns: {len(nf_cols)}, DF columns: {len(df_cols)}")
y_nf.head()

Phase Fractions (NF) shape: (44982, 804)
Driving Forces (DF) shape: (44982, 804)

NF columns: 804, DF columns: 804

,NF_AG2CA,NF_AG3BE8,NF_AG3CA5,NF_AG3MG,NF_AG7CA2,NF_AG9CA2,NF_AGCA,NF_AGCA3,NF_AGCD_ETA,NF_AGIN2,...,NF_YSI2_H,NF_YSI2_R,NF_ZINCBLENDE_B3,NF_ZR2SI,NF_ZR3SI,NF_ZR3SI2,NF_ZR5SI3,NF_ZR5SI4,NF_ZRSI,NF_ZRSI2
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [12]:
def evaluate_parameters_NFnn(parameters, batch_size=32, epochs=1000, verbose=True):
    
    # Extract hyperparameters from parameters dict with defaults
    batch_size = parameters.get('batch_size', batch_size)
    hidden_layers = parameters.get('hidden_layers', [256, 128, 64])
    dropout_rate = parameters.get('dropout_rate', 0.2)
    dropout_type = parameters.get('dropout_type', 'standard')
    activation = parameters.get('activation', 'relu')
    use_batch_norm = parameters.get('use_batch_norm', False)
    use_layer_norm = parameters.get('use_layer_norm', False)
    weight_decay = parameters.get('weight_decay', 0.0)
    optimizer_type = parameters.get('optimizer_type', 'adam')
    lr = parameters.get('lr', 1e-3)
    early_stopping_patience = parameters.get('early_stopping_patience', 10)

    # Auto-detect device
    if torch.cuda.is_available():
        device = torch.device('cuda')
    elif torch.backends.mps.is_available():
        device = torch.device('mps')
    else:
        device = torch.device('cpu')
    print(f"Using device: {device}")

    #copy the x and y data
    y_data = y_nf.copy()
    x_data = X_combined.copy()

    # Get input and output dimensions
    input_dim = x_data.shape[1]
    output_dim = y_data.shape[1]
    print(f"Input dim: {input_dim}, Output dim: {output_dim}")

    # Store results for each fold
    fold_results = []
    all_test_predictions = []
    all_test_targets = []

    for test_group in range(5):  # 0-4 for 5 groups from KMeans
        print(f"\n{'='*50}")
        print(f"Fold {test_group}")
        print('='*50)
        
        # Get the split indexes for training and testing
        train_idx = cv_group_df['cv_group'] != test_group
        test_idx = cv_group_df['cv_group'] == test_group

        # Split the x and y data in train and test
        x_train = x_data.loc[train_idx]
        x_test = x_data.loc[test_idx]

        y_train = y_data.loc[train_idx]
        y_test = y_data.loc[test_idx]
        
        # Create train and validation data
        X_train, X_val, y_train, y_val = train_test_split(
            x_train, y_train, test_size=0.2, random_state=42
        )

        print(f"Train: {len(X_train)}, Val: {len(X_val)}, Test: {len(x_test)}")

        # Scale the x data
        scaler = StandardScaler()
        X_train_scaled = pd.DataFrame(scaler.fit_transform(X_train), columns=X_train.columns, index=X_train.index)
        X_val_scaled = pd.DataFrame(scaler.transform(X_val), columns=X_val.columns, index=X_val.index)
        x_test_scaled = pd.DataFrame(scaler.transform(x_test), columns=x_test.columns, index=x_test.index)

        #scale the y data
        y_scaler = StandardScaler()
        y_train_scaled = pd.DataFrame(y_scaler.fit_transform(y_train), columns=y_train.columns, index=y_train.index)
        y_val_scaled = pd.DataFrame(y_scaler.transform(y_val), columns=y_val.columns, index=y_val.index)
        y_test_scaled = pd.DataFrame(y_scaler.transform(y_test), columns=y_test.columns, index=y_test.index)

        # Convert DataFrames to PyTorch tensors
        X_train_t = torch.FloatTensor(X_train_scaled.values)
        y_train_t = torch.FloatTensor(y_train_scaled.values)
        X_val_t = torch.FloatTensor(X_val_scaled.values)
        y_val_t = torch.FloatTensor(y_val_scaled.values)
        X_test_t = torch.FloatTensor(x_test_scaled.values)
        y_test_t = torch.FloatTensor(y_test_scaled.values)

        # Create TensorDatasets
        train_dataset = TensorDataset(X_train_t, y_train_t)
        val_dataset = TensorDataset(X_val_t, y_val_t)
        test_dataset = TensorDataset(X_test_t, y_test_t)

        # Create DataLoaders
        # drop_last=True for train_loader to avoid batch size of 1 (causes BatchNorm to fail)
        train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, drop_last=True)
        val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)
        test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

        # Create the model with output_columns to auto-detect NF columns for softmax
        model = FlexibleNN(
            input_dim=input_dim,
            output_dim=output_dim,
            hidden_layers=hidden_layers,
            dropout_rate=dropout_rate,
            dropout_type=dropout_type,
            activation=activation,
            use_batch_norm=use_batch_norm,
            use_layer_norm=use_layer_norm,
            weight_decay=weight_decay,
            output_columns=y_data.columns.tolist()  # Auto-detect NF columns for softmax constraint
        ).to(device)

        # Get optimizer and criterion
        optimizer = model.get_optimizer(optimizer_type=optimizer_type, lr=lr)
        criterion = nn.MSELoss()

        # Training loop
        best_val_loss = float('inf')
        best_model_state = None
        patience_counter = 0
        train_losses = []
        val_losses = []

        for epoch in range(epochs):
            # Train
            train_loss = train_epoch(model, train_loader, optimizer, criterion, device)
            
            # Evaluate on validation
            val_loss, _, _ = evaluate_epoch(model, val_loader, criterion, device)
            
            train_losses.append(train_loss)
            val_losses.append(val_loss)
            
            # Track best model
            if val_loss < best_val_loss:
                best_val_loss = val_loss
                best_model_state = {k: v.cpu().clone() for k, v in model.state_dict().items()}
                patience_counter = 0
            else:
                patience_counter += 1
            
            # Verbose output
            if verbose and (epoch % 20 == 0 or epoch == epochs - 1):
                print(f"Epoch {epoch+1}/{epochs} - Train Loss: {train_loss:.6f} - Val Loss: {val_loss:.6f}")
            
            # Early stopping
            if early_stopping_patience and patience_counter >= early_stopping_patience:
                print(f"Early stopping at epoch {epoch+1}")
                break

        # Restore best model
        if best_model_state is not None:
            model.load_state_dict(best_model_state)
            model.to(device)

        # Evaluate on test set (scaled)
        test_loss_scaled, test_preds_scaled, test_targets_scaled = evaluate_epoch(model, test_loader, criterion, device)
        
        # Inverse transform predictions and targets to original scale
        test_preds_original = y_scaler.inverse_transform(test_preds_scaled.numpy())
        test_targets_original = y_scaler.inverse_transform(test_targets_scaled.numpy())
        
        # Get column names for separating DF (Driving Force) vs NF (Phase Fraction)
        col_names = y_data.columns.tolist()
        df_cols = [i for i, col in enumerate(col_names) if col.startswith('DF_')]
        nf_cols = [i for i, col in enumerate(col_names) if col.startswith('NF_')]
        
        # Calculate overall RMSE and MAE on original scale (all values)
        mse_original = np.mean((test_preds_original - test_targets_original) ** 2)
        rmse = np.sqrt(mse_original)
        mae = np.mean(np.abs(test_preds_original - test_targets_original))
        
        # Calculate metrics for non-zero targets only
        # Use a small threshold to handle floating point precision
        nonzero_threshold = 1e-6
        
        # Overall non-zero metrics
        nonzero_mask = np.abs(test_targets_original) > nonzero_threshold
        if np.any(nonzero_mask):
            nonzero_errors = test_preds_original[nonzero_mask] - test_targets_original[nonzero_mask]
            rmse_nonzero = np.sqrt(np.mean(nonzero_errors ** 2))
            mae_nonzero = np.mean(np.abs(nonzero_errors))
            n_nonzero = np.sum(nonzero_mask)
        else:
            rmse_nonzero, mae_nonzero, n_nonzero = 0.0, 0.0, 0
        
        # Calculate metrics for Driving Force columns (DF_) - non-zero only
        if df_cols:
            df_preds = test_preds_original[:, df_cols]
            df_targets = test_targets_original[:, df_cols]
            df_nonzero_mask = np.abs(df_targets) > nonzero_threshold
            if np.any(df_nonzero_mask):
                df_errors = df_preds[df_nonzero_mask] - df_targets[df_nonzero_mask]
                df_rmse = np.sqrt(np.mean(df_errors ** 2))
                df_mae = np.mean(np.abs(df_errors))
                n_df_nonzero = np.sum(df_nonzero_mask)
            else:
                df_rmse, df_mae, n_df_nonzero = 0.0, 0.0, 0
        else:
            df_rmse, df_mae, n_df_nonzero = 0.0, 0.0, 0
        
        # Calculate metrics for Phase Fraction columns (NF_) - non-zero only
        if nf_cols:
            nf_preds = test_preds_original[:, nf_cols]
            nf_targets = test_targets_original[:, nf_cols]
            nf_nonzero_mask = np.abs(nf_targets) > nonzero_threshold
            if np.any(nf_nonzero_mask):
                nf_errors = nf_preds[nf_nonzero_mask] - nf_targets[nf_nonzero_mask]
                nf_rmse = np.sqrt(np.mean(nf_errors ** 2))
                nf_mae = np.mean(np.abs(nf_errors))
                n_nf_nonzero = np.sum(nf_nonzero_mask)
            else:
                nf_rmse, nf_mae, n_nf_nonzero = 0.0, 0.0, 0
        else:
            nf_rmse, nf_mae, n_nf_nonzero = 0.0, 0.0, 0
        
        print(f"Overall (all)      - RMSE: {rmse:.4f}, MAE: {mae:.4f}")
        print(f"Overall (non-zero) - RMSE: {rmse_nonzero:.4f}, MAE: {mae_nonzero:.4f}  [{n_nonzero:,} values]")
        print(f"Driving Force (DF) - RMSE: {df_rmse:.4f}, MAE: {df_mae:.4f}  [{n_df_nonzero:,} non-zero values]")
        print(f"Phase Fraction (NF) - RMSE: {nf_rmse:.4f}, MAE: {nf_mae:.4f}  [{n_nf_nonzero:,} non-zero values]")

        # Store fold results
        fold_results.append({
            'fold': test_group,
            'best_val_loss': best_val_loss,
            'test_loss': mse_original,
            'test_rmse': rmse,
            'test_mae': mae,
            'rmse_nonzero': rmse_nonzero,
            'mae_nonzero': mae_nonzero,
            'df_rmse': df_rmse,
            'df_mae': df_mae,
            'nf_rmse': nf_rmse,
            'nf_mae': nf_mae,
            'train_losses': train_losses,
            'val_losses': val_losses
        })
        
        all_test_predictions.append(torch.FloatTensor(test_preds_original))
        all_test_targets.append(torch.FloatTensor(test_targets_original))

    # Summary across all folds
    print(f"\n{'='*50}")
    print("Cross-Validation Summary (non-zero targets only)")
    print('='*50)
    avg_test_loss = np.mean([r['test_loss'] for r in fold_results])
    avg_test_rmse = np.mean([r['test_rmse'] for r in fold_results])
    avg_test_mae = np.mean([r['test_mae'] for r in fold_results])
    avg_rmse_nonzero = np.mean([r['rmse_nonzero'] for r in fold_results])
    avg_mae_nonzero = np.mean([r['mae_nonzero'] for r in fold_results])
    std_test_loss = np.std([r['test_loss'] for r in fold_results])
    
    # Separate metrics for DF and NF (already non-zero)
    avg_df_rmse = np.mean([r['df_rmse'] for r in fold_results])
    avg_df_mae = np.mean([r['df_mae'] for r in fold_results])
    avg_nf_rmse = np.mean([r['nf_rmse'] for r in fold_results])
    avg_nf_mae = np.mean([r['nf_mae'] for r in fold_results])
    
    print(f"Overall (all values):")
    print(f"  Avg Test MSE: {avg_test_loss:.4f} (+/- {std_test_loss:.4f})")
    print(f"  Avg RMSE: {avg_test_rmse:.4f}, MAE: {avg_test_mae:.4f}")
    print(f"\nOverall (non-zero only):")
    print(f"  Avg RMSE: {avg_rmse_nonzero:.4f}, MAE: {avg_mae_nonzero:.4f}")
    print(f"\nDriving Force (DF, non-zero only):")
    print(f"  Avg RMSE: {avg_df_rmse:.4f}, MAE: {avg_df_mae:.4f}")
    print(f"\nPhase Fraction (NF, non-zero only):")
    print(f"  Avg RMSE: {avg_nf_rmse:.4f}, MAE: {avg_nf_mae:.4f}")

    return {
        'fold_results': fold_results,
        'avg_test_loss': avg_test_loss,
        'avg_test_rmse': avg_test_rmse,
        'avg_test_mae': avg_test_mae,
        'avg_rmse_nonzero': avg_rmse_nonzero,
        'avg_mae_nonzero': avg_mae_nonzero,
        'avg_df_rmse': avg_df_rmse,
        'avg_df_mae': avg_df_mae,
        'avg_nf_rmse': avg_nf_rmse,
        'avg_nf_mae': avg_nf_mae,
        'all_predictions': all_test_predictions,
        'all_targets': all_test_targets
    }

In [13]:
def evaluate_parameters_DFnn(parameters, batch_size=32, epochs=1000, verbose=True):
    
    # Extract hyperparameters from parameters dict with defaults
    batch_size = parameters.get('batch_size', batch_size)
    hidden_layers = parameters.get('hidden_layers', [256, 128, 64])
    dropout_rate = parameters.get('dropout_rate', 0.2)
    dropout_type = parameters.get('dropout_type', 'standard')
    activation = parameters.get('activation', 'relu')
    use_batch_norm = parameters.get('use_batch_norm', False)
    use_layer_norm = parameters.get('use_layer_norm', False)
    weight_decay = parameters.get('weight_decay', 0.0)
    optimizer_type = parameters.get('optimizer_type', 'adam')
    lr = parameters.get('lr', 1e-3)
    early_stopping_patience = parameters.get('early_stopping_patience', 10)

    # Auto-detect device
    if torch.cuda.is_available():
        device = torch.device('cuda')
    elif torch.backends.mps.is_available():
        device = torch.device('mps')
    else:
        device = torch.device('cpu')
    print(f"Using device: {device}")

    # Copy the x and y data — use driving force targets from cell 11
    y_data = y_df.copy()
    x_data = X_combined.copy()

    # Get input and output dimensions
    input_dim = x_data.shape[1]
    output_dim = y_data.shape[1]
    print(f"Input dim: {input_dim}, Output dim: {output_dim}")

    # Store results for each fold
    fold_results = []
    all_test_predictions = []
    all_test_targets = []

    for test_group in range(5):  # 0-4 for 5 groups from KMeans
        print(f"\n{'='*50}")
        print(f"Fold {test_group}")
        print('='*50)
        
        # Get the split indexes for training and testing
        train_idx = cv_group_df['cv_group'] != test_group
        test_idx = cv_group_df['cv_group'] == test_group

        # Split the x and y data in train and test
        x_train = x_data.loc[train_idx]
        x_test = x_data.loc[test_idx]

        y_train = y_data.loc[train_idx]
        y_test = y_data.loc[test_idx]
        
        # Create train and validation data
        X_train, X_val, y_train, y_val = train_test_split(
            x_train, y_train, test_size=0.2, random_state=42
        )

        print(f"Train: {len(X_train)}, Val: {len(X_val)}, Test: {len(x_test)}")

        # Scale the x data
        scaler = StandardScaler()
        X_train_scaled = pd.DataFrame(scaler.fit_transform(X_train), columns=X_train.columns, index=X_train.index)
        X_val_scaled = pd.DataFrame(scaler.transform(X_val), columns=X_val.columns, index=X_val.index)
        x_test_scaled = pd.DataFrame(scaler.transform(x_test), columns=x_test.columns, index=x_test.index)

        # Scale the y data
        y_scaler = StandardScaler()
        y_train_scaled = pd.DataFrame(y_scaler.fit_transform(y_train), columns=y_train.columns, index=y_train.index)
        y_val_scaled = pd.DataFrame(y_scaler.transform(y_val), columns=y_val.columns, index=y_val.index)
        y_test_scaled = pd.DataFrame(y_scaler.transform(y_test), columns=y_test.columns, index=y_test.index)

        # Convert DataFrames to PyTorch tensors
        X_train_t = torch.FloatTensor(X_train_scaled.values)
        y_train_t = torch.FloatTensor(y_train_scaled.values)
        X_val_t = torch.FloatTensor(X_val_scaled.values)
        y_val_t = torch.FloatTensor(y_val_scaled.values)
        X_test_t = torch.FloatTensor(x_test_scaled.values)
        y_test_t = torch.FloatTensor(y_test_scaled.values)

        # Create TensorDatasets
        train_dataset = TensorDataset(X_train_t, y_train_t)
        val_dataset = TensorDataset(X_val_t, y_val_t)
        test_dataset = TensorDataset(X_test_t, y_test_t)

        # Create DataLoaders
        # drop_last=True for train_loader to avoid batch size of 1 (causes BatchNorm to fail)
        train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, drop_last=True)
        val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)
        test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

        # Create the DrivingForceNN model (no softmax — outputs are unconstrained real values)
        model = DrivingForceNN(
            input_dim=input_dim,
            output_dim=output_dim,
            hidden_layers=hidden_layers,
            dropout_rate=dropout_rate,
            dropout_type=dropout_type,
            activation=activation,
            use_batch_norm=use_batch_norm,
            use_layer_norm=use_layer_norm,
            weight_decay=weight_decay,
        ).to(device)

        # Get optimizer and criterion
        optimizer = model.get_optimizer(optimizer_type=optimizer_type, lr=lr)
        criterion = nn.MSELoss()

        # Training loop
        best_val_loss = float('inf')
        best_model_state = None
        patience_counter = 0
        train_losses = []
        val_losses = []

        for epoch in range(epochs):
            # Train
            train_loss = train_epoch(model, train_loader, optimizer, criterion, device)
            
            # Evaluate on validation
            val_loss, _, _ = evaluate_epoch(model, val_loader, criterion, device)
            
            train_losses.append(train_loss)
            val_losses.append(val_loss)
            
            # Track best model
            if val_loss < best_val_loss:
                best_val_loss = val_loss
                best_model_state = {k: v.cpu().clone() for k, v in model.state_dict().items()}
                patience_counter = 0
            else:
                patience_counter += 1
            
            # Verbose output
            if verbose and (epoch % 20 == 0 or epoch == epochs - 1):
                print(f"Epoch {epoch+1}/{epochs} - Train Loss: {train_loss:.6f} - Val Loss: {val_loss:.6f}")
            
            # Early stopping
            if early_stopping_patience and patience_counter >= early_stopping_patience:
                print(f"Early stopping at epoch {epoch+1}")
                break

        # Restore best model
        if best_model_state is not None:
            model.load_state_dict(best_model_state)
            model.to(device)

        # Evaluate on test set (scaled)
        test_loss_scaled, test_preds_scaled, test_targets_scaled = evaluate_epoch(model, test_loader, criterion, device)
        
        # Inverse transform predictions and targets to original scale
        test_preds_original = y_scaler.inverse_transform(test_preds_scaled.numpy())
        test_targets_original = y_scaler.inverse_transform(test_targets_scaled.numpy())
        
        # Calculate overall RMSE and MAE on original scale (all values)
        mse_original = np.mean((test_preds_original - test_targets_original) ** 2)
        rmse = np.sqrt(mse_original)
        mae = np.mean(np.abs(test_preds_original - test_targets_original))
        
        # Calculate metrics for non-zero targets only
        nonzero_threshold = 1e-6
        
        nonzero_mask = np.abs(test_targets_original) > nonzero_threshold
        if np.any(nonzero_mask):
            nonzero_errors = test_preds_original[nonzero_mask] - test_targets_original[nonzero_mask]
            rmse_nonzero = np.sqrt(np.mean(nonzero_errors ** 2))
            mae_nonzero = np.mean(np.abs(nonzero_errors))
            n_nonzero = np.sum(nonzero_mask)
        else:
            rmse_nonzero, mae_nonzero, n_nonzero = 0.0, 0.0, 0
        
        # Per-column RMSE for driving force outputs (non-zero only)
        col_names = y_data.columns.tolist()
        per_col_rmse = {}
        for ci, col in enumerate(col_names):
            col_mask = np.abs(test_targets_original[:, ci]) > nonzero_threshold
            if np.any(col_mask):
                col_errors = test_preds_original[:, ci][col_mask] - test_targets_original[:, ci][col_mask]
                per_col_rmse[col] = np.sqrt(np.mean(col_errors ** 2))
        
        print(f"Driving Force (all)      - RMSE: {rmse:.4f}, MAE: {mae:.4f}")
        print(f"Driving Force (non-zero) - RMSE: {rmse_nonzero:.4f}, MAE: {mae_nonzero:.4f}  [{n_nonzero:,} values]")

        # Store fold results
        fold_results.append({
            'fold': test_group,
            'best_val_loss': best_val_loss,
            'test_loss': mse_original,
            'test_rmse': rmse,
            'test_mae': mae,
            'rmse_nonzero': rmse_nonzero,
            'mae_nonzero': mae_nonzero,
            'per_col_rmse': per_col_rmse,
            'train_losses': train_losses,
            'val_losses': val_losses
        })
        
        all_test_predictions.append(torch.FloatTensor(test_preds_original))
        all_test_targets.append(torch.FloatTensor(test_targets_original))

    # Summary across all folds
    print(f"\n{'='*50}")
    print("Cross-Validation Summary — Driving Forces")
    print('='*50)
    avg_test_loss = np.mean([r['test_loss'] for r in fold_results])
    avg_test_rmse = np.mean([r['test_rmse'] for r in fold_results])
    avg_test_mae = np.mean([r['test_mae'] for r in fold_results])
    avg_rmse_nonzero = np.mean([r['rmse_nonzero'] for r in fold_results])
    avg_mae_nonzero = np.mean([r['mae_nonzero'] for r in fold_results])
    std_test_loss = np.std([r['test_loss'] for r in fold_results])
    
    print(f"Driving Force (all values):")
    print(f"  Avg Test MSE: {avg_test_loss:.4f} (+/- {std_test_loss:.4f})")
    print(f"  Avg RMSE: {avg_test_rmse:.4f}, MAE: {avg_test_mae:.4f}")
    print(f"\nDriving Force (non-zero only):")
    print(f"  Avg RMSE: {avg_rmse_nonzero:.4f}, MAE: {avg_mae_nonzero:.4f}")

    return {
        'fold_results': fold_results,
        'avg_test_loss': avg_test_loss,
        'avg_test_rmse': avg_test_rmse,
        'avg_test_mae': avg_test_mae,
        'avg_rmse_nonzero': avg_rmse_nonzero,
        'avg_mae_nonzero': avg_mae_nonzero,
        'all_predictions': all_test_predictions,
        'all_targets': all_test_targets
    }

In [ ]:
#test evaluate parameters for NFnn
parameters = {
    'hidden_layers': [256, 512, 1024],
    'activation': 'gelu',
    'use_batch_norm': True,
    'lr': 1e-3,
    'early_stopping_patience': 15
}
results = evaluate_parameters_NFnn(parameters)

Using device: mps
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Epoch 1/1000 - Train Loss: 0.255452 - Val Loss: 0.344018
Epoch 21/1000 - Train Loss: 0.252722 - Val Loss: 0.341859
Epoch 41/1000 - Train Loss: 0.252290 - Val Loss: 0.341576
Epoch 61/1000 - Train Loss: 0.252245 - Val Loss: 0.341517
Epoch 81/1000 - Train Loss: 0.251786 - Val Loss: 0.341334
Epoch 101/1000 - Train Loss: 0.252075 - Val Loss: 0.341304
Epoch 121/1000 - Train Loss: 0.251710 - Val Loss: 0.341210
Epoch 141/1000 - Train Loss: 0.251468 - Val Loss: 0.341111
Epoch 161/1000 - Train Loss: 0.251638 - Val Loss: 0.341095
Early stopping at epoch 163
Overall (all)      - RMSE: 0.0366, MAE: 0.0023
Overall (non-zero) - RMSE: 0.4589, MAE: 0.3844  [11,193 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4589, MAE: 0.3844  [11,193 non-zero values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Epoch 1/1000 - Train Loss: 0.237284 - Val Loss: 0.266314
Epoch 21/1000 - Train Loss: 0.234392 - Val Loss: 0.264545
Epoch 41/1000 - Train Loss: 0.234112 - Val Loss: 0.264341
Epoch 61/1000 - Train Loss: 0.234017 - Val Loss: 0.264262
Early stopping at epoch 72
Overall (all)      - RMSE: 0.0251, MAE: 0.0016
Overall (non-zero) - RMSE: 0.3871, MAE: 0.2981  [27,977 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.3871, MAE: 0.2981  [27,977 non-zero values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Epoch 1/1000 - Train Loss: 0.273027 - Val Loss: 0.288501
Epoch 21/1000 - Train Loss: 0.269912 - Val Loss: 0.286257
Epoch 41/1000 - Train Loss: 0.269628 - Val Loss: 0.285881
Epoch 61/1000 - Train Loss: 0.269541 - Val Loss: 0.285810
Epoch 81/1000 - Train Loss: 0.269324 - Val Loss: 0.285603
Epoch 101/1000 - Train Loss: 0.269053 - Val Loss: 0.285610
Epoch 121/1000 - Train Loss: 0.269119 - Val Loss: 0.285423
Epoch 141/1000 - Train Loss: 0.269087 - Val Loss: 0.285430
Epoch 161/1000 - Train Loss: 0.269021 - Val Loss: 0.285365
Epoch 181/1000 - Train Loss: 0.268886 - Val Loss: 0.285279
Epoch 201/1000 - Train Loss: 0.268772 - Val Loss: 0.285286
Epoch 221/1000 - Train Loss: 0.268801 - Val Loss: 0.285200
Epoch 241/1000 - Train Loss: 0.268737 - Val Loss: 0.285220
Early stopping at epoch 242
Overall (all)      - RMSE: 0.0269, MAE: 0.0016
Overall (non-zero) - RMSE: 0.4457, MAE: 0.3458  [10,856 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4457, MAE: 0.3458  [10,856 non-zero values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Epoch 1/1000 - Train Loss: 0.243464 - Val Loss: 0.258784
Epoch 21/1000 - Train Loss: 0.240038 - Val Loss: 0.257027
Epoch 41/1000 - Train Loss: 0.240450 - Val Loss: 0.256896

KeyboardInterrupt:

In [21]:
# Define architecture presets mapping (all expanding for large output dim)
ARCHITECTURE_PRESETS = {
    # Single layer - direct expansion
    "single_256": [256],
    "single_512": [512],
    "single_1024": [1024],
    "single_2048": [2048],
    # Two layers - expanding
    "expand_2L_small": [256, 512],
    "expand_2L_medium": [512, 1024],
    "expand_2L_large": [1024, 2048],
    "expand_2L_xlarge": [512, 2048],
    # Three layers - expanding
    "expand_3L_small": [256, 512, 1024],
    "expand_3L_medium": [512, 1024, 2048],
    "expand_3L_large": [256, 1024, 2048],
    "expand_3L_gradual": [384, 768, 1536],
    # Four layers - expanding
    "expand_4L_small": [256, 512, 1024, 2048],
    "expand_4L_medium": [512, 768, 1024, 2048],
    "expand_4L_large": [256, 512, 1024, 4096],
    # Constant width (also good for large outputs)
    "constant_512": [512, 512],
    "constant_1024": [1024, 1024],
    "constant_2048": [2048, 2048],
    "constant_1024_3L": [1024, 1024, 1024],
}

ax_client = AxClient()
ax_client.create_experiment(
    name="NN opt NFnn f(T) Calphed",
    parameters=[
        {
            "name": "architecture",
            "type": "choice",
            "values": list(ARCHITECTURE_PRESETS.keys()),
            "is_ordered": False,
        },
        {
            "name": "dropout_rate",
            "type": "range",
            "bounds": [0.0, 0.5],
        },
        {
            "name": "activation",
            "type": "choice",
            "values": ["relu", "leaky_relu", "elu", "selu", "gelu"],
        },
        {
            "name": "normalization",
            "type": "choice",
            "values": ["none", "batch_norm", "layer_norm"],
        },
        {
            "name": "weight_decay",
            "type": "range",
            "bounds": [1e-6, 1e-2],
            "log_scale": True,
        },
        {
            "name": "lr",
            "type": "range",
            "bounds": [1e-5, 1e-2],
            "log_scale": True,
        },
        {
            "name": "optimizer_type",
            "type": "choice",
            "values": ["adam", "adamw"],
        },
        {
            "name": "batch_size",
            "type": "choice",
            "values": [32, 64, 128, 256],
        },
        {
            "name": "early_stopping_patience",
            "type": "range",
            "bounds": [10, 50],
            "value_type": "int",
        },
    ],
    objectives={"avg_rmse_nonzero": ObjectiveProperties(minimize=True)}
)

def evaluate_for_ax(parameterization):
    """Wrapper to convert Ax parameters to evaluate_parameters_NFnn format."""
    # Get hidden_layers from architecture preset
    architecture = parameterization["architecture"]
    hidden_layers = ARCHITECTURE_PRESETS[architecture]
    
    # Handle normalization choice
    normalization = parameterization["normalization"]
    use_batch_norm = normalization == "batch_norm"
    use_layer_norm = normalization == "layer_norm"
    
    # Handle dropout type based on activation
    activation = parameterization["activation"]
    dropout_type = "alpha" if activation == "selu" else "standard"
    
    # Build parameters dict
    parameters = {
        "hidden_layers": hidden_layers,
        "dropout_rate": parameterization["dropout_rate"],
        "dropout_type": dropout_type,
        "activation": activation,
        "use_batch_norm": use_batch_norm,
        "use_layer_norm": use_layer_norm,
        "weight_decay": parameterization["weight_decay"],
        "lr": parameterization["lr"],
        "optimizer_type": parameterization["optimizer_type"],
        "batch_size": parameterization["batch_size"],
        "early_stopping_patience": parameterization["early_stopping_patience"],
    }
    
    # Run evaluation using NFnn function
    results = evaluate_parameters_NFnn(parameters, verbose=False)
    
    # Calculate SEM (Standard Error of the Mean) from fold results
    # SEM = std / sqrt(n_folds)
    rmse_nonzero_values = [r["rmse_nonzero"] for r in results["fold_results"]]
    mean_rmse_nonzero = np.mean(rmse_nonzero_values)
    std_rmse_nonzero = np.std(rmse_nonzero_values, ddof=1)  # ddof=1 for sample std
    sem_rmse_nonzero = std_rmse_nonzero / np.sqrt(len(rmse_nonzero_values))
    
    # Return the objective with proper SEM for Bayesian optimization
    return {"avg_rmse_nonzero": (mean_rmse_nonzero, sem_rmse_nonzero)}

[INFO 02-11 08:57:18] ax.service.ax_client: Starting optimization with verbose logging. To disable logging, set the `verbose_logging` argument to `False`. Note that float values in the logs are rounded to 6 decimal points.
[INFO 02-11 08:57:18] ax.service.utils.instantiation: Inferred value type of ParameterType.STRING for parameter architecture. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\service\utils\instantiation.py:258: AxParameterWarning: `sort_values` is not specified for `ChoiceParameter` "architecture". Defaulting to `False` for parameters of `ParameterType` STRING. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  return ChoiceParameter(
[INFO 02-11 08:57:18] ax.service.utils.instantiation: Inferred value type of ParameterType.FLOAT for parameter dropout_rate. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
[INFO 02-11 08:57:18] ax.service.utils.instantiation: Inferred value type of ParameterType.STRING for parameter activation. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\service\utils\instantiation.py:258: AxParameterWarning: `is_ordered` is not specified for `ChoiceParameter` "activation". Defaulting to `False`  since the parameter is a string with more than 2 choices.. To override this behavior (or avoid this warning), specify `is_ordered` during `ChoiceParameter` construction. Note that choice parameters with exactly 2 choices are always considered ordered and that the user-supplied `is_ordered` has no effect in this particular case.
  return ChoiceParameter(
c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\service\utils\instantiation.py:258: AxParameterWarning: `sort_values` is not specified for `ChoiceParameter` "activation". Defaulting to `False` for parameters of `ParameterType` STRING. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  return ChoiceParameter(
[INFO 02-11 08:57:18] ax.service.utils.instantiation: Inferred value type of ParameterType.STRING for parameter normalization. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\service\utils\instantiation.py:258: AxParameterWarning: `is_ordered` is not specified for `ChoiceParameter` "normalization". Defaulting to `False`  since the parameter is a string with more than 2 choices.. To override this behavior (or avoid this warning), specify `is_ordered` during `ChoiceParameter` construction. Note that choice parameters with exactly 2 choices are always considered ordered and that the user-supplied `is_ordered` has no effect in this particular case.
  return ChoiceParameter(
c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\service\utils\instantiation.py:258: AxParameterWarning: `sort_values` is not specified for `ChoiceParameter` "normalization". Defaulting to `False` for parameters of `ParameterType` STRING. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  return ChoiceParameter(
[INFO 02-11 08:57:18] ax.service.utils.instantiation: Inferred value type of ParameterType.FLOAT for parameter weight_decay. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
[INFO 02-11 08:57:18] ax.service.utils.instantiation: Inferred value type of ParameterType.FLOAT for parameter lr. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
[INFO 02-11 08:57:18] ax.service.utils.instantiation: Inferred value type of ParameterType.STRING for parameter optimizer_type. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\service\utils\instantiation.py:258: AxParameterWarning: `is_ordered` is not specified for `ChoiceParameter` "optimizer_type". Defaulting to `True`  since there are exactly two choices.. To override this behavior (or avoid this warning), specify `is_ordered` during `ChoiceParameter` construction. Note that choice parameters with exactly 2 choices are always considered ordered and that the user-supplied `is_ordered` has no effect in this particular case.
  return ChoiceParameter(
c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\service\utils\instantiation.py:258: AxParameterWarning: `sort_values` is not specified for `ChoiceParameter` "optimizer_type". Defaulting to `False` for parameters of `ParameterType` STRING. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  return ChoiceParameter(
[INFO 02-11 08:57:18] ax.service.utils.instantiation: Inferred value type of ParameterType.INT for parameter batch_size. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\service\utils\instantiation.py:258: AxParameterWarning: `is_ordered` is not specified for `ChoiceParameter` "batch_size". Defaulting to `True`  since the parameter is not of type string.. To override this behavior (or avoid this warning), specify `is_ordered` during `ChoiceParameter` construction. Note that choice parameters with exactly 2 choices are always considered ordered and that the user-supplied `is_ordered` has no effect in this particular case.
  return ChoiceParameter(
c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\service\utils\instantiation.py:258: AxParameterWarning: `sort_values` is not specified for `ChoiceParameter` "batch_size". Defaulting to `True` for parameters of `ParameterType` INT. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  return ChoiceParameter(
[INFO 02-11 08:57:18] ax.service.utils.instantiation: Created search space: SearchSpace(parameters=[ChoiceParameter(name='architecture', parameter_type=STRING, values=['single_256', 'single_512', 'single_1024', 'single_2048', 'expand_2L_small', 'expand_2L_medium', 'expand_2L_large', 'expand_2L_xlarge', 'expand_3L_small', 'expand_3L_medium', 'expand_3L_large', 'expand_3L_gradual', 'expand_4L_small', 'expand_4L_medium', 'expand_4L_large', 'constant_512', 'constant_1024', 'constant_2048', 'constant_1024_3L'], is_ordered=False, sort_values=False), RangeParameter(name='dropout_rate', parameter_type=FLOAT, range=[0.0, 0.5]), ChoiceParameter(name='activation', parameter_type=STRING, values=['relu', 'leaky_relu', 'elu', 'selu', 'gelu'], is_ordered=False, sort_values=False), ChoiceParameter(name='normalization', parameter_type=STRING, values=['none', 'batch_norm', 'layer_norm'], is_ordered=False, sort_values=False), RangeParameter(name='weight_decay', parameter_type=FLOAT, range=[1e-06, 0.01], log_scale=True), RangeParameter(name='lr', parameter_type=FLOAT, range=[1e-05, 0.01], log_scale=True), ChoiceParameter(name='optimizer_type', parameter_type=STRING, values=['adam', 'adamw'], is_ordered=True, sort_values=False), ChoiceParameter(name='batch_size', parameter_type=INT, values=[32, 64, 128, 256], is_ordered=True, sort_values=True), RangeParameter(name='early_stopping_patience', parameter_type=INT, range=[10, 50])], parameter_constraints=[]).
[INFO 02-11 08:57:18] ax.modelbridge.dispatch_utils: Using Models.BOTORCH_MODULAR since there is at least one ordered parameter and there are fewer than 33 choices for unordered parameters.
[INFO 02-11 08:57:18] ax.modelbridge.dispatch_utils: Calculating the number of remaining initialization trials based on num_initialization_trials=None max_initialization_trials=None num_tunable_parameters=9 num_trials=None use_batch_trials=False
[INFO 02-11 08:57:18] ax.modelbridge.dispatch_utils: calculated num_initialization_trials=18
[INFO 02-11 08:57:18] ax.modelbridge.dispatch_utils: num_completed_initialization_trials=0 num_remaining_initialization_trials=18
[INFO 02-11 08:57:18] ax.modelbridge.dispatch_utils: `verbose`, `disable_progbar`, and `jit_compile` are not yet supported when using `choose_generation_strategy` with ModularBoTorchModel, dropping these arguments.
[INFO 02-11 08:57:18] ax.modelbridge.dispatch_utils: Using Bayesian Optimization generation strategy: GenerationStrategy(name='Sobol+BoTorch', steps=[Sobol for 18 trials, BoTorch for subsequent trials]). Iterations after 18 will take longer to generate due to model-fitting.

In [ ]:
# Run the Bayesian optimization loop
target_trials= 100
SAVE_PATH = r"Ax_checkpoints/ax_client_NN_NF(T)_checkpoint.json"

#load the partially completed AxClient from the checkpoint file and continue
ax_client = AxClient().load_from_json_file(SAVE_PATH)
completed_trials = len(ax_client.experiment.trials)

remaining_trials = target_trials - completed_trials

print(f"Loaded {completed_trials} completed trials from checkpoint")
print(f"Remaining trials to reach {target_trials}: {remaining_trials}")

if remaining_trials > 0:
    for i in range(remaining_trials):
        current_trial = completed_trials + i + 1
        print(f"\n{'='*60}")
        print(f"Trial {current_trial}/{target_trials}")
        print('='*60)
        
        parameters, trial_index = ax_client.get_next_trial()
        print(f"Parameters: {parameters}")
        
        try:
            result = evaluate_for_ax(parameters)
            ax_client.complete_trial(trial_index=trial_index, raw_data=result)
            print(f"Result: Non-zero RMSE = {result['avg_rmse_nonzero'][0]:.4f}")
        except Exception as e:
            print(f"Trial failed: {e}")
            ax_client.log_trial_failure(trial_index=trial_index)
        
        # Save checkpoint after each trial
        ax_client.save_to_json_file(SAVE_PATH)
        print(f"Checkpoint saved to {SAVE_PATH}")

# Get best parameters
best_parameters, values = ax_client.get_best_parameters()
print(f"\n{'='*60}")
print("OPTIMIZATION COMPLETE")
print('='*60)
print(f"Best parameters: {best_parameters}")
print(f"Best Non-zero RMSE: {values[0]['avg_rmse_nonzero']:.4f}")

c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\modelbridge\cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 02-11 08:57:24] ax.service.ax_client: Generated new trial 69 with parameters {'dropout_rate': 0.236128, 'weight_decay': 5e-06, 'lr': 0.005613, 'optimizer_type': 'adamw', 'batch_size': 256, 'early_stopping_patience': 39, 'architecture': 'single_256', 'activation': 'relu', 'normalization': 'none'} using model Sobol.

============================================================
Trial 1/32
============================================================
Parameters: {'dropout_rate': 0.2361278384923935, 'weight_decay': 5.245494132389832e-06, 'lr': 0.0056128659217602826, 'optimizer_type': 'adamw', 'batch_size': 256, 'early_stopping_patience': 39, 'architecture': 'single_256', 'activation': 'relu', 'normalization': 'none'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 50
Overall (all)      - RMSE: 0.0251, MAE: 0.0014
Overall (non-zero) - RMSE: 0.4624, MAE: 0.3642  [11,193 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4624, MAE: 0.3642  [11,193 non-zero values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 106
Overall (all)      - RMSE: 0.0241, MAE: 0.0014
Overall (non-zero) - RMSE: 0.3865, MAE: 0.2917  [27,977 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.3865, MAE: 0.2917  [27,977 non-zero values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 101
Overall (all)      - RMSE: 0.0271, MAE: 0.0016
Overall (non-zero) - RMSE: 0.4430, MAE: 0.3385  [10,856 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4430, MAE: 0.3385  [10,856 non-zero values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 84
Overall (all)      - RMSE: 0.0223, MAE: 0.0014
Overall (non-zero) - RMSE: 0.3230, MAE: 0.2496  [22,254 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.3230, MAE: 0.2496  [22,254 non-zero values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 114
Overall (all)      - RMSE: 0.0169, MAE: 0.0011
Overall (non-zero) - RMSE: 0.3507, MAE: 0.2764  [6,176 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.3507, MAE: 0.2764  [6,176 non-zero values]

==================================================
Cross-Validation Summary (non-zero targets only)
==================================================
Overall (all values):
  Avg Test MSE: 0.0005 (+/- 0.0002)
  Avg RMSE: 0.0231, MAE: 0.0014

Overall (non-zero only):
  Avg RMSE: 0.3931, MAE: 0.3041

Driving Force (DF, non-zero only):
  Avg RMSE: 0.0000, MAE: 0.0000

Phase Fraction (NF, non-zero only):
  Avg RMSE: 0.3931, MAE: 0.3041

[INFO 02-11 09:03:06] ax.service.ax_client: Completed trial 69 with data: {'avg_rmse_nonzero': (np.float32(0.39311767), np.float64(0.026503))}.
[INFO 02-11 09:03:06] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_Phase(T)_checkpoint.json`.
c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\modelbridge\cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 02-11 09:03:06] ax.service.ax_client: Generated new trial 70 with parameters {'dropout_rate': 0.363807, 'weight_decay': 0.00117, 'lr': 8.6e-05, 'optimizer_type': 'adam', 'batch_size': 64, 'early_stopping_patience': 23, 'architecture': 'single_512', 'activation': 'gelu', 'normalization': 'batch_norm'} using model Sobol.

Result: Non-zero RMSE = 0.3931
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_Phase(T)_checkpoint.json

============================================================
Trial 2/32
============================================================
Parameters: {'dropout_rate': 0.3638072586618364, 'weight_decay': 0.0011697226884563882, 'lr': 8.599836076315322e-05, 'optimizer_type': 'adam', 'batch_size': 64, 'early_stopping_patience': 23, 'architecture': 'single_512', 'activation': 'gelu', 'normalization': 'batch_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 28
Overall (all)      - RMSE: 0.0245, MAE: 0.0024
Overall (non-zero) - RMSE: 0.4907, MAE: 0.4204  [11,193 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4907, MAE: 0.4204  [11,193 non-zero values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 30
Overall (all)      - RMSE: 0.0236, MAE: 0.0024
Overall (non-zero) - RMSE: 0.4119, MAE: 0.3323  [27,977 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4119, MAE: 0.3323  [27,977 non-zero values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 28
Overall (all)      - RMSE: 0.0263, MAE: 0.0025
Overall (non-zero) - RMSE: 0.4733, MAE: 0.3927  [10,856 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4733, MAE: 0.3927  [10,856 non-zero values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 25
Overall (all)      - RMSE: 0.0226, MAE: 0.0024
Overall (non-zero) - RMSE: 0.3348, MAE: 0.2655  [22,254 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.3348, MAE: 0.2655  [22,254 non-zero values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 28
Overall (all)      - RMSE: 0.0193, MAE: 0.0021
Overall (non-zero) - RMSE: 0.4302, MAE: 0.4041  [6,176 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4302, MAE: 0.4041  [6,176 non-zero values]

==================================================
Cross-Validation Summary (non-zero targets only)
==================================================
Overall (all values):
  Avg Test MSE: 0.0005 (+/- 0.0001)
  Avg RMSE: 0.0233, MAE: 0.0024

Overall (non-zero only):
  Avg RMSE: 0.4282, MAE: 0.3630

Driving Force (DF, non-zero only):
  Avg RMSE: 0.0000, MAE: 0.0000

Phase Fraction (NF, non-zero only):
  Avg RMSE: 0.4282, MAE: 0.3630

[INFO 02-11 09:06:25] ax.service.ax_client: Completed trial 70 with data: {'avg_rmse_nonzero': (np.float32(0.42817968), np.float64(0.027335))}.
[INFO 02-11 09:06:25] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_Phase(T)_checkpoint.json`.
c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\modelbridge\cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 02-11 09:06:25] ax.service.ax_client: Generated new trial 71 with parameters {'dropout_rate': 0.107884, 'weight_decay': 7.4e-05, 'lr': 1.5e-05, 'optimizer_type': 'adamw', 'batch_size': 128, 'early_stopping_patience': 43, 'architecture': 'expand_4L_large', 'activation': 'leaky_relu', 'normalization': 'layer_norm'} using model Sobol.

Result: Non-zero RMSE = 0.4282
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_Phase(T)_checkpoint.json

============================================================
Trial 3/32
============================================================
Parameters: {'dropout_rate': 0.10788377514109015, 'weight_decay': 7.37751887430557e-05, 'lr': 1.4538089416445846e-05, 'optimizer_type': 'adamw', 'batch_size': 128, 'early_stopping_patience': 43, 'architecture': 'expand_4L_large', 'activation': 'leaky_relu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 414
Overall (all)      - RMSE: 0.0254, MAE: 0.0014
Overall (non-zero) - RMSE: 0.4522, MAE: 0.3492  [11,193 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4522, MAE: 0.3492  [11,193 non-zero values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 476
Overall (all)      - RMSE: 0.0239, MAE: 0.0014
Overall (non-zero) - RMSE: 0.3796, MAE: 0.2829  [27,977 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.3796, MAE: 0.2829  [27,977 non-zero values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 232
Overall (all)      - RMSE: 0.0268, MAE: 0.0016
Overall (non-zero) - RMSE: 0.4468, MAE: 0.3452  [10,856 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4468, MAE: 0.3452  [10,856 non-zero values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 537
Overall (all)      - RMSE: 0.0230, MAE: 0.0015
Overall (non-zero) - RMSE: 0.3275, MAE: 0.2608  [22,254 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.3275, MAE: 0.2608  [22,254 non-zero values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 749

[INFO 02-11 10:16:00] ax.service.ax_client: Completed trial 71 with data: {'avg_rmse_nonzero': (np.float32(0.3809546), np.float64(0.030859))}.
[INFO 02-11 10:16:00] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_Phase(T)_checkpoint.json`.

Overall (all)      - RMSE: 0.0165, MAE: 0.0010
Overall (non-zero) - RMSE: 0.2987, MAE: 0.2127  [6,176 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.2987, MAE: 0.2127  [6,176 non-zero values]

==================================================
Cross-Validation Summary (non-zero targets only)
==================================================
Overall (all values):
  Avg Test MSE: 0.0005 (+/- 0.0002)
  Avg RMSE: 0.0231, MAE: 0.0014

Overall (non-zero only):
  Avg RMSE: 0.3810, MAE: 0.2902

Driving Force (DF, non-zero only):
  Avg RMSE: 0.0000, MAE: 0.0000

Phase Fraction (NF, non-zero only):
  Avg RMSE: 0.3810, MAE: 0.2902
Result: Non-zero RMSE = 0.3810
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_Phase(T)_checkpoint.json

============================================================
Trial 4/32
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\modelbridge\cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 02-11 10:16:01] ax.service.ax_client: Generated new trial 72 with parameters {'dropout_rate': 0.479719, 'weight_decay': 0.000292, 'lr': 0.000955, 'optimizer_type': 'adam', 'batch_size': 32, 'early_stopping_patience': 17, 'architecture': 'expand_2L_large', 'activation': 'selu', 'normalization': 'batch_norm'} using model Sobol.

Parameters: {'dropout_rate': 0.479719300288707, 'weight_decay': 0.00029165141651438036, 'lr': 0.0009553069924217613, 'optimizer_type': 'adam', 'batch_size': 32, 'early_stopping_patience': 17, 'architecture': 'expand_2L_large', 'activation': 'selu', 'normalization': 'batch_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 18
Overall (all)      - RMSE: 0.0245, MAE: 0.0024
Overall (non-zero) - RMSE: 0.4907, MAE: 0.4203  [11,193 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4907, MAE: 0.4203  [11,193 non-zero values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 18
Overall (all)      - RMSE: 0.0236, MAE: 0.0023
Overall (non-zero) - RMSE: 0.4120, MAE: 0.3324  [27,977 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4120, MAE: 0.3324  [27,977 non-zero values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 18
Overall (all)      - RMSE: 0.0263, MAE: 0.0023
Overall (non-zero) - RMSE: 0.4734, MAE: 0.3928  [10,856 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4734, MAE: 0.3928  [10,856 non-zero values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 69
Overall (all)      - RMSE: 0.0226, MAE: 0.0024
Overall (non-zero) - RMSE: 0.3347, MAE: 0.2655  [22,254 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.3347, MAE: 0.2655  [22,254 non-zero values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 22

[INFO 02-11 10:28:28] ax.service.ax_client: Completed trial 72 with data: {'avg_rmse_nonzero': (np.float32(0.42819148), np.float64(0.027336))}.
[INFO 02-11 10:28:28] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_Phase(T)_checkpoint.json`.

Overall (all)      - RMSE: 0.0193, MAE: 0.0021
Overall (non-zero) - RMSE: 0.4302, MAE: 0.4041  [6,176 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4302, MAE: 0.4041  [6,176 non-zero values]

==================================================
Cross-Validation Summary (non-zero targets only)
==================================================
Overall (all values):
  Avg Test MSE: 0.0005 (+/- 0.0001)
  Avg RMSE: 0.0233, MAE: 0.0023

Overall (non-zero only):
  Avg RMSE: 0.4282, MAE: 0.3630

Driving Force (DF, non-zero only):
  Avg RMSE: 0.0000, MAE: 0.0000

Phase Fraction (NF, non-zero only):
  Avg RMSE: 0.4282, MAE: 0.3630
Result: Non-zero RMSE = 0.4282
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_Phase(T)_checkpoint.json

============================================================
Trial 5/32
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\modelbridge\cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 02-11 10:28:28] ax.service.ax_client: Generated new trial 73 with parameters {'dropout_rate': 0.138612, 'weight_decay': 3e-06, 'lr': 0.002044, 'optimizer_type': 'adamw', 'batch_size': 256, 'early_stopping_patience': 12, 'architecture': 'expand_2L_small', 'activation': 'relu', 'normalization': 'layer_norm'} using model Sobol.

Parameters: {'dropout_rate': 0.13861155742779374, 'weight_decay': 3.043839590776139e-06, 'lr': 0.00204411175976148, 'optimizer_type': 'adamw', 'batch_size': 256, 'early_stopping_patience': 12, 'architecture': 'expand_2L_small', 'activation': 'relu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 79
Overall (all)      - RMSE: 0.0253, MAE: 0.0015
Overall (non-zero) - RMSE: 0.4654, MAE: 0.3705  [11,193 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4654, MAE: 0.3705  [11,193 non-zero values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 262
Overall (all)      - RMSE: 0.0237, MAE: 0.0015
Overall (non-zero) - RMSE: 0.3798, MAE: 0.2871  [27,977 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.3798, MAE: 0.2871  [27,977 non-zero values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 72
Overall (all)      - RMSE: 0.0277, MAE: 0.0016
Overall (non-zero) - RMSE: 0.4443, MAE: 0.3358  [10,856 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4443, MAE: 0.3358  [10,856 non-zero values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 29
Overall (all)      - RMSE: 0.0223, MAE: 0.0014
Overall (non-zero) - RMSE: 0.3115, MAE: 0.2372  [22,254 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.3115, MAE: 0.2372  [22,254 non-zero values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 92

[INFO 02-11 10:40:49] ax.service.ax_client: Completed trial 73 with data: {'avg_rmse_nonzero': (np.float32(0.39214575), np.float64(0.028101))}.
[INFO 02-11 10:40:49] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_Phase(T)_checkpoint.json`.

Overall (all)      - RMSE: 0.0170, MAE: 0.0011
Overall (non-zero) - RMSE: 0.3598, MAE: 0.2926  [6,176 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.3598, MAE: 0.2926  [6,176 non-zero values]

==================================================
Cross-Validation Summary (non-zero targets only)
==================================================
Overall (all values):
  Avg Test MSE: 0.0006 (+/- 0.0002)
  Avg RMSE: 0.0232, MAE: 0.0014

Overall (non-zero only):
  Avg RMSE: 0.3921, MAE: 0.3046

Driving Force (DF, non-zero only):
  Avg RMSE: 0.0000, MAE: 0.0000

Phase Fraction (NF, non-zero only):
  Avg RMSE: 0.3921, MAE: 0.3046
Result: Non-zero RMSE = 0.3921
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_Phase(T)_checkpoint.json

============================================================
Trial 6/32
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\modelbridge\cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 02-11 10:40:49] ax.service.ax_client: Generated new trial 74 with parameters {'dropout_rate': 0.258494, 'weight_decay': 0.006668, 'lr': 0.000134, 'optimizer_type': 'adam', 'batch_size': 64, 'early_stopping_patience': 48, 'architecture': 'single_2048', 'activation': 'elu', 'normalization': 'batch_norm'} using model Sobol.

Parameters: {'dropout_rate': 0.2584940935485065, 'weight_decay': 0.006667572625007691, 'lr': 0.00013356812975099362, 'optimizer_type': 'adam', 'batch_size': 64, 'early_stopping_patience': 48, 'architecture': 'single_2048', 'activation': 'elu', 'normalization': 'batch_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 49
Overall (all)      - RMSE: 0.0245, MAE: 0.0024
Overall (non-zero) - RMSE: 0.4907, MAE: 0.4204  [11,193 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4907, MAE: 0.4204  [11,193 non-zero values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 49
Overall (all)      - RMSE: 0.0236, MAE: 0.0024
Overall (non-zero) - RMSE: 0.4119, MAE: 0.3323  [27,977 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4119, MAE: 0.3323  [27,977 non-zero values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 49
Overall (all)      - RMSE: 0.0263, MAE: 0.0025
Overall (non-zero) - RMSE: 0.4733, MAE: 0.3927  [10,856 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4733, MAE: 0.3927  [10,856 non-zero values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 49
Overall (all)      - RMSE: 0.0226, MAE: 0.0024
Overall (non-zero) - RMSE: 0.3348, MAE: 0.2655  [22,254 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.3348, MAE: 0.2655  [22,254 non-zero values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 49

[INFO 02-11 10:52:15] ax.service.ax_client: Completed trial 74 with data: {'avg_rmse_nonzero': (np.float32(0.42817646), np.float64(0.027337))}.
[INFO 02-11 10:52:15] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_Phase(T)_checkpoint.json`.

Overall (all)      - RMSE: 0.0193, MAE: 0.0021
Overall (non-zero) - RMSE: 0.4302, MAE: 0.4041  [6,176 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4302, MAE: 0.4041  [6,176 non-zero values]

==================================================
Cross-Validation Summary (non-zero targets only)
==================================================
Overall (all values):
  Avg Test MSE: 0.0005 (+/- 0.0001)
  Avg RMSE: 0.0233, MAE: 0.0024

Overall (non-zero only):
  Avg RMSE: 0.4282, MAE: 0.3630

Driving Force (DF, non-zero only):
  Avg RMSE: 0.0000, MAE: 0.0000

Phase Fraction (NF, non-zero only):
  Avg RMSE: 0.4282, MAE: 0.3630
Result: Non-zero RMSE = 0.4282
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_Phase(T)_checkpoint.json

============================================================
Trial 7/32
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\modelbridge\cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 02-11 10:52:15] ax.service.ax_client: Generated new trial 75 with parameters {'dropout_rate': 0.017831, 'weight_decay': 1.3e-05, 'lr': 2.5e-05, 'optimizer_type': 'adamw', 'batch_size': 128, 'early_stopping_patience': 26, 'architecture': 'constant_2048', 'activation': 'leaky_relu', 'normalization': 'none'} using model Sobol.

Parameters: {'dropout_rate': 0.017831246834248304, 'weight_decay': 1.3059426599263796e-05, 'lr': 2.5324244429837712e-05, 'optimizer_type': 'adamw', 'batch_size': 128, 'early_stopping_patience': 26, 'architecture': 'constant_2048', 'activation': 'leaky_relu', 'normalization': 'none'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 291
Overall (all)      - RMSE: 0.0255, MAE: 0.0014
Overall (non-zero) - RMSE: 0.4555, MAE: 0.3515  [11,193 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4555, MAE: 0.3515  [11,193 non-zero values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 268
Overall (all)      - RMSE: 0.0241, MAE: 0.0014
Overall (non-zero) - RMSE: 0.3821, MAE: 0.2832  [27,977 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.3821, MAE: 0.2832  [27,977 non-zero values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 229
Overall (all)      - RMSE: 0.0265, MAE: 0.0015
Overall (non-zero) - RMSE: 0.4414, MAE: 0.3408  [10,856 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4414, MAE: 0.3408  [10,856 non-zero values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 183
Overall (all)      - RMSE: 0.0225, MAE: 0.0014
Overall (non-zero) - RMSE: 0.3109, MAE: 0.2332  [22,254 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.3109, MAE: 0.2332  [22,254 non-zero values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 317

[INFO 02-11 11:30:03] ax.service.ax_client: Completed trial 75 with data: {'avg_rmse_nonzero': (np.float32(0.38183847), np.float64(0.029937))}.
[INFO 02-11 11:30:03] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_Phase(T)_checkpoint.json`.

Overall (all)      - RMSE: 0.0169, MAE: 0.0010
Overall (non-zero) - RMSE: 0.3192, MAE: 0.2341  [6,176 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.3192, MAE: 0.2341  [6,176 non-zero values]

==================================================
Cross-Validation Summary (non-zero targets only)
==================================================
Overall (all values):
  Avg Test MSE: 0.0005 (+/- 0.0001)
  Avg RMSE: 0.0231, MAE: 0.0014

Overall (non-zero only):
  Avg RMSE: 0.3818, MAE: 0.2886

Driving Force (DF, non-zero only):
  Avg RMSE: 0.0000, MAE: 0.0000

Phase Fraction (NF, non-zero only):
  Avg RMSE: 0.3818, MAE: 0.2886
Result: Non-zero RMSE = 0.3818
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_Phase(T)_checkpoint.json

============================================================
Trial 8/32
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\modelbridge\cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 02-11 11:30:03] ax.service.ax_client: Generated new trial 76 with parameters {'dropout_rate': 0.397464, 'weight_decay': 0.000507, 'lr': 0.000385, 'optimizer_type': 'adam', 'batch_size': 32, 'early_stopping_patience': 32, 'architecture': 'expand_4L_medium', 'activation': 'elu', 'normalization': 'layer_norm'} using model Sobol.

Parameters: {'dropout_rate': 0.3974638939835131, 'weight_decay': 0.0005071393721451422, 'lr': 0.0003849436076730768, 'optimizer_type': 'adam', 'batch_size': 32, 'early_stopping_patience': 32, 'architecture': 'expand_4L_medium', 'activation': 'elu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 34
Overall (all)      - RMSE: 0.0245, MAE: 0.0024
Overall (non-zero) - RMSE: 0.4907, MAE: 0.4204  [11,193 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4907, MAE: 0.4204  [11,193 non-zero values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 33
Overall (all)      - RMSE: 0.0236, MAE: 0.0021
Overall (non-zero) - RMSE: 0.4120, MAE: 0.3324  [27,977 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4120, MAE: 0.3324  [27,977 non-zero values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 33
Overall (all)      - RMSE: 0.0263, MAE: 0.0025
Overall (non-zero) - RMSE: 0.4733, MAE: 0.3926  [10,856 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4733, MAE: 0.3926  [10,856 non-zero values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 34
Overall (all)      - RMSE: 0.0226, MAE: 0.0024
Overall (non-zero) - RMSE: 0.3347, MAE: 0.2655  [22,254 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.3347, MAE: 0.2655  [22,254 non-zero values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 34

[INFO 02-11 11:46:48] ax.service.ax_client: Completed trial 76 with data: {'avg_rmse_nonzero': (np.float32(0.42819062), np.float64(0.027332))}.
[INFO 02-11 11:46:48] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_Phase(T)_checkpoint.json`.

Overall (all)      - RMSE: 0.0193, MAE: 0.0021
Overall (non-zero) - RMSE: 0.4302, MAE: 0.4041  [6,176 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4302, MAE: 0.4041  [6,176 non-zero values]

==================================================
Cross-Validation Summary (non-zero targets only)
==================================================
Overall (all values):
  Avg Test MSE: 0.0005 (+/- 0.0001)
  Avg RMSE: 0.0233, MAE: 0.0023

Overall (non-zero only):
  Avg RMSE: 0.4282, MAE: 0.3630

Driving Force (DF, non-zero only):
  Avg RMSE: 0.0000, MAE: 0.0000

Phase Fraction (NF, non-zero only):
  Avg RMSE: 0.4282, MAE: 0.3630
Result: Non-zero RMSE = 0.4282
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_Phase(T)_checkpoint.json

============================================================
Trial 9/32
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\modelbridge\cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 02-11 11:46:48] ax.service.ax_client: Generated new trial 77 with parameters {'dropout_rate': 0.086082, 'weight_decay': 0.003489, 'lr': 4.5e-05, 'optimizer_type': 'adamw', 'batch_size': 32, 'early_stopping_patience': 37, 'architecture': 'expand_3L_medium', 'activation': 'relu', 'normalization': 'none'} using model Sobol.

Parameters: {'dropout_rate': 0.08608160354197025, 'weight_decay': 0.003489456544468332, 'lr': 4.4875578374478044e-05, 'optimizer_type': 'adamw', 'batch_size': 32, 'early_stopping_patience': 37, 'architecture': 'expand_3L_medium', 'activation': 'relu', 'normalization': 'none'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 569
Overall (all)      - RMSE: 0.0273, MAE: 0.0015
Overall (non-zero) - RMSE: 0.4413, MAE: 0.3211  [11,193 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4413, MAE: 0.3211  [11,193 non-zero values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 361
Overall (all)      - RMSE: 0.0238, MAE: 0.0014
Overall (non-zero) - RMSE: 0.3794, MAE: 0.2859  [27,977 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.3794, MAE: 0.2859  [27,977 non-zero values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 490
Overall (all)      - RMSE: 0.0268, MAE: 0.0016
Overall (non-zero) - RMSE: 0.4501, MAE: 0.3518  [10,856 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4501, MAE: 0.3518  [10,856 non-zero values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 323
Overall (all)      - RMSE: 0.0274, MAE: 0.0016
Overall (non-zero) - RMSE: 0.3020, MAE: 0.2196  [22,254 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.3020, MAE: 0.2196  [22,254 non-zero values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 381

[INFO 02-11 14:39:22] ax.service.ax_client: Completed trial 77 with data: {'avg_rmse_nonzero': (np.float32(0.37383872), np.float64(0.032817))}.
[INFO 02-11 14:39:22] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_Phase(T)_checkpoint.json`.
c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\modelbridge\cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 02-11 14:39:22] ax.service.ax_client: Generated new trial 78 with parameters {'dropout_rate': 0.466215, 'weight_decay': 1e-06, 'lr': 0.000521, 'optimizer_type': 'adam', 'batch_size': 128, 'early_stopping_patience': 22, 'architecture': 'expand_4L_medium', 'activation': 'elu', 'normalization': 'layer_norm'} using model Sobol.

Overall (all)      - RMSE: 0.0170, MAE: 0.0010
Overall (non-zero) - RMSE: 0.2965, MAE: 0.2043  [6,176 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.2965, MAE: 0.2043  [6,176 non-zero values]

==================================================
Cross-Validation Summary (non-zero targets only)
==================================================
Overall (all values):
  Avg Test MSE: 0.0006 (+/- 0.0002)
  Avg RMSE: 0.0244, MAE: 0.0014

Overall (non-zero only):
  Avg RMSE: 0.3738, MAE: 0.2765

Driving Force (DF, non-zero only):
  Avg RMSE: 0.0000, MAE: 0.0000

Phase Fraction (NF, non-zero only):
  Avg RMSE: 0.3738, MAE: 0.2765
Result: Non-zero RMSE = 0.3738
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_Phase(T)_checkpoint.json

============================================================
Trial 10/32
============================================================
Parameters: {'dropout_rate': 0.46621457394212484, 'weight_decay': 1.3806321492302303e-06, 'lr': 0.0005212540353348058, 'optimizer_type': 'adam', 'batch_size': 128, 'early_stopping_patience': 22, 'architecture': 'expand_4L_medium', 'activation': 'elu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 104
Overall (all)      - RMSE: 0.0250, MAE: 0.0015
Overall (non-zero) - RMSE: 0.4648, MAE: 0.3711  [11,193 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4648, MAE: 0.3711  [11,193 non-zero values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 155
Overall (all)      - RMSE: 0.0239, MAE: 0.0015
Overall (non-zero) - RMSE: 0.3861, MAE: 0.2936  [27,977 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.3861, MAE: 0.2936  [27,977 non-zero values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 107
Overall (all)      - RMSE: 0.0280, MAE: 0.0016
Overall (non-zero) - RMSE: 0.4475, MAE: 0.3392  [10,856 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4475, MAE: 0.3392  [10,856 non-zero values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 74
Overall (all)      - RMSE: 0.0239, MAE: 0.0014
Overall (non-zero) - RMSE: 0.2981, MAE: 0.2153  [22,254 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.2981, MAE: 0.2153  [22,254 non-zero values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 81

[INFO 02-11 14:56:43] ax.service.ax_client: Completed trial 78 with data: {'avg_rmse_nonzero': (np.float32(0.39795557), np.float64(0.029206))}.
[INFO 02-11 14:56:43] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_Phase(T)_checkpoint.json`.

Overall (all)      - RMSE: 0.0193, MAE: 0.0013
Overall (non-zero) - RMSE: 0.3932, MAE: 0.3528  [6,176 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.3932, MAE: 0.3528  [6,176 non-zero values]

==================================================
Cross-Validation Summary (non-zero targets only)
==================================================
Overall (all values):
  Avg Test MSE: 0.0006 (+/- 0.0001)
  Avg RMSE: 0.0240, MAE: 0.0014

Overall (non-zero only):
  Avg RMSE: 0.3980, MAE: 0.3144

Driving Force (DF, non-zero only):
  Avg RMSE: 0.0000, MAE: 0.0000

Phase Fraction (NF, non-zero only):
  Avg RMSE: 0.3980, MAE: 0.3144
Result: Non-zero RMSE = 0.3980
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_Phase(T)_checkpoint.json

============================================================
Trial 11/32
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\modelbridge\cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 02-11 14:56:43] ax.service.ax_client: Generated new trial 79 with parameters {'dropout_rate': 0.194915, 'weight_decay': 0.00084, 'lr': 0.002806, 'optimizer_type': 'adamw', 'batch_size': 64, 'early_stopping_patience': 42, 'architecture': 'expand_2L_small', 'activation': 'relu', 'normalization': 'batch_norm'} using model Sobol.

Parameters: {'dropout_rate': 0.19491452258080244, 'weight_decay': 0.0008400303233604341, 'lr': 0.002805541146995349, 'optimizer_type': 'adamw', 'batch_size': 64, 'early_stopping_patience': 42, 'architecture': 'expand_2L_small', 'activation': 'relu', 'normalization': 'batch_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 222
Overall (all)      - RMSE: 0.0384, MAE: 0.0024
Overall (non-zero) - RMSE: 0.4732, MAE: 0.3852  [11,193 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4732, MAE: 0.3852  [11,193 non-zero values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 533
Overall (all)      - RMSE: 0.0296, MAE: 0.0018
Overall (non-zero) - RMSE: 0.3787, MAE: 0.2783  [27,977 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.3787, MAE: 0.2783  [27,977 non-zero values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 196
Overall (all)      - RMSE: 0.0293, MAE: 0.0019
Overall (non-zero) - RMSE: 0.4473, MAE: 0.3396  [10,856 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4473, MAE: 0.3396  [10,856 non-zero values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 556
Overall (all)      - RMSE: 0.0320, MAE: 0.0018
Overall (non-zero) - RMSE: 0.2986, MAE: 0.2111  [22,254 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.2986, MAE: 0.2111  [22,254 non-zero values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 450

[INFO 02-11 16:22:12] ax.service.ax_client: Completed trial 79 with data: {'avg_rmse_nonzero': (np.float32(0.36734024), np.float64(0.04415))}.
[INFO 02-11 16:22:12] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_Phase(T)_checkpoint.json`.
c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\modelbridge\cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 02-11 16:22:12] ax.service.ax_client: Generated new trial 80 with parameters {'dropout_rate': 0.315266, 'weight_decay': 1.9e-05, 'lr': 0.00024, 'optimizer_type': 'adam', 'batch_size': 256, 'early_stopping_patience': 17, 'architecture': 'expand_4L_small', 'activation': 'elu', 'normalization': 'none'} using model Sobol.

Overall (all)      - RMSE: 0.0181, MAE: 0.0010
Overall (non-zero) - RMSE: 0.2388, MAE: 0.1387  [6,176 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.2388, MAE: 0.1387  [6,176 non-zero values]

==================================================
Cross-Validation Summary (non-zero targets only)
==================================================
Overall (all values):
  Avg Test MSE: 0.0009 (+/- 0.0004)
  Avg RMSE: 0.0295, MAE: 0.0018

Overall (non-zero only):
  Avg RMSE: 0.3673, MAE: 0.2706

Driving Force (DF, non-zero only):
  Avg RMSE: 0.0000, MAE: 0.0000

Phase Fraction (NF, non-zero only):
  Avg RMSE: 0.3673, MAE: 0.2706
Result: Non-zero RMSE = 0.3673
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_Phase(T)_checkpoint.json

============================================================
Trial 12/32
============================================================
Parameters: {'dropout_rate': 0.3152663838118315, 'weight_decay': 1.8716537247697422e-05, 'lr': 0.00023990327933987252, 'optimizer_type': 'adam', 'batch_size': 256, 'early_stopping_patience': 17, 'architecture': 'expand_4L_small', 'activation': 'elu', 'normalization': 'none'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 20
Overall (all)      - RMSE: 0.0245, MAE: 0.0024
Overall (non-zero) - RMSE: 0.4907, MAE: 0.4204  [11,193 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4907, MAE: 0.4204  [11,193 non-zero values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 18
Overall (all)      - RMSE: 0.0236, MAE: 0.0024
Overall (non-zero) - RMSE: 0.4119, MAE: 0.3323  [27,977 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4119, MAE: 0.3323  [27,977 non-zero values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 42
Overall (all)      - RMSE: 0.0263, MAE: 0.0025
Overall (non-zero) - RMSE: 0.4733, MAE: 0.3927  [10,856 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4733, MAE: 0.3927  [10,856 non-zero values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 23
Overall (all)      - RMSE: 0.0226, MAE: 0.0024
Overall (non-zero) - RMSE: 0.3348, MAE: 0.2655  [22,254 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.3348, MAE: 0.2655  [22,254 non-zero values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 18

[INFO 02-11 16:25:01] ax.service.ax_client: Completed trial 80 with data: {'avg_rmse_nonzero': (np.float32(0.4281773), np.float64(0.027338))}.
[INFO 02-11 16:25:01] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_Phase(T)_checkpoint.json`.

Overall (all)      - RMSE: 0.0193, MAE: 0.0021
Overall (non-zero) - RMSE: 0.4302, MAE: 0.4041  [6,176 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4302, MAE: 0.4041  [6,176 non-zero values]

==================================================
Cross-Validation Summary (non-zero targets only)
==================================================
Overall (all values):
  Avg Test MSE: 0.0005 (+/- 0.0001)
  Avg RMSE: 0.0233, MAE: 0.0024

Overall (non-zero only):
  Avg RMSE: 0.4282, MAE: 0.3630

Driving Force (DF, non-zero only):
  Avg RMSE: 0.0000, MAE: 0.0000

Phase Fraction (NF, non-zero only):
  Avg RMSE: 0.4282, MAE: 0.3630
Result: Non-zero RMSE = 0.4282
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_Phase(T)_checkpoint.json

============================================================
Trial 13/32
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\modelbridge\cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 02-11 16:25:02] ax.service.ax_client: Generated new trial 81 with parameters {'dropout_rate': 0.035273, 'weight_decay': 0.001936, 'lr': 1.9e-05, 'optimizer_type': 'adamw', 'batch_size': 32, 'early_stopping_patience': 13, 'architecture': 'expand_3L_small', 'activation': 'gelu', 'normalization': 'batch_norm'} using model Sobol.

Parameters: {'dropout_rate': 0.035272739827632904, 'weight_decay': 0.001935838171065974, 'lr': 1.9145865584688073e-05, 'optimizer_type': 'adamw', 'batch_size': 32, 'early_stopping_patience': 13, 'architecture': 'expand_3L_small', 'activation': 'gelu', 'normalization': 'batch_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 104
Overall (all)      - RMSE: 0.0248, MAE: 0.0015
Overall (non-zero) - RMSE: 0.4728, MAE: 0.3849  [11,193 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4728, MAE: 0.3849  [11,193 non-zero values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 192
Overall (all)      - RMSE: 0.0259, MAE: 0.0015
Overall (non-zero) - RMSE: 0.3717, MAE: 0.2661  [27,977 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.3717, MAE: 0.2661  [27,977 non-zero values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 111
Overall (all)      - RMSE: 0.0272, MAE: 0.0017
Overall (non-zero) - RMSE: 0.4492, MAE: 0.3454  [10,856 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4492, MAE: 0.3454  [10,856 non-zero values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 119
Overall (all)      - RMSE: 0.0230, MAE: 0.0016
Overall (non-zero) - RMSE: 0.3073, MAE: 0.2283  [22,254 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.3073, MAE: 0.2283  [22,254 non-zero values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 171

[INFO 02-11 17:22:49] ax.service.ax_client: Completed trial 81 with data: {'avg_rmse_nonzero': (np.float32(0.388183), np.float64(0.031642))}.
[INFO 02-11 17:22:49] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_Phase(T)_checkpoint.json`.

Overall (all)      - RMSE: 0.0165, MAE: 0.0010
Overall (non-zero) - RMSE: 0.3399, MAE: 0.2646  [6,176 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.3399, MAE: 0.2646  [6,176 non-zero values]

==================================================
Cross-Validation Summary (non-zero targets only)
==================================================
Overall (all values):
  Avg Test MSE: 0.0006 (+/- 0.0002)
  Avg RMSE: 0.0235, MAE: 0.0014

Overall (non-zero only):
  Avg RMSE: 0.3882, MAE: 0.2979

Driving Force (DF, non-zero only):
  Avg RMSE: 0.0000, MAE: 0.0000

Phase Fraction (NF, non-zero only):
  Avg RMSE: 0.3882, MAE: 0.2979
Result: Non-zero RMSE = 0.3882
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_Phase(T)_checkpoint.json

============================================================
Trial 14/32
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\modelbridge\cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 02-11 17:22:49] ax.service.ax_client: Generated new trial 82 with parameters {'dropout_rate': 0.407578, 'weight_decay': 8e-06, 'lr': 0.001649, 'optimizer_type': 'adam', 'batch_size': 128, 'early_stopping_patience': 48, 'architecture': 'expand_2L_xlarge', 'activation': 'elu', 'normalization': 'none'} using model Sobol.

Parameters: {'dropout_rate': 0.40757783222943544, 'weight_decay': 7.5238262126142205e-06, 'lr': 0.001649166036344769, 'optimizer_type': 'adam', 'batch_size': 128, 'early_stopping_patience': 48, 'architecture': 'expand_2L_xlarge', 'activation': 'elu', 'normalization': 'none'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 272
Overall (all)      - RMSE: 0.0261, MAE: 0.0014
Overall (non-zero) - RMSE: 0.4474, MAE: 0.3362  [11,193 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4474, MAE: 0.3362  [11,193 non-zero values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 214
Overall (all)      - RMSE: 0.0242, MAE: 0.0015
Overall (non-zero) - RMSE: 0.3859, MAE: 0.2911  [27,977 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.3859, MAE: 0.2911  [27,977 non-zero values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 132
Overall (all)      - RMSE: 0.0262, MAE: 0.0016
Overall (non-zero) - RMSE: 0.4427, MAE: 0.3438  [10,856 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4427, MAE: 0.3438  [10,856 non-zero values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 225
Overall (all)      - RMSE: 0.0229, MAE: 0.0014
Overall (non-zero) - RMSE: 0.3079, MAE: 0.2288  [22,254 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.3079, MAE: 0.2288  [22,254 non-zero values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 65

[INFO 02-11 17:45:57] ax.service.ax_client: Completed trial 82 with data: {'avg_rmse_nonzero': (np.float32(0.38816264), np.float64(0.026373))}.
[INFO 02-11 17:45:57] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_Phase(T)_checkpoint.json`.

Overall (all)      - RMSE: 0.0171, MAE: 0.0011
Overall (non-zero) - RMSE: 0.3569, MAE: 0.2865  [6,176 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.3569, MAE: 0.2865  [6,176 non-zero values]

==================================================
Cross-Validation Summary (non-zero targets only)
==================================================
Overall (all values):
  Avg Test MSE: 0.0006 (+/- 0.0001)
  Avg RMSE: 0.0233, MAE: 0.0014

Overall (non-zero only):
  Avg RMSE: 0.3882, MAE: 0.2973

Driving Force (DF, non-zero only):
  Avg RMSE: 0.0000, MAE: 0.0000

Phase Fraction (NF, non-zero only):
  Avg RMSE: 0.3882, MAE: 0.2973
Result: Non-zero RMSE = 0.3882
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_Phase(T)_checkpoint.json

============================================================
Trial 15/32
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\modelbridge\cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 02-11 17:45:57] ax.service.ax_client: Generated new trial 83 with parameters {'dropout_rate': 0.183277, 'weight_decay': 0.000153, 'lr': 0.009821, 'optimizer_type': 'adamw', 'batch_size': 64, 'early_stopping_patience': 29, 'architecture': 'expand_3L_gradual', 'activation': 'gelu', 'normalization': 'none'} using model Sobol.

Parameters: {'dropout_rate': 0.18327669892460108, 'weight_decay': 0.00015276911735237418, 'lr': 0.00982121244375922, 'optimizer_type': 'adamw', 'batch_size': 64, 'early_stopping_patience': 29, 'architecture': 'expand_3L_gradual', 'activation': 'gelu', 'normalization': 'none'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 297
Overall (all)      - RMSE: 0.0245, MAE: 0.0025
Overall (non-zero) - RMSE: 0.4908, MAE: 0.4204  [11,193 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4908, MAE: 0.4204  [11,193 non-zero values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 30
Overall (all)      - RMSE: 0.0424, MAE: 0.0027
Overall (non-zero) - RMSE: 0.4123, MAE: 0.3327  [27,977 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4123, MAE: 0.3327  [27,977 non-zero values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 34
Overall (all)      - RMSE: 0.0329, MAE: 0.0020
Overall (non-zero) - RMSE: 0.4736, MAE: 0.3931  [10,856 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4736, MAE: 0.3931  [10,856 non-zero values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 32
Overall (all)      - RMSE: 0.0226, MAE: 0.0024
Overall (non-zero) - RMSE: 0.3348, MAE: 0.2655  [22,254 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.3348, MAE: 0.2655  [22,254 non-zero values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 31

[INFO 02-11 18:06:09] ax.service.ax_client: Completed trial 83 with data: {'avg_rmse_nonzero': (np.float32(0.4005025), np.float64(0.038683))}.
[INFO 02-11 18:06:09] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_Phase(T)_checkpoint.json`.

Overall (all)      - RMSE: 0.0179, MAE: 0.0010
Overall (non-zero) - RMSE: 0.2911, MAE: 0.1950  [6,176 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.2911, MAE: 0.1950  [6,176 non-zero values]

==================================================
Cross-Validation Summary (non-zero targets only)
==================================================
Overall (all values):
  Avg Test MSE: 0.0009 (+/- 0.0005)
  Avg RMSE: 0.0281, MAE: 0.0021

Overall (non-zero only):
  Avg RMSE: 0.4005, MAE: 0.3214

Driving Force (DF, non-zero only):
  Avg RMSE: 0.0000, MAE: 0.0000

Phase Fraction (NF, non-zero only):
  Avg RMSE: 0.4005, MAE: 0.3214
Result: Non-zero RMSE = 0.4005
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_Phase(T)_checkpoint.json

============================================================
Trial 16/32
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\modelbridge\cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 02-11 18:06:09] ax.service.ax_client: Generated new trial 84 with parameters {'dropout_rate': 0.311457, 'weight_decay': 3.3e-05, 'lr': 0.000115, 'optimizer_type': 'adam', 'batch_size': 256, 'early_stopping_patience': 33, 'architecture': 'constant_512', 'activation': 'leaky_relu', 'normalization': 'layer_norm'} using model Sobol.

Parameters: {'dropout_rate': 0.31145667657256126, 'weight_decay': 3.343610092554477e-05, 'lr': 0.0001147933962817675, 'optimizer_type': 'adam', 'batch_size': 256, 'early_stopping_patience': 33, 'architecture': 'constant_512', 'activation': 'leaky_relu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 74
Overall (all)      - RMSE: 0.0254, MAE: 0.0016
Overall (non-zero) - RMSE: 0.4354, MAE: 0.3245  [11,193 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4354, MAE: 0.3245  [11,193 non-zero values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 317
Overall (all)      - RMSE: 0.0237, MAE: 0.0017
Overall (non-zero) - RMSE: 0.3608, MAE: 0.2765  [27,977 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.3608, MAE: 0.2765  [27,977 non-zero values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 61
Overall (all)      - RMSE: 0.0277, MAE: 0.0018
Overall (non-zero) - RMSE: 0.4382, MAE: 0.3242  [10,856 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4382, MAE: 0.3242  [10,856 non-zero values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 67
Overall (all)      - RMSE: 0.0223, MAE: 0.0019
Overall (non-zero) - RMSE: 0.3213, MAE: 0.2529  [22,254 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.3213, MAE: 0.2529  [22,254 non-zero values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 311

[INFO 02-11 18:26:42] ax.service.ax_client: Completed trial 84 with data: {'avg_rmse_nonzero': (np.float32(0.3707973), np.float64(0.028761))}.
[INFO 02-11 18:26:42] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_Phase(T)_checkpoint.json`.

Overall (all)      - RMSE: 0.0174, MAE: 0.0011
Overall (non-zero) - RMSE: 0.2982, MAE: 0.2297  [6,176 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.2982, MAE: 0.2297  [6,176 non-zero values]

==================================================
Cross-Validation Summary (non-zero targets only)
==================================================
Overall (all values):
  Avg Test MSE: 0.0006 (+/- 0.0002)
  Avg RMSE: 0.0233, MAE: 0.0016

Overall (non-zero only):
  Avg RMSE: 0.3708, MAE: 0.2816

Driving Force (DF, non-zero only):
  Avg RMSE: 0.0000, MAE: 0.0000

Phase Fraction (NF, non-zero only):
  Avg RMSE: 0.3708, MAE: 0.2816
Result: Non-zero RMSE = 0.3708
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_Phase(T)_checkpoint.json

============================================================
Trial 17/32
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\modelbridge\cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 02-11 18:26:42] ax.service.ax_client: Generated new trial 85 with parameters {'dropout_rate': 0.223539, 'weight_decay': 1e-06, 'lr': 0.00135, 'optimizer_type': 'adamw', 'batch_size': 128, 'early_stopping_patience': 36, 'architecture': 'expand_2L_small', 'activation': 'gelu', 'normalization': 'layer_norm'} using model Sobol.

Parameters: {'dropout_rate': 0.223538625985384, 'weight_decay': 1.1524340901054115e-06, 'lr': 0.0013502526497113146, 'optimizer_type': 'adamw', 'batch_size': 128, 'early_stopping_patience': 36, 'architecture': 'expand_2L_small', 'activation': 'gelu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 190
Overall (all)      - RMSE: 0.0260, MAE: 0.0016
Overall (non-zero) - RMSE: 0.4515, MAE: 0.3469  [11,193 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4515, MAE: 0.3469  [11,193 non-zero values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 293
Overall (all)      - RMSE: 0.0238, MAE: 0.0014
Overall (non-zero) - RMSE: 0.3798, MAE: 0.2816  [27,977 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.3798, MAE: 0.2816  [27,977 non-zero values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 182
Overall (all)      - RMSE: 0.0274, MAE: 0.0016
Overall (non-zero) - RMSE: 0.4471, MAE: 0.3403  [10,856 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4471, MAE: 0.3403  [10,856 non-zero values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 170
Overall (all)      - RMSE: 0.0225, MAE: 0.0014
Overall (non-zero) - RMSE: 0.3108, MAE: 0.2326  [22,254 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.3108, MAE: 0.2326  [22,254 non-zero values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 450

[INFO 02-11 19:06:08] ax.service.ax_client: Completed trial 85 with data: {'avg_rmse_nonzero': (np.float32(0.37658328), np.float64(0.033019))}.
[INFO 02-11 19:06:09] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_Phase(T)_checkpoint.json`.

Overall (all)      - RMSE: 0.0166, MAE: 0.0010
Overall (non-zero) - RMSE: 0.2937, MAE: 0.2069  [6,176 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.2937, MAE: 0.2069  [6,176 non-zero values]

==================================================
Cross-Validation Summary (non-zero targets only)
==================================================
Overall (all values):
  Avg Test MSE: 0.0006 (+/- 0.0002)
  Avg RMSE: 0.0233, MAE: 0.0014

Overall (non-zero only):
  Avg RMSE: 0.3766, MAE: 0.2817

Driving Force (DF, non-zero only):
  Avg RMSE: 0.0000, MAE: 0.0000

Phase Fraction (NF, non-zero only):
  Avg RMSE: 0.3766, MAE: 0.2817
Result: Non-zero RMSE = 0.3766
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_Phase(T)_checkpoint.json

============================================================
Trial 18/32
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\modelbridge\cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 02-11 19:06:09] ax.service.ax_client: Generated new trial 86 with parameters {'dropout_rate': 0.345359, 'weight_decay': 0.004487, 'lr': 1.6e-05, 'optimizer_type': 'adam', 'batch_size': 32, 'early_stopping_patience': 20, 'architecture': 'constant_1024', 'activation': 'relu', 'normalization': 'batch_norm'} using model Sobol.

Parameters: {'dropout_rate': 0.3453591400757432, 'weight_decay': 0.004487237064462038, 'lr': 1.5789240785909228e-05, 'optimizer_type': 'adam', 'batch_size': 32, 'early_stopping_patience': 20, 'architecture': 'constant_1024', 'activation': 'relu', 'normalization': 'batch_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 21
Overall (all)      - RMSE: 0.0245, MAE: 0.0024
Overall (non-zero) - RMSE: 0.4907, MAE: 0.4204  [11,193 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4907, MAE: 0.4204  [11,193 non-zero values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 21
Overall (all)      - RMSE: 0.0236, MAE: 0.0024
Overall (non-zero) - RMSE: 0.4119, MAE: 0.3323  [27,977 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4119, MAE: 0.3323  [27,977 non-zero values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 21
Overall (all)      - RMSE: 0.0263, MAE: 0.0025
Overall (non-zero) - RMSE: 0.4733, MAE: 0.3927  [10,856 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4733, MAE: 0.3927  [10,856 non-zero values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 21
Overall (all)      - RMSE: 0.0226, MAE: 0.0024
Overall (non-zero) - RMSE: 0.3348, MAE: 0.2654  [22,254 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.3348, MAE: 0.2654  [22,254 non-zero values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 21

[INFO 02-11 19:15:31] ax.service.ax_client: Completed trial 86 with data: {'avg_rmse_nonzero': (np.float32(0.4281624), np.float64(0.027326))}.
[INFO 02-11 19:15:31] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_Phase(T)_checkpoint.json`.

Overall (all)      - RMSE: 0.0193, MAE: 0.0021
Overall (non-zero) - RMSE: 0.4301, MAE: 0.4040  [6,176 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4301, MAE: 0.4040  [6,176 non-zero values]

==================================================
Cross-Validation Summary (non-zero targets only)
==================================================
Overall (all values):
  Avg Test MSE: 0.0005 (+/- 0.0001)
  Avg RMSE: 0.0233, MAE: 0.0024

Overall (non-zero only):
  Avg RMSE: 0.4282, MAE: 0.3630

Driving Force (DF, non-zero only):
  Avg RMSE: 0.0000, MAE: 0.0000

Phase Fraction (NF, non-zero only):
  Avg RMSE: 0.4282, MAE: 0.3630
Result: Non-zero RMSE = 0.4282
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_Phase(T)_checkpoint.json

============================================================
Trial 19/32
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: '0.9899760679653765'
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-11 19:15:40] ax.service.ax_client: Generated new trial 87 with parameters {'dropout_rate': 0.5, 'weight_decay': 1.4e-05, 'lr': 1e-05, 'optimizer_type': 'adamw', 'batch_size': 32, 'early_stopping_patience': 49, 'architecture': 'expand_2L_small', 'activation': 'relu', 'normalization': 'none'} using model BoTorch.

Parameters: {'dropout_rate': 0.5, 'weight_decay': 1.4377794837977437e-05, 'lr': 1e-05, 'optimizer_type': 'adamw', 'batch_size': 32, 'early_stopping_patience': 49, 'architecture': 'expand_2L_small', 'activation': 'relu', 'normalization': 'none'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Overall (all)      - RMSE: 0.0269, MAE: 0.0014
Overall (non-zero) - RMSE: 0.4434, MAE: 0.3263  [11,193 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4434, MAE: 0.3263  [11,193 non-zero values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Overall (all)      - RMSE: 0.0245, MAE: 0.0014
Overall (non-zero) - RMSE: 0.3797, MAE: 0.2801  [27,977 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.3797, MAE: 0.2801  [27,977 non-zero values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Overall (all)      - RMSE: 0.0272, MAE: 0.0016
Overall (non-zero) - RMSE: 0.4457, MAE: 0.3414  [10,856 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4457, MAE: 0.3414  [10,856 non-zero values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Overall (all)      - RMSE: 0.0246, MAE: 0.0016
Overall (non-zero) - RMSE: 0.3052, MAE: 0.2359  [22,254 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.3052, MAE: 0.2359  [22,254 non-zero values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794

[INFO 02-12 04:10:16] ax.service.ax_client: Completed trial 87 with data: {'avg_rmse_nonzero': (np.float32(0.3859262), np.float64(0.026801))}.

Overall (all)      - RMSE: 0.0176, MAE: 0.0011
Overall (non-zero) - RMSE: 0.3555, MAE: 0.2934  [6,176 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.3555, MAE: 0.2934  [6,176 non-zero values]

==================================================
Cross-Validation Summary (non-zero targets only)
==================================================
Overall (all values):
  Avg Test MSE: 0.0006 (+/- 0.0002)
  Avg RMSE: 0.0242, MAE: 0.0014

Overall (non-zero only):
  Avg RMSE: 0.3859, MAE: 0.2954

Driving Force (DF, non-zero only):
  Avg RMSE: 0.0000, MAE: 0.0000

Phase Fraction (NF, non-zero only):
  Avg RMSE: 0.3859, MAE: 0.2954
Result: Non-zero RMSE = 0.3859

[INFO 02-12 04:10:16] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_Phase(T)_checkpoint.json`.

Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_Phase(T)_checkpoint.json

============================================================
Trial 20/32
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: '0.5785941783348792'
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-12 04:10:42] ax.service.ax_client: Generated new trial 88 with parameters {'dropout_rate': 0.5, 'weight_decay': 2.5e-05, 'lr': 1e-05, 'optimizer_type': 'adamw', 'batch_size': 256, 'early_stopping_patience': 21, 'architecture': 'constant_512', 'activation': 'relu', 'normalization': 'batch_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.5, 'weight_decay': 2.5478844902209677e-05, 'lr': 1e-05, 'optimizer_type': 'adamw', 'batch_size': 256, 'early_stopping_patience': 21, 'architecture': 'constant_512', 'activation': 'relu', 'normalization': 'batch_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 875
Overall (all)      - RMSE: 0.0251, MAE: 0.0014
Overall (non-zero) - RMSE: 0.4604, MAE: 0.3617  [11,193 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4604, MAE: 0.3617  [11,193 non-zero values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Overall (all)      - RMSE: 0.0237, MAE: 0.0014
Overall (non-zero) - RMSE: 0.3824, MAE: 0.2880  [27,977 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.3824, MAE: 0.2880  [27,977 non-zero values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Overall (all)      - RMSE: 0.0276, MAE: 0.0016
Overall (non-zero) - RMSE: 0.4469, MAE: 0.3402  [10,856 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4469, MAE: 0.3402  [10,856 non-zero values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 852
Overall (all)      - RMSE: 0.0222, MAE: 0.0014
Overall (non-zero) - RMSE: 0.3112, MAE: 0.2341  [22,254 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.3112, MAE: 0.2341  [22,254 non-zero values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794

[INFO 02-12 06:09:28] ax.service.ax_client: Completed trial 88 with data: {'avg_rmse_nonzero': (np.float32(0.39035767), np.float64(0.028274))}.
[INFO 02-12 06:09:28] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_Phase(T)_checkpoint.json`.

Overall (all)      - RMSE: 0.0167, MAE: 0.0011
Overall (non-zero) - RMSE: 0.3509, MAE: 0.2801  [6,176 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.3509, MAE: 0.2801  [6,176 non-zero values]

==================================================
Cross-Validation Summary (non-zero targets only)
==================================================
Overall (all values):
  Avg Test MSE: 0.0005 (+/- 0.0002)
  Avg RMSE: 0.0231, MAE: 0.0014

Overall (non-zero only):
  Avg RMSE: 0.3904, MAE: 0.3008

Driving Force (DF, non-zero only):
  Avg RMSE: 0.0000, MAE: 0.0000

Phase Fraction (NF, non-zero only):
  Avg RMSE: 0.3904, MAE: 0.3008
Result: Non-zero RMSE = 0.3904
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_Phase(T)_checkpoint.json

============================================================
Trial 21/32
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: '0.700459584299245'
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-12 06:09:37] ax.service.ax_client: Generated new trial 89 with parameters {'dropout_rate': 0.5, 'weight_decay': 1e-06, 'lr': 1e-05, 'optimizer_type': 'adamw', 'batch_size': 32, 'early_stopping_patience': 17, 'architecture': 'expand_4L_small', 'activation': 'gelu', 'normalization': 'batch_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.5, 'weight_decay': 1.0064077626459647e-06, 'lr': 1e-05, 'optimizer_type': 'adamw', 'batch_size': 32, 'early_stopping_patience': 17, 'architecture': 'expand_4L_small', 'activation': 'gelu', 'normalization': 'batch_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 458
Overall (all)      - RMSE: 0.0252, MAE: 0.0014
Overall (non-zero) - RMSE: 0.4618, MAE: 0.3606  [11,193 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4618, MAE: 0.3606  [11,193 non-zero values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 470
Overall (all)      - RMSE: 0.0238, MAE: 0.0015
Overall (non-zero) - RMSE: 0.3770, MAE: 0.2808  [27,977 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.3770, MAE: 0.2808  [27,977 non-zero values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 417
Overall (all)      - RMSE: 0.0269, MAE: 0.0016
Overall (non-zero) - RMSE: 0.4471, MAE: 0.3380  [10,856 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4471, MAE: 0.3380  [10,856 non-zero values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 350
Overall (all)      - RMSE: 0.0223, MAE: 0.0015
Overall (non-zero) - RMSE: 0.3233, MAE: 0.2501  [22,254 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.3233, MAE: 0.2501  [22,254 non-zero values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 238

[INFO 02-12 09:23:45] ax.service.ax_client: Completed trial 89 with data: {'avg_rmse_nonzero': (np.float32(0.39554816), np.float64(0.025826))}.
[INFO 02-12 09:23:46] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_Phase(T)_checkpoint.json`.

Overall (all)      - RMSE: 0.0173, MAE: 0.0012
Overall (non-zero) - RMSE: 0.3686, MAE: 0.3107  [6,176 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.3686, MAE: 0.3107  [6,176 non-zero values]

==================================================
Cross-Validation Summary (non-zero targets only)
==================================================
Overall (all values):
  Avg Test MSE: 0.0005 (+/- 0.0001)
  Avg RMSE: 0.0231, MAE: 0.0014

Overall (non-zero only):
  Avg RMSE: 0.3955, MAE: 0.3080

Driving Force (DF, non-zero only):
  Avg RMSE: 0.0000, MAE: 0.0000

Phase Fraction (NF, non-zero only):
  Avg RMSE: 0.3955, MAE: 0.3080
Result: Non-zero RMSE = 0.3955
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_Phase(T)_checkpoint.json

============================================================
Trial 22/32
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: '0.5877431120173467'
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-12 09:23:56] ax.service.ax_client: Generated new trial 90 with parameters {'dropout_rate': 0.403683, 'weight_decay': 1.5e-05, 'lr': 1e-05, 'optimizer_type': 'adamw', 'batch_size': 32, 'early_stopping_patience': 35, 'architecture': 'expand_2L_small', 'activation': 'leaky_relu', 'normalization': 'batch_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.40368343055926725, 'weight_decay': 1.4734940424840247e-05, 'lr': 1e-05, 'optimizer_type': 'adamw', 'batch_size': 32, 'early_stopping_patience': 35, 'architecture': 'expand_2L_small', 'activation': 'leaky_relu', 'normalization': 'batch_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 938
Overall (all)      - RMSE: 0.0257, MAE: 0.0014
Overall (non-zero) - RMSE: 0.4612, MAE: 0.3630  [11,193 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4612, MAE: 0.3630  [11,193 non-zero values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Overall (all)      - RMSE: 0.0243, MAE: 0.0015
Overall (non-zero) - RMSE: 0.3762, MAE: 0.2808  [27,977 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.3762, MAE: 0.2808  [27,977 non-zero values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 506
Overall (all)      - RMSE: 0.0274, MAE: 0.0016
Overall (non-zero) - RMSE: 0.4513, MAE: 0.3498  [10,856 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4513, MAE: 0.3498  [10,856 non-zero values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 646
Overall (all)      - RMSE: 0.0262, MAE: 0.0015
Overall (non-zero) - RMSE: 0.2966, MAE: 0.2112  [22,254 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.2966, MAE: 0.2112  [22,254 non-zero values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 733

[INFO 02-12 14:06:48] ax.service.ax_client: Completed trial 90 with data: {'avg_rmse_nonzero': (np.float32(0.38470966), np.float64(0.031863))}.
[INFO 02-12 14:06:48] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_Phase(T)_checkpoint.json`.

Overall (all)      - RMSE: 0.0166, MAE: 0.0010
Overall (non-zero) - RMSE: 0.3382, MAE: 0.2636  [6,176 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.3382, MAE: 0.2636  [6,176 non-zero values]

==================================================
Cross-Validation Summary (non-zero targets only)
==================================================
Overall (all values):
  Avg Test MSE: 0.0006 (+/- 0.0002)
  Avg RMSE: 0.0240, MAE: 0.0014

Overall (non-zero only):
  Avg RMSE: 0.3847, MAE: 0.2937

Driving Force (DF, non-zero only):
  Avg RMSE: 0.0000, MAE: 0.0000

Phase Fraction (NF, non-zero only):
  Avg RMSE: 0.3847, MAE: 0.2937
Result: Non-zero RMSE = 0.3847
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_Phase(T)_checkpoint.json

============================================================
Trial 23/32
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: '0.6622222566271043'
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-12 14:06:57] ax.service.ax_client: Generated new trial 91 with parameters {'dropout_rate': 0.490126, 'weight_decay': 2.4e-05, 'lr': 1e-05, 'optimizer_type': 'adamw', 'batch_size': 32, 'early_stopping_patience': 49, 'architecture': 'constant_1024_3L', 'activation': 'leaky_relu', 'normalization': 'batch_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.49012577045305206, 'weight_decay': 2.4139260492259626e-05, 'lr': 1e-05, 'optimizer_type': 'adamw', 'batch_size': 32, 'early_stopping_patience': 49, 'architecture': 'constant_1024_3L', 'activation': 'leaky_relu', 'normalization': 'batch_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 630
Overall (all)      - RMSE: 0.0276, MAE: 0.0014
Overall (non-zero) - RMSE: 0.4326, MAE: 0.3064  [11,193 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4326, MAE: 0.3064  [11,193 non-zero values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 747
Overall (all)      - RMSE: 0.0247, MAE: 0.0015
Overall (non-zero) - RMSE: 0.3771, MAE: 0.2803  [27,977 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.3771, MAE: 0.2803  [27,977 non-zero values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 673
Overall (all)      - RMSE: 0.0274, MAE: 0.0016
Overall (non-zero) - RMSE: 0.4427, MAE: 0.3320  [10,856 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4427, MAE: 0.3320  [10,856 non-zero values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 525
Overall (all)      - RMSE: 0.0288, MAE: 0.0016
Overall (non-zero) - RMSE: 0.2925, MAE: 0.2022  [22,254 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.2925, MAE: 0.2022  [22,254 non-zero values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 831

[INFO 02-12 21:38:57] ax.service.ax_client: Completed trial 91 with data: {'avg_rmse_nonzero': (np.float32(0.35938984), np.float64(0.037822))}.

Overall (all)      - RMSE: 0.0175, MAE: 0.0009
Overall (non-zero) - RMSE: 0.2521, MAE: 0.1547  [6,176 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.2521, MAE: 0.1547  [6,176 non-zero values]

==================================================
Cross-Validation Summary (non-zero targets only)
==================================================
Overall (all values):
  Avg Test MSE: 0.0007 (+/- 0.0002)
  Avg RMSE: 0.0252, MAE: 0.0014

Overall (non-zero only):
  Avg RMSE: 0.3594, MAE: 0.2551

Driving Force (DF, non-zero only):
  Avg RMSE: 0.0000, MAE: 0.0000

Phase Fraction (NF, non-zero only):
  Avg RMSE: 0.3594, MAE: 0.2551
Result: Non-zero RMSE = 0.3594

[INFO 02-12 21:38:57] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_Phase(T)_checkpoint.json`.

Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_Phase(T)_checkpoint.json

============================================================
Trial 24/32
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: '0.6488082758963455'
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-12 21:39:28] ax.service.ax_client: Generated new trial 92 with parameters {'dropout_rate': 0.0, 'weight_decay': 0.001042, 'lr': 1e-05, 'optimizer_type': 'adamw', 'batch_size': 32, 'early_stopping_patience': 26, 'architecture': 'single_1024', 'activation': 'leaky_relu', 'normalization': 'layer_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.0, 'weight_decay': 0.0010416155605703149, 'lr': 1e-05, 'optimizer_type': 'adamw', 'batch_size': 32, 'early_stopping_patience': 26, 'architecture': 'single_1024', 'activation': 'leaky_relu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 453
Overall (all)      - RMSE: 0.0249, MAE: 0.0014
Overall (non-zero) - RMSE: 0.4559, MAE: 0.3558  [11,193 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4559, MAE: 0.3558  [11,193 non-zero values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 726
Overall (all)      - RMSE: 0.0245, MAE: 0.0014
Overall (non-zero) - RMSE: 0.3790, MAE: 0.2770  [27,977 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.3790, MAE: 0.2770  [27,977 non-zero values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 336
Overall (all)      - RMSE: 0.0281, MAE: 0.0016
Overall (non-zero) - RMSE: 0.4426, MAE: 0.3320  [10,856 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4426, MAE: 0.3320  [10,856 non-zero values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 427
Overall (all)      - RMSE: 0.0235, MAE: 0.0014
Overall (non-zero) - RMSE: 0.3013, MAE: 0.2223  [22,254 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.3013, MAE: 0.2223  [22,254 non-zero values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 437

[INFO 02-13 03:11:00] ax.service.ax_client: Completed trial 92 with data: {'avg_rmse_nonzero': (np.float32(0.38309494), np.float64(0.029755))}.

Overall (all)      - RMSE: 0.0171, MAE: 0.0011
Overall (non-zero) - RMSE: 0.3366, MAE: 0.2716  [6,176 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.3366, MAE: 0.2716  [6,176 non-zero values]

==================================================
Cross-Validation Summary (non-zero targets only)
==================================================
Overall (all values):
  Avg Test MSE: 0.0006 (+/- 0.0002)
  Avg RMSE: 0.0236, MAE: 0.0014

Overall (non-zero only):
  Avg RMSE: 0.3831, MAE: 0.2917

Driving Force (DF, non-zero only):
  Avg RMSE: 0.0000, MAE: 0.0000

Phase Fraction (NF, non-zero only):
  Avg RMSE: 0.3831, MAE: 0.2917
Result: Non-zero RMSE = 0.3831

[INFO 02-13 03:11:01] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_Phase(T)_checkpoint.json`.

Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_Phase(T)_checkpoint.json

============================================================
Trial 25/32
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: '0.7707176332252292'
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-13 03:11:23] ax.service.ax_client: Generated new trial 93 with parameters {'dropout_rate': 0.5, 'weight_decay': 2e-06, 'lr': 1e-05, 'optimizer_type': 'adamw', 'batch_size': 32, 'early_stopping_patience': 48, 'architecture': 'expand_4L_medium', 'activation': 'leaky_relu', 'normalization': 'batch_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.5, 'weight_decay': 2.4739438011827026e-06, 'lr': 1e-05, 'optimizer_type': 'adamw', 'batch_size': 32, 'early_stopping_patience': 48, 'architecture': 'expand_4L_medium', 'activation': 'leaky_relu', 'normalization': 'batch_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 946
Overall (all)      - RMSE: 0.0272, MAE: 0.0016
Overall (non-zero) - RMSE: 0.4428, MAE: 0.3227  [11,193 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4428, MAE: 0.3227  [11,193 non-zero values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Overall (all)      - RMSE: 0.0250, MAE: 0.0015
Overall (non-zero) - RMSE: 0.3722, MAE: 0.2732  [27,977 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.3722, MAE: 0.2732  [27,977 non-zero values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 608
Overall (all)      - RMSE: 0.0272, MAE: 0.0016
Overall (non-zero) - RMSE: 0.4487, MAE: 0.3420  [10,856 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4487, MAE: 0.3420  [10,856 non-zero values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 777
Overall (all)      - RMSE: 0.0231, MAE: 0.0014
Overall (non-zero) - RMSE: 0.3023, MAE: 0.2201  [22,254 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.3023, MAE: 0.2201  [22,254 non-zero values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794

[INFO 02-13 12:38:53] ax.service.ax_client: Completed trial 93 with data: {'avg_rmse_nonzero': (np.float32(0.37175342), np.float64(0.033178))}.
[INFO 02-13 12:38:53] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_Phase(T)_checkpoint.json`.

Overall (all)      - RMSE: 0.0175, MAE: 0.0011
Overall (non-zero) - RMSE: 0.2928, MAE: 0.2022  [6,176 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.2928, MAE: 0.2022  [6,176 non-zero values]

==================================================
Cross-Validation Summary (non-zero targets only)
==================================================
Overall (all values):
  Avg Test MSE: 0.0006 (+/- 0.0002)
  Avg RMSE: 0.0240, MAE: 0.0015

Overall (non-zero only):
  Avg RMSE: 0.3718, MAE: 0.2720

Driving Force (DF, non-zero only):
  Avg RMSE: 0.0000, MAE: 0.0000

Phase Fraction (NF, non-zero only):
  Avg RMSE: 0.3718, MAE: 0.2720
Result: Non-zero RMSE = 0.3718
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_Phase(T)_checkpoint.json

============================================================
Trial 26/32
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: '0.6390476682367322'
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-13 12:39:01] ax.service.ax_client: Generated new trial 94 with parameters {'dropout_rate': 0.0, 'weight_decay': 0.000419, 'lr': 1e-05, 'optimizer_type': 'adamw', 'batch_size': 32, 'early_stopping_patience': 47, 'architecture': 'constant_512', 'activation': 'selu', 'normalization': 'batch_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.0, 'weight_decay': 0.00041930309837078135, 'lr': 1e-05, 'optimizer_type': 'adamw', 'batch_size': 32, 'early_stopping_patience': 47, 'architecture': 'constant_512', 'activation': 'selu', 'normalization': 'batch_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 759
Overall (all)      - RMSE: 0.0266, MAE: 0.0015
Overall (non-zero) - RMSE: 0.4654, MAE: 0.3685  [11,193 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4654, MAE: 0.3685  [11,193 non-zero values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 487
Overall (all)      - RMSE: 0.0238, MAE: 0.0015
Overall (non-zero) - RMSE: 0.3864, MAE: 0.3009  [27,977 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.3864, MAE: 0.3009  [27,977 non-zero values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 799
Overall (all)      - RMSE: 0.0268, MAE: 0.0016
Overall (non-zero) - RMSE: 0.4415, MAE: 0.3380  [10,856 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4415, MAE: 0.3380  [10,856 non-zero values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 840
Overall (all)      - RMSE: 0.0294, MAE: 0.0016
Overall (non-zero) - RMSE: 0.2940, MAE: 0.2029  [22,254 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.2940, MAE: 0.2029  [22,254 non-zero values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 716

[INFO 02-13 18:17:59] ax.service.ax_client: Completed trial 94 with data: {'avg_rmse_nonzero': (np.float32(0.3868166), np.float64(0.031124))}.
[INFO 02-13 18:17:59] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_Phase(T)_checkpoint.json`.

Overall (all)      - RMSE: 0.0174, MAE: 0.0011
Overall (non-zero) - RMSE: 0.3468, MAE: 0.2768  [6,176 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.3468, MAE: 0.2768  [6,176 non-zero values]

==================================================
Cross-Validation Summary (non-zero targets only)
==================================================
Overall (all values):
  Avg Test MSE: 0.0006 (+/- 0.0002)
  Avg RMSE: 0.0248, MAE: 0.0015

Overall (non-zero only):
  Avg RMSE: 0.3868, MAE: 0.2974

Driving Force (DF, non-zero only):
  Avg RMSE: 0.0000, MAE: 0.0000

Phase Fraction (NF, non-zero only):
  Avg RMSE: 0.3868, MAE: 0.2974
Result: Non-zero RMSE = 0.3868
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_Phase(T)_checkpoint.json

============================================================
Trial 27/32
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: '0.6274879881322892'
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-13 18:18:08] ax.service.ax_client: Generated new trial 95 with parameters {'dropout_rate': 0.5, 'weight_decay': 1e-06, 'lr': 1e-05, 'optimizer_type': 'adamw', 'batch_size': 256, 'early_stopping_patience': 44, 'architecture': 'constant_1024_3L', 'activation': 'leaky_relu', 'normalization': 'batch_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.5, 'weight_decay': 1.1426259815197614e-06, 'lr': 1e-05, 'optimizer_type': 'adamw', 'batch_size': 256, 'early_stopping_patience': 44, 'architecture': 'constant_1024_3L', 'activation': 'leaky_relu', 'normalization': 'batch_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 761
Overall (all)      - RMSE: 0.0253, MAE: 0.0014
Overall (non-zero) - RMSE: 0.4582, MAE: 0.3569  [11,193 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4582, MAE: 0.3569  [11,193 non-zero values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Overall (all)      - RMSE: 0.0236, MAE: 0.0014
Overall (non-zero) - RMSE: 0.3791, MAE: 0.2864  [27,977 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.3791, MAE: 0.2864  [27,977 non-zero values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Overall (all)      - RMSE: 0.0269, MAE: 0.0016
Overall (non-zero) - RMSE: 0.4427, MAE: 0.3379  [10,856 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4427, MAE: 0.3379  [10,856 non-zero values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Overall (all)      - RMSE: 0.0249, MAE: 0.0015
Overall (non-zero) - RMSE: 0.2984, MAE: 0.2138  [22,254 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.2984, MAE: 0.2138  [22,254 non-zero values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794

[INFO 02-13 21:17:24] ax.service.ax_client: Completed trial 95 with data: {'avg_rmse_nonzero': (np.float32(0.3831681), np.float64(0.030376))}.

Overall (all)      - RMSE: 0.0164, MAE: 0.0010
Overall (non-zero) - RMSE: 0.3375, MAE: 0.2637  [6,176 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.3375, MAE: 0.2637  [6,176 non-zero values]

==================================================
Cross-Validation Summary (non-zero targets only)
==================================================
Overall (all values):
  Avg Test MSE: 0.0006 (+/- 0.0002)
  Avg RMSE: 0.0235, MAE: 0.0014

Overall (non-zero only):
  Avg RMSE: 0.3832, MAE: 0.2917

Driving Force (DF, non-zero only):
  Avg RMSE: 0.0000, MAE: 0.0000

Phase Fraction (NF, non-zero only):
  Avg RMSE: 0.3832, MAE: 0.2917
Result: Non-zero RMSE = 0.3832

[INFO 02-13 21:17:24] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_Phase(T)_checkpoint.json`.

Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_Phase(T)_checkpoint.json

============================================================
Trial 28/32
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: '0.7583456525583635'
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-13 21:17:50] ax.service.ax_client: Generated new trial 96 with parameters {'dropout_rate': 0.5, 'weight_decay': 2e-06, 'lr': 1e-05, 'optimizer_type': 'adamw', 'batch_size': 32, 'early_stopping_patience': 31, 'architecture': 'expand_2L_medium', 'activation': 'leaky_relu', 'normalization': 'batch_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.5, 'weight_decay': 1.511869150604507e-06, 'lr': 1e-05, 'optimizer_type': 'adamw', 'batch_size': 32, 'early_stopping_patience': 31, 'architecture': 'expand_2L_medium', 'activation': 'leaky_relu', 'normalization': 'batch_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 867
Overall (all)      - RMSE: 0.0257, MAE: 0.0014
Overall (non-zero) - RMSE: 0.4498, MAE: 0.3413  [11,193 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4498, MAE: 0.3413  [11,193 non-zero values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 681
Overall (all)      - RMSE: 0.0252, MAE: 0.0015
Overall (non-zero) - RMSE: 0.3707, MAE: 0.2741  [27,977 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.3707, MAE: 0.2741  [27,977 non-zero values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 672
Overall (all)      - RMSE: 0.0276, MAE: 0.0016
Overall (non-zero) - RMSE: 0.4451, MAE: 0.3374  [10,856 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4451, MAE: 0.3374  [10,856 non-zero values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 491
Overall (all)      - RMSE: 0.0293, MAE: 0.0016
Overall (non-zero) - RMSE: 0.2937, MAE: 0.2034  [22,254 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.2937, MAE: 0.2034  [22,254 non-zero values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 739

[INFO 02-14 07:53:10] ax.service.ax_client: Completed trial 96 with data: {'avg_rmse_nonzero': (np.float32(0.37002817), np.float64(0.034709))}.

Overall (all)      - RMSE: 0.0171, MAE: 0.0010
Overall (non-zero) - RMSE: 0.2908, MAE: 0.1999  [6,176 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.2908, MAE: 0.1999  [6,176 non-zero values]

==================================================
Cross-Validation Summary (non-zero targets only)
==================================================
Overall (all values):
  Avg Test MSE: 0.0006 (+/- 0.0002)
  Avg RMSE: 0.0250, MAE: 0.0014

Overall (non-zero only):
  Avg RMSE: 0.3700, MAE: 0.2712

Driving Force (DF, non-zero only):
  Avg RMSE: 0.0000, MAE: 0.0000

Phase Fraction (NF, non-zero only):
  Avg RMSE: 0.3700, MAE: 0.2712
Result: Non-zero RMSE = 0.3700

[INFO 02-14 07:53:10] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_Phase(T)_checkpoint.json`.

Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_Phase(T)_checkpoint.json

============================================================
Trial 29/32
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: '0.7762352995601094'
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-14 07:53:35] ax.service.ax_client: Generated new trial 97 with parameters {'dropout_rate': 0.5, 'weight_decay': 5e-06, 'lr': 1e-05, 'optimizer_type': 'adamw', 'batch_size': 256, 'early_stopping_patience': 17, 'architecture': 'constant_1024_3L', 'activation': 'relu', 'normalization': 'batch_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.5, 'weight_decay': 5.428612823683799e-06, 'lr': 1e-05, 'optimizer_type': 'adamw', 'batch_size': 256, 'early_stopping_patience': 17, 'architecture': 'constant_1024_3L', 'activation': 'relu', 'normalization': 'batch_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 549
Overall (all)      - RMSE: 0.0250, MAE: 0.0014
Overall (non-zero) - RMSE: 0.4657, MAE: 0.3709  [11,193 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4657, MAE: 0.3709  [11,193 non-zero values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 595
Overall (all)      - RMSE: 0.0236, MAE: 0.0015
Overall (non-zero) - RMSE: 0.3776, MAE: 0.2828  [27,977 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.3776, MAE: 0.2828  [27,977 non-zero values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 626
Overall (all)      - RMSE: 0.0273, MAE: 0.0016
Overall (non-zero) - RMSE: 0.4411, MAE: 0.3295  [10,856 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4411, MAE: 0.3295  [10,856 non-zero values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 668
Overall (all)      - RMSE: 0.0222, MAE: 0.0014
Overall (non-zero) - RMSE: 0.3148, MAE: 0.2391  [22,254 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.3148, MAE: 0.2391  [22,254 non-zero values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 529

[INFO 02-14 10:24:31] ax.service.ax_client: Completed trial 97 with data: {'avg_rmse_nonzero': (np.float32(0.39096177), np.float64(0.027684))}.

Overall (all)      - RMSE: 0.0169, MAE: 0.0011
Overall (non-zero) - RMSE: 0.3556, MAE: 0.2875  [6,176 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.3556, MAE: 0.2875  [6,176 non-zero values]

==================================================
Cross-Validation Summary (non-zero targets only)
==================================================
Overall (all values):
  Avg Test MSE: 0.0005 (+/- 0.0002)
  Avg RMSE: 0.0230, MAE: 0.0014

Overall (non-zero only):
  Avg RMSE: 0.3910, MAE: 0.3020

Driving Force (DF, non-zero only):
  Avg RMSE: 0.0000, MAE: 0.0000

Phase Fraction (NF, non-zero only):
  Avg RMSE: 0.3910, MAE: 0.3020
Result: Non-zero RMSE = 0.3910

[INFO 02-14 10:24:31] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_Phase(T)_checkpoint.json`.

Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_Phase(T)_checkpoint.json

============================================================
Trial 30/32
============================================================

C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-14 10:24:57] ax.service.ax_client: Generated new trial 98 with parameters {'dropout_rate': 0.36751, 'weight_decay': 2e-06, 'lr': 1e-05, 'optimizer_type': 'adamw', 'batch_size': 32, 'early_stopping_patience': 50, 'architecture': 'constant_512', 'activation': 'relu', 'normalization': 'layer_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.36750974896888394, 'weight_decay': 1.5296292468721942e-06, 'lr': 1e-05, 'optimizer_type': 'adamw', 'batch_size': 32, 'early_stopping_patience': 50, 'architecture': 'constant_512', 'activation': 'relu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 685
Overall (all)      - RMSE: 0.0264, MAE: 0.0014
Overall (non-zero) - RMSE: 0.4350, MAE: 0.3146  [11,193 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4350, MAE: 0.3146  [11,193 non-zero values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Overall (all)      - RMSE: 0.0243, MAE: 0.0015
Overall (non-zero) - RMSE: 0.3788, MAE: 0.2813  [27,977 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.3788, MAE: 0.2813  [27,977 non-zero values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 787
Overall (all)      - RMSE: 0.0273, MAE: 0.0016
Overall (non-zero) - RMSE: 0.4458, MAE: 0.3411  [10,856 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4458, MAE: 0.3411  [10,856 non-zero values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 843
Overall (all)      - RMSE: 0.0258, MAE: 0.0015
Overall (non-zero) - RMSE: 0.2870, MAE: 0.2053  [22,254 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.2870, MAE: 0.2053  [22,254 non-zero values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 868

[INFO 02-14 19:14:28] ax.service.ax_client: Completed trial 98 with data: {'avg_rmse_nonzero': (np.float32(0.36697638), np.float64(0.034341))}.
[INFO 02-14 19:14:28] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_Phase(T)_checkpoint.json`.

Overall (all)      - RMSE: 0.0158, MAE: 0.0010
Overall (non-zero) - RMSE: 0.2882, MAE: 0.2022  [6,176 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.2882, MAE: 0.2022  [6,176 non-zero values]

==================================================
Cross-Validation Summary (non-zero targets only)
==================================================
Overall (all values):
  Avg Test MSE: 0.0006 (+/- 0.0002)
  Avg RMSE: 0.0239, MAE: 0.0014

Overall (non-zero only):
  Avg RMSE: 0.3670, MAE: 0.2689

Driving Force (DF, non-zero only):
  Avg RMSE: 0.0000, MAE: 0.0000

Phase Fraction (NF, non-zero only):
  Avg RMSE: 0.3670, MAE: 0.2689
Result: Non-zero RMSE = 0.3670
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_Phase(T)_checkpoint.json

============================================================
Trial 31/32
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: '0.9986567069097843'
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-14 19:14:37] ax.service.ax_client: Generated new trial 99 with parameters {'dropout_rate': 0.5, 'weight_decay': 2e-06, 'lr': 1e-05, 'optimizer_type': 'adamw', 'batch_size': 32, 'early_stopping_patience': 50, 'architecture': 'constant_1024_3L', 'activation': 'relu', 'normalization': 'none'} using model BoTorch.

Parameters: {'dropout_rate': 0.5, 'weight_decay': 1.5991981312728172e-06, 'lr': 1e-05, 'optimizer_type': 'adamw', 'batch_size': 32, 'early_stopping_patience': 50, 'architecture': 'constant_1024_3L', 'activation': 'relu', 'normalization': 'none'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 772
Overall (all)      - RMSE: 0.0273, MAE: 0.0015
Overall (non-zero) - RMSE: 0.4464, MAE: 0.3302  [11,193 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4464, MAE: 0.3302  [11,193 non-zero values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Overall (all)      - RMSE: 0.0240, MAE: 0.0015
Overall (non-zero) - RMSE: 0.3808, MAE: 0.2845  [27,977 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.3808, MAE: 0.2845  [27,977 non-zero values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Overall (all)      - RMSE: 0.0272, MAE: 0.0016
Overall (non-zero) - RMSE: 0.4482, MAE: 0.3419  [10,856 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4482, MAE: 0.3419  [10,856 non-zero values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Overall (all)      - RMSE: 0.0259, MAE: 0.0017
Overall (non-zero) - RMSE: 0.3215, MAE: 0.2507  [22,254 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.3215, MAE: 0.2507  [22,254 non-zero values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 879

[INFO 02-15 00:40:12] ax.service.ax_client: Completed trial 99 with data: {'avg_rmse_nonzero': (np.float32(0.38218355), np.float64(0.029019))}.
[INFO 02-15 00:40:12] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_Phase(T)_checkpoint.json`.

Overall (all)      - RMSE: 0.0163, MAE: 0.0010
Overall (non-zero) - RMSE: 0.3139, MAE: 0.2274  [6,176 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.3139, MAE: 0.2274  [6,176 non-zero values]

==================================================
Cross-Validation Summary (non-zero targets only)
==================================================
Overall (all values):
  Avg Test MSE: 0.0006 (+/- 0.0002)
  Avg RMSE: 0.0241, MAE: 0.0014

Overall (non-zero only):
  Avg RMSE: 0.3822, MAE: 0.2869

Driving Force (DF, non-zero only):
  Avg RMSE: 0.0000, MAE: 0.0000

Phase Fraction (NF, non-zero only):
  Avg RMSE: 0.3822, MAE: 0.2869
Result: Non-zero RMSE = 0.3822
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_Phase(T)_checkpoint.json

============================================================
Trial 32/32
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: '0.9918767776527053'
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-15 00:40:23] ax.service.ax_client: Generated new trial 100 with parameters {'dropout_rate': 0.5, 'weight_decay': 9.1e-05, 'lr': 1e-05, 'optimizer_type': 'adamw', 'batch_size': 32, 'early_stopping_patience': 48, 'architecture': 'constant_1024_3L', 'activation': 'leaky_relu', 'normalization': 'layer_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.5, 'weight_decay': 9.088122501327628e-05, 'lr': 1e-05, 'optimizer_type': 'adamw', 'batch_size': 32, 'early_stopping_patience': 48, 'architecture': 'constant_1024_3L', 'activation': 'leaky_relu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 749
Overall (all)      - RMSE: 0.0271, MAE: 0.0014
Overall (non-zero) - RMSE: 0.4377, MAE: 0.3165  [11,193 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4377, MAE: 0.3165  [11,193 non-zero values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 472
Overall (all)      - RMSE: 0.0247, MAE: 0.0015
Overall (non-zero) - RMSE: 0.3735, MAE: 0.2774  [27,977 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.3735, MAE: 0.2774  [27,977 non-zero values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 938
Overall (all)      - RMSE: 0.0273, MAE: 0.0016
Overall (non-zero) - RMSE: 0.4476, MAE: 0.3404  [10,856 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.4476, MAE: 0.3404  [10,856 non-zero values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Overall (all)      - RMSE: 0.0267, MAE: 0.0016
Overall (non-zero) - RMSE: 0.2905, MAE: 0.2008  [22,254 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.2905, MAE: 0.2008  [22,254 non-zero values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794

[INFO 02-15 06:01:21] ax.service.ax_client: Completed trial 100 with data: {'avg_rmse_nonzero': (np.float32(0.36970183), np.float64(0.033123))}.
[INFO 02-15 06:01:21] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_Phase(T)_checkpoint.json`.

Overall (all)      - RMSE: 0.0168, MAE: 0.0011
Overall (non-zero) - RMSE: 0.2993, MAE: 0.2162  [6,176 values]
Driving Force (DF) - RMSE: 0.0000, MAE: 0.0000  [0 non-zero values]
Phase Fraction (NF) - RMSE: 0.2993, MAE: 0.2162  [6,176 non-zero values]

==================================================
Cross-Validation Summary (non-zero targets only)
==================================================
Overall (all values):
  Avg Test MSE: 0.0006 (+/- 0.0002)
  Avg RMSE: 0.0245, MAE: 0.0014

Overall (non-zero only):
  Avg RMSE: 0.3697, MAE: 0.2703

Driving Force (DF, non-zero only):
  Avg RMSE: 0.0000, MAE: 0.0000

Phase Fraction (NF, non-zero only):
  Avg RMSE: 0.3697, MAE: 0.2703
Result: Non-zero RMSE = 0.3697
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_Phase(T)_checkpoint.json

============================================================
OPTIMIZATION COMPLETE
============================================================
Best parameters: {'dropout_rate': 0.5, 'weight_decay': 1e-06, 'lr': 1e-05, 'optimizer_type': 'adamw', 'batch_size': 32, 'early_stopping_patience': 50, 'architecture': 'constant_1024_3L', 'activation': 'relu', 'normalization': 'batch_norm'}
Best Non-zero RMSE: 0.3727

In [ ]:
# =====================================================================
# Ax Bayesian Optimization for Driving Force NN
# =====================================================================

# Reuse the same architecture presets
ARCHITECTURE_PRESETS_DF = {
    # Single layer
    "single_256": [256],
    "single_512": [512],
    "single_1024": [1024],
    "single_2048": [2048],
    # Two layers - expanding
    "expand_2L_small": [256, 512],
    "expand_2L_medium": [512, 1024],
    "expand_2L_large": [1024, 2048],
    "expand_2L_xlarge": [512, 2048],
    # Three layers - expanding
    "expand_3L_small": [256, 512, 1024],
    "expand_3L_medium": [512, 1024, 2048],
    "expand_3L_large": [256, 1024, 2048],
    "expand_3L_gradual": [384, 768, 1536],
    # Four layers - expanding
    "expand_4L_small": [256, 512, 1024, 2048],
    "expand_4L_medium": [512, 768, 1024, 2048],
    "expand_4L_large": [256, 512, 1024, 4096],
    # Constant width
    "constant_512": [512, 512],
    "constant_1024": [1024, 1024],
    "constant_2048": [2048, 2048],
    "constant_1024_3L": [1024, 1024, 1024],
}

ax_client_df = AxClient()
ax_client_df.create_experiment(
    name="NN opt DFnn f(T) Calphed",
    parameters=[
        {
            "name": "architecture",
            "type": "choice",
            "values": list(ARCHITECTURE_PRESETS_DF.keys()),
            "is_ordered": False,
        },
        {
            "name": "dropout_rate",
            "type": "range",
            "bounds": [0.0, 0.5],
        },
        {
            "name": "activation",
            "type": "choice",
            "values": ["relu", "leaky_relu", "elu", "selu", "gelu"],
        },
        {
            "name": "normalization",
            "type": "choice",
            "values": ["none", "batch_norm", "layer_norm"],
        },
        {
            "name": "weight_decay",
            "type": "range",
            "bounds": [1e-6, 1e-2],
            "log_scale": True,
        },
        {
            "name": "lr",
            "type": "range",
            "bounds": [1e-5, 1e-2],
            "log_scale": True,
        },
        {
            "name": "optimizer_type",
            "type": "choice",
            "values": ["adam", "adamw"],
        },
        {
            "name": "batch_size",
            "type": "choice",
            "values": [32, 64, 128, 256],
        },
        {
            "name": "early_stopping_patience",
            "type": "range",
            "bounds": [10, 50],
            "value_type": "int",
        },
    ],
    objectives={"avg_rmse_nonzero": ObjectiveProperties(minimize=True)}
)


def evaluate_for_ax_df(parameterization):
    """Wrapper to convert Ax parameters to evaluate_parameters_DFnn format."""
    # Get hidden_layers from architecture preset
    architecture = parameterization["architecture"]
    hidden_layers = ARCHITECTURE_PRESETS_DF[architecture]

    # Handle normalization choice
    normalization = parameterization["normalization"]
    use_batch_norm = normalization == "batch_norm"
    use_layer_norm = normalization == "layer_norm"

    # Handle dropout type based on activation
    activation = parameterization["activation"]
    dropout_type = "alpha" if activation == "selu" else "standard"

    # Build parameters dict
    parameters = {
        "hidden_layers": hidden_layers,
        "dropout_rate": parameterization["dropout_rate"],
        "dropout_type": dropout_type,
        "activation": activation,
        "use_batch_norm": use_batch_norm,
        "use_layer_norm": use_layer_norm,
        "weight_decay": parameterization["weight_decay"],
        "lr": parameterization["lr"],
        "optimizer_type": parameterization["optimizer_type"],
        "batch_size": parameterization["batch_size"],
        "early_stopping_patience": parameterization["early_stopping_patience"],
    }

    # Run evaluation using DFnn function
    results = evaluate_parameters_DFnn(parameters, verbose=False)

    # Calculate SEM (Standard Error of the Mean) from fold results
    rmse_nonzero_values = [r["rmse_nonzero"] for r in results["fold_results"]]
    mean_rmse_nonzero = np.mean(rmse_nonzero_values)
    std_rmse_nonzero = np.std(rmse_nonzero_values, ddof=1)
    sem_rmse_nonzero = std_rmse_nonzero / np.sqrt(len(rmse_nonzero_values))

    return {"avg_rmse_nonzero": (mean_rmse_nonzero, sem_rmse_nonzero)}


# =====================================================================
# Run the Bayesian optimization loop for Driving Force NN
# =====================================================================
n_trials_df = 32  # Adjust based on your time budget
SAVE_PATH_DF = r"Ax_checkpoints/ax_client_NN_DF(T)_checkpoint.json"

for i in range(n_trials_df):
    print(f"\n{'='*60}")
    print(f"Trial {i+1}/{n_trials_df}")
    print('='*60)

    parameters, trial_index = ax_client_df.get_next_trial()
    print(f"Parameters: {parameters}")

    try:
        result = evaluate_for_ax_df(parameters)
        ax_client_df.complete_trial(trial_index=trial_index, raw_data=result)
        print(f"Result: Non-zero RMSE = {result['avg_rmse_nonzero'][0]:.4f}")
    except Exception as e:
        print(f"Trial failed: {e}")
        ax_client_df.log_trial_failure(trial_index=trial_index)

    # Save checkpoint after each trial
    ax_client_df.save_to_json_file(SAVE_PATH_DF)
    print(f"Checkpoint saved to {SAVE_PATH_DF}")

# Get best parameters
best_parameters_df, values_df = ax_client_df.get_best_parameters()
print(f"\n{'='*60}")
print("OPTIMIZATION COMPLETE — Driving Force NN")
print('='*60)
print(f"Best parameters: {best_parameters_df}")
print(f"Best Non-zero RMSE: {values_df[0]['avg_rmse_nonzero']:.4f}")

[INFO 02-17 08:43:16] ax.service.ax_client: Starting optimization with verbose logging. To disable logging, set the `verbose_logging` argument to `False`. Note that float values in the logs are rounded to 6 decimal points.
[INFO 02-17 08:43:16] ax.service.utils.instantiation: Inferred value type of ParameterType.STRING for parameter architecture. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\service\utils\instantiation.py:258: AxParameterWarning: `sort_values` is not specified for `ChoiceParameter` "architecture". Defaulting to `False` for parameters of `ParameterType` STRING. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  return ChoiceParameter(
[INFO 02-17 08:43:16] ax.service.utils.instantiation: Inferred value type of ParameterType.FLOAT for parameter dropout_rate. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
[INFO 02-17 08:43:16] ax.service.utils.instantiation: Inferred value type of ParameterType.STRING for parameter activation. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\service\utils\instantiation.py:258: AxParameterWarning: `is_ordered` is not specified for `ChoiceParameter` "activation". Defaulting to `False`  since the parameter is a string with more than 2 choices.. To override this behavior (or avoid this warning), specify `is_ordered` during `ChoiceParameter` construction. Note that choice parameters with exactly 2 choices are always considered ordered and that the user-supplied `is_ordered` has no effect in this particular case.
  return ChoiceParameter(
c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\service\utils\instantiation.py:258: AxParameterWarning: `sort_values` is not specified for `ChoiceParameter` "activation". Defaulting to `False` for parameters of `ParameterType` STRING. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  return ChoiceParameter(
[INFO 02-17 08:43:16] ax.service.utils.instantiation: Inferred value type of ParameterType.STRING for parameter normalization. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\service\utils\instantiation.py:258: AxParameterWarning: `is_ordered` is not specified for `ChoiceParameter` "normalization". Defaulting to `False`  since the parameter is a string with more than 2 choices.. To override this behavior (or avoid this warning), specify `is_ordered` during `ChoiceParameter` construction. Note that choice parameters with exactly 2 choices are always considered ordered and that the user-supplied `is_ordered` has no effect in this particular case.
  return ChoiceParameter(
c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\service\utils\instantiation.py:258: AxParameterWarning: `sort_values` is not specified for `ChoiceParameter` "normalization". Defaulting to `False` for parameters of `ParameterType` STRING. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  return ChoiceParameter(
[INFO 02-17 08:43:16] ax.service.utils.instantiation: Inferred value type of ParameterType.FLOAT for parameter weight_decay. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
[INFO 02-17 08:43:16] ax.service.utils.instantiation: Inferred value type of ParameterType.FLOAT for parameter lr. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
[INFO 02-17 08:43:16] ax.service.utils.instantiation: Inferred value type of ParameterType.STRING for parameter optimizer_type. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\service\utils\instantiation.py:258: AxParameterWarning: `is_ordered` is not specified for `ChoiceParameter` "optimizer_type". Defaulting to `True`  since there are exactly two choices.. To override this behavior (or avoid this warning), specify `is_ordered` during `ChoiceParameter` construction. Note that choice parameters with exactly 2 choices are always considered ordered and that the user-supplied `is_ordered` has no effect in this particular case.
  return ChoiceParameter(
c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\service\utils\instantiation.py:258: AxParameterWarning: `sort_values` is not specified for `ChoiceParameter` "optimizer_type". Defaulting to `False` for parameters of `ParameterType` STRING. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  return ChoiceParameter(
[INFO 02-17 08:43:16] ax.service.utils.instantiation: Inferred value type of ParameterType.INT for parameter batch_size. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\service\utils\instantiation.py:258: AxParameterWarning: `is_ordered` is not specified for `ChoiceParameter` "batch_size". Defaulting to `True`  since the parameter is not of type string.. To override this behavior (or avoid this warning), specify `is_ordered` during `ChoiceParameter` construction. Note that choice parameters with exactly 2 choices are always considered ordered and that the user-supplied `is_ordered` has no effect in this particular case.
  return ChoiceParameter(
c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\service\utils\instantiation.py:258: AxParameterWarning: `sort_values` is not specified for `ChoiceParameter` "batch_size". Defaulting to `True` for parameters of `ParameterType` INT. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  return ChoiceParameter(
[INFO 02-17 08:43:16] ax.service.utils.instantiation: Created search space: SearchSpace(parameters=[ChoiceParameter(name='architecture', parameter_type=STRING, values=['single_256', 'single_512', 'single_1024', 'single_2048', 'expand_2L_small', 'expand_2L_medium', 'expand_2L_large', 'expand_2L_xlarge', 'expand_3L_small', 'expand_3L_medium', 'expand_3L_large', 'expand_3L_gradual', 'expand_4L_small', 'expand_4L_medium', 'expand_4L_large', 'constant_512', 'constant_1024', 'constant_2048', 'constant_1024_3L'], is_ordered=False, sort_values=False), RangeParameter(name='dropout_rate', parameter_type=FLOAT, range=[0.0, 0.5]), ChoiceParameter(name='activation', parameter_type=STRING, values=['relu', 'leaky_relu', 'elu', 'selu', 'gelu'], is_ordered=False, sort_values=False), ChoiceParameter(name='normalization', parameter_type=STRING, values=['none', 'batch_norm', 'layer_norm'], is_ordered=False, sort_values=False), RangeParameter(name='weight_decay', parameter_type=FLOAT, range=[1e-06, 0.01], log_scale=True), RangeParameter(name='lr', parameter_type=FLOAT, range=[1e-05, 0.01], log_scale=True), ChoiceParameter(name='optimizer_type', parameter_type=STRING, values=['adam', 'adamw'], is_ordered=True, sort_values=False), ChoiceParameter(name='batch_size', parameter_type=INT, values=[32, 64, 128, 256], is_ordered=True, sort_values=True), RangeParameter(name='early_stopping_patience', parameter_type=INT, range=[10, 50])], parameter_constraints=[]).
[INFO 02-17 08:43:16] ax.modelbridge.dispatch_utils: Using Models.BOTORCH_MODULAR since there is at least one ordered parameter and there are fewer than 33 choices for unordered parameters.
[INFO 02-17 08:43:16] ax.modelbridge.dispatch_utils: Calculating the number of remaining initialization trials based on num_initialization_trials=None max_initialization_trials=None num_tunable_parameters=9 num_trials=None use_batch_trials=False
[INFO 02-17 08:43:16] ax.modelbridge.dispatch_utils: calculated num_initialization_trials=18
[INFO 02-17 08:43:16] ax.modelbridge.dispatch_utils: num_completed_initialization_trials=0 num_remaining_initialization_trials=18
[INFO 02-17 08:43:16] ax.modelbridge.dispatch_utils: `verbose`, `disable_progbar`, and `jit_compile` are not yet supported when using `choose_generation_strategy` with ModularBoTorchModel, dropping these arguments.
[INFO 02-17 08:43:16] ax.modelbridge.dispatch_utils: Using Bayesian Optimization generation strategy: GenerationStrategy(name='Sobol+BoTorch', steps=[Sobol for 18 trials, BoTorch for subsequent trials]). Iterations after 18 will take longer to generate due to model-fitting.
c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\modelbridge\cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 02-17 08:43:16] ax.service.ax_client: Generated new trial 0 with parameters {'dropout_rate': 0.36588, 'weight_decay': 0.002128, 'lr': 3.8e-05, 'optimizer_type': 'adam', 'batch_size': 64, 'early_stopping_patience': 19, 'architecture': 'expand_2L_xlarge', 'activation': 'leaky_relu', 'normalization': 'layer_norm'} using model Sobol.

============================================================
Trial 1/32
============================================================
Parameters: {'dropout_rate': 0.36588019132614136, 'weight_decay': 0.002128345013887013, 'lr': 3.7883021895735e-05, 'optimizer_type': 'adam', 'batch_size': 64, 'early_stopping_patience': 19, 'architecture': 'expand_2L_xlarge', 'activation': 'leaky_relu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599

KeyboardInterrupt:

In [ ]:
# =====================================================================
# Resume Driving Force NN Bayesian Optimization to 100 trials
# =====================================================================
SAVE_PATH_DF = r"Ax_checkpoints/ax_client_NN_DF(T)_checkpoint.json"

ax_client_df = AxClient.load_from_json_file(SAVE_PATH_DF)

completed_trials = len(ax_client_df.experiment.trials)
target_trials = 100
remaining_trials = target_trials - completed_trials

print(f"Loaded {completed_trials} completed trials from checkpoint")
print(f"Remaining trials to reach {target_trials}: {remaining_trials}")

if remaining_trials > 0:
    for i in range(remaining_trials):
        current_trial = completed_trials + i + 1
        print(f"\n{'='*60}")
        print(f"Trial {current_trial}/{target_trials}")
        print('='*60)

        parameters, trial_index = ax_client_df.get_next_trial()
        print(f"Parameters: {parameters}")

        try:
            result = evaluate_for_ax_df(parameters)
            ax_client_df.complete_trial(trial_index=trial_index, raw_data=result)
            print(f"Result: Non-zero RMSE = {result['avg_rmse_nonzero'][0]:.4f}")
        except Exception as e:
            print(f"Trial failed: {e}")
            ax_client_df.log_trial_failure(trial_index=trial_index)

        # Save checkpoint after each trial
        ax_client_df.save_to_json_file(SAVE_PATH_DF)
        print(f"Checkpoint saved ({current_trial}/{target_trials})")

    best_parameters_df, values_df = ax_client_df.get_best_parameters()
    print(f"\n{'='*60}")
    print("OPTIMIZATION COMPLETE — Driving Force NN (100 trials)")
    print('='*60)
    print(f"Best parameters: {best_parameters_df}")
    print(f"Best Non-zero RMSE: {values_df[0]['avg_rmse_nonzero']:.4f}")
else:
    print("Already at or past 100 trials. No additional trials needed.")
    best_parameters_df, values_df = ax_client_df.get_best_parameters()
    print(f"Best parameters: {best_parameters_df}")
    print(f"Best Non-zero RMSE: {values_df[0]['avg_rmse_nonzero']:.4f}")

c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\storage\json_store\decoder.py:288: AxParameterWarning: `sort_values` is not specified for `ChoiceParameter` "architecture". Defaulting to `False` for parameters of `ParameterType` STRING. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  return _class(
c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\storage\json_store\decoder.py:288: AxParameterWarning: `sort_values` is not specified for `ChoiceParameter` "activation". Defaulting to `False` for parameters of `ParameterType` STRING. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  return _class(
c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\storage\json_store\decoder.py:288: AxParameterWarning: `sort_values` is not specified for `ChoiceParameter` "normalization". Defaulting to `False` for parameters of `ParameterType` STRING. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  return _class(
c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\storage\json_store\decoder.py:288: AxParameterWarning: `sort_values` is not specified for `ChoiceParameter` "optimizer_type". Defaulting to `False` for parameters of `ParameterType` STRING. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  return _class(
c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\storage\json_store\decoder.py:288: AxParameterWarning: `sort_values` is not specified for `ChoiceParameter` "batch_size". Defaulting to `True` for parameters of `ParameterType` INT. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  return _class(
[INFO 02-17 08:46:07] ax.service.ax_client: Starting optimization with verbose logging. To disable logging, set the `verbose_logging` argument to `False`. Note that float values in the logs are rounded to 6 decimal points.

Loaded 24 completed trials from checkpoint
Remaining trials to reach 100: 76

============================================================
Trial 25/100
============================================================

C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-17 08:46:13] ax.service.ax_client: Generated new trial 24 with parameters {'dropout_rate': 0.0, 'weight_decay': 2.2e-05, 'lr': 1e-05, 'optimizer_type': 'adam', 'batch_size': 32, 'early_stopping_patience': 44, 'architecture': 'constant_2048', 'activation': 'leaky_relu', 'normalization': 'layer_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.0, 'weight_decay': 2.2044587686597013e-05, 'lr': 1e-05, 'optimizer_type': 'adam', 'batch_size': 32, 'early_stopping_patience': 44, 'architecture': 'constant_2048', 'activation': 'leaky_relu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 678
Driving Force (all)      - RMSE: 1.9756, MAE: 0.7127
Driving Force (non-zero) - RMSE: 5.9091, MAE: 3.5707  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 528
Driving Force (all)      - RMSE: 2.1933, MAE: 0.7093
Driving Force (non-zero) - RMSE: 6.2318, MAE: 3.1930  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 637
Driving Force (all)      - RMSE: 1.4996, MAE: 0.5790
Driving Force (non-zero) - RMSE: 4.0700, MAE: 2.1596  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 268
Driving Force (all)      - RMSE: 2.0981, MAE: 0.7335
Driving Force (non-zero) - RMSE: 6.2346, MAE: 3.3006  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 522

[INFO 02-17 11:04:59] ax.service.ax_client: Completed trial 24 with data: {'avg_rmse_nonzero': (np.float32(5.161592), np.float64(0.603488))}.
[INFO 02-17 11:04:59] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Driving Force (all)      - RMSE: 1.9081, MAE: 0.8237
Driving Force (non-zero) - RMSE: 3.3624, MAE: 2.4307  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 3.8010 (+/- 0.8747)
  Avg RMSE: 1.9349, MAE: 0.7116

Driving Force (non-zero only):
  Avg RMSE: 5.1616, MAE: 2.9309
Result: Non-zero RMSE = 5.1616
Checkpoint saved (25/100)

============================================================
Trial 26/100
============================================================

C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-17 11:05:04] ax.service.ax_client: Generated new trial 25 with parameters {'dropout_rate': 0.0, 'weight_decay': 0.01, 'lr': 1e-05, 'optimizer_type': 'adam', 'batch_size': 256, 'early_stopping_patience': 50, 'architecture': 'expand_4L_large', 'activation': 'leaky_relu', 'normalization': 'layer_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.0, 'weight_decay': 0.01, 'lr': 1e-05, 'optimizer_type': 'adam', 'batch_size': 256, 'early_stopping_patience': 50, 'architecture': 'expand_4L_large', 'activation': 'leaky_relu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 162
Driving Force (all)      - RMSE: 1.9418, MAE: 0.5859
Driving Force (non-zero) - RMSE: 6.4246, MAE: 3.8035  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 202
Driving Force (all)      - RMSE: 2.0944, MAE: 0.5486
Driving Force (non-zero) - RMSE: 6.4177, MAE: 3.1584  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 164
Driving Force (all)      - RMSE: 1.3855, MAE: 0.4555
Driving Force (non-zero) - RMSE: 4.2657, MAE: 2.0922  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 178
Driving Force (all)      - RMSE: 2.1661, MAE: 0.6965
Driving Force (non-zero) - RMSE: 6.0312, MAE: 3.3254  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 160
Driving Force (all)      - RMSE: 1.1757, MAE: 0.5133
Driving Force (non-zero) - RMSE: 2.5299, MAE: 1.8190  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 3.2301 (+/- 1.3340)
  Avg RMSE: 1.7527, MAE: 0.5599

Driving Force (non-zero only):
  Avg RMSE: 5.1338, MAE: 2.8397

[INFO 02-17 11:19:32] ax.service.ax_client: Completed trial 25 with data: {'avg_rmse_nonzero': (np.float32(5.133836), np.float64(0.763341))}.
[INFO 02-17 11:19:32] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Result: Non-zero RMSE = 5.1338
Checkpoint saved (26/100)

============================================================
Trial 27/100
============================================================

C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-17 11:19:37] ax.service.ax_client: Generated new trial 26 with parameters {'dropout_rate': 0.312861, 'weight_decay': 0.01, 'lr': 1e-05, 'optimizer_type': 'adamw', 'batch_size': 256, 'early_stopping_patience': 50, 'architecture': 'constant_2048', 'activation': 'leaky_relu', 'normalization': 'layer_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.31286060582001124, 'weight_decay': 0.01, 'lr': 1e-05, 'optimizer_type': 'adamw', 'batch_size': 256, 'early_stopping_patience': 50, 'architecture': 'constant_2048', 'activation': 'leaky_relu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Driving Force (all)      - RMSE: 2.0189, MAE: 0.5600
Driving Force (non-zero) - RMSE: 6.8283, MAE: 4.1611  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Driving Force (all)      - RMSE: 2.0740, MAE: 0.5126
Driving Force (non-zero) - RMSE: 6.4675, MAE: 3.2413  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Driving Force (all)      - RMSE: 1.3189, MAE: 0.4042
Driving Force (non-zero) - RMSE: 4.2099, MAE: 1.9943  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Driving Force (all)      - RMSE: 2.0544, MAE: 0.6819
Driving Force (non-zero) - RMSE: 6.2834, MAE: 3.3691  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794

[INFO 02-17 12:25:18] ax.service.ax_client: Completed trial 26 with data: {'avg_rmse_nonzero': (np.float32(5.3466096), np.float64(0.754796))}.
[INFO 02-17 12:25:18] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Driving Force (all)      - RMSE: 1.3190, MAE: 0.5227
Driving Force (non-zero) - RMSE: 2.9440, MAE: 2.1741  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 3.2154 (+/- 1.2071)
  Avg RMSE: 1.7570, MAE: 0.5363

Driving Force (non-zero only):
  Avg RMSE: 5.3466, MAE: 2.9880
Result: Non-zero RMSE = 5.3466
Checkpoint saved (27/100)

============================================================
Trial 28/100
============================================================

C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-17 12:25:24] ax.service.ax_client: Generated new trial 27 with parameters {'dropout_rate': 0.0, 'weight_decay': 0.01, 'lr': 1e-05, 'optimizer_type': 'adam', 'batch_size': 32, 'early_stopping_patience': 50, 'architecture': 'expand_3L_medium', 'activation': 'leaky_relu', 'normalization': 'layer_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.0, 'weight_decay': 0.01, 'lr': 1e-05, 'optimizer_type': 'adam', 'batch_size': 32, 'early_stopping_patience': 50, 'architecture': 'expand_3L_medium', 'activation': 'leaky_relu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 68
Driving Force (all)      - RMSE: 1.9690, MAE: 0.5534
Driving Force (non-zero) - RMSE: 6.5743, MAE: 3.8939  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 73
Driving Force (all)      - RMSE: 2.0549, MAE: 0.5194
Driving Force (non-zero) - RMSE: 6.3726, MAE: 3.0670  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 68
Driving Force (all)      - RMSE: 1.3236, MAE: 0.4457
Driving Force (non-zero) - RMSE: 3.9817, MAE: 1.9668  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 68
Driving Force (all)      - RMSE: 2.0469, MAE: 0.6475
Driving Force (non-zero) - RMSE: 6.0747, MAE: 3.1834  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 68

[INFO 02-17 12:42:36] ax.service.ax_client: Completed trial 27 with data: {'avg_rmse_nonzero': (np.float32(5.1525664), np.float64(0.756891))}.
[INFO 02-17 12:42:37] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Driving Force (all)      - RMSE: 1.1552, MAE: 0.4609
Driving Force (non-zero) - RMSE: 2.7596, MAE: 2.0158  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 3.0751 (+/- 1.2635)
  Avg RMSE: 1.7099, MAE: 0.5254

Driving Force (non-zero only):
  Avg RMSE: 5.1526, MAE: 2.8254
Result: Non-zero RMSE = 5.1526
Checkpoint saved (28/100)

============================================================
Trial 29/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: 2
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-17 12:42:43] ax.service.ax_client: Generated new trial 28 with parameters {'dropout_rate': 0.0, 'weight_decay': 0.008832, 'lr': 1e-05, 'optimizer_type': 'adam', 'batch_size': 256, 'early_stopping_patience': 12, 'architecture': 'expand_4L_large', 'activation': 'gelu', 'normalization': 'layer_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.0, 'weight_decay': 0.00883154969405087, 'lr': 1e-05, 'optimizer_type': 'adam', 'batch_size': 256, 'early_stopping_patience': 12, 'architecture': 'expand_4L_large', 'activation': 'gelu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 117
Driving Force (all)      - RMSE: 1.9990, MAE: 0.5941
Driving Force (non-zero) - RMSE: 6.5796, MAE: 3.9238  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 140
Driving Force (all)      - RMSE: 2.1284, MAE: 0.5906
Driving Force (non-zero) - RMSE: 6.4484, MAE: 3.1843  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 111
Driving Force (all)      - RMSE: 1.4027, MAE: 0.4788
Driving Force (non-zero) - RMSE: 4.0760, MAE: 2.0371  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 126
Driving Force (all)      - RMSE: 1.9875, MAE: 0.5779
Driving Force (non-zero) - RMSE: 6.1890, MAE: 3.3356  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 107

[INFO 02-17 12:53:45] ax.service.ax_client: Completed trial 28 with data: {'avg_rmse_nonzero': (np.float32(5.233247), np.float64(0.745371))}.
[INFO 02-17 12:53:45] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Driving Force (all)      - RMSE: 1.2762, MAE: 0.5409
Driving Force (non-zero) - RMSE: 2.8733, MAE: 2.1118  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 3.2146 (+/- 1.1792)
  Avg RMSE: 1.7588, MAE: 0.5565

Driving Force (non-zero only):
  Avg RMSE: 5.2332, MAE: 2.9185
Result: Non-zero RMSE = 5.2332
Checkpoint saved (29/100)

============================================================
Trial 30/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: '0.4936582469759616'
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-17 12:53:52] ax.service.ax_client: Generated new trial 29 with parameters {'dropout_rate': 0.0, 'weight_decay': 2.2e-05, 'lr': 2.5e-05, 'optimizer_type': 'adam', 'batch_size': 32, 'early_stopping_patience': 30, 'architecture': 'expand_2L_medium', 'activation': 'leaky_relu', 'normalization': 'layer_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.0, 'weight_decay': 2.1618172649893174e-05, 'lr': 2.5464088941992157e-05, 'optimizer_type': 'adam', 'batch_size': 32, 'early_stopping_patience': 30, 'architecture': 'expand_2L_medium', 'activation': 'leaky_relu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 332
Driving Force (all)      - RMSE: 1.9938, MAE: 0.7049
Driving Force (non-zero) - RMSE: 6.2520, MAE: 3.7054  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 309
Driving Force (all)      - RMSE: 2.1769, MAE: 0.6949
Driving Force (non-zero) - RMSE: 6.2818, MAE: 3.2043  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 429
Driving Force (all)      - RMSE: 1.5534, MAE: 0.6294
Driving Force (non-zero) - RMSE: 4.3582, MAE: 2.3382  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 392
Driving Force (all)      - RMSE: 2.1611, MAE: 0.7430
Driving Force (non-zero) - RMSE: 6.3446, MAE: 3.3892  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 490
Driving Force (all)      - RMSE: 1.8681, MAE: 0.8710
Driving Force (non-zero) - RMSE: 3.0957, MAE: 2.3279  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 3.8574 (+/- 0.8571)
  Avg RMSE: 1.9506, MAE: 0.7287

Driving Force (non-zero only):
  Avg RMSE: 5.2664, MAE: 2.9930

[INFO 02-17 14:06:20] ax.service.ax_client: Completed trial 29 with data: {'avg_rmse_nonzero': (np.float32(5.2664332), np.float64(0.659614))}.
[INFO 02-17 14:06:20] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Result: Non-zero RMSE = 5.2664
Checkpoint saved (30/100)

============================================================
Trial 31/100
============================================================

C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-17 14:06:26] ax.service.ax_client: Generated new trial 30 with parameters {'dropout_rate': 0.0, 'weight_decay': 0.01, 'lr': 1e-05, 'optimizer_type': 'adam', 'batch_size': 256, 'early_stopping_patience': 50, 'architecture': 'expand_3L_gradual', 'activation': 'leaky_relu', 'normalization': 'layer_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.0, 'weight_decay': 0.01, 'lr': 1e-05, 'optimizer_type': 'adam', 'batch_size': 256, 'early_stopping_patience': 50, 'architecture': 'expand_3L_gradual', 'activation': 'leaky_relu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 166
Driving Force (all)      - RMSE: 1.9467, MAE: 0.5891
Driving Force (non-zero) - RMSE: 6.3146, MAE: 3.7102  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 193
Driving Force (all)      - RMSE: 2.0537, MAE: 0.5052
Driving Force (non-zero) - RMSE: 6.3530, MAE: 3.0560  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 155
Driving Force (all)      - RMSE: 1.4151, MAE: 0.5123
Driving Force (non-zero) - RMSE: 3.9806, MAE: 1.9887  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 157
Driving Force (all)      - RMSE: 1.9976, MAE: 0.5488
Driving Force (non-zero) - RMSE: 6.3330, MAE: 3.2023  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794

[INFO 02-17 14:15:43] ax.service.ax_client: Completed trial 30 with data: {'avg_rmse_nonzero': (np.float32(5.13497), np.float64(0.761681))}.

Early stopping at epoch 154
Driving Force (all)      - RMSE: 1.2712, MAE: 0.4899
Driving Force (non-zero) - RMSE: 2.6936, MAE: 1.9539  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 3.1232 (+/- 1.0883)
  Avg RMSE: 1.7369, MAE: 0.5291

Driving Force (non-zero only):
  Avg RMSE: 5.1350, MAE: 2.7822
Result: Non-zero RMSE = 5.1350

[INFO 02-17 14:15:43] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Checkpoint saved (31/100)

============================================================
Trial 32/100
============================================================

C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-17 14:15:49] ax.service.ax_client: Generated new trial 31 with parameters {'dropout_rate': 0.0, 'weight_decay': 1e-06, 'lr': 1e-05, 'optimizer_type': 'adam', 'batch_size': 256, 'early_stopping_patience': 47, 'architecture': 'expand_4L_small', 'activation': 'leaky_relu', 'normalization': 'layer_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.0, 'weight_decay': 1e-06, 'lr': 1e-05, 'optimizer_type': 'adam', 'batch_size': 256, 'early_stopping_patience': 47, 'architecture': 'expand_4L_small', 'activation': 'leaky_relu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 673
Driving Force (all)      - RMSE: 2.0473, MAE: 0.7586
Driving Force (non-zero) - RMSE: 6.1369, MAE: 3.6931  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 701
Driving Force (all)      - RMSE: 2.3249, MAE: 0.7196
Driving Force (non-zero) - RMSE: 6.7609, MAE: 3.5234  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 880
Driving Force (all)      - RMSE: 1.8414, MAE: 0.7520
Driving Force (non-zero) - RMSE: 4.5987, MAE: 2.6039  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 500
Driving Force (all)      - RMSE: 2.1074, MAE: 0.7063
Driving Force (non-zero) - RMSE: 6.2855, MAE: 3.3720  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794

[INFO 02-17 15:02:34] ax.service.ax_client: Completed trial 31 with data: {'avg_rmse_nonzero': (np.float32(5.4077272), np.float64(0.648653))}.

Early stopping at epoch 747
Driving Force (all)      - RMSE: 2.0374, MAE: 0.8599
Driving Force (non-zero) - RMSE: 3.2566, MAE: 2.3525  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 4.3158 (+/- 0.6482)
  Avg RMSE: 2.0717, MAE: 0.7593

Driving Force (non-zero only):
  Avg RMSE: 5.4077, MAE: 3.1090

[INFO 02-17 15:02:34] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Result: Non-zero RMSE = 5.4077
Checkpoint saved (32/100)

============================================================
Trial 33/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: '0.25634081421203736'
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-17 15:02:38] ax.service.ax_client: Generated new trial 32 with parameters {'dropout_rate': 0.0, 'weight_decay': 0.006688, 'lr': 1e-05, 'optimizer_type': 'adam', 'batch_size': 32, 'early_stopping_patience': 15, 'architecture': 'expand_2L_large', 'activation': 'gelu', 'normalization': 'layer_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.0, 'weight_decay': 0.006687885723135036, 'lr': 1e-05, 'optimizer_type': 'adam', 'batch_size': 32, 'early_stopping_patience': 15, 'architecture': 'expand_2L_large', 'activation': 'gelu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 34
Driving Force (all)      - RMSE: 1.9957, MAE: 0.5686
Driving Force (non-zero) - RMSE: 6.6245, MAE: 3.9707  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 41
Driving Force (all)      - RMSE: 2.0481, MAE: 0.4981
Driving Force (non-zero) - RMSE: 6.3983, MAE: 3.0631  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 36
Driving Force (all)      - RMSE: 1.3347, MAE: 0.4371
Driving Force (non-zero) - RMSE: 4.1169, MAE: 2.0250  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 36
Driving Force (all)      - RMSE: 2.0332, MAE: 0.6523
Driving Force (non-zero) - RMSE: 6.0717, MAE: 3.1729  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 33
Driving Force (all)      - RMSE: 1.1695, MAE: 0.4452
Driving Force (non-zero) - RMSE: 2.6897, MAE: 1.9586  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 3.0921 (+/- 1.2478)
  Avg RMSE: 1.7162, MAE: 0.5203

Driving Force (non-zero only):
  Avg RMSE: 5.1802, MAE: 2.8381

[INFO 02-17 15:09:40] ax.service.ax_client: Completed trial 32 with data: {'avg_rmse_nonzero': (np.float32(5.180213), np.float64(0.764767))}.
[INFO 02-17 15:09:40] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Result: Non-zero RMSE = 5.1802
Checkpoint saved (33/100)

============================================================
Trial 34/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: 1
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-17 15:09:44] ax.service.ax_client: Generated new trial 33 with parameters {'dropout_rate': 0.0, 'weight_decay': 1e-06, 'lr': 5.5e-05, 'optimizer_type': 'adam', 'batch_size': 32, 'early_stopping_patience': 50, 'architecture': 'single_2048', 'activation': 'relu', 'normalization': 'layer_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.0, 'weight_decay': 1.1145980828453324e-06, 'lr': 5.515393351452161e-05, 'optimizer_type': 'adam', 'batch_size': 32, 'early_stopping_patience': 50, 'architecture': 'single_2048', 'activation': 'relu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 278
Driving Force (all)      - RMSE: 2.2490, MAE: 0.8669
Driving Force (non-zero) - RMSE: 6.4182, MAE: 3.9303  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 578
Driving Force (all)      - RMSE: 2.3797, MAE: 0.8524
Driving Force (non-zero) - RMSE: 6.4939, MAE: 3.4368  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 692
Driving Force (all)      - RMSE: 2.0592, MAE: 0.9023
Driving Force (non-zero) - RMSE: 4.6393, MAE: 2.6520  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 397
Driving Force (all)      - RMSE: 2.5350, MAE: 1.0162
Driving Force (non-zero) - RMSE: 7.1197, MAE: 4.1564  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 545
Driving Force (all)      - RMSE: 3.1582, MAE: 1.4151
Driving Force (non-zero) - RMSE: 4.4072, MAE: 2.9192  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 6.2724 (+/- 1.9851)
  Avg RMSE: 2.4762, MAE: 1.0106

Driving Force (non-zero only):
  Avg RMSE: 5.8157, MAE: 3.4190

[INFO 02-17 16:27:19] ax.service.ax_client: Completed trial 33 with data: {'avg_rmse_nonzero': (np.float32(5.8156576), np.float64(0.54273))}.
[INFO 02-17 16:27:20] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Result: Non-zero RMSE = 5.8157
Checkpoint saved (34/100)

============================================================
Trial 35/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: 0
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-17 16:27:25] ax.service.ax_client: Generated new trial 34 with parameters {'dropout_rate': 0.0, 'weight_decay': 0.009293, 'lr': 1e-05, 'optimizer_type': 'adam', 'batch_size': 32, 'early_stopping_patience': 21, 'architecture': 'expand_4L_large', 'activation': 'leaky_relu', 'normalization': 'layer_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.0, 'weight_decay': 0.009293281318574183, 'lr': 1e-05, 'optimizer_type': 'adam', 'batch_size': 32, 'early_stopping_patience': 21, 'architecture': 'expand_4L_large', 'activation': 'leaky_relu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 43
Driving Force (all)      - RMSE: 2.0153, MAE: 0.5607
Driving Force (non-zero) - RMSE: 6.7844, MAE: 4.1066  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 46
Driving Force (all)      - RMSE: 2.1047, MAE: 0.5540
Driving Force (non-zero) - RMSE: 6.4855, MAE: 3.1773  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 40
Driving Force (all)      - RMSE: 1.3329, MAE: 0.4584
Driving Force (non-zero) - RMSE: 3.9663, MAE: 2.0445  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 43
Driving Force (all)      - RMSE: 1.9729, MAE: 0.6320
Driving Force (non-zero) - RMSE: 6.0654, MAE: 3.1985  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 37

[INFO 02-17 16:42:45] ax.service.ax_client: Completed trial 34 with data: {'avg_rmse_nonzero': (np.float32(5.170655), np.float64(0.819848))}.
[INFO 02-17 16:42:45] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Driving Force (all)      - RMSE: 1.0021, MAE: 0.4168
Driving Force (non-zero) - RMSE: 2.5517, MAE: 1.7767  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 3.0329 (+/- 1.3741)
  Avg RMSE: 1.6856, MAE: 0.5244

Driving Force (non-zero only):
  Avg RMSE: 5.1707, MAE: 2.8607
Result: Non-zero RMSE = 5.1707
Checkpoint saved (35/100)

============================================================
Trial 36/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: 2
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-17 16:42:48] ax.service.ax_client: Generated new trial 35 with parameters {'dropout_rate': 0.0, 'weight_decay': 0.000759, 'lr': 0.000139, 'optimizer_type': 'adam', 'batch_size': 32, 'early_stopping_patience': 48, 'architecture': 'expand_2L_small', 'activation': 'gelu', 'normalization': 'layer_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.0, 'weight_decay': 0.0007587024664608697, 'lr': 0.00013867121970355807, 'optimizer_type': 'adam', 'batch_size': 32, 'early_stopping_patience': 48, 'architecture': 'expand_2L_small', 'activation': 'gelu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 472
Driving Force (all)      - RMSE: 2.1087, MAE: 0.5811
Driving Force (non-zero) - RMSE: 7.1790, MAE: 4.5099  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 446
Driving Force (all)      - RMSE: 2.0935, MAE: 0.5594
Driving Force (non-zero) - RMSE: 6.2759, MAE: 3.1015  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 489
Driving Force (all)      - RMSE: 1.5379, MAE: 0.5616
Driving Force (non-zero) - RMSE: 4.1153, MAE: 2.0807  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 504
Driving Force (all)      - RMSE: 2.3408, MAE: 0.7653
Driving Force (non-zero) - RMSE: 6.2853, MAE: 3.3870  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 496
Driving Force (all)      - RMSE: 1.5211, MAE: 0.5942
Driving Force (non-zero) - RMSE: 2.8800, MAE: 2.0785  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 3.7976 (+/- 1.2527)
  Avg RMSE: 1.9204, MAE: 0.6123

Driving Force (non-zero only):
  Avg RMSE: 5.3471, MAE: 3.0315

[INFO 02-17 18:17:48] ax.service.ax_client: Completed trial 35 with data: {'avg_rmse_nonzero': (np.float32(5.3471093), np.float64(0.796969))}.
[INFO 02-17 18:17:48] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Result: Non-zero RMSE = 5.3471
Checkpoint saved (36/100)

============================================================
Trial 37/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: 0
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-17 18:17:52] ax.service.ax_client: Generated new trial 36 with parameters {'dropout_rate': 0.0, 'weight_decay': 0.01, 'lr': 1e-05, 'optimizer_type': 'adam', 'batch_size': 32, 'early_stopping_patience': 29, 'architecture': 'constant_2048', 'activation': 'leaky_relu', 'normalization': 'layer_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.0, 'weight_decay': 0.01, 'lr': 1e-05, 'optimizer_type': 'adam', 'batch_size': 32, 'early_stopping_patience': 29, 'architecture': 'constant_2048', 'activation': 'leaky_relu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 46
Driving Force (all)      - RMSE: 1.9506, MAE: 0.5284
Driving Force (non-zero) - RMSE: 6.6075, MAE: 3.9371  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 56
Driving Force (all)      - RMSE: 2.0288, MAE: 0.5010
Driving Force (non-zero) - RMSE: 6.2762, MAE: 3.0017  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 46
Driving Force (all)      - RMSE: 1.2952, MAE: 0.4356
Driving Force (non-zero) - RMSE: 3.9369, MAE: 1.9004  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 48
Driving Force (all)      - RMSE: 2.0754, MAE: 0.6710
Driving Force (non-zero) - RMSE: 6.0563, MAE: 3.2060  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 50

[INFO 02-17 18:30:33] ax.service.ax_client: Completed trial 36 with data: {'avg_rmse_nonzero': (np.float32(5.128007), np.float64(0.754316))}.
[INFO 02-17 18:30:33] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Driving Force (all)      - RMSE: 1.2329, MAE: 0.4966
Driving Force (non-zero) - RMSE: 2.7632, MAE: 2.0292  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 3.0851 (+/- 1.2252)
  Avg RMSE: 1.7166, MAE: 0.5265

Driving Force (non-zero only):
  Avg RMSE: 5.1280, MAE: 2.8149
Result: Non-zero RMSE = 5.1280
Checkpoint saved (37/100)

============================================================
Trial 38/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: 1
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-17 18:30:39] ax.service.ax_client: Generated new trial 37 with parameters {'dropout_rate': 0.0, 'weight_decay': 0.008891, 'lr': 1e-05, 'optimizer_type': 'adam', 'batch_size': 32, 'early_stopping_patience': 47, 'architecture': 'single_512', 'activation': 'leaky_relu', 'normalization': 'none'} using model BoTorch.

Parameters: {'dropout_rate': 0.0, 'weight_decay': 0.008891410091747879, 'lr': 1e-05, 'optimizer_type': 'adam', 'batch_size': 32, 'early_stopping_patience': 47, 'architecture': 'single_512', 'activation': 'leaky_relu', 'normalization': 'none'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 160
Driving Force (all)      - RMSE: 1.8969, MAE: 0.4826
Driving Force (non-zero) - RMSE: 6.4339, MAE: 3.7958  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 385
Driving Force (all)      - RMSE: 2.1661, MAE: 0.4865
Driving Force (non-zero) - RMSE: 6.8899, MAE: 3.3477  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 212
Driving Force (all)      - RMSE: 1.3737, MAE: 0.3856
Driving Force (non-zero) - RMSE: 4.3998, MAE: 2.2019  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 214
Driving Force (all)      - RMSE: 2.9817, MAE: 1.0503
Driving Force (non-zero) - RMSE: 6.6617, MAE: 3.9726  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 207
Driving Force (all)      - RMSE: 0.9558, MAE: 0.3443
Driving Force (non-zero) - RMSE: 2.8199, MAE: 2.0405  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 3.9962 (+/- 2.7765)
  Avg RMSE: 1.8748, MAE: 0.5499

Driving Force (non-zero only):
  Avg RMSE: 5.4410, MAE: 3.0717

[INFO 02-17 19:04:02] ax.service.ax_client: Completed trial 37 with data: {'avg_rmse_nonzero': (np.float32(5.441018), np.float64(0.791504))}.
[INFO 02-17 19:04:02] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Result: Non-zero RMSE = 5.4410
Checkpoint saved (38/100)

============================================================
Trial 39/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: '0.2602420818680919'
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-17 19:04:06] ax.service.ax_client: Generated new trial 38 with parameters {'dropout_rate': 0.0, 'weight_decay': 0.01, 'lr': 0.000119, 'optimizer_type': 'adamw', 'batch_size': 32, 'early_stopping_patience': 19, 'architecture': 'constant_1024', 'activation': 'leaky_relu', 'normalization': 'layer_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.0, 'weight_decay': 0.01, 'lr': 0.00011861621655537094, 'optimizer_type': 'adamw', 'batch_size': 32, 'early_stopping_patience': 19, 'architecture': 'constant_1024', 'activation': 'leaky_relu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 83
Driving Force (all)      - RMSE: 1.8968, MAE: 0.6508
Driving Force (non-zero) - RMSE: 6.0821, MAE: 3.6500  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 165
Driving Force (all)      - RMSE: 2.1808, MAE: 0.6841
Driving Force (non-zero) - RMSE: 6.3156, MAE: 3.2837  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 156
Driving Force (all)      - RMSE: 1.3933, MAE: 0.5448
Driving Force (non-zero) - RMSE: 3.9263, MAE: 2.0936  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 133
Driving Force (all)      - RMSE: 2.2896, MAE: 0.8598
Driving Force (non-zero) - RMSE: 6.2313, MAE: 3.4010  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 230

[INFO 02-17 19:30:58] ax.service.ax_client: Completed trial 38 with data: {'avg_rmse_nonzero': (np.float32(5.080453), np.float64(0.713215))}.
[INFO 02-17 19:30:58] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Driving Force (all)      - RMSE: 1.4179, MAE: 0.6782
Driving Force (non-zero) - RMSE: 2.8470, MAE: 2.0373  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 3.5095 (+/- 1.3616)
  Avg RMSE: 1.8357, MAE: 0.6835

Driving Force (non-zero only):
  Avg RMSE: 5.0805, MAE: 2.8931
Result: Non-zero RMSE = 5.0805
Checkpoint saved (39/100)

============================================================
Trial 40/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: 0
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-17 19:31:03] ax.service.ax_client: Generated new trial 39 with parameters {'dropout_rate': 0.31883, 'weight_decay': 1e-06, 'lr': 0.002887, 'optimizer_type': 'adamw', 'batch_size': 32, 'early_stopping_patience': 47, 'architecture': 'expand_4L_medium', 'activation': 'gelu', 'normalization': 'layer_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.3188298222237982, 'weight_decay': 1e-06, 'lr': 0.0028872276128898682, 'optimizer_type': 'adamw', 'batch_size': 32, 'early_stopping_patience': 47, 'architecture': 'expand_4L_medium', 'activation': 'gelu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 369
Driving Force (all)      - RMSE: 2.2512, MAE: 0.5651
Driving Force (non-zero) - RMSE: 7.6897, MAE: 5.0281  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 352
Driving Force (all)      - RMSE: 2.1325, MAE: 0.4606
Driving Force (non-zero) - RMSE: 6.7817, MAE: 3.5994  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 507
Driving Force (all)      - RMSE: 1.3795, MAE: 0.3424
Driving Force (non-zero) - RMSE: 4.2173, MAE: 2.0899  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 380
Driving Force (all)      - RMSE: 2.2960, MAE: 0.5730
Driving Force (non-zero) - RMSE: 6.5571, MAE: 3.5294  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 561

[INFO 02-17 21:37:32] ax.service.ax_client: Completed trial 39 with data: {'avg_rmse_nonzero': (np.float32(5.6329813), np.float64(0.888052))}.
[INFO 02-17 21:37:32] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Driving Force (all)      - RMSE: 1.1429, MAE: 0.3909
Driving Force (non-zero) - RMSE: 2.9192, MAE: 2.1529  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 3.6193 (+/- 1.6726)
  Avg RMSE: 1.8404, MAE: 0.4664

Driving Force (non-zero only):
  Avg RMSE: 5.6330, MAE: 3.2799
Result: Non-zero RMSE = 5.6330
Checkpoint saved (40/100)

============================================================
Trial 41/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: 2
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-17 21:37:38] ax.service.ax_client: Generated new trial 40 with parameters {'dropout_rate': 0.0, 'weight_decay': 0.01, 'lr': 1e-05, 'optimizer_type': 'adam', 'batch_size': 256, 'early_stopping_patience': 11, 'architecture': 'expand_4L_large', 'activation': 'leaky_relu', 'normalization': 'layer_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.0, 'weight_decay': 0.01, 'lr': 1e-05, 'optimizer_type': 'adam', 'batch_size': 256, 'early_stopping_patience': 11, 'architecture': 'expand_4L_large', 'activation': 'leaky_relu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 127
Driving Force (all)      - RMSE: 1.9207, MAE: 0.5713
Driving Force (non-zero) - RMSE: 6.1379, MAE: 3.5668  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 151
Driving Force (all)      - RMSE: 2.1102, MAE: 0.5656
Driving Force (non-zero) - RMSE: 6.4727, MAE: 3.2114  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 121
Driving Force (all)      - RMSE: 1.3741, MAE: 0.4602
Driving Force (non-zero) - RMSE: 4.2247, MAE: 2.1047  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 127
Driving Force (all)      - RMSE: 2.0852, MAE: 0.6353
Driving Force (non-zero) - RMSE: 6.1566, MAE: 3.2374  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 118
Driving Force (all)      - RMSE: 1.2482, MAE: 0.5248
Driving Force (non-zero) - RMSE: 3.0603, MAE: 2.3195  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 3.1874 (+/- 1.2283)
  Avg RMSE: 1.7477, MAE: 0.5514

Driving Force (non-zero only):
  Avg RMSE: 5.2104, MAE: 2.8880

[INFO 02-17 21:48:30] ax.service.ax_client: Completed trial 40 with data: {'avg_rmse_nonzero': (np.float32(5.2104497), np.float64(0.668718))}.
[INFO 02-17 21:48:30] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Result: Non-zero RMSE = 5.2104
Checkpoint saved (41/100)

============================================================
Trial 42/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: '0.019377164164459507'
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-17 21:48:34] ax.service.ax_client: Generated new trial 41 with parameters {'dropout_rate': 0.0, 'weight_decay': 2e-06, 'lr': 0.000151, 'optimizer_type': 'adam', 'batch_size': 32, 'early_stopping_patience': 25, 'architecture': 'constant_1024', 'activation': 'leaky_relu', 'normalization': 'layer_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.0, 'weight_decay': 2.0084315296179267e-06, 'lr': 0.00015141948734448844, 'optimizer_type': 'adam', 'batch_size': 32, 'early_stopping_patience': 25, 'architecture': 'constant_1024', 'activation': 'leaky_relu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 160
Driving Force (all)      - RMSE: 1.9549, MAE: 0.6514
Driving Force (non-zero) - RMSE: 6.2996, MAE: 3.7107  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 254
Driving Force (all)      - RMSE: 2.1607, MAE: 0.6590
Driving Force (non-zero) - RMSE: 6.4128, MAE: 3.2468  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 291
Driving Force (all)      - RMSE: 1.5466, MAE: 0.5865
Driving Force (non-zero) - RMSE: 4.3952, MAE: 2.2666  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 160
Driving Force (all)      - RMSE: 2.3767, MAE: 0.8784
Driving Force (non-zero) - RMSE: 6.3678, MAE: 3.4699  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 230

[INFO 02-17 22:25:01] ax.service.ax_client: Completed trial 41 with data: {'avg_rmse_nonzero': (np.float32(5.351393), np.float64(0.642539))}.
[INFO 02-17 22:25:01] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Driving Force (all)      - RMSE: 1.9620, MAE: 0.8607
Driving Force (non-zero) - RMSE: 3.2816, MAE: 2.3758  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 4.0760 (+/- 1.0747)
  Avg RMSE: 2.0002, MAE: 0.7272

Driving Force (non-zero only):
  Avg RMSE: 5.3514, MAE: 3.0140
Result: Non-zero RMSE = 5.3514
Checkpoint saved (42/100)

============================================================
Trial 43/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: '0.2312727329877409'
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-17 22:25:04] ax.service.ax_client: Generated new trial 42 with parameters {'dropout_rate': 0.0, 'weight_decay': 3e-06, 'lr': 1e-05, 'optimizer_type': 'adam', 'batch_size': 32, 'early_stopping_patience': 17, 'architecture': 'expand_2L_large', 'activation': 'selu', 'normalization': 'none'} using model BoTorch.

Parameters: {'dropout_rate': 0.0, 'weight_decay': 3.0470582226441888e-06, 'lr': 1e-05, 'optimizer_type': 'adam', 'batch_size': 32, 'early_stopping_patience': 17, 'architecture': 'expand_2L_large', 'activation': 'selu', 'normalization': 'none'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 704
Driving Force (all)      - RMSE: 5.8387, MAE: 2.3250
Driving Force (non-zero) - RMSE: 12.7265, MAE: 6.5849  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 910
Driving Force (all)      - RMSE: 3.2916, MAE: 1.3346
Driving Force (non-zero) - RMSE: 7.7549, MAE: 4.2619  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 573
Driving Force (all)      - RMSE: 2.3662, MAE: 1.0807
Driving Force (non-zero) - RMSE: 4.9756, MAE: 3.0395  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 634
Driving Force (all)      - RMSE: 4.2658, MAE: 2.0103
Driving Force (non-zero) - RMSE: 7.6804, MAE: 4.7056  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 588

[INFO 02-18 00:30:47] ax.service.ax_client: Completed trial 42 with data: {'avg_rmse_nonzero': (np.float32(7.4979525), np.float64(1.478074))}.
[INFO 02-18 00:30:47] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Driving Force (all)      - RMSE: 3.6143, MAE: 1.6974
Driving Force (non-zero) - RMSE: 4.3523, MAE: 2.7295  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 16.3569 (+/- 9.7464)
  Avg RMSE: 3.8753, MAE: 1.6896

Driving Force (non-zero only):
  Avg RMSE: 7.4980, MAE: 4.2643
Result: Non-zero RMSE = 7.4980
Checkpoint saved (43/100)

============================================================
Trial 44/100
============================================================

C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'dropout_rate': 0.0, 'weight_decay': 1.1514647916413392e-06, 'lr': 1e-05, 'optimizer_type': 'adamw', 'batch_size': 32, 'early_stopping_patience': 50, 'architecture': 'expand_3L_gradual', 'activation': 'leaky_relu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 700
Driving Force (all)      - RMSE: 2.2032, MAE: 0.8252
Driving Force (non-zero) - RMSE: 6.8057, MAE: 4.2946  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 601
Driving Force (all)      - RMSE: 2.2638, MAE: 0.7113
Driving Force (non-zero) - RMSE: 6.7615, MAE: 3.5378  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 662
Driving Force (all)      - RMSE: 1.6160, MAE: 0.6585
Driving Force (non-zero) - RMSE: 4.3428, MAE: 2.3709  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 332
Driving Force (all)      - RMSE: 2.2651, MAE: 0.8232
Driving Force (non-zero) - RMSE: 6.0644, MAE: 3.3970  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 936

[INFO 02-18 02:40:05] ax.service.ax_client: Completed trial 43 with data: {'avg_rmse_nonzero': (np.float32(5.481568), np.float64(0.679071))}.
[INFO 02-18 02:40:05] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Driving Force (all)      - RMSE: 1.8506, MAE: 0.8799
Driving Force (non-zero) - RMSE: 3.4334, MAE: 2.6204  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 4.2291 (+/- 1.0265)
  Avg RMSE: 2.0397, MAE: 0.7796

Driving Force (non-zero only):
  Avg RMSE: 5.4816, MAE: 3.2441
Result: Non-zero RMSE = 5.4816
Checkpoint saved (44/100)

============================================================
Trial 45/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: '0.30539008961610786'
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-18 02:40:11] ax.service.ax_client: Generated new trial 44 with parameters {'dropout_rate': 0.000836, 'weight_decay': 3e-06, 'lr': 0.003203, 'optimizer_type': 'adamw', 'batch_size': 32, 'early_stopping_patience': 48, 'architecture': 'expand_2L_small', 'activation': 'leaky_relu', 'normalization': 'layer_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.0008358374734566854, 'weight_decay': 2.637545870809237e-06, 'lr': 0.0032033354773190826, 'optimizer_type': 'adamw', 'batch_size': 32, 'early_stopping_patience': 48, 'architecture': 'expand_2L_small', 'activation': 'leaky_relu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 297
Driving Force (all)      - RMSE: 2.1840, MAE: 0.8868
Driving Force (non-zero) - RMSE: 6.2102, MAE: 3.9894  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 184
Driving Force (all)      - RMSE: 2.2303, MAE: 0.6858
Driving Force (non-zero) - RMSE: 6.4185, MAE: 3.3701  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 319
Driving Force (all)      - RMSE: 1.7028, MAE: 0.6169
Driving Force (non-zero) - RMSE: 4.6991, MAE: 2.5468  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 217
Driving Force (all)      - RMSE: 2.3440, MAE: 0.8476
Driving Force (non-zero) - RMSE: 6.5004, MAE: 3.5173  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 409

[INFO 02-18 03:39:29] ax.service.ax_client: Completed trial 44 with data: {'avg_rmse_nonzero': (np.float32(5.537211), np.float64(0.532908))}.
[INFO 02-18 03:39:29] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Driving Force (all)      - RMSE: 2.3686, MAE: 0.9791
Driving Force (non-zero) - RMSE: 3.8579, MAE: 2.6473  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 4.7497 (+/- 0.9766)
  Avg RMSE: 2.1660, MAE: 0.8032

Driving Force (non-zero only):
  Avg RMSE: 5.5372, MAE: 3.2142
Result: Non-zero RMSE = 5.5372
Checkpoint saved (45/100)

============================================================
Trial 46/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: '0.07242355380425158'
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-18 03:39:33] ax.service.ax_client: Generated new trial 45 with parameters {'dropout_rate': 0.0, 'weight_decay': 0.01, 'lr': 1e-05, 'optimizer_type': 'adam', 'batch_size': 32, 'early_stopping_patience': 26, 'architecture': 'single_256', 'activation': 'leaky_relu', 'normalization': 'none'} using model BoTorch.

Parameters: {'dropout_rate': 0.0, 'weight_decay': 0.01, 'lr': 1e-05, 'optimizer_type': 'adam', 'batch_size': 32, 'early_stopping_patience': 26, 'architecture': 'single_256', 'activation': 'leaky_relu', 'normalization': 'none'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 249
Driving Force (all)      - RMSE: 1.9049, MAE: 0.4764
Driving Force (non-zero) - RMSE: 6.4759, MAE: 3.8198  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 221
Driving Force (all)      - RMSE: 2.1728, MAE: 0.4884
Driving Force (non-zero) - RMSE: 6.9160, MAE: 3.3573  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 184
Driving Force (all)      - RMSE: 1.3775, MAE: 0.3890
Driving Force (non-zero) - RMSE: 4.4073, MAE: 2.2088  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 251
Driving Force (all)      - RMSE: 2.8805, MAE: 1.0152
Driving Force (non-zero) - RMSE: 6.5413, MAE: 3.8807  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 162

[INFO 02-18 04:07:38] ax.service.ax_client: Completed trial 45 with data: {'avg_rmse_nonzero': (np.float32(5.4364147), np.float64(0.783642))}.
[INFO 02-18 04:07:38] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Driving Force (all)      - RMSE: 0.9662, MAE: 0.3535
Driving Force (non-zero) - RMSE: 2.8417, MAE: 2.0587  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 3.8956 (+/- 2.5649)
  Avg RMSE: 1.8604, MAE: 0.5445

Driving Force (non-zero only):
  Avg RMSE: 5.4364, MAE: 3.0651
Result: Non-zero RMSE = 5.4364
Checkpoint saved (46/100)

============================================================
Trial 47/100
============================================================

C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-18 04:07:44] ax.service.ax_client: Generated new trial 46 with parameters {'dropout_rate': 0.0, 'weight_decay': 0.01, 'lr': 0.004628, 'optimizer_type': 'adam', 'batch_size': 32, 'early_stopping_patience': 44, 'architecture': 'constant_2048', 'activation': 'leaky_relu', 'normalization': 'layer_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.0, 'weight_decay': 0.01, 'lr': 0.004628032673571896, 'optimizer_type': 'adam', 'batch_size': 32, 'early_stopping_patience': 44, 'architecture': 'constant_2048', 'activation': 'leaky_relu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 96
Driving Force (all)      - RMSE: 1.8691, MAE: 0.4980
Driving Force (non-zero) - RMSE: 6.2872, MAE: 3.6859  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 79
Driving Force (all)      - RMSE: 2.1519, MAE: 0.4523
Driving Force (non-zero) - RMSE: 6.8647, MAE: 3.3212  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 58
Driving Force (all)      - RMSE: 1.5001, MAE: 0.4345
Driving Force (non-zero) - RMSE: 4.3367, MAE: 2.2286  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 52
Driving Force (all)      - RMSE: 2.1719, MAE: 0.6960
Driving Force (non-zero) - RMSE: 6.1227, MAE: 3.2405  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 89
Driving Force (all)      - RMSE: 0.8229, MAE: 0.2922
Driving Force (non-zero) - RMSE: 2.7382, MAE: 1.9413  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 3.1537 (+/- 1.5291)
  Avg RMSE: 1.7032, MAE: 0.4746

Driving Force (non-zero only):
  Avg RMSE: 5.2699, MAE: 2.8835

[INFO 02-18 04:27:22] ax.service.ax_client: Completed trial 46 with data: {'avg_rmse_nonzero': (np.float32(5.2699075), np.float64(0.761111))}.
[INFO 02-18 04:27:22] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Result: Non-zero RMSE = 5.2699
Checkpoint saved (47/100)

============================================================
Trial 48/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: '0.13792298627037494'
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-18 04:27:27] ax.service.ax_client: Generated new trial 47 with parameters {'dropout_rate': 0.0, 'weight_decay': 0.01, 'lr': 1e-05, 'optimizer_type': 'adamw', 'batch_size': 256, 'early_stopping_patience': 12, 'architecture': 'expand_2L_large', 'activation': 'leaky_relu', 'normalization': 'layer_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.0, 'weight_decay': 0.01, 'lr': 1e-05, 'optimizer_type': 'adamw', 'batch_size': 256, 'early_stopping_patience': 12, 'architecture': 'expand_2L_large', 'activation': 'leaky_relu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 355
Driving Force (all)      - RMSE: 2.0124, MAE: 0.7201
Driving Force (non-zero) - RMSE: 6.2042, MAE: 3.6913  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 495
Driving Force (all)      - RMSE: 2.1509, MAE: 0.6637
Driving Force (non-zero) - RMSE: 6.4603, MAE: 3.2771  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 262
Driving Force (all)      - RMSE: 1.4425, MAE: 0.5586
Driving Force (non-zero) - RMSE: 4.0307, MAE: 2.0934  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 285
Driving Force (all)      - RMSE: 2.0458, MAE: 0.6729
Driving Force (non-zero) - RMSE: 6.3469, MAE: 3.4801  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794

[INFO 02-18 04:45:57] ax.service.ax_client: Completed trial 47 with data: {'avg_rmse_nonzero': (np.float32(5.1714926), np.float64(0.740318))}.

Early stopping at epoch 301
Driving Force (all)      - RMSE: 1.5892, MAE: 0.7427
Driving Force (non-zero) - RMSE: 2.8154, MAE: 2.0774  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 3.4935 (+/- 1.0004)
  Avg RMSE: 1.8482, MAE: 0.6716

Driving Force (non-zero only):
  Avg RMSE: 5.1715, MAE: 2.9238
Result: Non-zero RMSE = 5.1715

[INFO 02-18 04:45:57] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Checkpoint saved (48/100)

============================================================
Trial 49/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: 0
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-18 04:46:01] ax.service.ax_client: Generated new trial 48 with parameters {'dropout_rate': 0.0, 'weight_decay': 0.01, 'lr': 0.008666, 'optimizer_type': 'adam', 'batch_size': 32, 'early_stopping_patience': 26, 'architecture': 'constant_1024', 'activation': 'leaky_relu', 'normalization': 'layer_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.0, 'weight_decay': 0.01, 'lr': 0.008666306905486462, 'optimizer_type': 'adam', 'batch_size': 32, 'early_stopping_patience': 26, 'architecture': 'constant_1024', 'activation': 'leaky_relu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 41
Driving Force (all)      - RMSE: 1.9572, MAE: 0.4878
Driving Force (non-zero) - RMSE: 6.6856, MAE: 4.0076  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 33
Driving Force (all)      - RMSE: 2.2165, MAE: 0.4947
Driving Force (non-zero) - RMSE: 6.9675, MAE: 3.4681  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 34
Driving Force (all)      - RMSE: 1.3628, MAE: 0.3596
Driving Force (non-zero) - RMSE: 4.3636, MAE: 2.2344  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 81
Driving Force (all)      - RMSE: 2.1281, MAE: 0.6591
Driving Force (non-zero) - RMSE: 6.1024, MAE: 3.2233  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 46
Driving Force (all)      - RMSE: 0.9023, MAE: 0.3182
Driving Force (non-zero) - RMSE: 2.8200, MAE: 2.0396  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 3.1888 (+/- 1.5870)
  Avg RMSE: 1.7134, MAE: 0.4639

Driving Force (non-zero only):
  Avg RMSE: 5.3878, MAE: 2.9946

[INFO 02-18 04:55:03] ax.service.ax_client: Completed trial 48 with data: {'avg_rmse_nonzero': (np.float32(5.38781), np.float64(0.785273))}.
[INFO 02-18 04:55:03] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Result: Non-zero RMSE = 5.3878
Checkpoint saved (49/100)

============================================================
Trial 50/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: '0.24996610847806033'
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-18 04:55:07] ax.service.ax_client: Generated new trial 49 with parameters {'dropout_rate': 0.5, 'weight_decay': 0.002731, 'lr': 1.5e-05, 'optimizer_type': 'adam', 'batch_size': 32, 'early_stopping_patience': 35, 'architecture': 'expand_4L_medium', 'activation': 'leaky_relu', 'normalization': 'layer_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.5, 'weight_decay': 0.0027314824397715633, 'lr': 1.4990541226612585e-05, 'optimizer_type': 'adam', 'batch_size': 32, 'early_stopping_patience': 35, 'architecture': 'expand_4L_medium', 'activation': 'leaky_relu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 67
Driving Force (all)      - RMSE: 2.0996, MAE: 0.5146
Driving Force (non-zero) - RMSE: 7.1790, MAE: 4.4992  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 77
Driving Force (all)      - RMSE: 2.0268, MAE: 0.4760
Driving Force (non-zero) - RMSE: 6.2353, MAE: 3.1856  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 68
Driving Force (all)      - RMSE: 1.2396, MAE: 0.3377
Driving Force (non-zero) - RMSE: 3.9948, MAE: 1.9523  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 68
Driving Force (all)      - RMSE: 2.1714, MAE: 0.6871
Driving Force (non-zero) - RMSE: 6.2339, MAE: 3.4807  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 64

[INFO 02-18 05:13:28] ax.service.ax_client: Completed trial 49 with data: {'avg_rmse_nonzero': (np.float32(5.2922716), np.float64(0.810533))}.
[INFO 02-18 05:13:28] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Driving Force (all)      - RMSE: 1.0386, MAE: 0.3511
Driving Force (non-zero) - RMSE: 2.8184, MAE: 2.0445  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 3.1693 (+/- 1.5390)
  Avg RMSE: 1.7152, MAE: 0.4733

Driving Force (non-zero only):
  Avg RMSE: 5.2923, MAE: 3.0325
Result: Non-zero RMSE = 5.2923
Checkpoint saved (50/100)

============================================================
Trial 51/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: 1
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-18 05:13:32] ax.service.ax_client: Generated new trial 50 with parameters {'dropout_rate': 0.0, 'weight_decay': 0.000101, 'lr': 1e-05, 'optimizer_type': 'adam', 'batch_size': 256, 'early_stopping_patience': 42, 'architecture': 'expand_3L_medium', 'activation': 'gelu', 'normalization': 'layer_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.0, 'weight_decay': 0.00010137933893365036, 'lr': 1e-05, 'optimizer_type': 'adam', 'batch_size': 256, 'early_stopping_patience': 42, 'architecture': 'expand_3L_medium', 'activation': 'gelu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 868
Driving Force (all)      - RMSE: 2.0603, MAE: 0.6792
Driving Force (non-zero) - RMSE: 6.4366, MAE: 3.8422  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 878
Driving Force (all)      - RMSE: 2.1125, MAE: 0.5744
Driving Force (non-zero) - RMSE: 6.4951, MAE: 3.1382  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Driving Force (all)      - RMSE: 1.4753, MAE: 0.5239
Driving Force (non-zero) - RMSE: 4.1382, MAE: 2.1303  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Driving Force (all)      - RMSE: 2.0109, MAE: 0.5503
Driving Force (non-zero) - RMSE: 6.6546, MAE: 3.4300  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794

[INFO 02-18 06:11:34] ax.service.ax_client: Completed trial 50 with data: {'avg_rmse_nonzero': (np.float32(5.3510113), np.float64(0.743041))}.
[INFO 02-18 06:11:34] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Driving Force (all)      - RMSE: 1.5876, MAE: 0.6956
Driving Force (non-zero) - RMSE: 3.0306, MAE: 2.3013  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 3.4896 (+/- 0.9473)
  Avg RMSE: 1.8493, MAE: 0.6047

Driving Force (non-zero only):
  Avg RMSE: 5.3510, MAE: 2.9684
Result: Non-zero RMSE = 5.3510
Checkpoint saved (51/100)

============================================================
Trial 52/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: 0
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-18 06:11:39] ax.service.ax_client: Generated new trial 51 with parameters {'dropout_rate': 0.0, 'weight_decay': 0.01, 'lr': 1e-05, 'optimizer_type': 'adamw', 'batch_size': 32, 'early_stopping_patience': 22, 'architecture': 'expand_4L_large', 'activation': 'gelu', 'normalization': 'layer_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.0, 'weight_decay': 0.01, 'lr': 1e-05, 'optimizer_type': 'adamw', 'batch_size': 32, 'early_stopping_patience': 22, 'architecture': 'expand_4L_large', 'activation': 'gelu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 121
Driving Force (all)      - RMSE: 2.0363, MAE: 0.7293
Driving Force (non-zero) - RMSE: 6.2439, MAE: 3.7303  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 154
Driving Force (all)      - RMSE: 2.1873, MAE: 0.6497
Driving Force (non-zero) - RMSE: 6.6398, MAE: 3.3493  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 369
Driving Force (all)      - RMSE: 1.7932, MAE: 0.7214
Driving Force (non-zero) - RMSE: 4.0671, MAE: 2.3219  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 154
Driving Force (all)      - RMSE: 2.1976, MAE: 0.7772
Driving Force (non-zero) - RMSE: 6.2737, MAE: 3.4634  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 184

[INFO 02-18 07:20:51] ax.service.ax_client: Completed trial 51 with data: {'avg_rmse_nonzero': (np.float32(5.2652106), np.float64(0.706436))}.
[INFO 02-18 07:20:51] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Driving Force (all)      - RMSE: 1.4971, MAE: 0.6674
Driving Force (non-zero) - RMSE: 3.1016, MAE: 2.3078  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 3.8435 (+/- 0.9910)
  Avg RMSE: 1.9423, MAE: 0.7090

Driving Force (non-zero only):
  Avg RMSE: 5.2652, MAE: 3.0345
Result: Non-zero RMSE = 5.2652
Checkpoint saved (52/100)

============================================================
Trial 53/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: '0.18564224528407652'
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-18 07:20:56] ax.service.ax_client: Generated new trial 52 with parameters {'dropout_rate': 0.0, 'weight_decay': 0.01, 'lr': 0.01, 'optimizer_type': 'adamw', 'batch_size': 32, 'early_stopping_patience': 18, 'architecture': 'expand_4L_large', 'activation': 'selu', 'normalization': 'layer_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.0, 'weight_decay': 0.01, 'lr': 0.01, 'optimizer_type': 'adamw', 'batch_size': 32, 'early_stopping_patience': 18, 'architecture': 'expand_4L_large', 'activation': 'selu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 86
Driving Force (all)      - RMSE: 2.1938, MAE: 0.8232
Driving Force (non-zero) - RMSE: 6.7705, MAE: 4.1941  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 123
Driving Force (all)      - RMSE: 2.3739, MAE: 0.7648
Driving Force (non-zero) - RMSE: 6.6890, MAE: 3.6313  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 68
Driving Force (all)      - RMSE: 1.6300, MAE: 0.5709
Driving Force (non-zero) - RMSE: 3.9834, MAE: 2.0637  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 89
Driving Force (all)      - RMSE: 2.1067, MAE: 0.6976
Driving Force (non-zero) - RMSE: 6.2677, MAE: 3.3160  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 96

[INFO 02-18 07:52:14] ax.service.ax_client: Completed trial 52 with data: {'avg_rmse_nonzero': (np.float32(5.2434382), np.float64(0.852911))}.
[INFO 02-18 07:52:14] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Driving Force (all)      - RMSE: 1.2341, MAE: 0.5319
Driving Force (non-zero) - RMSE: 2.5065, MAE: 1.7804  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 3.8132 (+/- 1.5028)
  Avg RMSE: 1.9077, MAE: 0.6777

Driving Force (non-zero only):
  Avg RMSE: 5.2434, MAE: 2.9971
Result: Non-zero RMSE = 5.2434
Checkpoint saved (53/100)

============================================================
Trial 54/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: '0.39705993411983154'
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-18 07:52:18] ax.service.ax_client: Generated new trial 53 with parameters {'dropout_rate': 0.0, 'weight_decay': 0.01, 'lr': 1e-05, 'optimizer_type': 'adamw', 'batch_size': 128, 'early_stopping_patience': 40, 'architecture': 'constant_2048', 'activation': 'gelu', 'normalization': 'layer_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.0, 'weight_decay': 0.01, 'lr': 1e-05, 'optimizer_type': 'adamw', 'batch_size': 128, 'early_stopping_patience': 40, 'architecture': 'constant_2048', 'activation': 'gelu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 615
Driving Force (all)      - RMSE: 1.9803, MAE: 0.7164
Driving Force (non-zero) - RMSE: 6.1931, MAE: 3.6949  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 568
Driving Force (all)      - RMSE: 2.1636, MAE: 0.6782
Driving Force (non-zero) - RMSE: 6.2958, MAE: 3.2163  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 434
Driving Force (all)      - RMSE: 1.4983, MAE: 0.5775
Driving Force (non-zero) - RMSE: 4.3815, MAE: 2.2887  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 414
Driving Force (all)      - RMSE: 2.2374, MAE: 0.7957
Driving Force (non-zero) - RMSE: 6.3198, MAE: 3.4939  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 469
Driving Force (all)      - RMSE: 1.9672, MAE: 0.8197
Driving Force (non-zero) - RMSE: 3.5073, MAE: 2.5441  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 3.9447 (+/- 0.9554)
  Avg RMSE: 1.9694, MAE: 0.7175

Driving Force (non-zero only):
  Avg RMSE: 5.3395, MAE: 3.0476

[INFO 02-18 08:36:38] ax.service.ax_client: Completed trial 53 with data: {'avg_rmse_nonzero': (np.float32(5.33949), np.float64(0.586478))}.
[INFO 02-18 08:36:38] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Result: Non-zero RMSE = 5.3395
Checkpoint saved (54/100)

============================================================
Trial 55/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: 0
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-18 08:36:42] ax.service.ax_client: Generated new trial 54 with parameters {'dropout_rate': 0.0, 'weight_decay': 8.4e-05, 'lr': 0.007125, 'optimizer_type': 'adam', 'batch_size': 256, 'early_stopping_patience': 46, 'architecture': 'expand_2L_medium', 'activation': 'leaky_relu', 'normalization': 'layer_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.0, 'weight_decay': 8.388807024268455e-05, 'lr': 0.007125230227536465, 'optimizer_type': 'adam', 'batch_size': 256, 'early_stopping_patience': 46, 'architecture': 'expand_2L_medium', 'activation': 'leaky_relu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 231
Driving Force (all)      - RMSE: 2.0434, MAE: 0.6765
Driving Force (non-zero) - RMSE: 6.3172, MAE: 3.7990  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 244
Driving Force (all)      - RMSE: 2.1152, MAE: 0.5622
Driving Force (non-zero) - RMSE: 6.2690, MAE: 3.1874  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 197
Driving Force (all)      - RMSE: 1.3473, MAE: 0.4532
Driving Force (non-zero) - RMSE: 3.9471, MAE: 2.0584  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 230
Driving Force (all)      - RMSE: 2.8924, MAE: 0.9024
Driving Force (non-zero) - RMSE: 6.5341, MAE: 3.8105  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 153
Driving Force (all)      - RMSE: 1.2961, MAE: 0.5207
Driving Force (non-zero) - RMSE: 2.6763, MAE: 1.8255  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 4.1021 (+/- 2.4257)
  Avg RMSE: 1.9389, MAE: 0.6230

Driving Force (non-zero only):
  Avg RMSE: 5.1487, MAE: 2.9362

[INFO 02-18 08:47:20] ax.service.ax_client: Completed trial 54 with data: {'avg_rmse_nonzero': (np.float32(5.1487417), np.float64(0.777697))}.
[INFO 02-18 08:47:20] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Result: Non-zero RMSE = 5.1487
Checkpoint saved (55/100)

============================================================
Trial 56/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: '0.5335632306851408'
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-18 08:47:25] ax.service.ax_client: Generated new trial 55 with parameters {'dropout_rate': 0.5, 'weight_decay': 0.01, 'lr': 1e-05, 'optimizer_type': 'adam', 'batch_size': 32, 'early_stopping_patience': 22, 'architecture': 'expand_2L_large', 'activation': 'selu', 'normalization': 'layer_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.5, 'weight_decay': 0.01, 'lr': 1e-05, 'optimizer_type': 'adam', 'batch_size': 32, 'early_stopping_patience': 22, 'architecture': 'expand_2L_large', 'activation': 'selu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 69
Driving Force (all)      - RMSE: 2.1134, MAE: 0.6801
Driving Force (non-zero) - RMSE: 6.9524, MAE: 4.2655  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 80
Driving Force (all)      - RMSE: 2.2897, MAE: 0.7363
Driving Force (non-zero) - RMSE: 6.4239, MAE: 3.3992  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 73
Driving Force (all)      - RMSE: 1.4546, MAE: 0.5642
Driving Force (non-zero) - RMSE: 4.0139, MAE: 2.1310  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 73
Driving Force (all)      - RMSE: 2.4969, MAE: 0.8502
Driving Force (non-zero) - RMSE: 6.5862, MAE: 3.8064  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 72

[INFO 02-18 09:03:27] ax.service.ax_client: Completed trial 55 with data: {'avg_rmse_nonzero': (np.float32(5.356399), np.float64(0.821833))}.
[INFO 02-18 09:03:27] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Driving Force (all)      - RMSE: 1.2403, MAE: 0.5192
Driving Force (non-zero) - RMSE: 2.8056, MAE: 1.9884  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 3.9197 (+/- 1.8073)
  Avg RMSE: 1.9190, MAE: 0.6700

Driving Force (non-zero only):
  Avg RMSE: 5.3564, MAE: 3.1181
Result: Non-zero RMSE = 5.3564
Checkpoint saved (56/100)

============================================================
Trial 57/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: 1
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-18 09:03:31] ax.service.ax_client: Generated new trial 56 with parameters {'dropout_rate': 0.0, 'weight_decay': 0.01, 'lr': 1e-05, 'optimizer_type': 'adam', 'batch_size': 32, 'early_stopping_patience': 49, 'architecture': 'single_256', 'activation': 'leaky_relu', 'normalization': 'layer_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.0, 'weight_decay': 0.01, 'lr': 1e-05, 'optimizer_type': 'adam', 'batch_size': 32, 'early_stopping_patience': 49, 'architecture': 'single_256', 'activation': 'leaky_relu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 71
Driving Force (all)      - RMSE: 2.0482, MAE: 0.5210
Driving Force (non-zero) - RMSE: 7.0145, MAE: 4.3189  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 76
Driving Force (all)      - RMSE: 2.0833, MAE: 0.4678
Driving Force (non-zero) - RMSE: 6.5686, MAE: 3.0501  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 71
Driving Force (all)      - RMSE: 1.3305, MAE: 0.4085
Driving Force (non-zero) - RMSE: 4.1337, MAE: 2.0286  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 72
Driving Force (all)      - RMSE: 2.0218, MAE: 0.5516
Driving Force (non-zero) - RMSE: 6.3304, MAE: 3.2799  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 70

[INFO 02-18 09:13:44] ax.service.ax_client: Completed trial 56 with data: {'avg_rmse_nonzero': (np.float32(5.3731894), np.float64(0.809331))}.
[INFO 02-18 09:13:44] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Driving Force (all)      - RMSE: 1.0005, MAE: 0.3677
Driving Force (non-zero) - RMSE: 2.8188, MAE: 2.0452  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 3.0788 (+/- 1.4061)
  Avg RMSE: 1.6969, MAE: 0.4633

Driving Force (non-zero only):
  Avg RMSE: 5.3732, MAE: 2.9445
Result: Non-zero RMSE = 5.3732
Checkpoint saved (57/100)

============================================================
Trial 58/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: 0
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-18 09:13:48] ax.service.ax_client: Generated new trial 57 with parameters {'dropout_rate': 0.439324, 'weight_decay': 0.01, 'lr': 8.7e-05, 'optimizer_type': 'adamw', 'batch_size': 256, 'early_stopping_patience': 10, 'architecture': 'constant_2048', 'activation': 'leaky_relu', 'normalization': 'layer_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.43932432649848324, 'weight_decay': 0.01, 'lr': 8.725675032270565e-05, 'optimizer_type': 'adamw', 'batch_size': 256, 'early_stopping_patience': 10, 'architecture': 'constant_2048', 'activation': 'leaky_relu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 211
Driving Force (all)      - RMSE: 2.0101, MAE: 0.5125
Driving Force (non-zero) - RMSE: 6.9053, MAE: 4.2282  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 192
Driving Force (all)      - RMSE: 2.0553, MAE: 0.4833
Driving Force (non-zero) - RMSE: 6.4530, MAE: 3.1725  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 219
Driving Force (all)      - RMSE: 1.2737, MAE: 0.3689
Driving Force (non-zero) - RMSE: 4.2123, MAE: 2.0020  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 278
Driving Force (all)      - RMSE: 1.9876, MAE: 0.5493
Driving Force (non-zero) - RMSE: 6.4036, MAE: 3.3677  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794

[INFO 02-18 09:28:06] ax.service.ax_client: Completed trial 57 with data: {'avg_rmse_nonzero': (np.float32(5.3735733), np.float64(0.776895))}.

Early stopping at epoch 208
Driving Force (all)      - RMSE: 1.2659, MAE: 0.4767
Driving Force (non-zero) - RMSE: 2.8936, MAE: 2.1459  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 3.0881 (+/- 1.2081)
  Avg RMSE: 1.7185, MAE: 0.4782

Driving Force (non-zero only):
  Avg RMSE: 5.3736, MAE: 2.9833
Result: Non-zero RMSE = 5.3736

[INFO 02-18 09:28:06] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Checkpoint saved (58/100)

============================================================
Trial 59/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: '0.122900653029751'
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-18 09:28:11] ax.service.ax_client: Generated new trial 58 with parameters {'dropout_rate': 0.0, 'weight_decay': 3e-06, 'lr': 0.000272, 'optimizer_type': 'adam', 'batch_size': 256, 'early_stopping_patience': 22, 'architecture': 'constant_512', 'activation': 'gelu', 'normalization': 'batch_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.0, 'weight_decay': 3.3697522611212636e-06, 'lr': 0.00027172268647199065, 'optimizer_type': 'adam', 'batch_size': 256, 'early_stopping_patience': 22, 'architecture': 'constant_512', 'activation': 'gelu', 'normalization': 'batch_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 209
Driving Force (all)      - RMSE: 5.2908, MAE: 2.2412
Driving Force (non-zero) - RMSE: 10.6477, MAE: 6.5077  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 320
Driving Force (all)      - RMSE: 3.1490, MAE: 1.1273
Driving Force (non-zero) - RMSE: 7.3816, MAE: 4.1655  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 192
Driving Force (all)      - RMSE: 2.2485, MAE: 0.8840
Driving Force (non-zero) - RMSE: 4.9859, MAE: 2.6429  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 342
Driving Force (all)      - RMSE: 6.0817, MAE: 2.5113
Driving Force (non-zero) - RMSE: 11.2412, MAE: 7.0183  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 200
Driving Force (all)      - RMSE: 2.3005, MAE: 1.0616
Driving Force (non-zero) - RMSE: 3.8418, MAE: 2.3962  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 17.0488 (+/- 13.0400)
  Avg RMSE: 3.8141, MAE: 1.5651

Driving Force (non-zero only):
  Avg RMSE: 7.6196, MAE: 4.5461

[INFO 02-18 09:42:37] ax.service.ax_client: Completed trial 58 with data: {'avg_rmse_nonzero': (np.float32(7.6196365), np.float64(1.475637))}.
[INFO 02-18 09:42:37] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Result: Non-zero RMSE = 7.6196
Checkpoint saved (59/100)

============================================================
Trial 60/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: 0
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-18 09:42:42] ax.service.ax_client: Generated new trial 59 with parameters {'dropout_rate': 0.5, 'weight_decay': 0.007501, 'lr': 0.008944, 'optimizer_type': 'adamw', 'batch_size': 32, 'early_stopping_patience': 13, 'architecture': 'expand_4L_medium', 'activation': 'leaky_relu', 'normalization': 'layer_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.5, 'weight_decay': 0.007500560011672149, 'lr': 0.008943500233297779, 'optimizer_type': 'adamw', 'batch_size': 32, 'early_stopping_patience': 13, 'architecture': 'expand_4L_medium', 'activation': 'leaky_relu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 74
Driving Force (all)      - RMSE: 1.9763, MAE: 0.5372
Driving Force (non-zero) - RMSE: 6.3297, MAE: 3.7860  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 70
Driving Force (all)      - RMSE: 2.1324, MAE: 0.4971
Driving Force (non-zero) - RMSE: 6.6997, MAE: 3.4232  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 94
Driving Force (all)      - RMSE: 1.3065, MAE: 0.3915
Driving Force (non-zero) - RMSE: 3.8645, MAE: 1.9443  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 64
Driving Force (all)      - RMSE: 2.0861, MAE: 0.5696
Driving Force (non-zero) - RMSE: 6.2898, MAE: 3.4347  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 65

[INFO 02-18 10:02:34] ax.service.ax_client: Completed trial 59 with data: {'avg_rmse_nonzero': (np.float32(5.204159), np.float64(0.777164))}.
[INFO 02-18 10:02:34] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Driving Force (all)      - RMSE: 1.0307, MAE: 0.3679
Driving Force (non-zero) - RMSE: 2.8371, MAE: 2.0631  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 3.1148 (+/- 1.4424)
  Avg RMSE: 1.7064, MAE: 0.4727

Driving Force (non-zero only):
  Avg RMSE: 5.2042, MAE: 2.9302
Result: Non-zero RMSE = 5.2042
Checkpoint saved (60/100)

============================================================
Trial 61/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: 2
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-18 10:02:38] ax.service.ax_client: Generated new trial 60 with parameters {'dropout_rate': 0.0, 'weight_decay': 0.000725, 'lr': 0.006541, 'optimizer_type': 'adam', 'batch_size': 256, 'early_stopping_patience': 31, 'architecture': 'single_1024', 'activation': 'leaky_relu', 'normalization': 'layer_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.0, 'weight_decay': 0.000725336034106832, 'lr': 0.00654065416309313, 'optimizer_type': 'adam', 'batch_size': 256, 'early_stopping_patience': 31, 'architecture': 'single_1024', 'activation': 'leaky_relu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 56
Driving Force (all)      - RMSE: 2.0424, MAE: 0.6297
Driving Force (non-zero) - RMSE: 6.7922, MAE: 4.1086  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 135
Driving Force (all)      - RMSE: 2.2115, MAE: 0.6972
Driving Force (non-zero) - RMSE: 6.2739, MAE: 3.2861  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 109
Driving Force (all)      - RMSE: 1.5799, MAE: 0.6524
Driving Force (non-zero) - RMSE: 3.9253, MAE: 2.0225  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 107
Driving Force (all)      - RMSE: 2.4992, MAE: 0.8336
Driving Force (non-zero) - RMSE: 6.5234, MAE: 3.5864  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794

[INFO 02-18 10:07:06] ax.service.ax_client: Completed trial 60 with data: {'avg_rmse_nonzero': (np.float32(5.2086563), np.float64(0.842644))}.

Early stopping at epoch 64
Driving Force (all)      - RMSE: 1.1710, MAE: 0.5080
Driving Force (non-zero) - RMSE: 2.5285, MAE: 1.7183  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 3.8351 (+/- 1.7265)
  Avg RMSE: 1.9008, MAE: 0.6642

Driving Force (non-zero only):
  Avg RMSE: 5.2087, MAE: 2.9444
Result: Non-zero RMSE = 5.2087

[INFO 02-18 10:07:06] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Checkpoint saved (61/100)

============================================================
Trial 62/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: 0
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-18 10:07:10] ax.service.ax_client: Generated new trial 61 with parameters {'dropout_rate': 0.5, 'weight_decay': 0.002211, 'lr': 0.001018, 'optimizer_type': 'adam', 'batch_size': 32, 'early_stopping_patience': 46, 'architecture': 'constant_1024_3L', 'activation': 'selu', 'normalization': 'layer_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.5, 'weight_decay': 0.002210608457631318, 'lr': 0.0010180791977475988, 'optimizer_type': 'adam', 'batch_size': 32, 'early_stopping_patience': 46, 'architecture': 'constant_1024_3L', 'activation': 'selu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 47
Driving Force (all)      - RMSE: 2.0479, MAE: 0.6887
Driving Force (non-zero) - RMSE: 6.4088, MAE: 3.9639  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 48
Driving Force (all)      - RMSE: 2.3229, MAE: 0.6623
Driving Force (non-zero) - RMSE: 6.9501, MAE: 3.6924  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 48
Driving Force (all)      - RMSE: 1.5318, MAE: 0.4843
Driving Force (non-zero) - RMSE: 4.7939, MAE: 2.7464  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 48
Driving Force (all)      - RMSE: 2.4373, MAE: 0.8737
Driving Force (non-zero) - RMSE: 6.2769, MAE: 3.5132  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 48
Driving Force (all)      - RMSE: 1.3911, MAE: 0.5215
Driving Force (non-zero) - RMSE: 3.0945, MAE: 2.2850  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 3.9624 (+/- 1.5964)
  Avg RMSE: 1.9462, MAE: 0.6461

Driving Force (non-zero only):
  Avg RMSE: 5.5049, MAE: 3.2402

[INFO 02-18 10:17:28] ax.service.ax_client: Completed trial 61 with data: {'avg_rmse_nonzero': (np.float32(5.5048556), np.float64(0.700615))}.
[INFO 02-18 10:17:28] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Result: Non-zero RMSE = 5.5049
Checkpoint saved (62/100)

============================================================
Trial 63/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: 0
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-18 10:17:33] ax.service.ax_client: Generated new trial 62 with parameters {'dropout_rate': 0.175999, 'weight_decay': 1e-06, 'lr': 1e-05, 'optimizer_type': 'adam', 'batch_size': 256, 'early_stopping_patience': 36, 'architecture': 'constant_2048', 'activation': 'leaky_relu', 'normalization': 'none'} using model BoTorch.

Parameters: {'dropout_rate': 0.1759993302110016, 'weight_decay': 1e-06, 'lr': 1e-05, 'optimizer_type': 'adam', 'batch_size': 256, 'early_stopping_patience': 36, 'architecture': 'constant_2048', 'activation': 'leaky_relu', 'normalization': 'none'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Driving Force (all)      - RMSE: 2.4923, MAE: 1.0047
Driving Force (non-zero) - RMSE: 7.1836, MAE: 4.3225  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Driving Force (all)      - RMSE: 2.1302, MAE: 0.6239
Driving Force (non-zero) - RMSE: 6.1555, MAE: 3.0630  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Driving Force (all)      - RMSE: 1.6586, MAE: 0.5572
Driving Force (non-zero) - RMSE: 4.2400, MAE: 2.0328  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Driving Force (all)      - RMSE: 2.7886, MAE: 1.1342
Driving Force (non-zero) - RMSE: 6.6477, MAE: 3.9893  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794

[INFO 02-18 11:22:11] ax.service.ax_client: Completed trial 62 with data: {'avg_rmse_nonzero': (np.float32(5.3548546), np.float64(0.859673))}.
[INFO 02-18 11:22:11] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Driving Force (all)      - RMSE: 1.2806, MAE: 0.6134
Driving Force (non-zero) - RMSE: 2.5475, MAE: 1.7870  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 4.5833 (+/- 2.2303)
  Avg RMSE: 2.0701, MAE: 0.7867

Driving Force (non-zero only):
  Avg RMSE: 5.3549, MAE: 3.0389
Result: Non-zero RMSE = 5.3549
Checkpoint saved (63/100)

============================================================
Trial 64/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: '0.9992028151869127'
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-18 11:22:16] ax.service.ax_client: Generated new trial 63 with parameters {'dropout_rate': 0.0, 'weight_decay': 0.01, 'lr': 1e-05, 'optimizer_type': 'adamw', 'batch_size': 32, 'early_stopping_patience': 16, 'architecture': 'constant_512', 'activation': 'leaky_relu', 'normalization': 'layer_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.0, 'weight_decay': 0.01, 'lr': 1e-05, 'optimizer_type': 'adamw', 'batch_size': 32, 'early_stopping_patience': 16, 'architecture': 'constant_512', 'activation': 'leaky_relu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 471
Driving Force (all)      - RMSE: 2.2458, MAE: 0.8747
Driving Force (non-zero) - RMSE: 6.5681, MAE: 3.9751  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 484
Driving Force (all)      - RMSE: 2.2422, MAE: 0.7182
Driving Force (non-zero) - RMSE: 6.6458, MAE: 3.4506  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 508
Driving Force (all)      - RMSE: 1.8599, MAE: 0.7515
Driving Force (non-zero) - RMSE: 4.5459, MAE: 2.4323  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 401
Driving Force (all)      - RMSE: 2.0909, MAE: 0.7332
Driving Force (non-zero) - RMSE: 6.2753, MAE: 3.4362  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 444

[INFO 02-18 12:46:10] ax.service.ax_client: Completed trial 63 with data: {'avg_rmse_nonzero': (np.float32(5.5042295), np.float64(0.633287))}.
[INFO 02-18 12:46:10] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Driving Force (all)      - RMSE: 2.4572, MAE: 1.0981
Driving Force (non-zero) - RMSE: 3.4861, MAE: 2.4048  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 4.7881 (+/- 0.8513)
  Avg RMSE: 2.1792, MAE: 0.8351

Driving Force (non-zero only):
  Avg RMSE: 5.5042, MAE: 3.1398
Result: Non-zero RMSE = 5.5042
Checkpoint saved (64/100)

============================================================
Trial 65/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: '0.1097670398520722'
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-18 12:46:15] ax.service.ax_client: Generated new trial 64 with parameters {'dropout_rate': 0.5, 'weight_decay': 0.01, 'lr': 1e-05, 'optimizer_type': 'adam', 'batch_size': 256, 'early_stopping_patience': 13, 'architecture': 'constant_2048', 'activation': 'leaky_relu', 'normalization': 'layer_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.5, 'weight_decay': 0.01, 'lr': 1e-05, 'optimizer_type': 'adam', 'batch_size': 256, 'early_stopping_patience': 13, 'architecture': 'constant_2048', 'activation': 'leaky_relu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 161
Driving Force (all)      - RMSE: 1.9888, MAE: 0.5362
Driving Force (non-zero) - RMSE: 6.7271, MAE: 4.0586  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 206
Driving Force (all)      - RMSE: 1.9965, MAE: 0.4776
Driving Force (non-zero) - RMSE: 6.2047, MAE: 3.0356  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 156
Driving Force (all)      - RMSE: 1.2712, MAE: 0.3754
Driving Force (non-zero) - RMSE: 4.1039, MAE: 1.9372  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 165
Driving Force (all)      - RMSE: 2.0590, MAE: 0.6337
Driving Force (non-zero) - RMSE: 6.2295, MAE: 3.2848  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794

[INFO 02-18 12:58:15] ax.service.ax_client: Completed trial 64 with data: {'avg_rmse_nonzero': (np.float32(5.2267504), np.float64(0.7428))}.

Early stopping at epoch 155
Driving Force (all)      - RMSE: 1.2423, MAE: 0.4589
Driving Force (non-zero) - RMSE: 2.8685, MAE: 2.1304  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 3.0681 (+/- 1.2195)
  Avg RMSE: 1.7116, MAE: 0.4964

Driving Force (non-zero only):
  Avg RMSE: 5.2268, MAE: 2.8893
Result: Non-zero RMSE = 5.2268

[INFO 02-18 12:58:15] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Checkpoint saved (65/100)

============================================================
Trial 66/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: '0.1402985828188147'
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-18 12:58:20] ax.service.ax_client: Generated new trial 65 with parameters {'dropout_rate': 0.007674, 'weight_decay': 7.2e-05, 'lr': 1e-05, 'optimizer_type': 'adamw', 'batch_size': 32, 'early_stopping_patience': 27, 'architecture': 'constant_1024_3L', 'activation': 'leaky_relu', 'normalization': 'layer_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.007673536182652034, 'weight_decay': 7.241034071611653e-05, 'lr': 1e-05, 'optimizer_type': 'adamw', 'batch_size': 32, 'early_stopping_patience': 27, 'architecture': 'constant_1024_3L', 'activation': 'leaky_relu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 397
Driving Force (all)      - RMSE: 1.9317, MAE: 0.6539
Driving Force (non-zero) - RMSE: 6.1512, MAE: 3.7545  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 289
Driving Force (all)      - RMSE: 2.1149, MAE: 0.5704
Driving Force (non-zero) - RMSE: 6.5174, MAE: 3.2738  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 316
Driving Force (all)      - RMSE: 1.4060, MAE: 0.5142
Driving Force (non-zero) - RMSE: 4.1537, MAE: 2.1138  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 386
Driving Force (all)      - RMSE: 2.2624, MAE: 0.8115
Driving Force (non-zero) - RMSE: 6.3643, MAE: 3.5168  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 419

[INFO 02-18 14:17:17] ax.service.ax_client: Completed trial 65 with data: {'avg_rmse_nonzero': (np.float32(5.22674), np.float64(0.712841))}.
[INFO 02-18 14:17:17] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Driving Force (all)      - RMSE: 1.3671, MAE: 0.6175
Driving Force (non-zero) - RMSE: 2.9470, MAE: 2.2046  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 3.4338 (+/- 1.3098)
  Avg RMSE: 1.8164, MAE: 0.6335

Driving Force (non-zero only):
  Avg RMSE: 5.2267, MAE: 2.9727
Result: Non-zero RMSE = 5.2267
Checkpoint saved (66/100)

============================================================
Trial 67/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: '0.6607979517758598'
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-18 14:17:22] ax.service.ax_client: Generated new trial 66 with parameters {'dropout_rate': 0.0, 'weight_decay': 9e-06, 'lr': 2.3e-05, 'optimizer_type': 'adamw', 'batch_size': 32, 'early_stopping_patience': 48, 'architecture': 'expand_2L_xlarge', 'activation': 'leaky_relu', 'normalization': 'layer_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.0, 'weight_decay': 8.759856082004416e-06, 'lr': 2.2529498870636164e-05, 'optimizer_type': 'adamw', 'batch_size': 32, 'early_stopping_patience': 48, 'architecture': 'expand_2L_xlarge', 'activation': 'leaky_relu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 502
Driving Force (all)      - RMSE: 2.1527, MAE: 0.8816
Driving Force (non-zero) - RMSE: 6.2717, MAE: 3.8392  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 401
Driving Force (all)      - RMSE: 2.2590, MAE: 0.7730
Driving Force (non-zero) - RMSE: 6.3361, MAE: 3.2284  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 521
Driving Force (all)      - RMSE: 1.6649, MAE: 0.6782
Driving Force (non-zero) - RMSE: 4.2674, MAE: 2.3765  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 284
Driving Force (all)      - RMSE: 2.2177, MAE: 0.8514
Driving Force (non-zero) - RMSE: 6.1331, MAE: 3.4114  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 586

[INFO 02-18 15:39:19] ax.service.ax_client: Completed trial 66 with data: {'avg_rmse_nonzero': (np.float32(5.2719245), np.float64(0.615278))}.
[INFO 02-18 15:39:19] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Driving Force (all)      - RMSE: 1.8463, MAE: 0.8895
Driving Force (non-zero) - RMSE: 3.3513, MAE: 2.4699  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 4.1672 (+/- 0.9143)
  Avg RMSE: 2.0281, MAE: 0.8147

Driving Force (non-zero only):
  Avg RMSE: 5.2719, MAE: 3.0651
Result: Non-zero RMSE = 5.2719
Checkpoint saved (67/100)

============================================================
Trial 68/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: '0.06912847497004018'
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-18 15:39:24] ax.service.ax_client: Generated new trial 67 with parameters {'dropout_rate': 0.0, 'weight_decay': 0.000403, 'lr': 2.6e-05, 'optimizer_type': 'adam', 'batch_size': 256, 'early_stopping_patience': 16, 'architecture': 'single_512', 'activation': 'leaky_relu', 'normalization': 'layer_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.0, 'weight_decay': 0.00040264932409508295, 'lr': 2.617088987342564e-05, 'optimizer_type': 'adam', 'batch_size': 256, 'early_stopping_patience': 16, 'architecture': 'single_512', 'activation': 'leaky_relu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 884
Driving Force (all)      - RMSE: 2.0417, MAE: 0.6752
Driving Force (non-zero) - RMSE: 6.6683, MAE: 3.9475  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Driving Force (all)      - RMSE: 2.0676, MAE: 0.5946
Driving Force (non-zero) - RMSE: 6.2032, MAE: 3.1301  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 979
Driving Force (all)      - RMSE: 1.4445, MAE: 0.5259
Driving Force (non-zero) - RMSE: 4.1765, MAE: 2.0688  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Driving Force (all)      - RMSE: 2.2074, MAE: 0.8005
Driving Force (non-zero) - RMSE: 6.4381, MAE: 3.3396  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794

[INFO 02-18 16:27:05] ax.service.ax_client: Completed trial 67 with data: {'avg_rmse_nonzero': (np.float32(5.2982435), np.float64(0.724976))}.
[INFO 02-18 16:27:05] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Driving Force (all)      - RMSE: 1.4461, MAE: 0.6527
Driving Force (non-zero) - RMSE: 3.0052, MAE: 2.2316  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 3.4988 (+/- 1.1760)
  Avg RMSE: 1.8415, MAE: 0.6498

Driving Force (non-zero only):
  Avg RMSE: 5.2982, MAE: 2.9435
Result: Non-zero RMSE = 5.2982
Checkpoint saved (68/100)

============================================================
Trial 69/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: 0
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-18 16:27:09] ax.service.ax_client: Generated new trial 68 with parameters {'dropout_rate': 0.0, 'weight_decay': 0.01, 'lr': 1e-05, 'optimizer_type': 'adamw', 'batch_size': 64, 'early_stopping_patience': 14, 'architecture': 'constant_1024', 'activation': 'elu', 'normalization': 'layer_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.0, 'weight_decay': 0.01, 'lr': 1e-05, 'optimizer_type': 'adamw', 'batch_size': 64, 'early_stopping_patience': 14, 'architecture': 'constant_1024', 'activation': 'elu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 209
Driving Force (all)      - RMSE: 2.1728, MAE: 0.8160
Driving Force (non-zero) - RMSE: 6.5320, MAE: 4.0459  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 245
Driving Force (all)      - RMSE: 2.1601, MAE: 0.6913
Driving Force (non-zero) - RMSE: 6.2983, MAE: 3.2207  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 337
Driving Force (all)      - RMSE: 1.5242, MAE: 0.6119
Driving Force (non-zero) - RMSE: 4.3025, MAE: 2.3171  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 296
Driving Force (all)      - RMSE: 2.2654, MAE: 0.7936
Driving Force (non-zero) - RMSE: 6.2295, MAE: 3.3732  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 370
Driving Force (all)      - RMSE: 1.9465, MAE: 0.9067
Driving Force (non-zero) - RMSE: 3.1215, MAE: 2.3031  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 4.1263 (+/- 1.0022)
  Avg RMSE: 2.0138, MAE: 0.7639

Driving Force (non-zero only):
  Avg RMSE: 5.2968, MAE: 3.0520

[INFO 02-18 16:56:22] ax.service.ax_client: Completed trial 68 with data: {'avg_rmse_nonzero': (np.float32(5.2967744), np.float64(0.675249))}.
[INFO 02-18 16:56:22] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Result: Non-zero RMSE = 5.2968
Checkpoint saved (69/100)

============================================================
Trial 70/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: 2
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-18 16:56:28] ax.service.ax_client: Generated new trial 69 with parameters {'dropout_rate': 0.5, 'weight_decay': 0.01, 'lr': 1e-05, 'optimizer_type': 'adam', 'batch_size': 256, 'early_stopping_patience': 23, 'architecture': 'single_256', 'activation': 'leaky_relu', 'normalization': 'layer_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.5, 'weight_decay': 0.01, 'lr': 1e-05, 'optimizer_type': 'adam', 'batch_size': 256, 'early_stopping_patience': 23, 'architecture': 'single_256', 'activation': 'leaky_relu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 172
Driving Force (all)      - RMSE: 2.0467, MAE: 0.5258
Driving Force (non-zero) - RMSE: 6.9934, MAE: 4.3004  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 218
Driving Force (all)      - RMSE: 2.0770, MAE: 0.4639
Driving Force (non-zero) - RMSE: 6.5461, MAE: 3.0465  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 165
Driving Force (all)      - RMSE: 1.3661, MAE: 0.4251
Driving Force (non-zero) - RMSE: 4.1754, MAE: 2.0684  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 178
Driving Force (all)      - RMSE: 2.0734, MAE: 0.5840
Driving Force (non-zero) - RMSE: 6.3017, MAE: 3.3113  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794

[INFO 02-18 17:04:58] ax.service.ax_client: Completed trial 69 with data: {'avg_rmse_nonzero': (np.float32(5.371114), np.float64(0.797485))}.

Early stopping at epoch 165
Driving Force (all)      - RMSE: 0.9713, MAE: 0.3530
Driving Force (non-zero) - RMSE: 2.8390, MAE: 2.0691  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 3.1223 (+/- 1.4330)
  Avg RMSE: 1.7069, MAE: 0.4704

Driving Force (non-zero only):
  Avg RMSE: 5.3711, MAE: 2.9591
Result: Non-zero RMSE = 5.3711

[INFO 02-18 17:04:58] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Checkpoint saved (70/100)

============================================================
Trial 71/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: 0
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-18 17:05:02] ax.service.ax_client: Generated new trial 70 with parameters {'dropout_rate': 0.435821, 'weight_decay': 0.01, 'lr': 0.000128, 'optimizer_type': 'adamw', 'batch_size': 256, 'early_stopping_patience': 46, 'architecture': 'expand_3L_medium', 'activation': 'elu', 'normalization': 'layer_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.43582066645059164, 'weight_decay': 0.01, 'lr': 0.00012766031611068088, 'optimizer_type': 'adamw', 'batch_size': 256, 'early_stopping_patience': 46, 'architecture': 'expand_3L_medium', 'activation': 'elu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 894
Driving Force (all)      - RMSE: 1.9713, MAE: 0.5777
Driving Force (non-zero) - RMSE: 6.4621, MAE: 3.8621  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 793
Driving Force (all)      - RMSE: 2.0610, MAE: 0.4853
Driving Force (non-zero) - RMSE: 6.4053, MAE: 3.1630  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 714
Driving Force (all)      - RMSE: 1.3064, MAE: 0.3848
Driving Force (non-zero) - RMSE: 4.0179, MAE: 1.9338  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 801
Driving Force (all)      - RMSE: 2.0558, MAE: 0.5426
Driving Force (non-zero) - RMSE: 6.3660, MAE: 3.3199  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 852
Driving Force (all)      - RMSE: 1.2559, MAE: 0.4376
Driving Force (non-zero) - RMSE: 3.0154, MAE: 2.2379  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 3.1287 (+/- 1.2214)
  Avg RMSE: 1.7301, MAE: 0.4856

Driving Force (non-zero only):
  Avg RMSE: 5.2533, MAE: 2.9034

[INFO 02-18 17:55:06] ax.service.ax_client: Completed trial 70 with data: {'avg_rmse_nonzero': (np.float32(5.25335), np.float64(0.726674))}.
[INFO 02-18 17:55:07] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Result: Non-zero RMSE = 5.2533
Checkpoint saved (71/100)

============================================================
Trial 72/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: 0
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'dropout_rate': 0.1690837338563216, 'weight_decay': 0.00015739533618695537, 'lr': 5.509378828519282e-05, 'optimizer_type': 'adam', 'batch_size': 32, 'early_stopping_patience': 46, 'architecture': 'expand_4L_small', 'activation': 'elu', 'normalization': 'none'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 559
Driving Force (all)      - RMSE: 1.9095, MAE: 0.5335
Driving Force (non-zero) - RMSE: 6.2747, MAE: 3.7433  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 737
Driving Force (all)      - RMSE: 2.0683, MAE: 0.4932
Driving Force (non-zero) - RMSE: 6.4048, MAE: 3.2758  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 651
Driving Force (all)      - RMSE: 1.3618, MAE: 0.4329
Driving Force (non-zero) - RMSE: 4.0205, MAE: 2.0149  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 708
Driving Force (all)      - RMSE: 2.1603, MAE: 0.6009
Driving Force (non-zero) - RMSE: 6.0610, MAE: 3.2520  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 527

[INFO 02-18 20:35:33] ax.service.ax_client: Completed trial 71 with data: {'avg_rmse_nonzero': (np.float32(5.109593), np.float64(0.72529))}.

Driving Force (all)      - RMSE: 1.1650, MAE: 0.4573
Driving Force (non-zero) - RMSE: 2.7870, MAE: 2.0391  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 3.1606 (+/- 1.3200)
  Avg RMSE: 1.7330, MAE: 0.5036

Driving Force (non-zero only):
  Avg RMSE: 5.1096, MAE: 2.8650
Result: Non-zero RMSE = 5.1096

[INFO 02-18 20:35:34] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Checkpoint saved (72/100)

============================================================
Trial 73/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: 1
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-18 20:35:48] ax.service.ax_client: Generated new trial 72 with parameters {'dropout_rate': 0.5, 'weight_decay': 0.01, 'lr': 1e-05, 'optimizer_type': 'adam', 'batch_size': 64, 'early_stopping_patience': 30, 'architecture': 'single_512', 'activation': 'leaky_relu', 'normalization': 'layer_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.5, 'weight_decay': 0.01, 'lr': 1e-05, 'optimizer_type': 'adam', 'batch_size': 64, 'early_stopping_patience': 30, 'architecture': 'single_512', 'activation': 'leaky_relu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 75
Driving Force (all)      - RMSE: 2.0237, MAE: 0.5283
Driving Force (non-zero) - RMSE: 6.8928, MAE: 4.2046  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 87
Driving Force (all)      - RMSE: 2.0630, MAE: 0.4740
Driving Force (non-zero) - RMSE: 6.4592, MAE: 2.9979  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 75
Driving Force (all)      - RMSE: 1.3451, MAE: 0.4187
Driving Force (non-zero) - RMSE: 4.1824, MAE: 2.0608  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 77
Driving Force (all)      - RMSE: 2.1176, MAE: 0.6035
Driving Force (non-zero) - RMSE: 6.2781, MAE: 3.3555  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 72

[INFO 02-18 20:49:25] ax.service.ax_client: Completed trial 72 with data: {'avg_rmse_nonzero': (np.float32(5.3208637), np.float64(0.78661))}.

Driving Force (all)      - RMSE: 1.0136, MAE: 0.3797
Driving Force (non-zero) - RMSE: 2.7918, MAE: 2.0288  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 3.1344 (+/- 1.4282)
  Avg RMSE: 1.7126, MAE: 0.4809

Driving Force (non-zero only):
  Avg RMSE: 5.3209, MAE: 2.9295
Result: Non-zero RMSE = 5.3209

[INFO 02-18 20:49:25] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Checkpoint saved (73/100)

============================================================
Trial 74/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: 0
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-18 20:49:37] ax.service.ax_client: Generated new trial 73 with parameters {'dropout_rate': 0.0, 'weight_decay': 0.007399, 'lr': 0.004115, 'optimizer_type': 'adamw', 'batch_size': 256, 'early_stopping_patience': 12, 'architecture': 'constant_512', 'activation': 'leaky_relu', 'normalization': 'none'} using model BoTorch.

Parameters: {'dropout_rate': 0.0, 'weight_decay': 0.007398801143656821, 'lr': 0.004115029892037479, 'optimizer_type': 'adamw', 'batch_size': 256, 'early_stopping_patience': 12, 'architecture': 'constant_512', 'activation': 'leaky_relu', 'normalization': 'none'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 59
Driving Force (all)      - RMSE: 6.0404, MAE: 2.1022
Driving Force (non-zero) - RMSE: 12.8224, MAE: 6.8761  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 56
Driving Force (all)      - RMSE: 2.2630, MAE: 0.7146
Driving Force (non-zero) - RMSE: 6.3569, MAE: 3.3558  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 70
Driving Force (all)      - RMSE: 2.8000, MAE: 0.8162
Driving Force (non-zero) - RMSE: 6.0284, MAE: 2.4533  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 80
Driving Force (all)      - RMSE: 8.5933, MAE: 2.4252
Driving Force (non-zero) - RMSE: 15.0695, MAE: 7.0443  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 88
Driving Force (all)      - RMSE: 2.0755, MAE: 0.8732
Driving Force (non-zero) - RMSE: 3.7870, MAE: 2.5898  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 25.5199 (+/- 26.9597)
  Avg RMSE: 4.3544, MAE: 1.3863

Driving Force (non-zero only):
  Avg RMSE: 8.8128, MAE: 4.4639

[INFO 02-18 20:56:05] ax.service.ax_client: Completed trial 73 with data: {'avg_rmse_nonzero': (np.float32(8.812816), np.float64(2.171023))}.
[INFO 02-18 20:56:05] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Result: Non-zero RMSE = 8.8128
Checkpoint saved (74/100)

============================================================
Trial 75/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: 0
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-18 20:56:17] ax.service.ax_client: Generated new trial 74 with parameters {'dropout_rate': 0.5, 'weight_decay': 2e-06, 'lr': 1e-05, 'optimizer_type': 'adamw', 'batch_size': 32, 'early_stopping_patience': 36, 'architecture': 'expand_4L_large', 'activation': 'elu', 'normalization': 'layer_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.5, 'weight_decay': 2.480931119166254e-06, 'lr': 1e-05, 'optimizer_type': 'adamw', 'batch_size': 32, 'early_stopping_patience': 36, 'architecture': 'expand_4L_large', 'activation': 'elu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Driving Force (all)      - RMSE: 2.0725, MAE: 0.5795
Driving Force (non-zero) - RMSE: 6.8968, MAE: 4.2489  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Driving Force (all)      - RMSE: 2.0773, MAE: 0.4793
Driving Force (non-zero) - RMSE: 6.4359, MAE: 3.2222  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Driving Force (all)      - RMSE: 1.3073, MAE: 0.3799
Driving Force (non-zero) - RMSE: 4.0529, MAE: 1.9447  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Driving Force (all)      - RMSE: 2.2259, MAE: 0.6327
Driving Force (non-zero) - RMSE: 6.3579, MAE: 3.5479  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794

[INFO 02-19 03:12:33] ax.service.ax_client: Completed trial 74 with data: {'avg_rmse_nonzero': (np.float32(5.3524218), np.float64(0.765026))}.
[INFO 02-19 03:12:33] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Driving Force (all)      - RMSE: 1.2688, MAE: 0.4256
Driving Force (non-zero) - RMSE: 3.0186, MAE: 2.2380  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 3.3768 (+/- 1.4224)
  Avg RMSE: 1.7904, MAE: 0.4994

Driving Force (non-zero only):
  Avg RMSE: 5.3524, MAE: 3.0403
Result: Non-zero RMSE = 5.3524
Checkpoint saved (75/100)

============================================================
Trial 76/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: '0.02365294957539382'
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-19 03:12:38] ax.service.ax_client: Generated new trial 75 with parameters {'dropout_rate': 0.025461, 'weight_decay': 1e-06, 'lr': 1.1e-05, 'optimizer_type': 'adam', 'batch_size': 256, 'early_stopping_patience': 48, 'architecture': 'expand_3L_medium', 'activation': 'leaky_relu', 'normalization': 'layer_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.025461083443859653, 'weight_decay': 1e-06, 'lr': 1.0544158363998748e-05, 'optimizer_type': 'adam', 'batch_size': 256, 'early_stopping_patience': 48, 'architecture': 'expand_3L_medium', 'activation': 'leaky_relu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Driving Force (all)      - RMSE: 1.8646, MAE: 0.5648
Driving Force (non-zero) - RMSE: 6.1200, MAE: 3.5560  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Driving Force (all)      - RMSE: 2.0802, MAE: 0.5215
Driving Force (non-zero) - RMSE: 6.4509, MAE: 3.1825  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 958
Driving Force (all)      - RMSE: 1.3661, MAE: 0.4397
Driving Force (non-zero) - RMSE: 4.2802, MAE: 2.1425  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 920
Driving Force (all)      - RMSE: 2.1197, MAE: 0.7081
Driving Force (non-zero) - RMSE: 6.2984, MAE: 3.4149  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794

[INFO 02-19 04:18:43] ax.service.ax_client: Completed trial 75 with data: {'avg_rmse_nonzero': (np.float32(5.197589), np.float64(0.708551))}.
[INFO 02-19 04:18:43] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Driving Force (all)      - RMSE: 1.2954, MAE: 0.5605
Driving Force (non-zero) - RMSE: 2.8384, MAE: 2.1084  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 3.1682 (+/- 1.1924)
  Avg RMSE: 1.7452, MAE: 0.5589

Driving Force (non-zero only):
  Avg RMSE: 5.1976, MAE: 2.8809
Result: Non-zero RMSE = 5.1976
Checkpoint saved (76/100)

============================================================
Trial 77/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: 1
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-19 04:18:51] ax.service.ax_client: Generated new trial 76 with parameters {'dropout_rate': 0.000484, 'weight_decay': 0.01, 'lr': 1e-05, 'optimizer_type': 'adam', 'batch_size': 256, 'early_stopping_patience': 15, 'architecture': 'expand_2L_medium', 'activation': 'leaky_relu', 'normalization': 'batch_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.00048365322946408804, 'weight_decay': 0.01, 'lr': 1e-05, 'optimizer_type': 'adam', 'batch_size': 256, 'early_stopping_patience': 15, 'architecture': 'expand_2L_medium', 'activation': 'leaky_relu', 'normalization': 'batch_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 156
Driving Force (all)      - RMSE: 2.8984, MAE: 1.1641
Driving Force (non-zero) - RMSE: 7.9675, MAE: 4.8823  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 215
Driving Force (all)      - RMSE: 2.3459, MAE: 0.7275
Driving Force (non-zero) - RMSE: 6.3701, MAE: 3.2963  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 146
Driving Force (all)      - RMSE: 1.5796, MAE: 0.5933
Driving Force (non-zero) - RMSE: 4.0766, MAE: 2.1495  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 128
Driving Force (all)      - RMSE: 3.5314, MAE: 1.6192
Driving Force (non-zero) - RMSE: 7.1788, MAE: 4.4590  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 151
Driving Force (all)      - RMSE: 1.6523, MAE: 0.7394
Driving Force (non-zero) - RMSE: 2.7102, MAE: 1.9166  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 6.3200 (+/- 3.7510)
  Avg RMSE: 2.4015, MAE: 0.9687

Driving Force (non-zero only):
  Avg RMSE: 5.6606, MAE: 3.3407

[INFO 02-19 04:28:41] ax.service.ax_client: Completed trial 76 with data: {'avg_rmse_nonzero': (np.float32(5.660647), np.float64(0.983453))}.
[INFO 02-19 04:28:41] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Result: Non-zero RMSE = 5.6606
Checkpoint saved (77/100)

============================================================
Trial 78/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: 2
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-19 04:28:48] ax.service.ax_client: Generated new trial 77 with parameters {'dropout_rate': 0.040345, 'weight_decay': 0.01, 'lr': 1e-05, 'optimizer_type': 'adam', 'batch_size': 256, 'early_stopping_patience': 11, 'architecture': 'expand_2L_large', 'activation': 'gelu', 'normalization': 'layer_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.04034542895664494, 'weight_decay': 0.01, 'lr': 1e-05, 'optimizer_type': 'adam', 'batch_size': 256, 'early_stopping_patience': 11, 'architecture': 'expand_2L_large', 'activation': 'gelu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 128
Driving Force (all)      - RMSE: 1.9738, MAE: 0.5258
Driving Force (non-zero) - RMSE: 6.6973, MAE: 4.0267  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 151
Driving Force (all)      - RMSE: 2.0444, MAE: 0.5130
Driving Force (non-zero) - RMSE: 6.2526, MAE: 3.0946  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 122
Driving Force (all)      - RMSE: 1.2881, MAE: 0.4161
Driving Force (non-zero) - RMSE: 3.9769, MAE: 1.9017  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 120
Driving Force (all)      - RMSE: 2.1503, MAE: 0.7148
Driving Force (non-zero) - RMSE: 6.1174, MAE: 3.3412  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 126
Driving Force (all)      - RMSE: 1.1959, MAE: 0.4498
Driving Force (non-zero) - RMSE: 2.7105, MAE: 1.9640  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 3.1577 (+/- 1.3394)
  Avg RMSE: 1.7305, MAE: 0.5239

Driving Force (non-zero only):
  Avg RMSE: 5.1509, MAE: 2.8657

[INFO 02-19 04:37:17] ax.service.ax_client: Completed trial 77 with data: {'avg_rmse_nonzero': (np.float32(5.1509233), np.float64(0.77049))}.
[INFO 02-19 04:37:17] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Result: Non-zero RMSE = 5.1509
Checkpoint saved (78/100)

============================================================
Trial 79/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: 2
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-19 04:37:22] ax.service.ax_client: Generated new trial 78 with parameters {'dropout_rate': 0.0, 'weight_decay': 2.2e-05, 'lr': 1.7e-05, 'optimizer_type': 'adam', 'batch_size': 256, 'early_stopping_patience': 10, 'architecture': 'constant_1024', 'activation': 'leaky_relu', 'normalization': 'layer_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.0, 'weight_decay': 2.158381414493367e-05, 'lr': 1.742805708843922e-05, 'optimizer_type': 'adam', 'batch_size': 256, 'early_stopping_patience': 10, 'architecture': 'constant_1024', 'activation': 'leaky_relu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 278
Driving Force (all)      - RMSE: 2.1494, MAE: 0.7546
Driving Force (non-zero) - RMSE: 6.7157, MAE: 4.0223  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 378
Driving Force (all)      - RMSE: 2.1974, MAE: 0.6547
Driving Force (non-zero) - RMSE: 6.6662, MAE: 3.4341  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 318
Driving Force (all)      - RMSE: 1.4774, MAE: 0.5790
Driving Force (non-zero) - RMSE: 4.0589, MAE: 2.1390  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 304
Driving Force (all)      - RMSE: 2.0984, MAE: 0.7175
Driving Force (non-zero) - RMSE: 6.0896, MAE: 3.2919  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 347
Driving Force (all)      - RMSE: 1.6581, MAE: 0.7651
Driving Force (non-zero) - RMSE: 3.0358, MAE: 2.2136  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 3.7567 (+/- 1.0773)
  Avg RMSE: 1.9161, MAE: 0.6942

Driving Force (non-zero only):
  Avg RMSE: 5.3132, MAE: 3.0202

[INFO 02-19 04:55:40] ax.service.ax_client: Completed trial 78 with data: {'avg_rmse_nonzero': (np.float32(5.3132296), np.float64(0.747006))}.
[INFO 02-19 04:55:40] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Result: Non-zero RMSE = 5.3132
Checkpoint saved (79/100)

============================================================
Trial 80/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: '0.14199148352139154'
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-19 04:55:45] ax.service.ax_client: Generated new trial 79 with parameters {'dropout_rate': 0.309363, 'weight_decay': 3e-06, 'lr': 1e-05, 'optimizer_type': 'adam', 'batch_size': 32, 'early_stopping_patience': 37, 'architecture': 'expand_2L_xlarge', 'activation': 'elu', 'normalization': 'layer_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.30936329927469897, 'weight_decay': 3.3026959251812194e-06, 'lr': 1e-05, 'optimizer_type': 'adam', 'batch_size': 32, 'early_stopping_patience': 37, 'architecture': 'expand_2L_xlarge', 'activation': 'elu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Driving Force (all)      - RMSE: 1.8980, MAE: 0.5695
Driving Force (non-zero) - RMSE: 6.2783, MAE: 3.6732  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Driving Force (all)      - RMSE: 2.0341, MAE: 0.5026
Driving Force (non-zero) - RMSE: 6.2931, MAE: 3.0924  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Driving Force (all)      - RMSE: 1.2884, MAE: 0.4049
Driving Force (non-zero) - RMSE: 4.0380, MAE: 1.9237  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Driving Force (all)      - RMSE: 2.0859, MAE: 0.6430
Driving Force (non-zero) - RMSE: 6.3169, MAE: 3.3433  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794

[INFO 02-19 08:10:19] ax.service.ax_client: Completed trial 79 with data: {'avg_rmse_nonzero': (np.float32(5.2240067), np.float64(0.66999))}.
[INFO 02-19 08:10:19] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Driving Force (all)      - RMSE: 1.6672, MAE: 0.6066
Driving Force (non-zero) - RMSE: 3.1937, MAE: 2.3699  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 3.3062 (+/- 0.9857)
  Avg RMSE: 1.7947, MAE: 0.5453

Driving Force (non-zero only):
  Avg RMSE: 5.2240, MAE: 2.8805
Result: Non-zero RMSE = 5.2240
Checkpoint saved (80/100)

============================================================
Trial 81/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: 1
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-19 08:10:24] ax.service.ax_client: Generated new trial 80 with parameters {'dropout_rate': 0.093831, 'weight_decay': 3e-06, 'lr': 1e-05, 'optimizer_type': 'adam', 'batch_size': 32, 'early_stopping_patience': 33, 'architecture': 'single_1024', 'activation': 'gelu', 'normalization': 'layer_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.09383145349226238, 'weight_decay': 3.3455467062919873e-06, 'lr': 1e-05, 'optimizer_type': 'adam', 'batch_size': 32, 'early_stopping_patience': 33, 'architecture': 'single_1024', 'activation': 'gelu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Driving Force (all)      - RMSE: 1.9879, MAE: 0.7266
Driving Force (non-zero) - RMSE: 6.0736, MAE: 3.5961  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Driving Force (all)      - RMSE: 2.2068, MAE: 0.7135
Driving Force (non-zero) - RMSE: 6.3448, MAE: 3.3380  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Driving Force (all)      - RMSE: 1.6071, MAE: 0.6498
Driving Force (non-zero) - RMSE: 3.9773, MAE: 2.0512  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Driving Force (all)      - RMSE: 2.1795, MAE: 0.7786
Driving Force (non-zero) - RMSE: 6.6319, MAE: 3.6428  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794

[INFO 02-19 10:36:16] ax.service.ax_client: Completed trial 80 with data: {'avg_rmse_nonzero': (np.float32(5.2003765), np.float64(0.727073))}.
[INFO 02-19 10:36:17] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Driving Force (all)      - RMSE: 1.6609, MAE: 0.7924
Driving Force (non-zero) - RMSE: 2.9743, MAE: 2.2229  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 3.7827 (+/- 0.9628)
  Avg RMSE: 1.9285, MAE: 0.7322

Driving Force (non-zero only):
  Avg RMSE: 5.2004, MAE: 2.9702
Result: Non-zero RMSE = 5.2004
Checkpoint saved (81/100)

============================================================
Trial 82/100
============================================================

C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-19 10:36:22] ax.service.ax_client: Generated new trial 81 with parameters {'dropout_rate': 0.5, 'weight_decay': 0.01, 'lr': 0.01, 'optimizer_type': 'adam', 'batch_size': 32, 'early_stopping_patience': 12, 'architecture': 'constant_1024_3L', 'activation': 'leaky_relu', 'normalization': 'layer_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.5, 'weight_decay': 0.01, 'lr': 0.01, 'optimizer_type': 'adam', 'batch_size': 32, 'early_stopping_patience': 12, 'architecture': 'constant_1024_3L', 'activation': 'leaky_relu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 13
Driving Force (all)      - RMSE: 2.0245, MAE: 0.5306
Driving Force (non-zero) - RMSE: 6.8986, MAE: 4.2030  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 17
Driving Force (all)      - RMSE: 2.1811, MAE: 0.5184
Driving Force (non-zero) - RMSE: 6.7211, MAE: 3.2769  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 13
Driving Force (all)      - RMSE: 1.4192, MAE: 0.4198
Driving Force (non-zero) - RMSE: 4.3103, MAE: 2.1631  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 14
Driving Force (all)      - RMSE: 2.0561, MAE: 0.5620
Driving Force (non-zero) - RMSE: 6.5591, MAE: 3.3151  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 13
Driving Force (all)      - RMSE: 1.1492, MAE: 0.4423
Driving Force (non-zero) - RMSE: 3.0813, MAE: 2.2921  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 3.2836 (+/- 1.3559)
  Avg RMSE: 1.7660, MAE: 0.4946

Driving Force (non-zero only):
  Avg RMSE: 5.5141, MAE: 3.0500

[INFO 02-19 10:39:20] ax.service.ax_client: Completed trial 81 with data: {'avg_rmse_nonzero': (np.float32(5.5140734), np.float64(0.769204))}.
[INFO 02-19 10:39:20] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Result: Non-zero RMSE = 5.5141
Checkpoint saved (82/100)

============================================================
Trial 83/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: '0.24433701630332064'
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-19 10:39:25] ax.service.ax_client: Generated new trial 82 with parameters {'dropout_rate': 0.0, 'weight_decay': 2e-06, 'lr': 1e-05, 'optimizer_type': 'adam', 'batch_size': 256, 'early_stopping_patience': 48, 'architecture': 'expand_2L_medium', 'activation': 'gelu', 'normalization': 'layer_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.0, 'weight_decay': 2.1050765014293065e-06, 'lr': 1e-05, 'optimizer_type': 'adam', 'batch_size': 256, 'early_stopping_patience': 48, 'architecture': 'expand_2L_medium', 'activation': 'gelu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Driving Force (all)      - RMSE: 2.1135, MAE: 0.7990
Driving Force (non-zero) - RMSE: 6.3212, MAE: 3.7654  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Driving Force (all)      - RMSE: 2.2411, MAE: 0.7024
Driving Force (non-zero) - RMSE: 6.6240, MAE: 3.3849  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Driving Force (all)      - RMSE: 1.5352, MAE: 0.6270
Driving Force (non-zero) - RMSE: 4.2279, MAE: 2.2928  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 823
Driving Force (all)      - RMSE: 2.4046, MAE: 0.8870
Driving Force (non-zero) - RMSE: 6.3360, MAE: 3.6244  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794

[INFO 02-19 11:30:33] ax.service.ax_client: Completed trial 82 with data: {'avg_rmse_nonzero': (np.float32(5.2977877), np.float64(0.721174))}.
[INFO 02-19 11:30:33] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Driving Force (all)      - RMSE: 1.4973, MAE: 0.7277
Driving Force (non-zero) - RMSE: 2.9798, MAE: 2.2061  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 3.9741 (+/- 1.4302)
  Avg RMSE: 1.9583, MAE: 0.7486

Driving Force (non-zero only):
  Avg RMSE: 5.2978, MAE: 3.0547
Result: Non-zero RMSE = 5.2978
Checkpoint saved (83/100)

============================================================
Trial 84/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: '0.36035180673422856'
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-19 11:30:39] ax.service.ax_client: Generated new trial 83 with parameters {'dropout_rate': 0.071387, 'weight_decay': 0.01, 'lr': 0.000254, 'optimizer_type': 'adamw', 'batch_size': 128, 'early_stopping_patience': 24, 'architecture': 'constant_2048', 'activation': 'selu', 'normalization': 'layer_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.07138666303258871, 'weight_decay': 0.01, 'lr': 0.00025397864829586233, 'optimizer_type': 'adamw', 'batch_size': 128, 'early_stopping_patience': 24, 'architecture': 'constant_2048', 'activation': 'selu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 160
Driving Force (all)      - RMSE: 1.9577, MAE: 0.6737
Driving Force (non-zero) - RMSE: 6.2228, MAE: 3.6643  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 204
Driving Force (all)      - RMSE: 2.2216, MAE: 0.6774
Driving Force (non-zero) - RMSE: 6.3296, MAE: 3.2261  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 146
Driving Force (all)      - RMSE: 1.4988, MAE: 0.5702
Driving Force (non-zero) - RMSE: 4.2206, MAE: 2.1934  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 116
Driving Force (all)      - RMSE: 2.2464, MAE: 0.8697
Driving Force (non-zero) - RMSE: 6.1810, MAE: 3.4554  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 232
Driving Force (all)      - RMSE: 1.8695, MAE: 0.7641
Driving Force (non-zero) - RMSE: 3.3955, MAE: 2.4182  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 3.9111 (+/- 1.0285)
  Avg RMSE: 1.9588, MAE: 0.7110

Driving Force (non-zero only):
  Avg RMSE: 5.2699, MAE: 2.9915

[INFO 02-19 11:46:35] ax.service.ax_client: Completed trial 83 with data: {'avg_rmse_nonzero': (np.float32(5.2698874), np.float64(0.611377))}.
[INFO 02-19 11:46:35] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Result: Non-zero RMSE = 5.2699
Checkpoint saved (84/100)

============================================================
Trial 85/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: '0.3782347670579631'
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-19 11:46:40] ax.service.ax_client: Generated new trial 84 with parameters {'dropout_rate': 0.230774, 'weight_decay': 0.01, 'lr': 1.4e-05, 'optimizer_type': 'adam', 'batch_size': 32, 'early_stopping_patience': 50, 'architecture': 'expand_4L_large', 'activation': 'gelu', 'normalization': 'none'} using model BoTorch.

Parameters: {'dropout_rate': 0.23077419301426547, 'weight_decay': 0.01, 'lr': 1.3891186243207866e-05, 'optimizer_type': 'adam', 'batch_size': 32, 'early_stopping_patience': 50, 'architecture': 'expand_4L_large', 'activation': 'gelu', 'normalization': 'none'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 78
Driving Force (all)      - RMSE: 2.0336, MAE: 0.5537
Driving Force (non-zero) - RMSE: 6.9035, MAE: 4.2326  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 51
Driving Force (all)      - RMSE: 2.2061, MAE: 0.5129
Driving Force (non-zero) - RMSE: 7.0078, MAE: 3.4168  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 111
Driving Force (all)      - RMSE: 1.4392, MAE: 0.4422
Driving Force (non-zero) - RMSE: 4.4515, MAE: 2.2953  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 65
Driving Force (all)      - RMSE: 2.0452, MAE: 0.5414
Driving Force (non-zero) - RMSE: 6.6233, MAE: 3.3257  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 72

[INFO 02-19 12:12:37] ax.service.ax_client: Completed trial 84 with data: {'avg_rmse_nonzero': (np.float32(5.6137667), np.float64(0.786847))}.
[INFO 02-19 12:12:37] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Driving Force (all)      - RMSE: 1.1025, MAE: 0.4450
Driving Force (non-zero) - RMSE: 3.0828, MAE: 2.2932  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 3.2944 (+/- 1.3991)
  Avg RMSE: 1.7653, MAE: 0.4990

Driving Force (non-zero only):
  Avg RMSE: 5.6138, MAE: 3.1127
Result: Non-zero RMSE = 5.6138
Checkpoint saved (85/100)

============================================================
Trial 86/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: '0.627339458021443'
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-19 12:12:43] ax.service.ax_client: Generated new trial 85 with parameters {'dropout_rate': 0.0, 'weight_decay': 0.01, 'lr': 0.01, 'optimizer_type': 'adamw', 'batch_size': 256, 'early_stopping_patience': 38, 'architecture': 'constant_2048', 'activation': 'leaky_relu', 'normalization': 'none'} using model BoTorch.

Parameters: {'dropout_rate': 0.0, 'weight_decay': 0.01, 'lr': 0.01, 'optimizer_type': 'adamw', 'batch_size': 256, 'early_stopping_patience': 38, 'architecture': 'constant_2048', 'activation': 'leaky_relu', 'normalization': 'none'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 84
Driving Force (all)      - RMSE: 7.8736, MAE: 2.8297
Driving Force (non-zero) - RMSE: 13.9133, MAE: 8.1340  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 100
Driving Force (all)      - RMSE: 3.6062, MAE: 1.0856
Driving Force (non-zero) - RMSE: 7.4191, MAE: 3.8789  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 79
Driving Force (all)      - RMSE: 3.5651, MAE: 0.7977
Driving Force (non-zero) - RMSE: 7.7317, MAE: 2.6120  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 55
Driving Force (all)      - RMSE: 3.2097, MAE: 1.4192
Driving Force (non-zero) - RMSE: 7.2461, MAE: 4.4967  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794

[INFO 02-19 12:17:26] ax.service.ax_client: Completed trial 85 with data: {'avg_rmse_nonzero': (np.float32(7.985573), np.float64(1.660562))}.

Early stopping at epoch 68
Driving Force (all)      - RMSE: 1.9252, MAE: 0.7506
Driving Force (non-zero) - RMSE: 3.6176, MAE: 2.2844  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 20.3433 (+/- 21.0926)
  Avg RMSE: 4.0360, MAE: 1.3765

Driving Force (non-zero only):
  Avg RMSE: 7.9856, MAE: 4.2812
Result: Non-zero RMSE = 7.9856

[INFO 02-19 12:17:26] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Checkpoint saved (86/100)

============================================================
Trial 87/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: '0.003445106301654583'
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-19 12:17:31] ax.service.ax_client: Generated new trial 86 with parameters {'dropout_rate': 0.30926, 'weight_decay': 0.000476, 'lr': 0.0017, 'optimizer_type': 'adam', 'batch_size': 32, 'early_stopping_patience': 47, 'architecture': 'constant_512', 'activation': 'gelu', 'normalization': 'layer_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.3092602460772977, 'weight_decay': 0.00047612226253199776, 'lr': 0.001700049583492589, 'optimizer_type': 'adam', 'batch_size': 32, 'early_stopping_patience': 47, 'architecture': 'constant_512', 'activation': 'gelu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 113
Driving Force (all)      - RMSE: 1.9968, MAE: 0.5014
Driving Force (non-zero) - RMSE: 6.7790, MAE: 4.0844  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 231
Driving Force (all)      - RMSE: 2.0432, MAE: 0.4663
Driving Force (non-zero) - RMSE: 6.3391, MAE: 3.0973  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 147
Driving Force (all)      - RMSE: 1.3326, MAE: 0.4076
Driving Force (non-zero) - RMSE: 4.0806, MAE: 2.0012  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 137
Driving Force (all)      - RMSE: 2.1251, MAE: 0.7033
Driving Force (non-zero) - RMSE: 6.0494, MAE: 3.2772  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 120

[INFO 02-19 12:43:36] ax.service.ax_client: Completed trial 86 with data: {'avg_rmse_nonzero': (np.float32(5.213215), np.float64(0.756252))}.
[INFO 02-19 12:43:36] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Driving Force (all)      - RMSE: 0.9588, MAE: 0.3417
Driving Force (non-zero) - RMSE: 2.8180, MAE: 2.0605  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 3.0746 (+/- 1.4458)
  Avg RMSE: 1.6913, MAE: 0.4841

Driving Force (non-zero only):
  Avg RMSE: 5.2132, MAE: 2.9041
Result: Non-zero RMSE = 5.2132
Checkpoint saved (87/100)

============================================================
Trial 88/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: 0
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-19 12:43:41] ax.service.ax_client: Generated new trial 87 with parameters {'dropout_rate': 0.0, 'weight_decay': 0.01, 'lr': 1e-05, 'optimizer_type': 'adam', 'batch_size': 256, 'early_stopping_patience': 16, 'architecture': 'expand_3L_medium', 'activation': 'gelu', 'normalization': 'none'} using model BoTorch.

Parameters: {'dropout_rate': 0.0, 'weight_decay': 0.01, 'lr': 1e-05, 'optimizer_type': 'adam', 'batch_size': 256, 'early_stopping_patience': 16, 'architecture': 'expand_3L_medium', 'activation': 'gelu', 'normalization': 'none'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 20
Driving Force (all)      - RMSE: 2.0355, MAE: 0.5549
Driving Force (non-zero) - RMSE: 6.9194, MAE: 4.2494  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 22
Driving Force (all)      - RMSE: 2.2060, MAE: 0.5141
Driving Force (non-zero) - RMSE: 7.0068, MAE: 3.4161  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 20
Driving Force (all)      - RMSE: 1.4402, MAE: 0.4422
Driving Force (non-zero) - RMSE: 4.4534, MAE: 2.2948  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 20
Driving Force (all)      - RMSE: 2.0489, MAE: 0.5490
Driving Force (non-zero) - RMSE: 6.6121, MAE: 3.3183  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794

[INFO 02-19 12:45:01] ax.service.ax_client: Completed trial 87 with data: {'avg_rmse_nonzero': (np.float32(5.6149416), np.float64(0.787193))}.

Early stopping at epoch 20
Driving Force (all)      - RMSE: 1.1057, MAE: 0.4464
Driving Force (non-zero) - RMSE: 3.0829, MAE: 2.2943  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 3.3009 (+/- 1.3992)
  Avg RMSE: 1.7673, MAE: 0.5013

Driving Force (non-zero only):
  Avg RMSE: 5.6149, MAE: 3.1146

[INFO 02-19 12:45:01] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Result: Non-zero RMSE = 5.6149
Checkpoint saved (88/100)

============================================================
Trial 89/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: '0.044530823912379724'
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-19 12:45:06] ax.service.ax_client: Generated new trial 88 with parameters {'dropout_rate': 0.0, 'weight_decay': 5.6e-05, 'lr': 0.000898, 'optimizer_type': 'adam', 'batch_size': 32, 'early_stopping_patience': 35, 'architecture': 'expand_2L_xlarge', 'activation': 'elu', 'normalization': 'layer_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.0, 'weight_decay': 5.6052631576520627e-05, 'lr': 0.000898307722905329, 'optimizer_type': 'adam', 'batch_size': 32, 'early_stopping_patience': 35, 'architecture': 'expand_2L_xlarge', 'activation': 'elu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 141
Driving Force (all)      - RMSE: 2.1269, MAE: 0.7923
Driving Force (non-zero) - RMSE: 6.4182, MAE: 3.7198  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 168
Driving Force (all)      - RMSE: 2.2876, MAE: 0.7343
Driving Force (non-zero) - RMSE: 6.6076, MAE: 3.4709  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 164
Driving Force (all)      - RMSE: 1.6399, MAE: 0.6712
Driving Force (non-zero) - RMSE: 4.1225, MAE: 2.1648  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 247
Driving Force (all)      - RMSE: 2.2826, MAE: 0.8148
Driving Force (non-zero) - RMSE: 6.2052, MAE: 3.4439  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 228
Driving Force (all)      - RMSE: 1.8459, MAE: 0.7797
Driving Force (non-zero) - RMSE: 3.3129, MAE: 2.4714  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 4.2127 (+/- 1.0102)
  Avg RMSE: 2.0366, MAE: 0.7584

Driving Force (non-zero only):
  Avg RMSE: 5.3333, MAE: 3.0541

[INFO 02-19 13:18:15] ax.service.ax_client: Completed trial 88 with data: {'avg_rmse_nonzero': (np.float32(5.333283), np.float64(0.674868))}.
[INFO 02-19 13:18:15] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Result: Non-zero RMSE = 5.3333
Checkpoint saved (89/100)

============================================================
Trial 90/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: 0
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-19 13:18:20] ax.service.ax_client: Generated new trial 89 with parameters {'dropout_rate': 0.0, 'weight_decay': 0.01, 'lr': 0.000417, 'optimizer_type': 'adamw', 'batch_size': 256, 'early_stopping_patience': 37, 'architecture': 'expand_3L_medium', 'activation': 'gelu', 'normalization': 'layer_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.0, 'weight_decay': 0.01, 'lr': 0.00041671990231606477, 'optimizer_type': 'adamw', 'batch_size': 256, 'early_stopping_patience': 37, 'architecture': 'expand_3L_medium', 'activation': 'gelu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 232
Driving Force (all)      - RMSE: 2.0851, MAE: 0.5984
Driving Force (non-zero) - RMSE: 6.9255, MAE: 4.3016  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 221
Driving Force (all)      - RMSE: 2.1231, MAE: 0.5733
Driving Force (non-zero) - RMSE: 6.4319, MAE: 3.1847  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 158
Driving Force (all)      - RMSE: 1.4158, MAE: 0.4570
Driving Force (non-zero) - RMSE: 4.3214, MAE: 2.2448  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 160
Driving Force (all)      - RMSE: 2.2084, MAE: 0.7435
Driving Force (non-zero) - RMSE: 6.3236, MAE: 3.5462  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 187
Driving Force (all)      - RMSE: 1.6493, MAE: 0.6155
Driving Force (non-zero) - RMSE: 2.9796, MAE: 2.1873  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 3.6915 (+/- 1.1218)
  Avg RMSE: 1.8964, MAE: 0.5975

Driving Force (non-zero only):
  Avg RMSE: 5.3964, MAE: 3.0929

[INFO 02-19 13:29:39] ax.service.ax_client: Completed trial 89 with data: {'avg_rmse_nonzero': (np.float32(5.396406), np.float64(0.750558))}.
[INFO 02-19 13:29:39] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Result: Non-zero RMSE = 5.3964
Checkpoint saved (90/100)

============================================================
Trial 91/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: 0
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-19 13:29:44] ax.service.ax_client: Generated new trial 90 with parameters {'dropout_rate': 0.169266, 'weight_decay': 0.000214, 'lr': 0.009412, 'optimizer_type': 'adam', 'batch_size': 256, 'early_stopping_patience': 23, 'architecture': 'single_256', 'activation': 'leaky_relu', 'normalization': 'layer_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.16926590067443356, 'weight_decay': 0.00021382613591458815, 'lr': 0.009412095225598476, 'optimizer_type': 'adam', 'batch_size': 256, 'early_stopping_patience': 23, 'architecture': 'single_256', 'activation': 'leaky_relu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 75
Driving Force (all)      - RMSE: 2.0031, MAE: 0.6134
Driving Force (non-zero) - RMSE: 6.4970, MAE: 3.8491  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 72
Driving Force (all)      - RMSE: 2.1600, MAE: 0.6426
Driving Force (non-zero) - RMSE: 6.2805, MAE: 3.3084  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 78
Driving Force (all)      - RMSE: 1.5614, MAE: 0.5879
Driving Force (non-zero) - RMSE: 4.0958, MAE: 2.0773  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 61
Driving Force (all)      - RMSE: 2.4465, MAE: 0.7809
Driving Force (non-zero) - RMSE: 6.3939, MAE: 3.4525  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794

[INFO 02-19 13:33:49] ax.service.ax_client: Completed trial 90 with data: {'avg_rmse_nonzero': (np.float32(5.212438), np.float64(0.750902))}.

Early stopping at epoch 115
Driving Force (all)      - RMSE: 1.3049, MAE: 0.4932
Driving Force (non-zero) - RMSE: 2.7950, MAE: 2.0167  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 3.7609 (+/- 1.5374)
  Avg RMSE: 1.8952, MAE: 0.6236

Driving Force (non-zero only):
  Avg RMSE: 5.2124, MAE: 2.9408
Result: Non-zero RMSE = 5.2124

[INFO 02-19 13:33:49] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Checkpoint saved (91/100)

============================================================
Trial 92/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: '0.1379486077712157'
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-19 13:33:55] ax.service.ax_client: Generated new trial 91 with parameters {'dropout_rate': 0.288298, 'weight_decay': 0.000209, 'lr': 2.2e-05, 'optimizer_type': 'adamw', 'batch_size': 256, 'early_stopping_patience': 17, 'architecture': 'expand_2L_xlarge', 'activation': 'elu', 'normalization': 'layer_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.28829760787152126, 'weight_decay': 0.00020854875526886904, 'lr': 2.2130507210084083e-05, 'optimizer_type': 'adamw', 'batch_size': 256, 'early_stopping_patience': 17, 'architecture': 'expand_2L_xlarge', 'activation': 'elu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 927
Driving Force (all)      - RMSE: 1.9546, MAE: 0.5994
Driving Force (non-zero) - RMSE: 6.4242, MAE: 3.7993  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 853
Driving Force (all)      - RMSE: 2.0426, MAE: 0.5269
Driving Force (non-zero) - RMSE: 6.2370, MAE: 3.0461  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 620
Driving Force (all)      - RMSE: 1.3300, MAE: 0.4205
Driving Force (non-zero) - RMSE: 4.0146, MAE: 1.9318  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 751
Driving Force (all)      - RMSE: 2.0690, MAE: 0.6665
Driving Force (non-zero) - RMSE: 6.2957, MAE: 3.3660  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 778
Driving Force (all)      - RMSE: 1.5594, MAE: 0.6278
Driving Force (non-zero) - RMSE: 2.9625, MAE: 2.1509  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 3.2948 (+/- 1.0091)
  Avg RMSE: 1.7911, MAE: 0.5682

Driving Force (non-zero only):
  Avg RMSE: 5.1868, MAE: 2.8588

[INFO 02-19 14:16:37] ax.service.ax_client: Completed trial 91 with data: {'avg_rmse_nonzero': (np.float32(5.1868176), np.float64(0.713626))}.
[INFO 02-19 14:16:37] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Result: Non-zero RMSE = 5.1868
Checkpoint saved (92/100)

============================================================
Trial 93/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: '0.7516179053845112'
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-19 14:16:43] ax.service.ax_client: Generated new trial 92 with parameters {'dropout_rate': 0.0, 'weight_decay': 0.01, 'lr': 0.004613, 'optimizer_type': 'adam', 'batch_size': 256, 'early_stopping_patience': 18, 'architecture': 'constant_2048', 'activation': 'elu', 'normalization': 'layer_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.0, 'weight_decay': 0.01, 'lr': 0.004612804730864017, 'optimizer_type': 'adam', 'batch_size': 256, 'early_stopping_patience': 18, 'architecture': 'constant_2048', 'activation': 'elu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 49
Driving Force (all)      - RMSE: 2.1595, MAE: 0.5643
Driving Force (non-zero) - RMSE: 7.3093, MAE: 4.5953  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 55
Driving Force (all)      - RMSE: 2.0986, MAE: 0.4827
Driving Force (non-zero) - RMSE: 6.6714, MAE: 3.3595  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 63
Driving Force (all)      - RMSE: 1.4440, MAE: 0.4549
Driving Force (non-zero) - RMSE: 4.1228, MAE: 2.0983  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 45
Driving Force (all)      - RMSE: 2.4073, MAE: 0.7604
Driving Force (non-zero) - RMSE: 6.3414, MAE: 3.5834  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 59
Driving Force (all)      - RMSE: 0.9673, MAE: 0.3737
Driving Force (non-zero) - RMSE: 2.4698, MAE: 1.6192  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 3.5768 (+/- 1.7882)
  Avg RMSE: 1.8154, MAE: 0.5272

Driving Force (non-zero only):
  Avg RMSE: 5.3829, MAE: 3.0511

[INFO 02-19 14:21:01] ax.service.ax_client: Completed trial 92 with data: {'avg_rmse_nonzero': (np.float32(5.3829403), np.float64(0.904547))}.
[INFO 02-19 14:21:01] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Result: Non-zero RMSE = 5.3829
Checkpoint saved (93/100)

============================================================
Trial 94/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: 0
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-19 14:21:09] ax.service.ax_client: Generated new trial 93 with parameters {'dropout_rate': 0.0, 'weight_decay': 3.8e-05, 'lr': 0.000979, 'optimizer_type': 'adam', 'batch_size': 256, 'early_stopping_patience': 34, 'architecture': 'expand_2L_large', 'activation': 'elu', 'normalization': 'layer_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.0, 'weight_decay': 3.830511789493214e-05, 'lr': 0.0009789189112188307, 'optimizer_type': 'adam', 'batch_size': 256, 'early_stopping_patience': 34, 'architecture': 'expand_2L_large', 'activation': 'elu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 165
Driving Force (all)      - RMSE: 2.3122, MAE: 0.7962
Driving Force (non-zero) - RMSE: 7.5191, MAE: 4.7419  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 234
Driving Force (all)      - RMSE: 2.3380, MAE: 0.7384
Driving Force (non-zero) - RMSE: 6.7003, MAE: 3.5704  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 210
Driving Force (all)      - RMSE: 1.5904, MAE: 0.6502
Driving Force (non-zero) - RMSE: 4.2703, MAE: 2.2305  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 219
Driving Force (all)      - RMSE: 2.4126, MAE: 0.8690
Driving Force (non-zero) - RMSE: 6.8968, MAE: 3.9048  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 210
Driving Force (all)      - RMSE: 2.0649, MAE: 0.8659
Driving Force (non-zero) - RMSE: 3.3393, MAE: 2.3098  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 4.6853 (+/- 1.1968)
  Avg RMSE: 2.1436, MAE: 0.7840

Driving Force (non-zero only):
  Avg RMSE: 5.7452, MAE: 3.3515

[INFO 02-19 14:36:41] ax.service.ax_client: Completed trial 93 with data: {'avg_rmse_nonzero': (np.float32(5.745183), np.float64(0.816967))}.
[INFO 02-19 14:36:41] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Result: Non-zero RMSE = 5.7452
Checkpoint saved (94/100)

============================================================
Trial 95/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: 0
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-19 14:36:48] ax.service.ax_client: Generated new trial 94 with parameters {'dropout_rate': 0.5, 'weight_decay': 4e-06, 'lr': 0.01, 'optimizer_type': 'adamw', 'batch_size': 32, 'early_stopping_patience': 16, 'architecture': 'expand_4L_medium', 'activation': 'elu', 'normalization': 'layer_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.5, 'weight_decay': 4.0393427334992195e-06, 'lr': 0.01, 'optimizer_type': 'adamw', 'batch_size': 32, 'early_stopping_patience': 16, 'architecture': 'expand_4L_medium', 'activation': 'elu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 209
Driving Force (all)      - RMSE: 2.0990, MAE: 0.5984
Driving Force (non-zero) - RMSE: 6.7288, MAE: 4.1255  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 141
Driving Force (all)      - RMSE: 2.7097, MAE: 0.7391
Driving Force (non-zero) - RMSE: 7.8678, MAE: 4.3973  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 96
Driving Force (all)      - RMSE: 1.4702, MAE: 0.4317
Driving Force (non-zero) - RMSE: 4.0013, MAE: 1.9948  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 191
Driving Force (all)      - RMSE: 3.0997, MAE: 0.8795
Driving Force (non-zero) - RMSE: 7.3043, MAE: 4.1274  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 117

[INFO 02-19 15:22:56] ax.service.ax_client: Completed trial 94 with data: {'avg_rmse_nonzero': (np.float32(5.7216444), np.float64(1.004447))}.
[INFO 02-19 15:22:56] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Driving Force (all)      - RMSE: 0.9166, MAE: 0.3799
Driving Force (non-zero) - RMSE: 2.7061, MAE: 1.9049  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 4.8715 (+/- 3.2358)
  Avg RMSE: 2.0590, MAE: 0.6057

Driving Force (non-zero only):
  Avg RMSE: 5.7216, MAE: 3.3100
Result: Non-zero RMSE = 5.7216
Checkpoint saved (95/100)

============================================================
Trial 96/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: 2
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-19 15:23:05] ax.service.ax_client: Generated new trial 95 with parameters {'dropout_rate': 0.0, 'weight_decay': 0.003315, 'lr': 0.002475, 'optimizer_type': 'adam', 'batch_size': 256, 'early_stopping_patience': 16, 'architecture': 'expand_3L_gradual', 'activation': 'leaky_relu', 'normalization': 'layer_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.0, 'weight_decay': 0.0033154458238090646, 'lr': 0.002474543691824403, 'optimizer_type': 'adam', 'batch_size': 256, 'early_stopping_patience': 16, 'architecture': 'expand_3L_gradual', 'activation': 'leaky_relu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 71
Driving Force (all)      - RMSE: 2.1056, MAE: 0.5394
Driving Force (non-zero) - RMSE: 7.1165, MAE: 4.4572  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 54
Driving Force (all)      - RMSE: 2.0580, MAE: 0.4923
Driving Force (non-zero) - RMSE: 6.3486, MAE: 3.3068  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 121
Driving Force (all)      - RMSE: 1.4371, MAE: 0.4624
Driving Force (non-zero) - RMSE: 3.9240, MAE: 2.0423  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 81
Driving Force (all)      - RMSE: 2.1917, MAE: 0.6590
Driving Force (non-zero) - RMSE: 6.3459, MAE: 3.4788  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794

[INFO 02-19 15:28:38] ax.service.ax_client: Completed trial 95 with data: {'avg_rmse_nonzero': (np.float32(5.341705), np.float64(0.799684))}.

Early stopping at epoch 65
Driving Force (all)      - RMSE: 1.3483, MAE: 0.5103
Driving Force (non-zero) - RMSE: 2.9736, MAE: 2.2155  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 3.4711 (+/- 1.2646)
  Avg RMSE: 1.8281, MAE: 0.5327

Driving Force (non-zero only):
  Avg RMSE: 5.3417, MAE: 3.1001

[INFO 02-19 15:28:38] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Result: Non-zero RMSE = 5.3417
Checkpoint saved (96/100)

============================================================
Trial 97/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: '0.7441467465800992'
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-19 15:28:44] ax.service.ax_client: Generated new trial 96 with parameters {'dropout_rate': 0.178598, 'weight_decay': 0.01, 'lr': 0.01, 'optimizer_type': 'adamw', 'batch_size': 32, 'early_stopping_patience': 11, 'architecture': 'expand_2L_medium', 'activation': 'leaky_relu', 'normalization': 'layer_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.17859807145248452, 'weight_decay': 0.01, 'lr': 0.01, 'optimizer_type': 'adamw', 'batch_size': 32, 'early_stopping_patience': 11, 'architecture': 'expand_2L_medium', 'activation': 'leaky_relu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 50
Driving Force (all)      - RMSE: 1.8873, MAE: 0.4977
Driving Force (non-zero) - RMSE: 6.3607, MAE: 3.7205  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 63
Driving Force (all)      - RMSE: 2.1012, MAE: 0.5166
Driving Force (non-zero) - RMSE: 6.5205, MAE: 3.2547  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 33
Driving Force (all)      - RMSE: 1.3040, MAE: 0.4232
Driving Force (non-zero) - RMSE: 3.8645, MAE: 1.9101  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 55
Driving Force (all)      - RMSE: 2.2075, MAE: 0.6396
Driving Force (non-zero) - RMSE: 6.2596, MAE: 3.4241  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 44

[INFO 02-19 15:37:38] ax.service.ax_client: Completed trial 96 with data: {'avg_rmse_nonzero': (np.float32(5.1666546), np.float64(0.762173))}.
[INFO 02-19 15:37:38] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Driving Force (all)      - RMSE: 1.2983, MAE: 0.4702
Driving Force (non-zero) - RMSE: 2.8280, MAE: 2.0157  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 3.2471 (+/- 1.3370)
  Avg RMSE: 1.7596, MAE: 0.5094

Driving Force (non-zero only):
  Avg RMSE: 5.1667, MAE: 2.8650
Result: Non-zero RMSE = 5.1667
Checkpoint saved (97/100)

============================================================
Trial 98/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: 2
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-19 15:37:46] ax.service.ax_client: Generated new trial 97 with parameters {'dropout_rate': 0.0, 'weight_decay': 0.01, 'lr': 0.000474, 'optimizer_type': 'adam', 'batch_size': 256, 'early_stopping_patience': 42, 'architecture': 'expand_2L_large', 'activation': 'gelu', 'normalization': 'layer_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.0, 'weight_decay': 0.01, 'lr': 0.00047442107721174117, 'optimizer_type': 'adam', 'batch_size': 256, 'early_stopping_patience': 42, 'architecture': 'expand_2L_large', 'activation': 'gelu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 45
Driving Force (all)      - RMSE: 1.9526, MAE: 0.5384
Driving Force (non-zero) - RMSE: 6.5964, MAE: 3.9270  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 48
Driving Force (all)      - RMSE: 2.0183, MAE: 0.4890
Driving Force (non-zero) - RMSE: 6.2287, MAE: 3.0777  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 45
Driving Force (all)      - RMSE: 1.3351, MAE: 0.3955
Driving Force (non-zero) - RMSE: 4.0470, MAE: 1.9753  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 46
Driving Force (all)      - RMSE: 2.0845, MAE: 0.6445
Driving Force (non-zero) - RMSE: 6.0783, MAE: 3.1686  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 47
Driving Force (all)      - RMSE: 1.0432, MAE: 0.3840
Driving Force (non-zero) - RMSE: 2.7399, MAE: 1.9871  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 3.0204 (+/- 1.3234)
  Avg RMSE: 1.6867, MAE: 0.4902

Driving Force (non-zero only):
  Avg RMSE: 5.1381, MAE: 2.8272

[INFO 02-19 15:41:36] ax.service.ax_client: Completed trial 97 with data: {'avg_rmse_nonzero': (np.float32(5.1380873), np.float64(0.746392))}.
[INFO 02-19 15:41:36] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Result: Non-zero RMSE = 5.1381
Checkpoint saved (98/100)

============================================================
Trial 99/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize_mixed.py:702: OptimizationWarning: Failed to initialize using continuous relaxation. Using `sample_feasible_points` for initialization. Original error message: '0.052353050421669683'
  best_X, best_acq_val = generate_starting_points(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-19 15:41:44] ax.service.ax_client: Generated new trial 98 with parameters {'dropout_rate': 0.133879, 'weight_decay': 5.9e-05, 'lr': 0.009934, 'optimizer_type': 'adam', 'batch_size': 256, 'early_stopping_patience': 11, 'architecture': 'constant_2048', 'activation': 'gelu', 'normalization': 'layer_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.13387919251715263, 'weight_decay': 5.886856673080748e-05, 'lr': 0.009934133893399456, 'optimizer_type': 'adam', 'batch_size': 256, 'early_stopping_patience': 11, 'architecture': 'constant_2048', 'activation': 'gelu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 36
Driving Force (all)      - RMSE: 1.9010, MAE: 0.4948
Driving Force (non-zero) - RMSE: 6.3127, MAE: 3.7751  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 57
Driving Force (all)      - RMSE: 2.1091, MAE: 0.4751
Driving Force (non-zero) - RMSE: 6.6146, MAE: 3.4322  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 53
Driving Force (all)      - RMSE: 1.4037, MAE: 0.4085
Driving Force (non-zero) - RMSE: 3.9704, MAE: 2.0672  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 48
Driving Force (all)      - RMSE: 2.2567, MAE: 0.5942
Driving Force (non-zero) - RMSE: 6.2676, MAE: 3.4173  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 52
Driving Force (all)      - RMSE: 0.9992, MAE: 0.3604
Driving Force (non-zero) - RMSE: 2.5616, MAE: 1.8394  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 3.2247 (+/- 1.5276)
  Avg RMSE: 1.7339, MAE: 0.4666

Driving Force (non-zero only):
  Avg RMSE: 5.1454, MAE: 2.9062

[INFO 02-19 15:45:09] ax.service.ax_client: Completed trial 98 with data: {'avg_rmse_nonzero': (np.float32(5.145384), np.float64(0.801161))}.
[INFO 02-19 15:45:09] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Result: Non-zero RMSE = 5.1454
Checkpoint saved (99/100)

============================================================
Trial 100/100
============================================================

C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-19 15:45:16] ax.service.ax_client: Generated new trial 99 with parameters {'dropout_rate': 0.0, 'weight_decay': 0.01, 'lr': 1e-05, 'optimizer_type': 'adamw', 'batch_size': 32, 'early_stopping_patience': 50, 'architecture': 'expand_2L_large', 'activation': 'leaky_relu', 'normalization': 'layer_norm'} using model BoTorch.

Parameters: {'dropout_rate': 0.0, 'weight_decay': 0.01, 'lr': 1e-05, 'optimizer_type': 'adamw', 'batch_size': 32, 'early_stopping_patience': 50, 'architecture': 'expand_2L_large', 'activation': 'leaky_relu', 'normalization': 'layer_norm'}
Using device: cuda
Input dim: 144, Output dim: 804

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Early stopping at epoch 571
Driving Force (all)      - RMSE: 2.1094, MAE: 0.7915
Driving Force (non-zero) - RMSE: 6.3030, MAE: 3.7994  [498,341 values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Early stopping at epoch 380
Driving Force (all)      - RMSE: 2.1825, MAE: 0.6776
Driving Force (non-zero) - RMSE: 6.5044, MAE: 3.2890  [1,207,679 values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Early stopping at epoch 560
Driving Force (all)      - RMSE: 1.6864, MAE: 0.6709
Driving Force (non-zero) - RMSE: 4.5672, MAE: 2.4543  [399,249 values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Early stopping at epoch 296
Driving Force (all)      - RMSE: 2.3357, MAE: 0.8158
Driving Force (non-zero) - RMSE: 6.3393, MAE: 3.4630  [673,018 values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Early stopping at epoch 577
Driving Force (all)      - RMSE: 2.0186, MAE: 0.8746
Driving Force (non-zero) - RMSE: 3.1211, MAE: 2.2281  [233,863 values]

==================================================
Cross-Validation Summary — Driving Forces
==================================================
Driving Force (all values):
  Avg Test MSE: 4.3174 (+/- 0.8650)
  Avg RMSE: 2.0665, MAE: 0.7661

Driving Force (non-zero only):
  Avg RMSE: 5.3670, MAE: 3.0467

[INFO 02-19 17:24:23] ax.service.ax_client: Completed trial 99 with data: {'avg_rmse_nonzero': (np.float32(5.3670096), np.float64(0.663292))}.
[INFO 02-19 17:24:23] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_DrivingForce(T)_checkpoint.json`.

Result: Non-zero RMSE = 5.3670
Checkpoint saved (100/100)

============================================================
OPTIMIZATION COMPLETE — Driving Force NN (100 trials)
============================================================
Best parameters: {'dropout_rate': 0.0, 'weight_decay': 0.01, 'lr': 1e-05, 'optimizer_type': 'adam', 'batch_size': 32, 'early_stopping_patience': 29, 'architecture': 'constant_2048', 'activation': 'leaky_relu', 'normalization': 'layer_norm'}
Best Non-zero RMSE: 5.2925

In [ ]:
ax_client_df = AxClient.load_from_json_file(r"Ax_checkpoints/ax_client_NN_DF(T)_checkpoint.json")
best_parameters_df, values_df = ax_client_df.get_best_parameters()
print(f"\n{'='*60}")
print("OPTIMIZATION COMPLETE — Driving Force NN (100 trials)")
print('='*60)
print(f"Best parameters: {best_parameters_df}")
print(f"Best Non-zero RMSE: {values_df[0]['avg_rmse_nonzero']:.4f}")

c:\Users\Chris\python\Lib\site-packages\ax\storage\json_store\decoder.py:288: AxParameterWarning: `sort_values` is not specified for `ChoiceParameter` "architecture". Defaulting to `False` for parameters of `ParameterType` STRING. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  return _class(
c:\Users\Chris\python\Lib\site-packages\ax\storage\json_store\decoder.py:288: AxParameterWarning: `sort_values` is not specified for `ChoiceParameter` "activation". Defaulting to `False` for parameters of `ParameterType` STRING. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  return _class(
c:\Users\Chris\python\Lib\site-packages\ax\storage\json_store\decoder.py:288: AxParameterWarning: `sort_values` is not specified for `ChoiceParameter` "normalization". Defaulting to `False` for parameters of `ParameterType` STRING. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  return _class(
c:\Users\Chris\python\Lib\site-packages\ax\storage\json_store\decoder.py:288: AxParameterWarning: `sort_values` is not specified for `ChoiceParameter` "optimizer_type". Defaulting to `False` for parameters of `ParameterType` STRING. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  return _class(
c:\Users\Chris\python\Lib\site-packages\ax\storage\json_store\decoder.py:288: AxParameterWarning: `sort_values` is not specified for `ChoiceParameter` "batch_size". Defaulting to `True` for parameters of `ParameterType` INT. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  return _class(
[INFO 03-06 11:28:37] ax.service.ax_client: Starting optimization with verbose logging. To disable logging, set the `verbose_logging` argument to `False`. Note that float values in the logs are rounded to 6 decimal points.

============================================================
OPTIMIZATION COMPLETE — Driving Force NN (100 trials)
============================================================
Best parameters: {'dropout_rate': 0.0, 'weight_decay': 0.01, 'lr': 1e-05, 'optimizer_type': 'adam', 'batch_size': 32, 'early_stopping_patience': 29, 'architecture': 'constant_2048', 'activation': 'leaky_relu', 'normalization': 'layer_norm'}
Best Non-zero RMSE: 5.2925

In [ ]:
# =====================================================================
# XGBoost Evaluation & Bayesian Optimization for Phase Fractions (NF)
# =====================================================================

def evaluate_parameters_XGB_NF_FT(parameters, verbose=True):
    """
    Evaluate XGBoost hyperparameters for predicting phase fractions (NF)
    using 5-fold KMeans-based cross-validation (same splits as NN evaluation).

    Parameters:
    -----------
    parameters : dict
        XGBoost hyperparameters including:
        - n_estimators, max_depth, learning_rate, subsample,
          colsample_bytree, min_child_weight, gamma,
          reg_alpha, reg_lambda, early_stopping_rounds
    verbose : bool
        Whether to print progress

    Returns:
    --------
    dict : Results including fold-level and average metrics
    """
    # Extract hyperparameters with defaults
    n_estimators = parameters.get('n_estimators', 500)
    max_depth = parameters.get('max_depth', 6)
    learning_rate = parameters.get('learning_rate', 0.1)
    subsample = parameters.get('subsample', 0.8)
    colsample_bytree = parameters.get('colsample_bytree', 0.8)
    min_child_weight = parameters.get('min_child_weight', 1)
    gamma = parameters.get('gamma', 0.0)
    reg_alpha = parameters.get('reg_alpha', 0.0)
    reg_lambda = parameters.get('reg_lambda', 1.0)
    early_stopping_rounds = parameters.get('early_stopping_rounds', 20)


    # Copy the x and y data — use phase fraction targets
    y_data = y_nf.copy()
    x_data = X_combined.copy()

    # Get dimensions
    input_dim = x_data.shape[1]
    output_dim = y_data.shape[1]
    if verbose:
        print(f"Input dim: {input_dim}, Output dim: {output_dim}")

    # Store results for each fold
    fold_results = []
    all_test_predictions = []
    all_test_targets = []

    for test_group in range(5):
        if verbose:
            print(f"\n{'='*50}")
            print(f"Fold {test_group}")
            print('='*50)

        # Get the split indexes for training and testing
        train_idx = cv_group_df['cv_group'] != test_group
        test_idx = cv_group_df['cv_group'] == test_group

        # Split the x and y data into train and test
        x_train = x_data.loc[train_idx]
        x_test = x_data.loc[test_idx]
        y_train = y_data.loc[train_idx]
        y_test = y_data.loc[test_idx]

        # Create train and validation split
        X_train, X_val, y_train_split, y_val = train_test_split(
            x_train, y_train, test_size=0.2, random_state=42
        )

        if verbose:
            print(f"Train: {len(X_train)}, Val: {len(X_val)}, Test: {len(x_test)}")

        # Train one XGBRegressor per output column (manual multi-output)
        # This ensures proper GPU usage — native multi-output doesn't fully support GPU
        estimators = []
        best_iters = []
        output_cols = y_train_split.columns.tolist()

        for col_idx, col_name in enumerate(output_cols):
            xgb_model = XGBRegressor(
                n_estimators=n_estimators,
                max_depth=max_depth,
                learning_rate=learning_rate,
                subsample=subsample,
                colsample_bytree=colsample_bytree,
                min_child_weight=min_child_weight,
                gamma=gamma,
                reg_alpha=reg_alpha,
                reg_lambda=reg_lambda,
                tree_method='hist',
                device='cuda',
                random_state=42,
                n_jobs=-1,
                verbosity=0,
                early_stopping_rounds=early_stopping_rounds,
                eval_metric='rmse',
            )

            xgb_model.fit(
                X_train, y_train_split[col_name],
                eval_set=[(X_val, y_val[col_name])],
                verbose=False,
            )

            estimators.append(xgb_model)
            best_iters.append(xgb_model.best_iteration)

        if verbose:
            print(f"Best iterations (min/mean/max): {min(best_iters)}/{np.mean(best_iters):.0f}/{max(best_iters)}")

        # Predict on test set (stack individual predictions)
        test_preds = np.column_stack([
            est.predict(x_test) for est in estimators
        ])
        test_targets = y_test.values

        # Get column names for NF columns
        col_names = y_data.columns.tolist()
        nf_col_idxs = [i for i, col in enumerate(col_names) if col.startswith('NF_')]

        # Calculate overall RMSE and MAE (all values)
        mse_original = np.mean((test_preds - test_targets) ** 2)
        rmse = np.sqrt(mse_original)
        mae = np.mean(np.abs(test_preds - test_targets))

        # Calculate metrics for non-zero targets only
        nonzero_threshold = 1e-6

        nonzero_mask = np.abs(test_targets) > nonzero_threshold
        if np.any(nonzero_mask):
            nonzero_errors = test_preds[nonzero_mask] - test_targets[nonzero_mask]
            rmse_nonzero = np.sqrt(np.mean(nonzero_errors ** 2))
            mae_nonzero = np.mean(np.abs(nonzero_errors))
            n_nonzero = np.sum(nonzero_mask)
        else:
            rmse_nonzero, mae_nonzero, n_nonzero = 0.0, 0.0, 0

        # Phase Fraction (NF) specific metrics — non-zero only
        if nf_col_idxs:
            nf_preds = test_preds[:, nf_col_idxs]
            nf_targets = test_targets[:, nf_col_idxs]
            nf_nonzero_mask = np.abs(nf_targets) > nonzero_threshold
            if np.any(nf_nonzero_mask):
                nf_errors = nf_preds[nf_nonzero_mask] - nf_targets[nf_nonzero_mask]
                nf_rmse = np.sqrt(np.mean(nf_errors ** 2))
                nf_mae = np.mean(np.abs(nf_errors))
                n_nf_nonzero = np.sum(nf_nonzero_mask)
            else:
                nf_rmse, nf_mae, n_nf_nonzero = 0.0, 0.0, 0
        else:
            nf_rmse, nf_mae, n_nf_nonzero = 0.0, 0.0, 0

        if verbose:
            print(f"Overall (all)      - RMSE: {rmse:.4f}, MAE: {mae:.4f}")
            print(f"Overall (non-zero) - RMSE: {rmse_nonzero:.4f}, MAE: {mae_nonzero:.4f}  [{n_nonzero:,} values]")
            print(f"Phase Fraction (NF) - RMSE: {nf_rmse:.4f}, MAE: {nf_mae:.4f}  [{n_nf_nonzero:,} non-zero values]")

        # Store fold results
        fold_results.append({
            'fold': test_group,
            'test_loss': mse_original,
            'test_rmse': rmse,
            'test_mae': mae,
            'rmse_nonzero': rmse_nonzero,
            'mae_nonzero': mae_nonzero,
            'nf_rmse': nf_rmse,
            'nf_mae': nf_mae,
        })

        all_test_predictions.append(test_preds)
        all_test_targets.append(test_targets)

    # Summary across all folds
    if verbose:
        print(f"\n{'='*50}")
        print("Cross-Validation Summary — XGBoost Phase Fractions (NF)")
        print('='*50)

    avg_test_loss = np.mean([r['test_loss'] for r in fold_results])
    avg_test_rmse = np.mean([r['test_rmse'] for r in fold_results])
    avg_test_mae = np.mean([r['test_mae'] for r in fold_results])
    avg_rmse_nonzero = np.mean([r['rmse_nonzero'] for r in fold_results])
    avg_mae_nonzero = np.mean([r['mae_nonzero'] for r in fold_results])
    avg_nf_rmse = np.mean([r['nf_rmse'] for r in fold_results])
    avg_nf_mae = np.mean([r['nf_mae'] for r in fold_results])
    std_test_loss = np.std([r['test_loss'] for r in fold_results])

    if verbose:
        print(f"Overall (all values):")
        print(f"  Avg Test MSE: {avg_test_loss:.4f} (+/- {std_test_loss:.4f})")
        print(f"  Avg RMSE: {avg_test_rmse:.4f}, MAE: {avg_test_mae:.4f}")
        print(f"\nOverall (non-zero only):")
        print(f"  Avg RMSE: {avg_rmse_nonzero:.4f}, MAE: {avg_mae_nonzero:.4f}")
        print(f"\nPhase Fraction (NF, non-zero only):")
        print(f"  Avg RMSE: {avg_nf_rmse:.4f}, MAE: {avg_nf_mae:.4f}")

    return {
        'fold_results': fold_results,
        'avg_test_loss': avg_test_loss,
        'avg_test_rmse': avg_test_rmse,
        'avg_test_mae': avg_test_mae,
        'avg_rmse_nonzero': avg_rmse_nonzero,
        'avg_mae_nonzero': avg_mae_nonzero,
        'avg_nf_rmse': avg_nf_rmse,
        'avg_nf_mae': avg_nf_mae,
        'all_predictions': all_test_predictions,
        'all_targets': all_test_targets,
    }


# =====================================================================
# Ax Bayesian Optimization for XGBoost NF f(T)
# =====================================================================

ax_client_xgb_nf = AxClient()
ax_client_xgb_nf.create_experiment(
    name="XGB opt NF f(T) Calphed",
    parameters=[
        {
            "name": "n_estimators",
            "type": "range",
            "bounds": [100, 5000],
            "value_type": "int",
        },
        {
            "name": "max_depth",
            "type": "range",
            "bounds": [3, 100],
            "value_type": "int",
        },
        {
            "name": "learning_rate",
            "type": "range",
            "bounds": [0.005, 0.3],
            "log_scale": True,
        },
        {
            "name": "subsample",
            "type": "range",
            "bounds": [0.5, 1.0],
        },
        {
            "name": "colsample_bytree",
            "type": "range",
            "bounds": [0.3, 1.0],
        },
        {
            "name": "min_child_weight",
            "type": "range",
            "bounds": [1, 20],
            "value_type": "int",
        },
        {
            "name": "gamma",
            "type": "range",
            "bounds": [0.0, 5.0],
        },
        {
            "name": "reg_alpha",
            "type": "range",
            "bounds": [1e-6, 10.0],
            "log_scale": True,
        },
        {
            "name": "reg_lambda",
            "type": "range",
            "bounds": [1e-6, 10.0],
            "log_scale": True,
        },
        {
            "name": "early_stopping_rounds",
            "type": "range",
            "bounds": [10, 50],
            "value_type": "int",
        },
    ],
    objectives={"avg_rmse_nonzero": ObjectiveProperties(minimize=True)},
)


def evaluate_for_ax_xgb_nf(parameterization):
    """Wrapper to convert Ax parameters to evaluate_parameters_XGB_NF_FT format."""
    parameters = {
        "n_estimators": parameterization["n_estimators"],
        "max_depth": parameterization["max_depth"],
        "learning_rate": parameterization["learning_rate"],
        "subsample": parameterization["subsample"],
        "colsample_bytree": parameterization["colsample_bytree"],
        "min_child_weight": parameterization["min_child_weight"],
        "gamma": parameterization["gamma"],
        "reg_alpha": parameterization["reg_alpha"],
        "reg_lambda": parameterization["reg_lambda"],
        "early_stopping_rounds": parameterization["early_stopping_rounds"],
    }

    results = evaluate_parameters_XGB_NF_FT(parameters, verbose=False)

    # Calculate SEM from fold results
    rmse_nonzero_values = [r["rmse_nonzero"] for r in results["fold_results"]]
    mean_rmse_nonzero = np.mean(rmse_nonzero_values)
    std_rmse_nonzero = np.std(rmse_nonzero_values, ddof=1)
    sem_rmse_nonzero = std_rmse_nonzero / np.sqrt(len(rmse_nonzero_values))

    return {"avg_rmse_nonzero": (mean_rmse_nonzero, sem_rmse_nonzero)}


# =====================================================================
# Run the Bayesian Optimization Loop — XGBoost NF f(T)
# =====================================================================
n_trials_xgb_nf = 100
SAVE_PATH_XGB_NF = r"Ax_checkpoints/ax_client_XGB_NF(T)_checkpoint.json"

for i in range(n_trials_xgb_nf):
    print(f"\n{'='*60}")
    print(f"Trial {i+1}/{n_trials_xgb_nf}")
    print('='*60)

    parameters, trial_index = ax_client_xgb_nf.get_next_trial()
    print(f"Parameters: {parameters}")

    try:
        result = evaluate_for_ax_xgb_nf(parameters)
        ax_client_xgb_nf.complete_trial(trial_index=trial_index, raw_data=result)
        print(f"Result: Non-zero RMSE = {result['avg_rmse_nonzero'][0]:.4f}")
    except Exception as e:
        print(f"Trial failed: {e}")
        ax_client_xgb_nf.log_trial_failure(trial_index=trial_index)

    # Save checkpoint after each trial
    ax_client_xgb_nf.save_to_json_file(SAVE_PATH_XGB_NF)
    print(f"Checkpoint saved to {SAVE_PATH_XGB_NF}")

# Get best parameters
best_parameters_xgb_nf, values_xgb_nf = ax_client_xgb_nf.get_best_parameters()
print(f"\n{'='*60}")
print("OPTIMIZATION COMPLETE — XGBoost Phase Fractions NF f(T)")
print('='*60)
print(f"Best parameters: {best_parameters_xgb_nf}")
print(f"Best Non-zero RMSE: {values_xgb_nf[0]['avg_rmse_nonzero']:.4f}")

[INFO 02-25 17:35:16] ax.service.ax_client: Starting optimization with verbose logging. To disable logging, set the `verbose_logging` argument to `False`. Note that float values in the logs are rounded to 6 decimal points.
[INFO 02-25 17:35:16] ax.service.utils.instantiation: Inferred value type of ParameterType.FLOAT for parameter learning_rate. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
[INFO 02-25 17:35:16] ax.service.utils.instantiation: Inferred value type of ParameterType.FLOAT for parameter subsample. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
[INFO 02-25 17:35:16] ax.service.utils.instantiation: Inferred value type of ParameterType.FLOAT for parameter colsample_bytree. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.

[INFO 02-25 17:35:16] ax.service.utils.instantiation: Inferred value type of ParameterType.FLOAT for parameter gamma. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
[INFO 02-25 17:35:16] ax.service.utils.instantiation: Inferred value type of ParameterType.FLOAT for parameter reg_alpha. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
[INFO 02-25 17:35:16] ax.service.utils.instantiation: Inferred value type of ParameterType.FLOAT for parameter reg_lambda. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
[INFO 02-25 17:35:16] ax.service.utils.instantiation: Created search space: SearchSpace(parameters=[RangeParameter(name='n_estimators', parameter_type=INT, range=[100, 5000]), RangeParameter(name='max_depth', parameter_type=INT, range=[3, 100]), RangeParameter(name='learning_rate', parameter_type=FLOAT, range=[0.005, 0.3], log_scale=True), RangeParameter(name='subsample', parameter_type=FLOAT, range=[0.5, 1.0]), RangeParameter(name='colsample_bytree', parameter_type=FLOAT, range=[0.3, 1.0]), RangeParameter(name='min_child_weight', parameter_type=INT, range=[1, 20]), RangeParameter(name='gamma', parameter_type=FLOAT, range=[0.0, 5.0]), RangeParameter(name='reg_alpha', parameter_type=FLOAT, range=[1e-06, 10.0], log_scale=True), RangeParameter(name='reg_lambda', parameter_type=FLOAT, range=[1e-06, 10.0], log_scale=True), RangeParameter(name='early_stopping_rounds', parameter_type=INT, range=[10, 50])], parameter_constraints=[]).
[INFO 02-25 17:35:16] ax.modelbridge.dispatch_utils: Using Models.BOTORCH_MODULAR since there is at least one ordered parameter and there are no unordered categorical parameters.
[INFO 02-25 17:35:16] ax.modelbridge.dispatch_utils: Calculating the number of remaining initialization trials based on num_initialization_trials=None max_initialization_trials=None num_tunable_parameters=10 num_trials=None use_batch_trials=False
[INFO 02-25 17:35:16] ax.modelbridge.dispatch_utils: calculated num_initialization_trials=20
[INFO 02-25 17:35:16] ax.modelbridge.dispatch_utils: num_completed_initialization_trials=0 num_remaining_initialization_trials=20
[INFO 02-25 17:35:16] ax.modelbridge.dispatch_utils: `verbose`, `disable_progbar`, and `jit_compile` are not yet supported when using `choose_generation_strategy` with ModularBoTorchModel, dropping these arguments.
[INFO 02-25 17:35:16] ax.modelbridge.dispatch_utils: Using Bayesian Optimization generation strategy: GenerationStrategy(name='Sobol+BoTorch', steps=[Sobol for 20 trials, BoTorch for subsequent trials]). Iterations after 20 will take longer to generate due to model-fitting.
c:\Users\Chris\python\Lib\site-packages\ax\modelbridge\cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 02-25 17:35:16] ax.service.ax_client: Generated new trial 0 with parameters {'n_estimators': 846, 'max_depth': 61, 'learning_rate': 0.037192, 'subsample': 0.754129, 'colsample_bytree': 0.547768, 'min_child_weight': 20, 'gamma': 0.465296, 'reg_alpha': 5.635551, 'reg_lambda': 6.1e-05, 'early_stopping_rounds': 29} using model Sobol.

============================================================
Trial 1/100
============================================================
Parameters: {'n_estimators': 846, 'max_depth': 61, 'learning_rate': 0.03719206554248498, 'subsample': 0.7541288733482361, 'colsample_bytree': 0.5477683752775192, 'min_child_weight': 20, 'gamma': 0.4652963951230049, 'reg_alpha': 5.635551059708466, 'reg_lambda': 6.097468206357738e-05, 'early_stopping_rounds': 29}

[INFO 02-25 17:58:59] ax.service.ax_client: Completed trial 0 with data: {'avg_rmse_nonzero': (0.37052, 0.029078)}.
[INFO 02-25 17:58:59] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.
c:\Users\Chris\python\Lib\site-packages\ax\modelbridge\cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 02-25 17:58:59] ax.service.ax_client: Generated new trial 1 with parameters {'n_estimators': 4041, 'max_depth': 30, 'learning_rate': 0.042852, 'subsample': 0.660767, 'colsample_bytree': 0.734029, 'min_child_weight': 7, 'gamma': 4.930101, 'reg_alpha': 0.00025, 'reg_lambda': 0.818885, 'early_stopping_rounds': 49} using model Sobol.

Result: Non-zero RMSE = 0.3705
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 2/100
============================================================
Parameters: {'n_estimators': 4041, 'max_depth': 30, 'learning_rate': 0.04285210387136406, 'subsample': 0.6607672781683505, 'colsample_bytree': 0.734029318485409, 'min_child_weight': 7, 'gamma': 4.9301014468073845, 'reg_alpha': 0.00024954599759043436, 'reg_lambda': 0.8188851431198646, 'early_stopping_rounds': 49}

[INFO 02-25 18:30:53] ax.service.ax_client: Completed trial 1 with data: {'avg_rmse_nonzero': (0.367296, 0.032199)}.
[INFO 02-25 18:30:53] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.
c:\Users\Chris\python\Lib\site-packages\ax\modelbridge\cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 02-25 18:30:53] ax.service.ax_client: Generated new trial 2 with parameters {'n_estimators': 3505, 'max_depth': 95, 'learning_rate': 0.009293, 'subsample': 0.92715, 'colsample_bytree': 0.857332, 'min_child_weight': 5, 'gamma': 2.469967, 'reg_alpha': 3.5e-05, 'reg_lambda': 0.063851, 'early_stopping_rounds': 39} using model Sobol.

Result: Non-zero RMSE = 0.3673
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 3/100
============================================================
Parameters: {'n_estimators': 3505, 'max_depth': 95, 'learning_rate': 0.009293310264185891, 'subsample': 0.9271502406336367, 'colsample_bytree': 0.8573320306837557, 'min_child_weight': 5, 'gamma': 2.469966569915414, 'reg_alpha': 3.544150611721603e-05, 'reg_lambda': 0.06385054699686148, 'early_stopping_rounds': 39}

[INFO 02-25 19:00:46] ax.service.ax_client: Completed trial 2 with data: {'avg_rmse_nonzero': (0.370871, 0.033987)}.
[INFO 02-25 19:00:46] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.
c:\Users\Chris\python\Lib\site-packages\ax\modelbridge\cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 02-25 19:00:46] ax.service.ax_client: Generated new trial 3 with parameters {'n_estimators': 1837, 'max_depth': 21, 'learning_rate': 0.173869, 'subsample': 0.521472, 'colsample_bytree': 0.343631, 'min_child_weight': 11, 'gamma': 2.925964, 'reg_alpha': 0.016142, 'reg_lambda': 3.1e-05, 'early_stopping_rounds': 18} using model Sobol.

Result: Non-zero RMSE = 0.3709
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 4/100
============================================================
Parameters: {'n_estimators': 1837, 'max_depth': 21, 'learning_rate': 0.17386926269291889, 'subsample': 0.5214716391637921, 'colsample_bytree': 0.34363102614879604, 'min_child_weight': 11, 'gamma': 2.925963532179594, 'reg_alpha': 0.016141719727460854, 'reg_lambda': 3.1310330333893475e-05, 'early_stopping_rounds': 18}

[INFO 02-25 19:19:04] ax.service.ax_client: Completed trial 3 with data: {'avg_rmse_nonzero': (0.372672, 0.02314)}.
[INFO 02-25 19:19:04] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.
c:\Users\Chris\python\Lib\site-packages\ax\modelbridge\cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 02-25 19:19:04] ax.service.ax_client: Generated new trial 4 with parameters {'n_estimators': 2538, 'max_depth': 87, 'learning_rate': 0.074371, 'subsample': 0.578714, 'colsample_bytree': 0.473671, 'min_child_weight': 16, 'gamma': 1.704117, 'reg_alpha': 2e-06, 'reg_lambda': 0.015982, 'early_stopping_rounds': 41} using model Sobol.

Result: Non-zero RMSE = 0.3727
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 5/100
============================================================
Parameters: {'n_estimators': 2538, 'max_depth': 87, 'learning_rate': 0.07437052371688621, 'subsample': 0.5787143604829907, 'colsample_bytree': 0.47367125656455755, 'min_child_weight': 16, 'gamma': 1.7041165148839355, 'reg_alpha': 1.5261724316794275e-06, 'reg_lambda': 0.015982083008113584, 'early_stopping_rounds': 41}

[INFO 02-25 19:44:23] ax.service.ax_client: Completed trial 4 with data: {'avg_rmse_nonzero': (0.366451, 0.028364)}.
[INFO 02-25 19:44:23] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.
c:\Users\Chris\python\Lib\site-packages\ax\modelbridge\cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 02-25 19:44:23] ax.service.ax_client: Generated new trial 5 with parameters {'n_estimators': 2942, 'max_depth': 4, 'learning_rate': 0.01914, 'subsample': 0.984375, 'colsample_bytree': 0.988083, 'min_child_weight': 9, 'gamma': 3.690899, 'reg_alpha': 0.039165, 'reg_lambda': 1e-06, 'early_stopping_rounds': 21} using model Sobol.

Result: Non-zero RMSE = 0.3665
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 6/100
============================================================
Parameters: {'n_estimators': 2942, 'max_depth': 4, 'learning_rate': 0.019139947347849864, 'subsample': 0.9843751401640475, 'colsample_bytree': 0.9880825681611896, 'min_child_weight': 9, 'gamma': 3.6908992612734437, 'reg_alpha': 0.0391652725822899, 'reg_lambda': 1.0452009326182967e-06, 'early_stopping_rounds': 21}

[INFO 02-25 20:05:51] ax.service.ax_client: Completed trial 5 with data: {'avg_rmse_nonzero': (0.370319, 0.026525)}.
[INFO 02-25 20:05:51] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.
c:\Users\Chris\python\Lib\site-packages\ax\modelbridge\cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 02-25 20:05:51] ax.service.ax_client: Generated new trial 6 with parameters {'n_estimators': 4546, 'max_depth': 72, 'learning_rate': 0.245598, 'subsample': 0.720486, 'colsample_bytree': 0.777964, 'min_child_weight': 1, 'gamma': 1.228395, 'reg_alpha': 0.312798, 'reg_lambda': 0.001827, 'early_stopping_rounds': 10} using model Sobol.

Result: Non-zero RMSE = 0.3703
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 7/100
============================================================
Parameters: {'n_estimators': 4546, 'max_depth': 72, 'learning_rate': 0.24559792533374375, 'subsample': 0.7204856188036501, 'colsample_bytree': 0.7779637704603374, 'min_child_weight': 1, 'gamma': 1.2283948762342334, 'reg_alpha': 0.31279803629632, 'reg_lambda': 0.0018272378394420456, 'early_stopping_rounds': 10}

[INFO 02-25 20:21:05] ax.service.ax_client: Completed trial 6 with data: {'avg_rmse_nonzero': (0.375738, 0.033627)}.
[INFO 02-25 20:21:05] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.
c:\Users\Chris\python\Lib\site-packages\ax\modelbridge\cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 02-25 20:21:05] ax.service.ax_client: Generated new trial 7 with parameters {'n_estimators': 164, 'max_depth': 44, 'learning_rate': 0.005714, 'subsample': 0.81383, 'colsample_bytree': 0.59236, 'min_child_weight': 15, 'gamma': 4.167307, 'reg_alpha': 0.000777, 'reg_lambda': 3.271988, 'early_stopping_rounds': 31} using model Sobol.

Result: Non-zero RMSE = 0.3757
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 8/100
============================================================
Parameters: {'n_estimators': 164, 'max_depth': 44, 'learning_rate': 0.005713851565008485, 'subsample': 0.8138296203687787, 'colsample_bytree': 0.5923597279004753, 'min_child_weight': 15, 'gamma': 4.1673069493845105, 'reg_alpha': 0.0007773489219910975, 'reg_lambda': 3.2719882233510718, 'early_stopping_rounds': 31}

[INFO 02-25 20:46:49] ax.service.ax_client: Completed trial 7 with data: {'avg_rmse_nonzero': (0.382065, 0.026093)}.
[INFO 02-25 20:46:49] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.
c:\Users\Chris\python\Lib\site-packages\ax\modelbridge\cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 02-25 20:46:49] ax.service.ax_client: Generated new trial 8 with parameters {'n_estimators': 688, 'max_depth': 93, 'learning_rate': 0.203427, 'subsample': 0.956168, 'colsample_bytree': 0.690897, 'min_child_weight': 13, 'gamma': 1.407171, 'reg_alpha': 4e-06, 'reg_lambda': 0.005079, 'early_stopping_rounds': 17} using model Sobol.

Result: Non-zero RMSE = 0.3821
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 9/100
============================================================
Parameters: {'n_estimators': 688, 'max_depth': 93, 'learning_rate': 0.203426731966392, 'subsample': 0.956167830619961, 'colsample_bytree': 0.6908972417935728, 'min_child_weight': 13, 'gamma': 1.4071706216782331, 'reg_alpha': 4.430699200802297e-06, 'reg_lambda': 0.0050792323398422155, 'early_stopping_rounds': 17}

[INFO 02-25 21:04:50] ax.service.ax_client: Completed trial 8 with data: {'avg_rmse_nonzero': (0.369971, 0.036734)}.
[INFO 02-25 21:04:50] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.
c:\Users\Chris\python\Lib\site-packages\ax\modelbridge\cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 02-25 21:04:50] ax.service.ax_client: Generated new trial 9 with parameters {'n_estimators': 4807, 'max_depth': 22, 'learning_rate': 0.007896, 'subsample': 0.612823, 'colsample_bytree': 0.5046, 'min_child_weight': 4, 'gamma': 3.197439, 'reg_alpha': 0.100372, 'reg_lambda': 7e-06, 'early_stopping_rounds': 37} using model Sobol.

Result: Non-zero RMSE = 0.3700
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 10/100
============================================================
Parameters: {'n_estimators': 4807, 'max_depth': 22, 'learning_rate': 0.007895516634468627, 'subsample': 0.6128229917958379, 'colsample_bytree': 0.5045995710417628, 'min_child_weight': 4, 'gamma': 3.1974392756819725, 'reg_alpha': 0.10037249153540279, 'reg_lambda': 6.848158179159099e-06, 'early_stopping_rounds': 37}

[INFO 02-25 21:39:49] ax.service.ax_client: Completed trial 9 with data: {'avg_rmse_nonzero': (0.36622, 0.027949)}.
[INFO 02-25 21:39:49] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.
c:\Users\Chris\python\Lib\site-packages\ax\modelbridge\cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 02-25 21:39:50] ax.service.ax_client: Generated new trial 10 with parameters {'n_estimators': 2738, 'max_depth': 53, 'learning_rate': 0.101136, 'subsample': 0.845952, 'colsample_bytree': 0.386765, 'min_child_weight': 8, 'gamma': 0.657421, 'reg_alpha': 0.909215, 'reg_lambda': 0.000765, 'early_stopping_rounds': 48} using model Sobol.

Result: Non-zero RMSE = 0.3662
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 11/100
============================================================
Parameters: {'n_estimators': 2738, 'max_depth': 53, 'learning_rate': 0.10113592145039131, 'subsample': 0.8459517480805516, 'colsample_bytree': 0.3867646153084934, 'min_child_weight': 8, 'gamma': 0.657420763745904, 'reg_alpha': 0.9092148691816397, 'reg_lambda': 0.0007648724119556241, 'early_stopping_rounds': 48}

[INFO 02-25 22:16:45] ax.service.ax_client: Completed trial 10 with data: {'avg_rmse_nonzero': (0.372473, 0.029163)}.
[INFO 02-25 22:16:45] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.
c:\Users\Chris\python\Lib\site-packages\ax\modelbridge\cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 02-25 22:16:45] ax.service.ax_client: Generated new trial 11 with parameters {'n_estimators': 1995, 'max_depth': 38, 'learning_rate': 0.015602, 'subsample': 0.69029, 'colsample_bytree': 0.900505, 'min_child_weight': 19, 'gamma': 3.946656, 'reg_alpha': 0.00199, 'reg_lambda': 3.765428, 'early_stopping_rounds': 26} using model Sobol.

Result: Non-zero RMSE = 0.3725
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 12/100
============================================================
Parameters: {'n_estimators': 1995, 'max_depth': 38, 'learning_rate': 0.015601839015502432, 'subsample': 0.6902898983098567, 'colsample_bytree': 0.9005049961619078, 'min_child_weight': 19, 'gamma': 3.946655672043562, 'reg_alpha': 0.001989735211945491, 'reg_lambda': 3.7654277576401154, 'early_stopping_rounds': 26}

[INFO 02-25 22:46:46] ax.service.ax_client: Completed trial 11 with data: {'avg_rmse_nonzero': (0.368523, 0.030984)}.
[INFO 02-25 22:46:46] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.
c:\Users\Chris\python\Lib\site-packages\ax\modelbridge\cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 02-25 22:46:46] ax.service.ax_client: Generated new trial 12 with parameters {'n_estimators': 1466, 'max_depth': 70, 'learning_rate': 0.011131, 'subsample': 0.632559, 'colsample_bytree': 0.945096, 'min_child_weight': 13, 'gamma': 0.16835, 'reg_alpha': 2.201702, 'reg_lambda': 0.000407, 'early_stopping_rounds': 34} using model Sobol.

Result: Non-zero RMSE = 0.3685
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 13/100
============================================================
Parameters: {'n_estimators': 1466, 'max_depth': 70, 'learning_rate': 0.011130509487994641, 'subsample': 0.6325590149499476, 'colsample_bytree': 0.9450960286892951, 'min_child_weight': 13, 'gamma': 0.16834994312375784, 'reg_alpha': 2.2017022708593705, 'reg_lambda': 0.00040744451334748526, 'early_stopping_rounds': 34}

[INFO 02-25 23:29:55] ax.service.ax_client: Completed trial 12 with data: {'avg_rmse_nonzero': (0.373679, 0.031371)}.
[INFO 02-25 23:29:55] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.
c:\Users\Chris\python\Lib\site-packages\ax\modelbridge\cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 02-25 23:29:55] ax.service.ax_client: Generated new trial 13 with parameters {'n_estimators': 3398, 'max_depth': 45, 'learning_rate': 0.124824, 'subsample': 0.788238, 'colsample_bytree': 0.430699, 'min_child_weight': 2, 'gamma': 4.436641, 'reg_alpha': 8.6e-05, 'reg_lambda': 0.267516, 'early_stopping_rounds': 14} using model Sobol.

Result: Non-zero RMSE = 0.3737
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 14/100
============================================================
Parameters: {'n_estimators': 3398, 'max_depth': 45, 'learning_rate': 0.1248238155827856, 'subsample': 0.7882384480908513, 'colsample_bytree': 0.43069872567430134, 'min_child_weight': 2, 'gamma': 4.436640837229788, 'reg_alpha': 8.585121151747232e-05, 'reg_lambda': 0.26751648761577734, 'early_stopping_rounds': 14}

[INFO 02-25 23:54:02] ax.service.ax_client: Completed trial 13 with data: {'avg_rmse_nonzero': (0.365095, 0.03209)}.
[INFO 02-25 23:54:02] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.
c:\Users\Chris\python\Lib\site-packages\ax\modelbridge\cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 02-25 23:54:02] ax.service.ax_client: Generated new trial 14 with parameters {'n_estimators': 4091, 'max_depth': 79, 'learning_rate': 0.027131, 'subsample': 0.553593, 'colsample_bytree': 0.63535, 'min_child_weight': 8, 'gamma': 1.898993, 'reg_alpha': 1.4e-05, 'reg_lambda': 0.071483, 'early_stopping_rounds': 24} using model Sobol.

Result: Non-zero RMSE = 0.3651
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 15/100
============================================================
Parameters: {'n_estimators': 4091, 'max_depth': 79, 'learning_rate': 0.027131485262852268, 'subsample': 0.5535928132012486, 'colsample_bytree': 0.6353504501283169, 'min_child_weight': 8, 'gamma': 1.898993174545467, 'reg_alpha': 1.3829302837440574e-05, 'reg_lambda': 0.0714832506211947, 'early_stopping_rounds': 24}

[INFO 02-26 00:20:06] ax.service.ax_client: Completed trial 14 with data: {'avg_rmse_nonzero': (0.368531, 0.030771)}.
[INFO 02-26 00:20:06] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.
c:\Users\Chris\python\Lib\site-packages\ax\modelbridge\cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 02-26 00:20:06] ax.service.ax_client: Generated new trial 15 with parameters {'n_estimators': 1236, 'max_depth': 12, 'learning_rate': 0.052151, 'subsample': 0.896955, 'colsample_bytree': 0.820938, 'min_child_weight': 17, 'gamma': 2.705313, 'reg_alpha': 0.00556, 'reg_lambda': 1.3e-05, 'early_stopping_rounds': 45} using model Sobol.

Result: Non-zero RMSE = 0.3685
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 16/100
============================================================
Parameters: {'n_estimators': 1236, 'max_depth': 12, 'learning_rate': 0.05215107391204479, 'subsample': 0.8969554738141596, 'colsample_bytree': 0.8209377929568291, 'min_child_weight': 17, 'gamma': 2.70531274843961, 'reg_alpha': 0.0055600599053958885, 'reg_lambda': 1.2850990959920442e-05, 'early_stopping_rounds': 45}

[INFO 02-26 00:52:35] ax.service.ax_client: Completed trial 15 with data: {'avg_rmse_nonzero': (0.374586, 0.033515)}.
[INFO 02-26 00:52:35] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.
c:\Users\Chris\python\Lib\site-packages\ax\modelbridge\cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 02-26 00:52:35] ax.service.ax_client: Generated new trial 16 with parameters {'n_estimators': 1096, 'max_depth': 81, 'learning_rate': 0.006772, 'subsample': 0.747145, 'colsample_bytree': 0.300415, 'min_child_weight': 2, 'gamma': 4.834012, 'reg_alpha': 8e-06, 'reg_lambda': 4e-06, 'early_stopping_rounds': 21} using model Sobol.

Result: Non-zero RMSE = 0.3746
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 17/100
============================================================
Parameters: {'n_estimators': 1096, 'max_depth': 81, 'learning_rate': 0.006771950047612621, 'subsample': 0.7471450590528548, 'colsample_bytree': 0.3004145257174969, 'min_child_weight': 2, 'gamma': 4.834012286737561, 'reg_alpha': 8.063912551822031e-06, 'reg_lambda': 3.8104569217681103e-06, 'early_stopping_rounds': 21}

[INFO 02-26 01:19:15] ax.service.ax_client: Completed trial 16 with data: {'avg_rmse_nonzero': (0.37069, 0.026081)}.
[INFO 02-26 01:19:15] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.
c:\Users\Chris\python\Lib\site-packages\ax\modelbridge\cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 02-26 01:19:15] ax.service.ax_client: Generated new trial 17 with parameters {'n_estimators': 4372, 'max_depth': 10, 'learning_rate': 0.21042, 'subsample': 0.841346, 'colsample_bytree': 0.835949, 'min_child_weight': 14, 'gamma': 0.55124, 'reg_alpha': 0.003246, 'reg_lambda': 0.006824, 'early_stopping_rounds': 43} using model Sobol.

Result: Non-zero RMSE = 0.3707
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 18/100
============================================================
Parameters: {'n_estimators': 4372, 'max_depth': 10, 'learning_rate': 0.21042019947274843, 'subsample': 0.8413464734330773, 'colsample_bytree': 0.8359491720795631, 'min_child_weight': 14, 'gamma': 0.5512396432459354, 'reg_alpha': 0.003245533043805597, 'reg_lambda': 0.00682354558467388, 'early_stopping_rounds': 43}

[INFO 02-26 01:51:14] ax.service.ax_client: Completed trial 17 with data: {'avg_rmse_nonzero': (0.383827, 0.036625)}.
[INFO 02-26 01:51:14] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.
c:\Users\Chris\python\Lib\site-packages\ax\modelbridge\cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 02-26 01:51:14] ax.service.ax_client: Generated new trial 18 with parameters {'n_estimators': 3222, 'max_depth': 66, 'learning_rate': 0.016136, 'subsample': 0.574521, 'colsample_bytree': 0.697606, 'min_child_weight': 18, 'gamma': 3.088741, 'reg_alpha': 3.51915, 'reg_lambda': 7.67678, 'early_stopping_rounds': 32} using model Sobol.

Result: Non-zero RMSE = 0.3838
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 19/100
============================================================
Parameters: {'n_estimators': 3222, 'max_depth': 66, 'learning_rate': 0.01613625721077803, 'subsample': 0.5745205292478204, 'colsample_bytree': 0.6976060309447347, 'min_child_weight': 18, 'gamma': 3.088740920647979, 'reg_alpha': 3.5191503844187246, 'reg_lambda': 7.67678006815864, 'early_stopping_rounds': 32}

[INFO 02-26 02:19:27] ax.service.ax_client: Completed trial 18 with data: {'avg_rmse_nonzero': (0.371745, 0.030267)}.
[INFO 02-26 02:19:27] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.
c:\Users\Chris\python\Lib\site-packages\ax\modelbridge\cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 02-26 02:19:27] ax.service.ax_client: Generated new trial 19 with parameters {'n_estimators': 1482, 'max_depth': 50, 'learning_rate': 0.086712, 'subsample': 0.981283, 'colsample_bytree': 0.533264, 'min_child_weight': 9, 'gamma': 2.297198, 'reg_alpha': 0.000137, 'reg_lambda': 0.000502, 'early_stopping_rounds': 12} using model Sobol.

Result: Non-zero RMSE = 0.3717
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 20/100
============================================================
Parameters: {'n_estimators': 1482, 'max_depth': 50, 'learning_rate': 0.08671161431471744, 'subsample': 0.9812828623689711, 'colsample_bytree': 0.5332641781307756, 'min_child_weight': 9, 'gamma': 2.297198250889778, 'reg_alpha': 0.00013709413072868521, 'reg_lambda': 0.0005020756928706462, 'early_stopping_rounds': 12}

[INFO 02-26 02:42:19] ax.service.ax_client: Completed trial 19 with data: {'avg_rmse_nonzero': (0.37, 0.031119)}.
[INFO 02-26 02:42:19] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Result: Non-zero RMSE = 0.3700
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 21/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-26 02:42:29] ax.service.ax_client: Generated new trial 20 with parameters {'n_estimators': 4945, 'max_depth': 100, 'learning_rate': 0.3, 'subsample': 1.0, 'colsample_bytree': 0.480914, 'min_child_weight': 1, 'gamma': 0.0, 'reg_alpha': 10.0, 'reg_lambda': 1e-06, 'early_stopping_rounds': 25} using model BoTorch.

Parameters: {'n_estimators': 4945, 'max_depth': 100, 'learning_rate': 0.29999999999999993, 'subsample': 1.0, 'colsample_bytree': 0.4809144781412095, 'min_child_weight': 1, 'gamma': 0.0, 'reg_alpha': 10.0, 'reg_lambda': 1e-06, 'early_stopping_rounds': 25}

[INFO 02-26 03:08:21] ax.service.ax_client: Completed trial 20 with data: {'avg_rmse_nonzero': (0.377766, 0.02267)}.
[INFO 02-26 03:08:21] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Result: Non-zero RMSE = 0.3778
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 22/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-26 03:08:29] ax.service.ax_client: Generated new trial 21 with parameters {'n_estimators': 1896, 'max_depth': 3, 'learning_rate': 0.3, 'subsample': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 20, 'gamma': 0.0, 'reg_alpha': 1e-06, 'reg_lambda': 1e-06, 'early_stopping_rounds': 50} using model BoTorch.

Parameters: {'n_estimators': 1896, 'max_depth': 3, 'learning_rate': 0.29999999999999993, 'subsample': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 20, 'gamma': 0.0, 'reg_alpha': 1e-06, 'reg_lambda': 1.4310558861233428e-06, 'early_stopping_rounds': 50}

[INFO 02-26 03:58:11] ax.service.ax_client: Completed trial 21 with data: {'avg_rmse_nonzero': (0.382532, 0.017173)}.
[INFO 02-26 03:58:11] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Result: Non-zero RMSE = 0.3825
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 23/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-26 03:58:20] ax.modelbridge.base: Untransformed parameter 0.004999999999999999 less than lower bound 0.005, clamping
[INFO 02-26 03:58:20] ax.service.ax_client: Generated new trial 22 with parameters {'n_estimators': 1362, 'max_depth': 100, 'learning_rate': 0.005, 'subsample': 0.5, 'colsample_bytree': 0.3, 'min_child_weight': 20, 'gamma': 5.0, 'reg_alpha': 1e-06, 'reg_lambda': 1e-06, 'early_stopping_rounds': 10} using model BoTorch.

Parameters: {'n_estimators': 1362, 'max_depth': 100, 'learning_rate': 0.005, 'subsample': 0.5, 'colsample_bytree': 0.3, 'min_child_weight': 20, 'gamma': 5.0, 'reg_alpha': 1e-06, 'reg_lambda': 1e-06, 'early_stopping_rounds': 10}

[INFO 02-26 04:22:52] ax.service.ax_client: Completed trial 22 with data: {'avg_rmse_nonzero': (0.37046, 0.026909)}.
[INFO 02-26 04:22:52] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Result: Non-zero RMSE = 0.3705
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 24/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-26 04:23:01] ax.modelbridge.base: Untransformed parameter 0.004999999999999999 less than lower bound 0.005, clamping
[INFO 02-26 04:23:01] ax.service.ax_client: Generated new trial 23 with parameters {'n_estimators': 437, 'max_depth': 100, 'learning_rate': 0.005, 'subsample': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 1, 'gamma': 0.236044, 'reg_alpha': 1e-06, 'reg_lambda': 0.941595, 'early_stopping_rounds': 50} using model BoTorch.

Parameters: {'n_estimators': 437, 'max_depth': 100, 'learning_rate': 0.005, 'subsample': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 1, 'gamma': 0.2360438221126433, 'reg_alpha': 1e-06, 'reg_lambda': 0.9415946617205196, 'early_stopping_rounds': 50}

[INFO 02-26 05:10:11] ax.service.ax_client: Completed trial 23 with data: {'avg_rmse_nonzero': (0.400865, 0.036955)}.
[INFO 02-26 05:10:11] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Result: Non-zero RMSE = 0.4009
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 25/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-26 05:10:18] ax.service.ax_client: Generated new trial 24 with parameters {'n_estimators': 100, 'max_depth': 100, 'learning_rate': 0.3, 'subsample': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 20, 'gamma': 5.0, 'reg_alpha': 10.0, 'reg_lambda': 1e-06, 'early_stopping_rounds': 50} using model BoTorch.

Parameters: {'n_estimators': 100, 'max_depth': 100, 'learning_rate': 0.29999999999999993, 'subsample': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 20, 'gamma': 5.0, 'reg_alpha': 10.0, 'reg_lambda': 1e-06, 'early_stopping_rounds': 50}

[INFO 02-26 05:43:50] ax.service.ax_client: Completed trial 24 with data: {'avg_rmse_nonzero': (0.372849, 0.031431)}.
[INFO 02-26 05:43:50] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Result: Non-zero RMSE = 0.3728
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 26/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-26 05:43:58] ax.service.ax_client: Generated new trial 25 with parameters {'n_estimators': 3308, 'max_depth': 3, 'learning_rate': 0.3, 'subsample': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 1, 'gamma': 5.0, 'reg_alpha': 1e-06, 'reg_lambda': 10.0, 'early_stopping_rounds': 50} using model BoTorch.

Parameters: {'n_estimators': 3308, 'max_depth': 3, 'learning_rate': 0.29999999999999993, 'subsample': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 1, 'gamma': 5.0, 'reg_alpha': 1e-06, 'reg_lambda': 10.0, 'early_stopping_rounds': 50}

[INFO 02-26 06:20:37] ax.service.ax_client: Completed trial 25 with data: {'avg_rmse_nonzero': (0.393028, 0.025191)}.
[INFO 02-26 06:20:37] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Result: Non-zero RMSE = 0.3930
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 27/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-26 06:20:46] ax.service.ax_client: Generated new trial 26 with parameters {'n_estimators': 4007, 'max_depth': 13, 'learning_rate': 0.3, 'subsample': 1.0, 'colsample_bytree': 0.3, 'min_child_weight': 1, 'gamma': 2.769442, 'reg_alpha': 1e-06, 'reg_lambda': 10.0, 'early_stopping_rounds': 10} using model BoTorch.

Parameters: {'n_estimators': 4007, 'max_depth': 13, 'learning_rate': 0.29999999999999993, 'subsample': 1.0, 'colsample_bytree': 0.3, 'min_child_weight': 1, 'gamma': 2.7694422868573865, 'reg_alpha': 1e-06, 'reg_lambda': 10.0, 'early_stopping_rounds': 10}

[INFO 02-26 06:41:44] ax.service.ax_client: Completed trial 26 with data: {'avg_rmse_nonzero': (0.378716, 0.022291)}.
[INFO 02-26 06:41:44] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Result: Non-zero RMSE = 0.3787
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 28/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 2940, 'max_depth': 81, 'learning_rate': 0.0053230643450975345, 'subsample': 0.5, 'colsample_bytree': 0.3, 'min_child_weight': 8, 'gamma': 5.0, 'reg_alpha': 1e-06, 'reg_lambda': 10.0, 'early_stopping_rounds': 10}

[INFO 02-26 07:05:57] ax.service.ax_client: Completed trial 27 with data: {'avg_rmse_nonzero': (0.371305, 0.026795)}.
[INFO 02-26 07:05:57] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Result: Non-zero RMSE = 0.3713
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 29/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-26 07:06:07] ax.modelbridge.base: Untransformed parameter 0.004999999999999999 less than lower bound 0.005, clamping
[INFO 02-26 07:06:07] ax.service.ax_client: Generated new trial 28 with parameters {'n_estimators': 4842, 'max_depth': 100, 'learning_rate': 0.005, 'subsample': 0.776409, 'colsample_bytree': 1.0, 'min_child_weight': 1, 'gamma': 3.706307, 'reg_alpha': 1e-06, 'reg_lambda': 10.0, 'early_stopping_rounds': 15} using model BoTorch.

Parameters: {'n_estimators': 4842, 'max_depth': 100, 'learning_rate': 0.005, 'subsample': 0.7764090483024929, 'colsample_bytree': 1.0, 'min_child_weight': 1, 'gamma': 3.7063073058130995, 'reg_alpha': 1e-06, 'reg_lambda': 10.0, 'early_stopping_rounds': 15}

[INFO 02-26 07:31:38] ax.service.ax_client: Completed trial 28 with data: {'avg_rmse_nonzero': (0.372871, 0.032322)}.
[INFO 02-26 07:31:38] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Result: Non-zero RMSE = 0.3729
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 30/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-26 07:31:46] ax.modelbridge.base: Untransformed parameter 0.004999999999999999 less than lower bound 0.005, clamping
[INFO 02-26 07:31:46] ax.service.ax_client: Generated new trial 29 with parameters {'n_estimators': 5000, 'max_depth': 3, 'learning_rate': 0.005, 'subsample': 1.0, 'colsample_bytree': 0.3, 'min_child_weight': 20, 'gamma': 5.0, 'reg_alpha': 10.0, 'reg_lambda': 1e-06, 'early_stopping_rounds': 10} using model BoTorch.

Parameters: {'n_estimators': 5000, 'max_depth': 3, 'learning_rate': 0.005, 'subsample': 1.0, 'colsample_bytree': 0.3, 'min_child_weight': 20, 'gamma': 5.0, 'reg_alpha': 10.0, 'reg_lambda': 1e-06, 'early_stopping_rounds': 10}

[INFO 02-26 07:54:16] ax.service.ax_client: Completed trial 29 with data: {'avg_rmse_nonzero': (0.379451, 0.023082)}.
[INFO 02-26 07:54:16] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Result: Non-zero RMSE = 0.3795
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 31/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-26 07:54:24] ax.modelbridge.base: Untransformed parameter 0.004999999999999999 less than lower bound 0.005, clamping
[INFO 02-26 07:54:24] ax.service.ax_client: Generated new trial 30 with parameters {'n_estimators': 100, 'max_depth': 3, 'learning_rate': 0.005, 'subsample': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 20, 'gamma': 0.0, 'reg_alpha': 1e-06, 'reg_lambda': 10.0, 'early_stopping_rounds': 10} using model BoTorch.

Parameters: {'n_estimators': 100, 'max_depth': 3, 'learning_rate': 0.005, 'subsample': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 20, 'gamma': 0.0, 'reg_alpha': 1e-06, 'reg_lambda': 10.0, 'early_stopping_rounds': 10}

[INFO 02-26 08:22:53] ax.service.ax_client: Completed trial 30 with data: {'avg_rmse_nonzero': (0.407265, 0.026478)}.
[INFO 02-26 08:22:53] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Result: Non-zero RMSE = 0.4073
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 32/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 4962, 'max_depth': 49, 'learning_rate': 0.29999999999999993, 'subsample': 0.7913417880429356, 'colsample_bytree': 1.0, 'min_child_weight': 1, 'gamma': 0.0, 'reg_alpha': 10.0, 'reg_lambda': 4.435211397899921, 'early_stopping_rounds': 10}

[INFO 02-26 08:46:51] ax.service.ax_client: Completed trial 31 with data: {'avg_rmse_nonzero': (0.381215, 0.028987)}.
[INFO 02-26 08:46:51] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Result: Non-zero RMSE = 0.3812
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 33/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 630, 'max_depth': 49, 'learning_rate': 0.005, 'subsample': 0.7945618403965203, 'colsample_bytree': 1.0, 'min_child_weight': 14, 'gamma': 0.0, 'reg_alpha': 10.0, 'reg_lambda': 1e-06, 'early_stopping_rounds': 10}

[INFO 02-26 09:42:57] ax.service.ax_client: Completed trial 32 with data: {'avg_rmse_nonzero': (0.381864, 0.028558)}.
[INFO 02-26 09:42:57] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Result: Non-zero RMSE = 0.3819
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 34/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 424, 'max_depth': 17, 'learning_rate': 0.008643982238799676, 'subsample': 0.501127300200943, 'colsample_bytree': 0.7704216588018129, 'min_child_weight': 20, 'gamma': 5.0, 'reg_alpha': 0.24294866685862873, 'reg_lambda': 10.0, 'early_stopping_rounds': 41}

[INFO 02-26 10:19:23] ax.service.ax_client: Completed trial 33 with data: {'avg_rmse_nonzero': (0.371462, 0.029681)}.
[INFO 02-26 10:19:23] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Result: Non-zero RMSE = 0.3715
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 35/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 1461, 'max_depth': 97, 'learning_rate': 0.005, 'subsample': 0.9919875358659891, 'colsample_bytree': 0.5670383565154151, 'min_child_weight': 10, 'gamma': 5.0, 'reg_alpha': 0.0026797790033521993, 'reg_lambda': 10.0, 'early_stopping_rounds': 50}

[INFO 02-26 11:01:49] ax.service.ax_client: Completed trial 34 with data: {'avg_rmse_nonzero': (0.368523, 0.029515)}.
[INFO 02-26 11:01:49] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Result: Non-zero RMSE = 0.3685
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 36/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 4644, 'max_depth': 64, 'learning_rate': 0.021486680839387998, 'subsample': 0.7696416456654817, 'colsample_bytree': 0.3, 'min_child_weight': 9, 'gamma': 4.516558114584556, 'reg_alpha': 10.0, 'reg_lambda': 10.0, 'early_stopping_rounds': 49}

[INFO 02-26 11:36:19] ax.service.ax_client: Completed trial 35 with data: {'avg_rmse_nonzero': (0.371251, 0.027503)}.
[INFO 02-26 11:36:19] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Result: Non-zero RMSE = 0.3713
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 37/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 205, 'max_depth': 20, 'learning_rate': 0.005, 'subsample': 0.5077037082090192, 'colsample_bytree': 0.3, 'min_child_weight': 1, 'gamma': 5.0, 'reg_alpha': 1.9021840542021012e-05, 'reg_lambda': 1.8928599293502804, 'early_stopping_rounds': 10}

[INFO 02-26 11:59:27] ax.service.ax_client: Completed trial 36 with data: {'avg_rmse_nonzero': (0.383245, 0.023742)}.
[INFO 02-26 11:59:28] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Result: Non-zero RMSE = 0.3832
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 38/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 3704, 'max_depth': 100, 'learning_rate': 0.005, 'subsample': 1.0, 'colsample_bytree': 0.893785286928914, 'min_child_weight': 1, 'gamma': 5.0, 'reg_alpha': 0.00028585539108908246, 'reg_lambda': 1e-06, 'early_stopping_rounds': 43}

[INFO 02-26 12:33:14] ax.service.ax_client: Completed trial 37 with data: {'avg_rmse_nonzero': (0.369611, 0.032285)}.
[INFO 02-26 12:33:14] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Result: Non-zero RMSE = 0.3696
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 39/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 4000, 'max_depth': 52, 'learning_rate': 0.2277538101478525, 'subsample': 0.9532488646653594, 'colsample_bytree': 0.3890800094509975, 'min_child_weight': 5, 'gamma': 4.408229180718665, 'reg_alpha': 0.019086167045218032, 'reg_lambda': 4.3327952729440184, 'early_stopping_rounds': 46}

[INFO 02-26 13:09:40] ax.service.ax_client: Completed trial 38 with data: {'avg_rmse_nonzero': (0.385488, 0.022631)}.
[INFO 02-26 13:09:40] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Result: Non-zero RMSE = 0.3855
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 40/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 4108, 'max_depth': 3, 'learning_rate': 0.09266444958494957, 'subsample': 0.5, 'colsample_bytree': 0.3, 'min_child_weight': 13, 'gamma': 4.5057633563356765, 'reg_alpha': 1e-06, 'reg_lambda': 1e-06, 'early_stopping_rounds': 10}

[INFO 02-26 13:32:38] ax.service.ax_client: Completed trial 39 with data: {'avg_rmse_nonzero': (0.379962, 0.019267)}.
[INFO 02-26 13:32:38] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Result: Non-zero RMSE = 0.3800
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 41/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 4459, 'max_depth': 100, 'learning_rate': 0.005, 'subsample': 0.9840930160317501, 'colsample_bytree': 0.6585203088572152, 'min_child_weight': 20, 'gamma': 4.050223491816839, 'reg_alpha': 1e-06, 'reg_lambda': 1e-06, 'early_stopping_rounds': 20}

[INFO 02-26 14:01:55] ax.service.ax_client: Completed trial 40 with data: {'avg_rmse_nonzero': (0.367753, 0.030445)}.
[INFO 02-26 14:01:55] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Result: Non-zero RMSE = 0.3678
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 42/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 2095, 'max_depth': 100, 'learning_rate': 0.005, 'subsample': 0.5, 'colsample_bytree': 0.30548687651908507, 'min_child_weight': 3, 'gamma': 2.865093135658711, 'reg_alpha': 1e-06, 'reg_lambda': 0.00021676017284036898, 'early_stopping_rounds': 28}

[INFO 02-26 14:35:25] ax.service.ax_client: Completed trial 41 with data: {'avg_rmse_nonzero': (0.369808, 0.025514)}.
[INFO 02-26 14:35:25] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Result: Non-zero RMSE = 0.3698
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 43/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 3555, 'max_depth': 38, 'learning_rate': 0.005, 'subsample': 0.969565597252104, 'colsample_bytree': 0.7122925312096021, 'min_child_weight': 20, 'gamma': 5.0, 'reg_alpha': 0.1791075020846003, 'reg_lambda': 6.590541261243023, 'early_stopping_rounds': 10}

[INFO 02-26 14:59:26] ax.service.ax_client: Completed trial 42 with data: {'avg_rmse_nonzero': (0.369958, 0.03105)}.
[INFO 02-26 14:59:26] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Result: Non-zero RMSE = 0.3700
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 44/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 3044, 'max_depth': 98, 'learning_rate': 0.005, 'subsample': 0.5516798206243066, 'colsample_bytree': 1.0, 'min_child_weight': 5, 'gamma': 0.0, 'reg_alpha': 0.2752380754414213, 'reg_lambda': 1.395040054725046e-06, 'early_stopping_rounds': 43}

[INFO 02-26 19:22:13] ax.service.ax_client: Completed trial 43 with data: {'avg_rmse_nonzero': (0.377257, 0.037102)}.
[INFO 02-26 19:22:13] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Result: Non-zero RMSE = 0.3773
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 45/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 744, 'max_depth': 100, 'learning_rate': 0.005, 'subsample': 0.5, 'colsample_bytree': 0.3, 'min_child_weight': 1, 'gamma': 0.5791306983900865, 'reg_alpha': 1e-06, 'reg_lambda': 1e-06, 'early_stopping_rounds': 43}

[INFO 02-26 20:11:11] ax.service.ax_client: Completed trial 44 with data: {'avg_rmse_nonzero': (0.370091, 0.024073)}.
[INFO 02-26 20:11:11] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Result: Non-zero RMSE = 0.3701
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 46/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-26 20:11:24] ax.modelbridge.base: Untransformed parameter 0.004999999999999999 less than lower bound 0.005, clamping
[INFO 02-26 20:11:24] ax.service.ax_client: Generated new trial 45 with parameters {'n_estimators': 1741, 'max_depth': 53, 'learning_rate': 0.014656, 'subsample': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 1, 'gamma': 5.0, 'reg_alpha': 2.322271, 'reg_lambda': 1e-06, 'early_stopping_rounds': 10} using model BoTorch.

Parameters: {'n_estimators': 1741, 'max_depth': 53, 'learning_rate': 0.014655851088700527, 'subsample': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 1, 'gamma': 5.0, 'reg_alpha': 2.322270573238195, 'reg_lambda': 1e-06, 'early_stopping_rounds': 10}

[INFO 02-26 20:34:32] ax.service.ax_client: Completed trial 45 with data: {'avg_rmse_nonzero': (0.370254, 0.031973)}.
[INFO 02-26 20:34:32] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Result: Non-zero RMSE = 0.3703
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 47/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-26 20:34:44] ax.modelbridge.base: Untransformed parameter 0.004999999999999999 less than lower bound 0.005, clamping
[INFO 02-26 20:34:44] ax.modelbridge.base: Untransformed parameter 0.004999999999999999 less than lower bound 0.005, clamping
[INFO 02-26 20:34:45] ax.service.ax_client: Generated new trial 46 with parameters {'n_estimators': 5000, 'max_depth': 100, 'learning_rate': 0.005, 'subsample': 0.5, 'colsample_bytree': 0.3, 'min_child_weight': 20, 'gamma': 3.490945, 'reg_alpha': 1e-06, 'reg_lambda': 10.0, 'early_stopping_rounds': 29} using model BoTorch.

Parameters: {'n_estimators': 5000, 'max_depth': 100, 'learning_rate': 0.005, 'subsample': 0.5, 'colsample_bytree': 0.3, 'min_child_weight': 20, 'gamma': 3.490944592554028, 'reg_alpha': 1e-06, 'reg_lambda': 10.0, 'early_stopping_rounds': 29}

[INFO 02-26 21:09:58] ax.service.ax_client: Completed trial 46 with data: {'avg_rmse_nonzero': (0.370336, 0.027143)}.
[INFO 02-26 21:09:58] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Result: Non-zero RMSE = 0.3703
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 48/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 100, 'max_depth': 100, 'learning_rate': 0.29999999999999993, 'subsample': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 20, 'gamma': 5.0, 'reg_alpha': 0.5173256440253642, 'reg_lambda': 1e-06, 'early_stopping_rounds': 11}

[INFO 02-26 21:33:48] ax.service.ax_client: Completed trial 47 with data: {'avg_rmse_nonzero': (0.381313, 0.031794)}.
[INFO 02-26 21:33:49] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Result: Non-zero RMSE = 0.3813
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 49/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 229, 'max_depth': 39, 'learning_rate': 0.005, 'subsample': 0.6595185159669966, 'colsample_bytree': 0.3049681950538426, 'min_child_weight': 13, 'gamma': 3.8423256415585487, 'reg_alpha': 1.7962454769523097e-05, 'reg_lambda': 0.02385828195698211, 'early_stopping_rounds': 44}

[INFO 02-26 22:12:20] ax.service.ax_client: Completed trial 48 with data: {'avg_rmse_nonzero': (0.380684, 0.024674)}.
[INFO 02-26 22:12:20] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Result: Non-zero RMSE = 0.3807
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 50/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 1098, 'max_depth': 77, 'learning_rate': 0.29999999999999993, 'subsample': 0.5, 'colsample_bytree': 0.4226368640165297, 'min_child_weight': 20, 'gamma': 3.195549935258008, 'reg_alpha': 0.021649085580097246, 'reg_lambda': 1e-06, 'early_stopping_rounds': 25}

[INFO 02-26 22:43:58] ax.service.ax_client: Completed trial 49 with data: {'avg_rmse_nonzero': (0.399849, 0.026354)}.
[INFO 02-26 22:43:58] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Result: Non-zero RMSE = 0.3998
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 51/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 1371, 'max_depth': 85, 'learning_rate': 0.005, 'subsample': 1.0, 'colsample_bytree': 0.429044307732192, 'min_child_weight': 10, 'gamma': 2.1261930302098704, 'reg_alpha': 1e-06, 'reg_lambda': 1e-06, 'early_stopping_rounds': 10}

[INFO 02-26 23:10:26] ax.service.ax_client: Completed trial 50 with data: {'avg_rmse_nonzero': (0.365427, 0.028961)}.
[INFO 02-26 23:10:26] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Result: Non-zero RMSE = 0.3654
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 52/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 4304, 'max_depth': 100, 'learning_rate': 0.005, 'subsample': 1.0, 'colsample_bytree': 0.9082640052770817, 'min_child_weight': 17, 'gamma': 5.0, 'reg_alpha': 5.31908546116142e-05, 'reg_lambda': 10.0, 'early_stopping_rounds': 10}

[INFO 02-26 23:37:20] ax.service.ax_client: Completed trial 51 with data: {'avg_rmse_nonzero': (0.372757, 0.032658)}.
[INFO 02-26 23:37:20] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Result: Non-zero RMSE = 0.3728
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 53/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 832, 'max_depth': 95, 'learning_rate': 0.005, 'subsample': 0.8281153186657728, 'colsample_bytree': 0.4892782746308333, 'min_child_weight': 4, 'gamma': 4.106934552940222, 'reg_alpha': 0.21241910510832177, 'reg_lambda': 9.049519253178264, 'early_stopping_rounds': 10}

[INFO 02-27 00:03:24] ax.service.ax_client: Completed trial 52 with data: {'avg_rmse_nonzero': (0.367772, 0.028771)}.

Result: Non-zero RMSE = 0.3678

[INFO 02-27 00:03:24] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 54/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 2050, 'max_depth': 100, 'learning_rate': 0.005, 'subsample': 0.648065685353506, 'colsample_bytree': 0.3, 'min_child_weight': 20, 'gamma': 2.2515483023902294, 'reg_alpha': 0.3047648418721599, 'reg_lambda': 0.7866813701018653, 'early_stopping_rounds': 39}

[INFO 02-27 00:43:25] ax.service.ax_client: Completed trial 53 with data: {'avg_rmse_nonzero': (0.368122, 0.026448)}.
[INFO 02-27 00:43:25] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Result: Non-zero RMSE = 0.3681
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 55/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 4432, 'max_depth': 40, 'learning_rate': 0.008320212803813402, 'subsample': 1.0, 'colsample_bytree': 0.3, 'min_child_weight': 1, 'gamma': 5.0, 'reg_alpha': 0.0010349816699783783, 'reg_lambda': 10.0, 'early_stopping_rounds': 10}

[INFO 02-27 01:08:12] ax.service.ax_client: Completed trial 54 with data: {'avg_rmse_nonzero': (0.370588, 0.02756)}.
[INFO 02-27 01:08:12] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Result: Non-zero RMSE = 0.3706
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 56/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 4641, 'max_depth': 100, 'learning_rate': 0.005, 'subsample': 0.8791030634270168, 'colsample_bytree': 0.3, 'min_child_weight': 1, 'gamma': 1.0989789141649826, 'reg_alpha': 1e-06, 'reg_lambda': 1e-06, 'early_stopping_rounds': 44}

[INFO 02-27 01:54:59] ax.service.ax_client: Completed trial 55 with data: {'avg_rmse_nonzero': (0.368838, 0.026325)}.
[INFO 02-27 01:54:59] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Result: Non-zero RMSE = 0.3688
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 57/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 2074, 'max_depth': 33, 'learning_rate': 0.12497043490902751, 'subsample': 0.7836733419386599, 'colsample_bytree': 0.8550943599640156, 'min_child_weight': 1, 'gamma': 4.197741074854019, 'reg_alpha': 6.861139904969712e-06, 'reg_lambda': 2.2522834028504838e-05, 'early_stopping_rounds': 10}

[INFO 02-27 02:18:55] ax.service.ax_client: Completed trial 56 with data: {'avg_rmse_nonzero': (0.376422, 0.032379)}.
[INFO 02-27 02:18:55] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Result: Non-zero RMSE = 0.3764
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 58/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 2966, 'max_depth': 89, 'learning_rate': 0.008358664709735866, 'subsample': 0.5873579887727512, 'colsample_bytree': 0.6510705682042908, 'min_child_weight': 1, 'gamma': 2.7641410318916875, 'reg_alpha': 10.0, 'reg_lambda': 0.14240985970865686, 'early_stopping_rounds': 12}

[INFO 02-27 02:44:02] ax.service.ax_client: Completed trial 57 with data: {'avg_rmse_nonzero': (0.374249, 0.030447)}.
[INFO 02-27 02:44:02] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Result: Non-zero RMSE = 0.3742
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 59/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 2405, 'max_depth': 100, 'learning_rate': 0.07387246654608746, 'subsample': 1.0, 'colsample_bytree': 0.872418559363128, 'min_child_weight': 20, 'gamma': 3.954939419435996, 'reg_alpha': 0.43324613109968685, 'reg_lambda': 10.0, 'early_stopping_rounds': 20}

[INFO 02-27 03:10:38] ax.service.ax_client: Completed trial 58 with data: {'avg_rmse_nonzero': (0.37648, 0.032137)}.
[INFO 02-27 03:10:38] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Result: Non-zero RMSE = 0.3765
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 60/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 518, 'max_depth': 100, 'learning_rate': 0.005, 'subsample': 1.0, 'colsample_bytree': 0.3, 'min_child_weight': 16, 'gamma': 0.32966998310071527, 'reg_alpha': 10.0, 'reg_lambda': 10.0, 'early_stopping_rounds': 17}

[INFO 02-27 03:44:10] ax.service.ax_client: Completed trial 59 with data: {'avg_rmse_nonzero': (0.376951, 0.026791)}.
[INFO 02-27 03:44:10] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Result: Non-zero RMSE = 0.3770
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 61/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 4907, 'max_depth': 100, 'learning_rate': 0.007604947839951523, 'subsample': 0.5, 'colsample_bytree': 0.8853439491633044, 'min_child_weight': 6, 'gamma': 3.4545115815814778, 'reg_alpha': 0.010682040895367737, 'reg_lambda': 10.0, 'early_stopping_rounds': 50}

[INFO 02-27 04:24:14] ax.service.ax_client: Completed trial 60 with data: {'avg_rmse_nonzero': (0.371904, 0.030159)}.
[INFO 02-27 04:24:14] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Result: Non-zero RMSE = 0.3719
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 62/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 4962, 'max_depth': 57, 'learning_rate': 0.22895122684689975, 'subsample': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 1, 'gamma': 0.10000147144802425, 'reg_alpha': 0.0011978881799104607, 'reg_lambda': 0.003597197149327476, 'early_stopping_rounds': 10}

[INFO 02-27 04:52:20] ax.service.ax_client: Completed trial 61 with data: {'avg_rmse_nonzero': (0.386441, 0.040386)}.
[INFO 02-27 04:52:20] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Result: Non-zero RMSE = 0.3864
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 63/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 4705, 'max_depth': 30, 'learning_rate': 0.01229845060046182, 'subsample': 0.7787288355167789, 'colsample_bytree': 0.56432171250942, 'min_child_weight': 20, 'gamma': 0.0, 'reg_alpha': 2.271245996549964, 'reg_lambda': 1e-06, 'early_stopping_rounds': 50}

[INFO 02-27 07:56:42] ax.service.ax_client: Completed trial 62 with data: {'avg_rmse_nonzero': (0.364935, 0.027724)}.
[INFO 02-27 07:56:42] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Result: Non-zero RMSE = 0.3649
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 64/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 587, 'max_depth': 100, 'learning_rate': 0.005, 'subsample': 0.8128243475829631, 'colsample_bytree': 0.9836172112730167, 'min_child_weight': 1, 'gamma': 5.0, 'reg_alpha': 1e-06, 'reg_lambda': 10.0, 'early_stopping_rounds': 20}

[INFO 02-27 08:28:31] ax.service.ax_client: Completed trial 63 with data: {'avg_rmse_nonzero': (0.37304, 0.031927)}.

Result: Non-zero RMSE = 0.3730

[INFO 02-27 08:28:31] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 65/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 4345, 'max_depth': 100, 'learning_rate': 0.005, 'subsample': 0.854030361027809, 'colsample_bytree': 0.743606473641392, 'min_child_weight': 11, 'gamma': 5.0, 'reg_alpha': 1e-06, 'reg_lambda': 1e-06, 'early_stopping_rounds': 50}

[INFO 02-27 09:12:00] ax.service.ax_client: Completed trial 64 with data: {'avg_rmse_nonzero': (0.369479, 0.030779)}.
[INFO 02-27 09:12:00] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Result: Non-zero RMSE = 0.3695
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 66/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 4234, 'max_depth': 49, 'learning_rate': 0.04459622288694521, 'subsample': 0.5, 'colsample_bytree': 0.5437705657397573, 'min_child_weight': 1, 'gamma': 0.0, 'reg_alpha': 1e-06, 'reg_lambda': 0.01123376600696019, 'early_stopping_rounds': 10}

[INFO 02-27 10:05:39] ax.service.ax_client: Completed trial 65 with data: {'avg_rmse_nonzero': (0.377039, 0.026304)}.
[INFO 02-27 10:05:39] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Result: Non-zero RMSE = 0.3770
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 67/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 2587, 'max_depth': 100, 'learning_rate': 0.005, 'subsample': 0.5, 'colsample_bytree': 0.3, 'min_child_weight': 20, 'gamma': 4.881284834200976, 'reg_alpha': 0.03523899219528604, 'reg_lambda': 3.283100380821587e-06, 'early_stopping_rounds': 15}

[INFO 02-27 10:26:10] ax.service.ax_client: Completed trial 66 with data: {'avg_rmse_nonzero': (0.370749, 0.026704)}.
[INFO 02-27 10:26:10] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Result: Non-zero RMSE = 0.3707
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 68/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 4578, 'max_depth': 100, 'learning_rate': 0.005, 'subsample': 0.5, 'colsample_bytree': 0.573106665092867, 'min_child_weight': 15, 'gamma': 1.1200703413939146, 'reg_alpha': 1e-06, 'reg_lambda': 2.663303888147666e-06, 'early_stopping_rounds': 26}

[INFO 02-27 10:51:41] ax.service.ax_client: Completed trial 67 with data: {'avg_rmse_nonzero': (0.366917, 0.028021)}.
[INFO 02-27 10:51:41] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Result: Non-zero RMSE = 0.3669
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 69/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 4932, 'max_depth': 31, 'learning_rate': 0.008969339787657874, 'subsample': 0.5, 'colsample_bytree': 0.4816338338327073, 'min_child_weight': 1, 'gamma': 2.169808903453712, 'reg_alpha': 1e-06, 'reg_lambda': 10.0, 'early_stopping_rounds': 50}

[INFO 02-27 11:20:30] ax.service.ax_client: Completed trial 68 with data: {'avg_rmse_nonzero': (0.368919, 0.028075)}.
[INFO 02-27 11:20:30] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Result: Non-zero RMSE = 0.3689
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 70/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 2028, 'max_depth': 5, 'learning_rate': 0.29999999999999993, 'subsample': 0.5, 'colsample_bytree': 0.9734407290450859, 'min_child_weight': 16, 'gamma': 5.0, 'reg_alpha': 3.599797513784131e-06, 'reg_lambda': 10.0, 'early_stopping_rounds': 50}

[INFO 02-27 11:59:51] ax.service.ax_client: Completed trial 69 with data: {'avg_rmse_nonzero': (0.379871, 0.026363)}.
[INFO 02-27 11:59:51] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Result: Non-zero RMSE = 0.3799
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 71/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 604, 'max_depth': 91, 'learning_rate': 0.07898579369892021, 'subsample': 1.0, 'colsample_bytree': 0.3, 'min_child_weight': 1, 'gamma': 4.225638929172904, 'reg_alpha': 1.1648090255363638e-06, 'reg_lambda': 1e-06, 'early_stopping_rounds': 16}

[INFO 02-27 12:23:05] ax.service.ax_client: Completed trial 70 with data: {'avg_rmse_nonzero': (0.376852, 0.024084)}.
[INFO 02-27 12:23:05] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Result: Non-zero RMSE = 0.3769
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 72/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 2841, 'max_depth': 50, 'learning_rate': 0.24162048091346644, 'subsample': 1.0, 'colsample_bytree': 0.549038470393725, 'min_child_weight': 20, 'gamma': 0.0, 'reg_alpha': 8.029570250513467e-05, 'reg_lambda': 0.5633429059234455, 'early_stopping_rounds': 10}

[INFO 02-27 13:08:09] ax.service.ax_client: Completed trial 71 with data: {'avg_rmse_nonzero': (0.386822, 0.035652)}.
[INFO 02-27 13:08:09] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Result: Non-zero RMSE = 0.3868
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 73/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 2380, 'max_depth': 98, 'learning_rate': 0.0601195215670519, 'subsample': 0.9593237318553611, 'colsample_bytree': 1.0, 'min_child_weight': 1, 'gamma': 0.0, 'reg_alpha': 0.02241229715882542, 'reg_lambda': 0.24520320787793665, 'early_stopping_rounds': 50}

[INFO 02-27 14:25:53] ax.service.ax_client: Completed trial 72 with data: {'avg_rmse_nonzero': (0.430429, 0.037698)}.
[INFO 02-27 14:25:53] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Result: Non-zero RMSE = 0.4304
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 74/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 644, 'max_depth': 100, 'learning_rate': 0.005, 'subsample': 0.6629385147895408, 'colsample_bytree': 0.3, 'min_child_weight': 1, 'gamma': 0.0, 'reg_alpha': 0.0009216471412562038, 'reg_lambda': 10.0, 'early_stopping_rounds': 10}

[INFO 02-27 16:36:24] ax.service.ax_client: Completed trial 73 with data: {'avg_rmse_nonzero': (0.372632, 0.024476)}.
[INFO 02-27 16:36:24] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Result: Non-zero RMSE = 0.3726
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 75/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 4400, 'max_depth': 36, 'learning_rate': 0.005, 'subsample': 0.7938758732419664, 'colsample_bytree': 0.37878315865193823, 'min_child_weight': 14, 'gamma': 5.0, 'reg_alpha': 1e-06, 'reg_lambda': 1.8020245632832546e-05, 'early_stopping_rounds': 50}

[INFO 02-27 17:20:17] ax.service.ax_client: Completed trial 74 with data: {'avg_rmse_nonzero': (0.367999, 0.027524)}.
[INFO 02-27 17:20:17] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Result: Non-zero RMSE = 0.3680
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 76/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 4381, 'max_depth': 6, 'learning_rate': 0.005, 'subsample': 0.8859843211345548, 'colsample_bytree': 0.3, 'min_child_weight': 9, 'gamma': 2.672895078238274, 'reg_alpha': 0.014592608264805023, 'reg_lambda': 1e-06, 'early_stopping_rounds': 50}

[INFO 02-27 18:07:02] ax.service.ax_client: Completed trial 75 with data: {'avg_rmse_nonzero': (0.371061, 0.022615)}.

Result: Non-zero RMSE = 0.3711

[INFO 02-27 18:07:02] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 77/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 4794, 'max_depth': 94, 'learning_rate': 0.005, 'subsample': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 9, 'gamma': 4.580491145630538, 'reg_alpha': 10.0, 'reg_lambda': 1e-06, 'early_stopping_rounds': 50}

[INFO 02-27 18:45:31] ax.service.ax_client: Completed trial 76 with data: {'avg_rmse_nonzero': (0.376423, 0.030905)}.

Result: Non-zero RMSE = 0.3764

[INFO 02-27 18:45:31] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 78/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 4984, 'max_depth': 27, 'learning_rate': 0.010312485217326627, 'subsample': 1.0, 'colsample_bytree': 0.3, 'min_child_weight': 20, 'gamma': 5.0, 'reg_alpha': 1e-06, 'reg_lambda': 4.057389292257426, 'early_stopping_rounds': 50}

[INFO 02-27 19:23:55] ax.service.ax_client: Completed trial 77 with data: {'avg_rmse_nonzero': (0.370012, 0.027064)}.
[INFO 02-27 19:23:55] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Result: Non-zero RMSE = 0.3700
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 79/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 3865, 'max_depth': 4, 'learning_rate': 0.0059559285224442, 'subsample': 0.5, 'colsample_bytree': 0.8124466743617053, 'min_child_weight': 5, 'gamma': 4.555984772904254, 'reg_alpha': 10.0, 'reg_lambda': 10.0, 'early_stopping_rounds': 50}

[INFO 02-27 20:04:58] ax.service.ax_client: Completed trial 78 with data: {'avg_rmse_nonzero': (0.375656, 0.0273)}.

Result: Non-zero RMSE = 0.3757

[INFO 02-27 20:04:58] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 80/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 2019, 'max_depth': 25, 'learning_rate': 0.005739096806093243, 'subsample': 1.0, 'colsample_bytree': 0.3, 'min_child_weight': 11, 'gamma': 0.7084185840026652, 'reg_alpha': 1e-06, 'reg_lambda': 1e-06, 'early_stopping_rounds': 50}

[INFO 02-27 20:56:17] ax.service.ax_client: Completed trial 79 with data: {'avg_rmse_nonzero': (0.367202, 0.027162)}.
[INFO 02-27 20:56:17] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Result: Non-zero RMSE = 0.3672
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 81/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-27 20:56:35] ax.modelbridge.base: Untransformed parameter 0.004999999999999999 less than lower bound 0.005, clamping
[INFO 02-27 20:56:37] ax.service.ax_client: Generated new trial 80 with parameters {'n_estimators': 1147, 'max_depth': 74, 'learning_rate': 0.280473, 'subsample': 0.5, 'colsample_bytree': 0.3, 'min_child_weight': 1, 'gamma': 0.0, 'reg_alpha': 1e-06, 'reg_lambda': 1.2e-05, 'early_stopping_rounds': 10} using model BoTorch.

Parameters: {'n_estimators': 1147, 'max_depth': 74, 'learning_rate': 0.28047343363016874, 'subsample': 0.5, 'colsample_bytree': 0.3, 'min_child_weight': 1, 'gamma': 0.0, 'reg_alpha': 1e-06, 'reg_lambda': 1.1869883002724596e-05, 'early_stopping_rounds': 10}

[INFO 02-27 21:40:30] ax.service.ax_client: Completed trial 80 with data: {'avg_rmse_nonzero': (0.399561, 0.020461)}.
[INFO 02-27 21:40:30] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Result: Non-zero RMSE = 0.3996
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 82/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 3748, 'max_depth': 100, 'learning_rate': 0.0071596728088329075, 'subsample': 0.9922652686389651, 'colsample_bytree': 0.775649232682074, 'min_child_weight': 17, 'gamma': 5.0, 'reg_alpha': 10.0, 'reg_lambda': 1e-06, 'early_stopping_rounds': 10}

[INFO 02-27 22:15:09] ax.service.ax_client: Completed trial 81 with data: {'avg_rmse_nonzero': (0.37344, 0.030454)}.

Result: Non-zero RMSE = 0.3734

[INFO 02-27 22:15:09] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 83/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 4311, 'max_depth': 15, 'learning_rate': 0.01042186965900956, 'subsample': 1.0, 'colsample_bytree': 0.8348892040189764, 'min_child_weight': 5, 'gamma': 5.0, 'reg_alpha': 1e-06, 'reg_lambda': 10.0, 'early_stopping_rounds': 28}

[INFO 02-27 22:51:30] ax.service.ax_client: Completed trial 82 with data: {'avg_rmse_nonzero': (0.370947, 0.031141)}.
[INFO 02-27 22:51:30] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Result: Non-zero RMSE = 0.3709
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 84/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-27 22:51:44] ax.modelbridge.base: Untransformed parameter 0.004999999999999999 less than lower bound 0.005, clamping
[INFO 02-27 22:51:46] ax.service.ax_client: Generated new trial 83 with parameters {'n_estimators': 4645, 'max_depth': 42, 'learning_rate': 0.0064, 'subsample': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 13, 'gamma': 0.0, 'reg_alpha': 1e-06, 'reg_lambda': 1e-06, 'early_stopping_rounds': 50} using model BoTorch.

Parameters: {'n_estimators': 4645, 'max_depth': 42, 'learning_rate': 0.006399672183595166, 'subsample': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 13, 'gamma': 0.0, 'reg_alpha': 1e-06, 'reg_lambda': 1e-06, 'early_stopping_rounds': 50}

[INFO 02-28 03:38:07] ax.service.ax_client: Completed trial 83 with data: {'avg_rmse_nonzero': (0.36824, 0.029711)}.

Result: Non-zero RMSE = 0.3682

[INFO 02-28 03:38:07] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 85/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 4846, 'max_depth': 24, 'learning_rate': 0.005, 'subsample': 0.9921188248548071, 'colsample_bytree': 0.3, 'min_child_weight': 1, 'gamma': 1.1350700951519919, 'reg_alpha': 1e-06, 'reg_lambda': 0.019485410126140492, 'early_stopping_rounds': 50}

[INFO 02-28 04:22:23] ax.service.ax_client: Completed trial 84 with data: {'avg_rmse_nonzero': (0.36911, 0.02656)}.
[INFO 02-28 04:22:23] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Result: Non-zero RMSE = 0.3691
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 86/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 3710, 'max_depth': 100, 'learning_rate': 0.1903292946300542, 'subsample': 0.9988931152672865, 'colsample_bytree': 0.3, 'min_child_weight': 20, 'gamma': 5.0, 'reg_alpha': 2.8965201490395724e-06, 'reg_lambda': 0.5138198978119933, 'early_stopping_rounds': 50}

[INFO 02-28 04:59:50] ax.service.ax_client: Completed trial 85 with data: {'avg_rmse_nonzero': (0.38295, 0.021984)}.
[INFO 02-28 04:59:50] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Result: Non-zero RMSE = 0.3830
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 87/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 2827, 'max_depth': 100, 'learning_rate': 0.005, 'subsample': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 20, 'gamma': 5.0, 'reg_alpha': 1e-06, 'reg_lambda': 1e-06, 'early_stopping_rounds': 40}

[INFO 02-28 05:35:16] ax.service.ax_client: Completed trial 86 with data: {'avg_rmse_nonzero': (0.370804, 0.029555)}.
[INFO 02-28 05:35:16] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Result: Non-zero RMSE = 0.3708
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 88/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 868, 'max_depth': 26, 'learning_rate': 0.005, 'subsample': 0.5731115537380106, 'colsample_bytree': 0.3, 'min_child_weight': 9, 'gamma': 4.615454944780977, 'reg_alpha': 10.0, 'reg_lambda': 1e-06, 'early_stopping_rounds': 50}

[INFO 02-28 06:12:34] ax.service.ax_client: Completed trial 87 with data: {'avg_rmse_nonzero': (0.37392, 0.028105)}.
[INFO 02-28 06:12:34] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Result: Non-zero RMSE = 0.3739
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 89/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 5000, 'max_depth': 81, 'learning_rate': 0.005, 'subsample': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 1, 'gamma': 0.0, 'reg_alpha': 1e-06, 'reg_lambda': 1e-06, 'early_stopping_rounds': 10}

[INFO 02-28 10:37:24] ax.service.ax_client: Completed trial 88 with data: {'avg_rmse_nonzero': (0.389268, 0.038091)}.
[INFO 02-28 10:37:24] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Result: Non-zero RMSE = 0.3893
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 90/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 4529, 'max_depth': 85, 'learning_rate': 0.005, 'subsample': 0.5, 'colsample_bytree': 0.3, 'min_child_weight': 16, 'gamma': 0.0, 'reg_alpha': 2.2856341343345186, 'reg_lambda': 0.66622229114204, 'early_stopping_rounds': 50}

[INFO 02-28 14:47:26] ax.service.ax_client: Completed trial 89 with data: {'avg_rmse_nonzero': (0.364299, 0.022197)}.
[INFO 02-28 14:47:26] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Result: Non-zero RMSE = 0.3643
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 91/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 100, 'max_depth': 100, 'learning_rate': 0.005, 'subsample': 0.8243817533304675, 'colsample_bytree': 0.3, 'min_child_weight': 4, 'gamma': 5.0, 'reg_alpha': 10.0, 'reg_lambda': 1e-06, 'early_stopping_rounds': 50}

[INFO 02-28 15:25:48] ax.service.ax_client: Completed trial 90 with data: {'avg_rmse_nonzero': (0.402872, 0.025113)}.
[INFO 02-28 15:25:48] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Result: Non-zero RMSE = 0.4029
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 92/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 4938, 'max_depth': 100, 'learning_rate': 0.005, 'subsample': 1.0, 'colsample_bytree': 0.3, 'min_child_weight': 20, 'gamma': 1.3196102011491464, 'reg_alpha': 1.7715054650863163e-05, 'reg_lambda': 10.0, 'early_stopping_rounds': 50}

[INFO 02-28 16:10:36] ax.service.ax_client: Completed trial 91 with data: {'avg_rmse_nonzero': (0.369027, 0.026833)}.
[INFO 02-28 16:10:36] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Result: Non-zero RMSE = 0.3690
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 93/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 100, 'max_depth': 3, 'learning_rate': 0.29999999999999993, 'subsample': 1.0, 'colsample_bytree': 0.3, 'min_child_weight': 3, 'gamma': 5.0, 'reg_alpha': 10.0, 'reg_lambda': 1.6818071722038185e-06, 'early_stopping_rounds': 10}

[INFO 02-28 16:34:13] ax.service.ax_client: Completed trial 92 with data: {'avg_rmse_nonzero': (0.378428, 0.016291)}.
[INFO 02-28 16:34:13] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Result: Non-zero RMSE = 0.3784
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 94/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 4905, 'max_depth': 12, 'learning_rate': 0.005, 'subsample': 0.6557127563817774, 'colsample_bytree': 0.9235961506683497, 'min_child_weight': 20, 'gamma': 2.053977769770046, 'reg_alpha': 1e-06, 'reg_lambda': 10.0, 'early_stopping_rounds': 12}

[INFO 02-28 17:02:13] ax.service.ax_client: Completed trial 93 with data: {'avg_rmse_nonzero': (0.369318, 0.030041)}.
[INFO 02-28 17:02:13] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Result: Non-zero RMSE = 0.3693
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 95/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 02-28 17:02:30] ax.modelbridge.base: Untransformed parameter 0.004999999999999999 less than lower bound 0.005, clamping
[INFO 02-28 17:02:31] ax.service.ax_client: Generated new trial 94 with parameters {'n_estimators': 4239, 'max_depth': 100, 'learning_rate': 0.007249, 'subsample': 0.5, 'colsample_bytree': 0.3, 'min_child_weight': 1, 'gamma': 0.0, 'reg_alpha': 10.0, 'reg_lambda': 10.0, 'early_stopping_rounds': 50} using model BoTorch.

Parameters: {'n_estimators': 4239, 'max_depth': 100, 'learning_rate': 0.007248878189289887, 'subsample': 0.5, 'colsample_bytree': 0.3, 'min_child_weight': 1, 'gamma': 0.0, 'reg_alpha': 10.0, 'reg_lambda': 10.0, 'early_stopping_rounds': 50}

[INFO 02-28 19:11:22] ax.service.ax_client: Completed trial 94 with data: {'avg_rmse_nonzero': (0.381715, 0.023243)}.

Result: Non-zero RMSE = 0.3817

[INFO 02-28 19:11:22] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 96/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 4883, 'max_depth': 100, 'learning_rate': 0.03163293031011935, 'subsample': 0.5549861222846088, 'colsample_bytree': 1.0, 'min_child_weight': 1, 'gamma': 5.0, 'reg_alpha': 10.0, 'reg_lambda': 3.2423726572376566e-06, 'early_stopping_rounds': 14}

[INFO 02-28 19:48:27] ax.service.ax_client: Completed trial 95 with data: {'avg_rmse_nonzero': (0.377956, 0.030699)}.

Result: Non-zero RMSE = 0.3780

[INFO 02-28 19:48:27] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 97/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 313, 'max_depth': 45, 'learning_rate': 0.005, 'subsample': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 10, 'gamma': 5.0, 'reg_alpha': 1e-06, 'reg_lambda': 1e-06, 'early_stopping_rounds': 22}

[INFO 02-28 20:30:05] ax.service.ax_client: Completed trial 96 with data: {'avg_rmse_nonzero': (0.372792, 0.030596)}.

Result: Non-zero RMSE = 0.3728

[INFO 02-28 20:30:05] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 98/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 594, 'max_depth': 3, 'learning_rate': 0.29999999999999993, 'subsample': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 1, 'gamma': 5.0, 'reg_alpha': 1e-06, 'reg_lambda': 9.472359344502173, 'early_stopping_rounds': 10}

[INFO 02-28 21:01:02] ax.service.ax_client: Completed trial 97 with data: {'avg_rmse_nonzero': (0.386263, 0.020238)}.
[INFO 02-28 21:01:03] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Result: Non-zero RMSE = 0.3863
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 99/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 5000, 'max_depth': 4, 'learning_rate': 0.005, 'subsample': 1.0, 'colsample_bytree': 0.6802311743028266, 'min_child_weight': 20, 'gamma': 0.0, 'reg_alpha': 1e-06, 'reg_lambda': 10.0, 'early_stopping_rounds': 10}

[INFO 02-28 23:53:06] ax.service.ax_client: Completed trial 98 with data: {'avg_rmse_nonzero': (0.378758, 0.02658)}.
[INFO 02-28 23:53:06] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Result: Non-zero RMSE = 0.3788
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
Trial 100/100
============================================================

c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 4056, 'max_depth': 21, 'learning_rate': 0.016676076252937135, 'subsample': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 8, 'gamma': 0.0, 'reg_alpha': 2.5739854966974115e-05, 'reg_lambda': 1e-06, 'early_stopping_rounds': 10}

[INFO 03-01 01:20:02] ax.service.ax_client: Completed trial 99 with data: {'avg_rmse_nonzero': (0.397241, 0.041343)}.
[INFO 03-01 01:20:02] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json`.

Result: Non-zero RMSE = 0.3972
Checkpoint saved to c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_NF_fT_checkpoint.json

============================================================
OPTIMIZATION COMPLETE — XGBoost Phase Fractions NF f(T)
============================================================
Best parameters: {'n_estimators': 4529, 'max_depth': 85, 'learning_rate': 0.005, 'subsample': 0.5, 'colsample_bytree': 0.3, 'min_child_weight': 16, 'gamma': 0.0, 'reg_alpha': 2.2856341343345186, 'reg_lambda': 0.66622229114204, 'early_stopping_rounds': 50}
Best Non-zero RMSE: 0.3643

In [ ]:
ax_client_xgb_nf = AxClient.load_from_json_file(r"Ax_checkpoints/ax_client_XGB_NF(T)_checkpoint.json")
best_parameters_xgb_nf, values_xgb_nf = ax_client_xgb_nf.get_best_parameters()
print(f"\n{'='*60}")
print("OPTIMIZATION COMPLETE — XGBoost Phase Fractions NF f(T)")
print('='*60)
print(f"Best parameters: {best_parameters_xgb_nf}")
print(f"Best Non-zero RMSE: {values_xgb_nf[0]['avg_rmse_nonzero']:.4f}")

[INFO 03-06 11:32:37] ax.service.ax_client: Starting optimization with verbose logging. To disable logging, set the `verbose_logging` argument to `False`. Note that float values in the logs are rounded to 6 decimal points.

KeyboardInterrupt:

In [ ]:
# =====================================================================
# XGBoost Evaluation & Bayesian Optimization for Driving Force XGB (DF)
# =====================================================================

def evaluate_parameters_XGB_DF_FT(parameters, verbose=True):
    """
    Evaluate XGBoost hyperparameters for predicting driving force (DF)
    using 5-fold KMeans-based cross-validation (same splits as NN evaluation).

    Parameters:
    -----------
    parameters : dict
        XGBoost hyperparameters including:
        - n_estimators, max_depth, learning_rate, subsample,
          colsample_bytree, min_child_weight, gamma,
          reg_alpha, reg_lambda, early_stopping_rounds
    verbose : bool
        Whether to print progress

    Returns:
    --------
    dict : Results including fold-level and average metrics
    """
    # Extract hyperparameters with defaults
    n_estimators = parameters.get('n_estimators', 500)
    max_depth = parameters.get('max_depth', 6)
    learning_rate = parameters.get('learning_rate', 0.1)
    subsample = parameters.get('subsample', 0.8)
    colsample_bytree = parameters.get('colsample_bytree', 0.8)
    min_child_weight = parameters.get('min_child_weight', 1)
    gamma = parameters.get('gamma', 0.0)
    reg_alpha = parameters.get('reg_alpha', 0.0)
    reg_lambda = parameters.get('reg_lambda', 1.0)
    early_stopping_rounds = parameters.get('early_stopping_rounds', 20)


    # Copy the x and y data — use driving force targets
    y_data = y_df.copy()
    x_data = X_combined.copy()

    # Get dimensions
    input_dim = x_data.shape[1]
    output_dim = y_data.shape[1]
    if verbose:
        print(f"Input dim: {input_dim}, Output dim: {output_dim}")

    # Store results for each fold
    fold_results = []
    all_test_predictions = []
    all_test_targets = []

    for test_group in range(5):
        if verbose:
            print(f"\n{'='*50}")
            print(f"Fold {test_group}")
            print('='*50)

        # Get the split indexes for training and testing
        train_idx = cv_group_df['cv_group'] != test_group
        test_idx = cv_group_df['cv_group'] == test_group

        # Split the x and y data into train and test
        x_train = x_data.loc[train_idx]
        x_test = x_data.loc[test_idx]
        y_train = y_data.loc[train_idx]
        y_test = y_data.loc[test_idx]

        # Create train and validation split
        X_train, X_val, y_train_split, y_val = train_test_split(
            x_train, y_train, test_size=0.2, random_state=42
        )

        if verbose:
            print(f"Train: {len(X_train)}, Val: {len(X_val)}, Test: {len(x_test)}")

        # Train one XGBRegressor per output column (manual multi-output)
        # This ensures proper GPU usage — native multi-output doesn't fully support GPU
        estimators = []
        best_iters = []
        output_cols = y_train_split.columns.tolist()

        for col_idx, col_name in enumerate(output_cols):
            xgb_model = XGBRegressor(
                n_estimators=n_estimators,
                max_depth=max_depth,
                learning_rate=learning_rate,
                subsample=subsample,
                colsample_bytree=colsample_bytree,
                min_child_weight=min_child_weight,
                gamma=gamma,
                reg_alpha=reg_alpha,
                reg_lambda=reg_lambda,
                tree_method='hist',
                device='cuda',
                random_state=42,
                n_jobs=-1,
                verbosity=0,
                early_stopping_rounds=early_stopping_rounds,
                eval_metric='rmse',
            )

            xgb_model.fit(
                X_train, y_train_split[col_name],
                eval_set=[(X_val, y_val[col_name])],
                verbose=False,
            )

            estimators.append(xgb_model)
            best_iters.append(xgb_model.best_iteration)

        if verbose:
            print(f"Best iterations (min/mean/max): {min(best_iters)}/{np.mean(best_iters):.0f}/{max(best_iters)}")

        # Predict on test set (stack individual predictions)
        test_preds = np.column_stack([
            est.predict(x_test) for est in estimators
        ])
        test_targets = y_test.values

        # Get column names for DF columns
        col_names = y_data.columns.tolist()
        df_col_idxs = [i for i, col in enumerate(col_names) if col.startswith('DF_')]

        # Calculate overall RMSE and MAE (all values)
        mse_original = np.mean((test_preds - test_targets) ** 2)
        rmse = np.sqrt(mse_original)
        mae = np.mean(np.abs(test_preds - test_targets))

        # Calculate metrics for non-zero targets only
        nonzero_threshold = 1e-6

        nonzero_mask = np.abs(test_targets) > nonzero_threshold
        if np.any(nonzero_mask):
            nonzero_errors = test_preds[nonzero_mask] - test_targets[nonzero_mask]
            rmse_nonzero = np.sqrt(np.mean(nonzero_errors ** 2))
            mae_nonzero = np.mean(np.abs(nonzero_errors))
            n_nonzero = np.sum(nonzero_mask)
        else:
            rmse_nonzero, mae_nonzero, n_nonzero = 0.0, 0.0, 0

        # Driving Force (DF) specific metrics — non-zero only
        if df_col_idxs:
            df_preds = test_preds[:, df_col_idxs]
            df_targets = test_targets[:, df_col_idxs]
            df_nonzero_mask = np.abs(df_targets) > nonzero_threshold
            if np.any(df_nonzero_mask):
                df_errors = df_preds[df_nonzero_mask] - df_targets[df_nonzero_mask]
                nf_rmse = np.sqrt(np.mean(df_errors ** 2))
                nf_mae = np.mean(np.abs(df_errors))
                n_nf_nonzero = np.sum(df_nonzero_mask)
            else:
                nf_rmse, nf_mae, n_nf_nonzero = 0.0, 0.0, 0
        else:
            nf_rmse, nf_mae, n_nf_nonzero = 0.0, 0.0, 0

        if verbose:
            print(f"Overall (all)      - RMSE: {rmse:.4f}, MAE: {mae:.4f}")
            print(f"Overall (non-zero) - RMSE: {rmse_nonzero:.4f}, MAE: {mae_nonzero:.4f}  [{n_nonzero:,} values]")
            print(f"Phase Fraction (NF) - RMSE: {nf_rmse:.4f}, MAE: {nf_mae:.4f}  [{n_nf_nonzero:,} non-zero values]")

        # Store fold results
        fold_results.append({
            'fold': test_group,
            'test_loss': mse_original,
            'test_rmse': rmse,
            'test_mae': mae,
            'rmse_nonzero': rmse_nonzero,
            'mae_nonzero': mae_nonzero,
            'nf_rmse': nf_rmse,
            'nf_mae': nf_mae,
        })

        all_test_predictions.append(test_preds)
        all_test_targets.append(test_targets)

    # Summary across all folds
    if verbose:
        print(f"\n{'='*50}")
        print("Cross-Validation Summary — XGBoost Phase Fractions (NF)")
        print('='*50)

    avg_test_loss = np.mean([r['test_loss'] for r in fold_results])
    avg_test_rmse = np.mean([r['test_rmse'] for r in fold_results])
    avg_test_mae = np.mean([r['test_mae'] for r in fold_results])
    avg_rmse_nonzero = np.mean([r['rmse_nonzero'] for r in fold_results])
    avg_mae_nonzero = np.mean([r['mae_nonzero'] for r in fold_results])
    avg_nf_rmse = np.mean([r['nf_rmse'] for r in fold_results])
    avg_nf_mae = np.mean([r['nf_mae'] for r in fold_results])
    std_test_loss = np.std([r['test_loss'] for r in fold_results])

    if verbose:
        print(f"Overall (all values):")
        print(f"  Avg Test MSE: {avg_test_loss:.4f} (+/- {std_test_loss:.4f})")
        print(f"  Avg RMSE: {avg_test_rmse:.4f}, MAE: {avg_test_mae:.4f}")
        print(f"\nOverall (non-zero only):")
        print(f"  Avg RMSE: {avg_rmse_nonzero:.4f}, MAE: {avg_mae_nonzero:.4f}")
        print(f"\nPhase Fraction (NF, non-zero only):")
        print(f"  Avg RMSE: {avg_nf_rmse:.4f}, MAE: {avg_nf_mae:.4f}")

    return {
        'fold_results': fold_results,
        'avg_test_loss': avg_test_loss,
        'avg_test_rmse': avg_test_rmse,
        'avg_test_mae': avg_test_mae,
        'avg_rmse_nonzero': avg_rmse_nonzero,
        'avg_mae_nonzero': avg_mae_nonzero,
        'avg_nf_rmse': avg_nf_rmse,
        'avg_nf_mae': avg_nf_mae,
        'all_predictions': all_test_predictions,
        'all_targets': all_test_targets,
    }


# =====================================================================
# Ax Bayesian Optimization for XGBoost DF f(T)
# =====================================================================

ax_client_xgb_df = AxClient()
ax_client_xgb_df.create_experiment(
    name="XGB opt DF f(T) Calphed",
    parameters=[
        {
            "name": "n_estimators",
            "type": "range",
            "bounds": [100, 5000],
            "value_type": "int",
        },
        {
            "name": "max_depth",
            "type": "range",
            "bounds": [3, 100],
            "value_type": "int",
        },
        {
            "name": "learning_rate",
            "type": "range",
            "bounds": [0.005, 0.3],
            "log_scale": True,
        },
        {
            "name": "subsample",
            "type": "range",
            "bounds": [0.5, 1.0],
        },
        {
            "name": "colsample_bytree",
            "type": "range",
            "bounds": [0.3, 1.0],
        },
        {
            "name": "min_child_weight",
            "type": "range",
            "bounds": [1, 20],
            "value_type": "int",
        },
        {
            "name": "gamma",
            "type": "range",
            "bounds": [0.0, 5.0],
        },
        {
            "name": "reg_alpha",
            "type": "range",
            "bounds": [1e-6, 10.0],
            "log_scale": True,
        },
        {
            "name": "reg_lambda",
            "type": "range",
            "bounds": [1e-6, 10.0],
            "log_scale": True,
        },
        {
            "name": "early_stopping_rounds",
            "type": "range",
            "bounds": [10, 50],
            "value_type": "int",
        },
    ],
    objectives={"avg_rmse_nonzero": ObjectiveProperties(minimize=True)},
)


def evaluate_for_ax_xgb_df(parameterization):
    """Wrapper to convert Ax parameters to evaluate_parameters_XGB_DF_FT format."""
    parameters = {
        "n_estimators": parameterization["n_estimators"],
        "max_depth": parameterization["max_depth"],
        "learning_rate": parameterization["learning_rate"],
        "subsample": parameterization["subsample"],
        "colsample_bytree": parameterization["colsample_bytree"],
        "min_child_weight": parameterization["min_child_weight"],
        "gamma": parameterization["gamma"],
        "reg_alpha": parameterization["reg_alpha"],
        "reg_lambda": parameterization["reg_lambda"],
        "early_stopping_rounds": parameterization["early_stopping_rounds"],
    }

    results = evaluate_parameters_XGB_DF_FT(parameters, verbose=False)

    # Calculate SEM from fold results
    rmse_nonzero_values = [r["rmse_nonzero"] for r in results["fold_results"]]
    mean_rmse_nonzero = np.mean(rmse_nonzero_values)
    std_rmse_nonzero = np.std(rmse_nonzero_values, ddof=1)
    sem_rmse_nonzero = std_rmse_nonzero / np.sqrt(len(rmse_nonzero_values))

    return {"avg_rmse_nonzero": (mean_rmse_nonzero, sem_rmse_nonzero)}

SAVE_PATH_XGB_DF = r"Ax_checkpoints/ax_client_XGB_DF(T)_checkpoint.json"

[INFO 03-11 06:06:42] ax.service.ax_client: Starting optimization with verbose logging. To disable logging, set the `verbose_logging` argument to `False`. Note that float values in the logs are rounded to 6 decimal points.
[INFO 03-11 06:06:42] ax.service.utils.instantiation: Inferred value type of ParameterType.FLOAT for parameter learning_rate. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
[INFO 03-11 06:06:42] ax.service.utils.instantiation: Inferred value type of ParameterType.FLOAT for parameter subsample. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
[INFO 03-11 06:06:42] ax.service.utils.instantiation: Inferred value type of ParameterType.FLOAT for parameter colsample_bytree. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
[INFO 03-11 06:06:42] ax.service.utils.instantiation: Inferred value type of ParameterType.FLOAT for parameter gamma. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
[INFO 03-11 06:06:42] ax.service.utils.instantiation: Inferred value type of ParameterType.FLOAT for parameter reg_alpha. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
[INFO 03-11 06:06:42] ax.service.utils.instantiation: Inferred value type of ParameterType.FLOAT for parameter reg_lambda. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
[INFO 03-11 06:06:42] ax.service.utils.instantiation: Created search space: SearchSpace(parameters=[RangeParameter(name='n_estimators', parameter_type=INT, range=[100, 5000]), RangeParameter(name='max_depth', parameter_type=INT, range=[3, 100]), RangeParameter(name='learning_rate', parameter_type=FLOAT, range=[0.005, 0.3], log_scale=True), RangeParameter(name='subsample', parameter_type=FLOAT, range=[0.5, 1.0]), RangeParameter(name='colsample_bytree', parameter_type=FLOAT, range=[0.3, 1.0]), RangeParameter(name='min_child_weight', parameter_type=INT, range=[1, 20]), RangeParameter(name='gamma', parameter_type=FLOAT, range=[0.0, 5.0]), RangeParameter(name='reg_alpha', parameter_type=FLOAT, range=[1e-06, 10.0], log_scale=True), RangeParameter(name='reg_lambda', parameter_type=FLOAT, range=[1e-06, 10.0], log_scale=True), RangeParameter(name='early_stopping_rounds', parameter_type=INT, range=[10, 50])], parameter_constraints=[]).
[INFO 03-11 06:06:42] ax.modelbridge.dispatch_utils: Using Models.BOTORCH_MODULAR since there is at least one ordered parameter and there are no unordered categorical parameters.
[INFO 03-11 06:06:42] ax.modelbridge.dispatch_utils: Calculating the number of remaining initialization trials based on num_initialization_trials=None max_initialization_trials=None num_tunable_parameters=10 num_trials=None use_batch_trials=False
[INFO 03-11 06:06:42] ax.modelbridge.dispatch_utils: calculated num_initialization_trials=20
[INFO 03-11 06:06:42] ax.modelbridge.dispatch_utils: num_completed_initialization_trials=0 num_remaining_initialization_trials=20
[INFO 03-11 06:06:42] ax.modelbridge.dispatch_utils: `verbose`, `disable_progbar`, and `jit_compile` are not yet supported when using `choose_generation_strategy` with ModularBoTorchModel, dropping these arguments.
[INFO 03-11 06:06:42] ax.modelbridge.dispatch_utils: Using Bayesian Optimization generation strategy: GenerationStrategy(name='Sobol+BoTorch', steps=[Sobol for 20 trials, BoTorch for subsequent trials]). Iterations after 20 will take longer to generate due to model-fitting.

In [ ]:
# =====================================================================
# Run the Bayesian Optimization Loop — XGBoost DF f(T)
# =====================================================================
n_trials_xgb_df = 100
SAVE_PATH_XGB_DF = r"Ax_checkpoints/ax_client_XGB_DF(T)_checkpoint.json"


for i in range(n_trials_xgb_df):
    print(f"\n{'='*60}")
    print(f"Trial {i+1}/{n_trials_xgb_df}")
    print('='*60)

    parameters, trial_index = ax_client_xgb_df.get_next_trial()
    print(f"Parameters: {parameters}")

    try:
        result = evaluate_for_ax_xgb_df(parameters)
        ax_client_xgb_df.complete_trial(trial_index=trial_index, raw_data=result)
        print(f"Result: Non-zero RMSE = {result['avg_rmse_nonzero'][0]:.4f}")
    except Exception as e:
        print(f"Trial failed: {e}")
        ax_client_xgb_df.log_trial_failure(trial_index=trial_index)
    # Save checkpoint after each trial
    ax_client_xgb_df.save_to_json_file(SAVE_PATH_XGB_DF)
    print(f"Checkpoint saved to {SAVE_PATH_XGB_DF}")

# Get best parameters
best_parameters_xgb_df, values_xgb_df = ax_client_xgb_df.get_best_parameters()
print(f"\n{'='*60}")
print("OPTIMIZATION COMPLETE — XGBoost Phase Fractions DF f(T)")
print('='*60)
print(f"Best parameters: {best_parameters_xgb_df}")
print(f"Best Non-zero RMSE: {values_xgb_df[0]['avg_rmse_nonzero']:.4f}")

In [13]:
# Load the XGBoost Ax client from last save and continue optimization to 100 trials
ax_client_xgb_df = AxClient.load_from_json_file(SAVE_PATH_XGB_DF)

completed_trials = len(ax_client_xgb_df.experiment.trials)
target_trials = 100
remaining_trials = target_trials - completed_trials

print(f"Loaded {completed_trials} completed trials from {SAVE_PATH_XGB_DF}")
print(f"Remaining trials to reach {target_trials}: {remaining_trials}")

if remaining_trials > 0:
    for i in range(remaining_trials):
        current_trial = completed_trials + i + 1
        print(f"\n{'='*60}")
        print(f"Trial {current_trial}/{target_trials}")
        print('='*60)

        parameters, trial_index = ax_client_xgb_df.get_next_trial()
        print(f"Parameters: {parameters}")

        try:
            result = evaluate_for_ax_xgb_df(parameters)
            ax_client_xgb_df.complete_trial(trial_index=trial_index, raw_data=result)
            print(f"Result: Non-zero RMSE = {result['avg_rmse_nonzero'][0]:.4f}")
        except Exception as e:
            print(f"Trial failed: {e}")
            ax_client_xgb_df.log_trial_failure(trial_index=trial_index)

        # Save after each trial for safety
        ax_client_xgb_df.save_to_json_file(SAVE_PATH_XGB_DF)

    # Get best parameters after all trials
    best_parameters, values = ax_client_xgb_df.get_best_parameters()
    print(f"\n{'='*60}")
    print("OPTIMIZATION COMPLETE")
    print('='*60)
    print(f"Best parameters: {best_parameters}")
    print(f"Best Non-zero RMSE: {values[0]['avg_rmse_nonzero']:.4f}")
else:
    print("Already at or past 100 trials. No additional trials needed.")
    best_parameters, values = ax_client_xgb_df.get_best_parameters()
    print(f"Best parameters: {best_parameters}")
    print(f"Best Non-zero RMSE: {values[0]['avg_rmse_nonzero']:.4f}")

[INFO 03-11 06:06:59] ax.service.ax_client: Starting optimization with verbose logging. To disable logging, set the `verbose_logging` argument to `False`. Note that float values in the logs are rounded to 6 decimal points.
c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\core\data.py:295: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))
c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\modelbridge\cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 03-11 06:06:59] ax.service.ax_client: Generated new trial 83 with parameters {'n_estimators': 3243, 'max_depth': 79, 'learning_rate': 0.0379, 'subsample': 0.617433, 'colsample_bytree': 0.845787, 'min_child_weight': 8, 'gamma': 0.253928, 'reg_alpha': 0.594869, 'reg_lambda': 1.3e-05, 'early_stopping_rounds': 46} using model Sobol.

Loaded 83 completed trials from c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_DF_fT_checkpoint.json
Remaining trials to reach 100: 17

============================================================
Trial 84/100
============================================================
Parameters: {'n_estimators': 3243, 'max_depth': 79, 'learning_rate': 0.03789960863323415, 'subsample': 0.6174330250360072, 'colsample_bytree': 0.8457865629345178, 'min_child_weight': 8, 'gamma': 0.2539283502846956, 'reg_alpha': 0.5948690377718296, 'reg_lambda': 1.2901651382278928e-05, 'early_stopping_rounds': 46}

[INFO 03-11 08:49:01] ax.service.ax_client: Completed trial 83 with data: {'avg_rmse_nonzero': (np.float64(4.476533), np.float64(0.776915))}.
[INFO 03-11 08:49:01] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_DF_fT_checkpoint.json`.
c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\core\data.py:295: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))
c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\modelbridge\cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 03-11 08:49:01] ax.service.ax_client: Generated new trial 84 with parameters {'n_estimators': 3993, 'max_depth': 19, 'learning_rate': 0.25126, 'subsample': 0.848032, 'colsample_bytree': 0.696249, 'min_child_weight': 4, 'gamma': 3.726222, 'reg_alpha': 0.055704, 'reg_lambda': 6.8e-05, 'early_stopping_rounds': 30} using model Sobol.

Result: Non-zero RMSE = 4.4765

============================================================
Trial 85/100
============================================================
Parameters: {'n_estimators': 3993, 'max_depth': 19, 'learning_rate': 0.25125954230322783, 'subsample': 0.848032443318516, 'colsample_bytree': 0.6962485030293464, 'min_child_weight': 4, 'gamma': 3.7262221658602357, 'reg_alpha': 0.055704055488356614, 'reg_lambda': 6.777471862379118e-05, 'early_stopping_rounds': 30}

[INFO 03-11 09:23:20] ax.service.ax_client: Completed trial 84 with data: {'avg_rmse_nonzero': (np.float64(4.641857), np.float64(0.702436))}.
[INFO 03-11 09:23:20] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_DF_fT_checkpoint.json`.
c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\core\data.py:295: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))
c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\modelbridge\cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 03-11 09:23:20] ax.service.ax_client: Generated new trial 85 with parameters {'n_estimators': 2381, 'max_depth': 56, 'learning_rate': 0.006862, 'subsample': 0.636483, 'colsample_bytree': 0.588823, 'min_child_weight': 13, 'gamma': 2.402634, 'reg_alpha': 5e-06, 'reg_lambda': 2.946433, 'early_stopping_rounds': 28} using model Sobol.

Result: Non-zero RMSE = 4.6419

============================================================
Trial 86/100
============================================================
Parameters: {'n_estimators': 2381, 'max_depth': 56, 'learning_rate': 0.006862184635488844, 'subsample': 0.6364830289967358, 'colsample_bytree': 0.5888227989897132, 'min_child_weight': 13, 'gamma': 2.402634476311505, 'reg_alpha': 4.76818203595208e-06, 'reg_lambda': 2.9464334231411904, 'early_stopping_rounds': 28}

[INFO 03-11 16:40:07] ax.service.ax_client: Completed trial 85 with data: {'avg_rmse_nonzero': (np.float64(4.310337), np.float64(0.746595))}.
[INFO 03-11 16:40:07] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_DF_fT_checkpoint.json`.
c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\core\data.py:295: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))
c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\modelbridge\cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 03-11 16:40:07] ax.service.ax_client: Generated new trial 86 with parameters {'n_estimators': 2521, 'max_depth': 15, 'learning_rate': 0.072764, 'subsample': 0.941276, 'colsample_bytree': 0.969391, 'min_child_weight': 9, 'gamma': 0.517556, 'reg_alpha': 0.037581, 'reg_lambda': 0.186792, 'early_stopping_rounds': 34} using model Sobol.

Result: Non-zero RMSE = 4.3103

============================================================
Trial 87/100
============================================================
Parameters: {'n_estimators': 2521, 'max_depth': 15, 'learning_rate': 0.07276434014330614, 'subsample': 0.9412760525010526, 'colsample_bytree': 0.9693908514454961, 'min_child_weight': 9, 'gamma': 0.5175560293719172, 'reg_alpha': 0.0375806455887885, 'reg_lambda': 0.18679224270030853, 'early_stopping_rounds': 34}

[INFO 03-11 18:26:48] ax.service.ax_client: Completed trial 86 with data: {'avg_rmse_nonzero': (np.float64(4.742786), np.float64(0.722084))}.
[INFO 03-11 18:26:48] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_DF_fT_checkpoint.json`.
c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\core\data.py:295: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))
c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\modelbridge\cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 03-11 18:26:48] ax.service.ax_client: Generated new trial 87 with parameters {'n_estimators': 3818, 'max_depth': 52, 'learning_rate': 0.013982, 'subsample': 0.543447, 'colsample_bytree': 0.336997, 'min_child_weight': 18, 'gamma': 4.369215, 'reg_alpha': 3e-06, 'reg_lambda': 0.001061, 'early_stopping_rounds': 27} using model Sobol.

Result: Non-zero RMSE = 4.7428

============================================================
Trial 88/100
============================================================
Parameters: {'n_estimators': 3818, 'max_depth': 52, 'learning_rate': 0.013982482554668677, 'subsample': 0.5434473524801433, 'colsample_bytree': 0.336997177824378, 'min_child_weight': 18, 'gamma': 4.369214936159551, 'reg_alpha': 3.117117861228671e-06, 'reg_lambda': 0.0010606878068469888, 'early_stopping_rounds': 27}

[INFO 03-11 23:18:22] ax.service.ax_client: Completed trial 87 with data: {'avg_rmse_nonzero': (np.float64(4.238345), np.float64(0.71681))}.
[INFO 03-11 23:18:22] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_DF_fT_checkpoint.json`.
c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\core\data.py:295: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))
c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\modelbridge\cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 03-11 23:18:22] ax.service.ax_client: Generated new trial 88 with parameters {'n_estimators': 3419, 'max_depth': 45, 'learning_rate': 0.126516, 'subsample': 0.79724, 'colsample_bytree': 0.548702, 'min_child_weight': 14, 'gamma': 2.11885, 'reg_alpha': 0.000938, 'reg_lambda': 1e-06, 'early_stopping_rounds': 11} using model Sobol.

Result: Non-zero RMSE = 4.2383

============================================================
Trial 89/100
============================================================
Parameters: {'n_estimators': 3419, 'max_depth': 45, 'learning_rate': 0.12651551801126082, 'subsample': 0.7972401301376522, 'colsample_bytree': 0.5487023763358593, 'min_child_weight': 14, 'gamma': 2.1188498847186565, 'reg_alpha': 0.0009381415917168166, 'reg_lambda': 1.3534965141258936e-06, 'early_stopping_rounds': 11}

[INFO 03-12 00:08:51] ax.service.ax_client: Completed trial 88 with data: {'avg_rmse_nonzero': (np.float64(4.369107), np.float64(0.7162))}.
[INFO 03-12 00:08:51] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_DF_fT_checkpoint.json`.
c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\core\data.py:295: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))
c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\modelbridge\cross_validation.py:439: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
[INFO 03-12 00:08:51] ax.service.ax_client: Generated new trial 89 with parameters {'n_estimators': 428, 'max_depth': 81, 'learning_rate': 0.010292, 'subsample': 0.718747, 'colsample_bytree': 0.74773, 'min_child_weight': 3, 'gamma': 3.314793, 'reg_alpha': 0.909845, 'reg_lambda': 0.046467, 'early_stopping_rounds': 50} using model Sobol.

Result: Non-zero RMSE = 4.3691

============================================================
Trial 90/100
============================================================
Parameters: {'n_estimators': 428, 'max_depth': 81, 'learning_rate': 0.010291549441053389, 'subsample': 0.7187466560862958, 'colsample_bytree': 0.7477296454831958, 'min_child_weight': 3, 'gamma': 3.3147934451699257, 'reg_alpha': 0.9098449317893097, 'reg_lambda': 0.046466838901836685, 'early_stopping_rounds': 50}

[INFO 03-12 04:42:55] ax.service.ax_client: Completed trial 89 with data: {'avg_rmse_nonzero': (np.float64(4.434648), np.float64(0.728413))}.
[INFO 03-12 04:42:55] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_DF_fT_checkpoint.json`.
c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\core\data.py:295: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

Result: Non-zero RMSE = 4.4346

============================================================
Trial 91/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize.py:652: RuntimeWarning: Optimization failed in `gen_candidates_scipy` with the following warning(s):
[OptimizeWarning('Unknown solver options: tol'), NumericalWarning('A not p.d., added jitter of 1.0e-08 to the diagonal'), OptimizationWarning('Optimization failed within `scipy.optimize.minimize` with status 2 and message ABNORMAL: .'), NumericalWarning('A not p.d., added jitter of 1.0e-08 to the diagonal')]
Trying again with a new set of initial conditions.
  return _optimize_acqf_batch(opt_inputs=opt_inputs)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize.py:652: RuntimeWarning: Optimization failed in `gen_candidates_scipy` with the following warning(s):
[OptimizeWarning('Unknown solver options: tol'), NumericalWarning('A not p.d., added jitter of 1.0e-08 to the diagonal'), OptimizationWarning('Optimization failed within `scipy.optimize.minimize` with status 2 and message ABNORMAL: .'), NumericalWarning('A not p.d., added jitter of 1.0e-08 to the diagonal')]
Trying again with a new set of initial conditions.
  return _optimize_acqf_batch(opt_inputs=opt_inputs)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize.py:652: RuntimeWarning: Optimization failed in `gen_candidates_scipy` with the following warning(s):
[OptimizeWarning('Unknown solver options: tol'), NumericalWarning('A not p.d., added jitter of 1.0e-08 to the diagonal'), OptimizationWarning('Optimization failed within `scipy.optimize.minimize` with status 2 and message ABNORMAL: .'), NumericalWarning('A not p.d., added jitter of 1.0e-08 to the diagonal')]
Trying again with a new set of initial conditions.
  return _optimize_acqf_batch(opt_inputs=opt_inputs)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(

Parameters: {'n_estimators': 4935, 'max_depth': 20, 'learning_rate': 0.048269671198996535, 'subsample': 0.5604853932773946, 'colsample_bytree': 0.3, 'min_child_weight': 1, 'gamma': 0.0, 'reg_alpha': 0.21662276182793602, 'reg_lambda': 10.0, 'early_stopping_rounds': 23}

[INFO 03-12 14:01:16] ax.service.ax_client: Completed trial 90 with data: {'avg_rmse_nonzero': (np.float64(4.298696), np.float64(0.717412))}.
[INFO 03-12 14:01:16] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_DF_fT_checkpoint.json`.
c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\core\data.py:295: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

Result: Non-zero RMSE = 4.2987

============================================================
Trial 92/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(

Parameters: {'n_estimators': 4646, 'max_depth': 3, 'learning_rate': 0.05297710905413752, 'subsample': 0.8948922252108319, 'colsample_bytree': 0.3, 'min_child_weight': 1, 'gamma': 0.4433598493961763, 'reg_alpha': 2.358935292512652, 'reg_lambda': 10.0, 'early_stopping_rounds': 50}

[INFO 03-12 20:40:38] ax.service.ax_client: Completed trial 91 with data: {'avg_rmse_nonzero': (np.float64(4.313744), np.float64(0.69422))}.
[INFO 03-12 20:40:38] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_DF_fT_checkpoint.json`.
c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\core\data.py:295: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

Result: Non-zero RMSE = 4.3137

============================================================
Trial 93/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 1249, 'max_depth': 100, 'learning_rate': 0.29999999999999993, 'subsample': 1.0, 'colsample_bytree': 0.3, 'min_child_weight': 20, 'gamma': 0.0, 'reg_alpha': 10.0, 'reg_lambda': 0.6588421894380211, 'early_stopping_rounds': 50}

[INFO 03-12 22:19:16] ax.service.ax_client: Completed trial 92 with data: {'avg_rmse_nonzero': (np.float64(4.477063), np.float64(0.665648))}.
[INFO 03-12 22:19:16] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_DF_fT_checkpoint.json`.
c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\core\data.py:295: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

Result: Non-zero RMSE = 4.4771

============================================================
Trial 94/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize.py:652: RuntimeWarning: Optimization failed in `gen_candidates_scipy` with the following warning(s):
[NumericalWarning('A not p.d., added jitter of 1.0e-08 to the diagonal'), NumericalWarning('A not p.d., added jitter of 1.0e-08 to the diagonal'), NumericalWarning('A not p.d., added jitter of 1.0e-08 to the diagonal'), NumericalWarning('A not p.d., added jitter of 1.0e-08 to the diagonal'), OptimizationWarning('Optimization failed within `scipy.optimize.minimize` with status 2 and message ABNORMAL: .'), NumericalWarning('A not p.d., added jitter of 1.0e-08 to the diagonal')]
Trying again with a new set of initial conditions.
  return _optimize_acqf_batch(opt_inputs=opt_inputs)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 100, 'max_depth': 3, 'learning_rate': 0.23714644680252103, 'subsample': 0.5803505548599137, 'colsample_bytree': 0.3, 'min_child_weight': 20, 'gamma': 0.0, 'reg_alpha': 3.92848722738669, 'reg_lambda': 0.5761302585836496, 'early_stopping_rounds': 50}

[INFO 03-12 23:17:51] ax.service.ax_client: Completed trial 93 with data: {'avg_rmse_nonzero': (np.float64(4.54138), np.float64(0.708198))}.
[INFO 03-12 23:17:51] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_DF_fT_checkpoint.json`.
c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\core\data.py:295: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

Result: Non-zero RMSE = 4.5414

============================================================
Trial 95/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize.py:652: RuntimeWarning: Optimization failed in `gen_candidates_scipy` with the following warning(s):
[OptimizeWarning('Unknown solver options: tol'), NumericalWarning('A not p.d., added jitter of 1.0e-08 to the diagonal'), OptimizationWarning('Optimization failed within `scipy.optimize.minimize` with status 2 and message ABNORMAL: .'), NumericalWarning('A not p.d., added jitter of 1.0e-08 to the diagonal')]
Trying again with a new set of initial conditions.
  return _optimize_acqf_batch(opt_inputs=opt_inputs)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize.py:652: RuntimeWarning: Optimization failed in `gen_candidates_scipy` with the following warning(s):
[OptimizeWarning('Unknown solver options: tol'), NumericalWarning('A not p.d., added jitter of 1.0e-08 to the diagonal'), OptimizationWarning('Optimization failed within `scipy.optimize.minimize` with status 2 and message ABNORMAL: .'), NumericalWarning('A not p.d., added jitter of 1.0e-08 to the diagonal')]
Trying again with a new set of initial conditions.
  return _optimize_acqf_batch(opt_inputs=opt_inputs)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 3355, 'max_depth': 88, 'learning_rate': 0.005, 'subsample': 0.5, 'colsample_bytree': 0.3, 'min_child_weight': 2, 'gamma': 1.8152022936628183, 'reg_alpha': 1.2096351577335574e-06, 'reg_lambda': 9.931429446724211, 'early_stopping_rounds': 40}

[INFO 03-13 16:41:16] ax.service.ax_client: Completed trial 94 with data: {'avg_rmse_nonzero': (np.float64(4.272209), np.float64(0.720924))}.
[INFO 03-13 16:41:16] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_DF_fT_checkpoint.json`.
c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\core\data.py:295: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

Result: Non-zero RMSE = 4.2722

============================================================
Trial 96/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize.py:652: RuntimeWarning: Optimization failed in `gen_candidates_scipy` with the following warning(s):
[NumericalWarning('A not p.d., added jitter of 1.0e-08 to the diagonal'), NumericalWarning('A not p.d., added jitter of 1.0e-08 to the diagonal'), OptimizationWarning('Optimization failed within `scipy.optimize.minimize` with status 2 and message ABNORMAL: .'), NumericalWarning('A not p.d., added jitter of 1.0e-08 to the diagonal'), NumericalWarning('A not p.d., added jitter of 1.0e-08 to the diagonal'), NumericalWarning('A not p.d., added jitter of 1.0e-08 to the diagonal')]
Trying again with a new set of initial conditions.
  return _optimize_acqf_batch(opt_inputs=opt_inputs)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize.py:652: RuntimeWarning: Optimization failed in `gen_candidates_scipy` with the following warning(s):
[OptimizeWarning('Unknown solver options: tol'), NumericalWarning('A not p.d., added jitter of 1.0e-08 to the diagonal'), OptimizationWarning('Optimization failed within `scipy.optimize.minimize` with status 2 and message ABNORMAL: .'), NumericalWarning('A not p.d., added jitter of 1.0e-08 to the diagonal')]
Trying again with a new set of initial conditions.
  return _optimize_acqf_batch(opt_inputs=opt_inputs)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 4409, 'max_depth': 8, 'learning_rate': 0.009800219823648057, 'subsample': 0.7149247856739281, 'colsample_bytree': 0.3469164244346193, 'min_child_weight': 19, 'gamma': 0.07105989188714533, 'reg_alpha': 1e-06, 'reg_lambda': 0.003269163053767945, 'early_stopping_rounds': 10}

[INFO 03-14 00:15:03] ax.service.ax_client: Completed trial 95 with data: {'avg_rmse_nonzero': (np.float64(4.193456), np.float64(0.723391))}.
[INFO 03-14 00:15:03] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_DF_fT_checkpoint.json`.
c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\core\data.py:295: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

Result: Non-zero RMSE = 4.1935

============================================================
Trial 97/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(

Parameters: {'n_estimators': 3328, 'max_depth': 45, 'learning_rate': 0.005, 'subsample': 0.5, 'colsample_bytree': 0.3, 'min_child_weight': 1, 'gamma': 5.0, 'reg_alpha': 0.018320764773211578, 'reg_lambda': 10.0, 'early_stopping_rounds': 50}

[INFO 03-14 09:43:59] ax.service.ax_client: Completed trial 96 with data: {'avg_rmse_nonzero': (np.float64(4.313261), np.float64(0.720945))}.
[INFO 03-14 09:43:59] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_DF_fT_checkpoint.json`.
c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\core\data.py:295: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

Result: Non-zero RMSE = 4.3133

============================================================
Trial 98/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\botorch\optim\optimize.py:652: RuntimeWarning: Optimization failed in `gen_candidates_scipy` with the following warning(s):
[OptimizeWarning('Unknown solver options: tol'), NumericalWarning('A not p.d., added jitter of 1.0e-08 to the diagonal'), OptimizationWarning('Optimization failed within `scipy.optimize.minimize` with status 2 and message ABNORMAL: .'), NumericalWarning('A not p.d., added jitter of 1.0e-08 to the diagonal')]
Trying again with a new set of initial conditions.
  return _optimize_acqf_batch(opt_inputs=opt_inputs)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(

Parameters: {'n_estimators': 1210, 'max_depth': 3, 'learning_rate': 0.011530214041659277, 'subsample': 0.5, 'colsample_bytree': 0.3, 'min_child_weight': 4, 'gamma': 0.5478430488384357, 'reg_alpha': 1e-06, 'reg_lambda': 1e-06, 'early_stopping_rounds': 50}

[INFO 03-14 13:00:59] ax.service.ax_client: Completed trial 97 with data: {'avg_rmse_nonzero': (np.float64(4.351881), np.float64(0.746515))}.
[INFO 03-14 13:00:59] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_DF_fT_checkpoint.json`.
c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\core\data.py:295: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

Result: Non-zero RMSE = 4.3519

============================================================
Trial 99/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.

Parameters: {'n_estimators': 381, 'max_depth': 42, 'learning_rate': 0.012478996386301679, 'subsample': 0.9842695521339649, 'colsample_bytree': 0.3, 'min_child_weight': 1, 'gamma': 0.0, 'reg_alpha': 1.7975031893175306e-05, 'reg_lambda': 1e-06, 'early_stopping_rounds': 39}

[INFO 03-16 06:47:32] ax.service.ax_client: Completed trial 98 with data: {'avg_rmse_nonzero': (np.float64(4.186865), np.float64(0.680615))}.
[INFO 03-16 06:47:32] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_DF_fT_checkpoint.json`.
c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\core\data.py:295: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

Result: Non-zero RMSE = 4.1869

============================================================
Trial 100/100
============================================================

c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
c:\Users\Chris\pytorch_gpu\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(

Parameters: {'n_estimators': 638, 'max_depth': 3, 'learning_rate': 0.005, 'subsample': 1.0, 'colsample_bytree': 0.3, 'min_child_weight': 6, 'gamma': 3.162864367783304, 'reg_alpha': 10.0, 'reg_lambda': 0.01960647310709318, 'early_stopping_rounds': 27}

[INFO 03-16 10:32:10] ax.service.ax_client: Completed trial 99 with data: {'avg_rmse_nonzero': (np.float64(4.489736), np.float64(0.747362))}.
[INFO 03-16 10:32:10] ax.service.ax_client: Saved JSON-serialized state of optimization to `c:\Users\Chris\OneDrive\Desktop\ML Project\ax_client_XGB_DF_fT_checkpoint.json`.
c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\core\data.py:295: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))

Result: Non-zero RMSE = 4.4897

============================================================
OPTIMIZATION COMPLETE
============================================================
Best parameters: {'n_estimators': 3742, 'max_depth': 11, 'learning_rate': 0.04133057413580116, 'subsample': 0.6830441900528967, 'colsample_bytree': 0.32020963728427887, 'min_child_weight': 8, 'gamma': 3.1530884513631463, 'reg_alpha': 0.16534358452677872, 'reg_lambda': 0.0001841925425023652, 'early_stopping_rounds': 16}
Best Non-zero RMSE: 4.3778

In [15]:
ax_client_xgb_df = AxClient.load_from_json_file(SAVE_PATH_XGB_DF)
# Get best parameters
best_parameters_xgb_df, values_xgb_df = ax_client_xgb_df.get_best_parameters()
print(f"\n{'='*60}")
print("OPTIMIZATION COMPLETE — XGBoost Phase Fractions DF f(T)")
print('='*60)
print(f"Best parameters: {best_parameters_xgb_df}")
print(f"Best Non-zero RMSE: {values_xgb_df[0]['avg_rmse_nonzero']:.4f}")

[INFO 03-09 09:01:32] ax.service.ax_client: Starting optimization with verbose logging. To disable logging, set the `verbose_logging` argument to `False`. Note that float values in the logs are rounded to 6 decimal points.

============================================================
OPTIMIZATION COMPLETE — XGBoost Phase Fractions DF f(T)
============================================================
Best parameters: {'n_estimators': 1203, 'max_depth': 18, 'learning_rate': 0.022103, 'subsample': 0.69082, 'colsample_bytree': 0.436275, 'min_child_weight': 1, 'gamma': 3.34254, 'reg_alpha': 0.004137, 'reg_lambda': 0.10817, 'early_stopping_rounds': 23}
Best Non-zero RMSE: 4.1923

c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\core\data.py:295: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))
c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\core\data.py:295: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return cls(df=pd.concat(dfs, axis=0, sort=True))