In [3]:
#this scripts uses calculated thermo cac equilibrium data to train ML models to predict D_max for different compositions. This uses CBFV as additional features.

In [13]:
#Import necessary libraries
import pandas as pd
import numpy as np
import torch
import matplotlib.pyplot as plt
from CBFV import composition
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import re
from ast import literal_eval
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset
from xgboost import XGBRegressor
from sklearn.multioutput import MultiOutputRegressor
from ax.service.ax_client import AxClient, ObjectiveProperties
from ax.core.arm import Arm
import ujson as js
from scipy.stats import sem

In [2]:
#according to the single tree notebook the best temperature ranges to utalize are: 2200, 1700, 2450, 2100, 2400, 1900, 1850
#according to the same notebook the NF or phase fraction features are ineffective at predicting D_max and thus will not be used

In [3]:
#pull training data
train_opt_CALPHAD_df = pd.read_csv(r"Data/F(Composition)_Data/CALPHAD_alloys_train_opt.csv")

#pull test data
test_CALPHAD_df = pd.read_csv(r"Data/F(Composition)_Data/CALPHAD_alloys_test.csv")


train_opt_CALPHAD_df.head()

,alloy_string,DF_AG2CA_T0C,DF_AG2CA_T1000C,DF_AG2CA_T100C,DF_AG2CA_T1050C,DF_AG2CA_T1100C,DF_AG2CA_T1150C,DF_AG2CA_T1200C,DF_AG2CA_T1250C,DF_AG2CA_T1300C,...,NF_ZRSI_T50C,NF_ZRSI_T550C,NF_ZRSI_T600C,NF_ZRSI_T650C,NF_ZRSI_T700C,NF_ZRSI_T750C,NF_ZRSI_T800C,NF_ZRSI_T850C,NF_ZRSI_T900C,NF_ZRSI_T950C
0,B22.00Co4.00Fe68.00Y6.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Cu47.00Nb11.00Ni8.00Si1.00Ti33.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,B6.00C15.00Co6.42Er0.75Fe57.82Mo14.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Be24.00Cu12.00Fe8.00Nb8.00Zr48.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Al10.00Ce60.00Cu20.00Ni10.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [4]:
#create the CBFV features for the training and test data
#start by pulling the formula column
train_opt_formula_df = pd.DataFrame({'formula': train_opt_CALPHAD_df['alloy_string']})
test_formula_df = pd.DataFrame({'formula': test_CALPHAD_df['alloy_string']})

#add a target column for CBFV api
train_opt_formula_df['target'] = 0
test_formula_df['target'] = 0

#use the CBFV api to create the features
train_opt_CBFV_df, _, train_opt_formulae, skipped_train = composition.generate_features(train_opt_formula_df, elem_prop='magpie')
test_CBFV_df, _, test_formulae, skipped_test = composition.generate_features(test_formula_df, elem_prop='magpie')


print(f"CBFV train features shape: {train_opt_CBFV_df.shape}, test features shape: {test_CBFV_df.shape}")
print(f"Number of skipped formulas: {len(skipped_train)}, {len(skipped_test)}")
train_opt_CBFV_df.head()

Processing Input Data: 100%|██████████| 882/882 [00:00<00:00, 27555.87it/s]

	Featurizing Compositions...

Assigning Features...: 100%|██████████| 882/882 [00:00<00:00, 27128.69it/s]

	Creating Pandas Objects...

Processing Input Data: 100%|██████████| 98/98 [00:00<00:00, 49026.93it/s]

	Featurizing Compositions...

Assigning Features...: 100%|██████████| 98/98 [00:00<00:00, 28005.85it/s]

	Creating Pandas Objects...
CBFV train features shape: (882, 132), test features shape: (98, 132)
Number of skipped formulas: 0, 0

,avg_Number,avg_MendeleevNumber,avg_AtomicWeight,avg_MeltingT,avg_Column,avg_Row,avg_CovalentRadius,avg_Electronegativity,avg_NsValence,avg_NpValence,...,mode_NValence,mode_NsUnfilled,mode_NpUnfilled,mode_NdUnfilled,mode_NfUnfilled,mode_NUnfilled,mode_GSvolume_pa,mode_GSbandgap,mode_GSmagmom,mode_SpaceGroupNumber
0,22.200000,56.280000,48.044699,1926.70000,8.840000,3.620000,124.680000,1.841600,2.000000,0.220000,...,8.0,0.0,0.0,4.0,0.0,4.0,10.730,0.0,2.110663,229.0
1,27.780000,55.100000,60.858759,1736.29190,7.980000,4.100000,143.910000,1.749000,1.420000,0.020000,...,11.0,1.0,0.0,0.0,0.0,1.0,11.070,0.0,0.000000,225.0
2,24.359036,58.662966,53.217519,2293.90019,8.946795,3.734973,123.841484,1.995602,1.859986,0.360036,...,8.0,0.0,0.0,4.0,0.0,4.0,10.730,0.0,2.110663,229.0
3,29.000000,53.040000,65.476074,1923.65240,4.760000,4.080000,146.560000,1.517600,1.800000,0.000000,...,4.0,0.0,0.0,8.0,0.0,8.0,23.195,0.0,0.000000,194.0
4,44.700000,35.200000,105.346294,1180.30100,6.300000,5.100000,173.300000,1.404000,1.800000,0.100000,...,4.0,0.0,0.0,9.0,13.0,22.0,37.240,0.0,0.000000,194.0

In [5]:
#filter the CALPHAD data to include only driving forces at the temepratures of interests
# Define the temperature ranges of interest
temperature_range = [2200, 1700, 2450, 2100, 2400, 1900, 1850]
temperature_range_str = [str(temp) for temp in temperature_range]

# Filter the columns to include only those with the specified temperature ranges and Df
filtered_CALPHAD_cols = [col for col in train_opt_CALPHAD_df.columns if any(temp in col for temp in temperature_range_str) and 'DF' in col]

print(f"Number of filtered CALPHAD columns: {len(filtered_CALPHAD_cols)}")

Number of filtered CALPHAD columns: 5628

In [ ]:
#combine the CBFV features with the filtered CALPHAD features for training and test data
X_train_opt = pd.concat([train_opt_CBFV_df, train_opt_CALPHAD_df[filtered_CALPHAD_cols]], axis=1)
X_test = pd.concat([test_CBFV_df, test_CALPHAD_df[filtered_CALPHAD_cols]], axis=1)

print(f"Combined train features shape: {X_train_opt.shape}, Combined test features shape: {X_test.shape}")

Combined train features shape: (882, 5760), Combined test features shape: (98, 5760)

In [9]:
#load the dmax json data and create y data
D_max_dict = js.load(open(r"Data\dmax_data.json", 'r'))

y_train_opt = [D_max_dict[formula] for formula in train_opt_CALPHAD_df['alloy_string']]
y_test = [D_max_dict[formula] for formula in test_CALPHAD_df['alloy_string']]

In [11]:
# Create 5 CV groups by clustering similar alloys together
# Standardize features for clustering
kmeans_scaler = StandardScaler()
kmeans_X_scaled = kmeans_scaler.fit_transform(X_train_opt)

# Use KMeans to group similar alloys into 5 clusters
kmeans = KMeans(n_clusters=5, random_state=42, n_init=10)
cv_groups = kmeans.fit_predict(kmeans_X_scaled)

# Add group assignments to a dataframe for reference
cv_group_df = pd.DataFrame({
    'formula': train_opt_CALPHAD_df['alloy_string'],
    'cv_group': cv_groups
})

print("CV Group distribution:")
print(cv_group_df['cv_group'].value_counts().sort_index())
print(f"\nTotal samples: {len(cv_groups)}")
cv_group_df.head(10)

CV Group distribution:
cv_group
0    512
1    146
2     86
3     96
4     42
Name: count, dtype: int64

Total samples: 882

                                 formula  cv_group
0               B22.00Co4.00Fe68.00Y6.00         0
1      Cu47.00Nb11.00Ni8.00Si1.00Ti33.00         0
2  B6.00C15.00Co6.42Er0.75Fe57.82Mo14.00         2
3      Be24.00Cu12.00Fe8.00Nb8.00Zr48.00         0
4           Al10.00Ce60.00Cu20.00Ni10.00         3
5            Cu20.00Gd10.00Mg65.00Ni5.00         1
6                  Ca55.00Cu20.00Mg25.00         1
7      Ag5.00Al12.50Cu15.00Fe5.00La62.50         3
8        B5.00C10.00Co35.00Fe40.00P10.00         2
9                  Ca55.00Mg20.00Zn25.00         1

In [ ]:
# --- Flexible NN for D_max regression (5760 → 1) ---
class DmaxNet(nn.Module):
    def __init__(self, input_dim, hidden_layers, dropout_rate=0.3, activation="relu"):
        """
        Args:
            input_dim:      number of input features (5760)
            hidden_layers:  list of ints, e.g. [1024, 512, 256]
            dropout_rate:   dropout probability applied after each hidden layer
            activation:     "relu", "leaky_relu", "elu", or "selu"
        """
        super().__init__()
        act_fn = {"relu": nn.ReLU, "leaky_relu": nn.LeakyReLU,
                  "elu": nn.ELU, "selu": nn.SELU}[activation]

        layers = []
        prev = input_dim
        for units in hidden_layers:
            layers.append(nn.Linear(prev, units))
            layers.append(nn.BatchNorm1d(units))
            layers.append(act_fn())
            layers.append(nn.Dropout(dropout_rate))
            prev = units
        layers.append(nn.Linear(prev, 1))
        self.net = nn.Sequential(*layers)

    def forward(self, x):
        return self.net(x).squeeze(-1)


def train_one_epoch(model, loader, optimizer, criterion, device):
    """Train model for one epoch. Returns average training loss."""
    model.train()
    total_loss = 0.0
    n_batches = 0
    for xb, yb in loader:
        xb, yb = xb.to(device), yb.to(device)
        optimizer.zero_grad()
        loss = criterion(model(xb), yb)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
        n_batches += 1
    return total_loss / n_batches


def evaluate(model, loader, criterion, device):
    """Evaluate model on a loader. Returns average loss."""
    model.eval()
    total_loss = 0.0
    n_batches = 0
    with torch.no_grad():
        for xb, yb in loader:
            xb, yb = xb.to(device), yb.to(device)
            loss = criterion(model(xb), yb)
            total_loss += loss.item()
            n_batches += 1
    return total_loss / n_batches


def predict(model, loader, device):
    """Run inference on a loader. Returns (predictions, actuals) if labels exist, else just (predictions, None)."""
    model.eval()
    all_preds = []
    all_actuals = []
    has_labels = False
    with torch.no_grad():
        for batch in loader:
            if isinstance(batch, (list, tuple)) and len(batch) >= 2:
                xb, yb = batch[0], batch[1]
                has_labels = True
                all_actuals.append(yb.cpu().numpy())
            else:
                xb = batch[0] if isinstance(batch, (list, tuple)) else batch
            xb = xb.to(device)
            all_preds.append(model(xb).cpu().numpy())
    preds = np.concatenate(all_preds)
    actuals = np.concatenate(all_actuals) if has_labels else None
    return preds, actuals

In [42]:
#define the evaluate parameters function for the ax optimization loop of the dmax_nn model
def evaluate_parameters_NN_dmax(parameters):
    
    #break down the parameters
    batch_size = parameters.get("batch_size", 64)
    n_layers = parameters.get("n_layers", 3)
    layer_1_dim = parameters.get("layer_1_dim", 1024)
    layer_2_dim = parameters.get("layer_2_dim", 1024)
    layer_3_dim = parameters.get("layer_3_dim", 512)
    dropout_rate = parameters.get("dropout_rate", 0.3)
    activation = parameters.get("activation", "relu")
    lr = parameters.get("lr", 1e-3)
    weight_decay = parameters.get("weight_decay", 1e-4)
    patience = parameters.get("early_stopping_patience", 20)
    
    #combine layer dimensions into a list for the model
    hidden_layers = [layer_1_dim, layer_2_dim, layer_3_dim][:n_layers]
    
    # Auto-detect device
    if torch.cuda.is_available():
        device = torch.device('cuda')
    elif torch.backends.mps.is_available():
        device = torch.device('mps')
    else:
        device = torch.device('cpu')
    print(f"Using device: {device}")
    
    
    #copy the x and y data
    y_data = y_train_opt.copy()
    x_data = X_train_opt.copy()
    
    #initialize cross fold info
    all_fold_mse = []
    all_fold_rmse = []
    all_fold_mae = []
    
    for fold in range(1,6):
        print(f"Starting fold {fold}...")
        
        #Establish from the folds the train and test data
        X_fold_train = x_data[cv_groups != (fold-1)]
        y_fold_train = np.array(y_data)[cv_groups != (fold-1)]
        
        X_fold_test = x_data[cv_groups == (fold-1)]
        y_fold_test = np.array(y_data)[cv_groups == (fold-1)]
        
        #split the fold train data into train and validation data
        X_fold_train, X_fold_val, y_fold_train, y_fold_val = train_test_split(X_fold_train, y_fold_train, test_size=0.2, random_state=42)
        
        #scale the X_data
        Scaler_X_fold = StandardScaler()
        X_fold_train_scaled = Scaler_X_fold.fit_transform(X_fold_train)
        X_fold_val_scaled = Scaler_X_fold.transform(X_fold_val)
        X_fold_test_scaled = Scaler_X_fold.transform(X_fold_test)
        
        #Scale the y data
        Scaler_y_fold = StandardScaler()
        y_fold_train_scaled = Scaler_y_fold.fit_transform(y_fold_train.reshape(-1, 1)).flatten()
        y_fold_val_scaled = Scaler_y_fold.transform(y_fold_val.reshape(-1, 1)).flatten()
        y_fold_test_scaled = Scaler_y_fold.transform(y_fold_test.reshape(-1, 1)).flatten()
        
        #convert all data to tensors
        X_fold_train_tensor = torch.tensor(X_fold_train_scaled, dtype=torch.float32).to(device)
        y_fold_train_tensor = torch.tensor(y_fold_train_scaled, dtype=torch.float32).to(device)
        X_fold_val_tensor = torch.tensor(X_fold_val_scaled, dtype=torch.float32).to(device)
        y_fold_val_tensor = torch.tensor(y_fold_val_scaled, dtype=torch.float32).to(device)
        X_fold_test_tensor = torch.tensor(X_fold_test_scaled, dtype=torch.float32).to(device)
        y_fold_test_tensor = torch.tensor(y_fold_test_scaled, dtype=torch.float32).to(device)
        
        #convert tensors to datasets then dataloaders
        train_ds = TensorDataset(X_fold_train_tensor, y_fold_train_tensor)
        train_loader = DataLoader(train_ds, batch_size=batch_size, shuffle=True, generator=torch.Generator().manual_seed(42))
        val_ds = TensorDataset(X_fold_val_tensor, y_fold_val_tensor)
        val_loader = DataLoader(val_ds, batch_size=batch_size, shuffle=True, generator=torch.Generator().manual_seed(42)) 
        test_ds = TensorDataset(X_fold_test_tensor, y_fold_test_tensor)
        test_loader = DataLoader(test_ds, batch_size=batch_size, shuffle=False, generator=torch.Generator().manual_seed(42))    

        #initialize the model
        input_dim = X_fold_train_tensor.shape[1]
        model = DmaxNet(input_dim, hidden_layers, dropout_rate, activation).to(device)
        optimizer = torch.optim.Adam(model.parameters(), lr=lr, weight_decay=weight_decay)
        scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, patience=patience // 3, factor=0.5)
        criterion = nn.MSELoss()
        
        
        best_val_loss = float("inf")
        best_state = None
        wait = 0
        
        for epoch in range(1000):

            train_loss = train_one_epoch(model, train_loader, optimizer, criterion, device)
            val_loss = evaluate(model, val_loader, criterion, device)
            if epoch % 10 == 0:
                print(f"  Epoch {epoch}... Train Loss: {train_loss:.4f}, Val Loss: {val_loss:.4f}")
            scheduler.step(val_loss)
            
            if val_loss < best_val_loss:
                best_val_loss = val_loss
                best_state = {k: v.cpu().clone() for k, v in model.state_dict().items()}
                wait = 0
            else:
                wait += 1
                if wait >= patience:
                    break
        
        # Restore best model and evaluate on fold test set
        model.load_state_dict(best_state)
        
        #predict the fold test set and inverse transform the predictions and actuals back to original scale
        y_fold_test_pred_scaled, y_fold_test_actual_scaled = predict(model, test_loader, device)
        y_fold_test_pred = Scaler_y_fold.inverse_transform(y_fold_test_pred_scaled.reshape(-1, 1)).flatten()
        y_fold_test_actual = Scaler_y_fold.inverse_transform(y_fold_test_actual_scaled.reshape(-1, 1)).flatten()
        
        #calculate the fold mse, rmse, and mae and add to the list of fold metrics
        fold_mse = np.mean((y_fold_test_pred - y_fold_test_actual) ** 2)
        fold_rmse = np.sqrt(fold_mse)
        fold_mae = np.mean(np.abs(y_fold_test_pred - y_fold_test_actual))
        
        all_fold_mse.append(fold_mse)
        all_fold_rmse.append(fold_rmse)
        all_fold_mae.append(fold_mae)
        
        #print the fold metrics
        print(f"Fold {fold} - MSE: {fold_mse:.4f}, RMSE: {fold_rmse:.4f}, MAE: {fold_mae:.4f}")

    mean_rmse = np.mean(all_fold_rmse)
    mean_mse = np.mean(all_fold_mse)
    mean_mae = np.mean(all_fold_mae)
    print(f"\nMean CV MSE: {mean_mse:.4f}, Mean CV RMSE: {mean_rmse:.4f}, Mean CV MAE: {mean_mae:.4f}")
    return mean_rmse, sem(all_fold_rmse)

In [45]:
#initialize the ax client for the dmax_nn model
ax_client_dmax_nn = AxClient()
ax_client_dmax_nn.create_experiment(
    name="NN CBVF + CALPHAD to D_max Regression",
    parameters=[
        {
            "name": "dropout_rate",
            "type": "range",
            "bounds": [0.0, 0.5],
        },
        {
            "name": "activation",
            "type": "choice",
            "values": ["relu", "leaky_relu", "elu", "selu"],
            "is_ordered": False,
            "sort_values": False,
        },
        {
            "name": "weight_decay",
            "type": "range",
            "bounds": [1e-6, 1e-2],
            "log_scale": True,
        },
        {
            "name": "lr",
            "type": "range",
            "bounds": [1e-5, 1e-2],
            "log_scale": True,
        },
        {
            "name": "batch_size",
            "type": "choice",
            "values": [32, 64, 128, 256],
            "is_ordered": True,
            "sort_values": True,
        },
        {
            "name": "early_stopping_patience",
            "type": "range",
            "bounds": [10, 50],
            "value_type": "int",
        },
        {
            "name": "n_layers",
            "type": "choice",
            "values": [1, 2, 3],
            "value_type": "int",
            "is_ordered": True,
            "sort_values": True,
        },
        {
            "name": "hidden1",
            "type": "choice",
            "values": [128, 256, 512, 1024, 2048],
            "value_type": "int",
            "is_ordered": True,
            "sort_values": True,

        },
        {
            "name": "hidden2",
            "type": "choice",
            "values": [64, 128, 256, 512, 1024],
            "value_type": "int",
            "is_ordered": True,
            "sort_values": True,

        },
        {
            "name": "hidden3",
            "type": "choice",
            "values": [32, 64, 128, 256, 512],
            "value_type": "int",
            "is_ordered": True,
            "sort_values": True,
        }
        
    ],
    objectives={"avg_rmse_nonzero": ObjectiveProperties(minimize=True)}
)

[INFO 04-02 09:54:19] ax.service.utils.instantiation: Inferred value type of ParameterType.FLOAT for parameter dropout_rate. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
[INFO 04-02 09:54:19] ax.service.utils.instantiation: Inferred value type of ParameterType.STRING for parameter activation. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
[INFO 04-02 09:54:19] ax.service.utils.instantiation: Inferred value type of ParameterType.FLOAT for parameter weight_decay. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
[INFO 04-02 09:54:19] ax.service.utils.instantiation: Inferred value type of ParameterType.FLOAT for parameter lr. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
[INFO 04-02 09:54:19] ax.service.utils.instantiation: Inferred value type of ParameterType.INT for parameter batch_size. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
[INFO 04-02 09:54:19] ax.generation_strategy.dispatch_utils: Using Generators.BOTORCH_MODULAR since there are more ordered parameters than there are categories for the unordered categorical parameters.
[INFO 04-02 09:54:19] ax.generation_strategy.dispatch_utils: Using Bayesian Optimization generation strategy: GenerationStrategy(name='Sobol+BoTorch', steps=[Sobol for 20 trials, BoTorch for subsequent trials]). Iterations after 20 will take longer to generate due to model-fitting.

In [46]:
#Perform the ax optimization loop for the dmax_nn model

#initialize the save path for the dmax_nn ax client
ax_client_dmax_nn_save_path = r"Ax_checkpoints\ax_client_dmax_nn_checkpoint.json"

#check if there is an existing checkpoint and load it, otherwise start a new optimization loop
try:
    ax_client_dmax_nn = AxClient.load_from_json_file(filepath=ax_client_dmax_nn_save_path)
    print(f"Loaded existing Ax client checkpoint from {ax_client_dmax_nn_save_path}")
    
    completed_trials = len(ax_client_dmax_nn.experiment.trials)
    target_trials = 100
    remaining_trials = target_trials - completed_trials
    
    print(f"Loaded {completed_trials} completed trials from ax_client_dmax_nn.json")
    print(f"Remaining trials to reach {target_trials}: {remaining_trials}")
    
    for i in range(remaining_trials):
        parameters, trial_index = ax_client_dmax_nn.get_next_trial()
        print(f"\nStarting trial {trial_index} with parameters: {parameters}")
        mean_rmse, rmse_sem = evaluate_parameters_NN_dmax(parameters)
        ax_client_dmax_nn.complete_trial(trial_index=trial_index, raw_data={"avg_rmse_nonzero": (mean_rmse, rmse_sem)})
        print(f"Completed trial {trial_index} with mean RMSE: {mean_rmse:.4f} ± {rmse_sem:.4f}")
        
        # Save the Ax client state after each trial
        ax_client_dmax_nn.save_to_json_file(filepath=ax_client_dmax_nn_save_path)
        print(f"Saved Ax client checkpoint")
    
    
except Exception as e:
    print(f"No existing checkpoint found, starting new optimization loop. Error: {e}")
    
    for i in range(100):
        parameters, trial_index = ax_client_dmax_nn.get_next_trial()
        print(f"\nStarting trial {trial_index} with parameters: {parameters}")
        mean_rmse, rmse_sem = evaluate_parameters_NN_dmax(parameters)
        ax_client_dmax_nn.complete_trial(trial_index=trial_index, raw_data={"avg_rmse_nonzero": (mean_rmse, rmse_sem)})
        print(f"Completed trial {trial_index} with mean RMSE: {mean_rmse:.4f} ± {rmse_sem:.4f}")
        
        # Save the Ax client state after each trial
        ax_client_dmax_nn.save_to_json_file(filepath=ax_client_dmax_nn_save_path)
        print(f"Saved Ax client checkpoint")

[INFO 04-02 09:54:21] ax.service.ax_client: Generated new trial 0 with parameters {'dropout_rate': 0.323671, 'weight_decay': 0.003794, 'lr': 0.003346, 'batch_size': 64, 'early_stopping_patience': 29, 'n_layers': 1, 'hidden1': 256, 'hidden2': 128, 'hidden3': 256, 'activation': 'elu'} using model Sobol.

No existing checkpoint found, starting new optimization loop. Error: [Errno 2] No such file or directory: 'Ax_checkpoints\\ax_client_dmax_nn_checkpoint.json'

Starting trial 0 with parameters: {'dropout_rate': 0.32367146015167236, 'weight_decay': 0.003793809981931019, 'lr': 0.003345730936533549, 'batch_size': 64, 'early_stopping_patience': 29, 'n_layers': 1, 'hidden1': 256, 'hidden2': 128, 'hidden3': 256, 'activation': 'elu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 20.6938, Val Loss: 7.6735
  Epoch 10... Train Loss: 0.4930, Val Loss: 0.4625
  Epoch 20... Train Loss: 0.5059, Val Loss: 0.5263
  Epoch 30... Train Loss: 0.4543, Val Loss: 0.3365
  Epoch 40... Train Loss: 0.3735, Val Loss: 0.3752
Fold 1 - MSE: 41.5238, RMSE: 6.4439, MAE: 4.3056
Starting fold 2...
  Epoch 0... Train Loss: 16.1146, Val Loss: 6.6206
  Epoch 10... Train Loss: 0.5687, Val Loss: 0.7827
  Epoch 20... Train Loss: 0.4337, Val Loss: 0.6551
  Epoch 30... Train Loss: 0.3941, Val Loss: 0.6522
  Epoch 40... Train Loss: 0.3718, Val Loss: 0.6034
  Epoch 50... Train Loss: 0.2979, Val Loss: 0.6072
Fold 2 - MSE: 62.8643, RMSE: 7.9287, MAE: 5.7921
Starting fold 3...
  Epoch 0... Train Loss: 13.8958, Val Loss: 4.2788
  Epoch 10... Train Loss: 0.5455, Val Loss: 0.7623
  Epoch 20... Train Loss: 0.3996, Val Loss: 0.5253
  Epoch 30... Train Loss: 0.3536, Val Loss: 0.4492
  Epoch 40... Train Loss: 0.3795, Val Loss: 0.4673
  Epoch 50... Train Loss: 0.3202, Val Loss: 0.4779
  Epoch 60... Train Loss: 0.3075, Val Loss: 0.4365
  Epoch 70... Train Loss: 0.2779, Val Loss: 0.5040
  Epoch 80... Train Loss: 0.2959, Val Loss: 0.4261
  Epoch 90... Train Loss: 0.2717, Val Loss: 0.4389
  Epoch 100... Train Loss: 0.2603, Val Loss: 0.4757
  Epoch 110... Train Loss: 0.2553, Val Loss: 0.4438
  Epoch 120... Train Loss: 0.2548, Val Loss: 0.4949
  Epoch 130... Train Loss: 0.2422, Val Loss: 0.4287
Fold 3 - MSE: 142.0677, RMSE: 11.9192, MAE: 7.1567
Starting fold 4...
  Epoch 0... Train Loss: 12.4740, Val Loss: 2.7800
  Epoch 10... Train Loss: 0.5627, Val Loss: 0.5079
  Epoch 20... Train Loss: 0.4518, Val Loss: 0.5780
  Epoch 30... Train Loss: 0.4724, Val Loss: 0.5347
  Epoch 40... Train Loss: 0.3796, Val Loss: 0.5357
  Epoch 50... Train Loss: 0.3240, Val Loss: 0.5541
Fold 4 - MSE: 33.3037, RMSE: 5.7709, MAE: 4.6248
Starting fold 5...
  Epoch 0... Train Loss: 10.4576, Val Loss: 3.9682
  Epoch 10... Train Loss: 0.5137, Val Loss: 1.0261
  Epoch 20... Train Loss: 0.4465, Val Loss: 0.8792
  Epoch 30... Train Loss: 0.4172, Val Loss: 1.0016
  Epoch 40... Train Loss: 0.4809, Val Loss: 0.8032
  Epoch 50... Train Loss: 0.3736, Val Loss: 0.9354
  Epoch 60... Train Loss: 0.3592, Val Loss: 0.9271

[INFO 04-02 09:54:33] ax.service.ax_client: Completed trial 0 with data: {'avg_rmse_nonzero': 7.378909}.
[INFO 04-02 09:54:33] ax.service.ax_client: Generated new trial 1 with parameters {'dropout_rate': 0.0562, 'weight_decay': 5e-05, 'lr': 1.9e-05, 'batch_size': 256, 'early_stopping_patience': 38, 'n_layers': 3, 'hidden1': 512, 'hidden2': 512, 'hidden3': 64, 'activation': 'relu'} using model Sobol.

Fold 5 - MSE: 23.3462, RMSE: 4.8318, MAE: 3.8941

Mean CV MSE: 60.6212, Mean CV RMSE: 7.3789, Mean CV MAE: 5.1547
Completed trial 0 with mean RMSE: 7.3789 ± 1.2423
Saved Ax client checkpoint

Starting trial 1 with parameters: {'dropout_rate': 0.05619959533214569, 'weight_decay': 4.9869540134627203e-05, 'lr': 1.9112885152396023e-05, 'batch_size': 256, 'early_stopping_patience': 38, 'n_layers': 3, 'hidden1': 512, 'hidden2': 512, 'hidden3': 64, 'activation': 'relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 1.2494, Val Loss: 0.9071
  Epoch 10... Train Loss: 0.4265, Val Loss: 0.5038
  Epoch 20... Train Loss: 0.3628, Val Loss: 0.2639
  Epoch 30... Train Loss: 0.2964, Val Loss: 0.3173
  Epoch 40... Train Loss: 0.2234, Val Loss: 0.2799
  Epoch 50... Train Loss: 0.3026, Val Loss: 0.2923
Fold 1 - MSE: 36.3759, RMSE: 6.0312, MAE: 4.2530
Starting fold 2...
  Epoch 0... Train Loss: 0.9090, Val Loss: 1.0626
  Epoch 10... Train Loss: 0.3368, Val Loss: 0.5440
  Epoch 20... Train Loss: 0.2001, Val Loss: 0.5169
  Epoch 30... Train Loss: 0.2089, Val Loss: 0.5234
  Epoch 40... Train Loss: 0.1692, Val Loss: 0.5137
  Epoch 50... Train Loss: 0.1713, Val Loss: 0.5118
  Epoch 60... Train Loss: 0.1662, Val Loss: 0.4703
  Epoch 70... Train Loss: 0.1751, Val Loss: 0.4829
  Epoch 80... Train Loss: 0.1529, Val Loss: 0.4809
  Epoch 90... Train Loss: 0.1717, Val Loss: 0.4854
  Epoch 100... Train Loss: 0.1581, Val Loss: 0.4822
  Epoch 110... Train Loss: 0.1382, Val Loss: 0.4890
Fold 2 - MSE: 28.6453, RMSE: 5.3521, MAE: 3.4387
Starting fold 3...
  Epoch 0... Train Loss: 1.0625, Val Loss: 1.1072
  Epoch 10... Train Loss: 0.3039, Val Loss: 0.4913
  Epoch 20... Train Loss: 0.2214, Val Loss: 0.4567
  Epoch 30... Train Loss: 0.2136, Val Loss: 0.4045
  Epoch 40... Train Loss: 0.1713, Val Loss: 0.3886
  Epoch 50... Train Loss: 0.1791, Val Loss: 0.3613
  Epoch 60... Train Loss: 0.1656, Val Loss: 0.3615
  Epoch 70... Train Loss: 0.1641, Val Loss: 0.3538
  Epoch 80... Train Loss: 0.1707, Val Loss: 0.3506
  Epoch 90... Train Loss: 0.1514, Val Loss: 0.3548
  Epoch 100... Train Loss: 0.1702, Val Loss: 0.3511
  Epoch 110... Train Loss: 0.1579, Val Loss: 0.3507
  Epoch 120... Train Loss: 0.1656, Val Loss: 0.3479
  Epoch 130... Train Loss: 0.1446, Val Loss: 0.3421
  Epoch 140... Train Loss: 0.1409, Val Loss: 0.3427
  Epoch 150... Train Loss: 0.1668, Val Loss: 0.3410
  Epoch 160... Train Loss: 0.1465, Val Loss: 0.3437
  Epoch 170... Train Loss: 0.1672, Val Loss: 0.3431
  Epoch 180... Train Loss: 0.1627, Val Loss: 0.3426
Fold 3 - MSE: 29.6786, RMSE: 5.4478, MAE: 3.8444
Starting fold 4...
  Epoch 0... Train Loss: 1.1193, Val Loss: 0.6975
  Epoch 10... Train Loss: 0.3066, Val Loss: 0.5774
  Epoch 20... Train Loss: 0.1610, Val Loss: 0.8375
  Epoch 30... Train Loss: 0.1718, Val Loss: 0.7739
  Epoch 40... Train Loss: 0.1508, Val Loss: 0.7296
Fold 4 - MSE: 37.3060, RMSE: 6.1079, MAE: 5.1140
Starting fold 5...
  Epoch 0... Train Loss: 0.9786, Val Loss: 1.4136
  Epoch 10... Train Loss: 0.2881, Val Loss: 0.8950
  Epoch 20... Train Loss: 0.2285, Val Loss: 0.7580
  Epoch 30... Train Loss: 0.1984, Val Loss: 0.8478
  Epoch 40... Train Loss: 0.1876, Val Loss: 0.8130
  Epoch 50... Train Loss: 0.1754, Val Loss: 0.8544
  Epoch 60... Train Loss: 0.1723, Val Loss: 0.8115
  Epoch 70... Train Loss: 0.1894, Val Loss: 0.8174
Fold 5 - MSE: 194.2319, RMSE: 13.9367, MAE: 12.4252

Mean CV MSE: 65.2475, Mean CV RMSE: 7.3751, Mean CV MAE: 5.8150

[INFO 04-02 09:54:43] ax.service.ax_client: Completed trial 1 with data: {'avg_rmse_nonzero': 7.37515}.
[INFO 04-02 09:54:43] ax.service.ax_client: Generated new trial 2 with parameters {'dropout_rate': 0.140552, 'weight_decay': 4e-06, 'lr': 0.000468, 'batch_size': 128, 'early_stopping_patience': 40, 'n_layers': 2, 'hidden1': 2048, 'hidden2': 512, 'hidden3': 512, 'activation': 'leaky_relu'} using model Sobol.

Completed trial 1 with mean RMSE: 7.3751 ± 1.6473
Saved Ax client checkpoint

Starting trial 2 with parameters: {'dropout_rate': 0.1405521985143423, 'weight_decay': 4.047408866332869e-06, 'lr': 0.00046791511116177933, 'batch_size': 128, 'early_stopping_patience': 40, 'n_layers': 2, 'hidden1': 2048, 'hidden2': 512, 'hidden3': 512, 'activation': 'leaky_relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 2.6954, Val Loss: 1.1386
  Epoch 10... Train Loss: 0.4090, Val Loss: 0.3768
  Epoch 20... Train Loss: 0.3321, Val Loss: 0.2986
  Epoch 30... Train Loss: 0.3014, Val Loss: 0.3172
  Epoch 40... Train Loss: 0.2669, Val Loss: 0.3009
  Epoch 50... Train Loss: 0.2874, Val Loss: 0.3395
  Epoch 60... Train Loss: 0.2553, Val Loss: 0.3036
  Epoch 70... Train Loss: 0.2732, Val Loss: 0.3252
Fold 1 - MSE: 41.3013, RMSE: 6.4266, MAE: 4.3415
Starting fold 2...
  Epoch 0... Train Loss: 1.6309, Val Loss: 0.9817
  Epoch 10... Train Loss: 0.3182, Val Loss: 0.7844
  Epoch 20... Train Loss: 0.2330, Val Loss: 0.3523
  Epoch 30... Train Loss: 0.2487, Val Loss: 0.4015
  Epoch 40... Train Loss: 0.1935, Val Loss: 0.6293
  Epoch 50... Train Loss: 0.1890, Val Loss: 0.4032
  Epoch 60... Train Loss: 0.1813, Val Loss: 0.3123
  Epoch 70... Train Loss: 0.1805, Val Loss: 0.3149
  Epoch 80... Train Loss: 0.1682, Val Loss: 0.3913
  Epoch 90... Train Loss: 0.1634, Val Loss: 0.2720
  Epoch 100... Train Loss: 0.1652, Val Loss: 0.3079
Fold 2 - MSE: 40.0881, RMSE: 6.3315, MAE: 3.7700
Starting fold 3...
  Epoch 0... Train Loss: 1.9761, Val Loss: 1.2485
  Epoch 10... Train Loss: 0.2991, Val Loss: 0.4807
  Epoch 20... Train Loss: 0.2440, Val Loss: 0.6543
  Epoch 30... Train Loss: 0.2424, Val Loss: 0.4872
  Epoch 40... Train Loss: 0.1981, Val Loss: 0.3468
  Epoch 50... Train Loss: 0.1855, Val Loss: 0.3613
  Epoch 60... Train Loss: 0.1739, Val Loss: 0.3386
  Epoch 70... Train Loss: 0.1689, Val Loss: 0.4592
  Epoch 80... Train Loss: 0.1663, Val Loss: 0.3050
  Epoch 90... Train Loss: 0.1701, Val Loss: 0.3400
  Epoch 100... Train Loss: 0.1793, Val Loss: 0.3415
  Epoch 110... Train Loss: 0.1682, Val Loss: 0.3733
Fold 3 - MSE: 42.1366, RMSE: 6.4913, MAE: 3.7305
Starting fold 4...
  Epoch 0... Train Loss: 1.7221, Val Loss: 1.1064
  Epoch 10... Train Loss: 0.2822, Val Loss: 0.4104
  Epoch 20... Train Loss: 0.1977, Val Loss: 0.6400
  Epoch 30... Train Loss: 0.1535, Val Loss: 0.3726
  Epoch 40... Train Loss: 0.1505, Val Loss: 0.5177
  Epoch 50... Train Loss: 0.1521, Val Loss: 0.3777
  Epoch 60... Train Loss: 0.1432, Val Loss: 0.3664
  Epoch 70... Train Loss: 0.1309, Val Loss: 0.5438
  Epoch 80... Train Loss: 0.1300, Val Loss: 0.5005
Fold 4 - MSE: 33.3186, RMSE: 5.7722, MAE: 4.7436
Starting fold 5...
  Epoch 0... Train Loss: 1.8181, Val Loss: 1.5199
  Epoch 10... Train Loss: 0.3249, Val Loss: 0.7466
  Epoch 20... Train Loss: 0.3235, Val Loss: 0.7094
  Epoch 30... Train Loss: 0.2695, Val Loss: 0.9809
  Epoch 40... Train Loss: 0.2768, Val Loss: 0.8200
  Epoch 50... Train Loss: 0.2193, Val Loss: 0.6174

[INFO 04-02 09:54:53] ax.service.ax_client: Completed trial 2 with data: {'avg_rmse_nonzero': 5.438161}.

  Epoch 60... Train Loss: 0.2108, Val Loss: 0.7369
Fold 5 - MSE: 4.7054, RMSE: 2.1692, MAE: 1.6717

Mean CV MSE: 32.3100, Mean CV RMSE: 5.4382, Mean CV MAE: 3.6515
Completed trial 2 with mean RMSE: 5.4382 ± 0.8271
Saved Ax client checkpoint

[INFO 04-02 09:54:53] ax.service.ax_client: Generated new trial 3 with parameters {'dropout_rate': 0.497132, 'weight_decay': 0.000552, 'lr': 5.9e-05, 'batch_size': 32, 'early_stopping_patience': 10, 'n_layers': 1, 'hidden1': 128, 'hidden2': 128, 'hidden3': 64, 'activation': 'selu'} using model Sobol.

Starting trial 3 with parameters: {'dropout_rate': 0.497131556738168, 'weight_decay': 0.0005521011445799135, 'lr': 5.9206442869065546e-05, 'batch_size': 32, 'early_stopping_patience': 10, 'n_layers': 1, 'hidden1': 128, 'hidden2': 128, 'hidden3': 64, 'activation': 'selu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 1.5291, Val Loss: 0.8761
  Epoch 10... Train Loss: 0.6823, Val Loss: 0.4551
  Epoch 20... Train Loss: 0.6312, Val Loss: 0.5711
  Epoch 30... Train Loss: 0.5816, Val Loss: 0.3272
  Epoch 40... Train Loss: 0.5703, Val Loss: 0.3474
Fold 1 - MSE: 51.7445, RMSE: 7.1934, MAE: 4.9537
Starting fold 2...
  Epoch 0... Train Loss: 1.7660, Val Loss: 1.1472
  Epoch 10... Train Loss: 0.7533, Val Loss: 0.8356
  Epoch 20... Train Loss: 0.7126, Val Loss: 0.6782
  Epoch 30... Train Loss: 0.5211, Val Loss: 0.6206
  Epoch 40... Train Loss: 0.5055, Val Loss: 0.5610
Fold 2 - MSE: 68.3505, RMSE: 8.2674, MAE: 6.1399
Starting fold 3...
  Epoch 0... Train Loss: 1.4821, Val Loss: 1.9504
  Epoch 10... Train Loss: 0.8374, Val Loss: 0.7850
  Epoch 20... Train Loss: 0.5701, Val Loss: 0.5281
  Epoch 30... Train Loss: 0.5449, Val Loss: 0.4468
  Epoch 40... Train Loss: 0.5219, Val Loss: 0.4647
Fold 3 - MSE: 67.9453, RMSE: 8.2429, MAE: 5.5426
Starting fold 4...
  Epoch 0... Train Loss: 1.8487, Val Loss: 1.8204
  Epoch 10... Train Loss: 0.7452, Val Loss: 0.7976
Fold 4 - MSE: 58.6777, RMSE: 7.6601, MAE: 5.5091
Starting fold 5...
  Epoch 0... Train Loss: 1.7164, Val Loss: 1.6398
  Epoch 10... Train Loss: 0.8908, Val Loss: 0.8320
  Epoch 20... Train Loss: 0.6215, Val Loss: 0.7453
  Epoch 30... Train Loss: 0.5093, Val Loss: 0.7444
  Epoch 40... Train Loss: 0.5389, Val Loss: 0.7566
  Epoch 50... Train Loss: 0.5259, Val Loss: 0.7738

[INFO 04-02 09:55:06] ax.service.ax_client: Completed trial 3 with data: {'avg_rmse_nonzero': 6.970387}.
[INFO 04-02 09:55:06] ax.service.ax_client: Generated new trial 4 with parameters {'dropout_rate': 0.37796, 'weight_decay': 0.001651, 'lr': 0.001666, 'batch_size': 128, 'early_stopping_patience': 48, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 64, 'hidden3': 512, 'activation': 'selu'} using model Sobol.

Fold 5 - MSE: 12.1669, RMSE: 3.4881, MAE: 2.7754

Mean CV MSE: 51.7770, Mean CV RMSE: 6.9704, Mean CV MAE: 4.9841
Completed trial 3 with mean RMSE: 6.9704 ± 0.8931
Saved Ax client checkpoint

Starting trial 4 with parameters: {'dropout_rate': 0.37795967794954777, 'weight_decay': 0.0016513290019417612, 'lr': 0.001666306180578289, 'batch_size': 128, 'early_stopping_patience': 48, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 64, 'hidden3': 512, 'activation': 'selu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 24.9514, Val Loss: 16.8406
  Epoch 10... Train Loss: 0.8560, Val Loss: 0.7737
  Epoch 20... Train Loss: 0.6098, Val Loss: 0.6272
  Epoch 30... Train Loss: 0.5444, Val Loss: 0.5473
  Epoch 40... Train Loss: 0.4427, Val Loss: 0.4741
  Epoch 50... Train Loss: 0.5141, Val Loss: 0.3894
  Epoch 60... Train Loss: 0.4432, Val Loss: 0.3905
  Epoch 70... Train Loss: 0.3926, Val Loss: 0.4281
  Epoch 80... Train Loss: 0.3784, Val Loss: 0.4187
  Epoch 90... Train Loss: 0.3730, Val Loss: 0.3904
  Epoch 100... Train Loss: 0.3560, Val Loss: 0.3980
  Epoch 110... Train Loss: 0.3326, Val Loss: 0.3719
  Epoch 120... Train Loss: 0.3896, Val Loss: 0.4409
  Epoch 130... Train Loss: 0.3158, Val Loss: 0.4180
Fold 1 - MSE: 47.3612, RMSE: 6.8819, MAE: 4.7773
Starting fold 2...
  Epoch 0... Train Loss: 23.0177, Val Loss: 63.0091
  Epoch 10... Train Loss: 0.7025, Val Loss: 1.3324
  Epoch 20... Train Loss: 0.5034, Val Loss: 0.8476
  Epoch 30... Train Loss: 0.4613, Val Loss: 0.7236
  Epoch 40... Train Loss: 0.4237, Val Loss: 0.6488
  Epoch 50... Train Loss: 0.3884, Val Loss: 0.6410
  Epoch 60... Train Loss: 0.3742, Val Loss: 0.3545
  Epoch 70... Train Loss: 0.3400, Val Loss: 0.4251
  Epoch 80... Train Loss: 0.3191, Val Loss: 0.4747
  Epoch 90... Train Loss: 0.3146, Val Loss: 0.3770
  Epoch 100... Train Loss: 0.3099, Val Loss: 0.3284
  Epoch 110... Train Loss: 0.2844, Val Loss: 0.3938
Fold 2 - MSE: 40.2419, RMSE: 6.3436, MAE: 3.7462
Starting fold 3...
  Epoch 0... Train Loss: 22.8218, Val Loss: 53.4703
  Epoch 10... Train Loss: 0.6474, Val Loss: 0.8656
  Epoch 20... Train Loss: 0.5175, Val Loss: 0.6202
  Epoch 30... Train Loss: 0.4837, Val Loss: 0.4425
  Epoch 40... Train Loss: 0.3957, Val Loss: 0.4556
  Epoch 50... Train Loss: 0.3605, Val Loss: 0.4864
  Epoch 60... Train Loss: 0.3808, Val Loss: 0.4625
  Epoch 70... Train Loss: 0.3137, Val Loss: 0.5392
  Epoch 80... Train Loss: 0.3129, Val Loss: 0.3724
  Epoch 90... Train Loss: 0.2913, Val Loss: 0.4307
  Epoch 100... Train Loss: 0.2946, Val Loss: 0.4613
  Epoch 110... Train Loss: 0.2823, Val Loss: 0.4237
  Epoch 120... Train Loss: 0.2619, Val Loss: 0.5254
Fold 3 - MSE: 52.7333, RMSE: 7.2618, MAE: 4.3928
Starting fold 4...
  Epoch 0... Train Loss: 21.9402, Val Loss: 55.7701
  Epoch 10... Train Loss: 0.6897, Val Loss: 0.5323
  Epoch 20... Train Loss: 0.5393, Val Loss: 0.6777
  Epoch 30... Train Loss: 0.4255, Val Loss: 0.4193
  Epoch 40... Train Loss: 0.3974, Val Loss: 0.5418
  Epoch 50... Train Loss: 0.3505, Val Loss: 0.4124
  Epoch 60... Train Loss: 0.3052, Val Loss: 0.4339
  Epoch 70... Train Loss: 0.2823, Val Loss: 0.5258
  Epoch 80... Train Loss: 0.2614, Val Loss: 0.5194
Fold 4 - MSE: 37.2125, RMSE: 6.1002, MAE: 4.9552
Starting fold 5...
  Epoch 0... Train Loss: 15.5875, Val Loss: 8.4835
  Epoch 10... Train Loss: 0.7245, Val Loss: 0.9878
  Epoch 20... Train Loss: 0.5150, Val Loss: 0.7918
  Epoch 30... Train Loss: 0.4392, Val Loss: 1.2128
  Epoch 40... Train Loss: 0.4503, Val Loss: 0.9083
  Epoch 50... Train Loss: 0.3677, Val Loss: 0.8186
  Epoch 60... Train Loss: 0.3720, Val Loss: 0.8119
  Epoch 70... Train Loss: 0.3457, Val Loss: 0.7393
  Epoch 80... Train Loss: 0.3335, Val Loss: 0.7588
  Epoch 90... Train Loss: 0.3590, Val Loss: 0.8139
  Epoch 100... Train Loss: 0.2799, Val Loss: 1.1279
  Epoch 110... Train Loss: 0.2907, Val Loss: 1.1005
  Epoch 120... Train Loss: 0.2687, Val Loss: 0.7642
  Epoch 130... Train Loss: 0.2941, Val Loss: 0.6866
  Epoch 140... Train Loss: 0.2899, Val Loss: 0.7057
  Epoch 150... Train Loss: 0.2577, Val Loss: 1.0744

[INFO 04-02 09:55:23] ax.service.ax_client: Completed trial 4 with data: {'avg_rmse_nonzero': 6.268815}.
[INFO 04-02 09:55:23] ax.service.ax_client: Generated new trial 5 with parameters {'dropout_rate': 0.23631, 'weight_decay': 1.2e-05, 'lr': 0.000223, 'batch_size': 32, 'early_stopping_patience': 16, 'n_layers': 2, 'hidden1': 256, 'hidden2': 1024, 'hidden3': 128, 'activation': 'relu'} using model Sobol.

  Epoch 160... Train Loss: 0.2253, Val Loss: 1.1114
Fold 5 - MSE: 22.6244, RMSE: 4.7565, MAE: 4.2845

Mean CV MSE: 40.0346, Mean CV RMSE: 6.2688, Mean CV MAE: 4.4312
Completed trial 4 with mean RMSE: 6.2688 ± 0.4291
Saved Ax client checkpoint

Starting trial 5 with parameters: {'dropout_rate': 0.2363098976202309, 'weight_decay': 1.1688615369247098e-05, 'lr': 0.0002225508010854438, 'batch_size': 32, 'early_stopping_patience': 16, 'n_layers': 2, 'hidden1': 256, 'hidden2': 1024, 'hidden3': 128, 'activation': 'relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 1.0963, Val Loss: 0.7484
  Epoch 10... Train Loss: 0.4745, Val Loss: 0.3387
  Epoch 20... Train Loss: 0.4111, Val Loss: 0.5038
Fold 1 - MSE: 39.5936, RMSE: 6.2923, MAE: 4.2588
Starting fold 2...
  Epoch 0... Train Loss: 1.1240, Val Loss: 1.0905
  Epoch 10... Train Loss: 0.4461, Val Loss: 0.6638
  Epoch 20... Train Loss: 0.3588, Val Loss: 0.4819
  Epoch 30... Train Loss: 0.2869, Val Loss: 0.4568
  Epoch 40... Train Loss: 0.2623, Val Loss: 0.4909
Fold 2 - MSE: 41.1291, RMSE: 6.4132, MAE: 3.8056
Starting fold 3...
  Epoch 0... Train Loss: 1.0433, Val Loss: 1.6712
  Epoch 10... Train Loss: 0.4615, Val Loss: 0.8814
  Epoch 20... Train Loss: 0.3250, Val Loss: 0.4423
  Epoch 30... Train Loss: 0.2647, Val Loss: 0.3792
  Epoch 40... Train Loss: 0.2325, Val Loss: 0.3797
  Epoch 50... Train Loss: 0.2430, Val Loss: 0.3629
  Epoch 60... Train Loss: 0.2371, Val Loss: 0.3461
  Epoch 70... Train Loss: 0.2171, Val Loss: 0.3522
Fold 3 - MSE: 48.8399, RMSE: 6.9886, MAE: 3.8457
Starting fold 4...
  Epoch 0... Train Loss: 0.9948, Val Loss: 1.6335
  Epoch 10... Train Loss: 0.4035, Val Loss: 0.6221
  Epoch 20... Train Loss: 0.2586, Val Loss: 0.5291
  Epoch 30... Train Loss: 0.2205, Val Loss: 0.5303
Fold 4 - MSE: 35.4382, RMSE: 5.9530, MAE: 4.8652
Starting fold 5...
  Epoch 0... Train Loss: 1.0454, Val Loss: 2.0190
  Epoch 10... Train Loss: 0.4548, Val Loss: 0.7742
  Epoch 20... Train Loss: 0.3517, Val Loss: 0.7321
  Epoch 30... Train Loss: 0.2594, Val Loss: 0.6744
  Epoch 40... Train Loss: 0.2697, Val Loss: 0.7176
  Epoch 50... Train Loss: 0.2512, Val Loss: 0.8436
  Epoch 60... Train Loss: 0.2575, Val Loss: 0.7023

[INFO 04-02 09:55:41] ax.service.ax_client: Completed trial 5 with data: {'avg_rmse_nonzero': 5.610293}.
[INFO 04-02 09:55:41] ax.service.ax_client: Generated new trial 6 with parameters {'dropout_rate': 0.06993, 'weight_decay': 2e-06, 'lr': 0.004761, 'batch_size': 64, 'early_stopping_patience': 24, 'n_layers': 1, 'hidden1': 512, 'hidden2': 256, 'hidden3': 128, 'activation': 'relu'} using model Sobol.

Fold 5 - MSE: 5.7810, RMSE: 2.4044, MAE: 2.0344

Mean CV MSE: 34.1563, Mean CV RMSE: 5.6103, Mean CV MAE: 3.7620
Completed trial 5 with mean RMSE: 5.6103 ± 0.8187
Saved Ax client checkpoint

Starting trial 6 with parameters: {'dropout_rate': 0.06992986286059022, 'weight_decay': 1.6633439953578884e-06, 'lr': 0.004761387663707257, 'batch_size': 64, 'early_stopping_patience': 24, 'n_layers': 1, 'hidden1': 512, 'hidden2': 256, 'hidden3': 128, 'activation': 'relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 8.4462, Val Loss: 15.1174
  Epoch 10... Train Loss: 0.4355, Val Loss: 0.4050
  Epoch 20... Train Loss: 0.3912, Val Loss: 0.3646
  Epoch 30... Train Loss: 0.3054, Val Loss: 0.2887
Fold 1 - MSE: 39.4801, RMSE: 6.2833, MAE: 4.3277
Starting fold 2...
  Epoch 0... Train Loss: 4.8049, Val Loss: 3.9841
  Epoch 10... Train Loss: 0.4857, Val Loss: 0.7333
  Epoch 20... Train Loss: 0.4320, Val Loss: 0.5814
  Epoch 30... Train Loss: 0.2619, Val Loss: 0.4590
  Epoch 40... Train Loss: 0.2377, Val Loss: 0.4964
  Epoch 50... Train Loss: 0.1950, Val Loss: 0.4456
  Epoch 60... Train Loss: 0.2084, Val Loss: 0.3810
  Epoch 70... Train Loss: 0.2308, Val Loss: 0.3978
  Epoch 80... Train Loss: 0.1982, Val Loss: 0.4066
  Epoch 90... Train Loss: 0.1969, Val Loss: 0.3527
  Epoch 100... Train Loss: 0.1735, Val Loss: 0.3840
Fold 2 - MSE: 47.3804, RMSE: 6.8833, MAE: 4.0675
Starting fold 3...
  Epoch 0... Train Loss: 5.4748, Val Loss: 5.1036
  Epoch 10... Train Loss: 0.3764, Val Loss: 0.5271
  Epoch 20... Train Loss: 0.4391, Val Loss: 0.4449
  Epoch 30... Train Loss: 0.2338, Val Loss: 0.3823
  Epoch 40... Train Loss: 0.2300, Val Loss: 0.3855
  Epoch 50... Train Loss: 0.2103, Val Loss: 0.3942
  Epoch 60... Train Loss: 0.2016, Val Loss: 0.3605
  Epoch 70... Train Loss: 0.1785, Val Loss: 0.4184
  Epoch 80... Train Loss: 0.1802, Val Loss: 0.3431
  Epoch 90... Train Loss: 0.1889, Val Loss: 0.3661
Fold 3 - MSE: 77.1314, RMSE: 8.7825, MAE: 5.1324
Starting fold 4...
  Epoch 0... Train Loss: 6.0659, Val Loss: 4.1147
  Epoch 10... Train Loss: 0.3875, Val Loss: 0.4798
  Epoch 20... Train Loss: 0.2621, Val Loss: 0.5428
  Epoch 30... Train Loss: 0.2046, Val Loss: 0.4513
  Epoch 40... Train Loss: 0.1703, Val Loss: 0.4750
  Epoch 50... Train Loss: 0.1718, Val Loss: 0.4375
  Epoch 60... Train Loss: 0.1503, Val Loss: 0.4335
  Epoch 70... Train Loss: 0.1486, Val Loss: 0.4970
  Epoch 80... Train Loss: 0.1495, Val Loss: 0.4666
  Epoch 90... Train Loss: 0.1442, Val Loss: 0.4254
  Epoch 100... Train Loss: 0.1461, Val Loss: 0.5145
  Epoch 110... Train Loss: 0.1396, Val Loss: 0.5229
  Epoch 120... Train Loss: 0.1345, Val Loss: 0.4848
Fold 4 - MSE: 25.5357, RMSE: 5.0533, MAE: 4.1221
Starting fold 5...
  Epoch 0... Train Loss: 5.5731, Val Loss: 3.5194
  Epoch 10... Train Loss: 0.4157, Val Loss: 1.1286
  Epoch 20... Train Loss: 0.3108, Val Loss: 0.7999
  Epoch 30... Train Loss: 0.2789, Val Loss: 0.9540
  Epoch 40... Train Loss: 0.3416, Val Loss: 0.7097
  Epoch 50... Train Loss: 0.3309, Val Loss: 0.7861
  Epoch 60... Train Loss: 0.2166, Val Loss: 0.7826
  Epoch 70... Train Loss: 0.2082, Val Loss: 0.6968
  Epoch 80... Train Loss: 0.2043, Val Loss: 0.7291
  Epoch 90... Train Loss: 0.2211, Val Loss: 0.7528
  Epoch 100... Train Loss: 0.1914, Val Loss: 0.8223

[INFO 04-02 09:55:57] ax.service.ax_client: Completed trial 6 with data: {'avg_rmse_nonzero': 6.705387}.
[INFO 04-02 09:55:57] ax.service.ax_client: Generated new trial 7 with parameters {'dropout_rate': 0.302152, 'weight_decay': 0.000131, 'lr': 3.2e-05, 'batch_size': 256, 'early_stopping_patience': 35, 'n_layers': 2, 'hidden1': 1024, 'hidden2': 256, 'hidden3': 32, 'activation': 'relu'} using model Sobol.

Fold 5 - MSE: 42.5696, RMSE: 6.5245, MAE: 5.9698

Mean CV MSE: 46.4195, Mean CV RMSE: 6.7054, Mean CV MAE: 4.7239
Completed trial 6 with mean RMSE: 6.7054 ± 0.6036
Saved Ax client checkpoint

Starting trial 7 with parameters: {'dropout_rate': 0.30215200409293175, 'weight_decay': 0.0001310176254724432, 'lr': 3.196919473270988e-05, 'batch_size': 256, 'early_stopping_patience': 35, 'n_layers': 2, 'hidden1': 1024, 'hidden2': 256, 'hidden3': 32, 'activation': 'relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 1.4471, Val Loss: 0.8509
  Epoch 10... Train Loss: 0.6114, Val Loss: 0.5117
  Epoch 20... Train Loss: 0.4920, Val Loss: 0.3511
  Epoch 30... Train Loss: 0.4136, Val Loss: 0.4397
  Epoch 40... Train Loss: 0.3075, Val Loss: 0.3199
  Epoch 50... Train Loss: 0.4504, Val Loss: 0.3805
  Epoch 60... Train Loss: 0.4150, Val Loss: 0.3260
  Epoch 70... Train Loss: 0.3246, Val Loss: 0.3436
Fold 1 - MSE: 41.5821, RMSE: 6.4484, MAE: 4.3853
Starting fold 2...
  Epoch 0... Train Loss: 1.0361, Val Loss: 0.9494
  Epoch 10... Train Loss: 0.5017, Val Loss: 0.7105
  Epoch 20... Train Loss: 0.3533, Val Loss: 0.6752
  Epoch 30... Train Loss: 0.3765, Val Loss: 0.6050
  Epoch 40... Train Loss: 0.3050, Val Loss: 0.5819
  Epoch 50... Train Loss: 0.3054, Val Loss: 0.5665
  Epoch 60... Train Loss: 0.2955, Val Loss: 0.5249
  Epoch 70... Train Loss: 0.3079, Val Loss: 0.5087
  Epoch 80... Train Loss: 0.2784, Val Loss: 0.4861
  Epoch 90... Train Loss: 0.2759, Val Loss: 0.5051
  Epoch 100... Train Loss: 0.2707, Val Loss: 0.5054
  Epoch 110... Train Loss: 0.2409, Val Loss: 0.4991
Fold 2 - MSE: 64.8914, RMSE: 8.0555, MAE: 6.4927
Starting fold 3...
  Epoch 0... Train Loss: 1.1592, Val Loss: 1.0055
  Epoch 10... Train Loss: 0.4407, Val Loss: 0.4979
  Epoch 20... Train Loss: 0.3506, Val Loss: 0.4448
  Epoch 30... Train Loss: 0.3156, Val Loss: 0.4026
  Epoch 40... Train Loss: 0.3041, Val Loss: 0.3829
  Epoch 50... Train Loss: 0.2732, Val Loss: 0.4315
  Epoch 60... Train Loss: 0.2694, Val Loss: 0.3643
  Epoch 70... Train Loss: 0.2711, Val Loss: 0.3684
  Epoch 80... Train Loss: 0.2873, Val Loss: 0.3714
  Epoch 90... Train Loss: 0.2432, Val Loss: 0.3826
Fold 3 - MSE: 41.5363, RMSE: 6.4449, MAE: 3.9319
Starting fold 4...
  Epoch 0... Train Loss: 0.9825, Val Loss: 0.6302
  Epoch 10... Train Loss: 0.3959, Val Loss: 0.5513
  Epoch 20... Train Loss: 0.3113, Val Loss: 0.5775
  Epoch 30... Train Loss: 0.3125, Val Loss: 0.5790
  Epoch 40... Train Loss: 0.2783, Val Loss: 0.6807
Fold 4 - MSE: 40.3346, RMSE: 6.3510, MAE: 4.8309
Starting fold 5...
  Epoch 0... Train Loss: 1.0815, Val Loss: 1.3110
  Epoch 10... Train Loss: 0.4999, Val Loss: 0.9441
  Epoch 20... Train Loss: 0.3567, Val Loss: 0.8584
  Epoch 30... Train Loss: 0.3218, Val Loss: 0.8119
  Epoch 40... Train Loss: 0.3374, Val Loss: 0.7574
  Epoch 50... Train Loss: 0.3007, Val Loss: 0.8078
  Epoch 60... Train Loss: 0.2936, Val Loss: 0.8073

[INFO 04-02 09:56:04] ax.service.ax_client: Completed trial 7 with data: {'avg_rmse_nonzero': 7.249822}.
[INFO 04-02 09:56:04] ax.service.ax_client: Generated new trial 8 with parameters {'dropout_rate': 0.267472, 'weight_decay': 0.000802, 'lr': 0.001145, 'batch_size': 128, 'early_stopping_patience': 48, 'n_layers': 1, 'hidden1': 1024, 'hidden2': 128, 'hidden3': 128, 'activation': 'elu'} using model Sobol.

  Epoch 70... Train Loss: 0.2917, Val Loss: 0.7968
Fold 5 - MSE: 80.0910, RMSE: 8.9494, MAE: 7.5773

Mean CV MSE: 53.6871, Mean CV RMSE: 7.2498, Mean CV MAE: 5.4436
Completed trial 7 with mean RMSE: 7.2498 ± 0.5308
Saved Ax client checkpoint

Starting trial 8 with parameters: {'dropout_rate': 0.2674719709903002, 'weight_decay': 0.000802299131548133, 'lr': 0.0011453541238261615, 'batch_size': 128, 'early_stopping_patience': 48, 'n_layers': 1, 'hidden1': 1024, 'hidden2': 128, 'hidden3': 128, 'activation': 'elu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 24.0018, Val Loss: 30.5439
  Epoch 10... Train Loss: 0.7153, Val Loss: 0.7747
  Epoch 20... Train Loss: 0.4262, Val Loss: 0.5297
  Epoch 30... Train Loss: 0.3984, Val Loss: 0.4575
  Epoch 40... Train Loss: 0.3956, Val Loss: 0.4212
  Epoch 50... Train Loss: 0.4032, Val Loss: 0.3876
  Epoch 60... Train Loss: 0.3591, Val Loss: 0.4133
  Epoch 70... Train Loss: 0.3419, Val Loss: 0.4152
  Epoch 80... Train Loss: 0.3584, Val Loss: 0.4504
  Epoch 90... Train Loss: 0.3292, Val Loss: 0.4719
Fold 1 - MSE: 46.9864, RMSE: 6.8547, MAE: 4.6965
Starting fold 2...
  Epoch 0... Train Loss: 22.2590, Val Loss: 26.3903
  Epoch 10... Train Loss: 0.5234, Val Loss: 1.2768
  Epoch 20... Train Loss: 0.3926, Val Loss: 0.8256
  Epoch 30... Train Loss: 0.3792, Val Loss: 0.8406
  Epoch 40... Train Loss: 0.3462, Val Loss: 0.6614
  Epoch 50... Train Loss: 0.3195, Val Loss: 0.6730
  Epoch 60... Train Loss: 0.3088, Val Loss: 0.4164
  Epoch 70... Train Loss: 0.3060, Val Loss: 0.4197
  Epoch 80... Train Loss: 0.2814, Val Loss: 0.5109
  Epoch 90... Train Loss: 0.2761, Val Loss: 0.4316
  Epoch 100... Train Loss: 0.2592, Val Loss: 0.3910
  Epoch 110... Train Loss: 0.2350, Val Loss: 0.4259
Fold 2 - MSE: 71.6699, RMSE: 8.4658, MAE: 6.5702
Starting fold 3...
  Epoch 0... Train Loss: 20.4517, Val Loss: 52.7129
  Epoch 10... Train Loss: 0.5026, Val Loss: 0.6800
  Epoch 20... Train Loss: 0.3879, Val Loss: 0.5016
  Epoch 30... Train Loss: 0.3562, Val Loss: 0.4201
  Epoch 40... Train Loss: 0.3382, Val Loss: 0.4248
  Epoch 50... Train Loss: 0.3103, Val Loss: 0.4332
  Epoch 60... Train Loss: 0.3041, Val Loss: 0.4252
  Epoch 70... Train Loss: 0.2733, Val Loss: 0.5617
  Epoch 80... Train Loss: 0.2863, Val Loss: 0.3918
  Epoch 90... Train Loss: 0.2713, Val Loss: 0.4490
  Epoch 100... Train Loss: 0.2557, Val Loss: 0.4742
  Epoch 110... Train Loss: 0.2448, Val Loss: 0.4411
  Epoch 120... Train Loss: 0.2418, Val Loss: 0.5237
Fold 3 - MSE: 105.4779, RMSE: 10.2702, MAE: 6.1927
Starting fold 4...
  Epoch 0... Train Loss: 28.4467, Val Loss: 20.3964
  Epoch 10... Train Loss: 0.5079, Val Loss: 0.5937
  Epoch 20... Train Loss: 0.4062, Val Loss: 0.8231
  Epoch 30... Train Loss: 0.3762, Val Loss: 0.8317
  Epoch 40... Train Loss: 0.3276, Val Loss: 1.0248
  Epoch 50... Train Loss: 0.3150, Val Loss: 0.8961
Fold 4 - MSE: 47.6230, RMSE: 6.9009, MAE: 5.5798
Starting fold 5...
  Epoch 0... Train Loss: 23.9155, Val Loss: 11.8907
  Epoch 10... Train Loss: 0.5488, Val Loss: 0.9013
  Epoch 20... Train Loss: 0.3937, Val Loss: 0.7885
  Epoch 30... Train Loss: 0.3800, Val Loss: 1.2734
  Epoch 40... Train Loss: 0.3800, Val Loss: 0.8777
  Epoch 50... Train Loss: 0.3328, Val Loss: 0.9052
  Epoch 60... Train Loss: 0.3488, Val Loss: 0.8969
  Epoch 70... Train Loss: 0.3152, Val Loss: 0.7397
  Epoch 80... Train Loss: 0.3332, Val Loss: 0.7384
  Epoch 90... Train Loss: 0.3220, Val Loss: 0.7637
  Epoch 100... Train Loss: 0.2903, Val Loss: 1.0460
  Epoch 110... Train Loss: 0.2726, Val Loss: 1.0930
  Epoch 120... Train Loss: 0.2766, Val Loss: 0.7699
  Epoch 130... Train Loss: 0.2673, Val Loss: 0.6879
Fold 5 - MSE: 6.1826, RMSE: 2.4865, MAE: 2.0025

Mean CV MSE: 55.5880, Mean CV RMSE: 6.9956, Mean CV MAE: 5.0083

[INFO 04-02 09:56:15] ax.service.ax_client: Completed trial 8 with data: {'avg_rmse_nonzero': 6.995628}.
[INFO 04-02 09:56:15] ax.service.ax_client: Generated new trial 9 with parameters {'dropout_rate': 0.096774, 'weight_decay': 6e-06, 'lr': 0.000137, 'batch_size': 32, 'early_stopping_patience': 18, 'n_layers': 3, 'hidden1': 512, 'hidden2': 512, 'hidden3': 512, 'activation': 'leaky_relu'} using model Sobol.

Completed trial 8 with mean RMSE: 6.9956 ± 1.2893
Saved Ax client checkpoint

Starting trial 9 with parameters: {'dropout_rate': 0.09677422465756536, 'weight_decay': 5.679319470023173e-06, 'lr': 0.0001365351190162153, 'batch_size': 32, 'early_stopping_patience': 18, 'n_layers': 3, 'hidden1': 512, 'hidden2': 512, 'hidden3': 512, 'activation': 'leaky_relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 0.8862, Val Loss: 0.7712
  Epoch 10... Train Loss: 0.3911, Val Loss: 0.2781
  Epoch 20... Train Loss: 0.3771, Val Loss: 0.3194
Fold 1 - MSE: 41.1863, RMSE: 6.4177, MAE: 4.4269
Starting fold 2...
  Epoch 0... Train Loss: 0.8729, Val Loss: 0.7446
  Epoch 10... Train Loss: 0.3856, Val Loss: 0.6239
  Epoch 20... Train Loss: 0.3063, Val Loss: 0.4589
  Epoch 30... Train Loss: 0.2416, Val Loss: 0.4997
  Epoch 40... Train Loss: 0.2388, Val Loss: 0.4702
  Epoch 50... Train Loss: 0.1885, Val Loss: 0.4135
Fold 2 - MSE: 33.3844, RMSE: 5.7779, MAE: 3.3902
Starting fold 3...
  Epoch 0... Train Loss: 0.8805, Val Loss: 0.8714
  Epoch 10... Train Loss: 0.3155, Val Loss: 0.4499
  Epoch 20... Train Loss: 0.2488, Val Loss: 0.3690
  Epoch 30... Train Loss: 0.2145, Val Loss: 0.3604
  Epoch 40... Train Loss: 0.2260, Val Loss: 0.3567
  Epoch 50... Train Loss: 0.2012, Val Loss: 0.3489
Fold 3 - MSE: 39.9787, RMSE: 6.3229, MAE: 3.6338
Starting fold 4...
  Epoch 0... Train Loss: 0.7865, Val Loss: 1.0311
  Epoch 10... Train Loss: 0.2928, Val Loss: 0.5935
  Epoch 20... Train Loss: 0.1884, Val Loss: 0.5058
  Epoch 30... Train Loss: 0.1732, Val Loss: 0.4913
  Epoch 40... Train Loss: 0.1755, Val Loss: 0.5055
  Epoch 50... Train Loss: 0.1764, Val Loss: 0.4895
Fold 4 - MSE: 29.3315, RMSE: 5.4159, MAE: 4.3573
Starting fold 5...
  Epoch 0... Train Loss: 0.9167, Val Loss: 1.2215
  Epoch 10... Train Loss: 0.3643, Val Loss: 0.8525
  Epoch 20... Train Loss: 0.2820, Val Loss: 0.7107
  Epoch 30... Train Loss: 0.2398, Val Loss: 0.7337
  Epoch 40... Train Loss: 0.2127, Val Loss: 0.7228
  Epoch 50... Train Loss: 0.2256, Val Loss: 0.8036
  Epoch 60... Train Loss: 0.2208, Val Loss: 0.6779
Fold 5 - MSE: 19.0808, RMSE: 4.3682, MAE: 3.9245

Mean CV MSE: 32.5923, Mean CV RMSE: 5.6605, Mean CV MAE: 3.9465

[INFO 04-02 09:56:39] ax.service.ax_client: Completed trial 9 with data: {'avg_rmse_nonzero': 5.660491}.
[INFO 04-02 09:56:39] ax.service.ax_client: Generated new trial 10 with parameters {'dropout_rate': 0.208467, 'weight_decay': 8.1e-05, 'lr': 0.007709, 'batch_size': 64, 'early_stopping_patience': 21, 'n_layers': 3, 'hidden1': 128, 'hidden2': 1024, 'hidden3': 32, 'activation': 'elu'} using model Sobol.

Completed trial 9 with mean RMSE: 5.6605 ± 0.3712
Saved Ax client checkpoint

Starting trial 10 with parameters: {'dropout_rate': 0.20846654707565904, 'weight_decay': 8.118433651412469e-05, 'lr': 0.0077088368774844915, 'batch_size': 64, 'early_stopping_patience': 21, 'n_layers': 3, 'hidden1': 128, 'hidden2': 1024, 'hidden3': 32, 'activation': 'elu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 14.3350, Val Loss: 47.1034
  Epoch 10... Train Loss: 0.8266, Val Loss: 0.6438
  Epoch 20... Train Loss: 0.6098, Val Loss: 0.5004
  Epoch 30... Train Loss: 0.4895, Val Loss: 0.4057
  Epoch 40... Train Loss: 0.4397, Val Loss: 0.3273
  Epoch 50... Train Loss: 0.4031, Val Loss: 0.4621
  Epoch 60... Train Loss: 0.3713, Val Loss: 0.3214
  Epoch 70... Train Loss: 0.3100, Val Loss: 0.3713
Fold 1 - MSE: 41.6562, RMSE: 6.4542, MAE: 4.2099
Starting fold 2...
  Epoch 0... Train Loss: 7.8322, Val Loss: 25.6397
  Epoch 10... Train Loss: 0.5849, Val Loss: 1.0170
  Epoch 20... Train Loss: 0.4795, Val Loss: 0.7328
  Epoch 30... Train Loss: 0.4369, Val Loss: 0.6589
  Epoch 40... Train Loss: 0.3382, Val Loss: 0.6243
  Epoch 50... Train Loss: 0.2639, Val Loss: 0.4939
  Epoch 60... Train Loss: 0.2760, Val Loss: 0.4011
  Epoch 70... Train Loss: 0.3168, Val Loss: 0.4113
  Epoch 80... Train Loss: 0.2864, Val Loss: 0.4089
Fold 2 - MSE: 49.7037, RMSE: 7.0501, MAE: 4.3933
Starting fold 3...
  Epoch 0... Train Loss: 8.8786, Val Loss: 28.6584
  Epoch 10... Train Loss: 0.6206, Val Loss: 0.7591
  Epoch 20... Train Loss: 0.4367, Val Loss: 0.5433
  Epoch 30... Train Loss: 0.3966, Val Loss: 0.4394
  Epoch 40... Train Loss: 0.3309, Val Loss: 0.4567
  Epoch 50... Train Loss: 0.2920, Val Loss: 0.4385
  Epoch 60... Train Loss: 0.2572, Val Loss: 0.4091
  Epoch 70... Train Loss: 0.2215, Val Loss: 0.4334
  Epoch 80... Train Loss: 0.2329, Val Loss: 0.3490
  Epoch 90... Train Loss: 0.2169, Val Loss: 0.3649
  Epoch 100... Train Loss: 0.2187, Val Loss: 0.3873
  Epoch 110... Train Loss: 0.2214, Val Loss: 0.3891
Fold 3 - MSE: 63.3986, RMSE: 7.9623, MAE: 4.1328
Starting fold 4...
  Epoch 0... Train Loss: 8.4936, Val Loss: 17.7521
  Epoch 10... Train Loss: 0.6120, Val Loss: 0.5347
  Epoch 20... Train Loss: 0.3751, Val Loss: 0.5348
  Epoch 30... Train Loss: 0.3095, Val Loss: 0.4330
  Epoch 40... Train Loss: 0.2722, Val Loss: 0.4170
  Epoch 50... Train Loss: 0.2411, Val Loss: 0.4464
  Epoch 60... Train Loss: 0.2166, Val Loss: 0.4134
Fold 4 - MSE: 39.4069, RMSE: 6.2775, MAE: 4.6293
Starting fold 5...
  Epoch 0... Train Loss: 10.2233, Val Loss: 38.7317
  Epoch 10... Train Loss: 0.6529, Val Loss: 1.1023
  Epoch 20... Train Loss: 0.4698, Val Loss: 0.9249
  Epoch 30... Train Loss: 0.3520, Val Loss: 1.0960
  Epoch 40... Train Loss: 0.3438, Val Loss: 0.8319
  Epoch 50... Train Loss: 0.2680, Val Loss: 0.7619
  Epoch 60... Train Loss: 0.2653, Val Loss: 0.8348

[INFO 04-02 09:56:58] ax.service.ax_client: Completed trial 10 with data: {'avg_rmse_nonzero': 7.167472}.
[INFO 04-02 09:56:58] ax.service.ax_client: Generated new trial 11 with parameters {'dropout_rate': 0.413592, 'weight_decay': 0.006394, 'lr': 4.7e-05, 'batch_size': 256, 'early_stopping_patience': 30, 'n_layers': 2, 'hidden1': 2048, 'hidden2': 64, 'hidden3': 256, 'activation': 'relu'} using model Sobol.

Fold 5 - MSE: 65.5016, RMSE: 8.0933, MAE: 6.8452

Mean CV MSE: 51.9334, Mean CV RMSE: 7.1675, Mean CV MAE: 4.8421
Completed trial 10 with mean RMSE: 7.1675 ± 0.3744
Saved Ax client checkpoint

Starting trial 11 with parameters: {'dropout_rate': 0.4135919399559498, 'weight_decay': 0.006394246545754221, 'lr': 4.682486444733884e-05, 'batch_size': 256, 'early_stopping_patience': 30, 'n_layers': 2, 'hidden1': 2048, 'hidden2': 64, 'hidden3': 256, 'activation': 'relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 1.5616, Val Loss: 0.8418
  Epoch 10... Train Loss: 0.6497, Val Loss: 0.4878
  Epoch 20... Train Loss: 0.5613, Val Loss: 0.3589
  Epoch 30... Train Loss: 0.4254, Val Loss: 0.3691
  Epoch 40... Train Loss: 0.4925, Val Loss: 0.3617
  Epoch 50... Train Loss: 0.5012, Val Loss: 0.3712
Fold 1 - MSE: 35.4331, RMSE: 5.9526, MAE: 4.1808
Starting fold 2...
  Epoch 0... Train Loss: 0.9659, Val Loss: 0.9394
  Epoch 10... Train Loss: 0.5493, Val Loss: 0.6160
  Epoch 20... Train Loss: 0.4422, Val Loss: 0.5666
  Epoch 30... Train Loss: 0.4188, Val Loss: 0.5585
  Epoch 40... Train Loss: 0.3610, Val Loss: 0.5255
  Epoch 50... Train Loss: 0.4100, Val Loss: 0.5544
  Epoch 60... Train Loss: 0.3250, Val Loss: 0.5076
  Epoch 70... Train Loss: 0.3536, Val Loss: 0.4824
  Epoch 80... Train Loss: 0.3651, Val Loss: 0.4815
  Epoch 90... Train Loss: 0.3515, Val Loss: 0.4526
  Epoch 100... Train Loss: 0.2981, Val Loss: 0.4853
  Epoch 110... Train Loss: 0.3044, Val Loss: 0.5049
  Epoch 120... Train Loss: 0.3285, Val Loss: 0.4777
Fold 2 - MSE: 43.4161, RMSE: 6.5891, MAE: 4.2640
Starting fold 3...
  Epoch 0... Train Loss: 1.0729, Val Loss: 0.9776
  Epoch 10... Train Loss: 0.5191, Val Loss: 0.4974
  Epoch 20... Train Loss: 0.4214, Val Loss: 0.4267
  Epoch 30... Train Loss: 0.3833, Val Loss: 0.4283
  Epoch 40... Train Loss: 0.3910, Val Loss: 0.3976
  Epoch 50... Train Loss: 0.3515, Val Loss: 0.4125
  Epoch 60... Train Loss: 0.3216, Val Loss: 0.3637
  Epoch 70... Train Loss: 0.3355, Val Loss: 0.3833
  Epoch 80... Train Loss: 0.3299, Val Loss: 0.3719
  Epoch 90... Train Loss: 0.2936, Val Loss: 0.3759
Fold 3 - MSE: 64.9445, RMSE: 8.0588, MAE: 4.9260
Starting fold 4...
  Epoch 0... Train Loss: 1.4144, Val Loss: 0.7322
  Epoch 10... Train Loss: 0.5052, Val Loss: 0.5133
  Epoch 20... Train Loss: 0.4214, Val Loss: 0.4883
  Epoch 30... Train Loss: 0.3842, Val Loss: 0.5168
Fold 4 - MSE: 51.9624, RMSE: 7.2085, MAE: 5.3247
Starting fold 5...
  Epoch 0... Train Loss: 1.1092, Val Loss: 1.3576
  Epoch 10... Train Loss: 0.5404, Val Loss: 0.9813
  Epoch 20... Train Loss: 0.4395, Val Loss: 0.8526
  Epoch 30... Train Loss: 0.4089, Val Loss: 0.8758
  Epoch 40... Train Loss: 0.4275, Val Loss: 0.7616
  Epoch 50... Train Loss: 0.3754, Val Loss: 0.7761

[INFO 04-02 09:57:04] ax.service.ax_client: Completed trial 11 with data: {'avg_rmse_nonzero': 6.859213}.
[INFO 04-02 09:57:04] ax.service.ax_client: Generated new trial 12 with parameters {'dropout_rate': 0.462477, 'weight_decay': 0.000185, 'lr': 0.002051, 'batch_size': 64, 'early_stopping_patience': 27, 'n_layers': 2, 'hidden1': 128, 'hidden2': 64, 'hidden3': 32, 'activation': 'leaky_relu'} using model Sobol.

Fold 5 - MSE: 42.0824, RMSE: 6.4871, MAE: 4.8006

Mean CV MSE: 47.5677, Mean CV RMSE: 6.8592, Mean CV MAE: 4.6992
Completed trial 11 with mean RMSE: 6.8592 ± 0.3602
Saved Ax client checkpoint

Starting trial 12 with parameters: {'dropout_rate': 0.4624766097404063, 'weight_decay': 0.0001851677284254904, 'lr': 0.002050770822735829, 'batch_size': 64, 'early_stopping_patience': 27, 'n_layers': 2, 'hidden1': 128, 'hidden2': 64, 'hidden3': 32, 'activation': 'leaky_relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 3.3866, Val Loss: 16.2613
  Epoch 10... Train Loss: 0.5488, Val Loss: 0.3810
  Epoch 20... Train Loss: 0.4500, Val Loss: 0.5235
  Epoch 30... Train Loss: 0.3617, Val Loss: 0.2793
  Epoch 40... Train Loss: 0.3202, Val Loss: 0.2871
  Epoch 50... Train Loss: 0.3978, Val Loss: 0.4830
Fold 1 - MSE: 43.4263, RMSE: 6.5899, MAE: 4.4165
Starting fold 2...
  Epoch 0... Train Loss: 1.8558, Val Loss: 1.8390
  Epoch 10... Train Loss: 0.4857, Val Loss: 0.7947
  Epoch 20... Train Loss: 0.4403, Val Loss: 0.4979
  Epoch 30... Train Loss: 0.4383, Val Loss: 0.5629
  Epoch 40... Train Loss: 0.3220, Val Loss: 0.6398
  Epoch 50... Train Loss: 0.2400, Val Loss: 0.4329
  Epoch 60... Train Loss: 0.2509, Val Loss: 0.3414
Fold 2 - MSE: 41.4360, RMSE: 6.4371, MAE: 3.9546
Starting fold 3...
  Epoch 0... Train Loss: 2.0268, Val Loss: 2.0228
  Epoch 10... Train Loss: 0.4328, Val Loss: 0.5981
  Epoch 20... Train Loss: 0.3202, Val Loss: 0.4539
  Epoch 30... Train Loss: 0.3452, Val Loss: 0.4320
  Epoch 40... Train Loss: 0.2795, Val Loss: 0.3824
  Epoch 50... Train Loss: 0.2590, Val Loss: 0.4068
  Epoch 60... Train Loss: 0.2494, Val Loss: 0.3535
  Epoch 70... Train Loss: 0.1981, Val Loss: 0.3838
  Epoch 80... Train Loss: 0.2144, Val Loss: 0.3239
  Epoch 90... Train Loss: 0.2278, Val Loss: 0.3475
  Epoch 100... Train Loss: 0.2048, Val Loss: 0.3545
Fold 3 - MSE: 62.4678, RMSE: 7.9037, MAE: 4.1892
Starting fold 4...
  Epoch 0... Train Loss: 2.0397, Val Loss: 2.7514
  Epoch 10... Train Loss: 0.4252, Val Loss: 0.5061
  Epoch 20... Train Loss: 0.2936, Val Loss: 0.5402
  Epoch 30... Train Loss: 0.2099, Val Loss: 0.4504
  Epoch 40... Train Loss: 0.1982, Val Loss: 0.4854
  Epoch 50... Train Loss: 0.1991, Val Loss: 0.4000
  Epoch 60... Train Loss: 0.1812, Val Loss: 0.4303
  Epoch 70... Train Loss: 0.1949, Val Loss: 0.4880
Fold 4 - MSE: 29.6297, RMSE: 5.4433, MAE: 4.3472
Starting fold 5...
  Epoch 0... Train Loss: 2.5896, Val Loss: 2.3127
  Epoch 10... Train Loss: 0.4332, Val Loss: 0.9516
  Epoch 20... Train Loss: 0.3408, Val Loss: 0.8802
  Epoch 30... Train Loss: 0.2898, Val Loss: 0.9209
  Epoch 40... Train Loss: 0.2995, Val Loss: 0.7908
  Epoch 50... Train Loss: 0.2850, Val Loss: 0.7621
  Epoch 60... Train Loss: 0.2545, Val Loss: 0.7708
  Epoch 70... Train Loss: 0.2634, Val Loss: 0.7297
  Epoch 80... Train Loss: 0.2259, Val Loss: 0.6961
  Epoch 90... Train Loss: 0.2532, Val Loss: 0.7195
  Epoch 100... Train Loss: 0.2286, Val Loss: 0.8230
  Epoch 110... Train Loss: 0.2272, Val Loss: 0.8195

[INFO 04-02 09:57:20] ax.service.ax_client: Completed trial 12 with data: {'avg_rmse_nonzero': 5.795888}.
[INFO 04-02 09:57:20] ax.service.ax_client: Generated new trial 13 with parameters {'dropout_rate': 0.167418, 'weight_decay': 2e-06, 'lr': 1.3e-05, 'batch_size': 256, 'early_stopping_patience': 37, 'n_layers': 1, 'hidden1': 1024, 'hidden2': 1024, 'hidden3': 256, 'activation': 'relu'} using model Sobol.

Fold 5 - MSE: 6.7887, RMSE: 2.6055, MAE: 2.1142

Mean CV MSE: 36.7497, Mean CV RMSE: 5.7959, Mean CV MAE: 3.8043
Completed trial 12 with mean RMSE: 5.7959 ± 0.8885
Saved Ax client checkpoint

Starting trial 13 with parameters: {'dropout_rate': 0.16741781681776047, 'weight_decay': 2.4338540977191783e-06, 'lr': 1.3149230182669592e-05, 'batch_size': 256, 'early_stopping_patience': 37, 'n_layers': 1, 'hidden1': 1024, 'hidden2': 1024, 'hidden3': 256, 'activation': 'relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 1.2306, Val Loss: 0.8411
  Epoch 10... Train Loss: 0.5532, Val Loss: 0.5471
  Epoch 20... Train Loss: 0.4293, Val Loss: 0.3807
  Epoch 30... Train Loss: 0.3191, Val Loss: 0.4257
  Epoch 40... Train Loss: 0.3122, Val Loss: 0.4064
  Epoch 50... Train Loss: 0.3427, Val Loss: 0.4276
  Epoch 60... Train Loss: 0.2891, Val Loss: 0.3551
  Epoch 70... Train Loss: 0.2781, Val Loss: 0.3430
  Epoch 80... Train Loss: 0.3611, Val Loss: 0.3700
  Epoch 90... Train Loss: 0.3244, Val Loss: 0.3578
  Epoch 100... Train Loss: 0.3620, Val Loss: 0.3689
Fold 1 - MSE: 46.9121, RMSE: 6.8492, MAE: 4.7164
Starting fold 2...
  Epoch 0... Train Loss: 0.9084, Val Loss: 0.9434
  Epoch 10... Train Loss: 0.4398, Val Loss: 0.6417
  Epoch 20... Train Loss: 0.2764, Val Loss: 0.6021
  Epoch 30... Train Loss: 0.2854, Val Loss: 0.5326
  Epoch 40... Train Loss: 0.2207, Val Loss: 0.5126
  Epoch 50... Train Loss: 0.2650, Val Loss: 0.5382
  Epoch 60... Train Loss: 0.2487, Val Loss: 0.4998
  Epoch 70... Train Loss: 0.2573, Val Loss: 0.4803
  Epoch 80... Train Loss: 0.2199, Val Loss: 0.4698
  Epoch 90... Train Loss: 0.2350, Val Loss: 0.4669
  Epoch 100... Train Loss: 0.2200, Val Loss: 0.4862
  Epoch 110... Train Loss: 0.1995, Val Loss: 0.4920
  Epoch 120... Train Loss: 0.2010, Val Loss: 0.4780
Fold 2 - MSE: 48.2234, RMSE: 6.9443, MAE: 5.2954
Starting fold 3...
  Epoch 0... Train Loss: 1.0089, Val Loss: 0.9907
  Epoch 10... Train Loss: 0.4027, Val Loss: 0.5502
  Epoch 20... Train Loss: 0.2908, Val Loss: 0.4698
  Epoch 30... Train Loss: 0.2934, Val Loss: 0.4510
  Epoch 40... Train Loss: 0.2374, Val Loss: 0.4137
  Epoch 50... Train Loss: 0.2383, Val Loss: 0.4275
  Epoch 60... Train Loss: 0.2214, Val Loss: 0.3853
  Epoch 70... Train Loss: 0.2292, Val Loss: 0.3877
  Epoch 80... Train Loss: 0.2029, Val Loss: 0.3812
  Epoch 90... Train Loss: 0.2026, Val Loss: 0.3772
  Epoch 100... Train Loss: 0.2045, Val Loss: 0.3708
  Epoch 110... Train Loss: 0.1931, Val Loss: 0.3738
Fold 3 - MSE: 50.2745, RMSE: 7.0904, MAE: 5.0013
Starting fold 4...
  Epoch 0... Train Loss: 0.9611, Val Loss: 1.5727
  Epoch 10... Train Loss: 0.4373, Val Loss: 2.2330
  Epoch 20... Train Loss: 0.2879, Val Loss: 2.7728
  Epoch 30... Train Loss: 0.2698, Val Loss: 3.0266
Fold 4 - MSE: 32.5961, RMSE: 5.7093, MAE: 4.6996
Starting fold 5...
  Epoch 0... Train Loss: 1.0572, Val Loss: 1.2517
  Epoch 10... Train Loss: 0.4024, Val Loss: 0.8937
  Epoch 20... Train Loss: 0.3208, Val Loss: 0.8242
  Epoch 30... Train Loss: 0.3013, Val Loss: 0.7669
  Epoch 40... Train Loss: 0.2611, Val Loss: 0.7955
  Epoch 50... Train Loss: 0.2432, Val Loss: 0.7444
  Epoch 60... Train Loss: 0.2458, Val Loss: 0.7577
  Epoch 70... Train Loss: 0.2332, Val Loss: 0.7135
  Epoch 80... Train Loss: 0.2366, Val Loss: 0.7318
  Epoch 90... Train Loss: 0.2402, Val Loss: 0.6818
  Epoch 100... Train Loss: 0.2274, Val Loss: 0.7147
  Epoch 110... Train Loss: 0.2217, Val Loss: 0.7000

[INFO 04-02 09:57:28] ax.service.ax_client: Completed trial 13 with data: {'avg_rmse_nonzero': 6.008929}.
[INFO 04-02 09:57:29] ax.service.ax_client: Generated new trial 14 with parameters {'dropout_rate': 0.028378, 'weight_decay': 2e-05, 'lr': 0.000685, 'batch_size': 128, 'early_stopping_patience': 45, 'n_layers': 2, 'hidden1': 512, 'hidden2': 256, 'hidden3': 64, 'activation': 'selu'} using model Sobol.

  Epoch 120... Train Loss: 0.2075, Val Loss: 0.7128
Fold 5 - MSE: 11.9118, RMSE: 3.4514, MAE: 2.4989

Mean CV MSE: 37.9836, Mean CV RMSE: 6.0089, Mean CV MAE: 4.4423
Completed trial 13 with mean RMSE: 6.0089 ± 0.6849
Saved Ax client checkpoint

Starting trial 14 with parameters: {'dropout_rate': 0.02837793342769146, 'weight_decay': 1.96643373267061e-05, 'lr': 0.0006847354355154155, 'batch_size': 128, 'early_stopping_patience': 45, 'n_layers': 2, 'hidden1': 512, 'hidden2': 256, 'hidden3': 64, 'activation': 'selu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 21.1634, Val Loss: 8.8101
  Epoch 10... Train Loss: 0.6036, Val Loss: 0.6414
  Epoch 20... Train Loss: 0.4180, Val Loss: 0.4235
  Epoch 30... Train Loss: 0.3627, Val Loss: 0.4178
  Epoch 40... Train Loss: 0.3305, Val Loss: 0.3927
  Epoch 50... Train Loss: 0.3642, Val Loss: 0.4259
  Epoch 60... Train Loss: 0.3072, Val Loss: 0.4412
  Epoch 70... Train Loss: 0.2802, Val Loss: 0.5221
  Epoch 80... Train Loss: 0.3308, Val Loss: 0.4800
  Epoch 90... Train Loss: 0.2848, Val Loss: 0.4526
Fold 1 - MSE: 46.5917, RMSE: 6.8258, MAE: 4.6993
Starting fold 2...
  Epoch 0... Train Loss: 14.3997, Val Loss: 2.9601
  Epoch 10... Train Loss: 0.4392, Val Loss: 1.0087
  Epoch 20... Train Loss: 0.3287, Val Loss: 0.7257
  Epoch 30... Train Loss: 0.3290, Val Loss: 0.7200
  Epoch 40... Train Loss: 0.2932, Val Loss: 0.5927
  Epoch 50... Train Loss: 0.2487, Val Loss: 0.5832
  Epoch 60... Train Loss: 0.2477, Val Loss: 0.3725
  Epoch 70... Train Loss: 0.2391, Val Loss: 0.4079
  Epoch 80... Train Loss: 0.2323, Val Loss: 0.5475
  Epoch 90... Train Loss: 0.2041, Val Loss: 0.3462
  Epoch 100... Train Loss: 0.1960, Val Loss: 0.3951
  Epoch 110... Train Loss: 0.1846, Val Loss: 0.4044
Fold 2 - MSE: 69.8854, RMSE: 8.3597, MAE: 5.9135
Starting fold 3...
  Epoch 0... Train Loss: 13.3207, Val Loss: 2.7661
  Epoch 10... Train Loss: 0.4225, Val Loss: 0.5851
  Epoch 20... Train Loss: 0.3444, Val Loss: 0.4814
  Epoch 30... Train Loss: 0.3132, Val Loss: 0.4012
  Epoch 40... Train Loss: 0.2910, Val Loss: 0.4077
  Epoch 50... Train Loss: 0.2630, Val Loss: 0.4538
  Epoch 60... Train Loss: 0.2617, Val Loss: 0.4598
  Epoch 70... Train Loss: 0.2223, Val Loss: 0.5522
  Epoch 80... Train Loss: 0.2140, Val Loss: 0.3706
Fold 3 - MSE: 73.0310, RMSE: 8.5458, MAE: 5.6127
Starting fold 4...
  Epoch 0... Train Loss: 14.6858, Val Loss: 2.5991
  Epoch 10... Train Loss: 0.4452, Val Loss: 0.5491
  Epoch 20... Train Loss: 0.3265, Val Loss: 0.7108
  Epoch 30... Train Loss: 0.2742, Val Loss: 0.4709
  Epoch 40... Train Loss: 0.2490, Val Loss: 0.6329
  Epoch 50... Train Loss: 0.2325, Val Loss: 0.4523
  Epoch 60... Train Loss: 0.2122, Val Loss: 0.5286
Fold 4 - MSE: 45.0045, RMSE: 6.7085, MAE: 5.2540
Starting fold 5...
  Epoch 0... Train Loss: 11.9638, Val Loss: 6.4440
  Epoch 10... Train Loss: 0.4820, Val Loss: 0.9564
  Epoch 20... Train Loss: 0.3627, Val Loss: 0.8012
  Epoch 30... Train Loss: 0.3328, Val Loss: 1.3033
  Epoch 40... Train Loss: 0.3232, Val Loss: 0.7654
  Epoch 50... Train Loss: 0.2761, Val Loss: 0.7629
  Epoch 60... Train Loss: 0.2685, Val Loss: 0.7252
  Epoch 70... Train Loss: 0.2621, Val Loss: 0.6812
  Epoch 80... Train Loss: 0.2527, Val Loss: 0.7239
  Epoch 90... Train Loss: 0.2778, Val Loss: 0.7437
  Epoch 100... Train Loss: 0.2294, Val Loss: 0.9953
  Epoch 110... Train Loss: 0.2291, Val Loss: 0.9941
  Epoch 120... Train Loss: 0.2328, Val Loss: 0.7208

[INFO 04-02 09:57:41] ax.service.ax_client: Completed trial 14 with data: {'avg_rmse_nonzero': 7.532443}.

  Epoch 130... Train Loss: 0.2283, Val Loss: 0.6609
Fold 5 - MSE: 52.1616, RMSE: 7.2223, MAE: 6.7562

Mean CV MSE: 57.3348, Mean CV RMSE: 7.5324, Mean CV MAE: 5.6471
Completed trial 14 with mean RMSE: 7.5324 ± 0.3864
Saved Ax client checkpoint

[INFO 04-02 09:57:41] ax.service.ax_client: Generated new trial 15 with parameters {'dropout_rate': 0.359329, 'weight_decay': 0.002683, 'lr': 9.6e-05, 'batch_size': 32, 'early_stopping_patience': 14, 'n_layers': 3, 'hidden1': 256, 'hidden2': 128, 'hidden3': 512, 'activation': 'elu'} using model Sobol.

Starting trial 15 with parameters: {'dropout_rate': 0.359329201746732, 'weight_decay': 0.0026825720909373903, 'lr': 9.594301942078082e-05, 'batch_size': 32, 'early_stopping_patience': 14, 'n_layers': 3, 'hidden1': 256, 'hidden2': 128, 'hidden3': 512, 'activation': 'elu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 1.0523, Val Loss: 0.7407
  Epoch 10... Train Loss: 0.6626, Val Loss: 0.4654
  Epoch 20... Train Loss: 0.5025, Val Loss: 0.4815
Fold 1 - MSE: 38.1467, RMSE: 6.1763, MAE: 4.2475
Starting fold 2...
  Epoch 0... Train Loss: 1.1680, Val Loss: 0.6682
  Epoch 10... Train Loss: 0.5476, Val Loss: 0.6678
  Epoch 20... Train Loss: 0.4551, Val Loss: 0.5645
  Epoch 30... Train Loss: 0.4138, Val Loss: 0.5635
  Epoch 40... Train Loss: 0.4062, Val Loss: 0.5717
  Epoch 50... Train Loss: 0.3949, Val Loss: 0.5427
  Epoch 60... Train Loss: 0.4091, Val Loss: 0.5011
  Epoch 70... Train Loss: 0.4254, Val Loss: 0.4990
  Epoch 80... Train Loss: 0.4410, Val Loss: 0.5058
Fold 2 - MSE: 45.6312, RMSE: 6.7551, MAE: 4.2750
Starting fold 3...
  Epoch 0... Train Loss: 0.9954, Val Loss: 0.7593
  Epoch 10... Train Loss: 0.6300, Val Loss: 0.5786
  Epoch 20... Train Loss: 0.4573, Val Loss: 0.4645
  Epoch 30... Train Loss: 0.4092, Val Loss: 0.4553
  Epoch 40... Train Loss: 0.3652, Val Loss: 0.4421
  Epoch 50... Train Loss: 0.3770, Val Loss: 0.4208
  Epoch 60... Train Loss: 0.3468, Val Loss: 0.4203
Fold 3 - MSE: 53.7392, RMSE: 7.3307, MAE: 4.2415
Starting fold 4...
  Epoch 0... Train Loss: 1.0146, Val Loss: 0.6489
  Epoch 10... Train Loss: 0.5934, Val Loss: 0.5947
  Epoch 20... Train Loss: 0.4214, Val Loss: 0.5741
Fold 4 - MSE: 27.7627, RMSE: 5.2690, MAE: 4.2368
Starting fold 5...
  Epoch 0... Train Loss: 1.1998, Val Loss: 1.2619
  Epoch 10... Train Loss: 0.5535, Val Loss: 0.9492
  Epoch 20... Train Loss: 0.4727, Val Loss: 0.8400

[INFO 04-02 09:57:59] ax.service.ax_client: Completed trial 15 with data: {'avg_rmse_nonzero': 5.552723}.
[INFO 04-02 09:57:59] ax.service.ax_client: Generated new trial 16 with parameters {'dropout_rate': 0.37364, 'weight_decay': 2e-06, 'lr': 1.8e-05, 'batch_size': 128, 'early_stopping_patience': 19, 'n_layers': 2, 'hidden1': 256, 'hidden2': 64, 'hidden3': 32, 'activation': 'leaky_relu'} using model Sobol.

  Epoch 30... Train Loss: 0.4553, Val Loss: 0.8117
Fold 5 - MSE: 4.9840, RMSE: 2.2325, MAE: 1.4564

Mean CV MSE: 34.0528, Mean CV RMSE: 5.5527, Mean CV MAE: 3.6914
Completed trial 15 with mean RMSE: 5.5527 ± 0.8972
Saved Ax client checkpoint

Starting trial 16 with parameters: {'dropout_rate': 0.3736395691521466, 'weight_decay': 1.843146088722603e-06, 'lr': 1.820542866714727e-05, 'batch_size': 128, 'early_stopping_patience': 19, 'n_layers': 2, 'hidden1': 256, 'hidden2': 64, 'hidden3': 32, 'activation': 'leaky_relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 1.2159, Val Loss: 0.8632
  Epoch 10... Train Loss: 0.6472, Val Loss: 0.5009
  Epoch 20... Train Loss: 0.4927, Val Loss: 0.3803
  Epoch 30... Train Loss: 0.5205, Val Loss: 0.4205
  Epoch 40... Train Loss: 0.3911, Val Loss: 0.3779
  Epoch 50... Train Loss: 0.4378, Val Loss: 0.3620
  Epoch 60... Train Loss: 0.4099, Val Loss: 0.3426
  Epoch 70... Train Loss: 0.4565, Val Loss: 0.3642
Fold 1 - MSE: 44.4874, RMSE: 6.6699, MAE: 4.4475
Starting fold 2...
  Epoch 0... Train Loss: 1.0414, Val Loss: 0.8331
  Epoch 10... Train Loss: 0.5229, Val Loss: 1.1632
  Epoch 20... Train Loss: 0.4405, Val Loss: 0.6505
  Epoch 30... Train Loss: 0.4629, Val Loss: 0.6068
  Epoch 40... Train Loss: 0.4385, Val Loss: 0.6920
Fold 2 - MSE: 31.2713, RMSE: 5.5921, MAE: 3.5967
Starting fold 3...
  Epoch 0... Train Loss: 1.1467, Val Loss: 0.9926
  Epoch 10... Train Loss: 0.5250, Val Loss: 0.5652
  Epoch 20... Train Loss: 0.4271, Val Loss: 0.4501
  Epoch 30... Train Loss: 0.3829, Val Loss: 0.3714
  Epoch 40... Train Loss: 0.3795, Val Loss: 0.3549
  Epoch 50... Train Loss: 0.3656, Val Loss: 0.3911
  Epoch 60... Train Loss: 0.3437, Val Loss: 0.3808
Fold 3 - MSE: 52.0346, RMSE: 7.2135, MAE: 4.7755
Starting fold 4...
  Epoch 0... Train Loss: 1.0729, Val Loss: 0.5996
  Epoch 10... Train Loss: 0.4908, Val Loss: 0.4873
  Epoch 20... Train Loss: 0.3849, Val Loss: 0.5934
  Epoch 30... Train Loss: 0.4053, Val Loss: 0.3799
Fold 4 - MSE: 45.4287, RMSE: 6.7401, MAE: 5.3179
Starting fold 5...
  Epoch 0... Train Loss: 1.0659, Val Loss: 1.6109
  Epoch 10... Train Loss: 0.5750, Val Loss: 0.7763
  Epoch 20... Train Loss: 0.4439, Val Loss: 0.7059
  Epoch 30... Train Loss: 0.4315, Val Loss: 1.1858

[INFO 04-02 09:58:05] ax.service.ax_client: Completed trial 16 with data: {'avg_rmse_nonzero': 5.976832}.
[INFO 04-02 09:58:05] ax.service.ax_client: Generated new trial 17 with parameters {'dropout_rate': 0.012114, 'weight_decay': 0.000249, 'lr': 0.003524, 'batch_size': 32, 'early_stopping_patience': 50, 'n_layers': 3, 'hidden1': 512, 'hidden2': 1024, 'hidden3': 128, 'activation': 'elu'} using model Sobol.

  Epoch 40... Train Loss: 0.4241, Val Loss: 0.8304
Fold 5 - MSE: 13.4588, RMSE: 3.6686, MAE: 2.6191

Mean CV MSE: 37.3362, Mean CV RMSE: 5.9768, Mean CV MAE: 4.1513
Completed trial 16 with mean RMSE: 5.9768 ± 0.6351
Saved Ax client checkpoint

Starting trial 17 with parameters: {'dropout_rate': 0.012114455923438072, 'weight_decay': 0.0002488890717261641, 'lr': 0.003524380768573858, 'batch_size': 32, 'early_stopping_patience': 50, 'n_layers': 3, 'hidden1': 512, 'hidden2': 1024, 'hidden3': 128, 'activation': 'elu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 17.3308, Val Loss: 16.9389
  Epoch 10... Train Loss: 0.5810, Val Loss: 0.5564
  Epoch 20... Train Loss: 0.5301, Val Loss: 0.5331
  Epoch 30... Train Loss: 0.3897, Val Loss: 0.3693
  Epoch 40... Train Loss: 0.3515, Val Loss: 0.3298
  Epoch 50... Train Loss: 0.4905, Val Loss: 0.4591
  Epoch 60... Train Loss: 0.3124, Val Loss: 0.5133
  Epoch 70... Train Loss: 0.3398, Val Loss: 0.4702
  Epoch 80... Train Loss: 0.3181, Val Loss: 0.5387
  Epoch 90... Train Loss: 0.3159, Val Loss: 0.5040
Fold 1 - MSE: 48.9539, RMSE: 6.9967, MAE: 4.5387
Starting fold 2...
  Epoch 0... Train Loss: 9.8354, Val Loss: 1.8198
  Epoch 10... Train Loss: 0.5182, Val Loss: 0.6486
  Epoch 20... Train Loss: 0.4127, Val Loss: 0.5858
  Epoch 30... Train Loss: 0.4157, Val Loss: 0.5304
  Epoch 40... Train Loss: 0.3837, Val Loss: 0.3975
  Epoch 50... Train Loss: 0.3485, Val Loss: 0.3423
  Epoch 60... Train Loss: 0.3506, Val Loss: 0.5051
  Epoch 70... Train Loss: 0.2780, Val Loss: 0.3786
  Epoch 80... Train Loss: 0.2362, Val Loss: 0.3661
  Epoch 90... Train Loss: 0.2116, Val Loss: 0.3920
  Epoch 100... Train Loss: 0.2013, Val Loss: 0.3424
  Epoch 110... Train Loss: 0.2079, Val Loss: 0.3153
  Epoch 120... Train Loss: 0.1874, Val Loss: 0.3691
  Epoch 130... Train Loss: 0.1768, Val Loss: 0.3340
  Epoch 140... Train Loss: 0.1715, Val Loss: 0.3214
  Epoch 150... Train Loss: 0.2083, Val Loss: 0.3298
  Epoch 160... Train Loss: 0.1775, Val Loss: 0.3672
Fold 2 - MSE: 42.0096, RMSE: 6.4815, MAE: 3.9860
Starting fold 3...
  Epoch 0... Train Loss: 11.3352, Val Loss: 2.7011
  Epoch 10... Train Loss: 0.6109, Val Loss: 0.7748
  Epoch 20... Train Loss: 0.3969, Val Loss: 0.4792
  Epoch 30... Train Loss: 0.3515, Val Loss: 0.4912
  Epoch 40... Train Loss: 0.3522, Val Loss: 0.4290
  Epoch 50... Train Loss: 0.3442, Val Loss: 0.4462
  Epoch 60... Train Loss: 0.2945, Val Loss: 0.4203
  Epoch 70... Train Loss: 0.2675, Val Loss: 0.3611
  Epoch 80... Train Loss: 0.2775, Val Loss: 0.4550
  Epoch 90... Train Loss: 0.2750, Val Loss: 0.3928
  Epoch 100... Train Loss: 0.2879, Val Loss: 0.3687
  Epoch 110... Train Loss: 0.2835, Val Loss: 0.3677
  Epoch 120... Train Loss: 0.2352, Val Loss: 0.3290
  Epoch 130... Train Loss: 0.2220, Val Loss: 0.3024
  Epoch 140... Train Loss: 0.1745, Val Loss: 0.3210
  Epoch 150... Train Loss: 0.1960, Val Loss: 0.3188
  Epoch 160... Train Loss: 0.2117, Val Loss: 0.3074
  Epoch 170... Train Loss: 0.1705, Val Loss: 0.3145
  Epoch 180... Train Loss: 0.1661, Val Loss: 0.3175
Fold 3 - MSE: 109.6997, RMSE: 10.4738, MAE: 5.2349
Starting fold 4...
  Epoch 0... Train Loss: 8.5024, Val Loss: 2.1909
  Epoch 10... Train Loss: 0.5019, Val Loss: 0.7937
  Epoch 20... Train Loss: 0.3998, Val Loss: 0.5736
  Epoch 30... Train Loss: 0.3319, Val Loss: 0.5996
  Epoch 40... Train Loss: 0.3183, Val Loss: 0.5216
  Epoch 50... Train Loss: 0.2572, Val Loss: 0.4726
  Epoch 60... Train Loss: 0.2139, Val Loss: 0.4103
  Epoch 70... Train Loss: 0.2469, Val Loss: 0.4793
  Epoch 80... Train Loss: 0.2502, Val Loss: 0.4450
  Epoch 90... Train Loss: 0.1732, Val Loss: 0.4389
  Epoch 100... Train Loss: 0.1958, Val Loss: 0.4261
  Epoch 110... Train Loss: 0.1815, Val Loss: 0.4490
  Epoch 120... Train Loss: 0.1522, Val Loss: 0.4029
  Epoch 130... Train Loss: 0.1560, Val Loss: 0.3840
  Epoch 140... Train Loss: 0.1955, Val Loss: 0.4074
  Epoch 150... Train Loss: 0.1562, Val Loss: 0.4275
  Epoch 160... Train Loss: 0.1586, Val Loss: 0.4110
  Epoch 170... Train Loss: 0.1502, Val Loss: 0.3932
  Epoch 180... Train Loss: 0.1414, Val Loss: 0.4087
  Epoch 190... Train Loss: 0.1316, Val Loss: 0.3968
  Epoch 200... Train Loss: 0.1447, Val Loss: 0.4046
  Epoch 210... Train Loss: 0.1386, Val Loss: 0.4004
  Epoch 220... Train Loss: 0.1329, Val Loss: 0.3979
Fold 4 - MSE: 43.7681, RMSE: 6.6157, MAE: 5.3781
Starting fold 5...
  Epoch 0... Train Loss: 9.2462, Val Loss: 2.4932
  Epoch 10... Train Loss: 0.5861, Val Loss: 0.9975
  Epoch 20... Train Loss: 0.4522, Val Loss: 0.9133
  Epoch 30... Train Loss: 0.3740, Val Loss: 0.8665
  Epoch 40... Train Loss: 0.3782, Val Loss: 0.8434
  Epoch 50... Train Loss: 0.3184, Val Loss: 0.8467
  Epoch 60... Train Loss: 0.2944, Val Loss: 0.7557
  Epoch 70... Train Loss: 0.2420, Val Loss: 0.8387

[INFO 04-02 09:59:01] ax.service.ax_client: Completed trial 17 with data: {'avg_rmse_nonzero': 8.992815}.
[INFO 04-02 09:59:01] ax.service.ax_client: Generated new trial 18 with parameters {'dropout_rate': 0.181668, 'weight_decay': 0.001993, 'lr': 8.6e-05, 'batch_size': 64, 'early_stopping_patience': 32, 'n_layers': 2, 'hidden1': 1024, 'hidden2': 256, 'hidden3': 128, 'activation': 'leaky_relu'} using model Sobol.

  Epoch 80... Train Loss: 0.2729, Val Loss: 0.7729
Fold 5 - MSE: 207.2558, RMSE: 14.3964, MAE: 12.8927

Mean CV MSE: 90.3374, Mean CV RMSE: 8.9928, Mean CV MAE: 6.4061
Completed trial 17 with mean RMSE: 8.9928 ± 1.5384
Saved Ax client checkpoint

Starting trial 18 with parameters: {'dropout_rate': 0.18166807293891907, 'weight_decay': 0.00199282448254186, 'lr': 8.627921532226588e-05, 'batch_size': 64, 'early_stopping_patience': 32, 'n_layers': 2, 'hidden1': 1024, 'hidden2': 256, 'hidden3': 128, 'activation': 'leaky_relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 1.0078, Val Loss: 0.6805
  Epoch 10... Train Loss: 0.3921, Val Loss: 0.3938
  Epoch 20... Train Loss: 0.3963, Val Loss: 0.6630
  Epoch 30... Train Loss: 0.3032, Val Loss: 0.2526
  Epoch 40... Train Loss: 0.2833, Val Loss: 0.2332
Fold 1 - MSE: 40.7853, RMSE: 6.3863, MAE: 4.4220
Starting fold 2...
  Epoch 0... Train Loss: 0.8903, Val Loss: 0.7061
  Epoch 10... Train Loss: 0.3726, Val Loss: 0.5904
  Epoch 20... Train Loss: 0.3317, Val Loss: 0.4095
  Epoch 30... Train Loss: 0.2728, Val Loss: 0.4299
  Epoch 40... Train Loss: 0.2796, Val Loss: 0.4911
  Epoch 50... Train Loss: 0.2308, Val Loss: 0.4484
  Epoch 60... Train Loss: 0.2229, Val Loss: 0.3843
  Epoch 70... Train Loss: 0.2461, Val Loss: 0.3902
  Epoch 80... Train Loss: 0.2135, Val Loss: 0.3947
  Epoch 90... Train Loss: 0.2109, Val Loss: 0.3142
  Epoch 100... Train Loss: 0.2170, Val Loss: 0.3597
  Epoch 110... Train Loss: 0.2122, Val Loss: 0.3726
  Epoch 120... Train Loss: 0.1903, Val Loss: 0.4546
Fold 2 - MSE: 39.5919, RMSE: 6.2922, MAE: 3.6998
Starting fold 3...
  Epoch 0... Train Loss: 0.9097, Val Loss: 0.8071
  Epoch 10... Train Loss: 0.3144, Val Loss: 0.4596
  Epoch 20... Train Loss: 0.2995, Val Loss: 0.6259
  Epoch 30... Train Loss: 0.2400, Val Loss: 0.3498
  Epoch 40... Train Loss: 0.2306, Val Loss: 0.3532
  Epoch 50... Train Loss: 0.2145, Val Loss: 0.3544
  Epoch 60... Train Loss: 0.2203, Val Loss: 0.3383
  Epoch 70... Train Loss: 0.2085, Val Loss: 0.3923
  Epoch 80... Train Loss: 0.1884, Val Loss: 0.3231
  Epoch 90... Train Loss: 0.1912, Val Loss: 0.3357
  Epoch 100... Train Loss: 0.2059, Val Loss: 0.3375
  Epoch 110... Train Loss: 0.2022, Val Loss: 0.3550
  Epoch 120... Train Loss: 0.1976, Val Loss: 0.3808
Fold 3 - MSE: 45.7993, RMSE: 6.7675, MAE: 4.2255
Starting fold 4...
  Epoch 0... Train Loss: 0.8498, Val Loss: 0.6758
  Epoch 10... Train Loss: 0.3170, Val Loss: 0.6255
  Epoch 20... Train Loss: 0.2250, Val Loss: 0.6919
  Epoch 30... Train Loss: 0.1922, Val Loss: 0.5446
  Epoch 40... Train Loss: 0.1832, Val Loss: 0.5560
Fold 4 - MSE: 42.3907, RMSE: 6.5108, MAE: 4.8847
Starting fold 5...
  Epoch 0... Train Loss: 0.9868, Val Loss: 1.2263
  Epoch 10... Train Loss: 0.3390, Val Loss: 0.7939
  Epoch 20... Train Loss: 0.3158, Val Loss: 0.6373
  Epoch 30... Train Loss: 0.2693, Val Loss: 0.8925
  Epoch 40... Train Loss: 0.2429, Val Loss: 0.8306
  Epoch 50... Train Loss: 0.2499, Val Loss: 0.6829
  Epoch 60... Train Loss: 0.2279, Val Loss: 0.7095
  Epoch 70... Train Loss: 0.2192, Val Loss: 0.6931

[INFO 04-02 09:59:16] ax.service.ax_client: Completed trial 18 with data: {'avg_rmse_nonzero': 5.835872}.
[INFO 04-02 09:59:16] ax.service.ax_client: Generated new trial 19 with parameters {'dropout_rate': 0.446273, 'weight_decay': 2.6e-05, 'lr': 0.000322, 'batch_size': 256, 'early_stopping_patience': 21, 'n_layers': 1, 'hidden1': 128, 'hidden2': 256, 'hidden3': 512, 'activation': 'relu'} using model Sobol.

Fold 5 - MSE: 10.3844, RMSE: 3.2225, MAE: 2.7863

Mean CV MSE: 35.7903, Mean CV RMSE: 5.8359, Mean CV MAE: 4.0037
Completed trial 18 with mean RMSE: 5.8359 ± 0.6582
Saved Ax client checkpoint

Starting trial 19 with parameters: {'dropout_rate': 0.4462731839157641, 'weight_decay': 2.599032910397216e-05, 'lr': 0.00032217829069965576, 'batch_size': 256, 'early_stopping_patience': 21, 'n_layers': 1, 'hidden1': 128, 'hidden2': 256, 'hidden3': 512, 'activation': 'relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 3.8016, Val Loss: 4.9069
  Epoch 10... Train Loss: 0.7494, Val Loss: 0.6979
  Epoch 20... Train Loss: 0.5277, Val Loss: 0.3810
  Epoch 30... Train Loss: 0.4780, Val Loss: 0.3879
Fold 1 - MSE: 41.2080, RMSE: 6.4193, MAE: 4.3585
Starting fold 2...
  Epoch 0... Train Loss: 2.5629, Val Loss: 2.7001
  Epoch 10... Train Loss: 0.4792, Val Loss: 0.6803
  Epoch 20... Train Loss: 0.3619, Val Loss: 0.5253
  Epoch 30... Train Loss: 0.3658, Val Loss: 0.5720
  Epoch 40... Train Loss: 0.3056, Val Loss: 0.5359
Fold 2 - MSE: 41.9601, RMSE: 6.4777, MAE: 4.1162
Starting fold 3...
  Epoch 0... Train Loss: 2.5241, Val Loss: 5.4032
  Epoch 10... Train Loss: 0.4744, Val Loss: 0.5144
  Epoch 20... Train Loss: 0.3528, Val Loss: 0.4547
  Epoch 30... Train Loss: 0.3158, Val Loss: 0.3988
  Epoch 40... Train Loss: 0.3071, Val Loss: 0.3952
  Epoch 50... Train Loss: 0.2853, Val Loss: 0.4073
  Epoch 60... Train Loss: 0.2769, Val Loss: 0.4048
  Epoch 70... Train Loss: 0.3118, Val Loss: 0.3883
  Epoch 80... Train Loss: 0.2798, Val Loss: 0.3898
  Epoch 90... Train Loss: 0.2682, Val Loss: 0.3881
Fold 3 - MSE: 54.4862, RMSE: 7.3815, MAE: 4.4387
Starting fold 4...
  Epoch 0... Train Loss: 3.7300, Val Loss: 1.5997
  Epoch 10... Train Loss: 0.4355, Val Loss: 0.8103
  Epoch 20... Train Loss: 0.3170, Val Loss: 0.5203
  Epoch 30... Train Loss: 0.3062, Val Loss: 0.4970
  Epoch 40... Train Loss: 0.2629, Val Loss: 0.4894
  Epoch 50... Train Loss: 0.2566, Val Loss: 0.4886
Fold 4 - MSE: 38.6166, RMSE: 6.2142, MAE: 4.8504
Starting fold 5...
  Epoch 0... Train Loss: 2.3200, Val Loss: 1.8182
  Epoch 10... Train Loss: 0.4297, Val Loss: 0.9876
  Epoch 20... Train Loss: 0.3619, Val Loss: 0.8712
  Epoch 30... Train Loss: 0.3111, Val Loss: 0.8032
  Epoch 40... Train Loss: 0.3011, Val Loss: 0.8512
  Epoch 50... Train Loss: 0.2741, Val Loss: 0.7478

[INFO 04-02 09:59:21] ax.service.ax_client: Completed trial 19 with data: {'avg_rmse_nonzero': 5.742083}.

Fold 5 - MSE: 4.9182, RMSE: 2.2177, MAE: 1.7929

Mean CV MSE: 36.2378, Mean CV RMSE: 5.7421, Mean CV MAE: 3.9113
Completed trial 19 with mean RMSE: 5.7421 ± 0.9036
Saved Ax client checkpoint

[INFO 04-02 09:59:23] ax.service.ax_client: Generated new trial 20 with parameters {'dropout_rate': 0.5, 'weight_decay': 1e-06, 'lr': 1e-05, 'batch_size': 32, 'early_stopping_patience': 10, 'n_layers': 2, 'hidden1': 128, 'hidden2': 1024, 'hidden3': 512, 'activation': 'relu'} using model BoTorch.

Starting trial 20 with parameters: {'dropout_rate': 0.5, 'weight_decay': 1e-06, 'lr': 1e-05, 'batch_size': 32, 'early_stopping_patience': 10, 'n_layers': 2, 'hidden1': 128, 'hidden2': 1024, 'hidden3': 512, 'activation': 'relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 1.2431, Val Loss: 0.8601
  Epoch 10... Train Loss: 0.6953, Val Loss: 0.5037
  Epoch 20... Train Loss: 0.6486, Val Loss: 0.4150
Fold 1 - MSE: 38.5836, RMSE: 6.2116, MAE: 4.5106
Starting fold 2...
  Epoch 0... Train Loss: 1.1819, Val Loss: 0.9103
  Epoch 10... Train Loss: 0.7676, Val Loss: 0.6854
  Epoch 20... Train Loss: 0.5686, Val Loss: 0.5576
  Epoch 30... Train Loss: 0.5502, Val Loss: 0.5642
Fold 2 - MSE: 45.3381, RMSE: 6.7334, MAE: 4.7227
Starting fold 3...
  Epoch 0... Train Loss: 1.1989, Val Loss: 1.0030
  Epoch 10... Train Loss: 0.6856, Val Loss: 0.5786
  Epoch 20... Train Loss: 0.6429, Val Loss: 0.5117
  Epoch 30... Train Loss: 0.5409, Val Loss: 0.4945
  Epoch 40... Train Loss: 0.5425, Val Loss: 0.4583
  Epoch 50... Train Loss: 0.5166, Val Loss: 0.4481
Fold 3 - MSE: 53.6513, RMSE: 7.3247, MAE: 4.9950
Starting fold 4...
  Epoch 0... Train Loss: 1.1879, Val Loss: 0.6085
  Epoch 10... Train Loss: 0.7196, Val Loss: 0.4757
  Epoch 20... Train Loss: 0.6040, Val Loss: 0.4735
  Epoch 30... Train Loss: 0.5906, Val Loss: 0.4515
  Epoch 40... Train Loss: 0.5399, Val Loss: 0.4530
  Epoch 50... Train Loss: 0.5333, Val Loss: 0.4481
  Epoch 60... Train Loss: 0.5922, Val Loss: 0.4477
  Epoch 70... Train Loss: 0.5120, Val Loss: 0.4432
Fold 4 - MSE: 45.1055, RMSE: 6.7161, MAE: 5.1604
Starting fold 5...
  Epoch 0... Train Loss: 1.1725, Val Loss: 1.6321
  Epoch 10... Train Loss: 0.7264, Val Loss: 0.9348
  Epoch 20... Train Loss: 0.6335, Val Loss: 0.9041
  Epoch 30... Train Loss: 0.5818, Val Loss: 0.8622

[INFO 04-02 09:59:40] ax.service.ax_client: Completed trial 20 with data: {'avg_rmse_nonzero': 7.17579}.

  Epoch 40... Train Loss: 0.5971, Val Loss: 0.9249
Fold 5 - MSE: 79.0901, RMSE: 8.8933, MAE: 7.6852

Mean CV MSE: 52.3537, Mean CV RMSE: 7.1758, Mean CV MAE: 5.4148
Completed trial 20 with mean RMSE: 7.1758 ± 0.4642
Saved Ax client checkpoint

[INFO 04-02 09:59:42] ax.service.ax_client: Generated new trial 21 with parameters {'dropout_rate': 0.456634, 'weight_decay': 1.8e-05, 'lr': 5.5e-05, 'batch_size': 32, 'early_stopping_patience': 15, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 64, 'hidden3': 512, 'activation': 'leaky_relu'} using model BoTorch.

Starting trial 21 with parameters: {'dropout_rate': 0.4566335138008231, 'weight_decay': 1.7688456681951543e-05, 'lr': 5.489948266124588e-05, 'batch_size': 32, 'early_stopping_patience': 15, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 64, 'hidden3': 512, 'activation': 'leaky_relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 1.0946, Val Loss: 0.7802
  Epoch 10... Train Loss: 0.6356, Val Loss: 0.4543
  Epoch 20... Train Loss: 0.7585, Val Loss: 0.6980
  Epoch 30... Train Loss: 0.5519, Val Loss: 0.3337
  Epoch 40... Train Loss: 0.5565, Val Loss: 0.3263
Fold 1 - MSE: 38.7698, RMSE: 6.2265, MAE: 4.1760
Starting fold 2...
  Epoch 0... Train Loss: 1.0767, Val Loss: 0.8266
  Epoch 10... Train Loss: 0.6003, Val Loss: 0.7701
  Epoch 20... Train Loss: 0.6003, Val Loss: 0.6010
  Epoch 30... Train Loss: 0.4929, Val Loss: 0.5974
  Epoch 40... Train Loss: 0.4818, Val Loss: 0.5810
  Epoch 50... Train Loss: 0.4339, Val Loss: 0.5504
  Epoch 60... Train Loss: 0.4590, Val Loss: 0.5112
  Epoch 70... Train Loss: 0.4815, Val Loss: 0.5035
  Epoch 80... Train Loss: 0.3975, Val Loss: 0.5138
Fold 2 - MSE: 51.3085, RMSE: 7.1630, MAE: 4.7881
Starting fold 3...
  Epoch 0... Train Loss: 1.1863, Val Loss: 0.9265
  Epoch 10... Train Loss: 0.6315, Val Loss: 0.4714
  Epoch 20... Train Loss: 0.5576, Val Loss: 0.4693
  Epoch 30... Train Loss: 0.4954, Val Loss: 0.4362
Fold 3 - MSE: 55.1030, RMSE: 7.4231, MAE: 4.2798
Starting fold 4...
  Epoch 0... Train Loss: 1.1457, Val Loss: 0.7742
  Epoch 10... Train Loss: 0.5683, Val Loss: 0.6448
  Epoch 20... Train Loss: 0.5126, Val Loss: 0.5231
  Epoch 30... Train Loss: 0.4368, Val Loss: 0.5636
Fold 4 - MSE: 40.6483, RMSE: 6.3756, MAE: 5.0491
Starting fold 5...
  Epoch 0... Train Loss: 1.0332, Val Loss: 1.3996
  Epoch 10... Train Loss: 0.6204, Val Loss: 0.8196
  Epoch 20... Train Loss: 0.5136, Val Loss: 0.9283
  Epoch 30... Train Loss: 0.4657, Val Loss: 0.7937
  Epoch 40... Train Loss: 0.4986, Val Loss: 0.8582

[INFO 04-02 10:00:04] ax.service.ax_client: Completed trial 21 with data: {'avg_rmse_nonzero': 6.348899}.

Fold 5 - MSE: 20.7592, RMSE: 4.5562, MAE: 4.0476

Mean CV MSE: 41.3177, Mean CV RMSE: 6.3489, Mean CV MAE: 4.4681
Completed trial 21 with mean RMSE: 6.3489 ± 0.5023
Saved Ax client checkpoint

[INFO 04-02 10:00:06] ax.service.ax_client: Generated new trial 22 with parameters {'dropout_rate': 0.11604, 'weight_decay': 1e-06, 'lr': 0.006525, 'batch_size': 256, 'early_stopping_patience': 12, 'n_layers': 2, 'hidden1': 128, 'hidden2': 1024, 'hidden3': 256, 'activation': 'leaky_relu'} using model BoTorch.

Starting trial 22 with parameters: {'dropout_rate': 0.11603976835822531, 'weight_decay': 1e-06, 'lr': 0.006525016308941868, 'batch_size': 256, 'early_stopping_patience': 12, 'n_layers': 2, 'hidden1': 128, 'hidden2': 1024, 'hidden3': 256, 'activation': 'leaky_relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 5.2236, Val Loss: 2487.0398
  Epoch 10... Train Loss: 1.0393, Val Loss: 1.2145
  Epoch 20... Train Loss: 0.5362, Val Loss: 0.5311
  Epoch 30... Train Loss: 0.4170, Val Loss: 0.5106
Fold 1 - MSE: 39.5248, RMSE: 6.2869, MAE: 4.2005
Starting fold 2...
  Epoch 0... Train Loss: 18.5197, Val Loss: 1157.9167
  Epoch 10... Train Loss: 0.9083, Val Loss: 0.9883
  Epoch 20... Train Loss: 0.4108, Val Loss: 0.6651
  Epoch 30... Train Loss: 0.3257, Val Loss: 0.5088
  Epoch 40... Train Loss: 0.2882, Val Loss: 0.4859
  Epoch 50... Train Loss: 0.2689, Val Loss: 0.4652
  Epoch 60... Train Loss: 0.2717, Val Loss: 0.4632
  Epoch 70... Train Loss: 0.2592, Val Loss: 0.4409
Fold 2 - MSE: 42.7148, RMSE: 6.5357, MAE: 4.1604
Starting fold 3...
  Epoch 0... Train Loss: 14.8669, Val Loss: 487.3204
  Epoch 10... Train Loss: 0.6199, Val Loss: 0.8540
  Epoch 20... Train Loss: 0.3854, Val Loss: 0.6104
  Epoch 30... Train Loss: 0.3231, Val Loss: 0.4842
  Epoch 40... Train Loss: 0.2668, Val Loss: 0.4319
  Epoch 50... Train Loss: 0.2345, Val Loss: 0.4432
  Epoch 60... Train Loss: 0.2069, Val Loss: 0.4429
Fold 3 - MSE: 26.4206, RMSE: 5.1401, MAE: 3.4039
Starting fold 4...
  Epoch 0... Train Loss: 20.2190, Val Loss: 588.5389
  Epoch 10... Train Loss: 0.7270, Val Loss: 0.7027
  Epoch 20... Train Loss: 0.4504, Val Loss: 0.6319
Fold 4 - MSE: 37.1347, RMSE: 6.0938, MAE: 4.5075
Starting fold 5...
  Epoch 0... Train Loss: 18.2331, Val Loss: 239.2464
  Epoch 10... Train Loss: 0.7064, Val Loss: 1.7074
  Epoch 20... Train Loss: 0.4721, Val Loss: 1.1475
  Epoch 30... Train Loss: 0.3535, Val Loss: 0.9610
  Epoch 40... Train Loss: 0.3214, Val Loss: 0.9290
  Epoch 50... Train Loss: 0.2617, Val Loss: 0.8456
  Epoch 60... Train Loss: 0.2473, Val Loss: 0.8389
  Epoch 70... Train Loss: 0.2460, Val Loss: 0.8108
  Epoch 80... Train Loss: 0.2264, Val Loss: 0.8091
  Epoch 90... Train Loss: 0.2300, Val Loss: 0.7862
  Epoch 100... Train Loss: 0.2220, Val Loss: 0.7739

[INFO 04-02 10:00:12] ax.service.ax_client: Completed trial 22 with data: {'avg_rmse_nonzero': 5.727309}.

  Epoch 110... Train Loss: 0.2172, Val Loss: 0.7717
Fold 5 - MSE: 20.9771, RMSE: 4.5801, MAE: 4.2821

Mean CV MSE: 33.3544, Mean CV RMSE: 5.7273, Mean CV MAE: 4.1109
Completed trial 22 with mean RMSE: 5.7273 ± 0.3716
Saved Ax client checkpoint

[INFO 04-02 10:00:15] ax.service.ax_client: Generated new trial 23 with parameters {'dropout_rate': 0.0, 'weight_decay': 1e-06, 'lr': 1e-05, 'batch_size': 32, 'early_stopping_patience': 23, 'n_layers': 1, 'hidden1': 128, 'hidden2': 1024, 'hidden3': 512, 'activation': 'leaky_relu'} using model BoTorch.

Starting trial 23 with parameters: {'dropout_rate': 0.0, 'weight_decay': 1e-06, 'lr': 1e-05, 'batch_size': 32, 'early_stopping_patience': 23, 'n_layers': 1, 'hidden1': 128, 'hidden2': 1024, 'hidden3': 512, 'activation': 'leaky_relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 0.8016, Val Loss: 0.7702
  Epoch 10... Train Loss: 0.3484, Val Loss: 0.3809
  Epoch 20... Train Loss: 0.3072, Val Loss: 0.4075
  Epoch 30... Train Loss: 0.3032, Val Loss: 0.3334
  Epoch 40... Train Loss: 0.2424, Val Loss: 0.3336
Fold 1 - MSE: 37.9136, RMSE: 6.1574, MAE: 4.2622
Starting fold 2...
  Epoch 0... Train Loss: 0.8376, Val Loss: 0.7420
  Epoch 10... Train Loss: 0.3157, Val Loss: 0.5842
  Epoch 20... Train Loss: 0.2577, Val Loss: 0.4794
  Epoch 30... Train Loss: 0.2161, Val Loss: 0.4927
  Epoch 40... Train Loss: 0.2114, Val Loss: 0.5159
  Epoch 50... Train Loss: 0.1906, Val Loss: 0.4948
  Epoch 60... Train Loss: 0.1804, Val Loss: 0.4476
Fold 2 - MSE: 32.5651, RMSE: 5.7066, MAE: 3.2967
Starting fold 3...
  Epoch 0... Train Loss: 0.8809, Val Loss: 0.8179
  Epoch 10... Train Loss: 0.2948, Val Loss: 0.4792
  Epoch 20... Train Loss: 0.2416, Val Loss: 0.4358
  Epoch 30... Train Loss: 0.2129, Val Loss: 0.3915
  Epoch 40... Train Loss: 0.2062, Val Loss: 0.3852
  Epoch 50... Train Loss: 0.1963, Val Loss: 0.3604
  Epoch 60... Train Loss: 0.1886, Val Loss: 0.3719
  Epoch 70... Train Loss: 0.1749, Val Loss: 0.3508
Fold 3 - MSE: 76.9680, RMSE: 8.7731, MAE: 6.1434
Starting fold 4...
  Epoch 0... Train Loss: 0.9314, Val Loss: 0.6572
  Epoch 10... Train Loss: 0.2741, Val Loss: 0.4916
  Epoch 20... Train Loss: 0.2000, Val Loss: 0.4497
  Epoch 30... Train Loss: 0.1849, Val Loss: 0.4285
  Epoch 40... Train Loss: 0.1591, Val Loss: 0.4412
  Epoch 50... Train Loss: 0.1555, Val Loss: 0.4353
  Epoch 60... Train Loss: 0.1593, Val Loss: 0.4296
  Epoch 70... Train Loss: 0.1496, Val Loss: 0.4304
  Epoch 80... Train Loss: 0.1667, Val Loss: 0.4386
Fold 4 - MSE: 32.0559, RMSE: 5.6618, MAE: 4.5662
Starting fold 5...
  Epoch 0... Train Loss: 0.8937, Val Loss: 1.5462
  Epoch 10... Train Loss: 0.3391, Val Loss: 0.8203
  Epoch 20... Train Loss: 0.2547, Val Loss: 0.7426
  Epoch 30... Train Loss: 0.2238, Val Loss: 0.6809
  Epoch 40... Train Loss: 0.2115, Val Loss: 0.7349
  Epoch 50... Train Loss: 0.2075, Val Loss: 0.7684
  Epoch 60... Train Loss: 0.2067, Val Loss: 0.6955

[INFO 04-02 10:00:33] ax.service.ax_client: Completed trial 23 with data: {'avg_rmse_nonzero': 8.103287}.

  Epoch 70... Train Loss: 0.2096, Val Loss: 0.6847
Fold 5 - MSE: 202.1376, RMSE: 14.2175, MAE: 9.1018

Mean CV MSE: 76.3280, Mean CV RMSE: 8.1033, Mean CV MAE: 5.4741
Completed trial 23 with mean RMSE: 8.1033 ± 1.6329
Saved Ax client checkpoint

[INFO 04-02 10:00:39] ax.service.ax_client: Generated new trial 24 with parameters {'dropout_rate': 0.00899, 'weight_decay': 3e-06, 'lr': 0.01, 'batch_size': 256, 'early_stopping_patience': 29, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 512, 'hidden3': 32, 'activation': 'leaky_relu'} using model BoTorch.

Starting trial 24 with parameters: {'dropout_rate': 0.008989869123602882, 'weight_decay': 3.248869572728746e-06, 'lr': 0.01, 'batch_size': 256, 'early_stopping_patience': 29, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 512, 'hidden3': 32, 'activation': 'leaky_relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 4.1225, Val Loss: 18444.0723
  Epoch 10... Train Loss: 0.9871, Val Loss: 1.1404
  Epoch 20... Train Loss: 0.5294, Val Loss: 0.6424
  Epoch 30... Train Loss: 0.4130, Val Loss: 0.6016
  Epoch 40... Train Loss: 0.4376, Val Loss: 0.5028
  Epoch 50... Train Loss: 0.4743, Val Loss: 0.3637
  Epoch 60... Train Loss: 0.3255, Val Loss: 0.4146
  Epoch 70... Train Loss: 0.2777, Val Loss: 0.3457
  Epoch 80... Train Loss: 0.3648, Val Loss: 0.3745
  Epoch 90... Train Loss: 0.2715, Val Loss: 0.3227
  Epoch 100... Train Loss: 0.3040, Val Loss: 0.3225
  Epoch 110... Train Loss: 0.2667, Val Loss: 0.3141
  Epoch 120... Train Loss: 0.3713, Val Loss: 0.3243
Fold 1 - MSE: 38.8044, RMSE: 6.2293, MAE: 4.0449
Starting fold 2...
  Epoch 0... Train Loss: 10.4589, Val Loss: 290.2753
  Epoch 10... Train Loss: 0.6593, Val Loss: 0.9258
  Epoch 20... Train Loss: 0.4098, Val Loss: 0.6138
  Epoch 30... Train Loss: 0.4386, Val Loss: 0.5491
  Epoch 40... Train Loss: 0.2390, Val Loss: 0.4481
  Epoch 50... Train Loss: 0.2438, Val Loss: 0.3816
  Epoch 60... Train Loss: 0.2774, Val Loss: 0.3975
  Epoch 70... Train Loss: 0.2009, Val Loss: 0.3718
  Epoch 80... Train Loss: 0.1851, Val Loss: 0.3566
  Epoch 90... Train Loss: 0.1758, Val Loss: 0.3392
  Epoch 100... Train Loss: 0.1697, Val Loss: 0.3602
  Epoch 110... Train Loss: 0.1409, Val Loss: 0.3623
Fold 2 - MSE: 32.6782, RMSE: 5.7165, MAE: 3.3552
Starting fold 3...
  Epoch 0... Train Loss: 12.4816, Val Loss: 154.4559
  Epoch 10... Train Loss: 0.6656, Val Loss: 1.0477
  Epoch 20... Train Loss: 0.3829, Val Loss: 0.6267
  Epoch 30... Train Loss: 0.2919, Val Loss: 0.5567
  Epoch 40... Train Loss: 0.2297, Val Loss: 0.4474
  Epoch 50... Train Loss: 0.2104, Val Loss: 0.5294
  Epoch 60... Train Loss: 0.1868, Val Loss: 0.4618
  Epoch 70... Train Loss: 0.1851, Val Loss: 0.4623
  Epoch 80... Train Loss: 0.1713, Val Loss: 0.4008
  Epoch 90... Train Loss: 0.1453, Val Loss: 0.3813
  Epoch 100... Train Loss: 0.1669, Val Loss: 0.4279
  Epoch 110... Train Loss: 0.1423, Val Loss: 0.3994
  Epoch 120... Train Loss: 0.1478, Val Loss: 0.3815
Fold 3 - MSE: 26.6833, RMSE: 5.1656, MAE: 3.1161
Starting fold 4...
  Epoch 0... Train Loss: 8.6415, Val Loss: 8313.1982
  Epoch 10... Train Loss: 0.6224, Val Loss: 0.6175
  Epoch 20... Train Loss: 0.2899, Val Loss: 0.5974
  Epoch 30... Train Loss: 0.2184, Val Loss: 0.5284
  Epoch 40... Train Loss: 0.2057, Val Loss: 0.4818
  Epoch 50... Train Loss: 0.1537, Val Loss: 0.4523
  Epoch 60... Train Loss: 0.1734, Val Loss: 0.4828
  Epoch 70... Train Loss: 0.1338, Val Loss: 0.4558
  Epoch 80... Train Loss: 0.1380, Val Loss: 0.4582
Fold 4 - MSE: 39.0828, RMSE: 6.2516, MAE: 4.9478
Starting fold 5...
  Epoch 0... Train Loss: 14.0611, Val Loss: 499.0067
  Epoch 10... Train Loss: 0.6829, Val Loss: 1.3091
  Epoch 20... Train Loss: 0.4490, Val Loss: 1.0000
  Epoch 30... Train Loss: 0.2837, Val Loss: 0.8603
  Epoch 40... Train Loss: 0.2586, Val Loss: 0.8143
  Epoch 50... Train Loss: 0.2104, Val Loss: 0.7711
  Epoch 60... Train Loss: 0.1870, Val Loss: 0.7808
  Epoch 70... Train Loss: 0.1802, Val Loss: 0.7716
  Epoch 80... Train Loss: 0.1850, Val Loss: 0.7591
  Epoch 90... Train Loss: 0.1620, Val Loss: 0.7380
  Epoch 100... Train Loss: 0.1614, Val Loss: 0.7345

[INFO 04-02 10:00:49] ax.service.ax_client: Completed trial 24 with data: {'avg_rmse_nonzero': 5.114148}.

  Epoch 110... Train Loss: 0.1460, Val Loss: 0.7541
Fold 5 - MSE: 4.8741, RMSE: 2.2077, MAE: 1.6558

Mean CV MSE: 28.4245, Mean CV RMSE: 5.1141, Mean CV MAE: 3.4240
Completed trial 24 with mean RMSE: 5.1141 ± 0.7533
Saved Ax client checkpoint

[INFO 04-02 10:00:51] ax.service.ax_client: Generated new trial 25 with parameters {'dropout_rate': 0.098536, 'weight_decay': 0.001022, 'lr': 0.01, 'batch_size': 256, 'early_stopping_patience': 48, 'n_layers': 3, 'hidden1': 128, 'hidden2': 1024, 'hidden3': 64, 'activation': 'leaky_relu'} using model BoTorch.

Starting trial 25 with parameters: {'dropout_rate': 0.09853569199392988, 'weight_decay': 0.0010220516993040237, 'lr': 0.01, 'batch_size': 256, 'early_stopping_patience': 48, 'n_layers': 3, 'hidden1': 128, 'hidden2': 1024, 'hidden3': 64, 'activation': 'leaky_relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 3.1924, Val Loss: 16389.6973
  Epoch 10... Train Loss: 0.8122, Val Loss: 1.2767
  Epoch 20... Train Loss: 0.4600, Val Loss: 0.5612
  Epoch 30... Train Loss: 0.4024, Val Loss: 0.5958
  Epoch 40... Train Loss: 0.3195, Val Loss: 0.4258
  Epoch 50... Train Loss: 0.3877, Val Loss: 0.5245
  Epoch 60... Train Loss: 0.3934, Val Loss: 0.4459
  Epoch 70... Train Loss: 0.3294, Val Loss: 0.4021
  Epoch 80... Train Loss: 0.3425, Val Loss: 0.4583
  Epoch 90... Train Loss: 0.2988, Val Loss: 0.3428
  Epoch 100... Train Loss: 0.3185, Val Loss: 0.3094
  Epoch 110... Train Loss: 0.2756, Val Loss: 0.3018
  Epoch 120... Train Loss: 0.5032, Val Loss: 0.4563
  Epoch 130... Train Loss: 0.3531, Val Loss: 0.2773
  Epoch 140... Train Loss: 0.2969, Val Loss: 0.3498
  Epoch 150... Train Loss: 0.3941, Val Loss: 0.3210
  Epoch 160... Train Loss: 0.2525, Val Loss: 0.3071
  Epoch 170... Train Loss: 0.2951, Val Loss: 0.3214
Fold 1 - MSE: 37.5176, RMSE: 6.1252, MAE: 4.2098
Starting fold 2...
  Epoch 0... Train Loss: 8.5381, Val Loss: 9887.6484
  Epoch 10... Train Loss: 0.7040, Val Loss: 0.7891
  Epoch 20... Train Loss: 0.4165, Val Loss: 0.7020
  Epoch 30... Train Loss: 0.3155, Val Loss: 0.5866
  Epoch 40... Train Loss: 0.2672, Val Loss: 0.4145
  Epoch 50... Train Loss: 0.3088, Val Loss: 0.4805
  Epoch 60... Train Loss: 0.3334, Val Loss: 0.4992
  Epoch 70... Train Loss: 0.3816, Val Loss: 0.4736
  Epoch 80... Train Loss: 0.2384, Val Loss: 0.4145
  Epoch 90... Train Loss: 0.2972, Val Loss: 0.4073
  Epoch 100... Train Loss: 0.2310, Val Loss: 0.3596
  Epoch 110... Train Loss: 0.1779, Val Loss: 0.3514
  Epoch 120... Train Loss: 0.2112, Val Loss: 0.3602
  Epoch 130... Train Loss: 0.2336, Val Loss: 0.4056
  Epoch 140... Train Loss: 0.1720, Val Loss: 0.3116
  Epoch 150... Train Loss: 0.2239, Val Loss: 0.3442
  Epoch 160... Train Loss: 0.1627, Val Loss: 0.3497
  Epoch 170... Train Loss: 0.1825, Val Loss: 0.3470
  Epoch 180... Train Loss: 0.1518, Val Loss: 0.3468
Fold 2 - MSE: 35.6614, RMSE: 5.9717, MAE: 3.5880
Starting fold 3...
  Epoch 0... Train Loss: 17.6697, Val Loss: 1226.2739
  Epoch 10... Train Loss: 0.6996, Val Loss: 0.9363
  Epoch 20... Train Loss: 0.3700, Val Loss: 0.6380
  Epoch 30... Train Loss: 0.3314, Val Loss: 0.5936
  Epoch 40... Train Loss: 0.2849, Val Loss: 0.5454
  Epoch 50... Train Loss: 0.2637, Val Loss: 0.4799
  Epoch 60... Train Loss: 0.2430, Val Loss: 0.4681
  Epoch 70... Train Loss: 0.2193, Val Loss: 0.5298
  Epoch 80... Train Loss: 0.2286, Val Loss: 0.4456
  Epoch 90... Train Loss: 0.2438, Val Loss: 0.3874
  Epoch 100... Train Loss: 0.2011, Val Loss: 0.3973
  Epoch 110... Train Loss: 0.1858, Val Loss: 0.3787
  Epoch 120... Train Loss: 0.2196, Val Loss: 0.4357
  Epoch 130... Train Loss: 0.1828, Val Loss: 0.3784
  Epoch 140... Train Loss: 0.1766, Val Loss: 0.4170
  Epoch 150... Train Loss: 0.1835, Val Loss: 0.3556
  Epoch 160... Train Loss: 0.1494, Val Loss: 0.4015
  Epoch 170... Train Loss: 0.1639, Val Loss: 0.3839
  Epoch 180... Train Loss: 0.1530, Val Loss: 0.3674
Fold 3 - MSE: 16.1496, RMSE: 4.0187, MAE: 2.7308
Starting fold 4...
  Epoch 0... Train Loss: 12.7323, Val Loss: 148.9884
  Epoch 10... Train Loss: 0.7349, Val Loss: 0.6162
  Epoch 20... Train Loss: 0.4407, Val Loss: 0.4580
  Epoch 30... Train Loss: 0.2886, Val Loss: 0.4366
  Epoch 40... Train Loss: 0.2494, Val Loss: 0.3586
  Epoch 50... Train Loss: 0.1968, Val Loss: 0.3888
  Epoch 60... Train Loss: 0.2109, Val Loss: 0.4115
  Epoch 70... Train Loss: 0.1856, Val Loss: 0.4167
  Epoch 80... Train Loss: 0.1890, Val Loss: 0.4370
  Epoch 90... Train Loss: 0.1909, Val Loss: 0.4229
  Epoch 100... Train Loss: 0.1499, Val Loss: 0.3916
  Epoch 110... Train Loss: 0.1422, Val Loss: 0.3943
  Epoch 120... Train Loss: 0.1387, Val Loss: 0.3813
Fold 4 - MSE: 31.3875, RMSE: 5.6025, MAE: 4.5138
Starting fold 5...
  Epoch 0... Train Loss: 7.3872, Val Loss: 17244.5859
  Epoch 10... Train Loss: 0.7691, Val Loss: 1.4864
  Epoch 20... Train Loss: 0.5259, Val Loss: 1.2602
  Epoch 30... Train Loss: 0.3011, Val Loss: 1.1047
  Epoch 40... Train Loss: 0.3472, Val Loss: 0.9946
  Epoch 50... Train Loss: 0.3046, Val Loss: 0.9093
  Epoch 60... Train Loss: 0.2616, Val Loss: 0.7343
  Epoch 70... Train Loss: 0.2907, Val Loss: 0.7502
  Epoch 80... Train Loss: 0.2385, Val Loss: 0.7772
  Epoch 90... Train Loss: 0.2537, Val Loss: 0.7736
  Epoch 100... Train Loss: 0.2098, Val Loss: 0.7888
  Epoch 110... Train Loss: 0.1900, Val Loss: 0.7558
  Epoch 120... Train Loss: 0.1864, Val Loss: 0.7721
  Epoch 130... Train Loss: 0.1862, Val Loss: 0.7200
  Epoch 140... Train Loss: 0.1667, Val Loss: 0.7018
  Epoch 150... Train Loss: 0.1715, Val Loss: 0.7393
  Epoch 160... Train Loss: 0.1809, Val Loss: 0.6632
  Epoch 170... Train Loss: 0.1320, Val Loss: 0.6639
  Epoch 180... Train Loss: 0.1495, Val Loss: 0.6743
  Epoch 190... Train Loss: 0.1361, Val Loss: 0.6073
  Epoch 200... Train Loss: 0.1365, Val Loss: 0.7026
  Epoch 210... Train Loss: 0.1240, Val Loss: 0.6419
  Epoch 220... Train Loss: 0.1141, Val Loss: 0.6387
  Epoch 230... Train Loss: 0.1203, Val Loss: 0.6679
  Epoch 240... Train Loss: 0.1054, Val Loss: 0.6644
  Epoch 250... Train Loss: 0.0960, Val Loss: 0.6686
  Epoch 260... Train Loss: 0.0795, Val Loss: 0.6298

[INFO 04-02 10:01:06] ax.service.ax_client: Completed trial 25 with data: {'avg_rmse_nonzero': 4.890409}.

  Epoch 270... Train Loss: 0.0760, Val Loss: 0.6592
Fold 5 - MSE: 7.4751, RMSE: 2.7341, MAE: 2.2865

Mean CV MSE: 25.6382, Mean CV RMSE: 4.8904, Mean CV MAE: 3.4658
Completed trial 25 with mean RMSE: 4.8904 ± 0.6561
Saved Ax client checkpoint

[INFO 04-02 10:01:07] ax.service.ax_client: Generated new trial 26 with parameters {'dropout_rate': 0.0, 'weight_decay': 0.01, 'lr': 0.01, 'batch_size': 64, 'early_stopping_patience': 50, 'n_layers': 3, 'hidden1': 128, 'hidden2': 1024, 'hidden3': 32, 'activation': 'leaky_relu'} using model BoTorch.

Starting trial 26 with parameters: {'dropout_rate': 0.0, 'weight_decay': 0.01, 'lr': 0.01, 'batch_size': 64, 'early_stopping_patience': 50, 'n_layers': 3, 'hidden1': 128, 'hidden2': 1024, 'hidden3': 32, 'activation': 'leaky_relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 8.7604, Val Loss: 882.9566
  Epoch 10... Train Loss: 0.6829, Val Loss: 0.6207
  Epoch 20... Train Loss: 0.6190, Val Loss: 0.6754
  Epoch 30... Train Loss: 0.5367, Val Loss: 0.4745
  Epoch 40... Train Loss: 0.3837, Val Loss: 0.3948
  Epoch 50... Train Loss: 0.5033, Val Loss: 0.5991
  Epoch 60... Train Loss: 0.3518, Val Loss: 0.3343
  Epoch 70... Train Loss: 0.3819, Val Loss: 0.4420
  Epoch 80... Train Loss: 0.3202, Val Loss: 0.2618
  Epoch 90... Train Loss: 0.2757, Val Loss: 0.6437
  Epoch 100... Train Loss: 0.2611, Val Loss: 0.2881
Fold 1 - MSE: 40.6526, RMSE: 6.3759, MAE: 4.1024
Starting fold 2...
  Epoch 0... Train Loss: 4.3596, Val Loss: 14.7590
  Epoch 10... Train Loss: 0.7600, Val Loss: 1.2796
  Epoch 20... Train Loss: 0.5826, Val Loss: 0.8699
  Epoch 30... Train Loss: 0.5285, Val Loss: 0.9474
  Epoch 40... Train Loss: 0.5163, Val Loss: 0.5459
  Epoch 50... Train Loss: 0.4153, Val Loss: 0.6865
  Epoch 60... Train Loss: 0.4057, Val Loss: 0.5753
  Epoch 70... Train Loss: 0.4458, Val Loss: 0.6045
  Epoch 80... Train Loss: 0.4279, Val Loss: 0.4753
  Epoch 90... Train Loss: 0.4074, Val Loss: 0.5300
  Epoch 100... Train Loss: 0.4787, Val Loss: 0.4432
  Epoch 110... Train Loss: 0.3571, Val Loss: 0.3944
  Epoch 120... Train Loss: 0.3347, Val Loss: 0.4411
  Epoch 130... Train Loss: 0.4184, Val Loss: 0.5932
  Epoch 140... Train Loss: 0.3148, Val Loss: 0.3802
  Epoch 150... Train Loss: 0.4263, Val Loss: 0.4146
  Epoch 160... Train Loss: 0.3229, Val Loss: 0.3857
  Epoch 170... Train Loss: 0.2649, Val Loss: 0.3762
  Epoch 180... Train Loss: 0.3224, Val Loss: 0.3014
  Epoch 190... Train Loss: 0.2876, Val Loss: 0.3376
  Epoch 200... Train Loss: 0.2078, Val Loss: 0.3129
  Epoch 210... Train Loss: 0.2037, Val Loss: 0.3224
Fold 2 - MSE: 38.4904, RMSE: 6.2041, MAE: 3.7362
Starting fold 3...
  Epoch 0... Train Loss: 4.3162, Val Loss: 9.4058
  Epoch 10... Train Loss: 0.6655, Val Loss: 0.9162
  Epoch 20... Train Loss: 0.5413, Val Loss: 0.5461
  Epoch 30... Train Loss: 0.4900, Val Loss: 0.6894
  Epoch 40... Train Loss: 0.4030, Val Loss: 1.3469
  Epoch 50... Train Loss: 0.4082, Val Loss: 0.6163
  Epoch 60... Train Loss: 0.3451, Val Loss: 0.4483
  Epoch 70... Train Loss: 0.3240, Val Loss: 0.5207
  Epoch 80... Train Loss: 0.3175, Val Loss: 0.3806
  Epoch 90... Train Loss: 0.3465, Val Loss: 0.4072
  Epoch 100... Train Loss: 0.3377, Val Loss: 0.5647
  Epoch 110... Train Loss: 0.3099, Val Loss: 0.4665
  Epoch 120... Train Loss: 0.2912, Val Loss: 0.4529
  Epoch 130... Train Loss: 0.2627, Val Loss: 0.3809
  Epoch 140... Train Loss: 0.2422, Val Loss: 0.5106
  Epoch 150... Train Loss: 0.2465, Val Loss: 0.5113
  Epoch 160... Train Loss: 0.2244, Val Loss: 0.3495
  Epoch 170... Train Loss: 0.2367, Val Loss: 0.3538
  Epoch 180... Train Loss: 0.2125, Val Loss: 0.3559
  Epoch 190... Train Loss: 0.2164, Val Loss: 0.3280
  Epoch 200... Train Loss: 0.2421, Val Loss: 0.3141
  Epoch 210... Train Loss: 0.1995, Val Loss: 0.3791
  Epoch 220... Train Loss: 0.1956, Val Loss: 0.3112
  Epoch 230... Train Loss: 0.1813, Val Loss: 0.3081
  Epoch 240... Train Loss: 0.1895, Val Loss: 0.4095
  Epoch 250... Train Loss: 0.2057, Val Loss: 0.3659
  Epoch 260... Train Loss: 0.1757, Val Loss: 0.2962
  Epoch 270... Train Loss: 0.1698, Val Loss: 0.3033
  Epoch 280... Train Loss: 0.1841, Val Loss: 0.2939
  Epoch 290... Train Loss: 0.1843, Val Loss: 0.3470
  Epoch 300... Train Loss: 0.1949, Val Loss: 0.2924
  Epoch 310... Train Loss: 0.1558, Val Loss: 0.3453
  Epoch 320... Train Loss: 0.1978, Val Loss: 0.3178
Fold 3 - MSE: 142.6532, RMSE: 11.9438, MAE: 5.5545
Starting fold 4...
  Epoch 0... Train Loss: 4.9139, Val Loss: 59.0651
  Epoch 10... Train Loss: 0.7059, Val Loss: 0.5336
  Epoch 20... Train Loss: 0.4993, Val Loss: 0.6811
  Epoch 30... Train Loss: 0.4106, Val Loss: 0.5877
  Epoch 40... Train Loss: 0.3832, Val Loss: 0.9380
  Epoch 50... Train Loss: 0.3021, Val Loss: 0.4039
  Epoch 60... Train Loss: 0.3134, Val Loss: 0.3821
  Epoch 70... Train Loss: 0.3260, Val Loss: 0.4868
  Epoch 80... Train Loss: 0.3099, Val Loss: 0.4924
  Epoch 90... Train Loss: 0.2431, Val Loss: 0.5266
  Epoch 100... Train Loss: 0.2338, Val Loss: 0.5317
  Epoch 110... Train Loss: 0.2000, Val Loss: 0.4341
  Epoch 120... Train Loss: 0.2032, Val Loss: 0.4104
  Epoch 130... Train Loss: 0.1919, Val Loss: 0.4139
  Epoch 140... Train Loss: 0.1976, Val Loss: 0.3715
  Epoch 150... Train Loss: 0.1721, Val Loss: 0.4823
  Epoch 160... Train Loss: 0.1691, Val Loss: 0.4541
  Epoch 170... Train Loss: 0.1600, Val Loss: 0.3778
  Epoch 180... Train Loss: 0.1538, Val Loss: 0.4462
  Epoch 190... Train Loss: 0.1443, Val Loss: 0.4065
Fold 4 - MSE: 51.5644, RMSE: 7.1808, MAE: 5.8324
Starting fold 5...
  Epoch 0... Train Loss: 3.0105, Val Loss: 21.6761
  Epoch 10... Train Loss: 0.7270, Val Loss: 1.1750
  Epoch 20... Train Loss: 0.5469, Val Loss: 1.3017
  Epoch 30... Train Loss: 0.4544, Val Loss: 1.1552
  Epoch 40... Train Loss: 0.4892, Val Loss: 0.9102
  Epoch 50... Train Loss: 0.4599, Val Loss: 0.8548
  Epoch 60... Train Loss: 0.4896, Val Loss: 0.9996
  Epoch 70... Train Loss: 0.4675, Val Loss: 0.9852
  Epoch 80... Train Loss: 0.3811, Val Loss: 0.7711
  Epoch 90... Train Loss: 0.3872, Val Loss: 0.8339
  Epoch 100... Train Loss: 0.3258, Val Loss: 0.9197
  Epoch 110... Train Loss: 0.3266, Val Loss: 0.8349
  Epoch 120... Train Loss: 0.3487, Val Loss: 0.8052
  Epoch 130... Train Loss: 0.3341, Val Loss: 0.7244
  Epoch 140... Train Loss: 0.2612, Val Loss: 0.7368
  Epoch 150... Train Loss: 0.2706, Val Loss: 0.7963
  Epoch 160... Train Loss: 0.2496, Val Loss: 0.8249
  Epoch 170... Train Loss: 0.2348, Val Loss: 0.7856

[INFO 04-02 10:01:51] ax.service.ax_client: Completed trial 26 with data: {'avg_rmse_nonzero': 6.872617}.

  Epoch 180... Train Loss: 0.2150, Val Loss: 0.7589
Fold 5 - MSE: 7.0676, RMSE: 2.6585, MAE: 2.3544

Mean CV MSE: 56.0856, Mean CV RMSE: 6.8726, Mean CV MAE: 4.3160
Completed trial 26 with mean RMSE: 6.8726 ± 1.4877
Saved Ax client checkpoint

[INFO 04-02 10:01:53] ax.service.ax_client: Generated new trial 27 with parameters {'dropout_rate': 0.0, 'weight_decay': 1e-06, 'lr': 0.01, 'batch_size': 256, 'early_stopping_patience': 50, 'n_layers': 3, 'hidden1': 256, 'hidden2': 128, 'hidden3': 256, 'activation': 'leaky_relu'} using model BoTorch.

Starting trial 27 with parameters: {'dropout_rate': 0.0, 'weight_decay': 1e-06, 'lr': 0.01, 'batch_size': 256, 'early_stopping_patience': 50, 'n_layers': 3, 'hidden1': 256, 'hidden2': 128, 'hidden3': 256, 'activation': 'leaky_relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 4.0562, Val Loss: 9941.1670
  Epoch 10... Train Loss: 0.9589, Val Loss: 1.6371
  Epoch 20... Train Loss: 0.4982, Val Loss: 0.6212
  Epoch 30... Train Loss: 0.4184, Val Loss: 0.6065
  Epoch 40... Train Loss: 0.4698, Val Loss: 0.4509
  Epoch 50... Train Loss: 0.4844, Val Loss: 0.3382
  Epoch 60... Train Loss: 0.3537, Val Loss: 0.3542
  Epoch 70... Train Loss: 0.2841, Val Loss: 0.3022
  Epoch 80... Train Loss: 0.3788, Val Loss: 0.3199
  Epoch 90... Train Loss: 0.2822, Val Loss: 0.2814
  Epoch 100... Train Loss: 0.2892, Val Loss: 0.2906
  Epoch 110... Train Loss: 0.2569, Val Loss: 0.2766
  Epoch 120... Train Loss: 0.3771, Val Loss: 0.3047
  Epoch 130... Train Loss: 0.2659, Val Loss: 0.3336
  Epoch 140... Train Loss: 0.2653, Val Loss: 0.2876
  Epoch 150... Train Loss: 0.3776, Val Loss: 0.2807
Fold 1 - MSE: 40.4621, RMSE: 6.3610, MAE: 4.1929
Starting fold 2...
  Epoch 0... Train Loss: 18.5549, Val Loss: 1151.5581
  Epoch 10... Train Loss: 0.7149, Val Loss: 0.7057
  Epoch 20... Train Loss: 0.4264, Val Loss: 0.7023
  Epoch 30... Train Loss: 0.3426, Val Loss: 0.5918
  Epoch 40... Train Loss: 0.2548, Val Loss: 0.4847
  Epoch 50... Train Loss: 0.2584, Val Loss: 0.4257
  Epoch 60... Train Loss: 0.2661, Val Loss: 0.4585
  Epoch 70... Train Loss: 0.2249, Val Loss: 0.3892
  Epoch 80... Train Loss: 0.2022, Val Loss: 0.4158
  Epoch 90... Train Loss: 0.2071, Val Loss: 0.3869
  Epoch 100... Train Loss: 0.1792, Val Loss: 0.3976
  Epoch 110... Train Loss: 0.1432, Val Loss: 0.3569
  Epoch 120... Train Loss: 0.1678, Val Loss: 0.3589
  Epoch 130... Train Loss: 0.1845, Val Loss: 0.4015
  Epoch 140... Train Loss: 0.1372, Val Loss: 0.3514
  Epoch 150... Train Loss: 0.1932, Val Loss: 0.3454
  Epoch 160... Train Loss: 0.1475, Val Loss: 0.3540
  Epoch 170... Train Loss: 0.1415, Val Loss: 0.3623
Fold 2 - MSE: 42.2523, RMSE: 6.5002, MAE: 3.8414
Starting fold 3...
  Epoch 0... Train Loss: 8.0040, Val Loss: 15241.1709
  Epoch 10... Train Loss: 0.6721, Val Loss: 0.9170
  Epoch 20... Train Loss: 0.4084, Val Loss: 0.6588
  Epoch 30... Train Loss: 0.3292, Val Loss: 0.5865
  Epoch 40... Train Loss: 0.2136, Val Loss: 0.4578
  Epoch 50... Train Loss: 0.1974, Val Loss: 0.5824
  Epoch 60... Train Loss: 0.1666, Val Loss: 0.5097
  Epoch 70... Train Loss: 0.1712, Val Loss: 0.5920
  Epoch 80... Train Loss: 0.1811, Val Loss: 0.4547
  Epoch 90... Train Loss: 0.1536, Val Loss: 0.4268
  Epoch 100... Train Loss: 0.1617, Val Loss: 0.4441
  Epoch 110... Train Loss: 0.1327, Val Loss: 0.4236
  Epoch 120... Train Loss: 0.1451, Val Loss: 0.4511
Fold 3 - MSE: 18.9777, RMSE: 4.3563, MAE: 2.8253
Starting fold 4...
  Epoch 0... Train Loss: 8.9005, Val Loss: 11472.5918
  Epoch 10... Train Loss: 0.5982, Val Loss: 1.0143
  Epoch 20... Train Loss: 0.3335, Val Loss: 0.5791
  Epoch 30... Train Loss: 0.2743, Val Loss: 0.6199
  Epoch 40... Train Loss: 0.2085, Val Loss: 0.5767
  Epoch 50... Train Loss: 0.1664, Val Loss: 0.5688
  Epoch 60... Train Loss: 0.1550, Val Loss: 0.4980
  Epoch 70... Train Loss: 0.1438, Val Loss: 0.4810
  Epoch 80... Train Loss: 0.1548, Val Loss: 0.5045
  Epoch 90... Train Loss: 0.1292, Val Loss: 0.4900
  Epoch 100... Train Loss: 0.1307, Val Loss: 0.4769
  Epoch 110... Train Loss: 0.1110, Val Loss: 0.4773
  Epoch 120... Train Loss: 0.1312, Val Loss: 0.4701
  Epoch 130... Train Loss: 0.1400, Val Loss: 0.4710
  Epoch 140... Train Loss: 0.1326, Val Loss: 0.4775
  Epoch 150... Train Loss: 0.1316, Val Loss: 0.4916
  Epoch 160... Train Loss: 0.1157, Val Loss: 0.4807
  Epoch 170... Train Loss: 0.1134, Val Loss: 0.4821
Fold 4 - MSE: 32.8059, RMSE: 5.7276, MAE: 4.3766
Starting fold 5...
  Epoch 0... Train Loss: 8.4151, Val Loss: 2222.3579
  Epoch 10... Train Loss: 0.6734, Val Loss: 1.3894
  Epoch 20... Train Loss: 0.4758, Val Loss: 1.1533
  Epoch 30... Train Loss: 0.3259, Val Loss: 0.9056
  Epoch 40... Train Loss: 0.2370, Val Loss: 0.8345
  Epoch 50... Train Loss: 0.2214, Val Loss: 0.8091
  Epoch 60... Train Loss: 0.1912, Val Loss: 0.8193
  Epoch 70... Train Loss: 0.1983, Val Loss: 0.7838
  Epoch 80... Train Loss: 0.1853, Val Loss: 0.7939
  Epoch 90... Train Loss: 0.1830, Val Loss: 0.7592
  Epoch 100... Train Loss: 0.1774, Val Loss: 0.7575
  Epoch 110... Train Loss: 0.1542, Val Loss: 0.7468
  Epoch 120... Train Loss: 0.1418, Val Loss: 0.7629
  Epoch 130... Train Loss: 0.1356, Val Loss: 0.7050
  Epoch 140... Train Loss: 0.1271, Val Loss: 0.7198
  Epoch 150... Train Loss: 0.1311, Val Loss: 0.7274
  Epoch 160... Train Loss: 0.1247, Val Loss: 0.6979
  Epoch 170... Train Loss: 0.1281, Val Loss: 0.7187
  Epoch 180... Train Loss: 0.1189, Val Loss: 0.6981
  Epoch 190... Train Loss: 0.1167, Val Loss: 0.6974

[INFO 04-02 10:02:06] ax.service.ax_client: Completed trial 27 with data: {'avg_rmse_nonzero': 6.621169}.

  Epoch 200... Train Loss: 0.1134, Val Loss: 0.6952
Fold 5 - MSE: 103.2398, RMSE: 10.1607, MAE: 9.1119

Mean CV MSE: 47.5476, Mean CV RMSE: 6.6212, Mean CV MAE: 4.8696
Completed trial 27 with mean RMSE: 6.6212 ± 0.9628
Saved Ax client checkpoint

[INFO 04-02 10:02:08] ax.service.ax_client: Generated new trial 28 with parameters {'dropout_rate': 0.467687, 'weight_decay': 1e-06, 'lr': 0.01, 'batch_size': 256, 'early_stopping_patience': 45, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 32, 'activation': 'leaky_relu'} using model BoTorch.

Starting trial 28 with parameters: {'dropout_rate': 0.46768719104410583, 'weight_decay': 1.3669871360797735e-06, 'lr': 0.01, 'batch_size': 256, 'early_stopping_patience': 45, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 32, 'activation': 'leaky_relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 5.6240, Val Loss: 486.7208
  Epoch 10... Train Loss: 1.1399, Val Loss: 0.9967
  Epoch 20... Train Loss: 0.5852, Val Loss: 0.5925
  Epoch 30... Train Loss: 0.6185, Val Loss: 0.4688
  Epoch 40... Train Loss: 0.5385, Val Loss: 0.4464
  Epoch 50... Train Loss: 0.5500, Val Loss: 0.3780
  Epoch 60... Train Loss: 0.5295, Val Loss: 0.3440
  Epoch 70... Train Loss: 0.3785, Val Loss: 0.3773
  Epoch 80... Train Loss: 0.4690, Val Loss: 0.2779
  Epoch 90... Train Loss: 0.4121, Val Loss: 0.3088
  Epoch 100... Train Loss: 0.4692, Val Loss: 0.3199
  Epoch 110... Train Loss: 0.3257, Val Loss: 0.2851
  Epoch 120... Train Loss: 0.3982, Val Loss: 0.3073
Fold 1 - MSE: 39.6392, RMSE: 6.2960, MAE: 4.0323
Starting fold 2...
  Epoch 0... Train Loss: 7.3692, Val Loss: 1037.5107
  Epoch 10... Train Loss: 0.6902, Val Loss: 0.8897
  Epoch 20... Train Loss: 0.4711, Val Loss: 0.6450
  Epoch 30... Train Loss: 0.3932, Val Loss: 0.4782
  Epoch 40... Train Loss: 0.3123, Val Loss: 0.4454
  Epoch 50... Train Loss: 0.3356, Val Loss: 0.4037
  Epoch 60... Train Loss: 0.3025, Val Loss: 0.4212
  Epoch 70... Train Loss: 0.2632, Val Loss: 0.3719
  Epoch 80... Train Loss: 0.2871, Val Loss: 0.3902
  Epoch 90... Train Loss: 0.2909, Val Loss: 0.3824
  Epoch 100... Train Loss: 0.2527, Val Loss: 0.3669
  Epoch 110... Train Loss: 0.2024, Val Loss: 0.3889
  Epoch 120... Train Loss: 0.2453, Val Loss: 0.3561
  Epoch 130... Train Loss: 0.2803, Val Loss: 0.3521
  Epoch 140... Train Loss: 0.2376, Val Loss: 0.3653
  Epoch 150... Train Loss: 0.2610, Val Loss: 0.3353
  Epoch 160... Train Loss: 0.2364, Val Loss: 0.3657
  Epoch 170... Train Loss: 0.2293, Val Loss: 0.3352
  Epoch 180... Train Loss: 0.2051, Val Loss: 0.3472
  Epoch 190... Train Loss: 0.2047, Val Loss: 0.3585
Fold 2 - MSE: 40.6906, RMSE: 6.3789, MAE: 3.8212
Starting fold 3...
  Epoch 0... Train Loss: 7.4334, Val Loss: 7923.5464
  Epoch 10... Train Loss: 0.7909, Val Loss: 0.9930
  Epoch 20... Train Loss: 0.4858, Val Loss: 0.5604
  Epoch 30... Train Loss: 0.4091, Val Loss: 0.5004
  Epoch 40... Train Loss: 0.2931, Val Loss: 0.4160
  Epoch 50... Train Loss: 0.2749, Val Loss: 0.4256
  Epoch 60... Train Loss: 0.2577, Val Loss: 0.4388
  Epoch 70... Train Loss: 0.2586, Val Loss: 0.3795
  Epoch 80... Train Loss: 0.2681, Val Loss: 0.3682
  Epoch 90... Train Loss: 0.2317, Val Loss: 0.3975
  Epoch 100... Train Loss: 0.2401, Val Loss: 0.3895
  Epoch 110... Train Loss: 0.2069, Val Loss: 0.3941
  Epoch 120... Train Loss: 0.2217, Val Loss: 0.3841
  Epoch 130... Train Loss: 0.2087, Val Loss: 0.3666
  Epoch 140... Train Loss: 0.2157, Val Loss: 0.3689
Fold 3 - MSE: 31.5825, RMSE: 5.6198, MAE: 3.3828
Starting fold 4...
  Epoch 0... Train Loss: 10.2393, Val Loss: 1913.6626
  Epoch 10... Train Loss: 0.7966, Val Loss: 0.6918
  Epoch 20... Train Loss: 0.5387, Val Loss: 0.5270
  Epoch 30... Train Loss: 0.3711, Val Loss: 0.5504
  Epoch 40... Train Loss: 0.3438, Val Loss: 0.4723
  Epoch 50... Train Loss: 0.2695, Val Loss: 0.4660
  Epoch 60... Train Loss: 0.2706, Val Loss: 0.4982
  Epoch 70... Train Loss: 0.2375, Val Loss: 0.4799
  Epoch 80... Train Loss: 0.2105, Val Loss: 0.4384
  Epoch 90... Train Loss: 0.2140, Val Loss: 0.4630
  Epoch 100... Train Loss: 0.2052, Val Loss: 0.4272
Fold 4 - MSE: 31.8971, RMSE: 5.6477, MAE: 4.4352
Starting fold 5...
  Epoch 0... Train Loss: 8.8139, Val Loss: 3604.5178
  Epoch 10... Train Loss: 0.7835, Val Loss: 1.3681
  Epoch 20... Train Loss: 0.5318, Val Loss: 0.9969
  Epoch 30... Train Loss: 0.4141, Val Loss: 0.9133
  Epoch 40... Train Loss: 0.3597, Val Loss: 0.8725
  Epoch 50... Train Loss: 0.3157, Val Loss: 0.8017
  Epoch 60... Train Loss: 0.2948, Val Loss: 0.8106
  Epoch 70... Train Loss: 0.2769, Val Loss: 0.7853
  Epoch 80... Train Loss: 0.2609, Val Loss: 0.7270
  Epoch 90... Train Loss: 0.2718, Val Loss: 0.7709
  Epoch 100... Train Loss: 0.2609, Val Loss: 0.7571
  Epoch 110... Train Loss: 0.2309, Val Loss: 0.7384
  Epoch 120... Train Loss: 0.2206, Val Loss: 0.7179
  Epoch 130... Train Loss: 0.2304, Val Loss: 0.7228
  Epoch 140... Train Loss: 0.2371, Val Loss: 0.7085
  Epoch 150... Train Loss: 0.2489, Val Loss: 0.7259
  Epoch 160... Train Loss: 0.2257, Val Loss: 0.7270
  Epoch 170... Train Loss: 0.2222, Val Loss: 0.6981

[INFO 04-02 10:02:21] ax.service.ax_client: Completed trial 28 with data: {'avg_rmse_nonzero': 5.287757}.

  Epoch 180... Train Loss: 0.2153, Val Loss: 0.7003
Fold 5 - MSE: 6.2316, RMSE: 2.4963, MAE: 2.0632

Mean CV MSE: 30.0082, Mean CV RMSE: 5.2878, Mean CV MAE: 3.5469
Completed trial 28 with mean RMSE: 5.2878 ± 0.7155
Saved Ax client checkpoint

[INFO 04-02 10:02:23] ax.service.ax_client: Generated new trial 29 with parameters {'dropout_rate': 0.345253, 'weight_decay': 0.01, 'lr': 0.01, 'batch_size': 256, 'early_stopping_patience': 10, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 32, 'activation': 'leaky_relu'} using model BoTorch.

Starting trial 29 with parameters: {'dropout_rate': 0.3452525346821827, 'weight_decay': 0.01, 'lr': 0.01, 'batch_size': 256, 'early_stopping_patience': 10, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 32, 'activation': 'leaky_relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 3.1173, Val Loss: 4209.3843
  Epoch 10... Train Loss: 0.8154, Val Loss: 0.5977
  Epoch 20... Train Loss: 0.5482, Val Loss: 0.7625
Fold 1 - MSE: 37.2044, RMSE: 6.0995, MAE: 3.9456
Starting fold 2...
  Epoch 0... Train Loss: 10.1983, Val Loss: 13246.9414
  Epoch 10... Train Loss: 0.6658, Val Loss: 0.9003
Fold 2 - MSE: 37.4662, RMSE: 6.1210, MAE: 3.5253
Starting fold 3...
  Epoch 0... Train Loss: 9.7783, Val Loss: 12241.7783
  Epoch 10... Train Loss: 0.6234, Val Loss: 1.0305
  Epoch 20... Train Loss: 0.3930, Val Loss: 0.8953
  Epoch 30... Train Loss: 0.4618, Val Loss: 0.7265
  Epoch 40... Train Loss: 0.2943, Val Loss: 0.5464
  Epoch 50... Train Loss: 0.2564, Val Loss: 0.5038
  Epoch 60... Train Loss: 0.2412, Val Loss: 0.4381
Fold 3 - MSE: 44.4729, RMSE: 6.6688, MAE: 3.8180
Starting fold 4...
  Epoch 0... Train Loss: 4.1535, Val Loss: 226.3161
  Epoch 10... Train Loss: 0.5387, Val Loss: 0.6055
  Epoch 20... Train Loss: 0.2984, Val Loss: 0.4236
  Epoch 30... Train Loss: 0.3204, Val Loss: 0.4302
  Epoch 40... Train Loss: 0.1956, Val Loss: 0.4151
Fold 4 - MSE: 30.8144, RMSE: 5.5511, MAE: 4.4360
Starting fold 5...
  Epoch 0... Train Loss: 9.1130, Val Loss: 4915.2817
  Epoch 10... Train Loss: 0.5936, Val Loss: 1.3207
  Epoch 20... Train Loss: 0.4237, Val Loss: 1.2497
  Epoch 30... Train Loss: 0.3402, Val Loss: 0.8321
  Epoch 40... Train Loss: 0.3130, Val Loss: 0.8533

[INFO 04-02 10:02:27] ax.service.ax_client: Completed trial 29 with data: {'avg_rmse_nonzero': 5.351123}.

  Epoch 50... Train Loss: 0.2419, Val Loss: 0.7620
Fold 5 - MSE: 5.3603, RMSE: 2.3152, MAE: 1.7719

Mean CV MSE: 31.0636, Mean CV RMSE: 5.3511, Mean CV MAE: 3.4993
Completed trial 29 with mean RMSE: 5.3511 ± 0.7793
Saved Ax client checkpoint

[INFO 04-02 10:02:29] ax.service.ax_client: Generated new trial 30 with parameters {'dropout_rate': 0.079386, 'weight_decay': 4.6e-05, 'lr': 0.008109, 'batch_size': 256, 'early_stopping_patience': 11, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 32, 'activation': 'leaky_relu'} using model BoTorch.

Starting trial 30 with parameters: {'dropout_rate': 0.079386049625649, 'weight_decay': 4.642048872302377e-05, 'lr': 0.008108657965269103, 'batch_size': 256, 'early_stopping_patience': 11, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 32, 'activation': 'leaky_relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 9.7059, Val Loss: 10075.2725
  Epoch 10... Train Loss: 1.2423, Val Loss: 1.3122
  Epoch 20... Train Loss: 0.5109, Val Loss: 0.5241
  Epoch 30... Train Loss: 0.3997, Val Loss: 0.4436
  Epoch 40... Train Loss: 0.3479, Val Loss: 0.3608
  Epoch 50... Train Loss: 0.4727, Val Loss: 0.3214
  Epoch 60... Train Loss: 0.3355, Val Loss: 0.3276
  Epoch 70... Train Loss: 0.2835, Val Loss: 0.3087
  Epoch 80... Train Loss: 0.3461, Val Loss: 0.2972
  Epoch 90... Train Loss: 0.2559, Val Loss: 0.2894
  Epoch 100... Train Loss: 0.3767, Val Loss: 0.2817
  Epoch 110... Train Loss: 0.2817, Val Loss: 0.2846
Fold 1 - MSE: 42.6471, RMSE: 6.5305, MAE: 4.2563
Starting fold 2...
  Epoch 0... Train Loss: 5.4142, Val Loss: 1553.5558
  Epoch 10... Train Loss: 0.6669, Val Loss: 0.7317
  Epoch 20... Train Loss: 0.4128, Val Loss: 0.6677
  Epoch 30... Train Loss: 0.3434, Val Loss: 0.5719
  Epoch 40... Train Loss: 0.2546, Val Loss: 0.4723
  Epoch 50... Train Loss: 0.2689, Val Loss: 0.4546
  Epoch 60... Train Loss: 0.2724, Val Loss: 0.4343
  Epoch 70... Train Loss: 0.2433, Val Loss: 0.4109
Fold 2 - MSE: 35.9316, RMSE: 5.9943, MAE: 3.4563
Starting fold 3...
  Epoch 0... Train Loss: 6.8114, Val Loss: 6577.7437
  Epoch 10... Train Loss: 0.6842, Val Loss: 0.8512
  Epoch 20... Train Loss: 0.4253, Val Loss: 0.6252
  Epoch 30... Train Loss: 0.3304, Val Loss: 0.5599
  Epoch 40... Train Loss: 0.2404, Val Loss: 0.4402
  Epoch 50... Train Loss: 0.2070, Val Loss: 0.4747
Fold 3 - MSE: 23.9824, RMSE: 4.8972, MAE: 2.9737
Starting fold 4...
  Epoch 0... Train Loss: 14.4659, Val Loss: 134.8656
  Epoch 10... Train Loss: 0.6827, Val Loss: 0.5446
  Epoch 20... Train Loss: 0.3679, Val Loss: 0.5365
  Epoch 30... Train Loss: 0.3787, Val Loss: 0.5383
  Epoch 40... Train Loss: 0.3105, Val Loss: 0.5162
  Epoch 50... Train Loss: 0.2852, Val Loss: 0.5144
  Epoch 60... Train Loss: 0.2497, Val Loss: 0.5131
  Epoch 70... Train Loss: 0.2648, Val Loss: 0.5163
Fold 4 - MSE: 41.4294, RMSE: 6.4366, MAE: 5.3199
Starting fold 5...
  Epoch 0... Train Loss: 13.2918, Val Loss: 572.3434
  Epoch 10... Train Loss: 0.7508, Val Loss: 1.6976
  Epoch 20... Train Loss: 0.5067, Val Loss: 1.1281
  Epoch 30... Train Loss: 0.3948, Val Loss: 0.9044
  Epoch 40... Train Loss: 0.2842, Val Loss: 0.8011
  Epoch 50... Train Loss: 0.2157, Val Loss: 0.7689
  Epoch 60... Train Loss: 0.2003, Val Loss: 0.7783

[INFO 04-02 10:02:36] ax.service.ax_client: Completed trial 30 with data: {'avg_rmse_nonzero': 5.289316}.

Fold 5 - MSE: 6.6980, RMSE: 2.5881, MAE: 2.1558

Mean CV MSE: 30.1377, Mean CV RMSE: 5.2893, Mean CV MAE: 3.6324
Completed trial 30 with mean RMSE: 5.2893 ± 0.7350
Saved Ax client checkpoint

[INFO 04-02 10:02:38] ax.service.ax_client: Generated new trial 31 with parameters {'dropout_rate': 0.310061, 'weight_decay': 0.000306, 'lr': 0.01, 'batch_size': 256, 'early_stopping_patience': 48, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 32, 'activation': 'leaky_relu'} using model BoTorch.

Starting trial 31 with parameters: {'dropout_rate': 0.31006098312897074, 'weight_decay': 0.0003060800001010333, 'lr': 0.01, 'batch_size': 256, 'early_stopping_patience': 48, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 32, 'activation': 'leaky_relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 4.4634, Val Loss: 2961.6326
  Epoch 10... Train Loss: 0.8152, Val Loss: 0.7724
  Epoch 20... Train Loss: 0.5314, Val Loss: 0.4936
  Epoch 30... Train Loss: 0.4687, Val Loss: 0.5249
  Epoch 40... Train Loss: 0.4266, Val Loss: 0.3397
  Epoch 50... Train Loss: 0.5649, Val Loss: 0.3245
  Epoch 60... Train Loss: 0.4486, Val Loss: 0.3450
  Epoch 70... Train Loss: 0.3329, Val Loss: 0.3587
  Epoch 80... Train Loss: 0.5120, Val Loss: 0.3355
  Epoch 90... Train Loss: 0.3585, Val Loss: 0.2979
  Epoch 100... Train Loss: 0.3609, Val Loss: 0.2788
  Epoch 110... Train Loss: 0.3659, Val Loss: 0.3134
  Epoch 120... Train Loss: 0.3977, Val Loss: 0.3879
  Epoch 130... Train Loss: 0.2831, Val Loss: 0.3073
  Epoch 140... Train Loss: 0.3021, Val Loss: 0.2955
  Epoch 150... Train Loss: 0.4465, Val Loss: 0.3037
Fold 1 - MSE: 40.8836, RMSE: 6.3940, MAE: 4.0825
Starting fold 2...
  Epoch 0... Train Loss: 9.8937, Val Loss: 9406.0127
  Epoch 10... Train Loss: 0.7664, Val Loss: 0.8736
  Epoch 20... Train Loss: 0.4461, Val Loss: 0.6462
  Epoch 30... Train Loss: 0.3746, Val Loss: 0.4840
  Epoch 40... Train Loss: 0.2974, Val Loss: 0.4826
  Epoch 50... Train Loss: 0.3482, Val Loss: 0.4313
  Epoch 60... Train Loss: 0.3478, Val Loss: 0.3770
  Epoch 70... Train Loss: 0.3275, Val Loss: 0.4402
  Epoch 80... Train Loss: 0.2762, Val Loss: 0.4001
  Epoch 90... Train Loss: 0.3025, Val Loss: 0.3822
  Epoch 100... Train Loss: 0.3186, Val Loss: 0.4116
  Epoch 110... Train Loss: 0.1899, Val Loss: 0.3933
  Epoch 120... Train Loss: 0.2062, Val Loss: 0.3425
  Epoch 130... Train Loss: 0.2229, Val Loss: 0.3285
  Epoch 140... Train Loss: 0.1897, Val Loss: 0.3456
  Epoch 150... Train Loss: 0.2983, Val Loss: 0.3145
  Epoch 160... Train Loss: 0.1882, Val Loss: 0.3291
  Epoch 170... Train Loss: 0.1913, Val Loss: 0.3260
  Epoch 180... Train Loss: 0.1682, Val Loss: 0.3181
Fold 2 - MSE: 40.0654, RMSE: 6.3297, MAE: 3.9458
Starting fold 3...
  Epoch 0... Train Loss: 10.0724, Val Loss: 2072.1990
  Epoch 10... Train Loss: 0.7575, Val Loss: 0.9185
  Epoch 20... Train Loss: 0.4999, Val Loss: 0.6052
  Epoch 30... Train Loss: 0.3647, Val Loss: 0.4778
  Epoch 40... Train Loss: 0.2689, Val Loss: 0.4329
  Epoch 50... Train Loss: 0.3132, Val Loss: 0.4535
  Epoch 60... Train Loss: 0.2485, Val Loss: 0.5079
  Epoch 70... Train Loss: 0.2416, Val Loss: 0.4051
  Epoch 80... Train Loss: 0.2605, Val Loss: 0.3905
  Epoch 90... Train Loss: 0.2494, Val Loss: 0.3724
  Epoch 100... Train Loss: 0.2790, Val Loss: 0.3711
  Epoch 110... Train Loss: 0.2143, Val Loss: 0.3806
  Epoch 120... Train Loss: 0.2169, Val Loss: 0.3659
  Epoch 130... Train Loss: 0.2090, Val Loss: 0.3697
  Epoch 140... Train Loss: 0.2071, Val Loss: 0.4853
  Epoch 150... Train Loss: 0.1859, Val Loss: 0.3700
  Epoch 160... Train Loss: 0.1914, Val Loss: 0.3504
  Epoch 170... Train Loss: 0.2082, Val Loss: 0.3380
Fold 3 - MSE: 95.4177, RMSE: 9.7682, MAE: 5.3403
Starting fold 4...
  Epoch 0... Train Loss: 8.9160, Val Loss: 10925.3193
  Epoch 10... Train Loss: 0.7397, Val Loss: 0.5349
  Epoch 20... Train Loss: 0.4277, Val Loss: 0.4612
  Epoch 30... Train Loss: 0.3818, Val Loss: 0.4422
  Epoch 40... Train Loss: 0.2592, Val Loss: 0.4368
  Epoch 50... Train Loss: 0.2138, Val Loss: 0.4572
  Epoch 60... Train Loss: 0.2573, Val Loss: 0.4732
  Epoch 70... Train Loss: 0.2138, Val Loss: 0.3962
  Epoch 80... Train Loss: 0.1939, Val Loss: 0.4148
  Epoch 90... Train Loss: 0.1794, Val Loss: 0.4049
  Epoch 100... Train Loss: 0.1888, Val Loss: 0.3799
  Epoch 110... Train Loss: 0.1568, Val Loss: 0.3984
  Epoch 120... Train Loss: 0.1718, Val Loss: 0.4112
  Epoch 130... Train Loss: 0.1661, Val Loss: 0.4313
Fold 4 - MSE: 28.0167, RMSE: 5.2931, MAE: 4.1910
Starting fold 5...
  Epoch 0... Train Loss: 8.4204, Val Loss: 9158.1436
  Epoch 10... Train Loss: 0.7342, Val Loss: 1.4163
  Epoch 20... Train Loss: 0.5348, Val Loss: 1.1099
  Epoch 30... Train Loss: 0.3653, Val Loss: 0.9197
  Epoch 40... Train Loss: 0.3508, Val Loss: 0.8592
  Epoch 50... Train Loss: 0.2938, Val Loss: 0.8282
  Epoch 60... Train Loss: 0.2965, Val Loss: 0.7792
  Epoch 70... Train Loss: 0.2760, Val Loss: 0.7402
  Epoch 80... Train Loss: 0.2598, Val Loss: 0.7237
  Epoch 90... Train Loss: 0.2810, Val Loss: 0.7502
  Epoch 100... Train Loss: 0.2409, Val Loss: 0.7389
  Epoch 110... Train Loss: 0.2185, Val Loss: 0.7184
  Epoch 120... Train Loss: 0.2137, Val Loss: 0.7305
  Epoch 130... Train Loss: 0.1950, Val Loss: 0.7071
  Epoch 140... Train Loss: 0.2074, Val Loss: 0.6966
  Epoch 150... Train Loss: 0.1961, Val Loss: 0.7116

[INFO 04-02 10:02:50] ax.service.ax_client: Completed trial 31 with data: {'avg_rmse_nonzero': 5.995233}.

  Epoch 160... Train Loss: 0.1735, Val Loss: 0.6958
Fold 5 - MSE: 4.8011, RMSE: 2.1911, MAE: 1.8516

Mean CV MSE: 41.8369, Mean CV RMSE: 5.9952, Mean CV MAE: 3.8822
Completed trial 31 with mean RMSE: 5.9952 ± 1.2139
Saved Ax client checkpoint

[INFO 04-02 10:02:52] ax.service.ax_client: Generated new trial 32 with parameters {'dropout_rate': 0.049766, 'weight_decay': 0.000177, 'lr': 0.01, 'batch_size': 256, 'early_stopping_patience': 27, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 64, 'activation': 'leaky_relu'} using model BoTorch.

Starting trial 32 with parameters: {'dropout_rate': 0.049765894962517265, 'weight_decay': 0.0001772454142652244, 'lr': 0.01, 'batch_size': 256, 'early_stopping_patience': 27, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 64, 'activation': 'leaky_relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 3.3507, Val Loss: 5496.0493
  Epoch 10... Train Loss: 0.7447, Val Loss: 2.3160
  Epoch 20... Train Loss: 0.5506, Val Loss: 0.5917
  Epoch 30... Train Loss: 0.4549, Val Loss: 0.5770
  Epoch 40... Train Loss: 0.3905, Val Loss: 0.5693
  Epoch 50... Train Loss: 0.4013, Val Loss: 0.6606
  Epoch 60... Train Loss: 0.3579, Val Loss: 0.3943
  Epoch 70... Train Loss: 0.2692, Val Loss: 0.3764
  Epoch 80... Train Loss: 0.3453, Val Loss: 0.3947
  Epoch 90... Train Loss: 0.2547, Val Loss: 0.3647
  Epoch 100... Train Loss: 0.2868, Val Loss: 0.3905
  Epoch 110... Train Loss: 0.2808, Val Loss: 0.3850
Fold 1 - MSE: 44.8672, RMSE: 6.6983, MAE: 4.3841
Starting fold 2...
  Epoch 0... Train Loss: 9.8539, Val Loss: 10188.4170
  Epoch 10... Train Loss: 0.6004, Val Loss: 0.9201
  Epoch 20... Train Loss: 0.3217, Val Loss: 0.5871
  Epoch 30... Train Loss: 0.3032, Val Loss: 0.4598
  Epoch 40... Train Loss: 0.2603, Val Loss: 0.4514
  Epoch 50... Train Loss: 0.2549, Val Loss: 0.4350
  Epoch 60... Train Loss: 0.3118, Val Loss: 0.3825
  Epoch 70... Train Loss: 0.2747, Val Loss: 0.4145
  Epoch 80... Train Loss: 0.2204, Val Loss: 0.3523
  Epoch 90... Train Loss: 0.2064, Val Loss: 0.3280
  Epoch 100... Train Loss: 0.1818, Val Loss: 0.3716
  Epoch 110... Train Loss: 0.1471, Val Loss: 0.3463
Fold 2 - MSE: 32.4971, RMSE: 5.7006, MAE: 3.3508
Starting fold 3...
  Epoch 0... Train Loss: 8.6079, Val Loss: 14778.4248
  Epoch 10... Train Loss: 0.6481, Val Loss: 0.9679
  Epoch 20... Train Loss: 0.3999, Val Loss: 0.6555
  Epoch 30... Train Loss: 0.3331, Val Loss: 0.4850
  Epoch 40... Train Loss: 0.2334, Val Loss: 0.4261
  Epoch 50... Train Loss: 0.2066, Val Loss: 0.4778
  Epoch 60... Train Loss: 0.1888, Val Loss: 0.4345
  Epoch 70... Train Loss: 0.1965, Val Loss: 0.4503
  Epoch 80... Train Loss: 0.1871, Val Loss: 0.3778
Fold 3 - MSE: 11.6329, RMSE: 3.4107, MAE: 2.4188
Starting fold 4...
  Epoch 0... Train Loss: 8.4095, Val Loss: 1598.6003
  Epoch 10... Train Loss: 0.6817, Val Loss: 0.8061
  Epoch 20... Train Loss: 0.3731, Val Loss: 0.5286
  Epoch 30... Train Loss: 0.2520, Val Loss: 0.4575
  Epoch 40... Train Loss: 0.2319, Val Loss: 0.4037
  Epoch 50... Train Loss: 0.1549, Val Loss: 0.4049
  Epoch 60... Train Loss: 0.1591, Val Loss: 0.4008
  Epoch 70... Train Loss: 0.1503, Val Loss: 0.4291
Fold 4 - MSE: 32.8686, RMSE: 5.7331, MAE: 4.6312
Starting fold 5...
  Epoch 0... Train Loss: 5.9000, Val Loss: 1763.6938
  Epoch 10... Train Loss: 0.6939, Val Loss: 1.4016
  Epoch 20... Train Loss: 0.5143, Val Loss: 1.0895
  Epoch 30... Train Loss: 0.3545, Val Loss: 0.8797
  Epoch 40... Train Loss: 0.2749, Val Loss: 0.8270
  Epoch 50... Train Loss: 0.2410, Val Loss: 0.8685
  Epoch 60... Train Loss: 0.2142, Val Loss: 0.8051
  Epoch 70... Train Loss: 0.2020, Val Loss: 0.7897
  Epoch 80... Train Loss: 0.2004, Val Loss: 0.7540
  Epoch 90... Train Loss: 0.1950, Val Loss: 0.7747
  Epoch 100... Train Loss: 0.1835, Val Loss: 0.7613
  Epoch 110... Train Loss: 0.1588, Val Loss: 0.7351

[INFO 04-02 10:03:02] ax.service.ax_client: Completed trial 32 with data: {'avg_rmse_nonzero': 5.043144}.

  Epoch 120... Train Loss: 0.1499, Val Loss: 0.7420
Fold 5 - MSE: 13.4908, RMSE: 3.6730, MAE: 3.0620

Mean CV MSE: 27.0713, Mean CV RMSE: 5.0431, Mean CV MAE: 3.5694
Completed trial 32 with mean RMSE: 5.0431 ± 0.6399
Saved Ax client checkpoint

[INFO 04-02 10:03:03] ax.service.ax_client: Generated new trial 33 with parameters {'dropout_rate': 0.0, 'weight_decay': 0.005119, 'lr': 0.01, 'batch_size': 256, 'early_stopping_patience': 10, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 64, 'activation': 'leaky_relu'} using model BoTorch.

Starting trial 33 with parameters: {'dropout_rate': 0.0, 'weight_decay': 0.005118866903143426, 'lr': 0.01, 'batch_size': 256, 'early_stopping_patience': 10, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 64, 'activation': 'leaky_relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 4.3791, Val Loss: 11283.5527
  Epoch 10... Train Loss: 0.7354, Val Loss: 1.0392
  Epoch 20... Train Loss: 0.5039, Val Loss: 0.6563
Fold 1 - MSE: 37.0499, RMSE: 6.0869, MAE: 4.1317
Starting fold 2...
  Epoch 0... Train Loss: 6.3906, Val Loss: 1723.5702
  Epoch 10... Train Loss: 0.5514, Val Loss: 0.6930
  Epoch 20... Train Loss: 0.3172, Val Loss: 0.6513
  Epoch 30... Train Loss: 0.3283, Val Loss: 0.4956
Fold 2 - MSE: 37.9311, RMSE: 6.1588, MAE: 3.5967
Starting fold 3...
  Epoch 0... Train Loss: 6.9608, Val Loss: 3786.9641
  Epoch 10... Train Loss: 0.5165, Val Loss: 0.6923
  Epoch 20... Train Loss: 0.2678, Val Loss: 0.5905
  Epoch 30... Train Loss: 0.3052, Val Loss: 0.5248
  Epoch 40... Train Loss: 0.2181, Val Loss: 0.4273
  Epoch 50... Train Loss: 0.2096, Val Loss: 0.3690
  Epoch 60... Train Loss: 0.1768, Val Loss: 0.3719
  Epoch 70... Train Loss: 0.1512, Val Loss: 0.3286
  Epoch 80... Train Loss: 0.1489, Val Loss: 0.3193
Fold 3 - MSE: 41.7260, RMSE: 6.4596, MAE: 3.2697
Starting fold 4...
  Epoch 0... Train Loss: 10.2569, Val Loss: 2832.4209
  Epoch 10... Train Loss: 0.5084, Val Loss: 0.5730
  Epoch 20... Train Loss: 0.2400, Val Loss: 0.4754
  Epoch 30... Train Loss: 0.2743, Val Loss: 0.5404
  Epoch 40... Train Loss: 0.1893, Val Loss: 0.4067
Fold 4 - MSE: 32.3015, RMSE: 5.6834, MAE: 4.3097
Starting fold 5...
  Epoch 0... Train Loss: 10.3599, Val Loss: 6450.5449
  Epoch 10... Train Loss: 0.6788, Val Loss: 1.4502
  Epoch 20... Train Loss: 0.4277, Val Loss: 1.2236
  Epoch 30... Train Loss: 0.3238, Val Loss: 1.0327
  Epoch 40... Train Loss: 0.2378, Val Loss: 0.8518

[INFO 04-02 10:03:08] ax.service.ax_client: Completed trial 33 with data: {'avg_rmse_nonzero': 5.653198}.

  Epoch 50... Train Loss: 0.1769, Val Loss: 0.7867
Fold 5 - MSE: 15.0334, RMSE: 3.8773, MAE: 3.5554

Mean CV MSE: 32.8084, Mean CV RMSE: 5.6532, Mean CV MAE: 3.7726
Completed trial 33 with mean RMSE: 5.6532 ± 0.4609
Saved Ax client checkpoint

[INFO 04-02 10:03:10] ax.service.ax_client: Generated new trial 34 with parameters {'dropout_rate': 0.014892, 'weight_decay': 1e-06, 'lr': 0.01, 'batch_size': 256, 'early_stopping_patience': 45, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 32, 'activation': 'leaky_relu'} using model BoTorch.

Starting trial 34 with parameters: {'dropout_rate': 0.014892207655605033, 'weight_decay': 1e-06, 'lr': 0.01, 'batch_size': 256, 'early_stopping_patience': 45, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 32, 'activation': 'leaky_relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 6.6996, Val Loss: 34198.5938
  Epoch 10... Train Loss: 0.7163, Val Loss: 2.0427
  Epoch 20... Train Loss: 0.4568, Val Loss: 0.4671
  Epoch 30... Train Loss: 0.3966, Val Loss: 0.4491
  Epoch 40... Train Loss: 0.3880, Val Loss: 0.4269
  Epoch 50... Train Loss: 0.4406, Val Loss: 0.4511
  Epoch 60... Train Loss: 0.4039, Val Loss: 0.3640
  Epoch 70... Train Loss: 0.2981, Val Loss: 0.3322
  Epoch 80... Train Loss: 0.3793, Val Loss: 0.3715
  Epoch 90... Train Loss: 0.2610, Val Loss: 0.3129
  Epoch 100... Train Loss: 0.3182, Val Loss: 0.3000
  Epoch 110... Train Loss: 0.2772, Val Loss: 0.2818
  Epoch 120... Train Loss: 0.3843, Val Loss: 0.3811
  Epoch 130... Train Loss: 0.2667, Val Loss: 0.3229
  Epoch 140... Train Loss: 0.2956, Val Loss: 0.2945
Fold 1 - MSE: 41.4563, RMSE: 6.4387, MAE: 4.3657
Starting fold 2...
  Epoch 0... Train Loss: 9.4569, Val Loss: 6885.9839
  Epoch 10... Train Loss: 0.7075, Val Loss: 0.7959
  Epoch 20... Train Loss: 0.4239, Val Loss: 0.6866
  Epoch 30... Train Loss: 0.3473, Val Loss: 0.5658
  Epoch 40... Train Loss: 0.2407, Val Loss: 0.5036
  Epoch 50... Train Loss: 0.2194, Val Loss: 0.4077
  Epoch 60... Train Loss: 0.2807, Val Loss: 0.4368
  Epoch 70... Train Loss: 0.2262, Val Loss: 0.3969
  Epoch 80... Train Loss: 0.2099, Val Loss: 0.3449
  Epoch 90... Train Loss: 0.2153, Val Loss: 0.3484
  Epoch 100... Train Loss: 0.1730, Val Loss: 0.3603
  Epoch 110... Train Loss: 0.1471, Val Loss: 0.3510
  Epoch 120... Train Loss: 0.1588, Val Loss: 0.3356
Fold 2 - MSE: 35.7173, RMSE: 5.9764, MAE: 3.8630
Starting fold 3...
  Epoch 0... Train Loss: 9.8237, Val Loss: 140.3072
  Epoch 10... Train Loss: 0.6376, Val Loss: 0.7975
  Epoch 20... Train Loss: 0.4100, Val Loss: 0.6575
  Epoch 30... Train Loss: 0.3195, Val Loss: 0.5336
  Epoch 40... Train Loss: 0.2172, Val Loss: 0.4523
  Epoch 50... Train Loss: 0.2065, Val Loss: 0.5126
  Epoch 60... Train Loss: 0.1806, Val Loss: 0.4685
  Epoch 70... Train Loss: 0.1718, Val Loss: 0.4267
  Epoch 80... Train Loss: 0.1867, Val Loss: 0.3758
  Epoch 90... Train Loss: 0.1605, Val Loss: 0.3943
  Epoch 100... Train Loss: 0.1778, Val Loss: 0.4356
  Epoch 110... Train Loss: 0.1622, Val Loss: 0.3936
  Epoch 120... Train Loss: 0.1613, Val Loss: 0.3998
  Epoch 130... Train Loss: 0.1461, Val Loss: 0.3745
  Epoch 140... Train Loss: 0.1531, Val Loss: 0.3903
  Epoch 150... Train Loss: 0.1534, Val Loss: 0.3770
  Epoch 160... Train Loss: 0.1367, Val Loss: 0.3804
Fold 3 - MSE: 13.3787, RMSE: 3.6577, MAE: 2.6826
Starting fold 4...
  Epoch 0... Train Loss: 16.7569, Val Loss: 921.3649
  Epoch 10... Train Loss: 0.8314, Val Loss: 0.7228
  Epoch 20... Train Loss: 0.4455, Val Loss: 0.5463
  Epoch 30... Train Loss: 0.2923, Val Loss: 0.5025
  Epoch 40... Train Loss: 0.1909, Val Loss: 0.4685
  Epoch 50... Train Loss: 0.1729, Val Loss: 0.5383
  Epoch 60... Train Loss: 0.1470, Val Loss: 0.4493
  Epoch 70... Train Loss: 0.1365, Val Loss: 0.4558
  Epoch 80... Train Loss: 0.1429, Val Loss: 0.4559
Fold 4 - MSE: 42.9505, RMSE: 6.5537, MAE: 5.1108
Starting fold 5...
  Epoch 0... Train Loss: 10.5051, Val Loss: 8230.5771
  Epoch 10... Train Loss: 0.6939, Val Loss: 1.6512
  Epoch 20... Train Loss: 0.4692, Val Loss: 1.0396
  Epoch 30... Train Loss: 0.2788, Val Loss: 0.8255
  Epoch 40... Train Loss: 0.2407, Val Loss: 0.7288
  Epoch 50... Train Loss: 0.2313, Val Loss: 0.6674
  Epoch 60... Train Loss: 0.2005, Val Loss: 0.7005
  Epoch 70... Train Loss: 0.1999, Val Loss: 0.7269
  Epoch 80... Train Loss: 0.1820, Val Loss: 0.7109

[INFO 04-02 10:03:22] ax.service.ax_client: Completed trial 34 with data: {'avg_rmse_nonzero': 5.271672}.

  Epoch 90... Train Loss: 0.1711, Val Loss: 0.7014
Fold 5 - MSE: 13.9274, RMSE: 3.7319, MAE: 3.2482

Mean CV MSE: 29.4861, Mean CV RMSE: 5.2717, Mean CV MAE: 3.8540
Completed trial 34 with mean RMSE: 5.2717 ± 0.6511
Saved Ax client checkpoint

[INFO 04-02 10:03:24] ax.service.ax_client: Generated new trial 35 with parameters {'dropout_rate': 0.112129, 'weight_decay': 1e-06, 'lr': 0.01, 'batch_size': 256, 'early_stopping_patience': 13, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 32, 'activation': 'leaky_relu'} using model BoTorch.

Starting trial 35 with parameters: {'dropout_rate': 0.11212894375864056, 'weight_decay': 1e-06, 'lr': 0.01, 'batch_size': 256, 'early_stopping_patience': 13, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 32, 'activation': 'leaky_relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 13.9199, Val Loss: 1431.3522
  Epoch 10... Train Loss: 1.1246, Val Loss: 1.8812
  Epoch 20... Train Loss: 0.4868, Val Loss: 0.5145
  Epoch 30... Train Loss: 0.4178, Val Loss: 0.4249
  Epoch 40... Train Loss: 0.3638, Val Loss: 0.3964
  Epoch 50... Train Loss: 0.3593, Val Loss: 0.3071
  Epoch 60... Train Loss: 0.3623, Val Loss: 0.3465
Fold 1 - MSE: 42.0762, RMSE: 6.4866, MAE: 4.1019
Starting fold 2...
  Epoch 0... Train Loss: 7.8370, Val Loss: 15261.9717
  Epoch 10... Train Loss: 0.6958, Val Loss: 0.9648
  Epoch 20... Train Loss: 0.4422, Val Loss: 0.6794
  Epoch 30... Train Loss: 0.3838, Val Loss: 0.5467
  Epoch 40... Train Loss: 0.2540, Val Loss: 0.4861
  Epoch 50... Train Loss: 0.2737, Val Loss: 0.3969
  Epoch 60... Train Loss: 0.2370, Val Loss: 0.4230
  Epoch 70... Train Loss: 0.2157, Val Loss: 0.3683
  Epoch 80... Train Loss: 0.2112, Val Loss: 0.3700
Fold 2 - MSE: 38.2246, RMSE: 6.1826, MAE: 3.5867
Starting fold 3...
  Epoch 0... Train Loss: 12.6189, Val Loss: 984.6385
  Epoch 10... Train Loss: 0.5795, Val Loss: 1.0447
  Epoch 20... Train Loss: 0.3549, Val Loss: 0.5685
  Epoch 30... Train Loss: 0.2887, Val Loss: 0.4584
  Epoch 40... Train Loss: 0.2252, Val Loss: 0.4357
  Epoch 50... Train Loss: 0.2087, Val Loss: 0.4461
Fold 3 - MSE: 12.7240, RMSE: 3.5671, MAE: 2.6429
Starting fold 4...
  Epoch 0... Train Loss: 11.7611, Val Loss: 2280.4531
  Epoch 10... Train Loss: 0.6426, Val Loss: 0.8188
  Epoch 20... Train Loss: 0.3660, Val Loss: 0.5654
  Epoch 30... Train Loss: 0.3045, Val Loss: 0.5079
  Epoch 40... Train Loss: 0.2324, Val Loss: 0.5010
Fold 4 - MSE: 35.7038, RMSE: 5.9753, MAE: 4.4525
Starting fold 5...
  Epoch 0... Train Loss: 9.1583, Val Loss: 23707.6816
  Epoch 10... Train Loss: 0.8446, Val Loss: 1.6337
  Epoch 20... Train Loss: 0.5935, Val Loss: 1.2870
  Epoch 30... Train Loss: 0.4999, Val Loss: 1.1626
  Epoch 40... Train Loss: 0.3543, Val Loss: 0.9299
  Epoch 50... Train Loss: 0.2664, Val Loss: 0.8318
  Epoch 60... Train Loss: 0.2347, Val Loss: 0.7837
  Epoch 70... Train Loss: 0.2287, Val Loss: 0.7369
  Epoch 80... Train Loss: 0.2286, Val Loss: 0.7247
  Epoch 90... Train Loss: 0.2015, Val Loss: 0.7196

[INFO 04-02 10:03:33] ax.service.ax_client: Completed trial 35 with data: {'avg_rmse_nonzero': 4.996182}.

  Epoch 100... Train Loss: 0.1894, Val Loss: 0.7257
Fold 5 - MSE: 7.6693, RMSE: 2.7693, MAE: 2.0267

Mean CV MSE: 27.2796, Mean CV RMSE: 4.9962, Mean CV MAE: 3.3621
Completed trial 35 with mean RMSE: 4.9962 ± 0.7612
Saved Ax client checkpoint

[INFO 04-02 10:03:36] ax.service.ax_client: Generated new trial 36 with parameters {'dropout_rate': 0.209702, 'weight_decay': 1e-06, 'lr': 0.01, 'batch_size': 256, 'early_stopping_patience': 15, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 32, 'activation': 'leaky_relu'} using model BoTorch.

Starting trial 36 with parameters: {'dropout_rate': 0.20970214092169823, 'weight_decay': 1e-06, 'lr': 0.01, 'batch_size': 256, 'early_stopping_patience': 15, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 32, 'activation': 'leaky_relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 4.5106, Val Loss: 6883.8438
  Epoch 10... Train Loss: 0.8853, Val Loss: 1.4141
  Epoch 20... Train Loss: 0.5712, Val Loss: 0.5352
  Epoch 30... Train Loss: 0.4988, Val Loss: 0.5162
  Epoch 40... Train Loss: 0.4229, Val Loss: 0.4486
  Epoch 50... Train Loss: 0.5627, Val Loss: 0.4118
  Epoch 60... Train Loss: 0.3859, Val Loss: 0.3778
  Epoch 70... Train Loss: 0.3688, Val Loss: 0.4096
Fold 1 - MSE: 46.7491, RMSE: 6.8373, MAE: 4.4872
Starting fold 2...
  Epoch 0... Train Loss: 16.2064, Val Loss: 1252.3950
  Epoch 10... Train Loss: 0.7559, Val Loss: 1.0023
  Epoch 20... Train Loss: 0.4648, Val Loss: 0.7490
  Epoch 30... Train Loss: 0.3768, Val Loss: 0.5259
  Epoch 40... Train Loss: 0.2921, Val Loss: 0.5085
  Epoch 50... Train Loss: 0.3145, Val Loss: 0.4314
  Epoch 60... Train Loss: 0.3027, Val Loss: 0.4347
  Epoch 70... Train Loss: 0.2648, Val Loss: 0.3948
  Epoch 80... Train Loss: 0.2602, Val Loss: 0.4110
Fold 2 - MSE: 37.5430, RMSE: 6.1272, MAE: 3.6784
Starting fold 3...
  Epoch 0... Train Loss: 14.1400, Val Loss: 96.4103
  Epoch 10... Train Loss: 0.6644, Val Loss: 0.6928
  Epoch 20... Train Loss: 0.3931, Val Loss: 0.6174
  Epoch 30... Train Loss: 0.3120, Val Loss: 0.4632
  Epoch 40... Train Loss: 0.2504, Val Loss: 0.4428
  Epoch 50... Train Loss: 0.2335, Val Loss: 0.4511
Fold 3 - MSE: 13.7658, RMSE: 3.7102, MAE: 2.6345
Starting fold 4...
  Epoch 0... Train Loss: 22.2704, Val Loss: 1513.3691
  Epoch 10... Train Loss: 0.8949, Val Loss: 0.5376
  Epoch 20... Train Loss: 0.5697, Val Loss: 0.5363
Fold 4 - MSE: 39.0355, RMSE: 6.2478, MAE: 5.0682
Starting fold 5...
  Epoch 0... Train Loss: 10.2528, Val Loss: 27352.6680
  Epoch 10... Train Loss: 0.8287, Val Loss: 1.9135
  Epoch 20... Train Loss: 0.5627, Val Loss: 1.1447
  Epoch 30... Train Loss: 0.5030, Val Loss: 1.0229
  Epoch 40... Train Loss: 0.3558, Val Loss: 0.8556
  Epoch 50... Train Loss: 0.2847, Val Loss: 0.8395
  Epoch 60... Train Loss: 0.2375, Val Loss: 0.8013
  Epoch 70... Train Loss: 0.2511, Val Loss: 0.7521
  Epoch 80... Train Loss: 0.2163, Val Loss: 0.7594
  Epoch 90... Train Loss: 0.2141, Val Loss: 0.7533

[INFO 04-02 10:03:44] ax.service.ax_client: Completed trial 36 with data: {'avg_rmse_nonzero': 5.377232}.

  Epoch 100... Train Loss: 0.2061, Val Loss: 0.7436
Fold 5 - MSE: 15.7095, RMSE: 3.9635, MAE: 3.3647

Mean CV MSE: 30.5606, Mean CV RMSE: 5.3772, Mean CV MAE: 3.8466
Completed trial 36 with mean RMSE: 5.3772 ± 0.6415
Saved Ax client checkpoint

[INFO 04-02 10:03:46] ax.service.ax_client: Generated new trial 37 with parameters {'dropout_rate': 0.270955, 'weight_decay': 1e-06, 'lr': 0.01, 'batch_size': 256, 'early_stopping_patience': 10, 'n_layers': 3, 'hidden1': 1024, 'hidden2': 1024, 'hidden3': 32, 'activation': 'leaky_relu'} using model BoTorch.

Starting trial 37 with parameters: {'dropout_rate': 0.270954678260437, 'weight_decay': 1e-06, 'lr': 0.01, 'batch_size': 256, 'early_stopping_patience': 10, 'n_layers': 3, 'hidden1': 1024, 'hidden2': 1024, 'hidden3': 32, 'activation': 'leaky_relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 4.4527, Val Loss: 17645.4160
  Epoch 10... Train Loss: 0.9271, Val Loss: 1.0009
  Epoch 20... Train Loss: 0.5282, Val Loss: 0.6089
  Epoch 30... Train Loss: 0.4092, Val Loss: 0.5386
  Epoch 40... Train Loss: 0.5083, Val Loss: 0.4832
  Epoch 50... Train Loss: 0.5603, Val Loss: 0.4513
  Epoch 60... Train Loss: 0.4154, Val Loss: 0.4352
  Epoch 70... Train Loss: 0.4230, Val Loss: 0.4356
Fold 1 - MSE: 37.7584, RMSE: 6.1448, MAE: 4.1756
Starting fold 2...
  Epoch 0... Train Loss: 8.8133, Val Loss: 12701.7979
  Epoch 10... Train Loss: 0.7020, Val Loss: 1.0707
  Epoch 20... Train Loss: 0.4390, Val Loss: 0.6113
  Epoch 30... Train Loss: 0.3845, Val Loss: 0.5512
  Epoch 40... Train Loss: 0.2854, Val Loss: 0.4412
Fold 2 - MSE: 39.6509, RMSE: 6.2969, MAE: 3.9740
Starting fold 3...
  Epoch 0... Train Loss: 12.8590, Val Loss: 1973.3524
  Epoch 10... Train Loss: 0.6774, Val Loss: 0.8305
  Epoch 20... Train Loss: 0.4292, Val Loss: 0.6060
  Epoch 30... Train Loss: 0.3335, Val Loss: 0.4693
  Epoch 40... Train Loss: 0.2670, Val Loss: 0.4543
  Epoch 50... Train Loss: 0.2429, Val Loss: 0.4352
Fold 3 - MSE: 27.5757, RMSE: 5.2513, MAE: 3.3713
Starting fold 4...
  Epoch 0... Train Loss: 11.2434, Val Loss: 3310.5249
  Epoch 10... Train Loss: 0.6849, Val Loss: 0.7366
  Epoch 20... Train Loss: 0.3830, Val Loss: 0.5424
  Epoch 30... Train Loss: 0.3120, Val Loss: 0.4663
  Epoch 40... Train Loss: 0.2513, Val Loss: 0.4506
Fold 4 - MSE: 31.9036, RMSE: 5.6483, MAE: 4.4355
Starting fold 5...
  Epoch 0... Train Loss: 9.3303, Val Loss: 2031.8142
  Epoch 10... Train Loss: 0.6556, Val Loss: 1.6375
  Epoch 20... Train Loss: 0.5318, Val Loss: 1.1526
  Epoch 30... Train Loss: 0.4114, Val Loss: 0.8722
  Epoch 40... Train Loss: 0.3345, Val Loss: 0.8619
  Epoch 50... Train Loss: 0.2990, Val Loss: 0.7790
  Epoch 60... Train Loss: 0.2610, Val Loss: 0.7706
  Epoch 70... Train Loss: 0.2633, Val Loss: 0.7585
  Epoch 80... Train Loss: 0.2652, Val Loss: 0.7480

[INFO 04-02 10:03:52] ax.service.ax_client: Completed trial 37 with data: {'avg_rmse_nonzero': 5.088796}.

Fold 5 - MSE: 4.4214, RMSE: 2.1027, MAE: 1.7451

Mean CV MSE: 28.2620, Mean CV RMSE: 5.0888, Mean CV MAE: 3.5403
Completed trial 37 with mean RMSE: 5.0888 ± 0.7691
Saved Ax client checkpoint

[INFO 04-02 10:03:54] ax.service.ax_client: Generated new trial 38 with parameters {'dropout_rate': 0.098409, 'weight_decay': 1e-06, 'lr': 0.01, 'batch_size': 256, 'early_stopping_patience': 40, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 32, 'activation': 'leaky_relu'} using model BoTorch.

Starting trial 38 with parameters: {'dropout_rate': 0.0984088052380869, 'weight_decay': 1e-06, 'lr': 0.01, 'batch_size': 256, 'early_stopping_patience': 40, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 32, 'activation': 'leaky_relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 8.1373, Val Loss: 21928.2402
  Epoch 10... Train Loss: 1.0309, Val Loss: 2.5665
  Epoch 20... Train Loss: 0.5171, Val Loss: 0.5175
  Epoch 30... Train Loss: 0.4612, Val Loss: 0.4920
  Epoch 40... Train Loss: 0.3674, Val Loss: 0.4234
  Epoch 50... Train Loss: 0.4493, Val Loss: 0.4218
  Epoch 60... Train Loss: 0.3364, Val Loss: 0.3280
  Epoch 70... Train Loss: 0.2826, Val Loss: 0.3588
  Epoch 80... Train Loss: 0.3535, Val Loss: 0.3261
  Epoch 90... Train Loss: 0.2675, Val Loss: 0.3536
  Epoch 100... Train Loss: 0.3104, Val Loss: 0.3134
  Epoch 110... Train Loss: 0.2652, Val Loss: 0.3018
  Epoch 120... Train Loss: 0.4041, Val Loss: 0.3136
  Epoch 130... Train Loss: 0.3025, Val Loss: 0.3514
  Epoch 140... Train Loss: 0.3145, Val Loss: 0.3212
  Epoch 150... Train Loss: 0.4350, Val Loss: 0.3180
Fold 1 - MSE: 44.7005, RMSE: 6.6858, MAE: 4.3574
Starting fold 2...
  Epoch 0... Train Loss: 10.7213, Val Loss: 12137.8301
  Epoch 10... Train Loss: 0.6727, Val Loss: 1.0344
  Epoch 20... Train Loss: 0.3841, Val Loss: 0.6288
  Epoch 30... Train Loss: 0.3814, Val Loss: 0.4515
  Epoch 40... Train Loss: 0.2579, Val Loss: 0.4539
  Epoch 50... Train Loss: 0.2684, Val Loss: 0.4136
  Epoch 60... Train Loss: 0.2872, Val Loss: 0.4240
  Epoch 70... Train Loss: 0.2209, Val Loss: 0.3772
  Epoch 80... Train Loss: 0.2298, Val Loss: 0.4020
  Epoch 90... Train Loss: 0.2077, Val Loss: 0.3587
  Epoch 100... Train Loss: 0.2118, Val Loss: 0.3779
  Epoch 110... Train Loss: 0.1504, Val Loss: 0.3646
  Epoch 120... Train Loss: 0.1917, Val Loss: 0.3609
Fold 2 - MSE: 37.8217, RMSE: 6.1499, MAE: 3.6890
Starting fold 3...
  Epoch 0... Train Loss: 7.6247, Val Loss: 7254.6235
  Epoch 10... Train Loss: 0.6356, Val Loss: 0.9276
  Epoch 20... Train Loss: 0.3990, Val Loss: 0.5730
  Epoch 30... Train Loss: 0.3085, Val Loss: 0.4674
  Epoch 40... Train Loss: 0.2437, Val Loss: 0.4852
  Epoch 50... Train Loss: 0.2065, Val Loss: 0.4912
  Epoch 60... Train Loss: 0.1957, Val Loss: 0.4886
  Epoch 70... Train Loss: 0.1947, Val Loss: 0.4744
Fold 3 - MSE: 16.1445, RMSE: 4.0180, MAE: 2.7314
Starting fold 4...
  Epoch 0... Train Loss: 11.5291, Val Loss: 1093.9337
  Epoch 10... Train Loss: 0.6756, Val Loss: 0.6149
  Epoch 20... Train Loss: 0.3700, Val Loss: 0.5943
  Epoch 30... Train Loss: 0.2913, Val Loss: 0.5109
  Epoch 40... Train Loss: 0.2403, Val Loss: 0.5329
  Epoch 50... Train Loss: 0.1953, Val Loss: 0.4563
  Epoch 60... Train Loss: 0.1811, Val Loss: 0.4549
  Epoch 70... Train Loss: 0.1839, Val Loss: 0.4366
  Epoch 80... Train Loss: 0.1540, Val Loss: 0.4371
  Epoch 90... Train Loss: 0.1462, Val Loss: 0.4548
  Epoch 100... Train Loss: 0.1509, Val Loss: 0.4261
  Epoch 110... Train Loss: 0.1301, Val Loss: 0.4361
  Epoch 120... Train Loss: 0.1446, Val Loss: 0.4367
Fold 4 - MSE: 33.1802, RMSE: 5.7602, MAE: 4.4549
Starting fold 5...
  Epoch 0... Train Loss: 9.9752, Val Loss: 23532.9395
  Epoch 10... Train Loss: 0.7431, Val Loss: 1.6025
  Epoch 20... Train Loss: 0.5505, Val Loss: 1.1419
  Epoch 30... Train Loss: 0.4332, Val Loss: 0.9389
  Epoch 40... Train Loss: 0.3337, Val Loss: 0.7672
  Epoch 50... Train Loss: 0.2493, Val Loss: 0.7709
  Epoch 60... Train Loss: 0.2321, Val Loss: 0.7606
  Epoch 70... Train Loss: 0.2514, Val Loss: 0.7381
  Epoch 80... Train Loss: 0.2152, Val Loss: 0.7105
  Epoch 90... Train Loss: 0.2170, Val Loss: 0.7846
  Epoch 100... Train Loss: 0.2039, Val Loss: 0.7331
  Epoch 110... Train Loss: 0.1862, Val Loss: 0.7299

[INFO 04-02 10:04:05] ax.service.ax_client: Completed trial 38 with data: {'avg_rmse_nonzero': 5.592116}.

Fold 5 - MSE: 28.5857, RMSE: 5.3466, MAE: 4.9056

Mean CV MSE: 32.0865, Mean CV RMSE: 5.5921, Mean CV MAE: 4.0277
Completed trial 38 with mean RMSE: 5.5921 ± 0.4513
Saved Ax client checkpoint

[INFO 04-02 10:04:07] ax.service.ax_client: Generated new trial 39 with parameters {'dropout_rate': 0.053445, 'weight_decay': 1e-06, 'lr': 1e-05, 'batch_size': 256, 'early_stopping_patience': 10, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 32, 'activation': 'leaky_relu'} using model BoTorch.

Starting trial 39 with parameters: {'dropout_rate': 0.05344482468270842, 'weight_decay': 1e-06, 'lr': 1e-05, 'batch_size': 256, 'early_stopping_patience': 10, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 32, 'activation': 'leaky_relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 1.3789, Val Loss: 0.9142
  Epoch 10... Train Loss: 0.5215, Val Loss: 0.6251
  Epoch 20... Train Loss: 0.3728, Val Loss: 0.3960
  Epoch 30... Train Loss: 0.2880, Val Loss: 0.4198
Fold 1 - MSE: 36.9176, RMSE: 6.0760, MAE: 4.2403
Starting fold 2...
  Epoch 0... Train Loss: 0.9786, Val Loss: 1.0795
  Epoch 10... Train Loss: 0.4167, Val Loss: 0.6231
  Epoch 20... Train Loss: 0.2506, Val Loss: 0.5803
  Epoch 30... Train Loss: 0.2348, Val Loss: 0.5089
  Epoch 40... Train Loss: 0.1968, Val Loss: 0.5047
  Epoch 50... Train Loss: 0.2131, Val Loss: 0.4867
  Epoch 60... Train Loss: 0.2050, Val Loss: 0.4872
  Epoch 70... Train Loss: 0.2024, Val Loss: 0.4785
  Epoch 80... Train Loss: 0.2042, Val Loss: 0.4826
Fold 2 - MSE: 43.6436, RMSE: 6.6063, MAE: 5.1001
Starting fold 3...
  Epoch 0... Train Loss: 1.1596, Val Loss: 1.1286
  Epoch 10... Train Loss: 0.3689, Val Loss: 0.5109
  Epoch 20... Train Loss: 0.2467, Val Loss: 0.4066
  Epoch 30... Train Loss: 0.2391, Val Loss: 0.3759
  Epoch 40... Train Loss: 0.1932, Val Loss: 0.3692
  Epoch 50... Train Loss: 0.2050, Val Loss: 0.3624
Fold 3 - MSE: 62.0029, RMSE: 7.8742, MAE: 4.9336
Starting fold 4...
  Epoch 0... Train Loss: 1.0025, Val Loss: 0.7063
  Epoch 10... Train Loss: 0.3787, Val Loss: 0.4344
Fold 4 - MSE: 33.4579, RMSE: 5.7843, MAE: 4.3987
Starting fold 5...
  Epoch 0... Train Loss: 1.2983, Val Loss: 1.4553
  Epoch 10... Train Loss: 0.4685, Val Loss: 1.1013
  Epoch 20... Train Loss: 0.3015, Val Loss: 0.9626
  Epoch 30... Train Loss: 0.2500, Val Loss: 0.8981

[INFO 04-02 10:04:12] ax.service.ax_client: Completed trial 39 with data: {'avg_rmse_nonzero': 6.800746}.

  Epoch 40... Train Loss: 0.2276, Val Loss: 0.8850
Fold 5 - MSE: 58.7206, RMSE: 7.6629, MAE: 6.3562

Mean CV MSE: 46.9485, Mean CV RMSE: 6.8007, Mean CV MAE: 5.0058
Completed trial 39 with mean RMSE: 6.8007 ± 0.4178
Saved Ax client checkpoint

[INFO 04-02 10:04:14] ax.service.ax_client: Generated new trial 40 with parameters {'dropout_rate': 0.225997, 'weight_decay': 1e-06, 'lr': 0.003962, 'batch_size': 32, 'early_stopping_patience': 12, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 64, 'activation': 'leaky_relu'} using model BoTorch.

Starting trial 40 with parameters: {'dropout_rate': 0.22599688872703758, 'weight_decay': 1.4581777510600302e-06, 'lr': 0.003962053659964967, 'batch_size': 32, 'early_stopping_patience': 12, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 64, 'activation': 'leaky_relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 2.5156, Val Loss: 7.9475
  Epoch 10... Train Loss: 0.5130, Val Loss: 0.4605
  Epoch 20... Train Loss: 0.5307, Val Loss: 0.4646
  Epoch 30... Train Loss: 0.3646, Val Loss: 0.3380
Fold 1 - MSE: 38.4991, RMSE: 6.2048, MAE: 4.1218
Starting fold 2...
  Epoch 0... Train Loss: 2.7256, Val Loss: 1.9564
  Epoch 10... Train Loss: 0.4949, Val Loss: 1.0473
  Epoch 20... Train Loss: 0.3266, Val Loss: 0.4252
  Epoch 30... Train Loss: 0.3291, Val Loss: 0.4693
  Epoch 40... Train Loss: 0.2925, Val Loss: 0.4330
  Epoch 50... Train Loss: 0.2105, Val Loss: 0.3519
  Epoch 60... Train Loss: 0.2289, Val Loss: 0.3547
  Epoch 70... Train Loss: 0.2435, Val Loss: 0.3423
Fold 2 - MSE: 40.0231, RMSE: 6.3264, MAE: 3.6446
Starting fold 3...
  Epoch 0... Train Loss: 2.3996, Val Loss: 1.2347
  Epoch 10... Train Loss: 0.4287, Val Loss: 0.5324
  Epoch 20... Train Loss: 0.3146, Val Loss: 0.4585
  Epoch 30... Train Loss: 0.2715, Val Loss: 0.4021
  Epoch 40... Train Loss: 0.2797, Val Loss: 0.3601
  Epoch 50... Train Loss: 0.2307, Val Loss: 0.3410
  Epoch 60... Train Loss: 0.2241, Val Loss: 0.3376
Fold 3 - MSE: 27.6048, RMSE: 5.2540, MAE: 3.2328
Starting fold 4...
  Epoch 0... Train Loss: 1.9899, Val Loss: 1.3986
  Epoch 10... Train Loss: 0.4718, Val Loss: 0.6661
  Epoch 20... Train Loss: 0.2306, Val Loss: 0.4823
  Epoch 30... Train Loss: 0.2267, Val Loss: 0.4459
  Epoch 40... Train Loss: 0.1931, Val Loss: 0.4795
Fold 4 - MSE: 30.5846, RMSE: 5.5303, MAE: 4.3867
Starting fold 5...
  Epoch 0... Train Loss: 1.8695, Val Loss: 1.8074
  Epoch 10... Train Loss: 0.4950, Val Loss: 0.7690
  Epoch 20... Train Loss: 0.3921, Val Loss: 0.8067
  Epoch 30... Train Loss: 0.2587, Val Loss: 0.6926
  Epoch 40... Train Loss: 0.2419, Val Loss: 0.7504
  Epoch 50... Train Loss: 0.2406, Val Loss: 0.7848

[INFO 04-02 10:04:41] ax.service.ax_client: Completed trial 40 with data: {'avg_rmse_nonzero': 5.376114}.

Fold 5 - MSE: 12.7097, RMSE: 3.5651, MAE: 3.1442

Mean CV MSE: 29.8843, Mean CV RMSE: 5.3761, Mean CV MAE: 3.7060
Completed trial 40 with mean RMSE: 5.3761 ± 0.4954
Saved Ax client checkpoint

[INFO 04-02 10:04:44] ax.service.ax_client: Generated new trial 41 with parameters {'dropout_rate': 0.5, 'weight_decay': 0.01, 'lr': 0.0016, 'batch_size': 256, 'early_stopping_patience': 14, 'n_layers': 3, 'hidden1': 128, 'hidden2': 1024, 'hidden3': 512, 'activation': 'leaky_relu'} using model BoTorch.

Starting trial 41 with parameters: {'dropout_rate': 0.5, 'weight_decay': 0.01, 'lr': 0.0016002140192375388, 'batch_size': 256, 'early_stopping_patience': 14, 'n_layers': 3, 'hidden1': 128, 'hidden2': 1024, 'hidden3': 512, 'activation': 'leaky_relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 1.2901, Val Loss: 1.1050
  Epoch 10... Train Loss: 0.8139, Val Loss: 0.5937
  Epoch 20... Train Loss: 0.4625, Val Loss: 0.3941
  Epoch 30... Train Loss: 0.4187, Val Loss: 0.4141
  Epoch 40... Train Loss: 0.4185, Val Loss: 0.3311
  Epoch 50... Train Loss: 0.4029, Val Loss: 0.3159
  Epoch 60... Train Loss: 0.3445, Val Loss: 0.3080
  Epoch 70... Train Loss: 0.3643, Val Loss: 0.3061
Fold 1 - MSE: 40.4086, RMSE: 6.3568, MAE: 4.1911
Starting fold 2...
  Epoch 0... Train Loss: 1.7273, Val Loss: 3.5667
  Epoch 10... Train Loss: 0.5288, Val Loss: 0.6749
  Epoch 20... Train Loss: 0.3744, Val Loss: 0.4255
  Epoch 30... Train Loss: 0.3550, Val Loss: 0.3897
  Epoch 40... Train Loss: 0.2574, Val Loss: 0.4027
Fold 2 - MSE: 40.1137, RMSE: 6.3335, MAE: 3.7226
Starting fold 3...
  Epoch 0... Train Loss: 1.8214, Val Loss: 2.0412
  Epoch 10... Train Loss: 0.5590, Val Loss: 0.6540
  Epoch 20... Train Loss: 0.3479, Val Loss: 0.4700
  Epoch 30... Train Loss: 0.3309, Val Loss: 0.4815
  Epoch 40... Train Loss: 0.2850, Val Loss: 0.4111
  Epoch 50... Train Loss: 0.2373, Val Loss: 0.3810
  Epoch 60... Train Loss: 0.2381, Val Loss: 0.3921
  Epoch 70... Train Loss: 0.2326, Val Loss: 0.3921
Fold 3 - MSE: 51.0031, RMSE: 7.1416, MAE: 3.8519
Starting fold 4...
  Epoch 0... Train Loss: 1.7813, Val Loss: 2.6592
  Epoch 10... Train Loss: 0.5406, Val Loss: 0.5420
  Epoch 20... Train Loss: 0.3181, Val Loss: 0.4684
  Epoch 30... Train Loss: 0.2928, Val Loss: 0.4697
Fold 4 - MSE: 30.7724, RMSE: 5.5473, MAE: 4.5152
Starting fold 5...
  Epoch 0... Train Loss: 1.3844, Val Loss: 1.5028
  Epoch 10... Train Loss: 0.5132, Val Loss: 0.9439
  Epoch 20... Train Loss: 0.3717, Val Loss: 0.8833
  Epoch 30... Train Loss: 0.2863, Val Loss: 0.8271
  Epoch 40... Train Loss: 0.2989, Val Loss: 0.7817

[INFO 04-02 10:04:49] ax.service.ax_client: Completed trial 41 with data: {'avg_rmse_nonzero': 5.69946}.

  Epoch 50... Train Loss: 0.2556, Val Loss: 0.7755
Fold 5 - MSE: 9.7222, RMSE: 3.1181, MAE: 2.5588

Mean CV MSE: 34.4040, Mean CV RMSE: 5.6995, Mean CV MAE: 3.7679
Completed trial 41 with mean RMSE: 5.6995 ± 0.6929
Saved Ax client checkpoint

[INFO 04-02 10:04:51] ax.service.ax_client: Generated new trial 42 with parameters {'dropout_rate': 0.20442, 'weight_decay': 1e-06, 'lr': 0.001589, 'batch_size': 256, 'early_stopping_patience': 44, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 32, 'activation': 'leaky_relu'} using model BoTorch.

Starting trial 42 with parameters: {'dropout_rate': 0.20442035661611885, 'weight_decay': 1e-06, 'lr': 0.0015891701199105246, 'batch_size': 256, 'early_stopping_patience': 44, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 32, 'activation': 'leaky_relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 2.2107, Val Loss: 6.5225
  Epoch 10... Train Loss: 0.6972, Val Loss: 0.7556
  Epoch 20... Train Loss: 0.4094, Val Loss: 0.3570
  Epoch 30... Train Loss: 0.3674, Val Loss: 0.3990
  Epoch 40... Train Loss: 0.3061, Val Loss: 0.3057
  Epoch 50... Train Loss: 0.3724, Val Loss: 0.3477
  Epoch 60... Train Loss: 0.3081, Val Loss: 0.2793
  Epoch 70... Train Loss: 0.2775, Val Loss: 0.3105
  Epoch 80... Train Loss: 0.3614, Val Loss: 0.2907
  Epoch 90... Train Loss: 0.2613, Val Loss: 0.2811
  Epoch 100... Train Loss: 0.3043, Val Loss: 0.2863
  Epoch 110... Train Loss: 0.2701, Val Loss: 0.2782
  Epoch 120... Train Loss: 0.3675, Val Loss: 0.2795
  Epoch 130... Train Loss: 0.2809, Val Loss: 0.2990
  Epoch 140... Train Loss: 0.3053, Val Loss: 0.2930
  Epoch 150... Train Loss: 0.3703, Val Loss: 0.2957
  Epoch 160... Train Loss: 0.2258, Val Loss: 0.3022
Fold 1 - MSE: 40.3066, RMSE: 6.3488, MAE: 4.2790
Starting fold 2...
  Epoch 0... Train Loss: 5.3370, Val Loss: 7.2161
  Epoch 10... Train Loss: 0.4755, Val Loss: 0.7947
  Epoch 20... Train Loss: 0.3023, Val Loss: 0.4632
  Epoch 30... Train Loss: 0.2787, Val Loss: 0.3574
  Epoch 40... Train Loss: 0.1976, Val Loss: 0.4414
  Epoch 50... Train Loss: 0.2367, Val Loss: 0.3978
  Epoch 60... Train Loss: 0.2143, Val Loss: 0.4134
  Epoch 70... Train Loss: 0.2089, Val Loss: 0.3772
  Epoch 80... Train Loss: 0.2060, Val Loss: 0.3750
  Epoch 90... Train Loss: 0.1989, Val Loss: 0.3378
  Epoch 100... Train Loss: 0.1886, Val Loss: 0.3666
Fold 2 - MSE: 37.4735, RMSE: 6.1216, MAE: 3.8089
Starting fold 3...
  Epoch 0... Train Loss: 4.5838, Val Loss: 3.7550
  Epoch 10... Train Loss: 0.4565, Val Loss: 0.6326
  Epoch 20... Train Loss: 0.2754, Val Loss: 0.4442
  Epoch 30... Train Loss: 0.2367, Val Loss: 0.4381
  Epoch 40... Train Loss: 0.2286, Val Loss: 0.4005
  Epoch 50... Train Loss: 0.2114, Val Loss: 0.4277
  Epoch 60... Train Loss: 0.1991, Val Loss: 0.3994
  Epoch 70... Train Loss: 0.1877, Val Loss: 0.3846
  Epoch 80... Train Loss: 0.2017, Val Loss: 0.3870
  Epoch 90... Train Loss: 0.1681, Val Loss: 0.3458
  Epoch 100... Train Loss: 0.2065, Val Loss: 0.3851
  Epoch 110... Train Loss: 0.1691, Val Loss: 0.3686
  Epoch 120... Train Loss: 0.1833, Val Loss: 0.3577
  Epoch 130... Train Loss: 0.1701, Val Loss: 0.3689
Fold 3 - MSE: 29.6075, RMSE: 5.4413, MAE: 3.2696
Starting fold 4...
  Epoch 0... Train Loss: 4.7496, Val Loss: 1.9829
  Epoch 10... Train Loss: 0.4648, Val Loss: 0.7289
  Epoch 20... Train Loss: 0.2463, Val Loss: 0.5339
  Epoch 30... Train Loss: 0.2088, Val Loss: 0.4868
  Epoch 40... Train Loss: 0.1786, Val Loss: 0.4893
  Epoch 50... Train Loss: 0.1500, Val Loss: 0.4659
  Epoch 60... Train Loss: 0.1482, Val Loss: 0.4281
  Epoch 70... Train Loss: 0.1571, Val Loss: 0.4685
  Epoch 80... Train Loss: 0.1640, Val Loss: 0.4488
  Epoch 90... Train Loss: 0.1500, Val Loss: 0.4538
Fold 4 - MSE: 31.5976, RMSE: 5.6212, MAE: 4.4195
Starting fold 5...
  Epoch 0... Train Loss: 5.3239, Val Loss: 3.6965
  Epoch 10... Train Loss: 0.5023, Val Loss: 1.1240
  Epoch 20... Train Loss: 0.3293, Val Loss: 0.8050
  Epoch 30... Train Loss: 0.2600, Val Loss: 0.8036
  Epoch 40... Train Loss: 0.2459, Val Loss: 0.7534
  Epoch 50... Train Loss: 0.2351, Val Loss: 0.7544
  Epoch 60... Train Loss: 0.2169, Val Loss: 0.7626
  Epoch 70... Train Loss: 0.1983, Val Loss: 0.7490

[INFO 04-02 10:05:00] ax.service.ax_client: Completed trial 42 with data: {'avg_rmse_nonzero': 5.202314}.

Fold 5 - MSE: 6.1445, RMSE: 2.4788, MAE: 1.9894

Mean CV MSE: 29.0259, Mean CV RMSE: 5.2023, Mean CV MAE: 3.5533
Completed trial 42 with mean RMSE: 5.2023 ± 0.7003
Saved Ax client checkpoint

[INFO 04-02 10:05:03] ax.service.ax_client: Generated new trial 43 with parameters {'dropout_rate': 0.5, 'weight_decay': 0.01, 'lr': 0.00187, 'batch_size': 256, 'early_stopping_patience': 50, 'n_layers': 1, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 32, 'activation': 'leaky_relu'} using model BoTorch.

Starting trial 43 with parameters: {'dropout_rate': 0.5, 'weight_decay': 0.01, 'lr': 0.0018697575683858936, 'batch_size': 256, 'early_stopping_patience': 50, 'n_layers': 1, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 32, 'activation': 'leaky_relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 16.3733, Val Loss: 133.6879
  Epoch 10... Train Loss: 0.8601, Val Loss: 0.7930
  Epoch 20... Train Loss: 0.4597, Val Loss: 0.5048
  Epoch 30... Train Loss: 0.3975, Val Loss: 0.4722
  Epoch 40... Train Loss: 0.3676, Val Loss: 0.4979
  Epoch 50... Train Loss: 0.4317, Val Loss: 0.4118
  Epoch 60... Train Loss: 0.4261, Val Loss: 0.4432
  Epoch 70... Train Loss: 0.2944, Val Loss: 0.4508
  Epoch 80... Train Loss: 0.4297, Val Loss: 0.3597
  Epoch 90... Train Loss: 0.3766, Val Loss: 0.4029
  Epoch 100... Train Loss: 0.3937, Val Loss: 0.3616
  Epoch 110... Train Loss: 0.3159, Val Loss: 0.3700
  Epoch 120... Train Loss: 0.4455, Val Loss: 0.3929
  Epoch 130... Train Loss: 0.2961, Val Loss: 0.4536
  Epoch 140... Train Loss: 0.3020, Val Loss: 0.3696
  Epoch 150... Train Loss: 0.3415, Val Loss: 0.3982
Fold 1 - MSE: 39.9447, RMSE: 6.3202, MAE: 4.3530
Starting fold 2...
  Epoch 0... Train Loss: 13.6304, Val Loss: 12.7622
  Epoch 10... Train Loss: 0.5834, Val Loss: 0.6997
  Epoch 20... Train Loss: 0.3638, Val Loss: 0.5488
  Epoch 30... Train Loss: 0.3670, Val Loss: 0.5236
  Epoch 40... Train Loss: 0.3442, Val Loss: 0.5429
  Epoch 50... Train Loss: 0.3677, Val Loss: 0.5331
  Epoch 60... Train Loss: 0.3744, Val Loss: 0.5149
  Epoch 70... Train Loss: 0.3060, Val Loss: 0.5292
  Epoch 80... Train Loss: 0.3250, Val Loss: 0.5088
  Epoch 90... Train Loss: 0.3251, Val Loss: 0.4298
  Epoch 100... Train Loss: 0.3054, Val Loss: 0.5261
  Epoch 110... Train Loss: 0.2526, Val Loss: 0.4552
  Epoch 120... Train Loss: 0.2581, Val Loss: 0.4492
  Epoch 130... Train Loss: 0.2211, Val Loss: 0.4139
Fold 2 - MSE: 40.3080, RMSE: 6.3489, MAE: 3.7798
Starting fold 3...
  Epoch 0... Train Loss: 11.1023, Val Loss: 15.3962
  Epoch 10... Train Loss: 0.5118, Val Loss: 0.6241
  Epoch 20... Train Loss: 0.3523, Val Loss: 0.5418
  Epoch 30... Train Loss: 0.3468, Val Loss: 0.4757
  Epoch 40... Train Loss: 0.2965, Val Loss: 0.4498
  Epoch 50... Train Loss: 0.3135, Val Loss: 0.5438
  Epoch 60... Train Loss: 0.3431, Val Loss: 0.4936
  Epoch 70... Train Loss: 0.2900, Val Loss: 0.4787
  Epoch 80... Train Loss: 0.2703, Val Loss: 0.4755
  Epoch 90... Train Loss: 0.2692, Val Loss: 0.4053
  Epoch 100... Train Loss: 0.3053, Val Loss: 0.4384
  Epoch 110... Train Loss: 0.2647, Val Loss: 0.4188
  Epoch 120... Train Loss: 0.2546, Val Loss: 0.4049
  Epoch 130... Train Loss: 0.2188, Val Loss: 0.3943
  Epoch 140... Train Loss: 0.2069, Val Loss: 0.3880
  Epoch 150... Train Loss: 0.2282, Val Loss: 0.3635
  Epoch 160... Train Loss: 0.2265, Val Loss: 0.3845
  Epoch 170... Train Loss: 0.2250, Val Loss: 0.3528
  Epoch 180... Train Loss: 0.2046, Val Loss: 0.3655
  Epoch 190... Train Loss: 0.2165, Val Loss: 0.3716
  Epoch 200... Train Loss: 0.2070, Val Loss: 0.3554
  Epoch 210... Train Loss: 0.1869, Val Loss: 0.3652
Fold 3 - MSE: 101.7951, RMSE: 10.0894, MAE: 5.3073
Starting fold 4...
  Epoch 0... Train Loss: 15.8597, Val Loss: 20.9431
  Epoch 10... Train Loss: 0.5860, Val Loss: 0.5822
  Epoch 20... Train Loss: 0.3327, Val Loss: 0.4342
  Epoch 30... Train Loss: 0.3335, Val Loss: 0.4892
  Epoch 40... Train Loss: 0.2682, Val Loss: 0.4603
  Epoch 50... Train Loss: 0.2721, Val Loss: 0.5462
  Epoch 60... Train Loss: 0.2388, Val Loss: 0.4558
  Epoch 70... Train Loss: 0.2268, Val Loss: 0.4492
Fold 4 - MSE: 39.1388, RMSE: 6.2561, MAE: 4.7386
Starting fold 5...
  Epoch 0... Train Loss: 12.9123, Val Loss: 16.4776
  Epoch 10... Train Loss: 0.5537, Val Loss: 1.0524
  Epoch 20... Train Loss: 0.3725, Val Loss: 0.9383
  Epoch 30... Train Loss: 0.3691, Val Loss: 0.8993
  Epoch 40... Train Loss: 0.3572, Val Loss: 0.7569
  Epoch 50... Train Loss: 0.3349, Val Loss: 0.9641
  Epoch 60... Train Loss: 0.3500, Val Loss: 0.8763
  Epoch 70... Train Loss: 0.3270, Val Loss: 0.8155
  Epoch 80... Train Loss: 0.2941, Val Loss: 0.8240

[INFO 04-02 10:05:12] ax.service.ax_client: Completed trial 43 with data: {'avg_rmse_nonzero': 6.450753}.

  Epoch 90... Train Loss: 0.2834, Val Loss: 0.8003
Fold 5 - MSE: 10.4929, RMSE: 3.2393, MAE: 2.3716

Mean CV MSE: 46.3359, Mean CV RMSE: 6.4508, Mean CV MAE: 4.1101
Completed trial 43 with mean RMSE: 6.4508 ± 1.0867
Saved Ax client checkpoint

[INFO 04-02 10:05:14] ax.service.ax_client: Generated new trial 44 with parameters {'dropout_rate': 0.5, 'weight_decay': 0.01, 'lr': 1e-05, 'batch_size': 32, 'early_stopping_patience': 42, 'n_layers': 3, 'hidden1': 128, 'hidden2': 64, 'hidden3': 512, 'activation': 'elu'} using model BoTorch.

Starting trial 44 with parameters: {'dropout_rate': 0.5, 'weight_decay': 0.01, 'lr': 1e-05, 'batch_size': 32, 'early_stopping_patience': 42, 'n_layers': 3, 'hidden1': 128, 'hidden2': 64, 'hidden3': 512, 'activation': 'elu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 1.2615, Val Loss: 0.8196
  Epoch 10... Train Loss: 0.9343, Val Loss: 0.5048
  Epoch 20... Train Loss: 0.9594, Val Loss: 0.4372
  Epoch 30... Train Loss: 0.8152, Val Loss: 0.3821
  Epoch 40... Train Loss: 0.7027, Val Loss: 0.3742
  Epoch 50... Train Loss: 0.7420, Val Loss: 0.4781
  Epoch 60... Train Loss: 0.7445, Val Loss: 0.3415
  Epoch 70... Train Loss: 0.7544, Val Loss: 0.3603
  Epoch 80... Train Loss: 0.7165, Val Loss: 0.3345
  Epoch 90... Train Loss: 0.7291, Val Loss: 0.3717
  Epoch 100... Train Loss: 0.6684, Val Loss: 0.2967
  Epoch 110... Train Loss: 0.6074, Val Loss: 0.3519
  Epoch 120... Train Loss: 0.7700, Val Loss: 0.3796
  Epoch 130... Train Loss: 0.6347, Val Loss: 0.3175
  Epoch 140... Train Loss: 0.6666, Val Loss: 0.4160
  Epoch 150... Train Loss: 0.6681, Val Loss: 0.3827
Fold 1 - MSE: 45.6268, RMSE: 6.7548, MAE: 4.5696
Starting fold 2...
  Epoch 0... Train Loss: 1.2740, Val Loss: 0.8169
  Epoch 10... Train Loss: 0.8741, Val Loss: 0.7397
  Epoch 20... Train Loss: 0.7670, Val Loss: 0.6244
  Epoch 30... Train Loss: 0.7417, Val Loss: 0.6067
  Epoch 40... Train Loss: 0.6367, Val Loss: 0.6074
  Epoch 50... Train Loss: 0.7109, Val Loss: 0.6292
  Epoch 60... Train Loss: 0.6291, Val Loss: 0.5914
  Epoch 70... Train Loss: 0.6605, Val Loss: 0.5807
Fold 2 - MSE: 48.8530, RMSE: 6.9895, MAE: 4.7768
Starting fold 3...
  Epoch 0... Train Loss: 1.3260, Val Loss: 0.9729
  Epoch 10... Train Loss: 0.8427, Val Loss: 0.5881
  Epoch 20... Train Loss: 0.8273, Val Loss: 0.5298
  Epoch 30... Train Loss: 0.7592, Val Loss: 0.5283
  Epoch 40... Train Loss: 0.6939, Val Loss: 0.4940
  Epoch 50... Train Loss: 0.6846, Val Loss: 0.4775
  Epoch 60... Train Loss: 0.6527, Val Loss: 0.4667
  Epoch 70... Train Loss: 0.6308, Val Loss: 0.4538
  Epoch 80... Train Loss: 0.5643, Val Loss: 0.4580
  Epoch 90... Train Loss: 0.5690, Val Loss: 0.4593
  Epoch 100... Train Loss: 0.5729, Val Loss: 0.4676
  Epoch 110... Train Loss: 0.5363, Val Loss: 0.4562
Fold 3 - MSE: 59.0511, RMSE: 7.6845, MAE: 4.6950
Starting fold 4...
  Epoch 0... Train Loss: 1.2807, Val Loss: 0.5944
  Epoch 10... Train Loss: 0.8919, Val Loss: 0.5274
  Epoch 20... Train Loss: 0.7658, Val Loss: 0.5330
  Epoch 30... Train Loss: 0.6787, Val Loss: 0.5353
  Epoch 40... Train Loss: 0.7143, Val Loss: 0.5381
  Epoch 50... Train Loss: 0.7255, Val Loss: 0.5377
  Epoch 60... Train Loss: 0.6589, Val Loss: 0.5367
  Epoch 70... Train Loss: 0.6526, Val Loss: 0.5307
  Epoch 80... Train Loss: 0.7220, Val Loss: 0.5306
  Epoch 90... Train Loss: 0.5916, Val Loss: 0.5399
  Epoch 100... Train Loss: 0.6139, Val Loss: 0.5506
  Epoch 110... Train Loss: 0.6061, Val Loss: 0.5484
Fold 4 - MSE: 34.6366, RMSE: 5.8853, MAE: 4.5349
Starting fold 5...
  Epoch 0... Train Loss: 1.2453, Val Loss: 1.4267
  Epoch 10... Train Loss: 0.9019, Val Loss: 1.0154
  Epoch 20... Train Loss: 0.7562, Val Loss: 1.0223
  Epoch 30... Train Loss: 0.7028, Val Loss: 0.8990
  Epoch 40... Train Loss: 0.7115, Val Loss: 0.9459
  Epoch 50... Train Loss: 0.6691, Val Loss: 1.0439
  Epoch 60... Train Loss: 0.6481, Val Loss: 0.8806
  Epoch 70... Train Loss: 0.6422, Val Loss: 0.8746
  Epoch 80... Train Loss: 0.6286, Val Loss: 0.9154
  Epoch 90... Train Loss: 0.6684, Val Loss: 0.8775
  Epoch 100... Train Loss: 0.5577, Val Loss: 0.8957
  Epoch 110... Train Loss: 0.6200, Val Loss: 0.9514

[INFO 04-02 10:06:02] ax.service.ax_client: Completed trial 44 with data: {'avg_rmse_nonzero': 6.97543}.

Fold 5 - MSE: 57.2010, RMSE: 7.5631, MAE: 6.8546

Mean CV MSE: 49.0737, Mean CV RMSE: 6.9754, Mean CV MAE: 5.0862
Completed trial 44 with mean RMSE: 6.9754 ± 0.3229
Saved Ax client checkpoint

[INFO 04-02 10:06:04] ax.service.ax_client: Generated new trial 45 with parameters {'dropout_rate': 0.172696, 'weight_decay': 1e-06, 'lr': 0.005174, 'batch_size': 32, 'early_stopping_patience': 27, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 32, 'activation': 'leaky_relu'} using model BoTorch.

Starting trial 45 with parameters: {'dropout_rate': 0.17269559845222276, 'weight_decay': 1e-06, 'lr': 0.005173653447841547, 'batch_size': 32, 'early_stopping_patience': 27, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 32, 'activation': 'leaky_relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 3.5241, Val Loss: 28.9997
  Epoch 10... Train Loss: 0.5319, Val Loss: 0.4383
  Epoch 20... Train Loss: 0.5320, Val Loss: 0.3778
  Epoch 30... Train Loss: 0.4173, Val Loss: 0.5482
  Epoch 40... Train Loss: 0.3129, Val Loss: 0.2688
  Epoch 50... Train Loss: 0.3984, Val Loss: 0.3371
Fold 1 - MSE: 40.8177, RMSE: 6.3889, MAE: 4.3434
Starting fold 2...
  Epoch 0... Train Loss: 3.2510, Val Loss: 5.1012
  Epoch 10... Train Loss: 0.4783, Val Loss: 0.7117
  Epoch 20... Train Loss: 0.3692, Val Loss: 0.4260
  Epoch 30... Train Loss: 0.3291, Val Loss: 0.5837
  Epoch 40... Train Loss: 0.2837, Val Loss: 0.3862
  Epoch 50... Train Loss: 0.2252, Val Loss: 0.3814
Fold 2 - MSE: 42.8618, RMSE: 6.5469, MAE: 4.1421
Starting fold 3...
  Epoch 0... Train Loss: 2.3405, Val Loss: 0.9820
  Epoch 10... Train Loss: 0.4386, Val Loss: 0.5056
  Epoch 20... Train Loss: 0.3417, Val Loss: 0.3961
  Epoch 30... Train Loss: 0.2956, Val Loss: 0.3808
  Epoch 40... Train Loss: 0.2758, Val Loss: 0.4164
  Epoch 50... Train Loss: 0.2496, Val Loss: 0.3663
  Epoch 60... Train Loss: 0.2407, Val Loss: 0.4402
  Epoch 70... Train Loss: 0.2061, Val Loss: 0.3388
  Epoch 80... Train Loss: 0.2114, Val Loss: 0.3254
  Epoch 90... Train Loss: 0.1915, Val Loss: 0.3389
Fold 3 - MSE: 21.8769, RMSE: 4.6773, MAE: 2.9072
Starting fold 4...
  Epoch 0... Train Loss: 2.4618, Val Loss: 1.1218
  Epoch 10... Train Loss: 0.4638, Val Loss: 0.7943
  Epoch 20... Train Loss: 0.2634, Val Loss: 0.4845
  Epoch 30... Train Loss: 0.2661, Val Loss: 0.4230
  Epoch 40... Train Loss: 0.2266, Val Loss: 0.4192
  Epoch 50... Train Loss: 0.1922, Val Loss: 0.4705
Fold 4 - MSE: 36.5870, RMSE: 6.0487, MAE: 4.8640
Starting fold 5...
  Epoch 0... Train Loss: 2.2184, Val Loss: 3.1271
  Epoch 10... Train Loss: 0.5004, Val Loss: 0.9867
  Epoch 20... Train Loss: 0.3363, Val Loss: 0.7004
  Epoch 30... Train Loss: 0.2830, Val Loss: 0.7367
  Epoch 40... Train Loss: 0.2507, Val Loss: 0.7414
  Epoch 50... Train Loss: 0.2520, Val Loss: 0.9439
  Epoch 60... Train Loss: 0.2341, Val Loss: 0.8032
  Epoch 70... Train Loss: 0.2311, Val Loss: 0.7678

[INFO 04-02 10:06:35] ax.service.ax_client: Completed trial 45 with data: {'avg_rmse_nonzero': 5.349535}.

Fold 5 - MSE: 9.5228, RMSE: 3.0859, MAE: 2.6930

Mean CV MSE: 30.3333, Mean CV RMSE: 5.3495, Mean CV MAE: 3.7899
Completed trial 45 with mean RMSE: 5.3495 ± 0.6549
Saved Ax client checkpoint

[INFO 04-02 10:06:37] ax.service.ax_client: Generated new trial 46 with parameters {'dropout_rate': 0.208745, 'weight_decay': 1e-06, 'lr': 0.008408, 'batch_size': 32, 'early_stopping_patience': 47, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 128, 'activation': 'leaky_relu'} using model BoTorch.

Starting trial 46 with parameters: {'dropout_rate': 0.20874493317242565, 'weight_decay': 1e-06, 'lr': 0.008408416258224905, 'batch_size': 32, 'early_stopping_patience': 47, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 128, 'activation': 'leaky_relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 3.8361, Val Loss: 15.3889
  Epoch 10... Train Loss: 0.5183, Val Loss: 0.4212
  Epoch 20... Train Loss: 0.5861, Val Loss: 0.5400
  Epoch 30... Train Loss: 0.3984, Val Loss: 0.4961
  Epoch 40... Train Loss: 0.3668, Val Loss: 0.3747
  Epoch 50... Train Loss: 0.5334, Val Loss: 0.5171
  Epoch 60... Train Loss: 0.3107, Val Loss: 0.3757
  Epoch 70... Train Loss: 0.3442, Val Loss: 0.4438
  Epoch 80... Train Loss: 0.2984, Val Loss: 0.3773
Fold 1 - MSE: 42.6266, RMSE: 6.5289, MAE: 4.3923
Starting fold 2...
  Epoch 0... Train Loss: 2.7399, Val Loss: 1.8433
  Epoch 10... Train Loss: 0.5386, Val Loss: 1.0514
  Epoch 20... Train Loss: 0.4093, Val Loss: 0.5093
  Epoch 30... Train Loss: 0.3548, Val Loss: 0.5877
  Epoch 40... Train Loss: 0.3112, Val Loss: 0.4230
  Epoch 50... Train Loss: 0.2785, Val Loss: 0.5295
  Epoch 60... Train Loss: 0.2370, Val Loss: 0.3899
  Epoch 70... Train Loss: 0.2634, Val Loss: 0.3574
  Epoch 80... Train Loss: 0.2243, Val Loss: 0.4245
  Epoch 90... Train Loss: 0.1954, Val Loss: 0.3482
  Epoch 100... Train Loss: 0.1900, Val Loss: 0.3633
  Epoch 110... Train Loss: 0.1990, Val Loss: 0.3548
Fold 2 - MSE: 43.0030, RMSE: 6.5577, MAE: 3.8332
Starting fold 3...
  Epoch 0... Train Loss: 2.1752, Val Loss: 1.6846
  Epoch 10... Train Loss: 0.4878, Val Loss: 0.5859
  Epoch 20... Train Loss: 0.3591, Val Loss: 0.5185
  Epoch 30... Train Loss: 0.3608, Val Loss: 0.4403
  Epoch 40... Train Loss: 0.2989, Val Loss: 0.3805
  Epoch 50... Train Loss: 0.2518, Val Loss: 0.3970
  Epoch 60... Train Loss: 0.2974, Val Loss: 0.4072
  Epoch 70... Train Loss: 0.2120, Val Loss: 0.3356
  Epoch 80... Train Loss: 0.2265, Val Loss: 0.3678
  Epoch 90... Train Loss: 0.2258, Val Loss: 0.3931
  Epoch 100... Train Loss: 0.1990, Val Loss: 0.3541
  Epoch 110... Train Loss: 0.2040, Val Loss: 0.3570
  Epoch 120... Train Loss: 0.2042, Val Loss: 0.3432
  Epoch 130... Train Loss: 0.1879, Val Loss: 0.3114
  Epoch 140... Train Loss: 0.1707, Val Loss: 0.3046
  Epoch 150... Train Loss: 0.1762, Val Loss: 0.3174
  Epoch 160... Train Loss: 0.1900, Val Loss: 0.3245
  Epoch 170... Train Loss: 0.1712, Val Loss: 0.2955
  Epoch 180... Train Loss: 0.1740, Val Loss: 0.3163
  Epoch 190... Train Loss: 0.1680, Val Loss: 0.3095
  Epoch 200... Train Loss: 0.1685, Val Loss: 0.3061
  Epoch 210... Train Loss: 0.1712, Val Loss: 0.3004
  Epoch 220... Train Loss: 0.1490, Val Loss: 0.2983
Fold 3 - MSE: 23.6786, RMSE: 4.8661, MAE: 2.9371
Starting fold 4...
  Epoch 0... Train Loss: 2.7534, Val Loss: 1.7467
  Epoch 10... Train Loss: 0.4285, Val Loss: 0.6286
  Epoch 20... Train Loss: 0.2759, Val Loss: 0.4809
  Epoch 30... Train Loss: 0.2732, Val Loss: 0.3995
  Epoch 40... Train Loss: 0.2455, Val Loss: 0.4604
  Epoch 50... Train Loss: 0.2019, Val Loss: 0.4339
  Epoch 60... Train Loss: 0.1873, Val Loss: 0.4474
  Epoch 70... Train Loss: 0.1935, Val Loss: 0.5237
  Epoch 80... Train Loss: 0.1750, Val Loss: 0.4393
  Epoch 90... Train Loss: 0.1707, Val Loss: 0.4332
  Epoch 100... Train Loss: 0.1572, Val Loss: 0.4460
Fold 4 - MSE: 26.5327, RMSE: 5.1510, MAE: 4.0636
Starting fold 5...
  Epoch 0... Train Loss: 2.7930, Val Loss: 5.0119
  Epoch 10... Train Loss: 0.5116, Val Loss: 0.9421
  Epoch 20... Train Loss: 0.4023, Val Loss: 0.7131
  Epoch 30... Train Loss: 0.3014, Val Loss: 0.7556
  Epoch 40... Train Loss: 0.2517, Val Loss: 0.7379
  Epoch 50... Train Loss: 0.2937, Val Loss: 0.8119
  Epoch 60... Train Loss: 0.2676, Val Loss: 0.7130
  Epoch 70... Train Loss: 0.2486, Val Loss: 0.6930
  Epoch 80... Train Loss: 0.2499, Val Loss: 0.6820
  Epoch 90... Train Loss: 0.2316, Val Loss: 0.6517
  Epoch 100... Train Loss: 0.1928, Val Loss: 0.6622

[INFO 04-02 10:07:28] ax.service.ax_client: Completed trial 46 with data: {'avg_rmse_nonzero': 5.691714}.

  Epoch 110... Train Loss: 0.2014, Val Loss: 0.6337
Fold 5 - MSE: 28.6753, RMSE: 5.3549, MAE: 4.9122

Mean CV MSE: 32.9033, Mean CV RMSE: 5.6917, Mean CV MAE: 4.0276
Completed trial 46 with mean RMSE: 5.6917 ± 0.3562
Saved Ax client checkpoint

[INFO 04-02 10:07:30] ax.service.ax_client: Generated new trial 47 with parameters {'dropout_rate': 0.320232, 'weight_decay': 1e-06, 'lr': 0.003618, 'batch_size': 256, 'early_stopping_patience': 11, 'n_layers': 3, 'hidden1': 1024, 'hidden2': 1024, 'hidden3': 32, 'activation': 'leaky_relu'} using model BoTorch.

Starting trial 47 with parameters: {'dropout_rate': 0.3202319140956494, 'weight_decay': 1e-06, 'lr': 0.003618242390529145, 'batch_size': 256, 'early_stopping_patience': 11, 'n_layers': 3, 'hidden1': 1024, 'hidden2': 1024, 'hidden3': 32, 'activation': 'leaky_relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 2.9558, Val Loss: 132.1604
  Epoch 10... Train Loss: 0.7983, Val Loss: 1.2134
  Epoch 20... Train Loss: 0.4947, Val Loss: 0.5005
  Epoch 30... Train Loss: 0.4600, Val Loss: 0.4608
  Epoch 40... Train Loss: 0.4111, Val Loss: 0.3980
  Epoch 50... Train Loss: 0.4069, Val Loss: 0.3480
  Epoch 60... Train Loss: 0.3829, Val Loss: 0.3562
Fold 1 - MSE: 39.3580, RMSE: 6.2736, MAE: 4.0436
Starting fold 2...
  Epoch 0... Train Loss: 8.5622, Val Loss: 317.1032
  Epoch 10... Train Loss: 0.6325, Val Loss: 0.7997
  Epoch 20... Train Loss: 0.4195, Val Loss: 0.6779
  Epoch 30... Train Loss: 0.4017, Val Loss: 0.5641
  Epoch 40... Train Loss: 0.3203, Val Loss: 0.5251
  Epoch 50... Train Loss: 0.3223, Val Loss: 0.5072
Fold 2 - MSE: 37.9317, RMSE: 6.1589, MAE: 3.6311
Starting fold 3...
  Epoch 0... Train Loss: 6.8696, Val Loss: 214.2101
  Epoch 10... Train Loss: 0.6101, Val Loss: 0.8484
  Epoch 20... Train Loss: 0.3676, Val Loss: 0.5684
  Epoch 30... Train Loss: 0.3026, Val Loss: 0.5078
  Epoch 40... Train Loss: 0.2540, Val Loss: 0.4765
Fold 3 - MSE: 24.8587, RMSE: 4.9858, MAE: 3.1342
Starting fold 4...
  Epoch 0... Train Loss: 8.2254, Val Loss: 192.7179
  Epoch 10... Train Loss: 0.6573, Val Loss: 0.6705
  Epoch 20... Train Loss: 0.3909, Val Loss: 0.5482
  Epoch 30... Train Loss: 0.3139, Val Loss: 0.5323
  Epoch 40... Train Loss: 0.2656, Val Loss: 0.5356
  Epoch 50... Train Loss: 0.2259, Val Loss: 0.4686
  Epoch 60... Train Loss: 0.2186, Val Loss: 0.4961
Fold 4 - MSE: 31.1141, RMSE: 5.5780, MAE: 4.4489
Starting fold 5...
  Epoch 0... Train Loss: 7.7752, Val Loss: 194.9552
  Epoch 10... Train Loss: 0.6614, Val Loss: 1.4733
  Epoch 20... Train Loss: 0.5096, Val Loss: 1.1081
  Epoch 30... Train Loss: 0.3620, Val Loss: 0.9517
  Epoch 40... Train Loss: 0.3108, Val Loss: 0.8785
  Epoch 50... Train Loss: 0.2637, Val Loss: 0.8048

[INFO 04-02 10:07:37] ax.service.ax_client: Completed trial 47 with data: {'avg_rmse_nonzero': 5.211295}.

  Epoch 60... Train Loss: 0.2595, Val Loss: 0.7797
Fold 5 - MSE: 9.3646, RMSE: 3.0602, MAE: 2.7003

Mean CV MSE: 28.5254, Mean CV RMSE: 5.2113, Mean CV MAE: 3.5916
Completed trial 47 with mean RMSE: 5.2113 ± 0.5848
Saved Ax client checkpoint

[INFO 04-02 10:07:39] ax.service.ax_client: Generated new trial 48 with parameters {'dropout_rate': 0.205598, 'weight_decay': 1e-06, 'lr': 0.003009, 'batch_size': 256, 'early_stopping_patience': 10, 'n_layers': 3, 'hidden1': 1024, 'hidden2': 1024, 'hidden3': 32, 'activation': 'leaky_relu'} using model BoTorch.

Starting trial 48 with parameters: {'dropout_rate': 0.2055981858264789, 'weight_decay': 1e-06, 'lr': 0.0030089339583540932, 'batch_size': 256, 'early_stopping_patience': 10, 'n_layers': 3, 'hidden1': 1024, 'hidden2': 1024, 'hidden3': 32, 'activation': 'leaky_relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 3.4743, Val Loss: 19.2642
  Epoch 10... Train Loss: 0.7409, Val Loss: 1.0662
  Epoch 20... Train Loss: 0.4986, Val Loss: 0.5578
  Epoch 30... Train Loss: 0.3994, Val Loss: 0.4895
Fold 1 - MSE: 37.2154, RMSE: 6.1004, MAE: 4.2947
Starting fold 2...
  Epoch 0... Train Loss: 8.6375, Val Loss: 353.9030
  Epoch 10... Train Loss: 0.6159, Val Loss: 0.7910
  Epoch 20... Train Loss: 0.3488, Val Loss: 0.6644
  Epoch 30... Train Loss: 0.3103, Val Loss: 0.4519
  Epoch 40... Train Loss: 0.2629, Val Loss: 0.4485
  Epoch 50... Train Loss: 0.2678, Val Loss: 0.4556
Fold 2 - MSE: 30.6940, RMSE: 5.5402, MAE: 3.5274
Starting fold 3...
  Epoch 0... Train Loss: 8.3570, Val Loss: 266.8415
  Epoch 10... Train Loss: 0.6250, Val Loss: 0.7548
  Epoch 20... Train Loss: 0.3919, Val Loss: 0.6022
  Epoch 30... Train Loss: 0.3255, Val Loss: 0.4512
  Epoch 40... Train Loss: 0.2336, Val Loss: 0.3945
  Epoch 50... Train Loss: 0.2237, Val Loss: 0.4125
Fold 3 - MSE: 19.1401, RMSE: 4.3749, MAE: 2.7834
Starting fold 4...
  Epoch 0... Train Loss: 8.9771, Val Loss: 94.8121
  Epoch 10... Train Loss: 0.6263, Val Loss: 0.5838
  Epoch 20... Train Loss: 0.4033, Val Loss: 0.5492
Fold 4 - MSE: 37.8242, RMSE: 6.1501, MAE: 4.9289
Starting fold 5...
  Epoch 0... Train Loss: 9.1431, Val Loss: 154.2301
  Epoch 10... Train Loss: 0.6341, Val Loss: 1.4770
  Epoch 20... Train Loss: 0.4715, Val Loss: 1.0574
  Epoch 30... Train Loss: 0.3250, Val Loss: 0.9101
  Epoch 40... Train Loss: 0.2701, Val Loss: 0.8646

[INFO 04-02 10:07:44] ax.service.ax_client: Completed trial 48 with data: {'avg_rmse_nonzero': 4.931648}.

  Epoch 50... Train Loss: 0.2615, Val Loss: 0.8324
Fold 5 - MSE: 6.2125, RMSE: 2.4925, MAE: 1.9430

Mean CV MSE: 26.2173, Mean CV RMSE: 4.9316, Mean CV MAE: 3.4955
Completed trial 48 with mean RMSE: 4.9316 ± 0.6885
Saved Ax client checkpoint

[INFO 04-02 10:07:47] ax.service.ax_client: Generated new trial 49 with parameters {'dropout_rate': 0.2888, 'weight_decay': 1e-06, 'lr': 0.002726, 'batch_size': 256, 'early_stopping_patience': 10, 'n_layers': 3, 'hidden1': 256, 'hidden2': 1024, 'hidden3': 32, 'activation': 'leaky_relu'} using model BoTorch.

Starting trial 49 with parameters: {'dropout_rate': 0.2887996208312125, 'weight_decay': 1.0495255931868301e-06, 'lr': 0.002726399155948507, 'batch_size': 256, 'early_stopping_patience': 10, 'n_layers': 3, 'hidden1': 256, 'hidden2': 1024, 'hidden3': 32, 'activation': 'leaky_relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 2.4341, Val Loss: 51.7718
  Epoch 10... Train Loss: 0.6998, Val Loss: 0.8792
  Epoch 20... Train Loss: 0.4735, Val Loss: 0.4254
  Epoch 30... Train Loss: 0.3921, Val Loss: 0.4440
Fold 1 - MSE: 39.1527, RMSE: 6.2572, MAE: 4.1562
Starting fold 2...
  Epoch 0... Train Loss: 8.5742, Val Loss: 106.1623
  Epoch 10... Train Loss: 0.5721, Val Loss: 0.8395
  Epoch 20... Train Loss: 0.3572, Val Loss: 0.6141
  Epoch 30... Train Loss: 0.2810, Val Loss: 0.4661
  Epoch 40... Train Loss: 0.2450, Val Loss: 0.4371
Fold 2 - MSE: 35.2012, RMSE: 5.9331, MAE: 3.6379
Starting fold 3...
  Epoch 0... Train Loss: 5.7400, Val Loss: 67.3137
  Epoch 10... Train Loss: 0.5176, Val Loss: 0.7473
  Epoch 20... Train Loss: 0.3147, Val Loss: 0.5020
  Epoch 30... Train Loss: 0.2990, Val Loss: 0.5041
  Epoch 40... Train Loss: 0.2281, Val Loss: 0.4629
Fold 3 - MSE: 18.5434, RMSE: 4.3062, MAE: 2.8113
Starting fold 4...
  Epoch 0... Train Loss: 7.1252, Val Loss: 14.3405
  Epoch 10... Train Loss: 0.5855, Val Loss: 0.6820
  Epoch 20... Train Loss: 0.3721, Val Loss: 0.5221
Fold 4 - MSE: 33.0659, RMSE: 5.7503, MAE: 4.4906
Starting fold 5...
  Epoch 0... Train Loss: 7.5067, Val Loss: 94.0671
  Epoch 10... Train Loss: 0.6113, Val Loss: 1.3779
  Epoch 20... Train Loss: 0.4092, Val Loss: 0.9960
  Epoch 30... Train Loss: 0.2979, Val Loss: 0.8881
  Epoch 40... Train Loss: 0.2753, Val Loss: 0.8378
  Epoch 50... Train Loss: 0.2513, Val Loss: 0.7906
  Epoch 60... Train Loss: 0.2358, Val Loss: 0.7846
  Epoch 70... Train Loss: 0.2514, Val Loss: 0.7694

[INFO 04-02 10:07:52] ax.service.ax_client: Completed trial 49 with data: {'avg_rmse_nonzero': 4.949965}.

  Epoch 80... Train Loss: 0.2395, Val Loss: 0.7574
  Epoch 90... Train Loss: 0.2227, Val Loss: 0.7593
Fold 5 - MSE: 6.2653, RMSE: 2.5031, MAE: 2.1041

Mean CV MSE: 26.4457, Mean CV RMSE: 4.9500, Mean CV MAE: 3.4400
Completed trial 49 with mean RMSE: 4.9500 ± 0.6971
Saved Ax client checkpoint

[INFO 04-02 10:07:54] ax.service.ax_client: Generated new trial 50 with parameters {'dropout_rate': 0.065194, 'weight_decay': 1e-06, 'lr': 0.002444, 'batch_size': 256, 'early_stopping_patience': 14, 'n_layers': 3, 'hidden1': 1024, 'hidden2': 1024, 'hidden3': 32, 'activation': 'leaky_relu'} using model BoTorch.

Starting trial 50 with parameters: {'dropout_rate': 0.06519359831077737, 'weight_decay': 1e-06, 'lr': 0.0024435730661934206, 'batch_size': 256, 'early_stopping_patience': 14, 'n_layers': 3, 'hidden1': 1024, 'hidden2': 1024, 'hidden3': 32, 'activation': 'leaky_relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 2.6736, Val Loss: 18.7243
  Epoch 10... Train Loss: 0.6956, Val Loss: 0.9528
  Epoch 20... Train Loss: 0.4310, Val Loss: 0.5065
  Epoch 30... Train Loss: 0.3430, Val Loss: 0.3773
  Epoch 40... Train Loss: 0.2591, Val Loss: 0.3082
  Epoch 50... Train Loss: 0.3201, Val Loss: 0.2900
Fold 1 - MSE: 43.3321, RMSE: 6.5827, MAE: 4.2440
Starting fold 2...
  Epoch 0... Train Loss: 7.9763, Val Loss: 22.5734
  Epoch 10... Train Loss: 0.6529, Val Loss: 0.8193
  Epoch 20... Train Loss: 0.3432, Val Loss: 0.6423
  Epoch 30... Train Loss: 0.2921, Val Loss: 0.4130
  Epoch 40... Train Loss: 0.1970, Val Loss: 0.3751
  Epoch 50... Train Loss: 0.2146, Val Loss: 0.3914
  Epoch 60... Train Loss: 0.2319, Val Loss: 0.3610
  Epoch 70... Train Loss: 0.2142, Val Loss: 0.3417
Fold 2 - MSE: 39.5463, RMSE: 6.2886, MAE: 3.7547
Starting fold 3...
  Epoch 0... Train Loss: 8.2052, Val Loss: 60.7178
  Epoch 10... Train Loss: 0.5409, Val Loss: 0.6994
  Epoch 20... Train Loss: 0.3478, Val Loss: 0.5874
  Epoch 30... Train Loss: 0.2655, Val Loss: 0.4652
  Epoch 40... Train Loss: 0.2101, Val Loss: 0.4177
  Epoch 50... Train Loss: 0.1939, Val Loss: 0.4126
  Epoch 60... Train Loss: 0.1705, Val Loss: 0.3989
  Epoch 70... Train Loss: 0.1769, Val Loss: 0.3947
Fold 3 - MSE: 22.8428, RMSE: 4.7794, MAE: 3.0957
Starting fold 4...
  Epoch 0... Train Loss: 7.4793, Val Loss: 8.2068
  Epoch 10... Train Loss: 0.6097, Val Loss: 0.6459
  Epoch 20... Train Loss: 0.3254, Val Loss: 0.5757
  Epoch 30... Train Loss: 0.2447, Val Loss: 0.5117
  Epoch 40... Train Loss: 0.1866, Val Loss: 0.4939
Fold 4 - MSE: 35.9111, RMSE: 5.9926, MAE: 4.7010
Starting fold 5...
  Epoch 0... Train Loss: 6.5589, Val Loss: 13.4089
  Epoch 10... Train Loss: 0.5704, Val Loss: 1.4168
  Epoch 20... Train Loss: 0.3247, Val Loss: 0.8688
  Epoch 30... Train Loss: 0.2361, Val Loss: 0.7777
  Epoch 40... Train Loss: 0.2212, Val Loss: 0.7831

[INFO 04-02 10:08:01] ax.service.ax_client: Completed trial 50 with data: {'avg_rmse_nonzero': 5.353217}.

  Epoch 50... Train Loss: 0.1802, Val Loss: 0.7374
Fold 5 - MSE: 9.7518, RMSE: 3.1228, MAE: 2.3677

Mean CV MSE: 30.2768, Mean CV RMSE: 5.3532, Mean CV MAE: 3.6326
Completed trial 50 with mean RMSE: 5.3532 ± 0.6364
Saved Ax client checkpoint

[INFO 04-02 10:08:03] ax.service.ax_client: Generated new trial 51 with parameters {'dropout_rate': 0.207538, 'weight_decay': 2e-06, 'lr': 0.003209, 'batch_size': 256, 'early_stopping_patience': 14, 'n_layers': 3, 'hidden1': 256, 'hidden2': 1024, 'hidden3': 32, 'activation': 'relu'} using model BoTorch.

Starting trial 51 with parameters: {'dropout_rate': 0.20753837583198242, 'weight_decay': 1.5452357314707855e-06, 'lr': 0.0032090978070208787, 'batch_size': 256, 'early_stopping_patience': 14, 'n_layers': 3, 'hidden1': 256, 'hidden2': 1024, 'hidden3': 32, 'activation': 'relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 2.8251, Val Loss: 94.0331
  Epoch 10... Train Loss: 0.8355, Val Loss: 0.7649
  Epoch 20... Train Loss: 0.4887, Val Loss: 0.4680
  Epoch 30... Train Loss: 0.3620, Val Loss: 0.4634
  Epoch 40... Train Loss: 0.3148, Val Loss: 0.3232
  Epoch 50... Train Loss: 0.4392, Val Loss: 0.3346
Fold 1 - MSE: 43.7502, RMSE: 6.6144, MAE: 4.3454
Starting fold 2...
  Epoch 0... Train Loss: 9.4877, Val Loss: 303.5943
  Epoch 10... Train Loss: 0.6341, Val Loss: 0.7887
  Epoch 20... Train Loss: 0.3998, Val Loss: 0.6658
  Epoch 30... Train Loss: 0.3496, Val Loss: 0.4808
  Epoch 40... Train Loss: 0.2336, Val Loss: 0.4283
  Epoch 50... Train Loss: 0.2764, Val Loss: 0.4332
  Epoch 60... Train Loss: 0.2699, Val Loss: 0.3923
  Epoch 70... Train Loss: 0.2405, Val Loss: 0.4081
Fold 2 - MSE: 37.5512, RMSE: 6.1279, MAE: 3.7652
Starting fold 3...
  Epoch 0... Train Loss: 7.3230, Val Loss: 437.1341
  Epoch 10... Train Loss: 0.5691, Val Loss: 0.6982
  Epoch 20... Train Loss: 0.3888, Val Loss: 0.5715
  Epoch 30... Train Loss: 0.3129, Val Loss: 0.4587
  Epoch 40... Train Loss: 0.2221, Val Loss: 0.3958
Fold 3 - MSE: 30.4103, RMSE: 5.5146, MAE: 3.2652
Starting fold 4...
  Epoch 0... Train Loss: 7.3612, Val Loss: 132.5340
  Epoch 10... Train Loss: 0.6207, Val Loss: 0.6350
  Epoch 20... Train Loss: 0.3494, Val Loss: 0.5808
  Epoch 30... Train Loss: 0.2789, Val Loss: 0.5568
  Epoch 40... Train Loss: 0.2425, Val Loss: 0.5251
  Epoch 50... Train Loss: 0.1909, Val Loss: 0.4771
  Epoch 60... Train Loss: 0.1868, Val Loss: 0.4981
Fold 4 - MSE: 33.9234, RMSE: 5.8244, MAE: 4.5713
Starting fold 5...
  Epoch 0... Train Loss: 8.0889, Val Loss: 327.3403
  Epoch 10... Train Loss: 0.6524, Val Loss: 1.4718
  Epoch 20... Train Loss: 0.4724, Val Loss: 1.0364
  Epoch 30... Train Loss: 0.3281, Val Loss: 0.9233
  Epoch 40... Train Loss: 0.2789, Val Loss: 0.8151
  Epoch 50... Train Loss: 0.2363, Val Loss: 0.7752

[INFO 04-02 10:08:09] ax.service.ax_client: Completed trial 51 with data: {'avg_rmse_nonzero': 5.189918}.

  Epoch 60... Train Loss: 0.2229, Val Loss: 0.7889
Fold 5 - MSE: 3.4908, RMSE: 1.8684, MAE: 1.4663

Mean CV MSE: 29.8252, Mean CV RMSE: 5.1899, Mean CV MAE: 3.4827
Completed trial 51 with mean RMSE: 5.1899 ± 0.8500
Saved Ax client checkpoint

[INFO 04-02 10:08:12] ax.service.ax_client: Generated new trial 52 with parameters {'dropout_rate': 0.5, 'weight_decay': 1e-06, 'lr': 0.002594, 'batch_size': 256, 'early_stopping_patience': 10, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 64, 'hidden3': 32, 'activation': 'leaky_relu'} using model BoTorch.

Starting trial 52 with parameters: {'dropout_rate': 0.5, 'weight_decay': 1e-06, 'lr': 0.0025941079608990166, 'batch_size': 256, 'early_stopping_patience': 10, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 64, 'hidden3': 32, 'activation': 'leaky_relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 1.3523, Val Loss: 2.4493
  Epoch 10... Train Loss: 0.7182, Val Loss: 1.1361
  Epoch 20... Train Loss: 0.5421, Val Loss: 0.4279
  Epoch 30... Train Loss: 0.5275, Val Loss: 0.5600
Fold 1 - MSE: 39.9442, RMSE: 6.3201, MAE: 4.2758
Starting fold 2...
  Epoch 0... Train Loss: 3.1102, Val Loss: 4.4202
  Epoch 10... Train Loss: 0.5862, Val Loss: 0.7800
  Epoch 20... Train Loss: 0.3883, Val Loss: 0.6378
  Epoch 30... Train Loss: 0.3868, Val Loss: 0.5038
  Epoch 40... Train Loss: 0.3084, Val Loss: 0.4787
  Epoch 50... Train Loss: 0.3491, Val Loss: 0.4824
Fold 2 - MSE: 37.2141, RMSE: 6.1003, MAE: 3.7199
Starting fold 3...
  Epoch 0... Train Loss: 3.1367, Val Loss: 16.3350
  Epoch 10... Train Loss: 0.4964, Val Loss: 0.7086
  Epoch 20... Train Loss: 0.3643, Val Loss: 0.4822
  Epoch 30... Train Loss: 0.3141, Val Loss: 0.4691
  Epoch 40... Train Loss: 0.3218, Val Loss: 0.4201
  Epoch 50... Train Loss: 0.2582, Val Loss: 0.4095
Fold 3 - MSE: 43.5013, RMSE: 6.5956, MAE: 3.7440
Starting fold 4...
  Epoch 0... Train Loss: 3.4518, Val Loss: 14.4532
  Epoch 10... Train Loss: 0.5860, Val Loss: 0.6349
  Epoch 20... Train Loss: 0.3163, Val Loss: 0.5272
  Epoch 30... Train Loss: 0.2819, Val Loss: 0.4998
Fold 4 - MSE: 30.8905, RMSE: 5.5579, MAE: 4.2965
Starting fold 5...
  Epoch 0... Train Loss: 2.1201, Val Loss: 7.6609
  Epoch 10... Train Loss: 0.5748, Val Loss: 1.0352
  Epoch 20... Train Loss: 0.3806, Val Loss: 0.9120
  Epoch 30... Train Loss: 0.3404, Val Loss: 0.8238
  Epoch 40... Train Loss: 0.3022, Val Loss: 0.8146
  Epoch 50... Train Loss: 0.2728, Val Loss: 0.8160

[INFO 04-02 10:08:18] ax.service.ax_client: Completed trial 52 with data: {'avg_rmse_nonzero': 5.43702}.

Fold 5 - MSE: 6.8181, RMSE: 2.6111, MAE: 1.9507

Mean CV MSE: 31.6736, Mean CV RMSE: 5.4370, Mean CV MAE: 3.5974
Completed trial 52 with mean RMSE: 5.4370 ± 0.7267
Saved Ax client checkpoint

[INFO 04-02 10:08:20] ax.service.ax_client: Generated new trial 53 with parameters {'dropout_rate': 0.5, 'weight_decay': 1e-06, 'lr': 0.001957, 'batch_size': 256, 'early_stopping_patience': 47, 'n_layers': 3, 'hidden1': 128, 'hidden2': 1024, 'hidden3': 32, 'activation': 'leaky_relu'} using model BoTorch.

Starting trial 53 with parameters: {'dropout_rate': 0.5, 'weight_decay': 1e-06, 'lr': 0.0019565982926947403, 'batch_size': 256, 'early_stopping_patience': 47, 'n_layers': 3, 'hidden1': 128, 'hidden2': 1024, 'hidden3': 32, 'activation': 'leaky_relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 1.6995, Val Loss: 2.1914
  Epoch 10... Train Loss: 0.7815, Val Loss: 0.7080
  Epoch 20... Train Loss: 0.5017, Val Loss: 0.4190
  Epoch 30... Train Loss: 0.4686, Val Loss: 0.4751
  Epoch 40... Train Loss: 0.3591, Val Loss: 0.3503
  Epoch 50... Train Loss: 0.3895, Val Loss: 0.3402
  Epoch 60... Train Loss: 0.3763, Val Loss: 0.3251
  Epoch 70... Train Loss: 0.3077, Val Loss: 0.3157
  Epoch 80... Train Loss: 0.4327, Val Loss: 0.2847
  Epoch 90... Train Loss: 0.2991, Val Loss: 0.2951
  Epoch 100... Train Loss: 0.3430, Val Loss: 0.3044
  Epoch 110... Train Loss: 0.3324, Val Loss: 0.3007
  Epoch 120... Train Loss: 0.4090, Val Loss: 0.3003
Fold 1 - MSE: 42.0310, RMSE: 6.4831, MAE: 4.2347
Starting fold 2...
  Epoch 0... Train Loss: 1.5569, Val Loss: 1.3572
  Epoch 10... Train Loss: 0.5844, Val Loss: 0.7134
  Epoch 20... Train Loss: 0.3546, Val Loss: 0.5364
  Epoch 30... Train Loss: 0.3506, Val Loss: 0.5007
  Epoch 40... Train Loss: 0.2611, Val Loss: 0.4338
  Epoch 50... Train Loss: 0.3222, Val Loss: 0.3817
  Epoch 60... Train Loss: 0.2878, Val Loss: 0.4237
  Epoch 70... Train Loss: 0.3114, Val Loss: 0.3674
  Epoch 80... Train Loss: 0.2466, Val Loss: 0.4342
  Epoch 90... Train Loss: 0.2882, Val Loss: 0.3626
  Epoch 100... Train Loss: 0.2388, Val Loss: 0.3676
  Epoch 110... Train Loss: 0.2000, Val Loss: 0.3728
Fold 2 - MSE: 36.2888, RMSE: 6.0240, MAE: 3.5691
Starting fold 3...
  Epoch 0... Train Loss: 2.0456, Val Loss: 4.5796
  Epoch 10... Train Loss: 0.5292, Val Loss: 0.7464
  Epoch 20... Train Loss: 0.3922, Val Loss: 0.4788
  Epoch 30... Train Loss: 0.3240, Val Loss: 0.4319
  Epoch 40... Train Loss: 0.2744, Val Loss: 0.4090
  Epoch 50... Train Loss: 0.2690, Val Loss: 0.4339
  Epoch 60... Train Loss: 0.2417, Val Loss: 0.4280
  Epoch 70... Train Loss: 0.2449, Val Loss: 0.3904
  Epoch 80... Train Loss: 0.2180, Val Loss: 0.3733
  Epoch 90... Train Loss: 0.2168, Val Loss: 0.3865
  Epoch 100... Train Loss: 0.2159, Val Loss: 0.4044
  Epoch 110... Train Loss: 0.2121, Val Loss: 0.3793
  Epoch 120... Train Loss: 0.2353, Val Loss: 0.3689
  Epoch 130... Train Loss: 0.2136, Val Loss: 0.3715
  Epoch 140... Train Loss: 0.2160, Val Loss: 0.3817
  Epoch 150... Train Loss: 0.2296, Val Loss: 0.3734
  Epoch 160... Train Loss: 0.2187, Val Loss: 0.3691
  Epoch 170... Train Loss: 0.2146, Val Loss: 0.3654
  Epoch 180... Train Loss: 0.2020, Val Loss: 0.3689
  Epoch 190... Train Loss: 0.2057, Val Loss: 0.3711
  Epoch 200... Train Loss: 0.2370, Val Loss: 0.3733
  Epoch 210... Train Loss: 0.1970, Val Loss: 0.3743
  Epoch 220... Train Loss: 0.2107, Val Loss: 0.3721
Fold 3 - MSE: 35.0324, RMSE: 5.9188, MAE: 3.4795
Starting fold 4...
  Epoch 0... Train Loss: 1.7171, Val Loss: 1.0265
  Epoch 10... Train Loss: 0.5183, Val Loss: 0.6482
  Epoch 20... Train Loss: 0.3491, Val Loss: 0.5225
  Epoch 30... Train Loss: 0.2507, Val Loss: 0.5087
  Epoch 40... Train Loss: 0.2273, Val Loss: 0.4793
  Epoch 50... Train Loss: 0.1899, Val Loss: 0.4440
  Epoch 60... Train Loss: 0.1924, Val Loss: 0.4720
  Epoch 70... Train Loss: 0.2041, Val Loss: 0.4392
  Epoch 80... Train Loss: 0.1750, Val Loss: 0.4787
  Epoch 90... Train Loss: 0.1985, Val Loss: 0.4695
Fold 4 - MSE: 28.9541, RMSE: 5.3809, MAE: 4.2444
Starting fold 5...
  Epoch 0... Train Loss: 1.9941, Val Loss: 4.1748
  Epoch 10... Train Loss: 0.5248, Val Loss: 1.1324
  Epoch 20... Train Loss: 0.4172, Val Loss: 0.8371
  Epoch 30... Train Loss: 0.3318, Val Loss: 0.8059
  Epoch 40... Train Loss: 0.3224, Val Loss: 0.8258
  Epoch 50... Train Loss: 0.2869, Val Loss: 0.8138
  Epoch 60... Train Loss: 0.2428, Val Loss: 0.7648
  Epoch 70... Train Loss: 0.2560, Val Loss: 0.7567
  Epoch 80... Train Loss: 0.2382, Val Loss: 0.7462
  Epoch 90... Train Loss: 0.2404, Val Loss: 0.7457
  Epoch 100... Train Loss: 0.2423, Val Loss: 0.7294
  Epoch 110... Train Loss: 0.2201, Val Loss: 0.7286
  Epoch 120... Train Loss: 0.2163, Val Loss: 0.7447
  Epoch 130... Train Loss: 0.2269, Val Loss: 0.7358
  Epoch 140... Train Loss: 0.2206, Val Loss: 0.7324
  Epoch 150... Train Loss: 0.2198, Val Loss: 0.7388

[INFO 04-02 10:08:32] ax.service.ax_client: Completed trial 53 with data: {'avg_rmse_nonzero': 5.193738}.

Fold 5 - MSE: 4.6735, RMSE: 2.1618, MAE: 1.7419

Mean CV MSE: 29.3960, Mean CV RMSE: 5.1937, Mean CV MAE: 3.4539
Completed trial 53 with mean RMSE: 5.1937 ± 0.7780
Saved Ax client checkpoint

[INFO 04-02 10:08:35] ax.service.ax_client: Generated new trial 54 with parameters {'dropout_rate': 0.5, 'weight_decay': 1e-06, 'lr': 0.002512, 'batch_size': 256, 'early_stopping_patience': 11, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 32, 'activation': 'leaky_relu'} using model BoTorch.

Starting trial 54 with parameters: {'dropout_rate': 0.5, 'weight_decay': 1e-06, 'lr': 0.0025118186233797474, 'batch_size': 256, 'early_stopping_patience': 11, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 32, 'activation': 'leaky_relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 1.5251, Val Loss: 12.2923
  Epoch 10... Train Loss: 0.9492, Val Loss: 0.7247
  Epoch 20... Train Loss: 0.4865, Val Loss: 0.5067
  Epoch 30... Train Loss: 0.4337, Val Loss: 0.4576
Fold 1 - MSE: 40.1585, RMSE: 6.3371, MAE: 4.2760
Starting fold 2...
  Epoch 0... Train Loss: 3.6297, Val Loss: 32.0431
  Epoch 10... Train Loss: 0.5880, Val Loss: 0.7621
  Epoch 20... Train Loss: 0.4058, Val Loss: 0.6133
  Epoch 30... Train Loss: 0.3752, Val Loss: 0.4779
  Epoch 40... Train Loss: 0.3014, Val Loss: 0.4668
  Epoch 50... Train Loss: 0.2882, Val Loss: 0.4610
  Epoch 60... Train Loss: 0.2854, Val Loss: 0.4351
Fold 2 - MSE: 37.8333, RMSE: 6.1509, MAE: 3.5625
Starting fold 3...
  Epoch 0... Train Loss: 3.4985, Val Loss: 30.0132
  Epoch 10... Train Loss: 0.5645, Val Loss: 0.6791
  Epoch 20... Train Loss: 0.4028, Val Loss: 0.4795
  Epoch 30... Train Loss: 0.3680, Val Loss: 0.4429
  Epoch 40... Train Loss: 0.3097, Val Loss: 0.4184
  Epoch 50... Train Loss: 0.2892, Val Loss: 0.4032
  Epoch 60... Train Loss: 0.2436, Val Loss: 0.4041
Fold 3 - MSE: 47.7363, RMSE: 6.9091, MAE: 3.8218
Starting fold 4...
  Epoch 0... Train Loss: 2.9924, Val Loss: 11.4563
  Epoch 10... Train Loss: 0.6519, Val Loss: 0.6416
  Epoch 20... Train Loss: 0.3663, Val Loss: 0.5487
  Epoch 30... Train Loss: 0.3461, Val Loss: 0.4752
  Epoch 40... Train Loss: 0.2963, Val Loss: 0.4853
Fold 4 - MSE: 32.6973, RMSE: 5.7182, MAE: 4.3122
Starting fold 5...
  Epoch 0... Train Loss: 2.1339, Val Loss: 10.0328
  Epoch 10... Train Loss: 0.5387, Val Loss: 1.1494
  Epoch 20... Train Loss: 0.3876, Val Loss: 0.8944
  Epoch 30... Train Loss: 0.3426, Val Loss: 0.8375
  Epoch 40... Train Loss: 0.3219, Val Loss: 0.8249
  Epoch 50... Train Loss: 0.3108, Val Loss: 0.8219

[INFO 04-02 10:08:40] ax.service.ax_client: Completed trial 54 with data: {'avg_rmse_nonzero': 5.448676}.

Fold 5 - MSE: 4.5289, RMSE: 2.1281, MAE: 1.6046

Mean CV MSE: 32.5909, Mean CV RMSE: 5.4487, Mean CV MAE: 3.5154
Completed trial 54 with mean RMSE: 5.4487 ± 0.8519
Saved Ax client checkpoint

[INFO 04-02 10:08:43] ax.service.ax_client: Generated new trial 55 with parameters {'dropout_rate': 0.5, 'weight_decay': 0.002587, 'lr': 0.01, 'batch_size': 128, 'early_stopping_patience': 34, 'n_layers': 3, 'hidden1': 1024, 'hidden2': 64, 'hidden3': 512, 'activation': 'relu'} using model BoTorch.

Starting trial 55 with parameters: {'dropout_rate': 0.5, 'weight_decay': 0.0025870952539376185, 'lr': 0.01, 'batch_size': 128, 'early_stopping_patience': 34, 'n_layers': 3, 'hidden1': 1024, 'hidden2': 64, 'hidden3': 512, 'activation': 'relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 8.9173, Val Loss: 2657.2510
  Epoch 10... Train Loss: 0.7208, Val Loss: 0.5813
  Epoch 20... Train Loss: 0.4711, Val Loss: 0.5655
  Epoch 30... Train Loss: 0.5183, Val Loss: 0.4506
  Epoch 40... Train Loss: 0.4637, Val Loss: 0.4293
  Epoch 50... Train Loss: 0.5184, Val Loss: 0.3738
  Epoch 60... Train Loss: 0.4003, Val Loss: 0.3307
  Epoch 70... Train Loss: 0.3431, Val Loss: 0.3695
  Epoch 80... Train Loss: 0.3842, Val Loss: 0.3884
  Epoch 90... Train Loss: 0.4403, Val Loss: 0.2983
  Epoch 100... Train Loss: 0.3966, Val Loss: 0.3002
  Epoch 110... Train Loss: 0.3189, Val Loss: 0.3005
  Epoch 120... Train Loss: 0.3802, Val Loss: 0.3084
  Epoch 130... Train Loss: 0.3055, Val Loss: 0.3004
  Epoch 140... Train Loss: 0.3051, Val Loss: 0.2738
  Epoch 150... Train Loss: 0.3156, Val Loss: 0.2672
  Epoch 160... Train Loss: 0.2579, Val Loss: 0.2812
  Epoch 170... Train Loss: 0.3137, Val Loss: 0.2811
Fold 1 - MSE: 41.1440, RMSE: 6.4144, MAE: 4.2479
Starting fold 2...
  Epoch 0... Train Loss: 3.8672, Val Loss: 490.4275
  Epoch 10... Train Loss: 0.5262, Val Loss: 1.1971
  Epoch 20... Train Loss: 0.3869, Val Loss: 0.9036
  Epoch 30... Train Loss: 0.5265, Val Loss: 0.4883
  Epoch 40... Train Loss: 0.4378, Val Loss: 0.5078
  Epoch 50... Train Loss: 0.4113, Val Loss: 0.9053
  Epoch 60... Train Loss: 0.3448, Val Loss: 0.3989
  Epoch 70... Train Loss: 0.2843, Val Loss: 0.2904
  Epoch 80... Train Loss: 0.3242, Val Loss: 0.3599
  Epoch 90... Train Loss: 0.2861, Val Loss: 0.3291
  Epoch 100... Train Loss: 0.2382, Val Loss: 0.3062
  Epoch 110... Train Loss: 0.2661, Val Loss: 0.3317
Fold 2 - MSE: 42.4054, RMSE: 6.5119, MAE: 3.8614
Starting fold 3...
  Epoch 0... Train Loss: 5.7160, Val Loss: 232.2941
  Epoch 10... Train Loss: 0.5460, Val Loss: 0.6787
  Epoch 20... Train Loss: 0.4245, Val Loss: 0.5574
  Epoch 30... Train Loss: 0.3779, Val Loss: 0.4641
  Epoch 40... Train Loss: 0.3551, Val Loss: 0.4017
  Epoch 50... Train Loss: 0.3213, Val Loss: 0.4524
  Epoch 60... Train Loss: 0.2789, Val Loss: 0.3689
  Epoch 70... Train Loss: 0.2881, Val Loss: 0.3928
  Epoch 80... Train Loss: 0.2687, Val Loss: 0.3419
  Epoch 90... Train Loss: 0.2529, Val Loss: 0.3681
  Epoch 100... Train Loss: 0.2519, Val Loss: 0.3988
  Epoch 110... Train Loss: 0.2413, Val Loss: 0.3693
Fold 3 - MSE: 53.0764, RMSE: 7.2854, MAE: 3.8748
Starting fold 4...
  Epoch 0... Train Loss: 5.5954, Val Loss: 287.3925
  Epoch 10... Train Loss: 0.5369, Val Loss: 0.5538
  Epoch 20... Train Loss: 0.3425, Val Loss: 0.5115
  Epoch 30... Train Loss: 0.3222, Val Loss: 0.4578
  Epoch 40... Train Loss: 0.2505, Val Loss: 0.4729
  Epoch 50... Train Loss: 0.2592, Val Loss: 0.3214
  Epoch 60... Train Loss: 0.2261, Val Loss: 0.3591
  Epoch 70... Train Loss: 0.2230, Val Loss: 0.5332
Fold 4 - MSE: 31.4226, RMSE: 5.6056, MAE: 4.4482
Starting fold 5...
  Epoch 0... Train Loss: 4.7819, Val Loss: 610.3001
  Epoch 10... Train Loss: 0.6397, Val Loss: 0.9028
  Epoch 20... Train Loss: 0.5895, Val Loss: 0.7650
  Epoch 30... Train Loss: 0.4809, Val Loss: 1.0569
  Epoch 40... Train Loss: 0.4701, Val Loss: 0.9685
  Epoch 50... Train Loss: 0.4486, Val Loss: 0.9194
  Epoch 60... Train Loss: 0.3943, Val Loss: 0.8395
  Epoch 70... Train Loss: 0.3941, Val Loss: 0.6805
  Epoch 80... Train Loss: 0.4393, Val Loss: 0.6740
  Epoch 90... Train Loss: 0.4613, Val Loss: 0.8288
  Epoch 100... Train Loss: 0.3591, Val Loss: 1.0264
  Epoch 110... Train Loss: 0.3105, Val Loss: 1.0975
  Epoch 120... Train Loss: 0.3071, Val Loss: 0.6336
  Epoch 130... Train Loss: 0.2780, Val Loss: 0.5833
  Epoch 140... Train Loss: 0.3267, Val Loss: 0.5649

[INFO 04-02 10:08:57] ax.service.ax_client: Completed trial 55 with data: {'avg_rmse_nonzero': 5.582723}.

  Epoch 150... Train Loss: 0.2997, Val Loss: 0.8975
Fold 5 - MSE: 4.3948, RMSE: 2.0964, MAE: 1.6871

Mean CV MSE: 34.4886, Mean CV RMSE: 5.5827, Mean CV MAE: 3.6239
Completed trial 55 with mean RMSE: 5.5827 ± 0.9113
Saved Ax client checkpoint

[INFO 04-02 10:09:00] ax.service.ax_client: Generated new trial 56 with parameters {'dropout_rate': 0.087153, 'weight_decay': 1e-06, 'lr': 0.001329, 'batch_size': 256, 'early_stopping_patience': 14, 'n_layers': 3, 'hidden1': 128, 'hidden2': 1024, 'hidden3': 32, 'activation': 'leaky_relu'} using model BoTorch.

Starting trial 56 with parameters: {'dropout_rate': 0.08715301419162932, 'weight_decay': 1e-06, 'lr': 0.00132930167408132, 'batch_size': 256, 'early_stopping_patience': 14, 'n_layers': 3, 'hidden1': 128, 'hidden2': 1024, 'hidden3': 32, 'activation': 'leaky_relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 2.4474, Val Loss: 3.2171
  Epoch 10... Train Loss: 0.5470, Val Loss: 1.1299
  Epoch 20... Train Loss: 0.3811, Val Loss: 0.3319
  Epoch 30... Train Loss: 0.3292, Val Loss: 0.4271
  Epoch 40... Train Loss: 0.2855, Val Loss: 0.3222
  Epoch 50... Train Loss: 0.3094, Val Loss: 0.3008
Fold 1 - MSE: 44.5932, RMSE: 6.6778, MAE: 4.3652
Starting fold 2...
  Epoch 0... Train Loss: 4.4345, Val Loss: 2.9136
  Epoch 10... Train Loss: 0.4440, Val Loss: 0.7078
  Epoch 20... Train Loss: 0.2588, Val Loss: 0.4726
  Epoch 30... Train Loss: 0.2617, Val Loss: 0.3591
  Epoch 40... Train Loss: 0.1884, Val Loss: 0.4055
  Epoch 50... Train Loss: 0.2018, Val Loss: 0.3746
Fold 2 - MSE: 35.2882, RMSE: 5.9404, MAE: 3.3989
Starting fold 3...
  Epoch 0... Train Loss: 4.6820, Val Loss: 2.2127
  Epoch 10... Train Loss: 0.4339, Val Loss: 0.6747
  Epoch 20... Train Loss: 0.2528, Val Loss: 0.4604
  Epoch 30... Train Loss: 0.2328, Val Loss: 0.4569
  Epoch 40... Train Loss: 0.1849, Val Loss: 0.4228
  Epoch 50... Train Loss: 0.1682, Val Loss: 0.4155
Fold 3 - MSE: 25.1059, RMSE: 5.0106, MAE: 3.1640
Starting fold 4...
  Epoch 0... Train Loss: 4.9990, Val Loss: 1.4348
  Epoch 10... Train Loss: 0.4308, Val Loss: 0.5978
  Epoch 20... Train Loss: 0.2074, Val Loss: 0.5120
  Epoch 30... Train Loss: 0.1804, Val Loss: 0.4785
  Epoch 40... Train Loss: 0.1657, Val Loss: 0.4856
Fold 4 - MSE: 29.5463, RMSE: 5.4356, MAE: 4.2469
Starting fold 5...
  Epoch 0... Train Loss: 4.1452, Val Loss: 1.8776
  Epoch 10... Train Loss: 0.4318, Val Loss: 1.0683
  Epoch 20... Train Loss: 0.2580, Val Loss: 0.7502
  Epoch 30... Train Loss: 0.2315, Val Loss: 0.7706
  Epoch 40... Train Loss: 0.2085, Val Loss: 0.7394

[INFO 04-02 10:09:05] ax.service.ax_client: Completed trial 56 with data: {'avg_rmse_nonzero': 5.708358}.

  Epoch 50... Train Loss: 0.1955, Val Loss: 0.7366
Fold 5 - MSE: 30.0015, RMSE: 5.4774, MAE: 4.6484

Mean CV MSE: 32.9070, Mean CV RMSE: 5.7084, Mean CV MAE: 3.9647
Completed trial 56 with mean RMSE: 5.7084 ± 0.2836
Saved Ax client checkpoint

[INFO 04-02 10:09:08] ax.service.ax_client: Generated new trial 57 with parameters {'dropout_rate': 0.5, 'weight_decay': 1e-06, 'lr': 0.01, 'batch_size': 256, 'early_stopping_patience': 10, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 512, 'activation': 'leaky_relu'} using model BoTorch.

Starting trial 57 with parameters: {'dropout_rate': 0.5, 'weight_decay': 1e-06, 'lr': 0.01, 'batch_size': 256, 'early_stopping_patience': 10, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 512, 'activation': 'leaky_relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 3.1662, Val Loss: 3930.2468
  Epoch 10... Train Loss: 1.0592, Val Loss: 1.6488
  Epoch 20... Train Loss: 0.6632, Val Loss: 0.6366
  Epoch 30... Train Loss: 0.5344, Val Loss: 0.5577
  Epoch 40... Train Loss: 0.5041, Val Loss: 0.4750
  Epoch 50... Train Loss: 0.6387, Val Loss: 0.4644
Fold 1 - MSE: 41.6626, RMSE: 6.4547, MAE: 4.5345
Starting fold 2...
  Epoch 0... Train Loss: 6.4767, Val Loss: 2846.0513
  Epoch 10... Train Loss: 0.7972, Val Loss: 0.9008
  Epoch 20... Train Loss: 0.5331, Val Loss: 0.6836
  Epoch 30... Train Loss: 0.4734, Val Loss: 0.6160
  Epoch 40... Train Loss: 0.4579, Val Loss: 0.5884
  Epoch 50... Train Loss: 0.4020, Val Loss: 0.5408
  Epoch 60... Train Loss: 0.3542, Val Loss: 0.5055
  Epoch 70... Train Loss: 0.3285, Val Loss: 0.4813
Fold 2 - MSE: 34.4728, RMSE: 5.8714, MAE: 3.7857
Starting fold 3...
  Epoch 0... Train Loss: 9.8758, Val Loss: 3049.9075
  Epoch 10... Train Loss: 0.7906, Val Loss: 0.8228
  Epoch 20... Train Loss: 0.4860, Val Loss: 0.6438
  Epoch 30... Train Loss: 0.4598, Val Loss: 0.5364
  Epoch 40... Train Loss: 0.3426, Val Loss: 0.5295
  Epoch 50... Train Loss: 0.3354, Val Loss: 0.4893
Fold 3 - MSE: 32.2309, RMSE: 5.6772, MAE: 3.4066
Starting fold 4...
  Epoch 0... Train Loss: 12.5344, Val Loss: 93.9585
  Epoch 10... Train Loss: 0.8468, Val Loss: 0.5842
  Epoch 20... Train Loss: 0.5144, Val Loss: 0.7171
Fold 4 - MSE: 31.2722, RMSE: 5.5922, MAE: 4.2502
Starting fold 5...
  Epoch 0... Train Loss: 6.5150, Val Loss: 1304.1451
  Epoch 10... Train Loss: 0.7187, Val Loss: 1.3845
  Epoch 20... Train Loss: 0.4912, Val Loss: 0.9739
  Epoch 30... Train Loss: 0.4142, Val Loss: 0.8551
  Epoch 40... Train Loss: 0.3153, Val Loss: 0.8465

[INFO 04-02 10:09:14] ax.service.ax_client: Completed trial 57 with data: {'avg_rmse_nonzero': 5.205639}.

  Epoch 50... Train Loss: 0.3192, Val Loss: 0.7710
  Epoch 60... Train Loss: 0.2771, Val Loss: 0.7820
Fold 5 - MSE: 5.9185, RMSE: 2.4328, MAE: 1.7606

Mean CV MSE: 29.1114, Mean CV RMSE: 5.2056, Mean CV MAE: 3.5475
Completed trial 57 with mean RMSE: 5.2056 ± 0.7094
Saved Ax client checkpoint

[INFO 04-02 10:09:17] ax.service.ax_client: Generated new trial 58 with parameters {'dropout_rate': 0.5, 'weight_decay': 1e-06, 'lr': 0.006319, 'batch_size': 256, 'early_stopping_patience': 35, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 32, 'activation': 'relu'} using model BoTorch.

Starting trial 58 with parameters: {'dropout_rate': 0.5, 'weight_decay': 1e-06, 'lr': 0.006319167474710881, 'batch_size': 256, 'early_stopping_patience': 35, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 32, 'activation': 'relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 1.7668, Val Loss: 99.9481
  Epoch 10... Train Loss: 0.9666, Val Loss: 1.0941
  Epoch 20... Train Loss: 0.6260, Val Loss: 0.5173
  Epoch 30... Train Loss: 0.5368, Val Loss: 0.5033
  Epoch 40... Train Loss: 0.4871, Val Loss: 0.4240
  Epoch 50... Train Loss: 0.6331, Val Loss: 0.3615
  Epoch 60... Train Loss: 0.5301, Val Loss: 0.3733
  Epoch 70... Train Loss: 0.4140, Val Loss: 0.3664
  Epoch 80... Train Loss: 0.3626, Val Loss: 0.2976
  Epoch 90... Train Loss: 0.3883, Val Loss: 0.3137
  Epoch 100... Train Loss: 0.4339, Val Loss: 0.2964
  Epoch 110... Train Loss: 0.3717, Val Loss: 0.2893
  Epoch 120... Train Loss: 0.4754, Val Loss: 0.2928
  Epoch 130... Train Loss: 0.3643, Val Loss: 0.2801
  Epoch 140... Train Loss: 0.3554, Val Loss: 0.2837
  Epoch 150... Train Loss: 0.4866, Val Loss: 0.2820
  Epoch 160... Train Loss: 0.3094, Val Loss: 0.2847
  Epoch 170... Train Loss: 0.3782, Val Loss: 0.2824
Fold 1 - MSE: 36.8593, RMSE: 6.0712, MAE: 4.0411
Starting fold 2...
  Epoch 0... Train Loss: 7.9191, Val Loss: 2952.2974
  Epoch 10... Train Loss: 0.7086, Val Loss: 0.8038
  Epoch 20... Train Loss: 0.4277, Val Loss: 0.6724
  Epoch 30... Train Loss: 0.4109, Val Loss: 0.5607
  Epoch 40... Train Loss: 0.3630, Val Loss: 0.4360
  Epoch 50... Train Loss: 0.3498, Val Loss: 0.4717
  Epoch 60... Train Loss: 0.3177, Val Loss: 0.4293
  Epoch 70... Train Loss: 0.2917, Val Loss: 0.4044
  Epoch 80... Train Loss: 0.2763, Val Loss: 0.4017
  Epoch 90... Train Loss: 0.2728, Val Loss: 0.4066
  Epoch 100... Train Loss: 0.2871, Val Loss: 0.3911
  Epoch 110... Train Loss: 0.2323, Val Loss: 0.3931
  Epoch 120... Train Loss: 0.2253, Val Loss: 0.4010
  Epoch 130... Train Loss: 0.2463, Val Loss: 0.3877
Fold 2 - MSE: 35.7688, RMSE: 5.9807, MAE: 3.6053
Starting fold 3...
  Epoch 0... Train Loss: 8.7469, Val Loss: 261.0014
  Epoch 10... Train Loss: 0.6568, Val Loss: 0.6736
  Epoch 20... Train Loss: 0.4320, Val Loss: 0.5397
  Epoch 30... Train Loss: 0.3808, Val Loss: 0.4625
  Epoch 40... Train Loss: 0.2974, Val Loss: 0.4321
  Epoch 50... Train Loss: 0.2702, Val Loss: 0.4501
  Epoch 60... Train Loss: 0.2562, Val Loss: 0.4250
  Epoch 70... Train Loss: 0.2425, Val Loss: 0.3940
  Epoch 80... Train Loss: 0.2260, Val Loss: 0.3936
  Epoch 90... Train Loss: 0.2196, Val Loss: 0.3858
  Epoch 100... Train Loss: 0.2295, Val Loss: 0.3670
  Epoch 110... Train Loss: 0.2054, Val Loss: 0.3745
  Epoch 120... Train Loss: 0.2346, Val Loss: 0.3649
  Epoch 130... Train Loss: 0.2216, Val Loss: 0.3638
  Epoch 140... Train Loss: 0.2060, Val Loss: 0.3642
  Epoch 150... Train Loss: 0.2224, Val Loss: 0.3589
Fold 3 - MSE: 34.1998, RMSE: 5.8481, MAE: 3.5433
Starting fold 4...
  Epoch 0... Train Loss: 7.3003, Val Loss: 1997.2738
  Epoch 10... Train Loss: 0.7057, Val Loss: 0.6777
  Epoch 20... Train Loss: 0.4162, Val Loss: 0.5365
  Epoch 30... Train Loss: 0.3712, Val Loss: 0.5708
  Epoch 40... Train Loss: 0.3254, Val Loss: 0.4876
  Epoch 50... Train Loss: 0.2426, Val Loss: 0.5202
  Epoch 60... Train Loss: 0.2413, Val Loss: 0.4568
  Epoch 70... Train Loss: 0.2270, Val Loss: 0.4580
  Epoch 80... Train Loss: 0.2083, Val Loss: 0.4520
  Epoch 90... Train Loss: 0.2089, Val Loss: 0.4549
  Epoch 100... Train Loss: 0.2103, Val Loss: 0.4359
  Epoch 110... Train Loss: 0.1856, Val Loss: 0.4445
Fold 4 - MSE: 30.4929, RMSE: 5.5220, MAE: 4.2658
Starting fold 5...
  Epoch 0... Train Loss: 6.4913, Val Loss: 387.4431
  Epoch 10... Train Loss: 0.6346, Val Loss: 1.1227
  Epoch 20... Train Loss: 0.4385, Val Loss: 0.8838
  Epoch 30... Train Loss: 0.3259, Val Loss: 0.8339
  Epoch 40... Train Loss: 0.3484, Val Loss: 0.8602
  Epoch 50... Train Loss: 0.2706, Val Loss: 0.7516
  Epoch 60... Train Loss: 0.2812, Val Loss: 0.7619
  Epoch 70... Train Loss: 0.2812, Val Loss: 0.7474
  Epoch 80... Train Loss: 0.2833, Val Loss: 0.7331
  Epoch 90... Train Loss: 0.2532, Val Loss: 0.7287
  Epoch 100... Train Loss: 0.2446, Val Loss: 0.7424
  Epoch 110... Train Loss: 0.2652, Val Loss: 0.7430
  Epoch 120... Train Loss: 0.2421, Val Loss: 0.7343
Fold 5 - MSE: 9.6730, RMSE: 3.1101, MAE: 2.7158

Mean CV MSE: 29.3988, Mean CV RMSE: 5.3064, Mean CV MAE: 3.6343

[INFO 04-02 10:09:30] ax.service.ax_client: Completed trial 58 with data: {'avg_rmse_nonzero': 5.306426}.

Completed trial 58 with mean RMSE: 5.3064 ± 0.5569
Saved Ax client checkpoint

[INFO 04-02 10:09:34] ax.service.ax_client: Generated new trial 59 with parameters {'dropout_rate': 0.5, 'weight_decay': 1e-06, 'lr': 0.01, 'batch_size': 256, 'early_stopping_patience': 10, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 512, 'activation': 'relu'} using model BoTorch.

Starting trial 59 with parameters: {'dropout_rate': 0.5, 'weight_decay': 1e-06, 'lr': 0.01, 'batch_size': 256, 'early_stopping_patience': 10, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 512, 'activation': 'relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 2.1952, Val Loss: 911.1988
  Epoch 10... Train Loss: 1.0515, Val Loss: 1.1399
  Epoch 20... Train Loss: 0.7986, Val Loss: 0.6658
  Epoch 30... Train Loss: 0.5749, Val Loss: 0.5332
Fold 1 - MSE: 41.3644, RMSE: 6.4315, MAE: 4.3294
Starting fold 2...
  Epoch 0... Train Loss: 2.8566, Val Loss: 390.0625
  Epoch 10... Train Loss: 0.7210, Val Loss: 0.7055
  Epoch 20... Train Loss: 0.4686, Val Loss: 0.6737
  Epoch 30... Train Loss: 0.4146, Val Loss: 0.5889
  Epoch 40... Train Loss: 0.4033, Val Loss: 0.5609
  Epoch 50... Train Loss: 0.4331, Val Loss: 0.5111
  Epoch 60... Train Loss: 0.4011, Val Loss: 0.5033
Fold 2 - MSE: 36.7096, RMSE: 6.0588, MAE: 3.5682
Starting fold 3...
  Epoch 0... Train Loss: 4.6515, Val Loss: 21.8630
  Epoch 10... Train Loss: 0.7800, Val Loss: 0.7762
  Epoch 20... Train Loss: 0.4158, Val Loss: 0.5482
  Epoch 30... Train Loss: 0.3722, Val Loss: 0.4794
  Epoch 40... Train Loss: 0.2791, Val Loss: 0.4128
Fold 3 - MSE: 32.0386, RMSE: 5.6603, MAE: 3.4227
Starting fold 4...
  Epoch 0... Train Loss: 9.2329, Val Loss: 5362.7891
  Epoch 10... Train Loss: 0.7722, Val Loss: 0.8030
  Epoch 20... Train Loss: 0.4158, Val Loss: 0.5239
  Epoch 30... Train Loss: 0.3314, Val Loss: 0.5161
Fold 4 - MSE: 28.1630, RMSE: 5.3069, MAE: 4.1087
Starting fold 5...
  Epoch 0... Train Loss: 9.4552, Val Loss: 6069.4990
  Epoch 10... Train Loss: 0.7429, Val Loss: 1.2741
  Epoch 20... Train Loss: 0.5590, Val Loss: 1.0003
  Epoch 30... Train Loss: 0.4374, Val Loss: 0.8714
  Epoch 40... Train Loss: 0.3540, Val Loss: 0.8057
  Epoch 50... Train Loss: 0.3359, Val Loss: 0.7773

[INFO 04-02 10:09:40] ax.service.ax_client: Completed trial 59 with data: {'avg_rmse_nonzero': 5.171288}.

  Epoch 60... Train Loss: 0.2709, Val Loss: 0.7780
Fold 5 - MSE: 5.7549, RMSE: 2.3989, MAE: 1.8809

Mean CV MSE: 28.8061, Mean CV RMSE: 5.1713, Mean CV MAE: 3.4620
Completed trial 59 with mean RMSE: 5.1713 ± 0.7183
Saved Ax client checkpoint

[INFO 04-02 10:09:45] ax.service.ax_client: Generated new trial 60 with parameters {'dropout_rate': 0.5, 'weight_decay': 1e-06, 'lr': 0.004672, 'batch_size': 256, 'early_stopping_patience': 49, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 256, 'activation': 'leaky_relu'} using model BoTorch.

Starting trial 60 with parameters: {'dropout_rate': 0.5, 'weight_decay': 1.0377619109047954e-06, 'lr': 0.004672426679438883, 'batch_size': 256, 'early_stopping_patience': 49, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 256, 'activation': 'leaky_relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 2.0893, Val Loss: 65.5867
  Epoch 10... Train Loss: 0.9055, Val Loss: 1.0727
  Epoch 20... Train Loss: 0.6850, Val Loss: 0.6259
  Epoch 30... Train Loss: 0.5215, Val Loss: 0.6384
  Epoch 40... Train Loss: 0.5002, Val Loss: 0.4313
  Epoch 50... Train Loss: 0.6150, Val Loss: 0.3233
  Epoch 60... Train Loss: 0.3549, Val Loss: 0.3210
  Epoch 70... Train Loss: 0.3392, Val Loss: 0.2988
  Epoch 80... Train Loss: 0.5087, Val Loss: 0.3631
  Epoch 90... Train Loss: 0.3204, Val Loss: 0.3074
  Epoch 100... Train Loss: 0.3831, Val Loss: 0.2767
  Epoch 110... Train Loss: 0.3971, Val Loss: 0.3285
  Epoch 120... Train Loss: 0.4808, Val Loss: 0.3469
  Epoch 130... Train Loss: 0.3573, Val Loss: 0.3364
  Epoch 140... Train Loss: 0.3874, Val Loss: 0.2965
Fold 1 - MSE: 37.4323, RMSE: 6.1182, MAE: 4.0994
Starting fold 2...
  Epoch 0... Train Loss: 8.7881, Val Loss: 650.6840
  Epoch 10... Train Loss: 0.7550, Val Loss: 0.7370
  Epoch 20... Train Loss: 0.4912, Val Loss: 0.6657
  Epoch 30... Train Loss: 0.4004, Val Loss: 0.5706
  Epoch 40... Train Loss: 0.3441, Val Loss: 0.4900
  Epoch 50... Train Loss: 0.3852, Val Loss: 0.4695
  Epoch 60... Train Loss: 0.2996, Val Loss: 0.4445
  Epoch 70... Train Loss: 0.2936, Val Loss: 0.4114
  Epoch 80... Train Loss: 0.3059, Val Loss: 0.4555
  Epoch 90... Train Loss: 0.2806, Val Loss: 0.3876
  Epoch 100... Train Loss: 0.2509, Val Loss: 0.3914
  Epoch 110... Train Loss: 0.2398, Val Loss: 0.3842
  Epoch 120... Train Loss: 0.2492, Val Loss: 0.3773
  Epoch 130... Train Loss: 0.2295, Val Loss: 0.3833
  Epoch 140... Train Loss: 0.2294, Val Loss: 0.3453
  Epoch 150... Train Loss: 0.2474, Val Loss: 0.3433
  Epoch 160... Train Loss: 0.2354, Val Loss: 0.3894
  Epoch 170... Train Loss: 0.2258, Val Loss: 0.3486
  Epoch 180... Train Loss: 0.2277, Val Loss: 0.3742
  Epoch 190... Train Loss: 0.2153, Val Loss: 0.3814
Fold 2 - MSE: 37.0174, RMSE: 6.0842, MAE: 3.7846
Starting fold 3...
  Epoch 0... Train Loss: 7.1339, Val Loss: 833.7331
  Epoch 10... Train Loss: 0.6522, Val Loss: 0.7673
  Epoch 20... Train Loss: 0.4524, Val Loss: 0.5703
  Epoch 30... Train Loss: 0.3566, Val Loss: 0.4835
  Epoch 40... Train Loss: 0.3143, Val Loss: 0.4163
  Epoch 50... Train Loss: 0.2856, Val Loss: 0.4390
  Epoch 60... Train Loss: 0.2427, Val Loss: 0.4278
  Epoch 70... Train Loss: 0.2163, Val Loss: 0.3969
  Epoch 80... Train Loss: 0.2520, Val Loss: 0.3881
  Epoch 90... Train Loss: 0.2547, Val Loss: 0.3873
  Epoch 100... Train Loss: 0.2281, Val Loss: 0.3774
  Epoch 110... Train Loss: 0.2387, Val Loss: 0.3682
  Epoch 120... Train Loss: 0.2334, Val Loss: 0.3879
  Epoch 130... Train Loss: 0.2201, Val Loss: 0.3878
  Epoch 140... Train Loss: 0.2335, Val Loss: 0.3822
Fold 3 - MSE: 29.4201, RMSE: 5.4240, MAE: 3.2459
Starting fold 4...
  Epoch 0... Train Loss: 4.5309, Val Loss: 22.2205
  Epoch 10... Train Loss: 0.5699, Val Loss: 0.8139
  Epoch 20... Train Loss: 0.3914, Val Loss: 0.5121
  Epoch 30... Train Loss: 0.3133, Val Loss: 0.4882
  Epoch 40... Train Loss: 0.2220, Val Loss: 0.4818
  Epoch 50... Train Loss: 0.2461, Val Loss: 0.5251
  Epoch 60... Train Loss: 0.2454, Val Loss: 0.4552
  Epoch 70... Train Loss: 0.2001, Val Loss: 0.4563
  Epoch 80... Train Loss: 0.1895, Val Loss: 0.4374
  Epoch 90... Train Loss: 0.2046, Val Loss: 0.4360
  Epoch 100... Train Loss: 0.1843, Val Loss: 0.4476
  Epoch 110... Train Loss: 0.1612, Val Loss: 0.4494
Fold 4 - MSE: 28.2591, RMSE: 5.3159, MAE: 4.1445
Starting fold 5...
  Epoch 0... Train Loss: 4.6178, Val Loss: 24.9886
  Epoch 10... Train Loss: 0.6221, Val Loss: 1.2810
  Epoch 20... Train Loss: 0.4681, Val Loss: 0.9768
  Epoch 30... Train Loss: 0.3363, Val Loss: 0.8938
  Epoch 40... Train Loss: 0.3059, Val Loss: 0.8877
  Epoch 50... Train Loss: 0.3020, Val Loss: 0.7926
  Epoch 60... Train Loss: 0.2831, Val Loss: 0.7908
  Epoch 70... Train Loss: 0.2734, Val Loss: 0.8014
  Epoch 80... Train Loss: 0.2843, Val Loss: 0.7628
  Epoch 90... Train Loss: 0.2144, Val Loss: 0.7646
  Epoch 100... Train Loss: 0.2116, Val Loss: 0.7351

[INFO 04-02 10:10:07] ax.service.ax_client: Completed trial 60 with data: {'avg_rmse_nonzero': 5.419481}.

  Epoch 110... Train Loss: 0.2373, Val Loss: 0.7305
Fold 5 - MSE: 17.2645, RMSE: 4.1551, MAE: 3.2407

Mean CV MSE: 29.8787, Mean CV RMSE: 5.4195, Mean CV MAE: 3.7030
Completed trial 60 with mean RMSE: 5.4195 ± 0.3563
Saved Ax client checkpoint

[INFO 04-02 10:10:13] ax.service.ax_client: Generated new trial 61 with parameters {'dropout_rate': 0.5, 'weight_decay': 2e-06, 'lr': 0.009033, 'batch_size': 256, 'early_stopping_patience': 48, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 64, 'hidden3': 512, 'activation': 'relu'} using model BoTorch.

Starting trial 61 with parameters: {'dropout_rate': 0.5, 'weight_decay': 2.393107776712879e-06, 'lr': 0.009032801877566476, 'batch_size': 256, 'early_stopping_patience': 48, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 64, 'hidden3': 512, 'activation': 'relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 4.1251, Val Loss: 430.2938
  Epoch 10... Train Loss: 1.0706, Val Loss: 2.0308
  Epoch 20... Train Loss: 0.5734, Val Loss: 0.5156
  Epoch 30... Train Loss: 0.5572, Val Loss: 0.5417
  Epoch 40... Train Loss: 0.5100, Val Loss: 0.4291
  Epoch 50... Train Loss: 0.4827, Val Loss: 0.4577
  Epoch 60... Train Loss: 0.4066, Val Loss: 0.3939
  Epoch 70... Train Loss: 0.3928, Val Loss: 0.3818
  Epoch 80... Train Loss: 0.4506, Val Loss: 0.3032
  Epoch 90... Train Loss: 0.3571, Val Loss: 0.2816
  Epoch 100... Train Loss: 0.4538, Val Loss: 0.2687
  Epoch 110... Train Loss: 0.4078, Val Loss: 0.3272
  Epoch 120... Train Loss: 0.5273, Val Loss: 0.3223
  Epoch 130... Train Loss: 0.3082, Val Loss: 0.3021
  Epoch 140... Train Loss: 0.4012, Val Loss: 0.2759
Fold 1 - MSE: 40.8446, RMSE: 6.3910, MAE: 4.1792
Starting fold 2...
  Epoch 0... Train Loss: 9.3205, Val Loss: 8448.5156
  Epoch 10... Train Loss: 0.8094, Val Loss: 0.8096
  Epoch 20... Train Loss: 0.5047, Val Loss: 0.6968
  Epoch 30... Train Loss: 0.4184, Val Loss: 0.6305
  Epoch 40... Train Loss: 0.3728, Val Loss: 0.5211
  Epoch 50... Train Loss: 0.3441, Val Loss: 0.5117
  Epoch 60... Train Loss: 0.3101, Val Loss: 0.4573
  Epoch 70... Train Loss: 0.3059, Val Loss: 0.4642
  Epoch 80... Train Loss: 0.2867, Val Loss: 0.4699
  Epoch 90... Train Loss: 0.3039, Val Loss: 0.4555
  Epoch 100... Train Loss: 0.2779, Val Loss: 0.3961
  Epoch 110... Train Loss: 0.2316, Val Loss: 0.3970
  Epoch 120... Train Loss: 0.2362, Val Loss: 0.3773
  Epoch 130... Train Loss: 0.2290, Val Loss: 0.3849
  Epoch 140... Train Loss: 0.2230, Val Loss: 0.3862
  Epoch 150... Train Loss: 0.2515, Val Loss: 0.3650
  Epoch 160... Train Loss: 0.2451, Val Loss: 0.3929
  Epoch 170... Train Loss: 0.2330, Val Loss: 0.3662
  Epoch 180... Train Loss: 0.2202, Val Loss: 0.3743
  Epoch 190... Train Loss: 0.2253, Val Loss: 0.3911
  Epoch 200... Train Loss: 0.2016, Val Loss: 0.3867
  Epoch 210... Train Loss: 0.1987, Val Loss: 0.3838
Fold 2 - MSE: 37.0475, RMSE: 6.0867, MAE: 3.5910
Starting fold 3...
  Epoch 0... Train Loss: 10.3026, Val Loss: 4651.9175
  Epoch 10... Train Loss: 0.7530, Val Loss: 0.9443
  Epoch 20... Train Loss: 0.4423, Val Loss: 0.5875
  Epoch 30... Train Loss: 0.3925, Val Loss: 0.4768
  Epoch 40... Train Loss: 0.3414, Val Loss: 0.4879
  Epoch 50... Train Loss: 0.2959, Val Loss: 0.4641
  Epoch 60... Train Loss: 0.2627, Val Loss: 0.4466
  Epoch 70... Train Loss: 0.2412, Val Loss: 0.4020
  Epoch 80... Train Loss: 0.2472, Val Loss: 0.3720
  Epoch 90... Train Loss: 0.2294, Val Loss: 0.3937
  Epoch 100... Train Loss: 0.2563, Val Loss: 0.4246
  Epoch 110... Train Loss: 0.2299, Val Loss: 0.3898
  Epoch 120... Train Loss: 0.2208, Val Loss: 0.3841
Fold 3 - MSE: 24.9388, RMSE: 4.9939, MAE: 3.0166
Starting fold 4...
  Epoch 0... Train Loss: 10.9773, Val Loss: 317.0674
  Epoch 10... Train Loss: 0.8391, Val Loss: 0.9227
  Epoch 20... Train Loss: 0.5197, Val Loss: 0.5435
  Epoch 30... Train Loss: 0.3902, Val Loss: 0.6272
  Epoch 40... Train Loss: 0.3071, Val Loss: 0.4785
  Epoch 50... Train Loss: 0.2522, Val Loss: 0.4981
  Epoch 60... Train Loss: 0.2234, Val Loss: 0.4906
  Epoch 70... Train Loss: 0.2602, Val Loss: 0.4516
  Epoch 80... Train Loss: 0.2175, Val Loss: 0.4487
  Epoch 90... Train Loss: 0.2256, Val Loss: 0.4485
  Epoch 100... Train Loss: 0.1779, Val Loss: 0.4752
Fold 4 - MSE: 31.6296, RMSE: 5.6240, MAE: 4.3729
Starting fold 5...
  Epoch 0... Train Loss: 7.6890, Val Loss: 4062.4858
  Epoch 10... Train Loss: 0.6835, Val Loss: 1.4353
  Epoch 20... Train Loss: 0.5082, Val Loss: 0.9908
  Epoch 30... Train Loss: 0.4104, Val Loss: 0.8960
  Epoch 40... Train Loss: 0.3820, Val Loss: 0.8291
  Epoch 50... Train Loss: 0.3111, Val Loss: 0.7822
  Epoch 60... Train Loss: 0.2880, Val Loss: 0.8009
  Epoch 70... Train Loss: 0.2698, Val Loss: 0.7332
  Epoch 80... Train Loss: 0.2908, Val Loss: 0.7545
  Epoch 90... Train Loss: 0.2641, Val Loss: 0.7411
  Epoch 100... Train Loss: 0.2474, Val Loss: 0.7381
  Epoch 110... Train Loss: 0.2080, Val Loss: 0.7371
  Epoch 120... Train Loss: 0.2577, Val Loss: 0.7430
  Epoch 130... Train Loss: 0.2347, Val Loss: 0.7255
  Epoch 140... Train Loss: 0.2137, Val Loss: 0.7070
  Epoch 150... Train Loss: 0.2244, Val Loss: 0.7190
  Epoch 160... Train Loss: 0.2286, Val Loss: 0.7111
  Epoch 170... Train Loss: 0.2221, Val Loss: 0.7105

[INFO 04-02 10:10:30] ax.service.ax_client: Completed trial 61 with data: {'avg_rmse_nonzero': 5.141715}.

  Epoch 180... Train Loss: 0.2239, Val Loss: 0.7113
Fold 5 - MSE: 6.8279, RMSE: 2.6130, MAE: 2.1207

Mean CV MSE: 28.2577, Mean CV RMSE: 5.1417, Mean CV MAE: 3.4561
Completed trial 61 with mean RMSE: 5.1417 ± 0.6746
Saved Ax client checkpoint

[INFO 04-02 10:10:32] ax.service.ax_client: Generated new trial 62 with parameters {'dropout_rate': 0.158112, 'weight_decay': 1e-06, 'lr': 0.004103, 'batch_size': 256, 'early_stopping_patience': 40, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 128, 'hidden3': 512, 'activation': 'relu'} using model BoTorch.

Starting trial 62 with parameters: {'dropout_rate': 0.15811244425572885, 'weight_decay': 1e-06, 'lr': 0.004102863919392471, 'batch_size': 256, 'early_stopping_patience': 40, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 128, 'hidden3': 512, 'activation': 'relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 2.1116, Val Loss: 255.8411
  Epoch 10... Train Loss: 0.8152, Val Loss: 0.8955
  Epoch 20... Train Loss: 0.5000, Val Loss: 0.5221
  Epoch 30... Train Loss: 0.3623, Val Loss: 0.5106
  Epoch 40... Train Loss: 0.3216, Val Loss: 0.3232
  Epoch 50... Train Loss: 0.4696, Val Loss: 0.3138
  Epoch 60... Train Loss: 0.3177, Val Loss: 0.2787
  Epoch 70... Train Loss: 0.2894, Val Loss: 0.3184
  Epoch 80... Train Loss: 0.3508, Val Loss: 0.3000
  Epoch 90... Train Loss: 0.2619, Val Loss: 0.2940
  Epoch 100... Train Loss: 0.3223, Val Loss: 0.3063
Fold 1 - MSE: 40.7030, RMSE: 6.3799, MAE: 4.1982
Starting fold 2...
  Epoch 0... Train Loss: 7.8445, Val Loss: 660.5150
  Epoch 10... Train Loss: 0.6147, Val Loss: 0.8351
  Epoch 20... Train Loss: 0.3844, Val Loss: 0.6478
  Epoch 30... Train Loss: 0.3294, Val Loss: 0.4280
  Epoch 40... Train Loss: 0.2344, Val Loss: 0.3907
  Epoch 50... Train Loss: 0.2210, Val Loss: 0.3507
  Epoch 60... Train Loss: 0.2389, Val Loss: 0.4086
  Epoch 70... Train Loss: 0.2307, Val Loss: 0.3512
  Epoch 80... Train Loss: 0.2201, Val Loss: 0.3550
  Epoch 90... Train Loss: 0.2048, Val Loss: 0.3330
  Epoch 100... Train Loss: 0.1646, Val Loss: 0.3370
  Epoch 110... Train Loss: 0.1701, Val Loss: 0.3461
Fold 2 - MSE: 38.0874, RMSE: 6.1715, MAE: 3.8112
Starting fold 3...
  Epoch 0... Train Loss: 8.8508, Val Loss: 443.6817
  Epoch 10... Train Loss: 0.6496, Val Loss: 0.9457
  Epoch 20... Train Loss: 0.3868, Val Loss: 0.6181
  Epoch 30... Train Loss: 0.3020, Val Loss: 0.4468
  Epoch 40... Train Loss: 0.2274, Val Loss: 0.4467
  Epoch 50... Train Loss: 0.2132, Val Loss: 0.4807
  Epoch 60... Train Loss: 0.2013, Val Loss: 0.4573
  Epoch 70... Train Loss: 0.2001, Val Loss: 0.4493
  Epoch 80... Train Loss: 0.2063, Val Loss: 0.4102
  Epoch 90... Train Loss: 0.1732, Val Loss: 0.4280
  Epoch 100... Train Loss: 0.1795, Val Loss: 0.4433
  Epoch 110... Train Loss: 0.1709, Val Loss: 0.4179
  Epoch 120... Train Loss: 0.1752, Val Loss: 0.4184
  Epoch 130... Train Loss: 0.1528, Val Loss: 0.3991
  Epoch 140... Train Loss: 0.1478, Val Loss: 0.4011
  Epoch 150... Train Loss: 0.1680, Val Loss: 0.4119
  Epoch 160... Train Loss: 0.1570, Val Loss: 0.3960
  Epoch 170... Train Loss: 0.1762, Val Loss: 0.3792
  Epoch 180... Train Loss: 0.1496, Val Loss: 0.3774
  Epoch 190... Train Loss: 0.1404, Val Loss: 0.3977
  Epoch 200... Train Loss: 0.1540, Val Loss: 0.3887
  Epoch 210... Train Loss: 0.1480, Val Loss: 0.3829
  Epoch 220... Train Loss: 0.1450, Val Loss: 0.3732
Fold 3 - MSE: 20.0526, RMSE: 4.4780, MAE: 2.8394
Starting fold 4...
  Epoch 0... Train Loss: 9.5824, Val Loss: 605.6114
  Epoch 10... Train Loss: 0.7045, Val Loss: 0.5462
  Epoch 20... Train Loss: 0.3863, Val Loss: 0.5447
  Epoch 30... Train Loss: 0.2724, Val Loss: 0.5428
  Epoch 40... Train Loss: 0.2083, Val Loss: 0.4378
  Epoch 50... Train Loss: 0.1662, Val Loss: 0.4721
  Epoch 60... Train Loss: 0.1633, Val Loss: 0.4976
  Epoch 70... Train Loss: 0.1518, Val Loss: 0.4393
  Epoch 80... Train Loss: 0.1522, Val Loss: 0.4788
Fold 4 - MSE: 32.0111, RMSE: 5.6578, MAE: 4.5063
Starting fold 5...
  Epoch 0... Train Loss: 9.3179, Val Loss: 142.7980
  Epoch 10... Train Loss: 0.5553, Val Loss: 1.3134
  Epoch 20... Train Loss: 0.3441, Val Loss: 0.9145
  Epoch 30... Train Loss: 0.2604, Val Loss: 0.9280
  Epoch 40... Train Loss: 0.2525, Val Loss: 0.8431
  Epoch 50... Train Loss: 0.2349, Val Loss: 0.7889
  Epoch 60... Train Loss: 0.2119, Val Loss: 0.7819
  Epoch 70... Train Loss: 0.1964, Val Loss: 0.7685
  Epoch 80... Train Loss: 0.2064, Val Loss: 0.7652
  Epoch 90... Train Loss: 0.1792, Val Loss: 0.7428
  Epoch 100... Train Loss: 0.1829, Val Loss: 0.7350
  Epoch 110... Train Loss: 0.1855, Val Loss: 0.7446

[INFO 04-02 10:10:45] ax.service.ax_client: Completed trial 62 with data: {'avg_rmse_nonzero': 4.980075}.

  Epoch 120... Train Loss: 0.1680, Val Loss: 0.7370
Fold 5 - MSE: 4.8980, RMSE: 2.2131, MAE: 1.6729

Mean CV MSE: 27.1504, Mean CV RMSE: 4.9801, Mean CV MAE: 3.4056
Completed trial 62 with mean RMSE: 4.9801 ± 0.7664
Saved Ax client checkpoint

[INFO 04-02 10:10:48] ax.service.ax_client: Generated new trial 63 with parameters {'dropout_rate': 0.5, 'weight_decay': 4.1e-05, 'lr': 0.005337, 'batch_size': 256, 'early_stopping_patience': 49, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 32, 'activation': 'relu'} using model BoTorch.

Starting trial 63 with parameters: {'dropout_rate': 0.5, 'weight_decay': 4.138563336340799e-05, 'lr': 0.005336538536021532, 'batch_size': 256, 'early_stopping_patience': 49, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 32, 'activation': 'relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 1.2810, Val Loss: 109.5055
  Epoch 10... Train Loss: 1.0673, Val Loss: 1.2125
  Epoch 20... Train Loss: 0.4949, Val Loss: 0.6094
  Epoch 30... Train Loss: 0.4827, Val Loss: 0.5250
  Epoch 40... Train Loss: 0.4800, Val Loss: 0.3905
  Epoch 50... Train Loss: 0.5014, Val Loss: 0.4101
  Epoch 60... Train Loss: 0.3621, Val Loss: 0.3501
  Epoch 70... Train Loss: 0.3247, Val Loss: 0.3759
  Epoch 80... Train Loss: 0.4978, Val Loss: 0.3976
  Epoch 90... Train Loss: 0.2999, Val Loss: 0.3323
  Epoch 100... Train Loss: 0.4267, Val Loss: 0.3116
  Epoch 110... Train Loss: 0.4490, Val Loss: 0.3126
  Epoch 120... Train Loss: 0.4858, Val Loss: 0.3551
  Epoch 130... Train Loss: 0.3301, Val Loss: 0.3128
  Epoch 140... Train Loss: 0.2981, Val Loss: 0.3015
  Epoch 150... Train Loss: 0.4394, Val Loss: 0.3038
  Epoch 160... Train Loss: 0.2952, Val Loss: 0.3126
Fold 1 - MSE: 39.5950, RMSE: 6.2925, MAE: 4.2370
Starting fold 2...
  Epoch 0... Train Loss: 7.0344, Val Loss: 465.8335
  Epoch 10... Train Loss: 0.6530, Val Loss: 0.8132
  Epoch 20... Train Loss: 0.4464, Val Loss: 0.6809
  Epoch 30... Train Loss: 0.4041, Val Loss: 0.4897
  Epoch 40... Train Loss: 0.2974, Val Loss: 0.4431
  Epoch 50... Train Loss: 0.3407, Val Loss: 0.4203
  Epoch 60... Train Loss: 0.3255, Val Loss: 0.4430
  Epoch 70... Train Loss: 0.3543, Val Loss: 0.4097
  Epoch 80... Train Loss: 0.3421, Val Loss: 0.4458
  Epoch 90... Train Loss: 0.2532, Val Loss: 0.3734
  Epoch 100... Train Loss: 0.2576, Val Loss: 0.4040
  Epoch 110... Train Loss: 0.2338, Val Loss: 0.4142
  Epoch 120... Train Loss: 0.2505, Val Loss: 0.3747
  Epoch 130... Train Loss: 0.2145, Val Loss: 0.3924
  Epoch 140... Train Loss: 0.2210, Val Loss: 0.3753
Fold 2 - MSE: 38.9250, RMSE: 6.2390, MAE: 3.8381
Starting fold 3...
  Epoch 0... Train Loss: 7.0927, Val Loss: 1115.8695
  Epoch 10... Train Loss: 0.6879, Val Loss: 0.7536
  Epoch 20... Train Loss: 0.4680, Val Loss: 0.5190
  Epoch 30... Train Loss: 0.3619, Val Loss: 0.4757
  Epoch 40... Train Loss: 0.2855, Val Loss: 0.4647
  Epoch 50... Train Loss: 0.2951, Val Loss: 0.4590
  Epoch 60... Train Loss: 0.2462, Val Loss: 0.4100
  Epoch 70... Train Loss: 0.2423, Val Loss: 0.4255
  Epoch 80... Train Loss: 0.2653, Val Loss: 0.4176
  Epoch 90... Train Loss: 0.2286, Val Loss: 0.4040
  Epoch 100... Train Loss: 0.2346, Val Loss: 0.4097
  Epoch 110... Train Loss: 0.2162, Val Loss: 0.3915
Fold 3 - MSE: 39.2434, RMSE: 6.2645, MAE: 3.5488
Starting fold 4...
  Epoch 0... Train Loss: 4.3934, Val Loss: 35.2962
  Epoch 10... Train Loss: 0.6266, Val Loss: 0.6274
  Epoch 20... Train Loss: 0.4111, Val Loss: 0.5351
  Epoch 30... Train Loss: 0.3363, Val Loss: 0.5661
  Epoch 40... Train Loss: 0.2623, Val Loss: 0.4311
  Epoch 50... Train Loss: 0.2226, Val Loss: 0.4631
  Epoch 60... Train Loss: 0.2417, Val Loss: 0.4885
  Epoch 70... Train Loss: 0.2046, Val Loss: 0.4371
  Epoch 80... Train Loss: 0.2027, Val Loss: 0.4167
  Epoch 90... Train Loss: 0.1814, Val Loss: 0.4239
  Epoch 100... Train Loss: 0.1837, Val Loss: 0.4189
  Epoch 110... Train Loss: 0.1732, Val Loss: 0.4491
  Epoch 120... Train Loss: 0.1888, Val Loss: 0.4332
  Epoch 130... Train Loss: 0.1881, Val Loss: 0.4237
Fold 4 - MSE: 29.7458, RMSE: 5.4540, MAE: 4.2898
Starting fold 5...
  Epoch 0... Train Loss: 7.5138, Val Loss: 406.1378
  Epoch 10... Train Loss: 0.6577, Val Loss: 1.3332
  Epoch 20... Train Loss: 0.5123, Val Loss: 1.0200
  Epoch 30... Train Loss: 0.4234, Val Loss: 0.9035
  Epoch 40... Train Loss: 0.3137, Val Loss: 0.8453
  Epoch 50... Train Loss: 0.2917, Val Loss: 0.7760
  Epoch 60... Train Loss: 0.2807, Val Loss: 0.7722
  Epoch 70... Train Loss: 0.2963, Val Loss: 0.7818
  Epoch 80... Train Loss: 0.2731, Val Loss: 0.7458
  Epoch 90... Train Loss: 0.2535, Val Loss: 0.7445
  Epoch 100... Train Loss: 0.2477, Val Loss: 0.6991
  Epoch 110... Train Loss: 0.2367, Val Loss: 0.7201
  Epoch 120... Train Loss: 0.2161, Val Loss: 0.7339
  Epoch 130... Train Loss: 0.2469, Val Loss: 0.7184
Fold 5 - MSE: 17.2175, RMSE: 4.1494, MAE: 3.6364

Mean CV MSE: 32.9453, Mean CV RMSE: 5.6799, Mean CV MAE: 3.9100

[INFO 04-02 10:10:59] ax.service.ax_client: Completed trial 63 with data: {'avg_rmse_nonzero': 5.679854}.

Completed trial 63 with mean RMSE: 5.6799 ± 0.4137
Saved Ax client checkpoint

[INFO 04-02 10:11:02] ax.service.ax_client: Generated new trial 64 with parameters {'dropout_rate': 0.5, 'weight_decay': 1e-06, 'lr': 0.005862, 'batch_size': 256, 'early_stopping_patience': 15, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 128, 'hidden3': 512, 'activation': 'leaky_relu'} using model BoTorch.

Starting trial 64 with parameters: {'dropout_rate': 0.5, 'weight_decay': 1e-06, 'lr': 0.005862323607618377, 'batch_size': 256, 'early_stopping_patience': 15, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 128, 'hidden3': 512, 'activation': 'leaky_relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 3.6563, Val Loss: 73.8816
  Epoch 10... Train Loss: 0.9393, Val Loss: 1.3301
  Epoch 20... Train Loss: 0.5515, Val Loss: 0.5235
  Epoch 30... Train Loss: 0.4645, Val Loss: 0.5515
  Epoch 40... Train Loss: 0.4641, Val Loss: 0.4346
  Epoch 50... Train Loss: 0.4606, Val Loss: 0.3645
  Epoch 60... Train Loss: 0.4272, Val Loss: 0.3680
  Epoch 70... Train Loss: 0.4042, Val Loss: 0.3833
  Epoch 80... Train Loss: 0.4280, Val Loss: 0.3389
  Epoch 90... Train Loss: 0.3292, Val Loss: 0.3172
  Epoch 100... Train Loss: 0.4911, Val Loss: 0.3167
Fold 1 - MSE: 42.5095, RMSE: 6.5199, MAE: 4.2834
Starting fold 2...
  Epoch 0... Train Loss: 8.1441, Val Loss: 2629.0068
  Epoch 10... Train Loss: 0.7780, Val Loss: 0.9353
  Epoch 20... Train Loss: 0.4403, Val Loss: 0.6717
  Epoch 30... Train Loss: 0.4196, Val Loss: 0.5447
  Epoch 40... Train Loss: 0.3176, Val Loss: 0.5347
  Epoch 50... Train Loss: 0.3264, Val Loss: 0.4918
  Epoch 60... Train Loss: 0.3045, Val Loss: 0.4590
  Epoch 70... Train Loss: 0.2960, Val Loss: 0.4187
  Epoch 80... Train Loss: 0.3237, Val Loss: 0.4501
Fold 2 - MSE: 39.5756, RMSE: 6.2909, MAE: 3.9089
Starting fold 3...
  Epoch 0... Train Loss: 7.7592, Val Loss: 1175.7361
  Epoch 10... Train Loss: 0.6672, Val Loss: 0.8145
  Epoch 20... Train Loss: 0.4512, Val Loss: 0.5900
  Epoch 30... Train Loss: 0.4111, Val Loss: 0.4926
  Epoch 40... Train Loss: 0.3517, Val Loss: 0.4222
  Epoch 50... Train Loss: 0.3208, Val Loss: 0.4394
Fold 3 - MSE: 20.4669, RMSE: 4.5240, MAE: 2.9502
Starting fold 4...
  Epoch 0... Train Loss: 7.5257, Val Loss: 368.2553
  Epoch 10... Train Loss: 0.7314, Val Loss: 0.6454
  Epoch 20... Train Loss: 0.4369, Val Loss: 0.5390
  Epoch 30... Train Loss: 0.3896, Val Loss: 0.5450
  Epoch 40... Train Loss: 0.2928, Val Loss: 0.4558
  Epoch 50... Train Loss: 0.2464, Val Loss: 0.4346
  Epoch 60... Train Loss: 0.2263, Val Loss: 0.4452
Fold 4 - MSE: 30.3178, RMSE: 5.5062, MAE: 4.3145
Starting fold 5...
  Epoch 0... Train Loss: 5.6592, Val Loss: 107.8672
  Epoch 10... Train Loss: 0.6777, Val Loss: 1.5463
  Epoch 20... Train Loss: 0.5012, Val Loss: 1.0594
  Epoch 30... Train Loss: 0.3965, Val Loss: 0.9343
  Epoch 40... Train Loss: 0.3115, Val Loss: 0.8014
  Epoch 50... Train Loss: 0.2823, Val Loss: 0.8111
  Epoch 60... Train Loss: 0.2755, Val Loss: 0.7676

[INFO 04-02 10:11:09] ax.service.ax_client: Completed trial 64 with data: {'avg_rmse_nonzero': 5.068447}.

  Epoch 70... Train Loss: 0.2765, Val Loss: 0.7753
  Epoch 80... Train Loss: 0.2672, Val Loss: 0.7854
Fold 5 - MSE: 6.2559, RMSE: 2.5012, MAE: 2.0101

Mean CV MSE: 27.8252, Mean CV RMSE: 5.0684, Mean CV MAE: 3.4934
Completed trial 64 with mean RMSE: 5.0684 ± 0.7308
Saved Ax client checkpoint

[INFO 04-02 10:11:12] ax.service.ax_client: Generated new trial 65 with parameters {'dropout_rate': 0.5, 'weight_decay': 8.1e-05, 'lr': 0.01, 'batch_size': 256, 'early_stopping_patience': 20, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 64, 'hidden3': 512, 'activation': 'leaky_relu'} using model BoTorch.

Starting trial 65 with parameters: {'dropout_rate': 0.5, 'weight_decay': 8.097382581835886e-05, 'lr': 0.01, 'batch_size': 256, 'early_stopping_patience': 20, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 64, 'hidden3': 512, 'activation': 'leaky_relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 2.4286, Val Loss: 562.4431
  Epoch 10... Train Loss: 1.0239, Val Loss: 1.5310
  Epoch 20... Train Loss: 0.7136, Val Loss: 0.5936
  Epoch 30... Train Loss: 0.4541, Val Loss: 0.6765
  Epoch 40... Train Loss: 0.5766, Val Loss: 0.4500
  Epoch 50... Train Loss: 0.5019, Val Loss: 0.3975
  Epoch 60... Train Loss: 0.4383, Val Loss: 0.3749
  Epoch 70... Train Loss: 0.4255, Val Loss: 0.3774
  Epoch 80... Train Loss: 0.5346, Val Loss: 0.3491
  Epoch 90... Train Loss: 0.3743, Val Loss: 0.3447
  Epoch 100... Train Loss: 0.4316, Val Loss: 0.3350
  Epoch 110... Train Loss: 0.4400, Val Loss: 0.3373
  Epoch 120... Train Loss: 0.5490, Val Loss: 0.3443
  Epoch 130... Train Loss: 0.3298, Val Loss: 0.3366
Fold 1 - MSE: 41.7175, RMSE: 6.4589, MAE: 4.2491
Starting fold 2...
  Epoch 0... Train Loss: 8.9991, Val Loss: 5244.6284
  Epoch 10... Train Loss: 0.9665, Val Loss: 0.7829
  Epoch 20... Train Loss: 0.5184, Val Loss: 0.6707
  Epoch 30... Train Loss: 0.4543, Val Loss: 0.5473
  Epoch 40... Train Loss: 0.3267, Val Loss: 0.4432
  Epoch 50... Train Loss: 0.3153, Val Loss: 0.4474
  Epoch 60... Train Loss: 0.3652, Val Loss: 0.4493
Fold 2 - MSE: 36.5450, RMSE: 6.0452, MAE: 3.6482
Starting fold 3...
  Epoch 0... Train Loss: 9.0232, Val Loss: 7681.4565
  Epoch 10... Train Loss: 0.7918, Val Loss: 0.8480
  Epoch 20... Train Loss: 0.4988, Val Loss: 0.6213
  Epoch 30... Train Loss: 0.4283, Val Loss: 0.4854
  Epoch 40... Train Loss: 0.3182, Val Loss: 0.5249
  Epoch 50... Train Loss: 0.3032, Val Loss: 0.4840
  Epoch 60... Train Loss: 0.2724, Val Loss: 0.5017
Fold 3 - MSE: 26.2386, RMSE: 5.1224, MAE: 3.2087
Starting fold 4...
  Epoch 0... Train Loss: 10.6236, Val Loss: 1311.2412
  Epoch 10... Train Loss: 0.8058, Val Loss: 0.5835
  Epoch 20... Train Loss: 0.5062, Val Loss: 0.5231
  Epoch 30... Train Loss: 0.4280, Val Loss: 0.4868
  Epoch 40... Train Loss: 0.3270, Val Loss: 0.4302
  Epoch 50... Train Loss: 0.2848, Val Loss: 0.4292
  Epoch 60... Train Loss: 0.2478, Val Loss: 0.4585
  Epoch 70... Train Loss: 0.2507, Val Loss: 0.4418
Fold 4 - MSE: 30.2612, RMSE: 5.5010, MAE: 4.3597
Starting fold 5...
  Epoch 0... Train Loss: 9.4008, Val Loss: 7314.7041
  Epoch 10... Train Loss: 0.8161, Val Loss: 1.5378
  Epoch 20... Train Loss: 0.5011, Val Loss: 1.0506
  Epoch 30... Train Loss: 0.4275, Val Loss: 0.8888
  Epoch 40... Train Loss: 0.3264, Val Loss: 0.8813
  Epoch 50... Train Loss: 0.2706, Val Loss: 0.8088
  Epoch 60... Train Loss: 0.2706, Val Loss: 0.7790
  Epoch 70... Train Loss: 0.2633, Val Loss: 0.7800
  Epoch 80... Train Loss: 0.2948, Val Loss: 0.7705

[INFO 04-02 10:11:20] ax.service.ax_client: Completed trial 65 with data: {'avg_rmse_nonzero': 5.052083}.

Fold 5 - MSE: 4.5492, RMSE: 2.1329, MAE: 1.5874

Mean CV MSE: 27.8623, Mean CV RMSE: 5.0521, Mean CV MAE: 3.4106
Completed trial 65 with mean RMSE: 5.0521 ± 0.7646
Saved Ax client checkpoint

[INFO 04-02 10:11:23] ax.service.ax_client: Generated new trial 66 with parameters {'dropout_rate': 0.404643, 'weight_decay': 1e-06, 'lr': 0.004376, 'batch_size': 256, 'early_stopping_patience': 10, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 512, 'activation': 'leaky_relu'} using model BoTorch.

Starting trial 66 with parameters: {'dropout_rate': 0.4046431084804865, 'weight_decay': 1e-06, 'lr': 0.004376390671672479, 'batch_size': 256, 'early_stopping_patience': 10, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 512, 'activation': 'leaky_relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 1.4401, Val Loss: 412.6567
  Epoch 10... Train Loss: 0.8587, Val Loss: 0.8015
  Epoch 20... Train Loss: 0.5303, Val Loss: 0.5271
  Epoch 30... Train Loss: 0.4440, Val Loss: 0.4538
  Epoch 40... Train Loss: 0.4225, Val Loss: 0.4232
  Epoch 50... Train Loss: 0.4682, Val Loss: 0.3641
  Epoch 60... Train Loss: 0.4301, Val Loss: 0.3640
  Epoch 70... Train Loss: 0.3951, Val Loss: 0.3519
  Epoch 80... Train Loss: 0.3740, Val Loss: 0.3431
  Epoch 90... Train Loss: 0.4053, Val Loss: 0.3497
Fold 1 - MSE: 41.0143, RMSE: 6.4042, MAE: 4.1224
Starting fold 2...
  Epoch 0... Train Loss: 10.3754, Val Loss: 864.8739
  Epoch 10... Train Loss: 0.6840, Val Loss: 0.8383
  Epoch 20... Train Loss: 0.4680, Val Loss: 0.6505
  Epoch 30... Train Loss: 0.4370, Val Loss: 0.5335
  Epoch 40... Train Loss: 0.3535, Val Loss: 0.5503
Fold 2 - MSE: 37.9687, RMSE: 6.1619, MAE: 3.6263
Starting fold 3...
  Epoch 0... Train Loss: 7.2212, Val Loss: 337.4380
  Epoch 10... Train Loss: 0.5468, Val Loss: 0.8249
  Epoch 20... Train Loss: 0.3503, Val Loss: 0.5202
  Epoch 30... Train Loss: 0.3209, Val Loss: 0.4283
  Epoch 40... Train Loss: 0.2433, Val Loss: 0.4432
Fold 3 - MSE: 38.6949, RMSE: 6.2205, MAE: 3.5299
Starting fold 4...
  Epoch 0... Train Loss: 8.5622, Val Loss: 725.9312
  Epoch 10... Train Loss: 0.6734, Val Loss: 0.6223
  Epoch 20... Train Loss: 0.4235, Val Loss: 0.5703
  Epoch 30... Train Loss: 0.3173, Val Loss: 0.5703
Fold 4 - MSE: 37.7081, RMSE: 6.1407, MAE: 4.9533
Starting fold 5...
  Epoch 0... Train Loss: 7.1663, Val Loss: 485.2769
  Epoch 10... Train Loss: 0.6620, Val Loss: 1.3111
  Epoch 20... Train Loss: 0.5017, Val Loss: 1.0685
  Epoch 30... Train Loss: 0.3993, Val Loss: 0.9017
  Epoch 40... Train Loss: 0.3265, Val Loss: 0.8329
  Epoch 50... Train Loss: 0.2691, Val Loss: 0.7909
  Epoch 60... Train Loss: 0.2492, Val Loss: 0.7777
  Epoch 70... Train Loss: 0.2698, Val Loss: 0.7709

[INFO 04-02 10:11:29] ax.service.ax_client: Completed trial 66 with data: {'avg_rmse_nonzero': 5.459661}.

  Epoch 80... Train Loss: 0.2746, Val Loss: 0.7596
Fold 5 - MSE: 5.6215, RMSE: 2.3710, MAE: 1.7295

Mean CV MSE: 32.2015, Mean CV RMSE: 5.4597, Mean CV MAE: 3.5923
Completed trial 66 with mean RMSE: 5.4597 ± 0.7736
Saved Ax client checkpoint

[INFO 04-02 10:11:33] ax.service.ax_client: Generated new trial 67 with parameters {'dropout_rate': 0.344258, 'weight_decay': 1e-06, 'lr': 0.007014, 'batch_size': 256, 'early_stopping_patience': 10, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 64, 'hidden3': 256, 'activation': 'relu'} using model BoTorch.

Starting trial 67 with parameters: {'dropout_rate': 0.34425842937966156, 'weight_decay': 1e-06, 'lr': 0.007013764414201555, 'batch_size': 256, 'early_stopping_patience': 10, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 64, 'hidden3': 256, 'activation': 'relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 1.8851, Val Loss: 1003.4584
  Epoch 10... Train Loss: 0.8784, Val Loss: 1.4353
  Epoch 20... Train Loss: 0.4684, Val Loss: 0.6190
  Epoch 30... Train Loss: 0.4293, Val Loss: 0.4507
  Epoch 40... Train Loss: 0.4404, Val Loss: 0.3845
  Epoch 50... Train Loss: 0.4244, Val Loss: 0.3434
  Epoch 60... Train Loss: 0.3817, Val Loss: 0.3347
  Epoch 70... Train Loss: 0.3886, Val Loss: 0.3469
Fold 1 - MSE: 41.8905, RMSE: 6.4723, MAE: 4.2523
Starting fold 2...
  Epoch 0... Train Loss: 10.2269, Val Loss: 6116.2236
  Epoch 10... Train Loss: 0.7311, Val Loss: 0.9273
  Epoch 20... Train Loss: 0.4934, Val Loss: 0.6816
  Epoch 30... Train Loss: 0.4115, Val Loss: 0.5755
  Epoch 40... Train Loss: 0.3321, Val Loss: 0.5386
  Epoch 50... Train Loss: 0.3068, Val Loss: 0.4868
  Epoch 60... Train Loss: 0.2955, Val Loss: 0.4674
Fold 2 - MSE: 36.7995, RMSE: 6.0663, MAE: 4.0233
Starting fold 3...
  Epoch 0... Train Loss: 8.8175, Val Loss: 8700.8506
  Epoch 10... Train Loss: 0.6548, Val Loss: 0.9033
  Epoch 20... Train Loss: 0.3673, Val Loss: 0.5523
  Epoch 30... Train Loss: 0.3070, Val Loss: 0.4633
  Epoch 40... Train Loss: 0.2630, Val Loss: 0.4359
  Epoch 50... Train Loss: 0.2524, Val Loss: 0.4360
Fold 3 - MSE: 26.2990, RMSE: 5.1283, MAE: 2.9640
Starting fold 4...
  Epoch 0... Train Loss: 6.6661, Val Loss: 3210.5466
  Epoch 10... Train Loss: 0.7372, Val Loss: 0.6312
  Epoch 20... Train Loss: 0.4216, Val Loss: 0.6065
  Epoch 30... Train Loss: 0.3391, Val Loss: 0.5528
  Epoch 40... Train Loss: 0.3048, Val Loss: 0.5068
Fold 4 - MSE: 32.2949, RMSE: 5.6829, MAE: 4.4287
Starting fold 5...
  Epoch 0... Train Loss: 9.1712, Val Loss: 4125.0396
  Epoch 10... Train Loss: 0.6433, Val Loss: 1.2630
  Epoch 20... Train Loss: 0.4267, Val Loss: 0.9463
  Epoch 30... Train Loss: 0.3147, Val Loss: 0.8217
  Epoch 40... Train Loss: 0.3257, Val Loss: 0.8177
  Epoch 50... Train Loss: 0.2472, Val Loss: 0.7602
  Epoch 60... Train Loss: 0.2546, Val Loss: 0.7656

[INFO 04-02 10:11:40] ax.service.ax_client: Completed trial 67 with data: {'avg_rmse_nonzero': 5.280516}.

Fold 5 - MSE: 9.3203, RMSE: 3.0529, MAE: 2.4483

Mean CV MSE: 29.3208, Mean CV RMSE: 5.2805, Mean CV MAE: 3.6233
Completed trial 67 with mean RMSE: 5.2805 ± 0.5994
Saved Ax client checkpoint

[INFO 04-02 10:11:42] ax.service.ax_client: Generated new trial 68 with parameters {'dropout_rate': 0.5, 'weight_decay': 1e-06, 'lr': 0.01, 'batch_size': 64, 'early_stopping_patience': 10, 'n_layers': 3, 'hidden1': 128, 'hidden2': 64, 'hidden3': 32, 'activation': 'leaky_relu'} using model BoTorch.

Starting trial 68 with parameters: {'dropout_rate': 0.5, 'weight_decay': 1e-06, 'lr': 0.01, 'batch_size': 64, 'early_stopping_patience': 10, 'n_layers': 3, 'hidden1': 128, 'hidden2': 64, 'hidden3': 32, 'activation': 'leaky_relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 5.0846, Val Loss: 373.4156
  Epoch 10... Train Loss: 0.7920, Val Loss: 0.4968
  Epoch 20... Train Loss: 0.5582, Val Loss: 0.4629
  Epoch 30... Train Loss: 0.4302, Val Loss: 0.3530
  Epoch 40... Train Loss: 0.4049, Val Loss: 0.2651
Fold 1 - MSE: 35.6558, RMSE: 5.9713, MAE: 4.0962
Starting fold 2...
  Epoch 0... Train Loss: 2.8099, Val Loss: 15.2710
  Epoch 10... Train Loss: 0.5726, Val Loss: 0.9209
  Epoch 20... Train Loss: 0.4462, Val Loss: 0.6725
  Epoch 30... Train Loss: 0.3845, Val Loss: 0.5387
Fold 2 - MSE: 43.9289, RMSE: 6.6279, MAE: 4.0789
Starting fold 3...
  Epoch 0... Train Loss: 3.1593, Val Loss: 22.7601
  Epoch 10... Train Loss: 0.5101, Val Loss: 0.5770
  Epoch 20... Train Loss: 0.3653, Val Loss: 0.4279
  Epoch 30... Train Loss: 0.2930, Val Loss: 0.3949
  Epoch 40... Train Loss: 0.2726, Val Loss: 0.3695
  Epoch 50... Train Loss: 0.2787, Val Loss: 0.3935
Fold 3 - MSE: 45.9993, RMSE: 6.7823, MAE: 3.7181
Starting fold 4...
  Epoch 0... Train Loss: 2.7982, Val Loss: 13.7523
  Epoch 10... Train Loss: 0.5453, Val Loss: 0.5014
  Epoch 20... Train Loss: 0.3087, Val Loss: 0.5113
Fold 4 - MSE: 34.2847, RMSE: 5.8553, MAE: 4.5863
Starting fold 5...
  Epoch 0... Train Loss: 4.0315, Val Loss: 18.8081
  Epoch 10... Train Loss: 0.5441, Val Loss: 0.9668
  Epoch 20... Train Loss: 0.4119, Val Loss: 0.7925
  Epoch 30... Train Loss: 0.3280, Val Loss: 0.9408

[INFO 04-02 10:11:53] ax.service.ax_client: Completed trial 68 with data: {'avg_rmse_nonzero': 5.482528}.

Fold 5 - MSE: 4.7346, RMSE: 2.1759, MAE: 1.7093

Mean CV MSE: 32.9207, Mean CV RMSE: 5.4825, Mean CV MAE: 3.6378
Completed trial 68 with mean RMSE: 5.4825 ± 0.8460
Saved Ax client checkpoint

[INFO 04-02 10:11:56] ax.service.ax_client: Generated new trial 69 with parameters {'dropout_rate': 0.0, 'weight_decay': 1e-06, 'lr': 1e-05, 'batch_size': 32, 'early_stopping_patience': 10, 'n_layers': 1, 'hidden1': 2048, 'hidden2': 64, 'hidden3': 512, 'activation': 'elu'} using model BoTorch.

Starting trial 69 with parameters: {'dropout_rate': 0.0, 'weight_decay': 1e-06, 'lr': 1e-05, 'batch_size': 32, 'early_stopping_patience': 10, 'n_layers': 1, 'hidden1': 2048, 'hidden2': 64, 'hidden3': 512, 'activation': 'elu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 0.8721, Val Loss: 0.7258
  Epoch 10... Train Loss: 0.4011, Val Loss: 0.3578
  Epoch 20... Train Loss: 0.3683, Val Loss: 0.3996
Fold 1 - MSE: 46.9590, RMSE: 6.8527, MAE: 4.8322
Starting fold 2...
  Epoch 0... Train Loss: 0.7830, Val Loss: 0.6950
  Epoch 10... Train Loss: 0.3775, Val Loss: 0.6163
  Epoch 20... Train Loss: 0.3261, Val Loss: 0.5431
  Epoch 30... Train Loss: 0.2687, Val Loss: 0.5518
Fold 2 - MSE: 83.5499, RMSE: 9.1406, MAE: 6.9163
Starting fold 3...
  Epoch 0... Train Loss: 0.9139, Val Loss: 0.7608
  Epoch 10... Train Loss: 0.3754, Val Loss: 0.4847
  Epoch 20... Train Loss: 0.3057, Val Loss: 0.4649
  Epoch 30... Train Loss: 0.2668, Val Loss: 0.4372
  Epoch 40... Train Loss: 0.2566, Val Loss: 0.4211
Fold 3 - MSE: 93.4707, RMSE: 9.6680, MAE: 5.7067
Starting fold 4...
  Epoch 0... Train Loss: 0.9152, Val Loss: 1.7193
  Epoch 10... Train Loss: 0.3274, Val Loss: 1.0945
  Epoch 20... Train Loss: 0.2617, Val Loss: 1.1264
Fold 4 - MSE: 38.1591, RMSE: 6.1773, MAE: 4.7147
Starting fold 5...
  Epoch 0... Train Loss: 0.8824, Val Loss: 1.4067
  Epoch 10... Train Loss: 0.3825, Val Loss: 0.9031
  Epoch 20... Train Loss: 0.3166, Val Loss: 0.8604

[INFO 04-02 10:12:06] ax.service.ax_client: Completed trial 69 with data: {'avg_rmse_nonzero': 8.31722}.

Fold 5 - MSE: 95.0146, RMSE: 9.7475, MAE: 8.8520

Mean CV MSE: 71.4307, Mean CV RMSE: 8.3172, Mean CV MAE: 6.2044
Completed trial 69 with mean RMSE: 8.3172 ± 0.7508
Saved Ax client checkpoint

[INFO 04-02 10:12:09] ax.service.ax_client: Generated new trial 70 with parameters {'dropout_rate': 0.491471, 'weight_decay': 1e-06, 'lr': 0.009657, 'batch_size': 256, 'early_stopping_patience': 31, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 128, 'hidden3': 512, 'activation': 'leaky_relu'} using model BoTorch.

Starting trial 70 with parameters: {'dropout_rate': 0.491470952236286, 'weight_decay': 1e-06, 'lr': 0.009656757376059047, 'batch_size': 256, 'early_stopping_patience': 31, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 128, 'hidden3': 512, 'activation': 'leaky_relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 6.4779, Val Loss: 2538.9480
  Epoch 10... Train Loss: 1.0870, Val Loss: 1.7606
  Epoch 20... Train Loss: 1.0068, Val Loss: 0.8732
  Epoch 30... Train Loss: 0.5708, Val Loss: 0.8115
  Epoch 40... Train Loss: 0.5094, Val Loss: 0.4405
  Epoch 50... Train Loss: 0.7701, Val Loss: 0.4555
  Epoch 60... Train Loss: 0.4575, Val Loss: 0.4105
  Epoch 70... Train Loss: 0.5964, Val Loss: 0.3816
  Epoch 80... Train Loss: 0.4635, Val Loss: 0.3625
  Epoch 90... Train Loss: 0.3999, Val Loss: 0.3608
  Epoch 100... Train Loss: 0.4429, Val Loss: 0.3163
  Epoch 110... Train Loss: 0.4292, Val Loss: 0.3220
  Epoch 120... Train Loss: 0.4750, Val Loss: 0.3239
  Epoch 130... Train Loss: 0.3221, Val Loss: 0.3385
  Epoch 140... Train Loss: 0.3909, Val Loss: 0.3162
Fold 1 - MSE: 38.6577, RMSE: 6.2175, MAE: 4.1011
Starting fold 2...
  Epoch 0... Train Loss: 10.1549, Val Loss: 5511.3867
  Epoch 10... Train Loss: 0.8176, Val Loss: 1.1731
  Epoch 20... Train Loss: 0.5436, Val Loss: 0.6645
  Epoch 30... Train Loss: 0.4449, Val Loss: 0.6308
  Epoch 40... Train Loss: 0.3468, Val Loss: 0.5662
  Epoch 50... Train Loss: 0.3029, Val Loss: 0.5034
  Epoch 60... Train Loss: 0.3333, Val Loss: 0.5112
  Epoch 70... Train Loss: 0.3256, Val Loss: 0.4828
  Epoch 80... Train Loss: 0.3223, Val Loss: 0.4484
  Epoch 90... Train Loss: 0.2823, Val Loss: 0.4387
  Epoch 100... Train Loss: 0.3053, Val Loss: 0.4177
  Epoch 110... Train Loss: 0.2632, Val Loss: 0.4275
  Epoch 120... Train Loss: 0.2434, Val Loss: 0.4300
  Epoch 130... Train Loss: 0.2590, Val Loss: 0.4184
Fold 2 - MSE: 38.5342, RMSE: 6.2076, MAE: 3.6401
Starting fold 3...
  Epoch 0... Train Loss: 9.0265, Val Loss: 10416.9199
  Epoch 10... Train Loss: 0.7367, Val Loss: 0.9195
  Epoch 20... Train Loss: 0.4614, Val Loss: 0.5821
  Epoch 30... Train Loss: 0.4286, Val Loss: 0.4950
  Epoch 40... Train Loss: 0.3402, Val Loss: 0.4651
  Epoch 50... Train Loss: 0.2986, Val Loss: 0.4381
  Epoch 60... Train Loss: 0.2564, Val Loss: 0.4032
  Epoch 70... Train Loss: 0.2559, Val Loss: 0.4231
  Epoch 80... Train Loss: 0.2253, Val Loss: 0.4003
  Epoch 90... Train Loss: 0.2347, Val Loss: 0.4189
  Epoch 100... Train Loss: 0.2109, Val Loss: 0.3860
  Epoch 110... Train Loss: 0.2194, Val Loss: 0.4078
  Epoch 120... Train Loss: 0.2292, Val Loss: 0.4063
  Epoch 130... Train Loss: 0.2338, Val Loss: 0.4033
Fold 3 - MSE: 26.0836, RMSE: 5.1072, MAE: 3.0774
Starting fold 4...
  Epoch 0... Train Loss: 8.6167, Val Loss: 4508.7495
  Epoch 10... Train Loss: 0.7648, Val Loss: 0.9125
  Epoch 20... Train Loss: 0.4561, Val Loss: 0.6033
  Epoch 30... Train Loss: 0.4016, Val Loss: 0.6066
  Epoch 40... Train Loss: 0.3427, Val Loss: 0.5311
  Epoch 50... Train Loss: 0.2742, Val Loss: 0.4893
  Epoch 60... Train Loss: 0.2537, Val Loss: 0.5447
  Epoch 70... Train Loss: 0.2223, Val Loss: 0.4652
  Epoch 80... Train Loss: 0.2281, Val Loss: 0.4945
  Epoch 90... Train Loss: 0.2049, Val Loss: 0.4524
Fold 4 - MSE: 30.3173, RMSE: 5.5061, MAE: 4.2980
Starting fold 5...
  Epoch 0... Train Loss: 6.6757, Val Loss: 2869.3167
  Epoch 10... Train Loss: 0.7465, Val Loss: 1.6363
  Epoch 20... Train Loss: 0.5298, Val Loss: 0.9795
  Epoch 30... Train Loss: 0.4133, Val Loss: 0.9010
  Epoch 40... Train Loss: 0.3688, Val Loss: 0.8319
  Epoch 50... Train Loss: 0.3062, Val Loss: 0.7957
  Epoch 60... Train Loss: 0.2780, Val Loss: 0.8098
  Epoch 70... Train Loss: 0.2893, Val Loss: 0.7857
  Epoch 80... Train Loss: 0.2603, Val Loss: 0.7583
  Epoch 90... Train Loss: 0.2416, Val Loss: 0.7436
  Epoch 100... Train Loss: 0.2639, Val Loss: 0.7401
  Epoch 110... Train Loss: 0.2478, Val Loss: 0.7612
  Epoch 120... Train Loss: 0.2261, Val Loss: 0.7431
Fold 5 - MSE: 6.0507, RMSE: 2.4598, MAE: 1.9450

Mean CV MSE: 27.9287, Mean CV RMSE: 5.0997, Mean CV MAE: 3.4123

[INFO 04-02 10:12:21] ax.service.ax_client: Completed trial 70 with data: {'avg_rmse_nonzero': 5.099653}.

Completed trial 70 with mean RMSE: 5.0997 ± 0.6932
Saved Ax client checkpoint

[INFO 04-02 10:12:24] ax.service.ax_client: Generated new trial 71 with parameters {'dropout_rate': 0.215482, 'weight_decay': 1e-06, 'lr': 0.006138, 'batch_size': 256, 'early_stopping_patience': 10, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 64, 'hidden3': 512, 'activation': 'leaky_relu'} using model BoTorch.

Starting trial 71 with parameters: {'dropout_rate': 0.2154821357881633, 'weight_decay': 1e-06, 'lr': 0.006137534782824582, 'batch_size': 256, 'early_stopping_patience': 10, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 64, 'hidden3': 512, 'activation': 'leaky_relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 2.5783, Val Loss: 1953.2843
  Epoch 10... Train Loss: 1.0896, Val Loss: 1.2642
  Epoch 20... Train Loss: 0.5396, Val Loss: 0.5933
  Epoch 30... Train Loss: 0.4080, Val Loss: 0.5953
  Epoch 40... Train Loss: 0.4311, Val Loss: 0.4585
  Epoch 50... Train Loss: 0.4649, Val Loss: 0.3961
  Epoch 60... Train Loss: 0.3535, Val Loss: 0.3917
  Epoch 70... Train Loss: 0.3759, Val Loss: 0.3855
Fold 1 - MSE: 40.9333, RMSE: 6.3979, MAE: 4.3326
Starting fold 2...
  Epoch 0... Train Loss: 10.6041, Val Loss: 3348.6177
  Epoch 10... Train Loss: 0.6837, Val Loss: 0.8483
  Epoch 20... Train Loss: 0.4504, Val Loss: 0.7029
  Epoch 30... Train Loss: 0.4194, Val Loss: 0.6338
  Epoch 40... Train Loss: 0.3208, Val Loss: 0.5393
  Epoch 50... Train Loss: 0.3257, Val Loss: 0.5015
  Epoch 60... Train Loss: 0.3162, Val Loss: 0.4701
Fold 2 - MSE: 34.0947, RMSE: 5.8391, MAE: 3.6277
Starting fold 3...
  Epoch 0... Train Loss: 7.9377, Val Loss: 971.2565
  Epoch 10... Train Loss: 0.6267, Val Loss: 0.7393
  Epoch 20... Train Loss: 0.3324, Val Loss: 0.5337
  Epoch 30... Train Loss: 0.2862, Val Loss: 0.3915
Fold 3 - MSE: 25.0990, RMSE: 5.0099, MAE: 3.2619
Starting fold 4...
  Epoch 0... Train Loss: 7.7920, Val Loss: 1747.3944
  Epoch 10... Train Loss: 0.7010, Val Loss: 0.8228
  Epoch 20... Train Loss: 0.3895, Val Loss: 0.5378
  Epoch 30... Train Loss: 0.2764, Val Loss: 0.5100
Fold 4 - MSE: 29.6565, RMSE: 5.4458, MAE: 4.3021
Starting fold 5...
  Epoch 0... Train Loss: 11.4445, Val Loss: 287.9906
  Epoch 10... Train Loss: 0.6410, Val Loss: 1.4145
  Epoch 20... Train Loss: 0.4611, Val Loss: 1.0330
  Epoch 30... Train Loss: 0.3405, Val Loss: 0.8912
  Epoch 40... Train Loss: 0.2763, Val Loss: 0.8475
  Epoch 50... Train Loss: 0.2856, Val Loss: 0.8155

[INFO 04-02 10:12:30] ax.service.ax_client: Completed trial 71 with data: {'avg_rmse_nonzero': 5.026237}.

  Epoch 60... Train Loss: 0.2434, Val Loss: 0.7958
Fold 5 - MSE: 5.9465, RMSE: 2.4385, MAE: 1.7832

Mean CV MSE: 27.1460, Mean CV RMSE: 5.0262, Mean CV MAE: 3.4615
Completed trial 71 with mean RMSE: 5.0262 ± 0.6861
Saved Ax client checkpoint

[INFO 04-02 10:12:34] ax.service.ax_client: Generated new trial 72 with parameters {'dropout_rate': 0.5, 'weight_decay': 1e-06, 'lr': 0.009416, 'batch_size': 256, 'early_stopping_patience': 10, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 64, 'hidden3': 512, 'activation': 'relu'} using model BoTorch.

Starting trial 72 with parameters: {'dropout_rate': 0.5, 'weight_decay': 1e-06, 'lr': 0.009415610578621324, 'batch_size': 256, 'early_stopping_patience': 10, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 64, 'hidden3': 512, 'activation': 'relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 4.9447, Val Loss: 332.4852
  Epoch 10... Train Loss: 0.9532, Val Loss: 1.1673
  Epoch 20... Train Loss: 0.8008, Val Loss: 0.5121
  Epoch 30... Train Loss: 0.4756, Val Loss: 0.4926
  Epoch 40... Train Loss: 0.4767, Val Loss: 0.4462
  Epoch 50... Train Loss: 0.5434, Val Loss: 0.3433
  Epoch 60... Train Loss: 0.4042, Val Loss: 0.3572
Fold 1 - MSE: 41.0700, RMSE: 6.4086, MAE: 4.1948
Starting fold 2...
  Epoch 0... Train Loss: 8.5408, Val Loss: 8341.7197
  Epoch 10... Train Loss: 0.8962, Val Loss: 0.8797
  Epoch 20... Train Loss: 0.5474, Val Loss: 0.6785
  Epoch 30... Train Loss: 0.4916, Val Loss: 0.6250
  Epoch 40... Train Loss: 0.4456, Val Loss: 0.6000
  Epoch 50... Train Loss: 0.4724, Val Loss: 0.5827
Fold 2 - MSE: 41.2223, RMSE: 6.4205, MAE: 3.9886
Starting fold 3...
  Epoch 0... Train Loss: 7.5767, Val Loss: 3390.2993
  Epoch 10... Train Loss: 0.7181, Val Loss: 0.8763
  Epoch 20... Train Loss: 0.4550, Val Loss: 0.5722
  Epoch 30... Train Loss: 0.3944, Val Loss: 0.5089
  Epoch 40... Train Loss: 0.3543, Val Loss: 0.4965
  Epoch 50... Train Loss: 0.3666, Val Loss: 0.4811
  Epoch 60... Train Loss: 0.3231, Val Loss: 0.4848
Fold 3 - MSE: 38.8435, RMSE: 6.2325, MAE: 3.5411
Starting fold 4...
  Epoch 0... Train Loss: 11.0571, Val Loss: 1828.9130
  Epoch 10... Train Loss: 0.8348, Val Loss: 0.7396
  Epoch 20... Train Loss: 0.5127, Val Loss: 0.6380
  Epoch 30... Train Loss: 0.4445, Val Loss: 0.5455
Fold 4 - MSE: 31.7122, RMSE: 5.6314, MAE: 4.4486
Starting fold 5...
  Epoch 0... Train Loss: 6.3938, Val Loss: 1043.0204
  Epoch 10... Train Loss: 0.7008, Val Loss: 1.1969
  Epoch 20... Train Loss: 0.4861, Val Loss: 0.9068
  Epoch 30... Train Loss: 0.3635, Val Loss: 0.8735
  Epoch 40... Train Loss: 0.3322, Val Loss: 0.7824
  Epoch 50... Train Loss: 0.3276, Val Loss: 0.7715

[INFO 04-02 10:12:40] ax.service.ax_client: Completed trial 72 with data: {'avg_rmse_nonzero': 5.375447}.

Fold 5 - MSE: 4.7715, RMSE: 2.1844, MAE: 1.6386

Mean CV MSE: 31.5239, Mean CV RMSE: 5.3754, Mean CV MAE: 3.5624
Completed trial 72 with mean RMSE: 5.3754 ± 0.8106
Saved Ax client checkpoint

[INFO 04-02 10:12:43] ax.service.ax_client: Generated new trial 73 with parameters {'dropout_rate': 0.011233, 'weight_decay': 1e-06, 'lr': 0.01, 'batch_size': 256, 'early_stopping_patience': 10, 'n_layers': 3, 'hidden1': 128, 'hidden2': 64, 'hidden3': 512, 'activation': 'leaky_relu'} using model BoTorch.

Starting trial 73 with parameters: {'dropout_rate': 0.01123281937782246, 'weight_decay': 1e-06, 'lr': 0.01, 'batch_size': 256, 'early_stopping_patience': 10, 'n_layers': 3, 'hidden1': 128, 'hidden2': 64, 'hidden3': 512, 'activation': 'leaky_relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 3.9396, Val Loss: 10027.3936
  Epoch 10... Train Loss: 0.8257, Val Loss: 1.2616
  Epoch 20... Train Loss: 0.5172, Val Loss: 0.4913
  Epoch 30... Train Loss: 0.3298, Val Loss: 0.4686
  Epoch 40... Train Loss: 0.3781, Val Loss: 0.4523
  Epoch 50... Train Loss: 0.4272, Val Loss: 0.3105
  Epoch 60... Train Loss: 0.3276, Val Loss: 0.3075
Fold 1 - MSE: 43.9715, RMSE: 6.6311, MAE: 4.4521
Starting fold 2...
  Epoch 0... Train Loss: 14.3109, Val Loss: 81.2929
  Epoch 10... Train Loss: 0.6489, Val Loss: 0.7166
  Epoch 20... Train Loss: 0.4155, Val Loss: 0.7299
  Epoch 30... Train Loss: 0.3861, Val Loss: 0.6963
  Epoch 40... Train Loss: 0.3784, Val Loss: 0.6647
  Epoch 50... Train Loss: 0.3895, Val Loss: 0.6425
  Epoch 60... Train Loss: 0.4119, Val Loss: 0.6164
Fold 2 - MSE: 36.3476, RMSE: 6.0289, MAE: 3.5317
Starting fold 3...
  Epoch 0... Train Loss: 7.4362, Val Loss: 4853.5288
  Epoch 10... Train Loss: 0.6706, Val Loss: 1.4236
  Epoch 20... Train Loss: 0.4086, Val Loss: 0.5846
  Epoch 30... Train Loss: 0.3086, Val Loss: 0.4865
  Epoch 40... Train Loss: 0.2188, Val Loss: 0.4218
  Epoch 50... Train Loss: 0.1904, Val Loss: 0.4276
Fold 3 - MSE: 27.4318, RMSE: 5.2375, MAE: 3.2697
Starting fold 4...
  Epoch 0... Train Loss: 13.0763, Val Loss: 629.9008
  Epoch 10... Train Loss: 0.6898, Val Loss: 0.9157
  Epoch 20... Train Loss: 0.4119, Val Loss: 0.5906
Fold 4 - MSE: 32.9422, RMSE: 5.7395, MAE: 4.5717
Starting fold 5...
  Epoch 0... Train Loss: 9.1359, Val Loss: 10946.9277
  Epoch 10... Train Loss: 0.6793, Val Loss: 1.5232
  Epoch 20... Train Loss: 0.4844, Val Loss: 1.1524
  Epoch 30... Train Loss: 0.3582, Val Loss: 0.9959
  Epoch 40... Train Loss: 0.2983, Val Loss: 0.8156
  Epoch 50... Train Loss: 0.2149, Val Loss: 0.7796
  Epoch 60... Train Loss: 0.1944, Val Loss: 0.7723

[INFO 04-02 10:12:49] ax.service.ax_client: Completed trial 73 with data: {'avg_rmse_nonzero': 5.802339}.

  Epoch 70... Train Loss: 0.2000, Val Loss: 0.7549
Fold 5 - MSE: 28.8865, RMSE: 5.3746, MAE: 4.0725

Mean CV MSE: 33.9160, Mean CV RMSE: 5.8023, Mean CV MAE: 3.9796
Completed trial 73 with mean RMSE: 5.8023 ± 0.2494
Saved Ax client checkpoint

[INFO 04-02 10:12:52] ax.service.ax_client: Generated new trial 74 with parameters {'dropout_rate': 0.496054, 'weight_decay': 2.3e-05, 'lr': 0.005785, 'batch_size': 256, 'early_stopping_patience': 49, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 512, 'hidden3': 512, 'activation': 'relu'} using model BoTorch.

Starting trial 74 with parameters: {'dropout_rate': 0.496054272366784, 'weight_decay': 2.3350269733858088e-05, 'lr': 0.005784750208603954, 'batch_size': 256, 'early_stopping_patience': 49, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 512, 'hidden3': 512, 'activation': 'relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 2.0043, Val Loss: 68.4097
  Epoch 10... Train Loss: 1.0242, Val Loss: 0.8543
  Epoch 20... Train Loss: 0.5644, Val Loss: 0.5106
  Epoch 30... Train Loss: 0.5254, Val Loss: 0.4833
  Epoch 40... Train Loss: 0.4469, Val Loss: 0.3837
  Epoch 50... Train Loss: 0.5416, Val Loss: 0.3559
  Epoch 60... Train Loss: 0.4429, Val Loss: 0.3020
  Epoch 70... Train Loss: 0.3267, Val Loss: 0.3544
  Epoch 80... Train Loss: 0.3896, Val Loss: 0.3270
  Epoch 90... Train Loss: 0.3486, Val Loss: 0.3773
  Epoch 100... Train Loss: 0.3328, Val Loss: 0.3083
  Epoch 110... Train Loss: 0.4131, Val Loss: 0.3019
Fold 1 - MSE: 38.1559, RMSE: 6.1770, MAE: 4.0118
Starting fold 2...
  Epoch 0... Train Loss: 8.9090, Val Loss: 1023.4083
  Epoch 10... Train Loss: 0.7138, Val Loss: 0.8084
  Epoch 20... Train Loss: 0.4687, Val Loss: 0.6289
  Epoch 30... Train Loss: 0.3856, Val Loss: 0.5347
  Epoch 40... Train Loss: 0.3031, Val Loss: 0.4564
  Epoch 50... Train Loss: 0.3208, Val Loss: 0.4703
  Epoch 60... Train Loss: 0.3145, Val Loss: 0.4417
  Epoch 70... Train Loss: 0.3315, Val Loss: 0.4366
  Epoch 80... Train Loss: 0.3191, Val Loss: 0.4935
  Epoch 90... Train Loss: 0.2975, Val Loss: 0.4134
  Epoch 100... Train Loss: 0.2574, Val Loss: 0.4052
  Epoch 110... Train Loss: 0.2401, Val Loss: 0.4343
  Epoch 120... Train Loss: 0.2079, Val Loss: 0.3991
  Epoch 130... Train Loss: 0.2237, Val Loss: 0.3919
  Epoch 140... Train Loss: 0.2137, Val Loss: 0.3601
  Epoch 150... Train Loss: 0.2680, Val Loss: 0.3777
  Epoch 160... Train Loss: 0.2278, Val Loss: 0.3606
  Epoch 170... Train Loss: 0.2330, Val Loss: 0.3668
  Epoch 180... Train Loss: 0.1948, Val Loss: 0.3745
  Epoch 190... Train Loss: 0.1910, Val Loss: 0.3872
  Epoch 200... Train Loss: 0.1940, Val Loss: 0.3838
Fold 2 - MSE: 34.4066, RMSE: 5.8657, MAE: 3.5696
Starting fold 3...
  Epoch 0... Train Loss: 4.9879, Val Loss: 146.2060
  Epoch 10... Train Loss: 0.5714, Val Loss: 0.6878
  Epoch 20... Train Loss: 0.3830, Val Loss: 0.5122
  Epoch 30... Train Loss: 0.3541, Val Loss: 0.5245
  Epoch 40... Train Loss: 0.3024, Val Loss: 0.4569
  Epoch 50... Train Loss: 0.2637, Val Loss: 0.4383
  Epoch 60... Train Loss: 0.2333, Val Loss: 0.4327
  Epoch 70... Train Loss: 0.2590, Val Loss: 0.3867
  Epoch 80... Train Loss: 0.2453, Val Loss: 0.4188
  Epoch 90... Train Loss: 0.2232, Val Loss: 0.4137
  Epoch 100... Train Loss: 0.2322, Val Loss: 0.3837
  Epoch 110... Train Loss: 0.2270, Val Loss: 0.3951
  Epoch 120... Train Loss: 0.2167, Val Loss: 0.3740
  Epoch 130... Train Loss: 0.1824, Val Loss: 0.3742
  Epoch 140... Train Loss: 0.1908, Val Loss: 0.3740
  Epoch 150... Train Loss: 0.2080, Val Loss: 0.3565
  Epoch 160... Train Loss: 0.1967, Val Loss: 0.3745
  Epoch 170... Train Loss: 0.2125, Val Loss: 0.3641
  Epoch 180... Train Loss: 0.1993, Val Loss: 0.3727
  Epoch 190... Train Loss: 0.1677, Val Loss: 0.3720
Fold 3 - MSE: 50.5877, RMSE: 7.1125, MAE: 3.8007
Starting fold 4...
  Epoch 0... Train Loss: 6.7053, Val Loss: 726.8246
  Epoch 10... Train Loss: 0.6898, Val Loss: 0.6921
  Epoch 20... Train Loss: 0.4135, Val Loss: 0.5388
  Epoch 30... Train Loss: 0.2808, Val Loss: 0.5406
  Epoch 40... Train Loss: 0.3025, Val Loss: 0.5131
  Epoch 50... Train Loss: 0.2354, Val Loss: 0.4630
  Epoch 60... Train Loss: 0.2326, Val Loss: 0.4462
  Epoch 70... Train Loss: 0.2109, Val Loss: 0.4217
  Epoch 80... Train Loss: 0.2109, Val Loss: 0.4683
  Epoch 90... Train Loss: 0.2177, Val Loss: 0.4283
  Epoch 100... Train Loss: 0.1940, Val Loss: 0.3992
  Epoch 110... Train Loss: 0.1766, Val Loss: 0.4321
  Epoch 120... Train Loss: 0.1948, Val Loss: 0.4177
  Epoch 130... Train Loss: 0.1857, Val Loss: 0.4138
  Epoch 140... Train Loss: 0.1945, Val Loss: 0.4317
Fold 4 - MSE: 31.0097, RMSE: 5.5686, MAE: 4.1911
Starting fold 5...
  Epoch 0... Train Loss: 4.3482, Val Loss: 107.8411
  Epoch 10... Train Loss: 0.6478, Val Loss: 1.0838
  Epoch 20... Train Loss: 0.4377, Val Loss: 0.9072
  Epoch 30... Train Loss: 0.3370, Val Loss: 0.8525
  Epoch 40... Train Loss: 0.3566, Val Loss: 0.8480
  Epoch 50... Train Loss: 0.3104, Val Loss: 0.7747
  Epoch 60... Train Loss: 0.2631, Val Loss: 0.8071
  Epoch 70... Train Loss: 0.2959, Val Loss: 0.7974
  Epoch 80... Train Loss: 0.2719, Val Loss: 0.7281
  Epoch 90... Train Loss: 0.2658, Val Loss: 0.7460
  Epoch 100... Train Loss: 0.2696, Val Loss: 0.7556
  Epoch 110... Train Loss: 0.2460, Val Loss: 0.7602
  Epoch 120... Train Loss: 0.2380, Val Loss: 0.7603
  Epoch 130... Train Loss: 0.2597, Val Loss: 0.7114
  Epoch 140... Train Loss: 0.2304, Val Loss: 0.7250
  Epoch 150... Train Loss: 0.2153, Val Loss: 0.7067
  Epoch 160... Train Loss: 0.2335, Val Loss: 0.7153
  Epoch 170... Train Loss: 0.2300, Val Loss: 0.6989
  Epoch 180... Train Loss: 0.2199, Val Loss: 0.7071
  Epoch 190... Train Loss: 0.1985, Val Loss: 0.7051
  Epoch 200... Train Loss: 0.1814, Val Loss: 0.7056

[INFO 04-02 10:13:07] ax.service.ax_client: Completed trial 74 with data: {'avg_rmse_nonzero': 5.479182}.

  Epoch 210... Train Loss: 0.1931, Val Loss: 0.7007
  Epoch 220... Train Loss: 0.2022, Val Loss: 0.7056
Fold 5 - MSE: 7.1396, RMSE: 2.6720, MAE: 2.2074

Mean CV MSE: 32.2599, Mean CV RMSE: 5.4792, Mean CV MAE: 3.5561
Completed trial 74 with mean RMSE: 5.4792 ± 0.7481
Saved Ax client checkpoint

[INFO 04-02 10:13:09] ax.service.ax_client: Generated new trial 75 with parameters {'dropout_rate': 0.342459, 'weight_decay': 1e-06, 'lr': 0.005529, 'batch_size': 256, 'early_stopping_patience': 45, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 128, 'hidden3': 32, 'activation': 'relu'} using model BoTorch.

Starting trial 75 with parameters: {'dropout_rate': 0.3424589507438683, 'weight_decay': 1e-06, 'lr': 0.0055290293995103185, 'batch_size': 256, 'early_stopping_patience': 45, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 128, 'hidden3': 32, 'activation': 'relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 5.2288, Val Loss: 263.0857
  Epoch 10... Train Loss: 0.9124, Val Loss: 0.8868
  Epoch 20... Train Loss: 0.5038, Val Loss: 0.4773
  Epoch 30... Train Loss: 0.4026, Val Loss: 0.4599
  Epoch 40... Train Loss: 0.3850, Val Loss: 0.3140
  Epoch 50... Train Loss: 0.4785, Val Loss: 0.3891
  Epoch 60... Train Loss: 0.3942, Val Loss: 0.2984
  Epoch 70... Train Loss: 0.3867, Val Loss: 0.3440
  Epoch 80... Train Loss: 0.4135, Val Loss: 0.3095
  Epoch 90... Train Loss: 0.2665, Val Loss: 0.2661
  Epoch 100... Train Loss: 0.3553, Val Loss: 0.2999
  Epoch 110... Train Loss: 0.3207, Val Loss: 0.2913
  Epoch 120... Train Loss: 0.3919, Val Loss: 0.2846
  Epoch 130... Train Loss: 0.2727, Val Loss: 0.2869
Fold 1 - MSE: 38.8993, RMSE: 6.2369, MAE: 4.0730
Starting fold 2...
  Epoch 0... Train Loss: 10.0972, Val Loss: 3706.2205
  Epoch 10... Train Loss: 0.6649, Val Loss: 0.7616
  Epoch 20... Train Loss: 0.4138, Val Loss: 0.6673
  Epoch 30... Train Loss: 0.3657, Val Loss: 0.4751
  Epoch 40... Train Loss: 0.2709, Val Loss: 0.4614
  Epoch 50... Train Loss: 0.2731, Val Loss: 0.4095
  Epoch 60... Train Loss: 0.2880, Val Loss: 0.4652
  Epoch 70... Train Loss: 0.2601, Val Loss: 0.3821
  Epoch 80... Train Loss: 0.2529, Val Loss: 0.4144
  Epoch 90... Train Loss: 0.2342, Val Loss: 0.3552
  Epoch 100... Train Loss: 0.2017, Val Loss: 0.3910
  Epoch 110... Train Loss: 0.1913, Val Loss: 0.3725
  Epoch 120... Train Loss: 0.2177, Val Loss: 0.3683
Fold 2 - MSE: 40.8489, RMSE: 6.3913, MAE: 3.9791
Starting fold 3...
  Epoch 0... Train Loss: 9.5843, Val Loss: 3043.1797
  Epoch 10... Train Loss: 0.6728, Val Loss: 0.8978
  Epoch 20... Train Loss: 0.4454, Val Loss: 0.5562
  Epoch 30... Train Loss: 0.3511, Val Loss: 0.4959
  Epoch 40... Train Loss: 0.2716, Val Loss: 0.4617
  Epoch 50... Train Loss: 0.2641, Val Loss: 0.4520
  Epoch 60... Train Loss: 0.2253, Val Loss: 0.4310
  Epoch 70... Train Loss: 0.2172, Val Loss: 0.4402
  Epoch 80... Train Loss: 0.2173, Val Loss: 0.4205
  Epoch 90... Train Loss: 0.2139, Val Loss: 0.4321
  Epoch 100... Train Loss: 0.2333, Val Loss: 0.4338
  Epoch 110... Train Loss: 0.2103, Val Loss: 0.4131
  Epoch 120... Train Loss: 0.2215, Val Loss: 0.4157
  Epoch 130... Train Loss: 0.1732, Val Loss: 0.4067
  Epoch 140... Train Loss: 0.2163, Val Loss: 0.4127
Fold 3 - MSE: 23.3274, RMSE: 4.8298, MAE: 2.9685
Starting fold 4...
  Epoch 0... Train Loss: 7.8419, Val Loss: 2178.4346
  Epoch 10... Train Loss: 0.6987, Val Loss: 0.5880
  Epoch 20... Train Loss: 0.3623, Val Loss: 0.5113
  Epoch 30... Train Loss: 0.3281, Val Loss: 0.5043
  Epoch 40... Train Loss: 0.2532, Val Loss: 0.4701
  Epoch 50... Train Loss: 0.2243, Val Loss: 0.4354
  Epoch 60... Train Loss: 0.2068, Val Loss: 0.4813
  Epoch 70... Train Loss: 0.1932, Val Loss: 0.4613
  Epoch 80... Train Loss: 0.1825, Val Loss: 0.4670
  Epoch 90... Train Loss: 0.1696, Val Loss: 0.4381
Fold 4 - MSE: 30.2776, RMSE: 5.5025, MAE: 4.2297
Starting fold 5...
  Epoch 0... Train Loss: 7.5006, Val Loss: 293.1046
  Epoch 10... Train Loss: 0.6826, Val Loss: 1.4370
  Epoch 20... Train Loss: 0.5221, Val Loss: 1.0972
  Epoch 30... Train Loss: 0.3524, Val Loss: 0.8733
  Epoch 40... Train Loss: 0.2923, Val Loss: 0.8330
  Epoch 50... Train Loss: 0.2788, Val Loss: 0.8276
  Epoch 60... Train Loss: 0.2488, Val Loss: 0.7612
  Epoch 70... Train Loss: 0.2400, Val Loss: 0.7725
  Epoch 80... Train Loss: 0.2337, Val Loss: 0.7439
  Epoch 90... Train Loss: 0.2274, Val Loss: 0.7425
  Epoch 100... Train Loss: 0.2287, Val Loss: 0.7383
  Epoch 110... Train Loss: 0.2057, Val Loss: 0.7613
  Epoch 120... Train Loss: 0.2096, Val Loss: 0.7465

[INFO 04-02 10:13:19] ax.service.ax_client: Completed trial 75 with data: {'avg_rmse_nonzero': 5.049218}.

  Epoch 130... Train Loss: 0.2341, Val Loss: 0.7344
Fold 5 - MSE: 5.2235, RMSE: 2.2855, MAE: 1.7644

Mean CV MSE: 27.7153, Mean CV RMSE: 5.0492, Mean CV MAE: 3.4029
Completed trial 75 with mean RMSE: 5.0492 ± 0.7451
Saved Ax client checkpoint

[INFO 04-02 10:13:22] ax.service.ax_client: Generated new trial 76 with parameters {'dropout_rate': 0.364684, 'weight_decay': 1e-06, 'lr': 0.005356, 'batch_size': 256, 'early_stopping_patience': 10, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 256, 'activation': 'relu'} using model BoTorch.

Starting trial 76 with parameters: {'dropout_rate': 0.3646843518208192, 'weight_decay': 1e-06, 'lr': 0.005355517490147647, 'batch_size': 256, 'early_stopping_patience': 10, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 256, 'activation': 'relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 3.9394, Val Loss: 298.5168
  Epoch 10... Train Loss: 0.8528, Val Loss: 1.0433
  Epoch 20... Train Loss: 0.5326, Val Loss: 0.4815
  Epoch 30... Train Loss: 0.4286, Val Loss: 0.4502
  Epoch 40... Train Loss: 0.4172, Val Loss: 0.3953
  Epoch 50... Train Loss: 0.4673, Val Loss: 0.3613
  Epoch 60... Train Loss: 0.3720, Val Loss: 0.3436
  Epoch 70... Train Loss: 0.3451, Val Loss: 0.3377
Fold 1 - MSE: 43.4227, RMSE: 6.5896, MAE: 4.3343
Starting fold 2...
  Epoch 0... Train Loss: 10.3509, Val Loss: 502.7872
  Epoch 10... Train Loss: 0.7051, Val Loss: 0.7477
  Epoch 20... Train Loss: 0.4422, Val Loss: 0.6606
  Epoch 30... Train Loss: 0.3661, Val Loss: 0.5421
  Epoch 40... Train Loss: 0.2921, Val Loss: 0.4897
  Epoch 50... Train Loss: 0.3465, Val Loss: 0.4778
Fold 2 - MSE: 36.4831, RMSE: 6.0401, MAE: 3.4894
Starting fold 3...
  Epoch 0... Train Loss: 7.9352, Val Loss: 2856.4944
  Epoch 10... Train Loss: 0.6372, Val Loss: 0.7294
  Epoch 20... Train Loss: 0.3770, Val Loss: 0.5788
  Epoch 30... Train Loss: 0.3040, Val Loss: 0.4718
  Epoch 40... Train Loss: 0.2542, Val Loss: 0.4513
Fold 3 - MSE: 20.0237, RMSE: 4.4748, MAE: 2.9698
Starting fold 4...
  Epoch 0... Train Loss: 7.3796, Val Loss: 666.5077
  Epoch 10... Train Loss: 0.7007, Val Loss: 0.6405
  Epoch 20... Train Loss: 0.4095, Val Loss: 0.6164
  Epoch 30... Train Loss: 0.3091, Val Loss: 0.5044
  Epoch 40... Train Loss: 0.2750, Val Loss: 0.4963
Fold 4 - MSE: 33.1648, RMSE: 5.7589, MAE: 4.5760
Starting fold 5...
  Epoch 0... Train Loss: 5.1295, Val Loss: 154.9264
  Epoch 10... Train Loss: 0.5969, Val Loss: 1.2791
  Epoch 20... Train Loss: 0.3962, Val Loss: 0.8998
  Epoch 30... Train Loss: 0.3096, Val Loss: 0.8648
  Epoch 40... Train Loss: 0.2964, Val Loss: 0.8279
  Epoch 50... Train Loss: 0.2759, Val Loss: 0.8008
  Epoch 60... Train Loss: 0.2422, Val Loss: 0.8017
Fold 5 - MSE: 6.4561, RMSE: 2.5409, MAE: 1.8051

Mean CV MSE: 27.9101, Mean CV RMSE: 5.0809, Mean CV MAE: 3.4349

[INFO 04-02 10:13:27] ax.service.ax_client: Completed trial 76 with data: {'avg_rmse_nonzero': 5.080854}.

Completed trial 76 with mean RMSE: 5.0809 ± 0.7237
Saved Ax client checkpoint

[INFO 04-02 10:13:30] ax.service.ax_client: Generated new trial 77 with parameters {'dropout_rate': 0.439207, 'weight_decay': 0.006754, 'lr': 0.004706, 'batch_size': 256, 'early_stopping_patience': 41, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 64, 'hidden3': 32, 'activation': 'relu'} using model BoTorch.

Starting trial 77 with parameters: {'dropout_rate': 0.4392066986048777, 'weight_decay': 0.006753840584656211, 'lr': 0.004705811028588585, 'batch_size': 256, 'early_stopping_patience': 41, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 64, 'hidden3': 32, 'activation': 'relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 1.2540, Val Loss: 14.1181
  Epoch 10... Train Loss: 0.7812, Val Loss: 0.9156
  Epoch 20... Train Loss: 0.5300, Val Loss: 0.5316
  Epoch 30... Train Loss: 0.3952, Val Loss: 0.6850
  Epoch 40... Train Loss: 0.3944, Val Loss: 0.4328
  Epoch 50... Train Loss: 0.4310, Val Loss: 0.5985
  Epoch 60... Train Loss: 0.3939, Val Loss: 0.3800
  Epoch 70... Train Loss: 0.3359, Val Loss: 0.4470
  Epoch 80... Train Loss: 0.3817, Val Loss: 0.3566
  Epoch 90... Train Loss: 0.3407, Val Loss: 0.3738
  Epoch 100... Train Loss: 0.3279, Val Loss: 0.3138
  Epoch 110... Train Loss: 0.3563, Val Loss: 0.3583
  Epoch 120... Train Loss: 0.4459, Val Loss: 0.3445
  Epoch 130... Train Loss: 0.3140, Val Loss: 0.2841
  Epoch 140... Train Loss: 0.3827, Val Loss: 0.2652
  Epoch 150... Train Loss: 0.4139, Val Loss: 0.3022
  Epoch 160... Train Loss: 0.2826, Val Loss: 0.2798
  Epoch 170... Train Loss: 0.3004, Val Loss: 0.2917
  Epoch 180... Train Loss: 0.3325, Val Loss: 0.2777
Fold 1 - MSE: 39.7286, RMSE: 6.3031, MAE: 4.0671
Starting fold 2...
  Epoch 0... Train Loss: 8.7662, Val Loss: 410.3737
  Epoch 10... Train Loss: 0.6782, Val Loss: 0.6750
  Epoch 20... Train Loss: 0.3341, Val Loss: 0.7710
  Epoch 30... Train Loss: 0.3947, Val Loss: 0.5012
  Epoch 40... Train Loss: 0.3254, Val Loss: 0.5338
  Epoch 50... Train Loss: 0.3371, Val Loss: 0.4466
  Epoch 60... Train Loss: 0.3854, Val Loss: 0.5039
  Epoch 70... Train Loss: 0.3593, Val Loss: 0.4394
  Epoch 80... Train Loss: 0.3106, Val Loss: 0.5357
  Epoch 90... Train Loss: 0.2823, Val Loss: 0.4533
  Epoch 100... Train Loss: 0.2394, Val Loss: 0.4057
Fold 2 - MSE: 35.1962, RMSE: 5.9326, MAE: 3.4806
Starting fold 3...
  Epoch 0... Train Loss: 7.2954, Val Loss: 1257.6426
  Epoch 10... Train Loss: 0.5998, Val Loss: 0.6461
  Epoch 20... Train Loss: 0.3720, Val Loss: 0.6618
  Epoch 30... Train Loss: 0.3897, Val Loss: 0.5269
  Epoch 40... Train Loss: 0.3599, Val Loss: 0.5221
  Epoch 50... Train Loss: 0.3143, Val Loss: 0.5481
  Epoch 60... Train Loss: 0.3269, Val Loss: 0.4731
  Epoch 70... Train Loss: 0.2818, Val Loss: 0.5713
  Epoch 80... Train Loss: 0.2699, Val Loss: 0.4226
  Epoch 90... Train Loss: 0.2831, Val Loss: 0.3720
  Epoch 100... Train Loss: 0.3186, Val Loss: 0.4032
  Epoch 110... Train Loss: 0.2510, Val Loss: 0.3863
  Epoch 120... Train Loss: 0.2261, Val Loss: 0.3737
  Epoch 130... Train Loss: 0.2214, Val Loss: 0.3147
  Epoch 140... Train Loss: 0.2035, Val Loss: 0.3288
Fold 3 - MSE: 48.9726, RMSE: 6.9980, MAE: 4.5960
Starting fold 4...
  Epoch 0... Train Loss: 4.7451, Val Loss: 29.2786
  Epoch 10... Train Loss: 0.5833, Val Loss: 0.5161
  Epoch 20... Train Loss: 0.2828, Val Loss: 0.4554
  Epoch 30... Train Loss: 0.3359, Val Loss: 0.4400
  Epoch 40... Train Loss: 0.2811, Val Loss: 0.4316
  Epoch 50... Train Loss: 0.2549, Val Loss: 0.3720
  Epoch 60... Train Loss: 0.2589, Val Loss: 0.4527
  Epoch 70... Train Loss: 0.1899, Val Loss: 0.3862
  Epoch 80... Train Loss: 0.2526, Val Loss: 0.3850
  Epoch 90... Train Loss: 0.1949, Val Loss: 0.4070
  Epoch 100... Train Loss: 0.1822, Val Loss: 0.4099
  Epoch 110... Train Loss: 0.1512, Val Loss: 0.4242
Fold 4 - MSE: 29.5458, RMSE: 5.4356, MAE: 4.2308
Starting fold 5...
  Epoch 0... Train Loss: 6.1559, Val Loss: 71.3643
  Epoch 10... Train Loss: 0.5930, Val Loss: 1.0877
  Epoch 20... Train Loss: 0.4218, Val Loss: 1.0117
  Epoch 30... Train Loss: 0.4089, Val Loss: 1.0021
  Epoch 40... Train Loss: 0.3502, Val Loss: 0.8684
  Epoch 50... Train Loss: 0.3617, Val Loss: 0.8912
  Epoch 60... Train Loss: 0.2904, Val Loss: 0.8524
  Epoch 70... Train Loss: 0.3017, Val Loss: 0.7363
  Epoch 80... Train Loss: 0.2908, Val Loss: 0.7206

[INFO 04-02 10:13:40] ax.service.ax_client: Completed trial 77 with data: {'avg_rmse_nonzero': 5.413809}.

  Epoch 90... Train Loss: 0.2415, Val Loss: 0.8024
Fold 5 - MSE: 5.7586, RMSE: 2.3997, MAE: 1.8975

Mean CV MSE: 31.8403, Mean CV RMSE: 5.4138, Mean CV MAE: 3.6544
Completed trial 77 with mean RMSE: 5.4138 ± 0.7955
Saved Ax client checkpoint

[INFO 04-02 10:13:42] ax.service.ax_client: Generated new trial 78 with parameters {'dropout_rate': 0.5, 'weight_decay': 1e-06, 'lr': 0.01, 'batch_size': 32, 'early_stopping_patience': 10, 'n_layers': 3, 'hidden1': 256, 'hidden2': 1024, 'hidden3': 32, 'activation': 'relu'} using model BoTorch.

Starting trial 78 with parameters: {'dropout_rate': 0.5, 'weight_decay': 1e-06, 'lr': 0.01, 'batch_size': 32, 'early_stopping_patience': 10, 'n_layers': 3, 'hidden1': 256, 'hidden2': 1024, 'hidden3': 32, 'activation': 'relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 2.6661, Val Loss: 141.0168
  Epoch 10... Train Loss: 0.6632, Val Loss: 0.5333
  Epoch 20... Train Loss: 0.5227, Val Loss: 0.3254
  Epoch 30... Train Loss: 0.4658, Val Loss: 0.2865
  Epoch 40... Train Loss: 0.4241, Val Loss: 0.2833
Fold 1 - MSE: 41.3637, RMSE: 6.4315, MAE: 4.2667
Starting fold 2...
  Epoch 0... Train Loss: 2.2353, Val Loss: 9.2924
  Epoch 10... Train Loss: 0.7568, Val Loss: 0.9125
  Epoch 20... Train Loss: 0.4163, Val Loss: 0.4285
  Epoch 30... Train Loss: 0.3818, Val Loss: 0.4544
Fold 2 - MSE: 36.3456, RMSE: 6.0287, MAE: 3.4945
Starting fold 3...
  Epoch 0... Train Loss: 1.8067, Val Loss: 1.0979
  Epoch 10... Train Loss: 0.6235, Val Loss: 0.5359
  Epoch 20... Train Loss: 0.5338, Val Loss: 0.4898
  Epoch 30... Train Loss: 0.3694, Val Loss: 0.4620
  Epoch 40... Train Loss: 0.2855, Val Loss: 0.3955
  Epoch 50... Train Loss: 0.2779, Val Loss: 0.4112
Fold 3 - MSE: 25.6588, RMSE: 5.0655, MAE: 3.2846
Starting fold 4...
  Epoch 0... Train Loss: 2.0224, Val Loss: 1.1805
  Epoch 10... Train Loss: 0.6627, Val Loss: 0.6589
  Epoch 20... Train Loss: 0.3471, Val Loss: 0.4679
  Epoch 30... Train Loss: 0.3057, Val Loss: 0.4870
Fold 4 - MSE: 37.8713, RMSE: 6.1540, MAE: 5.0535
Starting fold 5...
  Epoch 0... Train Loss: 1.7541, Val Loss: 2.3263
  Epoch 10... Train Loss: 0.5667, Val Loss: 1.0197
  Epoch 20... Train Loss: 0.4154, Val Loss: 0.8078
  Epoch 30... Train Loss: 0.3326, Val Loss: 0.7409

[INFO 04-02 10:13:58] ax.service.ax_client: Completed trial 78 with data: {'avg_rmse_nonzero': 5.249104}.

  Epoch 40... Train Loss: 0.3179, Val Loss: 0.7961
Fold 5 - MSE: 6.5839, RMSE: 2.5659, MAE: 2.1188

Mean CV MSE: 29.5647, Mean CV RMSE: 5.2491, Mean CV MAE: 3.6436
Completed trial 78 with mean RMSE: 5.2491 ± 0.7091
Saved Ax client checkpoint

[INFO 04-02 10:14:01] ax.service.ax_client: Generated new trial 79 with parameters {'dropout_rate': 0.479717, 'weight_decay': 0.01, 'lr': 0.0033, 'batch_size': 32, 'early_stopping_patience': 10, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 64, 'hidden3': 512, 'activation': 'relu'} using model BoTorch.

Starting trial 79 with parameters: {'dropout_rate': 0.4797171700608929, 'weight_decay': 0.01, 'lr': 0.003300438187690365, 'batch_size': 32, 'early_stopping_patience': 10, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 64, 'hidden3': 512, 'activation': 'relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 1.6169, Val Loss: 21.2258
  Epoch 10... Train Loss: 0.5741, Val Loss: 0.4753
  Epoch 20... Train Loss: 0.4717, Val Loss: 0.4175
Fold 1 - MSE: 43.8719, RMSE: 6.6236, MAE: 4.3995
Starting fold 2...
  Epoch 0... Train Loss: 1.6250, Val Loss: 5.1248
  Epoch 10... Train Loss: 0.6563, Val Loss: 0.6210
  Epoch 20... Train Loss: 0.4555, Val Loss: 0.4975
  Epoch 30... Train Loss: 0.4095, Val Loss: 0.4389
  Epoch 40... Train Loss: 0.3564, Val Loss: 0.4281
Fold 2 - MSE: 40.7951, RMSE: 6.3871, MAE: 3.7762
Starting fold 3...
  Epoch 0... Train Loss: 1.4154, Val Loss: 2.3699
  Epoch 10... Train Loss: 0.6252, Val Loss: 0.8527
  Epoch 20... Train Loss: 0.4957, Val Loss: 0.5053
  Epoch 30... Train Loss: 0.3999, Val Loss: 0.5536
  Epoch 40... Train Loss: 0.3363, Val Loss: 0.4077
  Epoch 50... Train Loss: 0.3245, Val Loss: 0.4210
  Epoch 60... Train Loss: 0.2957, Val Loss: 0.4042
Fold 3 - MSE: 114.7485, RMSE: 10.7121, MAE: 4.9201
Starting fold 4...
  Epoch 0... Train Loss: 1.3194, Val Loss: 2.0265
  Epoch 10... Train Loss: 0.5403, Val Loss: 0.4514
  Epoch 20... Train Loss: 0.4364, Val Loss: 0.4743
Fold 4 - MSE: 27.9266, RMSE: 5.2846, MAE: 4.1238
Starting fold 5...
  Epoch 0... Train Loss: 1.6124, Val Loss: 1.9095
  Epoch 10... Train Loss: 0.5373, Val Loss: 0.8915
  Epoch 20... Train Loss: 0.4678, Val Loss: 0.7461
  Epoch 30... Train Loss: 0.3717, Val Loss: 0.8357
  Epoch 40... Train Loss: 0.3524, Val Loss: 0.7865
  Epoch 50... Train Loss: 0.2972, Val Loss: 0.8675
  Epoch 60... Train Loss: 0.2972, Val Loss: 0.7079
  Epoch 70... Train Loss: 0.2873, Val Loss: 0.7191

[INFO 04-02 10:14:19] ax.service.ax_client: Completed trial 79 with data: {'avg_rmse_nonzero': 7.044921}.

Fold 5 - MSE: 38.6546, RMSE: 6.2173, MAE: 5.6509

Mean CV MSE: 53.1993, Mean CV RMSE: 7.0449, Mean CV MAE: 4.5741
Completed trial 79 with mean RMSE: 7.0449 ± 0.9445
Saved Ax client checkpoint

[INFO 04-02 10:14:22] ax.service.ax_client: Generated new trial 80 with parameters {'dropout_rate': 0.383461, 'weight_decay': 1e-06, 'lr': 0.01, 'batch_size': 256, 'early_stopping_patience': 14, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 512, 'hidden3': 32, 'activation': 'relu'} using model BoTorch.

Starting trial 80 with parameters: {'dropout_rate': 0.3834614395346545, 'weight_decay': 1e-06, 'lr': 0.01, 'batch_size': 256, 'early_stopping_patience': 14, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 512, 'hidden3': 32, 'activation': 'relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 4.8379, Val Loss: 2033.7977
  Epoch 10... Train Loss: 0.8838, Val Loss: 1.6645
  Epoch 20... Train Loss: 0.5566, Val Loss: 0.6891
  Epoch 30... Train Loss: 0.5845, Val Loss: 0.6151
  Epoch 40... Train Loss: 0.4680, Val Loss: 0.3667
  Epoch 50... Train Loss: 0.4805, Val Loss: 0.3511
  Epoch 60... Train Loss: 0.4624, Val Loss: 0.3449
  Epoch 70... Train Loss: 0.4056, Val Loss: 0.3403
Fold 1 - MSE: 40.7030, RMSE: 6.3799, MAE: 4.1968
Starting fold 2...
  Epoch 0... Train Loss: 9.0605, Val Loss: 9954.5859
  Epoch 10... Train Loss: 0.6716, Val Loss: 0.9431
  Epoch 20... Train Loss: 0.4335, Val Loss: 0.6959
  Epoch 30... Train Loss: 0.4354, Val Loss: 0.5742
  Epoch 40... Train Loss: 0.3370, Val Loss: 0.5047
  Epoch 50... Train Loss: 0.3298, Val Loss: 0.4777
  Epoch 60... Train Loss: 0.3231, Val Loss: 0.4651
  Epoch 70... Train Loss: 0.2744, Val Loss: 0.4765
Fold 2 - MSE: 38.2424, RMSE: 6.1840, MAE: 3.6143
Starting fold 3...
  Epoch 0... Train Loss: 8.7521, Val Loss: 18686.1445
  Epoch 10... Train Loss: 0.6972, Val Loss: 0.9554
  Epoch 20... Train Loss: 0.3964, Val Loss: 0.5210
  Epoch 30... Train Loss: 0.3409, Val Loss: 0.4573
  Epoch 40... Train Loss: 0.2679, Val Loss: 0.4391
Fold 3 - MSE: 29.9680, RMSE: 5.4743, MAE: 3.3418
Starting fold 4...
  Epoch 0... Train Loss: 9.0764, Val Loss: 7062.7646
  Epoch 10... Train Loss: 0.7360, Val Loss: 0.6142
  Epoch 20... Train Loss: 0.4264, Val Loss: 0.5669
  Epoch 30... Train Loss: 0.3436, Val Loss: 0.5516
  Epoch 40... Train Loss: 0.3084, Val Loss: 0.5155
  Epoch 50... Train Loss: 0.2766, Val Loss: 0.5080
  Epoch 60... Train Loss: 0.3007, Val Loss: 0.5266
Fold 4 - MSE: 30.6758, RMSE: 5.5386, MAE: 4.2314
Starting fold 5...
  Epoch 0... Train Loss: 10.6415, Val Loss: 2199.2256
  Epoch 10... Train Loss: 0.7230, Val Loss: 1.2770
  Epoch 20... Train Loss: 0.5570, Val Loss: 1.0896
  Epoch 30... Train Loss: 0.4238, Val Loss: 0.8950
  Epoch 40... Train Loss: 0.3554, Val Loss: 0.8521
  Epoch 50... Train Loss: 0.3204, Val Loss: 0.7704

[INFO 04-02 10:14:28] ax.service.ax_client: Completed trial 80 with data: {'avg_rmse_nonzero': 5.454577}.

  Epoch 60... Train Loss: 0.2852, Val Loss: 0.7942
Fold 5 - MSE: 13.6610, RMSE: 3.6961, MAE: 3.2121

Mean CV MSE: 30.6500, Mean CV RMSE: 5.4546, Mean CV MAE: 3.7193
Completed trial 80 with mean RMSE: 5.4546 ± 0.4737
Saved Ax client checkpoint

[INFO 04-02 10:14:31] ax.service.ax_client: Generated new trial 81 with parameters {'dropout_rate': 0.399872, 'weight_decay': 1e-06, 'lr': 0.005199, 'batch_size': 256, 'early_stopping_patience': 46, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 512, 'hidden3': 512, 'activation': 'leaky_relu'} using model BoTorch.

Starting trial 81 with parameters: {'dropout_rate': 0.3998715162835609, 'weight_decay': 1e-06, 'lr': 0.00519859290612748, 'batch_size': 256, 'early_stopping_patience': 46, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 512, 'hidden3': 512, 'activation': 'leaky_relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 1.8379, Val Loss: 283.3771
  Epoch 10... Train Loss: 0.7931, Val Loss: 1.2183
  Epoch 20... Train Loss: 0.5533, Val Loss: 0.4658
  Epoch 30... Train Loss: 0.4593, Val Loss: 0.4773
  Epoch 40... Train Loss: 0.3998, Val Loss: 0.3469
  Epoch 50... Train Loss: 0.4434, Val Loss: 0.3188
  Epoch 60... Train Loss: 0.3419, Val Loss: 0.3396
  Epoch 70... Train Loss: 0.3137, Val Loss: 0.3167
  Epoch 80... Train Loss: 0.3861, Val Loss: 0.3036
  Epoch 90... Train Loss: 0.2968, Val Loss: 0.2936
  Epoch 100... Train Loss: 0.4205, Val Loss: 0.2793
  Epoch 110... Train Loss: 0.3622, Val Loss: 0.2816
  Epoch 120... Train Loss: 0.4200, Val Loss: 0.3268
  Epoch 130... Train Loss: 0.2752, Val Loss: 0.3075
  Epoch 140... Train Loss: 0.3181, Val Loss: 0.3158
  Epoch 150... Train Loss: 0.4762, Val Loss: 0.3286
  Epoch 160... Train Loss: 0.2363, Val Loss: 0.3340
Fold 1 - MSE: 38.1621, RMSE: 6.1775, MAE: 4.0862
Starting fold 2...
  Epoch 0... Train Loss: 6.1526, Val Loss: 273.6220
  Epoch 10... Train Loss: 0.6223, Val Loss: 0.8723
  Epoch 20... Train Loss: 0.4114, Val Loss: 0.6229
  Epoch 30... Train Loss: 0.3605, Val Loss: 0.4052
  Epoch 40... Train Loss: 0.2775, Val Loss: 0.4919
  Epoch 50... Train Loss: 0.2735, Val Loss: 0.4562
  Epoch 60... Train Loss: 0.3136, Val Loss: 0.4269
  Epoch 70... Train Loss: 0.2728, Val Loss: 0.4052
  Epoch 80... Train Loss: 0.2606, Val Loss: 0.3747
  Epoch 90... Train Loss: 0.2314, Val Loss: 0.3358
  Epoch 100... Train Loss: 0.2506, Val Loss: 0.3870
  Epoch 110... Train Loss: 0.2113, Val Loss: 0.3808
  Epoch 120... Train Loss: 0.2283, Val Loss: 0.3671
  Epoch 130... Train Loss: 0.1876, Val Loss: 0.3542
Fold 2 - MSE: 35.0507, RMSE: 5.9204, MAE: 3.4644
Starting fold 3...
  Epoch 0... Train Loss: 8.8042, Val Loss: 890.6885
  Epoch 10... Train Loss: 0.5761, Val Loss: 1.1727
  Epoch 20... Train Loss: 0.3826, Val Loss: 0.6318
  Epoch 30... Train Loss: 0.3827, Val Loss: 0.4970
  Epoch 40... Train Loss: 0.2825, Val Loss: 0.4336
  Epoch 50... Train Loss: 0.2517, Val Loss: 0.4571
  Epoch 60... Train Loss: 0.2279, Val Loss: 0.4400
  Epoch 70... Train Loss: 0.2332, Val Loss: 0.4279
  Epoch 80... Train Loss: 0.2404, Val Loss: 0.4254
  Epoch 90... Train Loss: 0.2024, Val Loss: 0.4332
  Epoch 100... Train Loss: 0.2221, Val Loss: 0.4876
  Epoch 110... Train Loss: 0.2050, Val Loss: 0.4100
  Epoch 120... Train Loss: 0.2222, Val Loss: 0.4180
  Epoch 130... Train Loss: 0.1982, Val Loss: 0.3988
  Epoch 140... Train Loss: 0.1852, Val Loss: 0.4252
  Epoch 150... Train Loss: 0.1965, Val Loss: 0.3966
  Epoch 160... Train Loss: 0.2024, Val Loss: 0.3933
  Epoch 170... Train Loss: 0.2238, Val Loss: 0.4009
  Epoch 180... Train Loss: 0.2026, Val Loss: 0.4024
  Epoch 190... Train Loss: 0.1886, Val Loss: 0.4059
  Epoch 200... Train Loss: 0.1971, Val Loss: 0.4094
Fold 3 - MSE: 36.5722, RMSE: 6.0475, MAE: 3.5039
Starting fold 4...
  Epoch 0... Train Loss: 7.8682, Val Loss: 999.7164
  Epoch 10... Train Loss: 0.7071, Val Loss: 0.6718
  Epoch 20... Train Loss: 0.4720, Val Loss: 0.5448
  Epoch 30... Train Loss: 0.3441, Val Loss: 0.5771
  Epoch 40... Train Loss: 0.2874, Val Loss: 0.5590
  Epoch 50... Train Loss: 0.2394, Val Loss: 0.5094
  Epoch 60... Train Loss: 0.2029, Val Loss: 0.4681
  Epoch 70... Train Loss: 0.2083, Val Loss: 0.4623
  Epoch 80... Train Loss: 0.1992, Val Loss: 0.5138
  Epoch 90... Train Loss: 0.1915, Val Loss: 0.4787
  Epoch 100... Train Loss: 0.1833, Val Loss: 0.4370
  Epoch 110... Train Loss: 0.1862, Val Loss: 0.4398
  Epoch 120... Train Loss: 0.1674, Val Loss: 0.4274
  Epoch 130... Train Loss: 0.1808, Val Loss: 0.4326
  Epoch 140... Train Loss: 0.1699, Val Loss: 0.4609
  Epoch 150... Train Loss: 0.1681, Val Loss: 0.4389
  Epoch 160... Train Loss: 0.1702, Val Loss: 0.4404
Fold 4 - MSE: 30.4398, RMSE: 5.5172, MAE: 4.4785
Starting fold 5...
  Epoch 0... Train Loss: 8.1586, Val Loss: 1664.5175
  Epoch 10... Train Loss: 0.6812, Val Loss: 1.6690
  Epoch 20... Train Loss: 0.4846, Val Loss: 1.0625
  Epoch 30... Train Loss: 0.3662, Val Loss: 0.8791
  Epoch 40... Train Loss: 0.3153, Val Loss: 0.8063
  Epoch 50... Train Loss: 0.2789, Val Loss: 0.7811
  Epoch 60... Train Loss: 0.2711, Val Loss: 0.8195
  Epoch 70... Train Loss: 0.2428, Val Loss: 0.7604
  Epoch 80... Train Loss: 0.2472, Val Loss: 0.7644
  Epoch 90... Train Loss: 0.2152, Val Loss: 0.7633
  Epoch 100... Train Loss: 0.2229, Val Loss: 0.7607

[INFO 04-02 10:14:44] ax.service.ax_client: Completed trial 81 with data: {'avg_rmse_nonzero': 5.663668}.

  Epoch 110... Train Loss: 0.2107, Val Loss: 0.7588
Fold 5 - MSE: 21.6755, RMSE: 4.6557, MAE: 4.0427

Mean CV MSE: 32.3801, Mean CV RMSE: 5.6637, Mean CV MAE: 3.9151
Completed trial 81 with mean RMSE: 5.6637 ± 0.2752
Saved Ax client checkpoint

[INFO 04-02 10:14:47] ax.service.ax_client: Generated new trial 82 with parameters {'dropout_rate': 0.447679, 'weight_decay': 1e-06, 'lr': 0.008983, 'batch_size': 256, 'early_stopping_patience': 10, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 32, 'activation': 'leaky_relu'} using model BoTorch.

Starting trial 82 with parameters: {'dropout_rate': 0.4476790871118204, 'weight_decay': 1e-06, 'lr': 0.008983451465709037, 'batch_size': 256, 'early_stopping_patience': 10, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 32, 'activation': 'leaky_relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 2.7998, Val Loss: 1477.8990
  Epoch 10... Train Loss: 1.0451, Val Loss: 1.1411
  Epoch 20... Train Loss: 0.6711, Val Loss: 0.5285
  Epoch 30... Train Loss: 0.5105, Val Loss: 0.5321
  Epoch 40... Train Loss: 0.5056, Val Loss: 0.4219
  Epoch 50... Train Loss: 0.5252, Val Loss: 0.3909
  Epoch 60... Train Loss: 0.4462, Val Loss: 0.3590
  Epoch 70... Train Loss: 0.5341, Val Loss: 0.3682
Fold 1 - MSE: 36.4946, RMSE: 6.0411, MAE: 4.1091
Starting fold 2...
  Epoch 0... Train Loss: 5.9334, Val Loss: 1038.1655
  Epoch 10... Train Loss: 0.6971, Val Loss: 0.7952
  Epoch 20... Train Loss: 0.4254, Val Loss: 0.6515
  Epoch 30... Train Loss: 0.3962, Val Loss: 0.5389
  Epoch 40... Train Loss: 0.3390, Val Loss: 0.5023
  Epoch 50... Train Loss: 0.3881, Val Loss: 0.4638
Fold 2 - MSE: 37.0108, RMSE: 6.0837, MAE: 3.5324
Starting fold 3...
  Epoch 0... Train Loss: 8.2946, Val Loss: 3328.9316
  Epoch 10... Train Loss: 0.7162, Val Loss: 0.7925
  Epoch 20... Train Loss: 0.5379, Val Loss: 0.6349
  Epoch 30... Train Loss: 0.4506, Val Loss: 0.5243
  Epoch 40... Train Loss: 0.3631, Val Loss: 0.4590
  Epoch 50... Train Loss: 0.3189, Val Loss: 0.4608
Fold 3 - MSE: 25.7632, RMSE: 5.0758, MAE: 3.2649
Starting fold 4...
  Epoch 0... Train Loss: 10.1758, Val Loss: 854.1450
  Epoch 10... Train Loss: 0.8731, Val Loss: 0.6557
  Epoch 20... Train Loss: 0.4638, Val Loss: 0.5299
  Epoch 30... Train Loss: 0.4190, Val Loss: 0.5531
Fold 4 - MSE: 34.0552, RMSE: 5.8357, MAE: 4.4965
Starting fold 5...
  Epoch 0... Train Loss: 12.8406, Val Loss: 524.7253
  Epoch 10... Train Loss: 0.7056, Val Loss: 1.2746
  Epoch 20... Train Loss: 0.5697, Val Loss: 1.0355
  Epoch 30... Train Loss: 0.4885, Val Loss: 0.9549
  Epoch 40... Train Loss: 0.3661, Val Loss: 0.8690
  Epoch 50... Train Loss: 0.3278, Val Loss: 0.8679
Fold 5 - MSE: 5.2583, RMSE: 2.2931, MAE: 1.6978

Mean CV MSE: 27.7164, Mean CV RMSE: 5.0659, Mean CV MAE: 3.4201

[INFO 04-02 10:14:52] ax.service.ax_client: Completed trial 82 with data: {'avg_rmse_nonzero': 5.065852}.

Completed trial 82 with mean RMSE: 5.0659 ± 0.7165
Saved Ax client checkpoint

[INFO 04-02 10:14:56] ax.service.ax_client: Generated new trial 83 with parameters {'dropout_rate': 0.5, 'weight_decay': 1e-06, 'lr': 0.01, 'batch_size': 256, 'early_stopping_patience': 10, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 64, 'hidden3': 32, 'activation': 'leaky_relu'} using model BoTorch.

Starting trial 83 with parameters: {'dropout_rate': 0.5, 'weight_decay': 1e-06, 'lr': 0.01, 'batch_size': 256, 'early_stopping_patience': 10, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 64, 'hidden3': 32, 'activation': 'leaky_relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 3.9169, Val Loss: 280.0656
  Epoch 10... Train Loss: 1.0697, Val Loss: 4.0289
  Epoch 20... Train Loss: 0.7942, Val Loss: 1.2074
  Epoch 30... Train Loss: 0.7626, Val Loss: 0.5569
  Epoch 40... Train Loss: 0.6819, Val Loss: 0.5039
  Epoch 50... Train Loss: 0.5934, Val Loss: 0.4590
  Epoch 60... Train Loss: 0.4912, Val Loss: 0.4646
Fold 1 - MSE: 36.2477, RMSE: 6.0206, MAE: 4.1042
Starting fold 2...
  Epoch 0... Train Loss: 11.4056, Val Loss: 221.3888
  Epoch 10... Train Loss: 0.8243, Val Loss: 0.8523
  Epoch 20... Train Loss: 0.5149, Val Loss: 0.7035
  Epoch 30... Train Loss: 0.5178, Val Loss: 0.6573
  Epoch 40... Train Loss: 0.4323, Val Loss: 0.6465
  Epoch 50... Train Loss: 0.4438, Val Loss: 0.6112
  Epoch 60... Train Loss: 0.4699, Val Loss: 0.5903
  Epoch 70... Train Loss: 0.4161, Val Loss: 0.5859
  Epoch 80... Train Loss: 0.4597, Val Loss: 0.5880
Fold 2 - MSE: 39.3183, RMSE: 6.2704, MAE: 3.6868
Starting fold 3...
  Epoch 0... Train Loss: 6.3937, Val Loss: 3322.7029
  Epoch 10... Train Loss: 0.6986, Val Loss: 0.7739
  Epoch 20... Train Loss: 0.4593, Val Loss: 0.5377
  Epoch 30... Train Loss: 0.4075, Val Loss: 0.4957
  Epoch 40... Train Loss: 0.3038, Val Loss: 0.4649
  Epoch 50... Train Loss: 0.3199, Val Loss: 0.4566
Fold 3 - MSE: 29.9751, RMSE: 5.4749, MAE: 3.2440
Starting fold 4...
  Epoch 0... Train Loss: 15.2171, Val Loss: 401.2969
  Epoch 10... Train Loss: 1.0265, Val Loss: 0.7097
  Epoch 20... Train Loss: 0.6077, Val Loss: 0.5972
Fold 4 - MSE: 39.6779, RMSE: 6.2990, MAE: 5.0575
Starting fold 5...
  Epoch 0... Train Loss: 10.2830, Val Loss: 2952.8997
  Epoch 10... Train Loss: 0.8411, Val Loss: 1.2573
  Epoch 20... Train Loss: 0.6210, Val Loss: 1.1064
  Epoch 30... Train Loss: 0.4953, Val Loss: 0.9175
  Epoch 40... Train Loss: 0.3762, Val Loss: 0.8619
  Epoch 50... Train Loss: 0.3408, Val Loss: 0.8036
  Epoch 60... Train Loss: 0.3053, Val Loss: 0.7822
  Epoch 70... Train Loss: 0.3073, Val Loss: 0.7699

[INFO 04-02 10:15:02] ax.service.ax_client: Completed trial 83 with data: {'avg_rmse_nonzero': 5.246755}.

  Epoch 80... Train Loss: 0.2818, Val Loss: 0.7663
Fold 5 - MSE: 4.7035, RMSE: 2.1688, MAE: 1.7925

Mean CV MSE: 29.9845, Mean CV RMSE: 5.2468, Mean CV MAE: 3.5770
Completed trial 83 with mean RMSE: 5.2468 ± 0.7836
Saved Ax client checkpoint

[INFO 04-02 10:15:05] ax.service.ax_client: Generated new trial 84 with parameters {'dropout_rate': 0.5, 'weight_decay': 1e-06, 'lr': 0.009089, 'batch_size': 256, 'early_stopping_patience': 10, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 32, 'activation': 'relu'} using model BoTorch.

Starting trial 84 with parameters: {'dropout_rate': 0.5, 'weight_decay': 1e-06, 'lr': 0.009088629897710305, 'batch_size': 256, 'early_stopping_patience': 10, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 32, 'activation': 'relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 4.6848, Val Loss: 457.0151
  Epoch 10... Train Loss: 1.0466, Val Loss: 2.7743
  Epoch 20... Train Loss: 0.5463, Val Loss: 0.5417
  Epoch 30... Train Loss: 0.5354, Val Loss: 0.4934
  Epoch 40... Train Loss: 0.4007, Val Loss: 0.4094
  Epoch 50... Train Loss: 0.6085, Val Loss: 0.3680
  Epoch 60... Train Loss: 0.4865, Val Loss: 0.3975
Fold 1 - MSE: 38.9794, RMSE: 6.2434, MAE: 4.0877
Starting fold 2...
  Epoch 0... Train Loss: 9.5198, Val Loss: 5481.9492
  Epoch 10... Train Loss: 0.8351, Val Loss: 0.8032
  Epoch 20... Train Loss: 0.4841, Val Loss: 0.6346
  Epoch 30... Train Loss: 0.4423, Val Loss: 0.6236
  Epoch 40... Train Loss: 0.4128, Val Loss: 0.5974
  Epoch 50... Train Loss: 0.4241, Val Loss: 0.5785
  Epoch 60... Train Loss: 0.4505, Val Loss: 0.5663
Fold 2 - MSE: 38.5131, RMSE: 6.2059, MAE: 3.7522
Starting fold 3...
  Epoch 0... Train Loss: 5.4973, Val Loss: 1111.8505
  Epoch 10... Train Loss: 0.6897, Val Loss: 0.8250
  Epoch 20... Train Loss: 0.4957, Val Loss: 0.5603
  Epoch 30... Train Loss: 0.3866, Val Loss: 0.5040
  Epoch 40... Train Loss: 0.3421, Val Loss: 0.4561
Fold 3 - MSE: 23.7855, RMSE: 4.8770, MAE: 2.9801
Starting fold 4...
  Epoch 0... Train Loss: 10.0539, Val Loss: 104.5534
  Epoch 10... Train Loss: 0.8034, Val Loss: 0.7924
  Epoch 20... Train Loss: 0.6466, Val Loss: 0.6047
  Epoch 30... Train Loss: 0.4052, Val Loss: 0.4989
  Epoch 40... Train Loss: 0.3133, Val Loss: 0.4778
Fold 4 - MSE: 34.1747, RMSE: 5.8459, MAE: 4.6828
Starting fold 5...
  Epoch 0... Train Loss: 4.1574, Val Loss: 77.4139
  Epoch 10... Train Loss: 0.6586, Val Loss: 1.1717
  Epoch 20... Train Loss: 0.4621, Val Loss: 0.9481

[INFO 04-02 10:15:10] ax.service.ax_client: Completed trial 84 with data: {'avg_rmse_nonzero': 5.676445}.

Fold 5 - MSE: 27.1445, RMSE: 5.2100, MAE: 4.4892

Mean CV MSE: 32.5194, Mean CV RMSE: 5.6764, Mean CV MAE: 3.9984
Completed trial 84 with mean RMSE: 5.6764 ± 0.2727
Saved Ax client checkpoint

[INFO 04-02 10:15:14] ax.service.ax_client: Generated new trial 85 with parameters {'dropout_rate': 0.5, 'weight_decay': 2.1e-05, 'lr': 0.005494, 'batch_size': 256, 'early_stopping_patience': 48, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 64, 'hidden3': 32, 'activation': 'leaky_relu'} using model BoTorch.

Starting trial 85 with parameters: {'dropout_rate': 0.5, 'weight_decay': 2.083735725378853e-05, 'lr': 0.005494274995904235, 'batch_size': 256, 'early_stopping_patience': 48, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 64, 'hidden3': 32, 'activation': 'leaky_relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 2.2655, Val Loss: 54.9776
  Epoch 10... Train Loss: 0.9204, Val Loss: 1.1582
  Epoch 20... Train Loss: 0.5840, Val Loss: 0.5440
  Epoch 30... Train Loss: 0.4500, Val Loss: 0.5830
  Epoch 40... Train Loss: 0.4835, Val Loss: 0.4549
  Epoch 50... Train Loss: 0.5759, Val Loss: 0.4057
  Epoch 60... Train Loss: 0.3710, Val Loss: 0.3589
  Epoch 70... Train Loss: 0.3451, Val Loss: 0.3446
  Epoch 80... Train Loss: 0.5030, Val Loss: 0.3977
  Epoch 90... Train Loss: 0.3495, Val Loss: 0.3809
  Epoch 100... Train Loss: 0.3652, Val Loss: 0.3208
  Epoch 110... Train Loss: 0.3752, Val Loss: 0.3224
  Epoch 120... Train Loss: 0.4950, Val Loss: 0.4052
  Epoch 130... Train Loss: 0.3614, Val Loss: 0.2999
  Epoch 140... Train Loss: 0.3614, Val Loss: 0.3062
  Epoch 150... Train Loss: 0.4958, Val Loss: 0.3166
  Epoch 160... Train Loss: 0.3014, Val Loss: 0.3237
  Epoch 170... Train Loss: 0.3313, Val Loss: 0.3064
  Epoch 180... Train Loss: 0.3930, Val Loss: 0.2987
Fold 1 - MSE: 36.3073, RMSE: 6.0256, MAE: 4.0501
Starting fold 2...
  Epoch 0... Train Loss: 7.4472, Val Loss: 1786.4855
  Epoch 10... Train Loss: 0.6594, Val Loss: 0.7452
  Epoch 20... Train Loss: 0.4782, Val Loss: 0.6427
  Epoch 30... Train Loss: 0.4427, Val Loss: 0.5779
  Epoch 40... Train Loss: 0.3683, Val Loss: 0.4798
  Epoch 50... Train Loss: 0.3142, Val Loss: 0.4558
  Epoch 60... Train Loss: 0.3567, Val Loss: 0.4738
  Epoch 70... Train Loss: 0.2860, Val Loss: 0.3750
  Epoch 80... Train Loss: 0.2643, Val Loss: 0.4154
  Epoch 90... Train Loss: 0.2807, Val Loss: 0.4044
  Epoch 100... Train Loss: 0.2428, Val Loss: 0.3957
  Epoch 110... Train Loss: 0.2148, Val Loss: 0.4252
  Epoch 120... Train Loss: 0.2500, Val Loss: 0.4456
  Epoch 130... Train Loss: 0.2631, Val Loss: 0.3860
  Epoch 140... Train Loss: 0.2471, Val Loss: 0.3765
  Epoch 150... Train Loss: 0.2839, Val Loss: 0.3444
  Epoch 160... Train Loss: 0.2222, Val Loss: 0.3601
  Epoch 170... Train Loss: 0.2006, Val Loss: 0.3542
  Epoch 180... Train Loss: 0.2409, Val Loss: 0.3612
Fold 2 - MSE: 37.6971, RMSE: 6.1398, MAE: 3.9470
Starting fold 3...
  Epoch 0... Train Loss: 3.3271, Val Loss: 160.1446
  Epoch 10... Train Loss: 0.6445, Val Loss: 0.8144
  Epoch 20... Train Loss: 0.4345, Val Loss: 0.5720
  Epoch 30... Train Loss: 0.3644, Val Loss: 0.5020
  Epoch 40... Train Loss: 0.2821, Val Loss: 0.4513
  Epoch 50... Train Loss: 0.3026, Val Loss: 0.4604
  Epoch 60... Train Loss: 0.2493, Val Loss: 0.4379
  Epoch 70... Train Loss: 0.2480, Val Loss: 0.4214
  Epoch 80... Train Loss: 0.2532, Val Loss: 0.4319
  Epoch 90... Train Loss: 0.2298, Val Loss: 0.4260
  Epoch 100... Train Loss: 0.2355, Val Loss: 0.3984
Fold 3 - MSE: 48.7810, RMSE: 6.9843, MAE: 3.9097
Starting fold 4...
  Epoch 0... Train Loss: 6.7833, Val Loss: 694.2242
  Epoch 10... Train Loss: 0.6970, Val Loss: 0.6428
  Epoch 20... Train Loss: 0.3952, Val Loss: 0.5574
  Epoch 30... Train Loss: 0.3233, Val Loss: 0.5621
  Epoch 40... Train Loss: 0.2563, Val Loss: 0.4633
  Epoch 50... Train Loss: 0.2606, Val Loss: 0.4833
  Epoch 60... Train Loss: 0.2586, Val Loss: 0.4813
  Epoch 70... Train Loss: 0.2228, Val Loss: 0.4949
  Epoch 80... Train Loss: 0.2005, Val Loss: 0.4740
  Epoch 90... Train Loss: 0.1910, Val Loss: 0.4516
  Epoch 100... Train Loss: 0.1796, Val Loss: 0.4471
  Epoch 110... Train Loss: 0.1822, Val Loss: 0.3973
  Epoch 120... Train Loss: 0.1929, Val Loss: 0.4300
Fold 4 - MSE: 28.0004, RMSE: 5.2915, MAE: 4.1627
Starting fold 5...
  Epoch 0... Train Loss: 6.5901, Val Loss: 669.4363
  Epoch 10... Train Loss: 0.6239, Val Loss: 1.2390
  Epoch 20... Train Loss: 0.4732, Val Loss: 0.9771
  Epoch 30... Train Loss: 0.3670, Val Loss: 0.8566
  Epoch 40... Train Loss: 0.3479, Val Loss: 0.8059
  Epoch 50... Train Loss: 0.2942, Val Loss: 0.7569
  Epoch 60... Train Loss: 0.2562, Val Loss: 0.7864
  Epoch 70... Train Loss: 0.2565, Val Loss: 0.7453
  Epoch 80... Train Loss: 0.2673, Val Loss: 0.7465
  Epoch 90... Train Loss: 0.2475, Val Loss: 0.7518
  Epoch 100... Train Loss: 0.2524, Val Loss: 0.7073
  Epoch 110... Train Loss: 0.2406, Val Loss: 0.7482
  Epoch 120... Train Loss: 0.2050, Val Loss: 0.7081
  Epoch 130... Train Loss: 0.2154, Val Loss: 0.7177

[INFO 04-02 10:15:35] ax.service.ax_client: Completed trial 85 with data: {'avg_rmse_nonzero': 5.771661}.

  Epoch 140... Train Loss: 0.2448, Val Loss: 0.7194
Fold 5 - MSE: 19.5105, RMSE: 4.4171, MAE: 3.8300

Mean CV MSE: 34.0593, Mean CV RMSE: 5.7717, Mean CV MAE: 3.9799
Completed trial 85 with mean RMSE: 5.7717 ± 0.4322
Saved Ax client checkpoint

[INFO 04-02 10:15:42] ax.service.ax_client: Generated new trial 86 with parameters {'dropout_rate': 0.5, 'weight_decay': 1e-06, 'lr': 0.000128, 'batch_size': 32, 'early_stopping_patience': 47, 'n_layers': 3, 'hidden1': 256, 'hidden2': 1024, 'hidden3': 512, 'activation': 'selu'} using model BoTorch.

Starting trial 86 with parameters: {'dropout_rate': 0.5, 'weight_decay': 1e-06, 'lr': 0.0001283337426501299, 'batch_size': 32, 'early_stopping_patience': 47, 'n_layers': 3, 'hidden1': 256, 'hidden2': 1024, 'hidden3': 512, 'activation': 'selu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 1.2603, Val Loss: 1.1556
  Epoch 10... Train Loss: 0.8483, Val Loss: 0.4887
  Epoch 20... Train Loss: 0.8838, Val Loss: 0.4310
  Epoch 30... Train Loss: 0.7293, Val Loss: 0.4848
  Epoch 40... Train Loss: 0.6355, Val Loss: 0.3928
  Epoch 50... Train Loss: 0.6779, Val Loss: 0.4719
  Epoch 60... Train Loss: 0.5506, Val Loss: 0.3851
  Epoch 70... Train Loss: 0.5727, Val Loss: 0.3974
  Epoch 80... Train Loss: 0.5167, Val Loss: 0.3329
  Epoch 90... Train Loss: 0.5386, Val Loss: 0.3739
  Epoch 100... Train Loss: 0.5141, Val Loss: 0.3639
  Epoch 110... Train Loss: 0.5219, Val Loss: 0.3771
  Epoch 120... Train Loss: 0.5721, Val Loss: 0.5064
  Epoch 130... Train Loss: 0.5759, Val Loss: 0.3612
  Epoch 140... Train Loss: 0.5254, Val Loss: 0.4302
  Epoch 150... Train Loss: 0.4993, Val Loss: 0.4930
  Epoch 160... Train Loss: 0.5306, Val Loss: 0.3592
  Epoch 170... Train Loss: 0.5284, Val Loss: 0.3505
  Epoch 180... Train Loss: 0.7019, Val Loss: 0.3712
Fold 1 - MSE: 50.2125, RMSE: 7.0861, MAE: 4.9179
Starting fold 2...
  Epoch 0... Train Loss: 1.4919, Val Loss: 0.9315
  Epoch 10... Train Loss: 0.8174, Val Loss: 0.7572
  Epoch 20... Train Loss: 0.6958, Val Loss: 0.7350
  Epoch 30... Train Loss: 0.6108, Val Loss: 0.7017
  Epoch 40... Train Loss: 0.5531, Val Loss: 0.6649
  Epoch 50... Train Loss: 0.4642, Val Loss: 0.6020
  Epoch 60... Train Loss: 0.4335, Val Loss: 0.5572
  Epoch 70... Train Loss: 0.4458, Val Loss: 0.5216
  Epoch 80... Train Loss: 0.3853, Val Loss: 0.5315
  Epoch 90... Train Loss: 0.3679, Val Loss: 0.5168
  Epoch 100... Train Loss: 0.3399, Val Loss: 0.5095
  Epoch 110... Train Loss: 0.3564, Val Loss: 0.4990
Fold 2 - MSE: 55.2266, RMSE: 7.4315, MAE: 5.1110
Starting fold 3...
  Epoch 0... Train Loss: 1.3749, Val Loss: 0.9629
  Epoch 10... Train Loss: 0.7875, Val Loss: 0.6268
  Epoch 20... Train Loss: 0.7355, Val Loss: 0.5551
  Epoch 30... Train Loss: 0.5776, Val Loss: 0.6042
  Epoch 40... Train Loss: 0.5126, Val Loss: 0.5158
  Epoch 50... Train Loss: 0.4426, Val Loss: 0.4849
  Epoch 60... Train Loss: 0.4329, Val Loss: 0.4860
  Epoch 70... Train Loss: 0.4110, Val Loss: 0.4979
  Epoch 80... Train Loss: 0.3716, Val Loss: 0.4645
  Epoch 90... Train Loss: 0.3524, Val Loss: 0.4649
  Epoch 100... Train Loss: 0.3327, Val Loss: 0.4669
  Epoch 110... Train Loss: 0.3229, Val Loss: 0.4691
  Epoch 120... Train Loss: 0.3032, Val Loss: 0.4314
  Epoch 130... Train Loss: 0.3182, Val Loss: 0.4434
  Epoch 140... Train Loss: 0.2695, Val Loss: 0.4369
  Epoch 150... Train Loss: 0.3007, Val Loss: 0.4330
  Epoch 160... Train Loss: 0.2892, Val Loss: 0.4376
Fold 3 - MSE: 72.6916, RMSE: 8.5259, MAE: 4.9943
Starting fold 4...
  Epoch 0... Train Loss: 1.5379, Val Loss: 0.9981
  Epoch 10... Train Loss: 0.8477, Val Loss: 0.5880
  Epoch 20... Train Loss: 0.6646, Val Loss: 0.5560
  Epoch 30... Train Loss: 0.5566, Val Loss: 0.5483
  Epoch 40... Train Loss: 0.4989, Val Loss: 0.5330
  Epoch 50... Train Loss: 0.4161, Val Loss: 0.5478
  Epoch 60... Train Loss: 0.4423, Val Loss: 0.5143
  Epoch 70... Train Loss: 0.4268, Val Loss: 0.5219
  Epoch 80... Train Loss: 0.4111, Val Loss: 0.5176
  Epoch 90... Train Loss: 0.3944, Val Loss: 0.5198
  Epoch 100... Train Loss: 0.3819, Val Loss: 0.5191
  Epoch 110... Train Loss: 0.3869, Val Loss: 0.5250
Fold 4 - MSE: 36.1677, RMSE: 6.0140, MAE: 4.8505
Starting fold 5...
  Epoch 0... Train Loss: 1.4757, Val Loss: 1.4676
  Epoch 10... Train Loss: 0.8216, Val Loss: 1.0700
  Epoch 20... Train Loss: 0.6556, Val Loss: 0.9589
  Epoch 30... Train Loss: 0.5947, Val Loss: 0.9667
  Epoch 40... Train Loss: 0.5268, Val Loss: 0.9673
  Epoch 50... Train Loss: 0.4757, Val Loss: 0.9956
  Epoch 60... Train Loss: 0.4661, Val Loss: 0.8711

[INFO 04-02 10:16:58] ax.service.ax_client: Completed trial 86 with data: {'avg_rmse_nonzero': 7.31472}.

Fold 5 - MSE: 56.4929, RMSE: 7.5162, MAE: 6.9916

Mean CV MSE: 54.1582, Mean CV RMSE: 7.3147, Mean CV MAE: 5.3731
Completed trial 86 with mean RMSE: 7.3147 ± 0.4041
Saved Ax client checkpoint

[INFO 04-02 10:17:04] ax.service.ax_client: Generated new trial 87 with parameters {'dropout_rate': 0.5, 'weight_decay': 0.009644, 'lr': 0.01, 'batch_size': 256, 'early_stopping_patience': 27, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 64, 'hidden3': 512, 'activation': 'relu'} using model BoTorch.

Starting trial 87 with parameters: {'dropout_rate': 0.5, 'weight_decay': 0.009643559158233075, 'lr': 0.01, 'batch_size': 256, 'early_stopping_patience': 27, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 64, 'hidden3': 512, 'activation': 'relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 3.4468, Val Loss: 557.2158
  Epoch 10... Train Loss: 1.0119, Val Loss: 0.7059
  Epoch 20... Train Loss: 0.5940, Val Loss: 0.7577
  Epoch 30... Train Loss: 0.4969, Val Loss: 0.6075
  Epoch 40... Train Loss: 0.4023, Val Loss: 0.5185
  Epoch 50... Train Loss: 0.6200, Val Loss: 0.4892
  Epoch 60... Train Loss: 0.4155, Val Loss: 0.4240
  Epoch 70... Train Loss: 0.3730, Val Loss: 0.3607
  Epoch 80... Train Loss: 0.4246, Val Loss: 0.3924
  Epoch 90... Train Loss: 0.3284, Val Loss: 0.2836
  Epoch 100... Train Loss: 0.4025, Val Loss: 0.3175
  Epoch 110... Train Loss: 0.3991, Val Loss: 0.3394
Fold 1 - MSE: 37.8060, RMSE: 6.1487, MAE: 4.0487
Starting fold 2...
  Epoch 0... Train Loss: 9.0904, Val Loss: 11464.8203
  Epoch 10... Train Loss: 0.8084, Val Loss: 0.9467
  Epoch 20... Train Loss: 0.4982, Val Loss: 0.8815
  Epoch 30... Train Loss: 0.5365, Val Loss: 0.7733
  Epoch 40... Train Loss: 0.3922, Val Loss: 0.5731
  Epoch 50... Train Loss: 0.3885, Val Loss: 0.5799
  Epoch 60... Train Loss: 0.4055, Val Loss: 0.4390
  Epoch 70... Train Loss: 0.4086, Val Loss: 0.4045
  Epoch 80... Train Loss: 0.3843, Val Loss: 0.4951
  Epoch 90... Train Loss: 0.3664, Val Loss: 0.4358
  Epoch 100... Train Loss: 0.3062, Val Loss: 0.3966
  Epoch 110... Train Loss: 0.2418, Val Loss: 0.4257
Fold 2 - MSE: 37.4557, RMSE: 6.1201, MAE: 3.6134
Starting fold 3...
  Epoch 0... Train Loss: 9.2380, Val Loss: 8278.0703
  Epoch 10... Train Loss: 0.6729, Val Loss: 1.0174
  Epoch 20... Train Loss: 0.4358, Val Loss: 0.8256
  Epoch 30... Train Loss: 0.4498, Val Loss: 0.5508
  Epoch 40... Train Loss: 0.3987, Val Loss: 0.4831
  Epoch 50... Train Loss: 0.4279, Val Loss: 0.5491
  Epoch 60... Train Loss: 0.3171, Val Loss: 0.6352
  Epoch 70... Train Loss: 0.3562, Val Loss: 0.5295
  Epoch 80... Train Loss: 0.2936, Val Loss: 0.4001
  Epoch 90... Train Loss: 0.3090, Val Loss: 0.3936
  Epoch 100... Train Loss: 0.3092, Val Loss: 0.3989
  Epoch 110... Train Loss: 0.2843, Val Loss: 0.3554
Fold 3 - MSE: 48.4110, RMSE: 6.9578, MAE: 3.8160
Starting fold 4...
  Epoch 0... Train Loss: 8.5590, Val Loss: 4507.7368
  Epoch 10... Train Loss: 0.6683, Val Loss: 0.6741
  Epoch 20... Train Loss: 0.4123, Val Loss: 0.4844
  Epoch 30... Train Loss: 0.3983, Val Loss: 0.4125
  Epoch 40... Train Loss: 0.3353, Val Loss: 0.4788
  Epoch 50... Train Loss: 0.3212, Val Loss: 0.3855
Fold 4 - MSE: 32.8916, RMSE: 5.7351, MAE: 4.4211
Starting fold 5...
  Epoch 0... Train Loss: 4.0317, Val Loss: 421.1042
  Epoch 10... Train Loss: 0.5959, Val Loss: 1.2344
  Epoch 20... Train Loss: 0.4597, Val Loss: 1.2191
  Epoch 30... Train Loss: 0.4572, Val Loss: 1.0514
  Epoch 40... Train Loss: 0.4613, Val Loss: 0.9598
  Epoch 50... Train Loss: 0.4035, Val Loss: 0.9976
  Epoch 60... Train Loss: 0.3618, Val Loss: 0.8391

[INFO 04-02 10:17:20] ax.service.ax_client: Completed trial 87 with data: {'avg_rmse_nonzero': 5.496715}.

  Epoch 70... Train Loss: 0.3405, Val Loss: 0.8682
Fold 5 - MSE: 6.3599, RMSE: 2.5219, MAE: 2.1723

Mean CV MSE: 32.5848, Mean CV RMSE: 5.4967, Mean CV MAE: 3.6143
Completed trial 87 with mean RMSE: 5.4967 ± 0.7699
Saved Ax client checkpoint

[INFO 04-02 10:17:27] ax.service.ax_client: Generated new trial 88 with parameters {'dropout_rate': 0.092652, 'weight_decay': 1e-06, 'lr': 0.004934, 'batch_size': 256, 'early_stopping_patience': 39, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 512, 'activation': 'relu'} using model BoTorch.

Starting trial 88 with parameters: {'dropout_rate': 0.09265152928648504, 'weight_decay': 1e-06, 'lr': 0.004933866662679077, 'batch_size': 256, 'early_stopping_patience': 39, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 512, 'activation': 'relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 8.8793, Val Loss: 955.3327
  Epoch 10... Train Loss: 0.9744, Val Loss: 1.0024
  Epoch 20... Train Loss: 0.4581, Val Loss: 0.5560
  Epoch 30... Train Loss: 0.4137, Val Loss: 0.4610
  Epoch 40... Train Loss: 0.3183, Val Loss: 0.3412
  Epoch 50... Train Loss: 0.4055, Val Loss: 0.3434
  Epoch 60... Train Loss: 0.3244, Val Loss: 0.2999
  Epoch 70... Train Loss: 0.3065, Val Loss: 0.3092
  Epoch 80... Train Loss: 0.3301, Val Loss: 0.2885
Fold 1 - MSE: 49.8151, RMSE: 7.0580, MAE: 4.7629
Starting fold 2...
  Epoch 0... Train Loss: 11.7181, Val Loss: 738.9369
  Epoch 10... Train Loss: 0.6649, Val Loss: 0.7506
  Epoch 20... Train Loss: 0.4302, Val Loss: 0.6616
  Epoch 30... Train Loss: 0.3644, Val Loss: 0.5748
  Epoch 40... Train Loss: 0.2497, Val Loss: 0.4749
  Epoch 50... Train Loss: 0.2611, Val Loss: 0.4389
  Epoch 60... Train Loss: 0.2702, Val Loss: 0.4621
  Epoch 70... Train Loss: 0.2393, Val Loss: 0.3789
  Epoch 80... Train Loss: 0.2235, Val Loss: 0.4152
  Epoch 90... Train Loss: 0.2310, Val Loss: 0.3565
  Epoch 100... Train Loss: 0.2017, Val Loss: 0.4160
  Epoch 110... Train Loss: 0.1538, Val Loss: 0.3835
  Epoch 120... Train Loss: 0.1721, Val Loss: 0.3574
Fold 2 - MSE: 34.8241, RMSE: 5.9012, MAE: 3.4769
Starting fold 3...
  Epoch 0... Train Loss: 12.4888, Val Loss: 35.2393
  Epoch 10... Train Loss: 0.5631, Val Loss: 0.7706
  Epoch 20... Train Loss: 0.3090, Val Loss: 0.5611
  Epoch 30... Train Loss: 0.2783, Val Loss: 0.4556
  Epoch 40... Train Loss: 0.2153, Val Loss: 0.3984
  Epoch 50... Train Loss: 0.2111, Val Loss: 0.4551
  Epoch 60... Train Loss: 0.1834, Val Loss: 0.4173
  Epoch 70... Train Loss: 0.1696, Val Loss: 0.4165
  Epoch 80... Train Loss: 0.1867, Val Loss: 0.3904
  Epoch 90... Train Loss: 0.1659, Val Loss: 0.3733
  Epoch 100... Train Loss: 0.1861, Val Loss: 0.3999
  Epoch 110... Train Loss: 0.1702, Val Loss: 0.3933
  Epoch 120... Train Loss: 0.1714, Val Loss: 0.3565
  Epoch 130... Train Loss: 0.1472, Val Loss: 0.3814
  Epoch 140... Train Loss: 0.1602, Val Loss: 0.3765
  Epoch 150... Train Loss: 0.1617, Val Loss: 0.3801
Fold 3 - MSE: 15.5650, RMSE: 3.9452, MAE: 2.7850
Starting fold 4...
  Epoch 0... Train Loss: 9.5435, Val Loss: 997.8045
  Epoch 10... Train Loss: 0.8096, Val Loss: 0.5710
  Epoch 20... Train Loss: 0.4173, Val Loss: 0.5884
  Epoch 30... Train Loss: 0.2839, Val Loss: 0.5379
  Epoch 40... Train Loss: 0.2083, Val Loss: 0.5369
  Epoch 50... Train Loss: 0.1807, Val Loss: 0.4937
  Epoch 60... Train Loss: 0.1729, Val Loss: 0.5137
  Epoch 70... Train Loss: 0.1624, Val Loss: 0.4539
  Epoch 80... Train Loss: 0.1782, Val Loss: 0.5082
  Epoch 90... Train Loss: 0.1441, Val Loss: 0.4254
  Epoch 100... Train Loss: 0.1393, Val Loss: 0.4813
  Epoch 110... Train Loss: 0.1347, Val Loss: 0.4539
  Epoch 120... Train Loss: 0.1296, Val Loss: 0.5004
Fold 4 - MSE: 31.4842, RMSE: 5.6111, MAE: 4.4000
Starting fold 5...
  Epoch 0... Train Loss: 9.4160, Val Loss: 129.7393
  Epoch 10... Train Loss: 0.7352, Val Loss: 1.5587
  Epoch 20... Train Loss: 0.5554, Val Loss: 1.2691
  Epoch 30... Train Loss: 0.3895, Val Loss: 0.9561
  Epoch 40... Train Loss: 0.2715, Val Loss: 0.8323
  Epoch 50... Train Loss: 0.2384, Val Loss: 0.7710
  Epoch 60... Train Loss: 0.2133, Val Loss: 0.6863
  Epoch 70... Train Loss: 0.2091, Val Loss: 0.7329
  Epoch 80... Train Loss: 0.1913, Val Loss: 0.6931
  Epoch 90... Train Loss: 0.1838, Val Loss: 0.6934
Fold 5 - MSE: 25.8894, RMSE: 5.0882, MAE: 4.2560

Mean CV MSE: 31.5156, Mean CV RMSE: 5.5207, Mean CV MAE: 3.9362

[INFO 04-02 10:17:47] ax.service.ax_client: Completed trial 88 with data: {'avg_rmse_nonzero': 5.520733}.

Completed trial 88 with mean RMSE: 5.5207 ± 0.5092
Saved Ax client checkpoint

[INFO 04-02 10:17:53] ax.service.ax_client: Generated new trial 89 with parameters {'dropout_rate': 0.5, 'weight_decay': 1e-06, 'lr': 0.004112, 'batch_size': 256, 'early_stopping_patience': 10, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 512, 'activation': 'leaky_relu'} using model BoTorch.

Starting trial 89 with parameters: {'dropout_rate': 0.5, 'weight_decay': 1e-06, 'lr': 0.004112348077295594, 'batch_size': 256, 'early_stopping_patience': 10, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 512, 'activation': 'leaky_relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 1.5781, Val Loss: 73.9572
  Epoch 10... Train Loss: 0.9355, Val Loss: 1.2713
  Epoch 20... Train Loss: 0.4950, Val Loss: 0.4280
  Epoch 30... Train Loss: 0.5045, Val Loss: 0.4515
  Epoch 40... Train Loss: 0.4750, Val Loss: 0.3263
  Epoch 50... Train Loss: 0.4420, Val Loss: 0.3309
Fold 1 - MSE: 41.3129, RMSE: 6.4275, MAE: 4.1292
Starting fold 2...
  Epoch 0... Train Loss: 2.0809, Val Loss: 29.2199
  Epoch 10... Train Loss: 0.6009, Val Loss: 0.8285
  Epoch 20... Train Loss: 0.3666, Val Loss: 0.5628
  Epoch 30... Train Loss: 0.3902, Val Loss: 0.4352
  Epoch 40... Train Loss: 0.2845, Val Loss: 0.4550
Fold 2 - MSE: 38.8332, RMSE: 6.2316, MAE: 3.6794
Starting fold 3...
  Epoch 0... Train Loss: 5.3848, Val Loss: 283.3015
  Epoch 10... Train Loss: 0.5956, Val Loss: 0.8248
  Epoch 20... Train Loss: 0.4095, Val Loss: 0.4973
  Epoch 30... Train Loss: 0.3749, Val Loss: 0.4343
  Epoch 40... Train Loss: 0.2991, Val Loss: 0.3994
  Epoch 50... Train Loss: 0.2685, Val Loss: 0.4251
Fold 3 - MSE: 38.6615, RMSE: 6.2178, MAE: 3.5794
Starting fold 4...
  Epoch 0... Train Loss: 4.5403, Val Loss: 9.4037
  Epoch 10... Train Loss: 0.6019, Val Loss: 0.7220
  Epoch 20... Train Loss: 0.3814, Val Loss: 0.5536
  Epoch 30... Train Loss: 0.2832, Val Loss: 0.5559
  Epoch 40... Train Loss: 0.2515, Val Loss: 0.5232
Fold 4 - MSE: 29.5374, RMSE: 5.4348, MAE: 4.3333
Starting fold 5...
  Epoch 0... Train Loss: 5.8281, Val Loss: 196.8492
  Epoch 10... Train Loss: 0.6392, Val Loss: 1.2421
  Epoch 20... Train Loss: 0.4433, Val Loss: 0.9980
  Epoch 30... Train Loss: 0.3881, Val Loss: 0.9354
Fold 5 - MSE: 4.4188, RMSE: 2.1021, MAE: 1.6848

Mean CV MSE: 30.5528, Mean CV RMSE: 5.2828, Mean CV MAE: 3.4812

[INFO 04-02 10:18:03] ax.service.ax_client: Completed trial 89 with data: {'avg_rmse_nonzero': 5.282783}.

Completed trial 89 with mean RMSE: 5.2828 ± 0.8132
Saved Ax client checkpoint

[INFO 04-02 10:18:10] ax.service.ax_client: Generated new trial 90 with parameters {'dropout_rate': 0.5, 'weight_decay': 1e-06, 'lr': 0.008118, 'batch_size': 256, 'early_stopping_patience': 36, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 256, 'activation': 'leaky_relu'} using model BoTorch.

Starting trial 90 with parameters: {'dropout_rate': 0.5, 'weight_decay': 1e-06, 'lr': 0.008117500929062155, 'batch_size': 256, 'early_stopping_patience': 36, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 256, 'activation': 'leaky_relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 3.2277, Val Loss: 127.0281
  Epoch 10... Train Loss: 1.1472, Val Loss: 1.5201
  Epoch 20... Train Loss: 0.5590, Val Loss: 0.5870
  Epoch 30... Train Loss: 0.4572, Val Loss: 0.5047
  Epoch 40... Train Loss: 0.5084, Val Loss: 0.4323
  Epoch 50... Train Loss: 0.5271, Val Loss: 0.3876
  Epoch 60... Train Loss: 0.4156, Val Loss: 0.4354
  Epoch 70... Train Loss: 0.4605, Val Loss: 0.4080
  Epoch 80... Train Loss: 0.4786, Val Loss: 0.4064
  Epoch 90... Train Loss: 0.4534, Val Loss: 0.3698
  Epoch 100... Train Loss: 0.4832, Val Loss: 0.3049
  Epoch 110... Train Loss: 0.3991, Val Loss: 0.2923
  Epoch 120... Train Loss: 0.4562, Val Loss: 0.3339
  Epoch 130... Train Loss: 0.3102, Val Loss: 0.3053
  Epoch 140... Train Loss: 0.2970, Val Loss: 0.2853
Fold 1 - MSE: 42.8693, RMSE: 6.5475, MAE: 4.2622
Starting fold 2...
  Epoch 0... Train Loss: 8.9989, Val Loss: 8038.4092
  Epoch 10... Train Loss: 0.8874, Val Loss: 1.0514
  Epoch 20... Train Loss: 0.4764, Val Loss: 0.7185
  Epoch 30... Train Loss: 0.3859, Val Loss: 0.5493
  Epoch 40... Train Loss: 0.3306, Val Loss: 0.5272
  Epoch 50... Train Loss: 0.3470, Val Loss: 0.5050
  Epoch 60... Train Loss: 0.3122, Val Loss: 0.5087
  Epoch 70... Train Loss: 0.3060, Val Loss: 0.4488
  Epoch 80... Train Loss: 0.3093, Val Loss: 0.4294
  Epoch 90... Train Loss: 0.3410, Val Loss: 0.4244
  Epoch 100... Train Loss: 0.2378, Val Loss: 0.3941
  Epoch 110... Train Loss: 0.2382, Val Loss: 0.3988
  Epoch 120... Train Loss: 0.2347, Val Loss: 0.3625
  Epoch 130... Train Loss: 0.2542, Val Loss: 0.3719
  Epoch 140... Train Loss: 0.2274, Val Loss: 0.3607
  Epoch 150... Train Loss: 0.2870, Val Loss: 0.3539
  Epoch 160... Train Loss: 0.2239, Val Loss: 0.3556
  Epoch 170... Train Loss: 0.2257, Val Loss: 0.3593
  Epoch 180... Train Loss: 0.1946, Val Loss: 0.3636
  Epoch 190... Train Loss: 0.2170, Val Loss: 0.3648
Fold 2 - MSE: 38.2229, RMSE: 6.1825, MAE: 3.9529
Starting fold 3...
  Epoch 0... Train Loss: 10.8532, Val Loss: 319.8328
  Epoch 10... Train Loss: 0.7484, Val Loss: 0.8818
  Epoch 20... Train Loss: 0.4527, Val Loss: 0.5603
  Epoch 30... Train Loss: 0.3957, Val Loss: 0.5058
  Epoch 40... Train Loss: 0.3331, Val Loss: 0.4899
  Epoch 50... Train Loss: 0.2858, Val Loss: 0.4778
  Epoch 60... Train Loss: 0.2566, Val Loss: 0.4726
  Epoch 70... Train Loss: 0.2967, Val Loss: 0.4014
  Epoch 80... Train Loss: 0.2597, Val Loss: 0.4069
  Epoch 90... Train Loss: 0.2478, Val Loss: 0.4150
  Epoch 100... Train Loss: 0.2413, Val Loss: 0.4245
Fold 3 - MSE: 28.8630, RMSE: 5.3724, MAE: 3.2527
Starting fold 4...
  Epoch 0... Train Loss: 7.7592, Val Loss: 3079.7712
  Epoch 10... Train Loss: 0.8034, Val Loss: 0.6591
  Epoch 20... Train Loss: 0.4897, Val Loss: 0.6051
  Epoch 30... Train Loss: 0.3492, Val Loss: 0.5120
  Epoch 40... Train Loss: 0.3008, Val Loss: 0.4872
  Epoch 50... Train Loss: 0.2528, Val Loss: 0.4709
  Epoch 60... Train Loss: 0.2643, Val Loss: 0.4762
  Epoch 70... Train Loss: 0.2192, Val Loss: 0.4520
  Epoch 80... Train Loss: 0.2102, Val Loss: 0.5128
  Epoch 90... Train Loss: 0.2290, Val Loss: 0.4764
Fold 4 - MSE: 30.7293, RMSE: 5.5434, MAE: 4.3403
Starting fold 5...
  Epoch 0... Train Loss: 8.8129, Val Loss: 2629.0020
  Epoch 10... Train Loss: 0.7379, Val Loss: 1.3560
  Epoch 20... Train Loss: 0.4985, Val Loss: 0.9938
  Epoch 30... Train Loss: 0.4496, Val Loss: 0.8802
  Epoch 40... Train Loss: 0.3473, Val Loss: 0.8655
  Epoch 50... Train Loss: 0.3056, Val Loss: 0.8236
  Epoch 60... Train Loss: 0.2732, Val Loss: 0.7877
  Epoch 70... Train Loss: 0.2888, Val Loss: 0.7916
  Epoch 80... Train Loss: 0.2808, Val Loss: 0.7533
  Epoch 90... Train Loss: 0.2660, Val Loss: 0.7673
  Epoch 100... Train Loss: 0.2702, Val Loss: 0.7596
  Epoch 110... Train Loss: 0.2273, Val Loss: 0.7432
  Epoch 120... Train Loss: 0.2407, Val Loss: 0.7423
  Epoch 130... Train Loss: 0.2227, Val Loss: 0.7566
  Epoch 140... Train Loss: 0.2174, Val Loss: 0.7427
  Epoch 150... Train Loss: 0.2237, Val Loss: 0.7408
  Epoch 160... Train Loss: 0.2261, Val Loss: 0.7367
  Epoch 170... Train Loss: 0.2245, Val Loss: 0.7420
  Epoch 180... Train Loss: 0.2277, Val Loss: 0.7313
  Epoch 190... Train Loss: 0.2416, Val Loss: 0.7334
  Epoch 200... Train Loss: 0.2033, Val Loss: 0.7391
  Epoch 210... Train Loss: 0.2319, Val Loss: 0.7380

[INFO 04-02 10:18:34] ax.service.ax_client: Completed trial 90 with data: {'avg_rmse_nonzero': 5.163495}.

Fold 5 - MSE: 4.7163, RMSE: 2.1717, MAE: 1.7227

Mean CV MSE: 29.0802, Mean CV RMSE: 5.1635, Mean CV MAE: 3.5062
Completed trial 90 with mean RMSE: 5.1635 ± 0.7776
Saved Ax client checkpoint

c:\Users\Chris\Documents\ML_Project\ML_GFA_env\Lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning:

A not p.d., added jitter of 1.0e-08 to the diagonal

[INFO 04-02 10:18:41] ax.service.ax_client: Generated new trial 91 with parameters {'dropout_rate': 0.353419, 'weight_decay': 1e-06, 'lr': 0.00585, 'batch_size': 256, 'early_stopping_patience': 48, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 512, 'activation': 'relu'} using model BoTorch.

Starting trial 91 with parameters: {'dropout_rate': 0.35341877590715004, 'weight_decay': 1e-06, 'lr': 0.005849633343924109, 'batch_size': 256, 'early_stopping_patience': 48, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 512, 'activation': 'relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 1.8115, Val Loss: 98.3420
  Epoch 10... Train Loss: 1.0125, Val Loss: 1.0749
  Epoch 20... Train Loss: 0.6231, Val Loss: 0.5563
  Epoch 30... Train Loss: 0.4894, Val Loss: 0.7837
  Epoch 40... Train Loss: 0.4540, Val Loss: 0.4649
  Epoch 50... Train Loss: 0.6089, Val Loss: 0.3403
  Epoch 60... Train Loss: 0.3552, Val Loss: 0.3410
  Epoch 70... Train Loss: 0.3066, Val Loss: 0.3290
  Epoch 80... Train Loss: 0.3595, Val Loss: 0.3021
  Epoch 90... Train Loss: 0.3376, Val Loss: 0.2736
  Epoch 100... Train Loss: 0.3305, Val Loss: 0.2670
  Epoch 110... Train Loss: 0.3094, Val Loss: 0.2886
  Epoch 120... Train Loss: 0.4370, Val Loss: 0.3152
  Epoch 130... Train Loss: 0.2959, Val Loss: 0.2920
  Epoch 140... Train Loss: 0.3689, Val Loss: 0.2728
  Epoch 150... Train Loss: 0.4421, Val Loss: 0.2954
  Epoch 160... Train Loss: 0.2381, Val Loss: 0.3049
Fold 1 - MSE: 38.0645, RMSE: 6.1696, MAE: 4.1870
Starting fold 2...
  Epoch 0... Train Loss: 10.4955, Val Loss: 5175.1709
  Epoch 10... Train Loss: 0.6758, Val Loss: 0.8627
  Epoch 20... Train Loss: 0.4251, Val Loss: 0.6587
  Epoch 30... Train Loss: 0.3779, Val Loss: 0.4687
  Epoch 40... Train Loss: 0.2898, Val Loss: 0.4648
  Epoch 50... Train Loss: 0.2782, Val Loss: 0.4812
  Epoch 60... Train Loss: 0.2724, Val Loss: 0.4764
  Epoch 70... Train Loss: 0.2536, Val Loss: 0.3936
  Epoch 80... Train Loss: 0.2561, Val Loss: 0.4313
  Epoch 90... Train Loss: 0.2367, Val Loss: 0.3658
  Epoch 100... Train Loss: 0.2387, Val Loss: 0.3980
  Epoch 110... Train Loss: 0.2026, Val Loss: 0.3764
  Epoch 120... Train Loss: 0.2130, Val Loss: 0.3696
  Epoch 130... Train Loss: 0.2104, Val Loss: 0.3824
Fold 2 - MSE: 38.9516, RMSE: 6.2411, MAE: 3.7215
Starting fold 3...
  Epoch 0... Train Loss: 9.5246, Val Loss: 3247.1433
  Epoch 10... Train Loss: 0.7217, Val Loss: 0.8148
  Epoch 20... Train Loss: 0.4790, Val Loss: 0.6559
  Epoch 30... Train Loss: 0.4097, Val Loss: 0.5479
  Epoch 40... Train Loss: 0.2793, Val Loss: 0.4744
  Epoch 50... Train Loss: 0.2812, Val Loss: 0.4970
  Epoch 60... Train Loss: 0.2542, Val Loss: 0.4063
  Epoch 70... Train Loss: 0.2286, Val Loss: 0.4609
  Epoch 80... Train Loss: 0.2295, Val Loss: 0.4420
  Epoch 90... Train Loss: 0.1960, Val Loss: 0.4069
  Epoch 100... Train Loss: 0.2190, Val Loss: 0.4113
  Epoch 110... Train Loss: 0.2044, Val Loss: 0.4225
  Epoch 120... Train Loss: 0.2068, Val Loss: 0.4072
Fold 3 - MSE: 28.1527, RMSE: 5.3059, MAE: 3.2090
Starting fold 4...
  Epoch 0... Train Loss: 8.5760, Val Loss: 430.2954
  Epoch 10... Train Loss: 0.6458, Val Loss: 0.7397
  Epoch 20... Train Loss: 0.3392, Val Loss: 0.5310
  Epoch 30... Train Loss: 0.2942, Val Loss: 0.4722
  Epoch 40... Train Loss: 0.2385, Val Loss: 0.4947
  Epoch 50... Train Loss: 0.1914, Val Loss: 0.4511
  Epoch 60... Train Loss: 0.1896, Val Loss: 0.4797
  Epoch 70... Train Loss: 0.1851, Val Loss: 0.4463
Fold 4 - MSE: 28.7139, RMSE: 5.3585, MAE: 4.2677
Starting fold 5...
  Epoch 0... Train Loss: 7.3780, Val Loss: 1677.6366
  Epoch 10... Train Loss: 0.6302, Val Loss: 1.4144
  Epoch 20... Train Loss: 0.4226, Val Loss: 0.9504
  Epoch 30... Train Loss: 0.3169, Val Loss: 0.8957
  Epoch 40... Train Loss: 0.3023, Val Loss: 0.8101
  Epoch 50... Train Loss: 0.2411, Val Loss: 0.7998
  Epoch 60... Train Loss: 0.2582, Val Loss: 0.7777
  Epoch 70... Train Loss: 0.2481, Val Loss: 0.7762
  Epoch 80... Train Loss: 0.2256, Val Loss: 0.7551
  Epoch 90... Train Loss: 0.2274, Val Loss: 0.7441
  Epoch 100... Train Loss: 0.2346, Val Loss: 0.7475
  Epoch 110... Train Loss: 0.2228, Val Loss: 0.7451
  Epoch 120... Train Loss: 0.2126, Val Loss: 0.7377
  Epoch 130... Train Loss: 0.2218, Val Loss: 0.7445
  Epoch 140... Train Loss: 0.2162, Val Loss: 0.7310
  Epoch 150... Train Loss: 0.2067, Val Loss: 0.7373
  Epoch 160... Train Loss: 0.1879, Val Loss: 0.7299
  Epoch 170... Train Loss: 0.1795, Val Loss: 0.7355
  Epoch 180... Train Loss: 0.1775, Val Loss: 0.7379
Fold 5 - MSE: 4.9303, RMSE: 2.2204, MAE: 1.6844

Mean CV MSE: 27.7626, Mean CV RMSE: 5.0591, Mean CV MAE: 3.4139

[INFO 04-02 10:19:02] ax.service.ax_client: Completed trial 91 with data: {'avg_rmse_nonzero': 5.059125}.

Completed trial 91 with mean RMSE: 5.0591 ± 0.7362
Saved Ax client checkpoint

[INFO 04-02 10:19:09] ax.service.ax_client: Generated new trial 92 with parameters {'dropout_rate': 0.5, 'weight_decay': 0.005883, 'lr': 0.01, 'batch_size': 256, 'early_stopping_patience': 19, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 64, 'hidden3': 128, 'activation': 'leaky_relu'} using model BoTorch.

Starting trial 92 with parameters: {'dropout_rate': 0.5, 'weight_decay': 0.005882705810095958, 'lr': 0.01, 'batch_size': 256, 'early_stopping_patience': 19, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 64, 'hidden3': 128, 'activation': 'leaky_relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 2.6219, Val Loss: 1821.9421
  Epoch 10... Train Loss: 0.9717, Val Loss: 0.8144
  Epoch 20... Train Loss: 0.6659, Val Loss: 0.6872
  Epoch 30... Train Loss: 0.5342, Val Loss: 0.5825
  Epoch 40... Train Loss: 0.4297, Val Loss: 0.4311
  Epoch 50... Train Loss: 0.6264, Val Loss: 0.5219
  Epoch 60... Train Loss: 0.3576, Val Loss: 0.3811
  Epoch 70... Train Loss: 0.3212, Val Loss: 0.3440
  Epoch 80... Train Loss: 0.4038, Val Loss: 0.2877
  Epoch 90... Train Loss: 0.3764, Val Loss: 0.2993
  Epoch 100... Train Loss: 0.4113, Val Loss: 0.2836
  Epoch 110... Train Loss: 0.3411, Val Loss: 0.3006
Fold 1 - MSE: 37.2875, RMSE: 6.1064, MAE: 4.0500
Starting fold 2...
  Epoch 0... Train Loss: 7.5095, Val Loss: 4515.9224
  Epoch 10... Train Loss: 0.7005, Val Loss: 0.7220
  Epoch 20... Train Loss: 0.4556, Val Loss: 0.6514
  Epoch 30... Train Loss: 0.4352, Val Loss: 0.5451
  Epoch 40... Train Loss: 0.3747, Val Loss: 0.4681
  Epoch 50... Train Loss: 0.3789, Val Loss: 0.4438
  Epoch 60... Train Loss: 0.3731, Val Loss: 0.4926
  Epoch 70... Train Loss: 0.2750, Val Loss: 0.3175
  Epoch 80... Train Loss: 0.2666, Val Loss: 0.3618
  Epoch 90... Train Loss: 0.2882, Val Loss: 0.3476
  Epoch 100... Train Loss: 0.2518, Val Loss: 0.3732
Fold 2 - MSE: 35.8007, RMSE: 5.9834, MAE: 3.8306
Starting fold 3...
  Epoch 0... Train Loss: 7.9884, Val Loss: 6798.5054
  Epoch 10... Train Loss: 0.7105, Val Loss: 0.7795
  Epoch 20... Train Loss: 0.4526, Val Loss: 0.6620
  Epoch 30... Train Loss: 0.4341, Val Loss: 0.6371
  Epoch 40... Train Loss: 0.3590, Val Loss: 0.4391
  Epoch 50... Train Loss: 0.3109, Val Loss: 0.5019
  Epoch 60... Train Loss: 0.2796, Val Loss: 0.4552
  Epoch 70... Train Loss: 0.2805, Val Loss: 0.4182
  Epoch 80... Train Loss: 0.2413, Val Loss: 0.3621
  Epoch 90... Train Loss: 0.2049, Val Loss: 0.3930
Fold 3 - MSE: 51.2741, RMSE: 7.1606, MAE: 3.7831
Starting fold 4...
  Epoch 0... Train Loss: 6.7849, Val Loss: 214.4978
  Epoch 10... Train Loss: 0.6809, Val Loss: 0.5281
  Epoch 20... Train Loss: 0.3320, Val Loss: 0.4962
  Epoch 30... Train Loss: 0.4349, Val Loss: 0.4866
  Epoch 40... Train Loss: 0.3521, Val Loss: 0.4782
  Epoch 50... Train Loss: 0.2829, Val Loss: 0.3800
  Epoch 60... Train Loss: 0.2395, Val Loss: 0.4377
Fold 4 - MSE: 33.3497, RMSE: 5.7749, MAE: 4.6105
Starting fold 5...
  Epoch 0... Train Loss: 8.3090, Val Loss: 7355.2852
  Epoch 10... Train Loss: 0.6564, Val Loss: 1.2388
  Epoch 20... Train Loss: 0.4283, Val Loss: 1.2136
  Epoch 30... Train Loss: 0.4206, Val Loss: 1.0768
  Epoch 40... Train Loss: 0.3953, Val Loss: 0.8306
  Epoch 50... Train Loss: 0.3229, Val Loss: 0.8677

[INFO 04-02 10:19:24] ax.service.ax_client: Completed trial 92 with data: {'avg_rmse_nonzero': 5.831787}.

Fold 5 - MSE: 17.0875, RMSE: 4.1337, MAE: 3.6534

Mean CV MSE: 34.9599, Mean CV RMSE: 5.8318, Mean CV MAE: 3.9855
Completed trial 92 with mean RMSE: 5.8318 ± 0.4874
Saved Ax client checkpoint

[INFO 04-02 10:19:31] ax.service.ax_client: Generated new trial 93 with parameters {'dropout_rate': 0.0, 'weight_decay': 0.01, 'lr': 0.000224, 'batch_size': 256, 'early_stopping_patience': 43, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 64, 'hidden3': 512, 'activation': 'leaky_relu'} using model BoTorch.

Starting trial 93 with parameters: {'dropout_rate': 0.0, 'weight_decay': 0.01, 'lr': 0.0002242852248727407, 'batch_size': 256, 'early_stopping_patience': 43, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 64, 'hidden3': 512, 'activation': 'leaky_relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 1.6997, Val Loss: 0.8366
  Epoch 10... Train Loss: 0.3169, Val Loss: 0.3594
  Epoch 20... Train Loss: 0.3014, Val Loss: 0.2891
  Epoch 30... Train Loss: 0.2967, Val Loss: 0.3802
  Epoch 40... Train Loss: 0.2172, Val Loss: 0.3414
  Epoch 50... Train Loss: 0.2878, Val Loss: 0.3334
  Epoch 60... Train Loss: 0.2188, Val Loss: 0.3100
Fold 1 - MSE: 38.0286, RMSE: 6.1667, MAE: 4.1435
Starting fold 2...
  Epoch 0... Train Loss: 1.2346, Val Loss: 1.0300
  Epoch 10... Train Loss: 0.2685, Val Loss: 0.3818
  Epoch 20... Train Loss: 0.1733, Val Loss: 0.3951
  Epoch 30... Train Loss: 0.1844, Val Loss: 0.3999
  Epoch 40... Train Loss: 0.1685, Val Loss: 0.3854
  Epoch 50... Train Loss: 0.1345, Val Loss: 0.3473
  Epoch 60... Train Loss: 0.1439, Val Loss: 0.4011
  Epoch 70... Train Loss: 0.1535, Val Loss: 0.3642
  Epoch 80... Train Loss: 0.1069, Val Loss: 0.3568
  Epoch 90... Train Loss: 0.1088, Val Loss: 0.3495
Fold 2 - MSE: 32.8758, RMSE: 5.7337, MAE: 3.6305
Starting fold 3...
  Epoch 0... Train Loss: 1.5621, Val Loss: 1.0561
  Epoch 10... Train Loss: 0.2108, Val Loss: 0.4039
  Epoch 20... Train Loss: 0.1706, Val Loss: 0.4205
  Epoch 30... Train Loss: 0.1800, Val Loss: 0.3949
  Epoch 40... Train Loss: 0.1550, Val Loss: 0.3442
  Epoch 50... Train Loss: 0.1513, Val Loss: 0.3785
  Epoch 60... Train Loss: 0.1217, Val Loss: 0.3194
  Epoch 70... Train Loss: 0.1139, Val Loss: 0.3114
  Epoch 80... Train Loss: 0.1111, Val Loss: 0.3264
  Epoch 90... Train Loss: 0.1020, Val Loss: 0.3168
  Epoch 100... Train Loss: 0.1061, Val Loss: 0.2966
  Epoch 110... Train Loss: 0.0830, Val Loss: 0.3027
  Epoch 120... Train Loss: 0.0926, Val Loss: 0.3047
  Epoch 130... Train Loss: 0.0722, Val Loss: 0.2982
  Epoch 140... Train Loss: 0.0647, Val Loss: 0.2978
Fold 3 - MSE: 37.1710, RMSE: 6.0968, MAE: 3.8264
Starting fold 4...
  Epoch 0... Train Loss: 1.6402, Val Loss: 0.6418
  Epoch 10... Train Loss: 0.1984, Val Loss: 0.4674
  Epoch 20... Train Loss: 0.1266, Val Loss: 0.4732
  Epoch 30... Train Loss: 0.1167, Val Loss: 0.4679
  Epoch 40... Train Loss: 0.1094, Val Loss: 0.4680
  Epoch 50... Train Loss: 0.0936, Val Loss: 0.4511
Fold 4 - MSE: 27.1906, RMSE: 5.2145, MAE: 4.0970
Starting fold 5...
  Epoch 0... Train Loss: 1.3568, Val Loss: 1.3235
  Epoch 10... Train Loss: 0.2183, Val Loss: 0.7545
  Epoch 20... Train Loss: 0.1891, Val Loss: 0.6881
  Epoch 30... Train Loss: 0.1813, Val Loss: 0.7086
  Epoch 40... Train Loss: 0.1602, Val Loss: 0.7176
  Epoch 50... Train Loss: 0.1318, Val Loss: 0.7065
  Epoch 60... Train Loss: 0.1378, Val Loss: 0.7200
  Epoch 70... Train Loss: 0.1391, Val Loss: 0.6372
  Epoch 80... Train Loss: 0.1140, Val Loss: 0.6419
  Epoch 90... Train Loss: 0.0972, Val Loss: 0.6375
  Epoch 100... Train Loss: 0.0910, Val Loss: 0.6362
  Epoch 110... Train Loss: 0.0826, Val Loss: 0.6961
  Epoch 120... Train Loss: 0.0734, Val Loss: 0.6617
  Epoch 130... Train Loss: 0.0593, Val Loss: 0.6345

[INFO 04-02 10:19:48] ax.service.ax_client: Completed trial 93 with data: {'avg_rmse_nonzero': 5.358581}.

  Epoch 140... Train Loss: 0.0555, Val Loss: 0.6361
Fold 5 - MSE: 12.8246, RMSE: 3.5812, MAE: 3.1761

Mean CV MSE: 29.6182, Mean CV RMSE: 5.3586, Mean CV MAE: 3.7747
Completed trial 93 with mean RMSE: 5.3586 ± 0.4753
Saved Ax client checkpoint

[INFO 04-02 10:19:54] ax.service.ax_client: Generated new trial 94 with parameters {'dropout_rate': 0.294671, 'weight_decay': 1e-06, 'lr': 0.003383, 'batch_size': 256, 'early_stopping_patience': 21, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 512, 'activation': 'leaky_relu'} using model BoTorch.

Starting trial 94 with parameters: {'dropout_rate': 0.2946713998579394, 'weight_decay': 1e-06, 'lr': 0.0033826459281497364, 'batch_size': 256, 'early_stopping_patience': 21, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 512, 'activation': 'leaky_relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 2.8361, Val Loss: 132.6789
  Epoch 10... Train Loss: 0.9232, Val Loss: 1.1024
  Epoch 20... Train Loss: 0.5545, Val Loss: 0.5210
  Epoch 30... Train Loss: 0.4186, Val Loss: 0.4447
  Epoch 40... Train Loss: 0.3183, Val Loss: 0.3284
  Epoch 50... Train Loss: 0.4518, Val Loss: 0.3228
  Epoch 60... Train Loss: 0.3152, Val Loss: 0.3127
Fold 1 - MSE: 39.8121, RMSE: 6.3097, MAE: 4.1173
Starting fold 2...
  Epoch 0... Train Loss: 9.0131, Val Loss: 620.3683
  Epoch 10... Train Loss: 0.6341, Val Loss: 0.7980
  Epoch 20... Train Loss: 0.4054, Val Loss: 0.6366
  Epoch 30... Train Loss: 0.3121, Val Loss: 0.4481
  Epoch 40... Train Loss: 0.2394, Val Loss: 0.3955
  Epoch 50... Train Loss: 0.2420, Val Loss: 0.3816
  Epoch 60... Train Loss: 0.2631, Val Loss: 0.4280
  Epoch 70... Train Loss: 0.2513, Val Loss: 0.3757
  Epoch 80... Train Loss: 0.2194, Val Loss: 0.3723
Fold 2 - MSE: 37.1736, RMSE: 6.0970, MAE: 3.8667
Starting fold 3...
  Epoch 0... Train Loss: 7.5717, Val Loss: 187.2610
  Epoch 10... Train Loss: 0.5722, Val Loss: 0.7635
  Epoch 20... Train Loss: 0.3597, Val Loss: 0.5436
  Epoch 30... Train Loss: 0.3174, Val Loss: 0.4513
  Epoch 40... Train Loss: 0.2709, Val Loss: 0.4100
  Epoch 50... Train Loss: 0.2453, Val Loss: 0.4055
  Epoch 60... Train Loss: 0.2180, Val Loss: 0.4109
  Epoch 70... Train Loss: 0.2100, Val Loss: 0.3967
  Epoch 80... Train Loss: 0.2125, Val Loss: 0.3943
  Epoch 90... Train Loss: 0.1864, Val Loss: 0.3947
Fold 3 - MSE: 23.1148, RMSE: 4.8078, MAE: 3.0095
Starting fold 4...
  Epoch 0... Train Loss: 8.4587, Val Loss: 210.6765
  Epoch 10... Train Loss: 0.6874, Val Loss: 0.6011
  Epoch 20... Train Loss: 0.3926, Val Loss: 0.5316
  Epoch 30... Train Loss: 0.2769, Val Loss: 0.5484
  Epoch 40... Train Loss: 0.2863, Val Loss: 0.5188
  Epoch 50... Train Loss: 0.2072, Val Loss: 0.4656
  Epoch 60... Train Loss: 0.1858, Val Loss: 0.4689
Fold 4 - MSE: 32.3084, RMSE: 5.6841, MAE: 4.4297
Starting fold 5...
  Epoch 0... Train Loss: 7.3547, Val Loss: 145.3910
  Epoch 10... Train Loss: 0.6215, Val Loss: 1.5072
  Epoch 20... Train Loss: 0.4791, Val Loss: 1.1015
  Epoch 30... Train Loss: 0.3056, Val Loss: 0.8894
  Epoch 40... Train Loss: 0.2840, Val Loss: 0.8480
  Epoch 50... Train Loss: 0.2510, Val Loss: 0.8179
  Epoch 60... Train Loss: 0.2254, Val Loss: 0.7794
  Epoch 70... Train Loss: 0.2328, Val Loss: 0.7808
  Epoch 80... Train Loss: 0.2610, Val Loss: 0.7638
  Epoch 90... Train Loss: 0.2131, Val Loss: 0.7605
  Epoch 100... Train Loss: 0.2252, Val Loss: 0.7595

[INFO 04-02 10:20:10] ax.service.ax_client: Completed trial 94 with data: {'avg_rmse_nonzero': 5.264836}.

Fold 5 - MSE: 11.7350, RMSE: 3.4256, MAE: 2.8641

Mean CV MSE: 28.8288, Mean CV RMSE: 5.2648, Mean CV MAE: 3.6575
Completed trial 94 with mean RMSE: 5.2648 ± 0.5269
Saved Ax client checkpoint

[INFO 04-02 10:20:17] ax.service.ax_client: Generated new trial 95 with parameters {'dropout_rate': 0.134657, 'weight_decay': 1e-06, 'lr': 0.003732, 'batch_size': 256, 'early_stopping_patience': 10, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 512, 'activation': 'relu'} using model BoTorch.

Starting trial 95 with parameters: {'dropout_rate': 0.13465706781587392, 'weight_decay': 1e-06, 'lr': 0.003732125682026073, 'batch_size': 256, 'early_stopping_patience': 10, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 512, 'activation': 'relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 9.6741, Val Loss: 65.9488
  Epoch 10... Train Loss: 0.9201, Val Loss: 1.2710
  Epoch 20... Train Loss: 0.4710, Val Loss: 0.5576
  Epoch 30... Train Loss: 0.3759, Val Loss: 0.5036
  Epoch 40... Train Loss: 0.3597, Val Loss: 0.4386
  Epoch 50... Train Loss: 0.4947, Val Loss: 0.3548
  Epoch 60... Train Loss: 0.3429, Val Loss: 0.3352
  Epoch 70... Train Loss: 0.3219, Val Loss: 0.3193
  Epoch 80... Train Loss: 0.3868, Val Loss: 0.3025
  Epoch 90... Train Loss: 0.2976, Val Loss: 0.2984
  Epoch 100... Train Loss: 0.3378, Val Loss: 0.2997
Fold 1 - MSE: 38.7618, RMSE: 6.2259, MAE: 4.0648
Starting fold 2...
  Epoch 0... Train Loss: 6.9823, Val Loss: 701.9945
  Epoch 10... Train Loss: 0.6900, Val Loss: 0.7947
  Epoch 20... Train Loss: 0.3881, Val Loss: 0.6623
  Epoch 30... Train Loss: 0.3042, Val Loss: 0.4418
  Epoch 40... Train Loss: 0.2313, Val Loss: 0.4051
Fold 2 - MSE: 33.8043, RMSE: 5.8141, MAE: 3.5449
Starting fold 3...
  Epoch 0... Train Loss: 7.5814, Val Loss: 347.3131
  Epoch 10... Train Loss: 0.5877, Val Loss: 0.7460
  Epoch 20... Train Loss: 0.4047, Val Loss: 0.6260
  Epoch 30... Train Loss: 0.3280, Val Loss: 0.5183
  Epoch 40... Train Loss: 0.2103, Val Loss: 0.4264
Fold 3 - MSE: 37.2192, RMSE: 6.1008, MAE: 3.6312
Starting fold 4...
  Epoch 0... Train Loss: 9.0495, Val Loss: 464.7927
  Epoch 10... Train Loss: 0.7629, Val Loss: 0.5177
  Epoch 20... Train Loss: 0.4537, Val Loss: 0.5125
Fold 4 - MSE: 33.2444, RMSE: 5.7658, MAE: 4.5985
Starting fold 5...
  Epoch 0... Train Loss: 9.2521, Val Loss: 424.0479
  Epoch 10... Train Loss: 0.7161, Val Loss: 1.3863
  Epoch 20... Train Loss: 0.5871, Val Loss: 1.3493
  Epoch 30... Train Loss: 0.4994, Val Loss: 1.2012
  Epoch 40... Train Loss: 0.3544, Val Loss: 1.0060
  Epoch 50... Train Loss: 0.2589, Val Loss: 0.8817
  Epoch 60... Train Loss: 0.2567, Val Loss: 0.8419
  Epoch 70... Train Loss: 0.2538, Val Loss: 0.8300
Fold 5 - MSE: 5.8544, RMSE: 2.4196, MAE: 1.7180

Mean CV MSE: 29.7768, Mean CV RMSE: 5.2652, Mean CV MAE: 3.5115

[INFO 04-02 10:20:29] ax.service.ax_client: Completed trial 95 with data: {'avg_rmse_nonzero': 5.265237}.

Completed trial 95 with mean RMSE: 5.2652 ± 0.7166
Saved Ax client checkpoint

[INFO 04-02 10:20:36] ax.service.ax_client: Generated new trial 96 with parameters {'dropout_rate': 0.0, 'weight_decay': 1e-06, 'lr': 0.002715, 'batch_size': 256, 'early_stopping_patience': 36, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 512, 'activation': 'leaky_relu'} using model BoTorch.

Starting trial 96 with parameters: {'dropout_rate': 0.0, 'weight_decay': 1e-06, 'lr': 0.0027146073835491624, 'batch_size': 256, 'early_stopping_patience': 36, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 512, 'activation': 'leaky_relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 4.7529, Val Loss: 43.1176
  Epoch 10... Train Loss: 0.7030, Val Loss: 1.0552
  Epoch 20... Train Loss: 0.4430, Val Loss: 0.4973
  Epoch 30... Train Loss: 0.3678, Val Loss: 0.5242
  Epoch 40... Train Loss: 0.3198, Val Loss: 0.3604
  Epoch 50... Train Loss: 0.3831, Val Loss: 0.3608
  Epoch 60... Train Loss: 0.3118, Val Loss: 0.3454
  Epoch 70... Train Loss: 0.2631, Val Loss: 0.3318
  Epoch 80... Train Loss: 0.3144, Val Loss: 0.3078
  Epoch 90... Train Loss: 0.2344, Val Loss: 0.2988
  Epoch 100... Train Loss: 0.2856, Val Loss: 0.3048
  Epoch 110... Train Loss: 0.2648, Val Loss: 0.2875
  Epoch 120... Train Loss: 0.3713, Val Loss: 0.3329
  Epoch 130... Train Loss: 0.2511, Val Loss: 0.3429
  Epoch 140... Train Loss: 0.2696, Val Loss: 0.3040
Fold 1 - MSE: 44.4051, RMSE: 6.6637, MAE: 4.3514
Starting fold 2...
  Epoch 0... Train Loss: 5.7926, Val Loss: 19.6898
  Epoch 10... Train Loss: 0.5678, Val Loss: 0.8131
  Epoch 20... Train Loss: 0.3044, Val Loss: 0.5279
  Epoch 30... Train Loss: 0.2668, Val Loss: 0.3962
  Epoch 40... Train Loss: 0.1850, Val Loss: 0.4114
  Epoch 50... Train Loss: 0.1889, Val Loss: 0.3596
  Epoch 60... Train Loss: 0.2136, Val Loss: 0.3962
  Epoch 70... Train Loss: 0.1835, Val Loss: 0.3418
  Epoch 80... Train Loss: 0.1535, Val Loss: 0.3631
  Epoch 90... Train Loss: 0.1604, Val Loss: 0.3415
Fold 2 - MSE: 34.0131, RMSE: 5.8321, MAE: 3.5894
Starting fold 3...
  Epoch 0... Train Loss: 8.0432, Val Loss: 50.6321
  Epoch 10... Train Loss: 0.6216, Val Loss: 0.7722
  Epoch 20... Train Loss: 0.3914, Val Loss: 0.6240
  Epoch 30... Train Loss: 0.2986, Val Loss: 0.4744
  Epoch 40... Train Loss: 0.1981, Val Loss: 0.4297
  Epoch 50... Train Loss: 0.2045, Val Loss: 0.4443
  Epoch 60... Train Loss: 0.1724, Val Loss: 0.4259
  Epoch 70... Train Loss: 0.1719, Val Loss: 0.5001
  Epoch 80... Train Loss: 0.1818, Val Loss: 0.3679
  Epoch 90... Train Loss: 0.1388, Val Loss: 0.3415
  Epoch 100... Train Loss: 0.1574, Val Loss: 0.3586
  Epoch 110... Train Loss: 0.1386, Val Loss: 0.3367
  Epoch 120... Train Loss: 0.1483, Val Loss: 0.3382
  Epoch 130... Train Loss: 0.1343, Val Loss: 0.3164
  Epoch 140... Train Loss: 0.1313, Val Loss: 0.3223
  Epoch 150... Train Loss: 0.1331, Val Loss: 0.3130
  Epoch 160... Train Loss: 0.1271, Val Loss: 0.3044
  Epoch 170... Train Loss: 0.1350, Val Loss: 0.3010
  Epoch 180... Train Loss: 0.1191, Val Loss: 0.2973
  Epoch 190... Train Loss: 0.1133, Val Loss: 0.2987
  Epoch 200... Train Loss: 0.1289, Val Loss: 0.3025
Fold 3 - MSE: 23.3951, RMSE: 4.8369, MAE: 3.3361
Starting fold 4...
  Epoch 0... Train Loss: 8.5531, Val Loss: 43.3486
  Epoch 10... Train Loss: 0.6145, Val Loss: 0.5603
  Epoch 20... Train Loss: 0.3280, Val Loss: 0.5964
  Epoch 30... Train Loss: 0.2390, Val Loss: 0.5443
  Epoch 40... Train Loss: 0.1951, Val Loss: 0.4970
  Epoch 50... Train Loss: 0.1372, Val Loss: 0.4731
  Epoch 60... Train Loss: 0.1381, Val Loss: 0.4951
  Epoch 70... Train Loss: 0.1425, Val Loss: 0.4400
  Epoch 80... Train Loss: 0.1511, Val Loss: 0.5332
  Epoch 90... Train Loss: 0.1166, Val Loss: 0.4490
  Epoch 100... Train Loss: 0.1155, Val Loss: 0.4434
Fold 4 - MSE: 28.7783, RMSE: 5.3645, MAE: 4.5212
Starting fold 5...
  Epoch 0... Train Loss: 6.6042, Val Loss: 49.0994
  Epoch 10... Train Loss: 0.6013, Val Loss: 1.3116
  Epoch 20... Train Loss: 0.3686, Val Loss: 0.8884
  Epoch 30... Train Loss: 0.2279, Val Loss: 0.7435
  Epoch 40... Train Loss: 0.1998, Val Loss: 0.7540
  Epoch 50... Train Loss: 0.1879, Val Loss: 0.7213
  Epoch 60... Train Loss: 0.1693, Val Loss: 0.7217
  Epoch 70... Train Loss: 0.1720, Val Loss: 0.6521
  Epoch 80... Train Loss: 0.1581, Val Loss: 0.6868
  Epoch 90... Train Loss: 0.1484, Val Loss: 0.6621
  Epoch 100... Train Loss: 0.1348, Val Loss: 0.6510

[INFO 04-02 10:20:56] ax.service.ax_client: Completed trial 96 with data: {'avg_rmse_nonzero': 5.125435}.

  Epoch 110... Train Loss: 0.1303, Val Loss: 0.6381
Fold 5 - MSE: 8.5849, RMSE: 2.9300, MAE: 2.1603

Mean CV MSE: 27.8353, Mean CV RMSE: 5.1254, Mean CV MAE: 3.5917
Completed trial 96 with mean RMSE: 5.1254 ± 0.6255
Saved Ax client checkpoint

[INFO 04-02 10:21:03] ax.service.ax_client: Generated new trial 97 with parameters {'dropout_rate': 0.070956, 'weight_decay': 1e-06, 'lr': 0.003023, 'batch_size': 256, 'early_stopping_patience': 18, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 512, 'activation': 'leaky_relu'} using model BoTorch.

Starting trial 97 with parameters: {'dropout_rate': 0.07095621515728066, 'weight_decay': 1e-06, 'lr': 0.0030231286188883797, 'batch_size': 256, 'early_stopping_patience': 18, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 512, 'activation': 'leaky_relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 8.5309, Val Loss: 71.5026
  Epoch 10... Train Loss: 0.8907, Val Loss: 1.0177
  Epoch 20... Train Loss: 0.4767, Val Loss: 0.6075
  Epoch 30... Train Loss: 0.4620, Val Loss: 0.5034
  Epoch 40... Train Loss: 0.3524, Val Loss: 0.4073
  Epoch 50... Train Loss: 0.4258, Val Loss: 0.3654
  Epoch 60... Train Loss: 0.3072, Val Loss: 0.3258
  Epoch 70... Train Loss: 0.2858, Val Loss: 0.3309
  Epoch 80... Train Loss: 0.3943, Val Loss: 0.2932
  Epoch 90... Train Loss: 0.2627, Val Loss: 0.2932
  Epoch 100... Train Loss: 0.3184, Val Loss: 0.2926
Fold 1 - MSE: 39.9850, RMSE: 6.3234, MAE: 4.3266
Starting fold 2...
  Epoch 0... Train Loss: 7.0746, Val Loss: 143.1849
  Epoch 10... Train Loss: 0.6057, Val Loss: 0.8807
  Epoch 20... Train Loss: 0.3397, Val Loss: 0.6203
  Epoch 30... Train Loss: 0.2932, Val Loss: 0.4067
  Epoch 40... Train Loss: 0.2000, Val Loss: 0.4584
  Epoch 50... Train Loss: 0.1997, Val Loss: 0.3752
  Epoch 60... Train Loss: 0.2274, Val Loss: 0.3982
  Epoch 70... Train Loss: 0.1879, Val Loss: 0.3605
Fold 2 - MSE: 43.4296, RMSE: 6.5901, MAE: 3.9151
Starting fold 3...
  Epoch 0... Train Loss: 8.1711, Val Loss: 99.0820
  Epoch 10... Train Loss: 0.5761, Val Loss: 0.6883
  Epoch 20... Train Loss: 0.3370, Val Loss: 0.5769
  Epoch 30... Train Loss: 0.2758, Val Loss: 0.4487
  Epoch 40... Train Loss: 0.2071, Val Loss: 0.4431
  Epoch 50... Train Loss: 0.1928, Val Loss: 0.4056
  Epoch 60... Train Loss: 0.1824, Val Loss: 0.4115
  Epoch 70... Train Loss: 0.1853, Val Loss: 0.4100
  Epoch 80... Train Loss: 0.1776, Val Loss: 0.3990
  Epoch 90... Train Loss: 0.1629, Val Loss: 0.3907
Fold 3 - MSE: 17.5324, RMSE: 4.1872, MAE: 2.7522
Starting fold 4...
  Epoch 0... Train Loss: 8.2170, Val Loss: 85.5974
  Epoch 10... Train Loss: 0.6303, Val Loss: 0.7249
  Epoch 20... Train Loss: 0.3217, Val Loss: 0.5723
  Epoch 30... Train Loss: 0.2123, Val Loss: 0.4963
  Epoch 40... Train Loss: 0.1704, Val Loss: 0.4787
  Epoch 50... Train Loss: 0.1455, Val Loss: 0.4455
  Epoch 60... Train Loss: 0.1458, Val Loss: 0.4467
Fold 4 - MSE: 31.9095, RMSE: 5.6489, MAE: 4.5307
Starting fold 5...
  Epoch 0... Train Loss: 9.6140, Val Loss: 242.0011
  Epoch 10... Train Loss: 0.6547, Val Loss: 1.4964
  Epoch 20... Train Loss: 0.4994, Val Loss: 1.1655
  Epoch 30... Train Loss: 0.3400, Val Loss: 0.9356
  Epoch 40... Train Loss: 0.2563, Val Loss: 0.8158
  Epoch 50... Train Loss: 0.2068, Val Loss: 0.7877
  Epoch 60... Train Loss: 0.1899, Val Loss: 0.7791
Fold 5 - MSE: 5.2148, RMSE: 2.2836, MAE: 1.9212

Mean CV MSE: 27.6143, Mean CV RMSE: 5.0066, Mean CV MAE: 3.4892

[INFO 04-02 10:21:18] ax.service.ax_client: Completed trial 97 with data: {'avg_rmse_nonzero': 5.00662}.

Completed trial 97 with mean RMSE: 5.0066 ± 0.7981
Saved Ax client checkpoint

[INFO 04-02 10:21:25] ax.service.ax_client: Generated new trial 98 with parameters {'dropout_rate': 0.180614, 'weight_decay': 1e-06, 'lr': 0.002735, 'batch_size': 256, 'early_stopping_patience': 47, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 128, 'activation': 'relu'} using model BoTorch.

Starting trial 98 with parameters: {'dropout_rate': 0.18061403952742355, 'weight_decay': 1e-06, 'lr': 0.002735149630043871, 'batch_size': 256, 'early_stopping_patience': 47, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 128, 'activation': 'relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 1.7686, Val Loss: 62.0797
  Epoch 10... Train Loss: 0.7138, Val Loss: 0.7315
  Epoch 20... Train Loss: 0.4689, Val Loss: 0.4074
  Epoch 30... Train Loss: 0.3494, Val Loss: 0.3871
  Epoch 40... Train Loss: 0.3077, Val Loss: 0.3848
  Epoch 50... Train Loss: 0.4078, Val Loss: 0.3923
  Epoch 60... Train Loss: 0.3056, Val Loss: 0.3365
  Epoch 70... Train Loss: 0.3077, Val Loss: 0.3646
  Epoch 80... Train Loss: 0.3177, Val Loss: 0.3634
Fold 1 - MSE: 38.2414, RMSE: 6.1840, MAE: 4.0274
Starting fold 2...
  Epoch 0... Train Loss: 6.9113, Val Loss: 27.0397
  Epoch 10... Train Loss: 0.5736, Val Loss: 0.8189
  Epoch 20... Train Loss: 0.3340, Val Loss: 0.5820
  Epoch 30... Train Loss: 0.2979, Val Loss: 0.4291
  Epoch 40... Train Loss: 0.2152, Val Loss: 0.4676
  Epoch 50... Train Loss: 0.2244, Val Loss: 0.3487
  Epoch 60... Train Loss: 0.2409, Val Loss: 0.3731
  Epoch 70... Train Loss: 0.2354, Val Loss: 0.3450
  Epoch 80... Train Loss: 0.2138, Val Loss: 0.3616
  Epoch 90... Train Loss: 0.2035, Val Loss: 0.3184
  Epoch 100... Train Loss: 0.1964, Val Loss: 0.3383
  Epoch 110... Train Loss: 0.1539, Val Loss: 0.3355
  Epoch 120... Train Loss: 0.1913, Val Loss: 0.3649
  Epoch 130... Train Loss: 0.1728, Val Loss: 0.3509
Fold 2 - MSE: 42.6775, RMSE: 6.5328, MAE: 3.8756
Starting fold 3...
  Epoch 0... Train Loss: 7.2047, Val Loss: 21.7088
  Epoch 10... Train Loss: 0.5169, Val Loss: 0.7031
  Epoch 20... Train Loss: 0.3407, Val Loss: 0.5845
  Epoch 30... Train Loss: 0.2840, Val Loss: 0.4432
  Epoch 40... Train Loss: 0.2305, Val Loss: 0.4284
  Epoch 50... Train Loss: 0.2251, Val Loss: 0.4043
  Epoch 60... Train Loss: 0.2013, Val Loss: 0.4541
  Epoch 70... Train Loss: 0.1923, Val Loss: 0.4101
  Epoch 80... Train Loss: 0.2133, Val Loss: 0.4216
  Epoch 90... Train Loss: 0.1686, Val Loss: 0.3641
  Epoch 100... Train Loss: 0.1812, Val Loss: 0.3798
  Epoch 110... Train Loss: 0.1589, Val Loss: 0.3676
  Epoch 120... Train Loss: 0.1741, Val Loss: 0.3542
  Epoch 130... Train Loss: 0.1490, Val Loss: 0.3524
  Epoch 140... Train Loss: 0.1480, Val Loss: 0.3650
  Epoch 150... Train Loss: 0.1634, Val Loss: 0.3582
  Epoch 160... Train Loss: 0.1674, Val Loss: 0.3548
Fold 3 - MSE: 22.1147, RMSE: 4.7026, MAE: 3.0338
Starting fold 4...
  Epoch 0... Train Loss: 7.9384, Val Loss: 204.3937
  Epoch 10... Train Loss: 0.6064, Val Loss: 0.6606
  Epoch 20... Train Loss: 0.3188, Val Loss: 0.5854
  Epoch 30... Train Loss: 0.2497, Val Loss: 0.5428
  Epoch 40... Train Loss: 0.2135, Val Loss: 0.4705
  Epoch 50... Train Loss: 0.1621, Val Loss: 0.5184
  Epoch 60... Train Loss: 0.1678, Val Loss: 0.4597
  Epoch 70... Train Loss: 0.1560, Val Loss: 0.4594
  Epoch 80... Train Loss: 0.1635, Val Loss: 0.5104
  Epoch 90... Train Loss: 0.1428, Val Loss: 0.4585
  Epoch 100... Train Loss: 0.1501, Val Loss: 0.4375
  Epoch 110... Train Loss: 0.1311, Val Loss: 0.4388
  Epoch 120... Train Loss: 0.1413, Val Loss: 0.4349
  Epoch 130... Train Loss: 0.1530, Val Loss: 0.4319
Fold 4 - MSE: 33.3237, RMSE: 5.7727, MAE: 4.6748
Starting fold 5...
  Epoch 0... Train Loss: 7.8894, Val Loss: 8.4823
  Epoch 10... Train Loss: 0.6317, Val Loss: 1.4503
  Epoch 20... Train Loss: 0.4770, Val Loss: 1.0553
  Epoch 30... Train Loss: 0.3227, Val Loss: 0.8899
  Epoch 40... Train Loss: 0.2765, Val Loss: 0.8218
  Epoch 50... Train Loss: 0.2349, Val Loss: 0.7546
  Epoch 60... Train Loss: 0.2318, Val Loss: 0.7801
  Epoch 70... Train Loss: 0.2133, Val Loss: 0.7435
  Epoch 80... Train Loss: 0.1980, Val Loss: 0.7369
  Epoch 90... Train Loss: 0.1883, Val Loss: 0.7286
  Epoch 100... Train Loss: 0.1767, Val Loss: 0.7119
  Epoch 110... Train Loss: 0.1782, Val Loss: 0.6983
  Epoch 120... Train Loss: 0.1701, Val Loss: 0.7154
  Epoch 130... Train Loss: 0.1728, Val Loss: 0.6942
  Epoch 140... Train Loss: 0.1701, Val Loss: 0.6950
  Epoch 150... Train Loss: 0.1634, Val Loss: 0.7046
  Epoch 160... Train Loss: 0.1668, Val Loss: 0.6973
  Epoch 170... Train Loss: 0.1567, Val Loss: 0.6968
  Epoch 180... Train Loss: 0.1465, Val Loss: 0.6918
  Epoch 190... Train Loss: 0.1582, Val Loss: 0.6873

[INFO 04-02 10:21:49] ax.service.ax_client: Completed trial 98 with data: {'avg_rmse_nonzero': 5.493186}.

  Epoch 200... Train Loss: 0.1524, Val Loss: 0.6960
Fold 5 - MSE: 18.2659, RMSE: 4.2739, MAE: 3.6958

Mean CV MSE: 30.9247, Mean CV RMSE: 5.4932, Mean CV MAE: 3.8615
Completed trial 98 with mean RMSE: 5.4932 ± 0.4329
Saved Ax client checkpoint

[INFO 04-02 10:21:56] ax.service.ax_client: Generated new trial 99 with parameters {'dropout_rate': 0.0, 'weight_decay': 0.005411, 'lr': 0.002379, 'batch_size': 256, 'early_stopping_patience': 12, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 128, 'activation': 'leaky_relu'} using model BoTorch.

Starting trial 99 with parameters: {'dropout_rate': 0.0, 'weight_decay': 0.005411252119188789, 'lr': 0.0023786499051302295, 'batch_size': 256, 'early_stopping_patience': 12, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 128, 'activation': 'leaky_relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 2.3404, Val Loss: 29.6148
  Epoch 10... Train Loss: 0.6567, Val Loss: 0.6541
  Epoch 20... Train Loss: 0.4761, Val Loss: 0.3791
  Epoch 30... Train Loss: 0.3592, Val Loss: 0.4276
Fold 1 - MSE: 36.6281, RMSE: 6.0521, MAE: 4.0636
Starting fold 2...
  Epoch 0... Train Loss: 6.5628, Val Loss: 9.1879
  Epoch 10... Train Loss: 0.5504, Val Loss: 0.7018
  Epoch 20... Train Loss: 0.2783, Val Loss: 0.4806
  Epoch 30... Train Loss: 0.2761, Val Loss: 0.3779
  Epoch 40... Train Loss: 0.1998, Val Loss: 0.3660
Fold 2 - MSE: 37.8337, RMSE: 6.1509, MAE: 3.8428
Starting fold 3...
  Epoch 0... Train Loss: 6.8919, Val Loss: 23.0733
  Epoch 10... Train Loss: 0.4890, Val Loss: 0.7147
  Epoch 20... Train Loss: 0.2518, Val Loss: 0.5231
  Epoch 30... Train Loss: 0.2306, Val Loss: 0.4817
  Epoch 40... Train Loss: 0.2209, Val Loss: 0.4444
  Epoch 50... Train Loss: 0.1698, Val Loss: 0.3906
  Epoch 60... Train Loss: 0.1544, Val Loss: 0.3731
  Epoch 70... Train Loss: 0.1514, Val Loss: 0.3622
Fold 3 - MSE: 61.3958, RMSE: 7.8355, MAE: 4.2622
Starting fold 4...
  Epoch 0... Train Loss: 9.7289, Val Loss: 64.8759
  Epoch 10... Train Loss: 0.6558, Val Loss: 0.5345
  Epoch 20... Train Loss: 0.3054, Val Loss: 0.4356
  Epoch 30... Train Loss: 0.2167, Val Loss: 0.3916
  Epoch 40... Train Loss: 0.1528, Val Loss: 0.3977
Fold 4 - MSE: 30.5178, RMSE: 5.5243, MAE: 4.3814
Starting fold 5...
  Epoch 0... Train Loss: 8.4532, Val Loss: 25.8983
  Epoch 10... Train Loss: 0.6642, Val Loss: 1.3899
  Epoch 20... Train Loss: 0.3988, Val Loss: 1.0030
  Epoch 30... Train Loss: 0.2556, Val Loss: 0.7845
  Epoch 40... Train Loss: 0.2288, Val Loss: 0.6725

[INFO 04-02 10:22:06] ax.service.ax_client: Completed trial 99 with data: {'avg_rmse_nonzero': 5.642336}.

  Epoch 50... Train Loss: 0.1749, Val Loss: 0.7284
Fold 5 - MSE: 7.0162, RMSE: 2.6488, MAE: 2.0585

Mean CV MSE: 34.6783, Mean CV RMSE: 5.6423, Mean CV MAE: 3.7217
Completed trial 99 with mean RMSE: 5.6423 ± 0.8430
Saved Ax client checkpoint

In [48]:
# Get best parameters after all trials
best_parameters, values = ax_client_dmax_nn.get_best_parameters()
print(f"\n{'='*60}")
print("OPTIMIZATION COMPLETE")
print('='*60)
print(f"Best parameters: {best_parameters}")
print(f"Best Non-zero RMSE: {values[0]['avg_rmse_nonzero']:.4f}")

============================================================
OPTIMIZATION COMPLETE
============================================================
Best parameters: {'dropout_rate': 0.07095621515728066, 'weight_decay': 1e-06, 'lr': 0.0030231286188883797, 'batch_size': 256, 'early_stopping_patience': 18, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 512, 'activation': 'leaky_relu'}
Best Non-zero RMSE: 5.3189

In [49]:
#evaluate the best parameters on the test set

# Auto-detect device
if torch.cuda.is_available():
    device = torch.device('cuda')
elif torch.backends.mps.is_available():
    device = torch.device('mps')
else:
    device = torch.device('cpu')
print(f"Using device: {device}")

#best parameters from the ax optimization loop
best_parameters_NN_dmax = {'dropout_rate': 0.07095621515728066, 'weight_decay': 1e-06, 'lr': 0.0030231286188883797, 'batch_size': 256, 'early_stopping_patience': 18, 'n_layers': 3, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 512, 'activation': 'leaky_relu'}

#combine layer dimensions into a list for the model
hidden_layers = [best_parameters_NN_dmax["hidden1"], best_parameters_NN_dmax["hidden2"], best_parameters_NN_dmax["hidden3"]][:best_parameters_NN_dmax["n_layers"]]

#copy the x and y data
X_evaluate_train = X_train_opt.copy()
y_evaluate_train = y_train_opt.copy()
X_evaluate_test = X_test.copy() 
y_evaluate_test = y_test.copy()

#split the train data into train and validation data
X_evaluate_train, X_evaluate_val, y_evaluate_train, y_evaluate_val = train_test_split(X_evaluate_train, y_evaluate_train, test_size=0.2, random_state=42)

#scale the X_data
Scaler_X_evaluate = StandardScaler()
X_evaluate_train_scaled = Scaler_X_evaluate.fit_transform(X_evaluate_train)
X_evaluate_val_scaled = Scaler_X_evaluate.transform(X_evaluate_val)
X_evaluate_test_scaled = Scaler_X_evaluate.transform(X_evaluate_test)

#Scale the y data
Scaler_y_evaluate = StandardScaler()
y_evaluate_train_scaled = Scaler_y_evaluate.fit_transform(np.array(y_evaluate_train).reshape(-1, 1)).flatten()
y_evaluate_val_scaled = Scaler_y_evaluate.transform(np.array(y_evaluate_val).reshape(-1, 1)).flatten()
y_evaluate_test_scaled = Scaler_y_evaluate.transform(np.array(y_evaluate_test).reshape(-1, 1)).flatten()

#convert all data to tensors
X_evaluate_train_tensor = torch.tensor(X_evaluate_train_scaled, dtype=torch.float32).to(device)
y_evaluate_train_tensor = torch.tensor(y_evaluate_train_scaled, dtype=torch.float32).to(device)
X_evaluate_val_tensor = torch.tensor(X_evaluate_val_scaled, dtype=torch.float32).to(device)
y_evaluate_val_tensor = torch.tensor(y_evaluate_val_scaled, dtype=torch.float32).to(device)
X_evaluate_test_tensor = torch.tensor(X_evaluate_test_scaled, dtype=torch.float32).to(device)
y_evaluate_test_tensor = torch.tensor(y_evaluate_test_scaled, dtype=torch.float32).to(device)

#convert tensors to datasets then dataloaders
evaluate_train_ds = TensorDataset(X_evaluate_train_tensor, y_evaluate_train_tensor)
evaluate_train_loader = DataLoader(evaluate_train_ds, batch_size=best_parameters_NN_dmax["batch_size"], shuffle=True, generator=torch.Generator().manual_seed(42))
evaluate_val_ds = TensorDataset(X_evaluate_val_tensor, y_evaluate_val_tensor)
evaluate_val_loader = DataLoader(evaluate_val_ds, batch_size=best_parameters_NN_dmax["batch_size"], shuffle=True, generator=torch.Generator().manual_seed(42))
evaluate_test_ds = TensorDataset(X_evaluate_test_tensor, y_evaluate_test_tensor)
evaluate_test_loader = DataLoader(evaluate_test_ds, batch_size=best_parameters_NN_dmax["batch_size"], shuffle=False, generator=torch.Generator().manual_seed(42))


#initialize the model
input_dim = X_evaluate_train_tensor.shape[1]
model = DmaxNet(input_dim, hidden_layers, best_parameters_NN_dmax["dropout_rate"], best_parameters_NN_dmax["activation"]).to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=best_parameters_NN_dmax["lr"], weight_decay=best_parameters_NN_dmax["weight_decay"])
scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, patience=best_parameters_NN_dmax["early_stopping_patience"] // 3, factor=0.5)
criterion = nn.MSELoss()


best_val_loss = float("inf")
best_state = None
wait = 0

for epoch in range(1000):

    train_loss = train_one_epoch(model, evaluate_train_loader, optimizer, criterion, device)
    val_loss = evaluate(model, evaluate_val_loader, criterion, device)
    if epoch % 10 == 0:
        print(f"  Epoch {epoch}... Train Loss: {train_loss:.4f}, Val Loss: {val_loss:.4f}")
    scheduler.step(val_loss)
    
    if val_loss < best_val_loss:
        best_val_loss = val_loss
        best_state = {k: v.cpu().clone() for k, v in model.state_dict().items()}
        wait = 0
    else:
        wait += 1
        if wait >= best_parameters_NN_dmax["early_stopping_patience"]:
            break

# Restore best model and evaluate on fold test set
model.load_state_dict(best_state)

#predict the fold test set and inverse transform the predictions and actuals back to original scale
y_fold_test_pred_scaled, y_fold_test_actual_scaled = predict(model, evaluate_test_loader, device)
y_fold_test_pred = Scaler_y_evaluate.inverse_transform(y_fold_test_pred_scaled.reshape(-1, 1)).flatten()
y_fold_test_actual = Scaler_y_evaluate.inverse_transform(y_fold_test_actual_scaled.reshape(-1, 1)).flatten()

#calculate the fold mse, rmse, and mae and add to the list of fold metrics
fold_mse = np.mean((y_fold_test_pred - y_fold_test_actual) ** 2)
fold_rmse = np.sqrt(fold_mse)
fold_mae = np.mean(np.abs(y_fold_test_pred - y_fold_test_actual))

#print the fold metrics
print(f"Test Results - MSE: {fold_mse:.4f}, RMSE: {fold_rmse:.4f}, MAE: {fold_mae:.4f}")

Using device: cuda
  Epoch 0... Train Loss: 8.4527, Val Loss: 287.3803
  Epoch 10... Train Loss: 0.7221, Val Loss: 0.5460
  Epoch 20... Train Loss: 0.4962, Val Loss: 0.3565
  Epoch 30... Train Loss: 0.2973, Val Loss: 0.3374
  Epoch 40... Train Loss: 0.2423, Val Loss: 0.3463
  Epoch 50... Train Loss: 0.2020, Val Loss: 0.3327
  Epoch 60... Train Loss: 0.1806, Val Loss: 0.3323
Test Results - MSE: 10.8110, RMSE: 3.2880, MAE: 2.2005

In [57]:
#Define the XGBboost parameter evaluation function for the ax optimization loop of the dmax_xgb model
def evaluate_parameters_XGB_dmax(parameters):
    
    #pull the relevent parameters for the xgboost model from the input parameters
    n_estimators = parameters.get("n_estimators", 100)
    max_depth = parameters.get("max_depth", 6)
    learning_rate = parameters.get("learning_rate", 0.1)
    subsample = parameters.get("subsample", 1.0)
    colsample_bytree = parameters.get("colsample_bytree", 1.0)
    minchild_weight = parameters.get("min_child_weight", 1)
    reg_alpha = parameters.get("reg_alpha", 0)
    reg_lambda = parameters.get("reg_lambda", 1)
    gamma = parameters.get("gamma", 0)
    earlystopping_rounds = parameters.get("early_stopping_rounds", 10)

    
    # Auto-detect device
    if torch.cuda.is_available():
        device = torch.device('cuda')
    elif torch.backends.mps.is_available():
        device = torch.device('mps')
    else:
        device = torch.device('cpu')
    print(f"Using device: {device}")
    
    
    #copy the x and y data
    y_data = y_train_opt.copy()
    x_data = X_train_opt.copy()
    
    #initialize cross fold info
    all_fold_mse = []
    all_fold_rmse = []
    all_fold_mae = []
    
    for fold in range(1,6):
        print(f"Starting fold {fold}...")
        
        #Establish from the folds the train and test data
        X_fold_train = x_data[cv_groups != (fold-1)]
        y_fold_train = np.array(y_data)[cv_groups != (fold-1)]
        
        X_fold_test = x_data[cv_groups == (fold-1)]
        y_fold_test = np.array(y_data)[cv_groups == (fold-1)]
        
        #split the fold train data into train and validation data
        X_fold_train, X_fold_val, y_fold_train, y_fold_val = train_test_split(X_fold_train, y_fold_train, test_size=0.2, random_state=42)
        
        #itialize the xgboost model with the input parameters
        xgb_model = XGBRegressor(
            n_estimators=n_estimators,
            max_depth=max_depth,
            learning_rate=learning_rate,
            subsample=subsample,
            colsample_bytree=colsample_bytree,
            min_child_weight=minchild_weight,
            reg_alpha=reg_alpha,
            reg_lambda=reg_lambda,
            gamma=gamma,
            early_stopping_rounds=earlystopping_rounds,
            random_state=42,
            tree_method="hist",
            device = "cuda"
        )  
        
        #fit the xgboost model with early stopping
        xgb_model.fit(
            X_fold_train, y_fold_train,
            eval_set=[(X_fold_val, y_fold_val)],
            verbose=False
        )
        
        #predict the fold test set
        y_fold_test_pred = xgb_model.predict(X_fold_test)
        y_fold_test_actual = y_fold_test
        
        #calculate the fold mse, rmse, and mae and add to the list of fold metrics
        fold_mse = np.mean((y_fold_test_pred - y_fold_test_actual) ** 2)
        fold_rmse = np.sqrt(fold_mse)
        fold_mae = np.mean(np.abs(y_fold_test_pred - y_fold_test_actual))
        
        all_fold_mse.append(fold_mse)
        all_fold_rmse.append(fold_rmse)
        all_fold_mae.append(fold_mae)
        
        #print the fold metrics
        print(f"Fold {fold} - MSE: {fold_mse:.4f}, RMSE: {fold_rmse:.4f}, MAE: {fold_mae:.4f}")

    mean_rmse = np.mean(all_fold_rmse)
    mean_mse = np.mean(all_fold_mse)
    mean_mae = np.mean(all_fold_mae)
    print(f"\nMean CV MSE: {mean_mse:.4f}, Mean CV RMSE: {mean_rmse:.4f}, Mean CV MAE: {mean_mae:.4f}")
    return mean_rmse, sem(all_fold_rmse)

In [58]:
#define the ax client for the xgboost model
ax_client_xgb_dmax = AxClient()
ax_client_xgb_dmax.create_experiment(
    name="XGB opt CBFV CALPHAD to D_max Regression",
    parameters=[
        {
            "name": "n_estimators",
            "type": "range",
            "bounds": [100, 10000],
            "value_type": "int",
        },
        {
            "name": "max_depth",
            "type": "range",
            "bounds": [3, 100],
            "value_type": "int",
        },
        {
            "name": "learning_rate",
            "type": "range",
            "bounds": [0.005, 0.3],
            "value_type": "float",
            "log_scale": True,
        },
        {
            "name": "subsample",
            "type": "range",
            "bounds": [0.5, 1.0],
            "value_type": "float",

        },
        {
            "name": "colsample_bytree",
            "type": "range",
            "bounds": [0.3, 1.0],
            "value_type": "float",
        },
        {
            "name": "min_child_weight",
            "type": "range",
            "bounds": [1, 20],
            "value_type": "int",
        },
        {
            "name": "reg_alpha",
            "type": "range",
            "bounds": [1e-6, 10.0],
            "value_type": "float",
            "log_scale": True,
        },
        {
            "name": "reg_lambda",
            "type": "range",
            "bounds": [1e-6, 10.0],
            "value_type": "float",
            "log_scale": True,
        },
        {
            "name": "gamma",
            "type": "range",
            "bounds": [1e-6, 5.0],
            "log_scale": True,
            "value_type": "float",
        },
        {
            "name": "early_stopping_rounds",
            "type": "range",
            "bounds": [10, 50],
            "value_type": "int",
        },
    ],
    objectives={"avg_rmse_nonzero": ObjectiveProperties(minimize=True)}
)

[INFO 04-02 10:43:43] ax.generation_strategy.dispatch_utils: Using Generators.BOTORCH_MODULAR since there is at least one ordered parameter and there are no unordered categorical parameters.
[INFO 04-02 10:43:43] ax.generation_strategy.dispatch_utils: Using Bayesian Optimization generation strategy: GenerationStrategy(name='Sobol+BoTorch', steps=[Sobol for 20 trials, BoTorch for subsequent trials]). Iterations after 20 will take longer to generate due to model-fitting.

In [59]:
#Perform the ax optimization loop for the xgboost model
#initialize the save path for the xgboost ax client
ax_client_xgb_dmax_save_path = r"Ax_checkpoints\ax_client_xgb_dmax_checkpoint.json"

#check if there is an existing checkpoint and load it, otherwise start a new optimization loop
try:
    ax_client_xgb_dmax = AxClient.load_from_json_file(filepath=ax_client_xgb_dmax_save_path)
    print(f"Loaded existing Ax client checkpoint from {ax_client_xgb_dmax_save_path}")
    
    completed_trials = len(ax_client_xgb_dmax.experiment.trials)
    target_trials = 100
    remaining_trials = target_trials - completed_trials
    
    print(f"Loaded {completed_trials} completed trials from ax_client_xgb_dmax.json")
    print(f"Remaining trials to reach {target_trials}: {remaining_trials}")
    
    for i in range(remaining_trials):
        parameters, trial_index = ax_client_xgb_dmax.get_next_trial()
        print(f"\nStarting trial {trial_index} with parameters: {parameters}")
        mean_rmse, rmse_sem = evaluate_parameters_XGB_dmax(parameters)
        ax_client_xgb_dmax.complete_trial(trial_index=trial_index, raw_data={"avg_rmse_nonzero": (mean_rmse, rmse_sem)})
        print(f"Completed trial {trial_index} with mean RMSE: {mean_rmse:.4f} ± {rmse_sem:.4f}")
        
        # Save the Ax client state after each trial
        ax_client_xgb_dmax.save_to_json_file(filepath=ax_client_xgb_dmax_save_path)
        print(f"Saved Ax client checkpoint")
    
    
except Exception as e:
    print(f"No existing checkpoint found, starting new optimization loop. Error: {e}")
    
    for i in range(100):
        parameters, trial_index = ax_client_xgb_dmax.get_next_trial()
        print(f"\nStarting trial {trial_index} with parameters: {parameters}")
        mean_rmse, rmse_sem = evaluate_parameters_XGB_dmax(parameters)
        ax_client_xgb_dmax.complete_trial(trial_index=trial_index, raw_data={"avg_rmse_nonzero": (mean_rmse, rmse_sem)})
        print(f"Completed trial {trial_index} with mean RMSE: {mean_rmse:.4f} ± {rmse_sem:.4f}")
        
        # Save the Ax client state after each trial
        ax_client_xgb_dmax.save_to_json_file(filepath=ax_client_xgb_dmax_save_path)
        print(f"Saved Ax client checkpoint")

[INFO 04-02 10:43:44] ax.service.ax_client: Generated new trial 0 with parameters {'n_estimators': 5263, 'max_depth': 64, 'learning_rate': 0.006597, 'subsample': 0.522859, 'colsample_bytree': 0.462448, 'min_child_weight': 4, 'reg_alpha': 2e-05, 'reg_lambda': 0.029245, 'gamma': 2.7e-05, 'early_stopping_rounds': 43} using model Sobol.

No existing checkpoint found, starting new optimization loop. Error: [Errno 2] No such file or directory: 'Ax_checkpoints\\ax_client_xgb_dmax_checkpoint.json'

Starting trial 0 with parameters: {'n_estimators': 5263, 'max_depth': 64, 'learning_rate': 0.006596605959109167, 'subsample': 0.5228592325001955, 'colsample_bytree': 0.46244767457246777, 'min_child_weight': 4, 'reg_alpha': 1.95441553706182e-05, 'reg_lambda': 0.029244928589894813, 'gamma': 2.686119407922972e-05, 'early_stopping_rounds': 43}
Using device: cuda
Starting fold 1...

c:\Users\Chris\Documents\ML_Project\ML_GFA_env\Lib\site-packages\xgboost\core.py:774: UserWarning:

[10:44:28] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\common\error_msg.cc:62: Falling back to prediction using DMatrix due to mismatched devices. This might lead to higher memory usage and slower performance. XGBoost is running on: cuda:0, while the input data is on: cpu.
Potential solutions:
- Use a data structure that matches the device ordinal in the booster.
- Set the device for booster before call to inplace_predict.

This warning will only be shown once.

Fold 1 - MSE: 36.8088, RMSE: 6.0670, MAE: 3.9734
Starting fold 2...
Fold 2 - MSE: 36.0286, RMSE: 6.0024, MAE: 3.8601
Starting fold 3...
Fold 3 - MSE: 8.0210, RMSE: 2.8321, MAE: 2.0930
Starting fold 4...
Fold 4 - MSE: 28.0342, RMSE: 5.2947, MAE: 4.4408
Starting fold 5...

[INFO 04-02 10:48:35] ax.service.ax_client: Completed trial 0 with data: {'avg_rmse_nonzero': 4.431959}.
[INFO 04-02 10:48:36] ax.service.ax_client: Generated new trial 1 with parameters {'n_estimators': 3102, 'max_depth': 7, 'learning_rate': 0.281275, 'subsample': 0.986166, 'colsample_bytree': 0.788279, 'min_child_weight': 12, 'reg_alpha': 0.265844, 'reg_lambda': 9e-06, 'gamma': 0.371676, 'early_stopping_rounds': 15} using model Sobol.

Fold 5 - MSE: 3.8553, RMSE: 1.9635, MAE: 1.4450

Mean CV MSE: 22.5496, Mean CV RMSE: 4.4320, Mean CV MAE: 3.1625
Completed trial 0 with mean RMSE: 4.4320 ± 0.8525
Saved Ax client checkpoint

Starting trial 1 with parameters: {'n_estimators': 3102, 'max_depth': 7, 'learning_rate': 0.28127486003696084, 'subsample': 0.986165574286133, 'colsample_bytree': 0.7882785874418914, 'min_child_weight': 12, 'reg_alpha': 0.2658443572832553, 'reg_lambda': 9.093431006421382e-06, 'gamma': 0.37167631509490584, 'early_stopping_rounds': 15}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 42.3753, RMSE: 6.5096, MAE: 4.3865
Starting fold 2...
Fold 2 - MSE: 44.8334, RMSE: 6.6958, MAE: 4.1103
Starting fold 3...
Fold 3 - MSE: 8.2054, RMSE: 2.8645, MAE: 2.0521
Starting fold 4...
Fold 4 - MSE: 42.4326, RMSE: 6.5140, MAE: 5.3675
Starting fold 5...

[INFO 04-02 10:48:52] ax.service.ax_client: Completed trial 1 with data: {'avg_rmse_nonzero': 4.92109}.
[INFO 04-02 10:48:52] ax.service.ax_client: Generated new trial 2 with parameters {'n_estimators': 2052, 'max_depth': 80, 'learning_rate': 0.025194, 'subsample': 0.658827, 'colsample_bytree': 0.999975, 'min_child_weight': 19, 'reg_alpha': 0.000124, 'reg_lambda': 0.001079, 'gamma': 0.026118, 'early_stopping_rounds': 22} using model Sobol.

Fold 5 - MSE: 4.0865, RMSE: 2.0215, MAE: 1.5112

Mean CV MSE: 28.3866, Mean CV RMSE: 4.9211, Mean CV MAE: 3.4855
Completed trial 1 with mean RMSE: 4.9211 ± 1.0210
Saved Ax client checkpoint

Starting trial 2 with parameters: {'n_estimators': 2052, 'max_depth': 80, 'learning_rate': 0.025193864031865864, 'subsample': 0.6588269853964448, 'colsample_bytree': 0.9999750879593192, 'min_child_weight': 19, 'reg_alpha': 0.0001238626923472322, 'reg_lambda': 0.0010794366207629716, 'gamma': 0.02611838739905483, 'early_stopping_rounds': 22}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 38.0954, RMSE: 6.1721, MAE: 3.9379
Starting fold 2...
Fold 2 - MSE: 34.3126, RMSE: 5.8577, MAE: 3.6217
Starting fold 3...
Fold 3 - MSE: 7.2718, RMSE: 2.6966, MAE: 1.7763
Starting fold 4...
Fold 4 - MSE: 31.6976, RMSE: 5.6301, MAE: 4.6360
Starting fold 5...

[INFO 04-02 10:50:42] ax.service.ax_client: Completed trial 2 with data: {'avg_rmse_nonzero': 4.532404}.
[INFO 04-02 10:50:42] ax.service.ax_client: Generated new trial 3 with parameters {'n_estimators': 9782, 'max_depth': 41, 'learning_rate': 0.049796, 'subsample': 0.816523, 'colsample_bytree': 0.622736, 'min_child_weight': 7, 'reg_alpha': 0.034315, 'reg_lambda': 3.367264, 'gamma': 8.9e-05, 'early_stopping_rounds': 40} using model Sobol.

Fold 5 - MSE: 5.3152, RMSE: 2.3055, MAE: 1.8878

Mean CV MSE: 23.3385, Mean CV RMSE: 4.5324, Mean CV MAE: 3.1720
Completed trial 2 with mean RMSE: 4.5324 ± 0.8360
Saved Ax client checkpoint

Starting trial 3 with parameters: {'n_estimators': 9782, 'max_depth': 41, 'learning_rate': 0.04979610749047295, 'subsample': 0.816522610373795, 'colsample_bytree': 0.6227358175441622, 'min_child_weight': 7, 'reg_alpha': 0.034315092031622356, 'reg_lambda': 3.367263889408206, 'gamma': 8.925951500374701e-05, 'early_stopping_rounds': 40}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 39.4368, RMSE: 6.2799, MAE: 4.0884
Starting fold 2...
Fold 2 - MSE: 38.2671, RMSE: 6.1860, MAE: 3.8355
Starting fold 3...
Fold 3 - MSE: 8.1350, RMSE: 2.8522, MAE: 2.1631
Starting fold 4...
Fold 4 - MSE: 41.2490, RMSE: 6.4225, MAE: 5.2762
Starting fold 5...

[INFO 04-02 10:52:13] ax.service.ax_client: Completed trial 3 with data: {'avg_rmse_nonzero': 4.738997}.
[INFO 04-02 10:52:13] ax.service.ax_client: Generated new trial 4 with parameters {'n_estimators': 8561, 'max_depth': 95, 'learning_rate': 0.109134, 'subsample': 0.769684, 'colsample_bytree': 0.481725, 'min_child_weight': 2, 'reg_alpha': 0.000868, 'reg_lambda': 0.000348, 'gamma': 0.004786, 'early_stopping_rounds': 12} using model Sobol.

Fold 5 - MSE: 3.8195, RMSE: 1.9544, MAE: 1.4883

Mean CV MSE: 26.1815, Mean CV RMSE: 4.7390, Mean CV MAE: 3.3703
Completed trial 3 with mean RMSE: 4.7390 ± 0.9648
Saved Ax client checkpoint

Starting trial 4 with parameters: {'n_estimators': 8561, 'max_depth': 95, 'learning_rate': 0.10913419498221197, 'subsample': 0.7696842346340418, 'colsample_bytree': 0.4817252163775265, 'min_child_weight': 2, 'reg_alpha': 0.0008675557858338225, 'reg_lambda': 0.00034780200175776844, 'gamma': 0.004785558188520037, 'early_stopping_rounds': 12}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 38.2384, RMSE: 6.1837, MAE: 4.1109
Starting fold 2...
Fold 2 - MSE: 36.3692, RMSE: 6.0307, MAE: 3.5730
Starting fold 3...
Fold 3 - MSE: 12.9076, RMSE: 3.5927, MAE: 2.7552
Starting fold 4...
Fold 4 - MSE: 31.0791, RMSE: 5.5749, MAE: 4.6544
Starting fold 5...

[INFO 04-02 10:52:45] ax.service.ax_client: Completed trial 4 with data: {'avg_rmse_nonzero': 4.65125}.
[INFO 04-02 10:52:45] ax.service.ax_client: Generated new trial 5 with parameters {'n_estimators': 832, 'max_depth': 38, 'learning_rate': 0.009856, 'subsample': 0.736897, 'colsample_bytree': 0.856611, 'min_child_weight': 14, 'reg_alpha': 0.003616, 'reg_lambda': 1.081224, 'gamma': 0.000797, 'early_stopping_rounds': 50} using model Sobol.

Fold 5 - MSE: 3.5129, RMSE: 1.8743, MAE: 1.3108

Mean CV MSE: 24.4214, Mean CV RMSE: 4.6513, Mean CV MAE: 3.2808
Completed trial 4 with mean RMSE: 4.6513 ± 0.8348
Saved Ax client checkpoint

Starting trial 5 with parameters: {'n_estimators': 832, 'max_depth': 38, 'learning_rate': 0.009855575216893767, 'subsample': 0.7368967663496733, 'colsample_bytree': 0.8566106891259551, 'min_child_weight': 14, 'reg_alpha': 0.0036159525063185756, 'reg_lambda': 1.0812239371756807, 'gamma': 0.0007970104163405092, 'early_stopping_rounds': 50}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 38.1440, RMSE: 6.1761, MAE: 4.0300
Starting fold 2...
Fold 2 - MSE: 36.9744, RMSE: 6.0807, MAE: 3.8192
Starting fold 3...
Fold 3 - MSE: 7.7107, RMSE: 2.7768, MAE: 1.9123
Starting fold 4...
Fold 4 - MSE: 31.5028, RMSE: 5.6127, MAE: 4.7256
Starting fold 5...

[INFO 04-02 10:55:39] ax.service.ax_client: Completed trial 5 with data: {'avg_rmse_nonzero': 4.548896}.
[INFO 04-02 10:55:39] ax.service.ax_client: Generated new trial 6 with parameters {'n_estimators': 4323, 'max_depth': 61, 'learning_rate': 0.08973, 'subsample': 0.908096, 'colsample_bytree': 0.668808, 'min_child_weight': 17, 'reg_alpha': 2e-06, 'reg_lambda': 0.009391, 'gamma': 3e-06, 'early_stopping_rounds': 33} using model Sobol.

Fold 5 - MSE: 4.4024, RMSE: 2.0982, MAE: 1.7046

Mean CV MSE: 23.7469, Mean CV RMSE: 4.5489, Mean CV MAE: 3.2383
Completed trial 5 with mean RMSE: 4.5489 ± 0.8738
Saved Ax client checkpoint

Starting trial 6 with parameters: {'n_estimators': 4323, 'max_depth': 61, 'learning_rate': 0.08972994401918881, 'subsample': 0.908096210565418, 'colsample_bytree': 0.6688078429549933, 'min_child_weight': 17, 'reg_alpha': 1.7387938976482574e-06, 'reg_lambda': 0.009390520334828865, 'gamma': 3.135311729878053e-06, 'early_stopping_rounds': 33}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 36.7070, RMSE: 6.0586, MAE: 3.9565
Starting fold 2...
Fold 2 - MSE: 39.0320, RMSE: 6.2476, MAE: 3.8747
Starting fold 3...
Fold 3 - MSE: 8.1205, RMSE: 2.8497, MAE: 1.9722
Starting fold 4...
Fold 4 - MSE: 32.0981, RMSE: 5.6655, MAE: 4.7154
Starting fold 5...

[INFO 04-02 10:56:38] ax.service.ax_client: Completed trial 6 with data: {'avg_rmse_nonzero': 4.620194}.
[INFO 04-02 10:56:38] ax.service.ax_client: Generated new trial 7 with parameters {'n_estimators': 6484, 'max_depth': 22, 'learning_rate': 0.022534, 'subsample': 0.569698, 'colsample_bytree': 0.341293, 'min_child_weight': 9, 'reg_alpha': 1.476253, 'reg_lambda': 3e-06, 'gamma': 1.990562, 'early_stopping_rounds': 26} using model Sobol.

Fold 5 - MSE: 5.1966, RMSE: 2.2796, MAE: 1.9286

Mean CV MSE: 24.2308, Mean CV RMSE: 4.6202, Mean CV MAE: 3.2895
Completed trial 6 with mean RMSE: 4.6202 ± 0.8492
Saved Ax client checkpoint

Starting trial 7 with parameters: {'n_estimators': 6484, 'max_depth': 22, 'learning_rate': 0.022534165638798107, 'subsample': 0.569698145147413, 'colsample_bytree': 0.3412934164516628, 'min_child_weight': 9, 'reg_alpha': 1.4762534064120976, 'reg_lambda': 2.9299698327917007e-06, 'gamma': 1.9905616675424525, 'early_stopping_rounds': 26}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 37.4325, RMSE: 6.1182, MAE: 3.9366
Starting fold 2...
Fold 2 - MSE: 35.1443, RMSE: 5.9283, MAE: 3.7868
Starting fold 3...
Fold 3 - MSE: 7.3225, RMSE: 2.7060, MAE: 1.7997
Starting fold 4...
Fold 4 - MSE: 29.0087, RMSE: 5.3860, MAE: 4.5082
Starting fold 5...

[INFO 04-02 10:58:09] ax.service.ax_client: Completed trial 7 with data: {'avg_rmse_nonzero': 4.453843}.
[INFO 04-02 10:58:09] ax.service.ax_client: Generated new trial 8 with parameters {'n_estimators': 6991, 'max_depth': 87, 'learning_rate': 0.074936, 'subsample': 0.712406, 'colsample_bytree': 0.742757, 'min_child_weight': 8, 'reg_alpha': 0.00289, 'reg_lambda': 7e-05, 'gamma': 0.007524, 'early_stopping_rounds': 37} using model Sobol.

Fold 5 - MSE: 4.5401, RMSE: 2.1308, MAE: 1.6580

Mean CV MSE: 22.6896, Mean CV RMSE: 4.4538, Mean CV MAE: 3.1379
Completed trial 7 with mean RMSE: 4.4538 ± 0.8445
Saved Ax client checkpoint

Starting trial 8 with parameters: {'n_estimators': 6991, 'max_depth': 87, 'learning_rate': 0.07493601677925597, 'subsample': 0.7124063819646835, 'colsample_bytree': 0.7427567339502275, 'min_child_weight': 8, 'reg_alpha': 0.002889665627022381, 'reg_lambda': 6.993313928957958e-05, 'gamma': 0.007523584306069562, 'early_stopping_rounds': 37}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 42.0732, RMSE: 6.4864, MAE: 4.3581
Starting fold 2...
Fold 2 - MSE: 36.7503, RMSE: 6.0622, MAE: 3.6765
Starting fold 3...
Fold 3 - MSE: 8.4495, RMSE: 2.9068, MAE: 2.2832
Starting fold 4...
Fold 4 - MSE: 36.8728, RMSE: 6.0723, MAE: 4.9095
Starting fold 5...

[INFO 04-02 10:59:03] ax.service.ax_client: Completed trial 8 with data: {'avg_rmse_nonzero': 4.708668}.
[INFO 04-02 10:59:04] ax.service.ax_client: Generated new trial 9 with parameters {'n_estimators': 4821, 'max_depth': 46, 'learning_rate': 0.01482, 'subsample': 0.811752, 'colsample_bytree': 0.409621, 'min_child_weight': 20, 'reg_alpha': 0.014125, 'reg_lambda': 0.217236, 'gamma': 0.001253, 'early_stopping_rounds': 24} using model Sobol.

Fold 5 - MSE: 4.0628, RMSE: 2.0156, MAE: 1.5270

Mean CV MSE: 25.6417, Mean CV RMSE: 4.7087, Mean CV MAE: 3.3509
Completed trial 8 with mean RMSE: 4.7087 ± 0.9314
Saved Ax client checkpoint

Starting trial 9 with parameters: {'n_estimators': 4821, 'max_depth': 46, 'learning_rate': 0.014819743592862904, 'subsample': 0.8117523975670338, 'colsample_bytree': 0.4096206404268741, 'min_child_weight': 20, 'reg_alpha': 0.014124646490242048, 'reg_lambda': 0.2172357774295344, 'gamma': 0.0012528671692876008, 'early_stopping_rounds': 24}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 36.8520, RMSE: 6.0706, MAE: 3.8633
Starting fold 2...
Fold 2 - MSE: 37.9386, RMSE: 6.1594, MAE: 3.8654
Starting fold 3...
Fold 3 - MSE: 7.3759, RMSE: 2.7159, MAE: 1.7811
Starting fold 4...
Fold 4 - MSE: 32.3060, RMSE: 5.6838, MAE: 4.7392
Starting fold 5...

[INFO 04-02 11:01:06] ax.service.ax_client: Completed trial 9 with data: {'avg_rmse_nonzero': 4.53604}.
[INFO 04-02 11:01:06] ax.service.ax_client: Generated new trial 10 with parameters {'n_estimators': 324, 'max_depth': 72, 'learning_rate': 0.171509, 'subsample': 0.605755, 'colsample_bytree': 0.577468, 'min_child_weight': 11, 'reg_alpha': 6e-06, 'reg_lambda': 0.008035, 'gamma': 2e-06, 'early_stopping_rounds': 18} using model Sobol.

Fold 5 - MSE: 4.2045, RMSE: 2.0505, MAE: 1.5458

Mean CV MSE: 23.7354, Mean CV RMSE: 4.5360, Mean CV MAE: 3.1590
Completed trial 9 with mean RMSE: 4.5360 ± 0.8888
Saved Ax client checkpoint

Starting trial 10 with parameters: {'n_estimators': 324, 'max_depth': 72, 'learning_rate': 0.17150940427660286, 'subsample': 0.6057545649819076, 'colsample_bytree': 0.5774681681767107, 'min_child_weight': 11, 'reg_alpha': 6.277496346704182e-06, 'reg_lambda': 0.00803514614024191, 'gamma': 1.8776761289472669e-06, 'early_stopping_rounds': 18}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 42.8148, RMSE: 6.5433, MAE: 4.2776
Starting fold 2...
Fold 2 - MSE: 40.3724, RMSE: 6.3539, MAE: 3.9676
Starting fold 3...
Fold 3 - MSE: 8.0551, RMSE: 2.8381, MAE: 2.0205
Starting fold 4...
Fold 4 - MSE: 31.1936, RMSE: 5.5851, MAE: 4.5467
Starting fold 5...

[INFO 04-02 11:01:22] ax.service.ax_client: Completed trial 10 with data: {'avg_rmse_nonzero': 4.758929}.
[INFO 04-02 11:01:22] ax.service.ax_client: Generated new trial 11 with parameters {'n_estimators': 8063, 'max_depth': 12, 'learning_rate': 0.012173, 'subsample': 0.885711, 'colsample_bytree': 0.946717, 'min_child_weight': 3, 'reg_alpha': 4.839699, 'reg_lambda': 3e-06, 'gamma': 1.192248, 'early_stopping_rounds': 41} using model Sobol.

Fold 5 - MSE: 6.1214, RMSE: 2.4742, MAE: 2.2062

Mean CV MSE: 25.7115, Mean CV RMSE: 4.7589, Mean CV MAE: 3.4037
Completed trial 10 with mean RMSE: 4.7589 ± 0.8752
Saved Ax client checkpoint

Starting trial 11 with parameters: {'n_estimators': 8063, 'max_depth': 12, 'learning_rate': 0.012172673682405384, 'subsample': 0.8857112969271839, 'colsample_bytree': 0.9467172899283469, 'min_child_weight': 3, 'reg_alpha': 4.8396985186499375, 'reg_lambda': 2.5040597507836035e-06, 'gamma': 1.1922484140225333, 'early_stopping_rounds': 41}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 38.6303, RMSE: 6.2153, MAE: 4.0740
Starting fold 2...
Fold 2 - MSE: 37.8141, RMSE: 6.1493, MAE: 3.6888
Starting fold 3...
Fold 3 - MSE: 8.0968, RMSE: 2.8455, MAE: 2.1561
Starting fold 4...
Fold 4 - MSE: 31.3074, RMSE: 5.5953, MAE: 4.6505
Starting fold 5...

[INFO 04-02 11:03:25] ax.service.ax_client: Completed trial 11 with data: {'avg_rmse_nonzero': 4.524342}.
[INFO 04-02 11:03:25] ax.service.ax_client: Generated new trial 12 with parameters {'n_estimators': 9284, 'max_depth': 56, 'learning_rate': 0.034527, 'subsample': 0.963629, 'colsample_bytree': 0.893203, 'min_child_weight': 8, 'reg_alpha': 4.1e-05, 'reg_lambda': 0.145589, 'gamma': 1.6e-05, 'early_stopping_rounds': 28} using model Sobol.

Fold 5 - MSE: 3.2988, RMSE: 1.8163, MAE: 1.4215

Mean CV MSE: 23.8295, Mean CV RMSE: 4.5243, Mean CV MAE: 3.1982
Completed trial 11 with mean RMSE: 4.5243 ± 0.9165
Saved Ax client checkpoint

Starting trial 12 with parameters: {'n_estimators': 9284, 'max_depth': 56, 'learning_rate': 0.034526647374359294, 'subsample': 0.9636287172324955, 'colsample_bytree': 0.8932026820257306, 'min_child_weight': 8, 'reg_alpha': 4.059028324673241e-05, 'reg_lambda': 0.1455889878824976, 'gamma': 1.6102027077399194e-05, 'early_stopping_rounds': 28}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 41.2666, RMSE: 6.4239, MAE: 4.2656
Starting fold 2...
Fold 2 - MSE: 40.8127, RMSE: 6.3885, MAE: 3.9779
Starting fold 3...
Fold 3 - MSE: 7.9647, RMSE: 2.8222, MAE: 1.9739
Starting fold 4...
Fold 4 - MSE: 41.4525, RMSE: 6.4384, MAE: 5.2026
Starting fold 5...

[INFO 04-02 11:05:29] ax.service.ax_client: Completed trial 12 with data: {'avg_rmse_nonzero': 4.795239}.
[INFO 04-02 11:05:29] ax.service.ax_client: Generated new trial 13 with parameters {'n_estimators': 1545, 'max_depth': 15, 'learning_rate': 0.052049, 'subsample': 0.559069, 'colsample_bytree': 0.521608, 'min_child_weight': 16, 'reg_alpha': 0.608023, 'reg_lambda': 4.5e-05, 'gamma': 0.222829, 'early_stopping_rounds': 31} using model Sobol.

Fold 5 - MSE: 3.6224, RMSE: 1.9033, MAE: 1.3798

Mean CV MSE: 27.0238, Mean CV RMSE: 4.7952, Mean CV MAE: 3.3600
Completed trial 12 with mean RMSE: 4.7952 ± 1.0037
Saved Ax client checkpoint

Starting trial 13 with parameters: {'n_estimators': 1545, 'max_depth': 15, 'learning_rate': 0.05204851810061841, 'subsample': 0.5590685424394906, 'colsample_bytree': 0.5216077760793268, 'min_child_weight': 16, 'reg_alpha': 0.6080233844929709, 'reg_lambda': 4.521508682343162e-05, 'gamma': 0.22282875816942282, 'early_stopping_rounds': 31}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 36.5121, RMSE: 6.0425, MAE: 3.8829
Starting fold 2...
Fold 2 - MSE: 37.1251, RMSE: 6.0930, MAE: 3.8935
Starting fold 3...
Fold 3 - MSE: 8.0706, RMSE: 2.8409, MAE: 1.8732
Starting fold 4...
Fold 4 - MSE: 28.4327, RMSE: 5.3322, MAE: 4.4175
Starting fold 5...

[INFO 04-02 11:06:14] ax.service.ax_client: Completed trial 13 with data: {'avg_rmse_nonzero': 4.481599}.
[INFO 04-02 11:06:14] ax.service.ax_client: Generated new trial 14 with parameters {'n_estimators': 3601, 'max_depth': 90, 'learning_rate': 0.006119, 'subsample': 0.858439, 'colsample_bytree': 0.377633, 'min_child_weight': 15, 'reg_alpha': 0.000279, 'reg_lambda': 0.001263, 'gamma': 0.041023, 'early_stopping_rounds': 47} using model Sobol.

Fold 5 - MSE: 4.4071, RMSE: 2.0993, MAE: 1.6855

Mean CV MSE: 22.9095, Mean CV RMSE: 4.4816, Mean CV MAE: 3.1505
Completed trial 13 with mean RMSE: 4.4816 ± 0.8404
Saved Ax client checkpoint

Starting trial 14 with parameters: {'n_estimators': 3601, 'max_depth': 90, 'learning_rate': 0.006118564029540236, 'subsample': 0.8584389565512538, 'colsample_bytree': 0.377632540371269, 'min_child_weight': 15, 'reg_alpha': 0.0002788951171375328, 'reg_lambda': 0.0012627638743428187, 'gamma': 0.04102261238313879, 'early_stopping_rounds': 47}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 38.4127, RMSE: 6.1978, MAE: 4.0361
Starting fold 2...
Fold 2 - MSE: 37.6404, RMSE: 6.1352, MAE: 3.8334
Starting fold 3...
Fold 3 - MSE: 7.7069, RMSE: 2.7761, MAE: 1.8726
Starting fold 4...
Fold 4 - MSE: 29.4877, RMSE: 5.4303, MAE: 4.5169
Starting fold 5...

[INFO 04-02 11:11:03] ax.service.ax_client: Completed trial 14 with data: {'avg_rmse_nonzero': 4.509448}.
[INFO 04-02 11:11:03] ax.service.ax_client: Generated new trial 15 with parameters {'n_estimators': 5771, 'max_depth': 31, 'learning_rate': 0.198585, 'subsample': 0.634489, 'colsample_bytree': 0.70912, 'min_child_weight': 3, 'reg_alpha': 0.065885, 'reg_lambda': 3.936103, 'gamma': 0.00014, 'early_stopping_rounds': 14} using model Sobol.

Fold 5 - MSE: 4.0315, RMSE: 2.0079, MAE: 1.5445

Mean CV MSE: 23.4559, Mean CV RMSE: 4.5094, Mean CV MAE: 3.1607
Completed trial 14 with mean RMSE: 4.5094 ± 0.8833
Saved Ax client checkpoint

Starting trial 15 with parameters: {'n_estimators': 5771, 'max_depth': 31, 'learning_rate': 0.19858472530964164, 'subsample': 0.6344893788918853, 'colsample_bytree': 0.7091198340058327, 'min_child_weight': 3, 'reg_alpha': 0.06588515174853872, 'reg_lambda': 3.9361033267366254, 'gamma': 0.00014017814802790246, 'early_stopping_rounds': 14}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 39.1380, RMSE: 6.2560, MAE: 4.1235
Starting fold 2...
Fold 2 - MSE: 39.6144, RMSE: 6.2940, MAE: 4.1784
Starting fold 3...
Fold 3 - MSE: 10.0566, RMSE: 3.1712, MAE: 2.6560
Starting fold 4...
Fold 4 - MSE: 33.8108, RMSE: 5.8147, MAE: 4.7260
Starting fold 5...

[INFO 04-02 11:11:24] ax.service.ax_client: Completed trial 15 with data: {'avg_rmse_nonzero': 4.67248}.
[INFO 04-02 11:11:24] ax.service.ax_client: Generated new trial 16 with parameters {'n_estimators': 6075, 'max_depth': 91, 'learning_rate': 0.017341, 'subsample': 0.931559, 'colsample_bytree': 0.633829, 'min_child_weight': 16, 'reg_alpha': 0.419615, 'reg_lambda': 0.002117, 'gamma': 0.001471, 'early_stopping_rounds': 48} using model Sobol.

Fold 5 - MSE: 3.3359, RMSE: 1.8264, MAE: 1.3225

Mean CV MSE: 25.1911, Mean CV RMSE: 4.6725, Mean CV MAE: 3.4013
Completed trial 15 with mean RMSE: 4.6725 ± 0.9164
Saved Ax client checkpoint

Starting trial 16 with parameters: {'n_estimators': 6075, 'max_depth': 91, 'learning_rate': 0.017341410757924305, 'subsample': 0.93155885534361, 'colsample_bytree': 0.6338285632431506, 'min_child_weight': 16, 'reg_alpha': 0.4196151361437876, 'reg_lambda': 0.0021172352690953765, 'gamma': 0.0014710035965059113, 'early_stopping_rounds': 48}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 37.5988, RMSE: 6.1318, MAE: 4.0518
Starting fold 2...
Fold 2 - MSE: 38.6736, RMSE: 6.2188, MAE: 3.8639
Starting fold 3...
Fold 3 - MSE: 7.5595, RMSE: 2.7495, MAE: 1.8879
Starting fold 4...
Fold 4 - MSE: 30.9552, RMSE: 5.5637, MAE: 4.6355
Starting fold 5...

[INFO 04-02 11:13:48] ax.service.ax_client: Completed trial 16 with data: {'avg_rmse_nonzero': 4.580459}.
[INFO 04-02 11:13:48] ax.service.ax_client: Generated new trial 17 with parameters {'n_estimators': 3296, 'max_depth': 29, 'learning_rate': 0.072743, 'subsample': 0.593108, 'colsample_bytree': 0.967007, 'min_child_weight': 9, 'reg_alpha': 1e-05, 'reg_lambda': 6.846102, 'gamma': 0.011585, 'early_stopping_rounds': 10} using model Sobol.

Fold 5 - MSE: 5.0109, RMSE: 2.2385, MAE: 1.7217

Mean CV MSE: 23.9596, Mean CV RMSE: 4.5805, Mean CV MAE: 3.2322
Completed trial 16 with mean RMSE: 4.5805 ± 0.8630
Saved Ax client checkpoint

Starting trial 17 with parameters: {'n_estimators': 3296, 'max_depth': 29, 'learning_rate': 0.07274338536571627, 'subsample': 0.5931076225824654, 'colsample_bytree': 0.9670073396526278, 'min_child_weight': 9, 'reg_alpha': 1.0249631968023209e-05, 'reg_lambda': 6.8461017062002165, 'gamma': 0.011584850314659124, 'early_stopping_rounds': 10}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 37.3200, RMSE: 6.1090, MAE: 4.0538
Starting fold 2...
Fold 2 - MSE: 34.4331, RMSE: 5.8680, MAE: 3.6732
Starting fold 3...
Fold 3 - MSE: 7.3822, RMSE: 2.7170, MAE: 1.9540
Starting fold 4...
Fold 4 - MSE: 29.1407, RMSE: 5.3982, MAE: 4.5186
Starting fold 5...

[INFO 04-02 11:14:18] ax.service.ax_client: Completed trial 17 with data: {'avg_rmse_nonzero': 4.421623}.
[INFO 04-02 11:14:18] ax.service.ax_client: Generated new trial 18 with parameters {'n_estimators': 1859, 'max_depth': 52, 'learning_rate': 0.012551, 'subsample': 0.761846, 'colsample_bytree': 0.820904, 'min_child_weight': 2, 'reg_alpha': 0.057691, 'reg_lambda': 0.084053, 'gamma': 1.132624, 'early_stopping_rounds': 27} using model Sobol.

Fold 5 - MSE: 4.0638, RMSE: 2.0159, MAE: 1.5255

Mean CV MSE: 22.4680, Mean CV RMSE: 4.4216, Mean CV MAE: 3.1450
Completed trial 17 with mean RMSE: 4.4216 ± 0.8540
Saved Ax client checkpoint

Starting trial 18 with parameters: {'n_estimators': 1859, 'max_depth': 52, 'learning_rate': 0.012551301075569624, 'subsample': 0.7618463514372706, 'colsample_bytree': 0.820903850439936, 'min_child_weight': 2, 'reg_alpha': 0.05769076307501751, 'reg_lambda': 0.08405316338944767, 'gamma': 1.1326237956120344, 'early_stopping_rounds': 27}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 38.4874, RMSE: 6.2038, MAE: 4.1199
Starting fold 2...
Fold 2 - MSE: 36.8484, RMSE: 6.0703, MAE: 3.6668
Starting fold 3...
Fold 3 - MSE: 11.5694, RMSE: 3.4014, MAE: 2.6544
Starting fold 4...
Fold 4 - MSE: 33.5730, RMSE: 5.7942, MAE: 4.8283
Starting fold 5...

[INFO 04-02 11:16:03] ax.service.ax_client: Completed trial 18 with data: {'avg_rmse_nonzero': 4.674589}.
[INFO 04-02 11:16:03] ax.service.ax_client: Generated new trial 19 with parameters {'n_estimators': 8970, 'max_depth': 20, 'learning_rate': 0.146433, 'subsample': 0.729113, 'colsample_bytree': 0.451697, 'min_child_weight': 15, 'reg_alpha': 8.9e-05, 'reg_lambda': 2.7e-05, 'gamma': 1e-06, 'early_stopping_rounds': 35} using model Sobol.

Fold 5 - MSE: 3.6223, RMSE: 1.9032, MAE: 1.3280

Mean CV MSE: 24.8201, Mean CV RMSE: 4.6746, Mean CV MAE: 3.3195
Completed trial 18 with mean RMSE: 4.6746 ± 0.8614
Saved Ax client checkpoint

Starting trial 19 with parameters: {'n_estimators': 8970, 'max_depth': 20, 'learning_rate': 0.1464328353368378, 'subsample': 0.7291125273332, 'colsample_bytree': 0.4516974115744233, 'min_child_weight': 15, 'reg_alpha': 8.90029326610707e-05, 'reg_lambda': 2.6852244941455786e-05, 'gamma': 1.3601470951811816e-06, 'early_stopping_rounds': 35}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 36.3307, RMSE: 6.0275, MAE: 3.9983
Starting fold 2...
Fold 2 - MSE: 39.6596, RMSE: 6.2976, MAE: 3.8730
Starting fold 3...
Fold 3 - MSE: 7.0473, RMSE: 2.6547, MAE: 1.8423
Starting fold 4...
Fold 4 - MSE: 31.4817, RMSE: 5.6109, MAE: 4.5145
Starting fold 5...

[INFO 04-02 11:16:30] ax.service.ax_client: Completed trial 19 with data: {'avg_rmse_nonzero': 4.558111}.

Fold 5 - MSE: 4.8397, RMSE: 2.1999, MAE: 1.7102

Mean CV MSE: 23.8718, Mean CV RMSE: 4.5581, Mean CV MAE: 3.1877
Completed trial 19 with mean RMSE: 4.5581 ± 0.8797
Saved Ax client checkpoint

[INFO 04-02 11:16:33] ax.service.ax_client: Generated new trial 20 with parameters {'n_estimators': 2561, 'max_depth': 100, 'learning_rate': 0.3, 'subsample': 0.5, 'colsample_bytree': 0.3, 'min_child_weight': 1, 'reg_alpha': 10.0, 'reg_lambda': 10.0, 'gamma': 5.0, 'early_stopping_rounds': 50} using model BoTorch.

Starting trial 20 with parameters: {'n_estimators': 2561, 'max_depth': 100, 'learning_rate': 0.29999999999999993, 'subsample': 0.5, 'colsample_bytree': 0.3, 'min_child_weight': 1, 'reg_alpha': 10.0, 'reg_lambda': 10.0, 'gamma': 5.0, 'early_stopping_rounds': 50}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 35.8952, RMSE: 5.9913, MAE: 3.8896
Starting fold 2...
Fold 2 - MSE: 36.0359, RMSE: 6.0030, MAE: 3.6061
Starting fold 3...
Fold 3 - MSE: 6.9394, RMSE: 2.6343, MAE: 1.9729
Starting fold 4...
Fold 4 - MSE: 29.7831, RMSE: 5.4574, MAE: 4.3544
Starting fold 5...

[INFO 04-02 11:16:55] ax.service.ax_client: Completed trial 20 with data: {'avg_rmse_nonzero': 4.531665}.

Fold 5 - MSE: 6.6173, RMSE: 2.5724, MAE: 2.1896

Mean CV MSE: 23.0542, Mean CV RMSE: 4.5317, Mean CV MAE: 3.2025
Completed trial 20 with mean RMSE: 4.5317 ± 0.7934
Saved Ax client checkpoint

[INFO 04-02 11:16:57] ax.service.ax_client: Generated new trial 21 with parameters {'n_estimators': 9974, 'max_depth': 100, 'learning_rate': 0.005, 'subsample': 1.0, 'colsample_bytree': 0.3, 'min_child_weight': 20, 'reg_alpha': 1e-06, 'reg_lambda': 1e-06, 'gamma': 5.0, 'early_stopping_rounds': 50} using model BoTorch.

Starting trial 21 with parameters: {'n_estimators': 9974, 'max_depth': 100, 'learning_rate': 0.005, 'subsample': 1.0, 'colsample_bytree': 0.3, 'min_child_weight': 20, 'reg_alpha': 1e-06, 'reg_lambda': 1e-06, 'gamma': 5.0, 'early_stopping_rounds': 50}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 36.4861, RMSE: 6.0404, MAE: 3.8601
Starting fold 2...
Fold 2 - MSE: 37.3914, RMSE: 6.1149, MAE: 3.7750
Starting fold 3...
Fold 3 - MSE: 7.6181, RMSE: 2.7601, MAE: 1.8507
Starting fold 4...
Fold 4 - MSE: 32.2872, RMSE: 5.6822, MAE: 4.7682
Starting fold 5...

[INFO 04-02 11:20:01] ax.service.ax_client: Completed trial 21 with data: {'avg_rmse_nonzero': 4.557276}.

Fold 5 - MSE: 4.7912, RMSE: 2.1889, MAE: 1.7945

Mean CV MSE: 23.7148, Mean CV RMSE: 4.5573, Mean CV MAE: 3.2097
Completed trial 21 with mean RMSE: 4.5573 ± 0.8582
Saved Ax client checkpoint

[INFO 04-02 11:20:03] ax.service.ax_client: Generated new trial 22 with parameters {'n_estimators': 4868, 'max_depth': 3, 'learning_rate': 0.3, 'subsample': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 1, 'reg_alpha': 10.0, 'reg_lambda': 10.0, 'gamma': 1e-06, 'early_stopping_rounds': 10} using model BoTorch.

Starting trial 22 with parameters: {'n_estimators': 4868, 'max_depth': 3, 'learning_rate': 0.29999999999999993, 'subsample': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 1, 'reg_alpha': 10.0, 'reg_lambda': 10.0, 'gamma': 1e-06, 'early_stopping_rounds': 10}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 40.4110, RMSE: 6.3570, MAE: 4.2707
Starting fold 2...
Fold 2 - MSE: 40.3330, RMSE: 6.3508, MAE: 3.8089
Starting fold 3...
Fold 3 - MSE: 9.2294, RMSE: 3.0380, MAE: 2.1438
Starting fold 4...
Fold 4 - MSE: 28.4114, RMSE: 5.3302, MAE: 4.2458
Starting fold 5...

[INFO 04-02 11:20:15] ax.service.ax_client: Completed trial 22 with data: {'avg_rmse_nonzero': 4.650889}.

Fold 5 - MSE: 4.7456, RMSE: 2.1784, MAE: 1.9001

Mean CV MSE: 24.6261, Mean CV RMSE: 4.6509, Mean CV MAE: 3.2739
Completed trial 22 with mean RMSE: 4.6509 ± 0.8653
Saved Ax client checkpoint

[INFO 04-02 11:20:20] ax.service.ax_client: Generated new trial 23 with parameters {'n_estimators': 5524, 'max_depth': 3, 'learning_rate': 0.3, 'subsample': 1.0, 'colsample_bytree': 0.3, 'min_child_weight': 1, 'reg_alpha': 10.0, 'reg_lambda': 1e-06, 'gamma': 1e-06, 'early_stopping_rounds': 50} using model BoTorch.

Starting trial 23 with parameters: {'n_estimators': 5524, 'max_depth': 3, 'learning_rate': 0.29999999999999993, 'subsample': 1.0, 'colsample_bytree': 0.3, 'min_child_weight': 1, 'reg_alpha': 10.0, 'reg_lambda': 1e-06, 'gamma': 1e-06, 'early_stopping_rounds': 50}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 40.2337, RMSE: 6.3430, MAE: 4.0813
Starting fold 2...
Fold 2 - MSE: 45.0278, RMSE: 6.7103, MAE: 4.0181
Starting fold 3...
Fold 3 - MSE: 8.9903, RMSE: 2.9984, MAE: 2.2993
Starting fold 4...
Fold 4 - MSE: 31.2111, RMSE: 5.5867, MAE: 4.6731
Starting fold 5...

[INFO 04-02 11:20:40] ax.service.ax_client: Completed trial 23 with data: {'avg_rmse_nonzero': 4.690281}.

Fold 5 - MSE: 3.2872, RMSE: 1.8131, MAE: 1.4825

Mean CV MSE: 25.7500, Mean CV RMSE: 4.6903, Mean CV MAE: 3.3108
Completed trial 23 with mean RMSE: 4.6903 ± 0.9684
Saved Ax client checkpoint

[INFO 04-02 11:20:47] ax.service.ax_client: Generated new trial 24 with parameters {'n_estimators': 3734, 'max_depth': 100, 'learning_rate': 0.005, 'subsample': 1.0, 'colsample_bytree': 0.3, 'min_child_weight': 20, 'reg_alpha': 0.00035, 'reg_lambda': 0.025797, 'gamma': 7e-06, 'early_stopping_rounds': 50} using model BoTorch.

Starting trial 24 with parameters: {'n_estimators': 3734, 'max_depth': 100, 'learning_rate': 0.005, 'subsample': 1.0, 'colsample_bytree': 0.3, 'min_child_weight': 20, 'reg_alpha': 0.00034966675850510844, 'reg_lambda': 0.025796580110933835, 'gamma': 7.034980724292647e-06, 'early_stopping_rounds': 50}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 36.9368, RMSE: 6.0776, MAE: 3.9015
Starting fold 2...
Fold 2 - MSE: 38.6689, RMSE: 6.2184, MAE: 3.8273
Starting fold 3...
Fold 3 - MSE: 8.3264, RMSE: 2.8856, MAE: 1.9350
Starting fold 4...
Fold 4 - MSE: 33.1130, RMSE: 5.7544, MAE: 4.7802
Starting fold 5...

[INFO 04-02 11:28:11] ax.service.ax_client: Completed trial 24 with data: {'avg_rmse_nonzero': 4.615428}.

Fold 5 - MSE: 4.5848, RMSE: 2.1412, MAE: 1.6510

Mean CV MSE: 24.3260, Mean CV RMSE: 4.6154, Mean CV MAE: 3.2190
Completed trial 24 with mean RMSE: 4.6154 ± 0.8695
Saved Ax client checkpoint

[INFO 04-02 11:28:14] ax.service.ax_client: Generated new trial 25 with parameters {'n_estimators': 8255, 'max_depth': 3, 'learning_rate': 0.005, 'subsample': 0.5, 'colsample_bytree': 0.3, 'min_child_weight': 1, 'reg_alpha': 1e-06, 'reg_lambda': 10.0, 'gamma': 5.0, 'early_stopping_rounds': 10} using model BoTorch.

Starting trial 25 with parameters: {'n_estimators': 8255, 'max_depth': 3, 'learning_rate': 0.005, 'subsample': 0.5, 'colsample_bytree': 0.3, 'min_child_weight': 1, 'reg_alpha': 1e-06, 'reg_lambda': 10.0, 'gamma': 5.0, 'early_stopping_rounds': 10}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 36.0886, RMSE: 6.0074, MAE: 3.8519
Starting fold 2...
Fold 2 - MSE: 37.4173, RMSE: 6.1170, MAE: 3.6631
Starting fold 3...
Fold 3 - MSE: 8.6598, RMSE: 2.9428, MAE: 1.9716
Starting fold 4...
Fold 4 - MSE: 28.5099, RMSE: 5.3395, MAE: 4.3427
Starting fold 5...

[INFO 04-02 11:30:58] ax.service.ax_client: Completed trial 25 with data: {'avg_rmse_nonzero': 4.497504}.

Fold 5 - MSE: 4.3304, RMSE: 2.0810, MAE: 1.7555

Mean CV MSE: 23.0012, Mean CV RMSE: 4.4975, Mean CV MAE: 3.1170
Completed trial 25 with mean RMSE: 4.4975 ± 0.8327
Saved Ax client checkpoint

[INFO 04-02 11:31:00] ax.service.ax_client: Generated new trial 26 with parameters {'n_estimators': 9061, 'max_depth': 100, 'learning_rate': 0.3, 'subsample': 0.5, 'colsample_bytree': 0.3, 'min_child_weight': 1, 'reg_alpha': 1e-06, 'reg_lambda': 1e-06, 'gamma': 5.0, 'early_stopping_rounds': 10} using model BoTorch.

Starting trial 26 with parameters: {'n_estimators': 9061, 'max_depth': 100, 'learning_rate': 0.29999999999999993, 'subsample': 0.5, 'colsample_bytree': 0.3, 'min_child_weight': 1, 'reg_alpha': 1e-06, 'reg_lambda': 1e-06, 'gamma': 5.0, 'early_stopping_rounds': 10}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 37.0995, RMSE: 6.0909, MAE: 4.0161
Starting fold 2...
Fold 2 - MSE: 41.0603, RMSE: 6.4078, MAE: 4.2760
Starting fold 3...
Fold 3 - MSE: 15.0126, RMSE: 3.8746, MAE: 3.0662
Starting fold 4...
Fold 4 - MSE: 33.0654, RMSE: 5.7503, MAE: 4.4462
Starting fold 5...

[INFO 04-02 11:31:09] ax.service.ax_client: Completed trial 26 with data: {'avg_rmse_nonzero': 5.226647}.

Fold 5 - MSE: 16.0769, RMSE: 4.0096, MAE: 3.6176

Mean CV MSE: 28.4629, Mean CV RMSE: 5.2266, Mean CV MAE: 3.8844
Completed trial 26 with mean RMSE: 5.2266 ± 0.5350
Saved Ax client checkpoint

[INFO 04-02 11:31:18] ax.service.ax_client: Generated new trial 27 with parameters {'n_estimators': 1396, 'max_depth': 45, 'learning_rate': 0.158654, 'subsample': 1.0, 'colsample_bytree': 0.453466, 'min_child_weight': 6, 'reg_alpha': 2e-06, 'reg_lambda': 1e-06, 'gamma': 0.011868, 'early_stopping_rounds': 50} using model BoTorch.

Starting trial 27 with parameters: {'n_estimators': 1396, 'max_depth': 45, 'learning_rate': 0.15865418282647076, 'subsample': 1.0, 'colsample_bytree': 0.4534659673314353, 'min_child_weight': 6, 'reg_alpha': 2.2465682652555848e-06, 'reg_lambda': 1e-06, 'gamma': 0.011867861508527318, 'early_stopping_rounds': 50}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 39.5597, RMSE: 6.2896, MAE: 4.2292
Starting fold 2...
Fold 2 - MSE: 38.5158, RMSE: 6.2061, MAE: 3.7546
Starting fold 3...
Fold 3 - MSE: 8.5775, RMSE: 2.9287, MAE: 2.2269
Starting fold 4...
Fold 4 - MSE: 37.6368, RMSE: 6.1349, MAE: 5.0740
Starting fold 5...

[INFO 04-02 11:31:48] ax.service.ax_client: Completed trial 27 with data: {'avg_rmse_nonzero': 4.685879}.

Fold 5 - MSE: 3.4970, RMSE: 1.8700, MAE: 1.2556

Mean CV MSE: 25.5573, Mean CV RMSE: 4.6859, Mean CV MAE: 3.3081
Completed trial 27 with mean RMSE: 4.6859 ± 0.9487
Saved Ax client checkpoint

[INFO 04-02 11:31:52] ax.service.ax_client: Generated new trial 28 with parameters {'n_estimators': 2292, 'max_depth': 4, 'learning_rate': 0.3, 'subsample': 0.93681, 'colsample_bytree': 1.0, 'min_child_weight': 14, 'reg_alpha': 1e-06, 'reg_lambda': 10.0, 'gamma': 1e-06, 'early_stopping_rounds': 10} using model BoTorch.

Starting trial 28 with parameters: {'n_estimators': 2292, 'max_depth': 4, 'learning_rate': 0.29999999999999993, 'subsample': 0.9368096019059176, 'colsample_bytree': 1.0, 'min_child_weight': 14, 'reg_alpha': 1e-06, 'reg_lambda': 10.0, 'gamma': 1e-06, 'early_stopping_rounds': 10}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 35.8700, RMSE: 5.9892, MAE: 4.0143
Starting fold 2...
Fold 2 - MSE: 43.0660, RMSE: 6.5625, MAE: 3.9369
Starting fold 3...
Fold 3 - MSE: 10.6102, RMSE: 3.2573, MAE: 2.3050
Starting fold 4...
Fold 4 - MSE: 36.0461, RMSE: 6.0038, MAE: 4.8574
Starting fold 5...

[INFO 04-02 11:32:05] ax.service.ax_client: Completed trial 28 with data: {'avg_rmse_nonzero': 4.889828}.

Fold 5 - MSE: 6.9503, RMSE: 2.6363, MAE: 2.2333

Mean CV MSE: 26.5085, Mean CV RMSE: 4.8898, Mean CV MAE: 3.4694
Completed trial 28 with mean RMSE: 4.8898 ± 0.8059
Saved Ax client checkpoint

[INFO 04-02 11:32:08] ax.service.ax_client: Generated new trial 29 with parameters {'n_estimators': 968, 'max_depth': 3, 'learning_rate': 0.005, 'subsample': 0.5, 'colsample_bytree': 0.3, 'min_child_weight': 1, 'reg_alpha': 1e-06, 'reg_lambda': 1e-06, 'gamma': 1e-06, 'early_stopping_rounds': 10} using model BoTorch.

Starting trial 29 with parameters: {'n_estimators': 968, 'max_depth': 3, 'learning_rate': 0.005, 'subsample': 0.5, 'colsample_bytree': 0.3, 'min_child_weight': 1, 'reg_alpha': 1e-06, 'reg_lambda': 1e-06, 'gamma': 1e-06, 'early_stopping_rounds': 10}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 37.1097, RMSE: 6.0918, MAE: 4.0018
Starting fold 2...
Fold 2 - MSE: 34.8189, RMSE: 5.9008, MAE: 3.7045
Starting fold 3...
Fold 3 - MSE: 16.1532, RMSE: 4.0191, MAE: 3.2600
Starting fold 4...
Fold 4 - MSE: 28.3989, RMSE: 5.3291, MAE: 4.2481
Starting fold 5...

[INFO 04-02 11:33:22] ax.service.ax_client: Completed trial 29 with data: {'avg_rmse_nonzero': 4.658857}.

Fold 5 - MSE: 3.8165, RMSE: 1.9536, MAE: 1.4065

Mean CV MSE: 24.0594, Mean CV RMSE: 4.6589, Mean CV MAE: 3.3242
Completed trial 29 with mean RMSE: 4.6589 ± 0.7672
Saved Ax client checkpoint

[INFO 04-02 11:33:26] ax.service.ax_client: Generated new trial 30 with parameters {'n_estimators': 3196, 'max_depth': 100, 'learning_rate': 0.005, 'subsample': 1.0, 'colsample_bytree': 0.3, 'min_child_weight': 20, 'reg_alpha': 1e-06, 'reg_lambda': 1e-06, 'gamma': 5.0, 'early_stopping_rounds': 10} using model BoTorch.

Starting trial 30 with parameters: {'n_estimators': 3196, 'max_depth': 100, 'learning_rate': 0.005, 'subsample': 1.0, 'colsample_bytree': 0.3, 'min_child_weight': 20, 'reg_alpha': 1e-06, 'reg_lambda': 1e-06, 'gamma': 5.0, 'early_stopping_rounds': 10}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 36.4861, RMSE: 6.0404, MAE: 3.8601
Starting fold 2...
Fold 2 - MSE: 37.3914, RMSE: 6.1149, MAE: 3.7750
Starting fold 3...
Fold 3 - MSE: 7.6181, RMSE: 2.7601, MAE: 1.8507
Starting fold 4...
Fold 4 - MSE: 32.1819, RMSE: 5.6729, MAE: 4.7592
Starting fold 5...

[INFO 04-02 11:36:30] ax.service.ax_client: Completed trial 30 with data: {'avg_rmse_nonzero': 4.570341}.

Fold 5 - MSE: 5.1234, RMSE: 2.2635, MAE: 1.9218

Mean CV MSE: 23.7602, Mean CV RMSE: 4.5703, Mean CV MAE: 3.2334
Completed trial 30 with mean RMSE: 4.5703 ± 0.8474
Saved Ax client checkpoint

[INFO 04-02 11:36:34] ax.service.ax_client: Generated new trial 31 with parameters {'n_estimators': 657, 'max_depth': 97, 'learning_rate': 0.005279, 'subsample': 0.678086, 'colsample_bytree': 1.0, 'min_child_weight': 12, 'reg_alpha': 0.002046, 'reg_lambda': 0.000451, 'gamma': 5.0, 'early_stopping_rounds': 15} using model BoTorch.

Starting trial 31 with parameters: {'n_estimators': 657, 'max_depth': 97, 'learning_rate': 0.005278921477972843, 'subsample': 0.678085948909722, 'colsample_bytree': 1.0, 'min_child_weight': 12, 'reg_alpha': 0.0020455492289191265, 'reg_lambda': 0.00045120536510441083, 'gamma': 5.0, 'early_stopping_rounds': 15}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 37.7765, RMSE: 6.1463, MAE: 4.0198
Starting fold 2...
Fold 2 - MSE: 35.5653, RMSE: 5.9637, MAE: 3.6963
Starting fold 3...
Fold 3 - MSE: 6.9847, RMSE: 2.6429, MAE: 1.8568
Starting fold 4...
Fold 4 - MSE: 29.4460, RMSE: 5.4264, MAE: 4.5848
Starting fold 5...

[INFO 04-02 11:38:36] ax.service.ax_client: Completed trial 31 with data: {'avg_rmse_nonzero': 4.47388}.

Fold 5 - MSE: 4.7970, RMSE: 2.1902, MAE: 1.8624

Mean CV MSE: 22.9139, Mean CV RMSE: 4.4739, Mean CV MAE: 3.2040
Completed trial 31 with mean RMSE: 4.4739 ± 0.8512
Saved Ax client checkpoint

[INFO 04-02 11:38:40] ax.service.ax_client: Generated new trial 32 with parameters {'n_estimators': 9506, 'max_depth': 100, 'learning_rate': 0.005, 'subsample': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 14, 'reg_alpha': 10.0, 'reg_lambda': 0.001419, 'gamma': 1e-06, 'early_stopping_rounds': 50} using model BoTorch.

Starting trial 32 with parameters: {'n_estimators': 9506, 'max_depth': 100, 'learning_rate': 0.005, 'subsample': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 14, 'reg_alpha': 10.0, 'reg_lambda': 0.0014190798992149826, 'gamma': 1e-06, 'early_stopping_rounds': 50}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 40.8988, RMSE: 6.3952, MAE: 4.1566
Starting fold 2...
Fold 2 - MSE: 36.9918, RMSE: 6.0821, MAE: 3.7136
Starting fold 3...
Fold 3 - MSE: 7.5250, RMSE: 2.7432, MAE: 1.8958
Starting fold 4...
Fold 4 - MSE: 29.0606, RMSE: 5.3908, MAE: 4.4352
Starting fold 5...

[INFO 04-02 11:45:40] ax.service.ax_client: Completed trial 32 with data: {'avg_rmse_nonzero': 4.542565}.

Fold 5 - MSE: 4.4165, RMSE: 2.1015, MAE: 1.6787

Mean CV MSE: 23.7786, Mean CV RMSE: 4.5426, Mean CV MAE: 3.1760
Completed trial 32 with mean RMSE: 4.5426 ± 0.8865
Saved Ax client checkpoint

[INFO 04-02 11:45:46] ax.service.ax_client: Generated new trial 33 with parameters {'n_estimators': 9842, 'max_depth': 3, 'learning_rate': 0.005, 'subsample': 1.0, 'colsample_bytree': 0.3, 'min_child_weight': 18, 'reg_alpha': 10.0, 'reg_lambda': 10.0, 'gamma': 1e-06, 'early_stopping_rounds': 14} using model BoTorch.

Starting trial 33 with parameters: {'n_estimators': 9842, 'max_depth': 3, 'learning_rate': 0.005, 'subsample': 1.0, 'colsample_bytree': 0.3, 'min_child_weight': 18, 'reg_alpha': 10.0, 'reg_lambda': 10.0, 'gamma': 1e-06, 'early_stopping_rounds': 14}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 37.3932, RMSE: 6.1150, MAE: 3.8765
Starting fold 2...
Fold 2 - MSE: 40.3549, RMSE: 6.3526, MAE: 3.7395
Starting fold 3...
Fold 3 - MSE: 8.4852, RMSE: 2.9129, MAE: 1.9972
Starting fold 4...
Fold 4 - MSE: 31.7295, RMSE: 5.6329, MAE: 4.6086
Starting fold 5...

[INFO 04-02 11:51:17] ax.service.ax_client: Completed trial 33 with data: {'avg_rmse_nonzero': 4.576861}.

Fold 5 - MSE: 3.5004, RMSE: 1.8709, MAE: 1.3737

Mean CV MSE: 24.2926, Mean CV RMSE: 4.5769, Mean CV MAE: 3.1191
Completed trial 33 with mean RMSE: 4.5769 ± 0.9145
Saved Ax client checkpoint

[INFO 04-02 11:51:26] ax.service.ax_client: Generated new trial 34 with parameters {'n_estimators': 2101, 'max_depth': 92, 'learning_rate': 0.191623, 'subsample': 0.932198, 'colsample_bytree': 0.555593, 'min_child_weight': 20, 'reg_alpha': 1e-06, 'reg_lambda': 1e-06, 'gamma': 5.0, 'early_stopping_rounds': 16} using model BoTorch.

Starting trial 34 with parameters: {'n_estimators': 2101, 'max_depth': 92, 'learning_rate': 0.1916225818573643, 'subsample': 0.9321984097837208, 'colsample_bytree': 0.5555928744695275, 'min_child_weight': 20, 'reg_alpha': 1e-06, 'reg_lambda': 1e-06, 'gamma': 5.0, 'early_stopping_rounds': 16}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 40.7336, RMSE: 6.3823, MAE: 4.1636
Starting fold 2...
Fold 2 - MSE: 34.8479, RMSE: 5.9032, MAE: 3.5644
Starting fold 3...
Fold 3 - MSE: 7.6487, RMSE: 2.7656, MAE: 1.8392
Starting fold 4...
Fold 4 - MSE: 44.0658, RMSE: 6.6382, MAE: 5.4170
Starting fold 5...

[INFO 04-02 11:51:41] ax.service.ax_client: Completed trial 34 with data: {'avg_rmse_nonzero': 4.93618}.

Fold 5 - MSE: 8.9495, RMSE: 2.9916, MAE: 2.5362

Mean CV MSE: 27.2491, Mean CV RMSE: 4.9362, Mean CV MAE: 3.5041
Completed trial 34 with mean RMSE: 4.9362 ± 0.8490
Saved Ax client checkpoint

[INFO 04-02 11:51:47] ax.service.ax_client: Generated new trial 35 with parameters {'n_estimators': 9955, 'max_depth': 62, 'learning_rate': 0.005, 'subsample': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 1, 'reg_alpha': 1e-06, 'reg_lambda': 10.0, 'gamma': 1e-06, 'early_stopping_rounds': 10} using model BoTorch.

Starting trial 35 with parameters: {'n_estimators': 9955, 'max_depth': 62, 'learning_rate': 0.005, 'subsample': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 1, 'reg_alpha': 1e-06, 'reg_lambda': 10.0, 'gamma': 1e-06, 'early_stopping_rounds': 10}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 42.3041, RMSE: 6.5042, MAE: 4.3130
Starting fold 2...
Fold 2 - MSE: 34.9144, RMSE: 5.9088, MAE: 3.7216
Starting fold 3...
Fold 3 - MSE: 9.5161, RMSE: 3.0848, MAE: 2.3150
Starting fold 4...
Fold 4 - MSE: 29.9720, RMSE: 5.4747, MAE: 4.3105
Starting fold 5...

[INFO 04-02 12:05:46] ax.service.ax_client: Completed trial 35 with data: {'avg_rmse_nonzero': 4.719691}.

Fold 5 - MSE: 6.8958, RMSE: 2.6260, MAE: 2.3021

Mean CV MSE: 24.7205, Mean CV RMSE: 4.7197, Mean CV MAE: 3.3925
Completed trial 35 with mean RMSE: 4.7197 ± 0.7818
Saved Ax client checkpoint

[INFO 04-02 12:05:57] ax.service.ax_client: Generated new trial 36 with parameters {'n_estimators': 8814, 'max_depth': 3, 'learning_rate': 0.3, 'subsample': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 1, 'reg_alpha': 1e-06, 'reg_lambda': 10.0, 'gamma': 3.653683, 'early_stopping_rounds': 10} using model BoTorch.

Starting trial 36 with parameters: {'n_estimators': 8814, 'max_depth': 3, 'learning_rate': 0.29999999999999993, 'subsample': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 1, 'reg_alpha': 1e-06, 'reg_lambda': 10.0, 'gamma': 3.6536829997946634, 'early_stopping_rounds': 10}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 35.5333, RMSE: 5.9610, MAE: 3.9890
Starting fold 2...
Fold 2 - MSE: 46.6767, RMSE: 6.8320, MAE: 4.2135
Starting fold 3...
Fold 3 - MSE: 10.0513, RMSE: 3.1704, MAE: 2.0855
Starting fold 4...
Fold 4 - MSE: 30.5062, RMSE: 5.5232, MAE: 4.4412
Starting fold 5...

[INFO 04-02 12:06:09] ax.service.ax_client: Completed trial 36 with data: {'avg_rmse_nonzero': 4.721256}.

Fold 5 - MSE: 4.4929, RMSE: 2.1196, MAE: 1.6144

Mean CV MSE: 25.4521, Mean CV RMSE: 4.7213, Mean CV MAE: 3.2687
Completed trial 36 with mean RMSE: 4.7213 ± 0.8891
Saved Ax client checkpoint

[INFO 04-02 12:06:20] ax.service.ax_client: Generated new trial 37 with parameters {'n_estimators': 277, 'max_depth': 3, 'learning_rate': 0.06476, 'subsample': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 20, 'reg_alpha': 1e-06, 'reg_lambda': 10.0, 'gamma': 5.0, 'early_stopping_rounds': 10} using model BoTorch.

Starting trial 37 with parameters: {'n_estimators': 277, 'max_depth': 3, 'learning_rate': 0.06476038678668689, 'subsample': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 20, 'reg_alpha': 1e-06, 'reg_lambda': 10.0, 'gamma': 5.0, 'early_stopping_rounds': 10}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 35.9396, RMSE: 5.9950, MAE: 3.7520
Starting fold 2...
Fold 2 - MSE: 36.7768, RMSE: 6.0644, MAE: 3.5993
Starting fold 3...
Fold 3 - MSE: 8.0169, RMSE: 2.8314, MAE: 2.0282
Starting fold 4...
Fold 4 - MSE: 33.0307, RMSE: 5.7472, MAE: 4.7046
Starting fold 5...

[INFO 04-02 12:06:45] ax.service.ax_client: Completed trial 37 with data: {'avg_rmse_nonzero': 4.509895}.

Fold 5 - MSE: 3.6537, RMSE: 1.9115, MAE: 1.4247

Mean CV MSE: 23.4836, Mean CV RMSE: 4.5099, Mean CV MAE: 3.1017
Completed trial 37 with mean RMSE: 4.5099 ± 0.8866
Saved Ax client checkpoint

[INFO 04-02 12:06:51] ax.service.ax_client: Generated new trial 38 with parameters {'n_estimators': 8318, 'max_depth': 6, 'learning_rate': 0.019876, 'subsample': 0.511, 'colsample_bytree': 0.323659, 'min_child_weight': 1, 'reg_alpha': 0.09465, 'reg_lambda': 10.0, 'gamma': 1e-06, 'early_stopping_rounds': 50} using model BoTorch.

Starting trial 38 with parameters: {'n_estimators': 8318, 'max_depth': 6, 'learning_rate': 0.019875803098548053, 'subsample': 0.5109998745986205, 'colsample_bytree': 0.3236587038612087, 'min_child_weight': 1, 'reg_alpha': 0.09465014124154503, 'reg_lambda': 10.0, 'gamma': 1e-06, 'early_stopping_rounds': 50}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 37.4378, RMSE: 6.1186, MAE: 3.9000
Starting fold 2...
Fold 2 - MSE: 36.3841, RMSE: 6.0319, MAE: 3.6907
Starting fold 3...
Fold 3 - MSE: 7.5181, RMSE: 2.7419, MAE: 2.1387
Starting fold 4...
Fold 4 - MSE: 27.8037, RMSE: 5.2729, MAE: 4.3145
Starting fold 5...

[INFO 04-02 12:09:04] ax.service.ax_client: Completed trial 38 with data: {'avg_rmse_nonzero': 4.424001}.

Fold 5 - MSE: 3.8205, RMSE: 1.9546, MAE: 1.5131

Mean CV MSE: 22.5928, Mean CV RMSE: 4.4240, Mean CV MAE: 3.1114
Completed trial 38 with mean RMSE: 4.4240 ± 0.8691
Saved Ax client checkpoint

[INFO 04-02 12:09:12] ax.service.ax_client: Generated new trial 39 with parameters {'n_estimators': 7175, 'max_depth': 3, 'learning_rate': 0.017743, 'subsample': 1.0, 'colsample_bytree': 0.429997, 'min_child_weight': 1, 'reg_alpha': 1.053413, 'reg_lambda': 0.00016, 'gamma': 2.2e-05, 'early_stopping_rounds': 50} using model BoTorch.

Starting trial 39 with parameters: {'n_estimators': 7175, 'max_depth': 3, 'learning_rate': 0.01774340670451644, 'subsample': 1.0, 'colsample_bytree': 0.4299972608646692, 'min_child_weight': 1, 'reg_alpha': 1.0534128538190362, 'reg_lambda': 0.00015974510642514098, 'gamma': 2.2167382936519113e-05, 'early_stopping_rounds': 50}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 36.3713, RMSE: 6.0309, MAE: 3.8850
Starting fold 2...
Fold 2 - MSE: 44.3115, RMSE: 6.6567, MAE: 4.1039
Starting fold 3...
Fold 3 - MSE: 12.7276, RMSE: 3.5676, MAE: 2.5334
Starting fold 4...
Fold 4 - MSE: 29.9113, RMSE: 5.4691, MAE: 4.3470
Starting fold 5...

[INFO 04-02 12:10:48] ax.service.ax_client: Completed trial 39 with data: {'avg_rmse_nonzero': 4.726711}.

Fold 5 - MSE: 3.6454, RMSE: 1.9093, MAE: 1.2621

Mean CV MSE: 25.3934, Mean CV RMSE: 4.7267, Mean CV MAE: 3.2263
Completed trial 39 with mean RMSE: 4.7267 ± 0.8734
Saved Ax client checkpoint

[INFO 04-02 12:10:56] ax.service.ax_client: Generated new trial 40 with parameters {'n_estimators': 7835, 'max_depth': 78, 'learning_rate': 0.048725, 'subsample': 0.641906, 'colsample_bytree': 0.483107, 'min_child_weight': 15, 'reg_alpha': 1e-06, 'reg_lambda': 1e-06, 'gamma': 0.00016, 'early_stopping_rounds': 44} using model BoTorch.

Starting trial 40 with parameters: {'n_estimators': 7835, 'max_depth': 78, 'learning_rate': 0.04872548240935628, 'subsample': 0.6419055312873059, 'colsample_bytree': 0.4831074108375222, 'min_child_weight': 15, 'reg_alpha': 1e-06, 'reg_lambda': 1e-06, 'gamma': 0.0001601319346785378, 'early_stopping_rounds': 44}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 37.5514, RMSE: 6.1279, MAE: 3.9791
Starting fold 2...
Fold 2 - MSE: 35.1843, RMSE: 5.9316, MAE: 3.7367
Starting fold 3...
Fold 3 - MSE: 8.3084, RMSE: 2.8824, MAE: 2.0089
Starting fold 4...
Fold 4 - MSE: 30.5147, RMSE: 5.5240, MAE: 4.6023
Starting fold 5...

[INFO 04-02 12:12:00] ax.service.ax_client: Completed trial 40 with data: {'avg_rmse_nonzero': 4.460895}.

Fold 5 - MSE: 3.3800, RMSE: 1.8385, MAE: 1.3759

Mean CV MSE: 22.9878, Mean CV RMSE: 4.4609, Mean CV MAE: 3.1406
Completed trial 40 with mean RMSE: 4.4609 ± 0.8787
Saved Ax client checkpoint

[INFO 04-02 12:12:09] ax.service.ax_client: Generated new trial 41 with parameters {'n_estimators': 7995, 'max_depth': 45, 'learning_rate': 0.01178, 'subsample': 1.0, 'colsample_bytree': 0.944996, 'min_child_weight': 20, 'reg_alpha': 10.0, 'reg_lambda': 10.0, 'gamma': 1e-06, 'early_stopping_rounds': 50} using model BoTorch.

Starting trial 41 with parameters: {'n_estimators': 7995, 'max_depth': 45, 'learning_rate': 0.011780018917783061, 'subsample': 1.0, 'colsample_bytree': 0.94499612509527, 'min_child_weight': 20, 'reg_alpha': 10.0, 'reg_lambda': 10.0, 'gamma': 1e-06, 'early_stopping_rounds': 50}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 40.3299, RMSE: 6.3506, MAE: 4.0489
Starting fold 2...
Fold 2 - MSE: 39.2631, RMSE: 6.2660, MAE: 3.8234
Starting fold 3...
Fold 3 - MSE: 8.1087, RMSE: 2.8476, MAE: 1.8823
Starting fold 4...
Fold 4 - MSE: 29.7275, RMSE: 5.4523, MAE: 4.4733
Starting fold 5...

[INFO 04-02 12:16:16] ax.service.ax_client: Completed trial 41 with data: {'avg_rmse_nonzero': 4.654773}.

Fold 5 - MSE: 5.5573, RMSE: 2.3574, MAE: 1.9802

Mean CV MSE: 24.5973, Mean CV RMSE: 4.6548, Mean CV MAE: 3.2416
Completed trial 41 with mean RMSE: 4.6548 ± 0.8559
Saved Ax client checkpoint

[INFO 04-02 12:16:25] ax.service.ax_client: Generated new trial 42 with parameters {'n_estimators': 7837, 'max_depth': 62, 'learning_rate': 0.182865, 'subsample': 0.5, 'colsample_bytree': 0.770396, 'min_child_weight': 1, 'reg_alpha': 3.595088, 'reg_lambda': 8.1e-05, 'gamma': 0.001461, 'early_stopping_rounds': 22} using model BoTorch.

Starting trial 42 with parameters: {'n_estimators': 7837, 'max_depth': 62, 'learning_rate': 0.1828648642123998, 'subsample': 0.5, 'colsample_bytree': 0.7703957429539809, 'min_child_weight': 1, 'reg_alpha': 3.595087644848429, 'reg_lambda': 8.122921136571843e-05, 'gamma': 0.0014611445506043771, 'early_stopping_rounds': 22}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 38.1447, RMSE: 6.1761, MAE: 4.1605
Starting fold 2...
Fold 2 - MSE: 37.8094, RMSE: 6.1489, MAE: 3.7342
Starting fold 3...
Fold 3 - MSE: 25.2105, RMSE: 5.0210, MAE: 3.9512
Starting fold 4...
Fold 4 - MSE: 28.0296, RMSE: 5.2943, MAE: 4.3229
Starting fold 5...

[INFO 04-02 12:16:51] ax.service.ax_client: Completed trial 42 with data: {'avg_rmse_nonzero': 4.896148}.

Fold 5 - MSE: 3.3869, RMSE: 1.8404, MAE: 1.2860

Mean CV MSE: 26.5162, Mean CV RMSE: 4.8961, Mean CV MAE: 3.4910
Completed trial 42 with mean RMSE: 4.8961 ± 0.7975
Saved Ax client checkpoint

[INFO 04-02 12:17:01] ax.service.ax_client: Generated new trial 43 with parameters {'n_estimators': 3231, 'max_depth': 33, 'learning_rate': 0.005, 'subsample': 0.853938, 'colsample_bytree': 0.908287, 'min_child_weight': 14, 'reg_alpha': 0.058121, 'reg_lambda': 7e-06, 'gamma': 5.0, 'early_stopping_rounds': 50} using model BoTorch.

Starting trial 43 with parameters: {'n_estimators': 3231, 'max_depth': 33, 'learning_rate': 0.005, 'subsample': 0.8539381135274356, 'colsample_bytree': 0.9082873987579183, 'min_child_weight': 14, 'reg_alpha': 0.05812090747342901, 'reg_lambda': 7.334380695805443e-06, 'gamma': 5.0, 'early_stopping_rounds': 50}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 38.2411, RMSE: 6.1839, MAE: 4.0510
Starting fold 2...
Fold 2 - MSE: 38.2478, RMSE: 6.1845, MAE: 3.8605
Starting fold 3...
Fold 3 - MSE: 7.3727, RMSE: 2.7153, MAE: 1.8872
Starting fold 4...
Fold 4 - MSE: 29.7489, RMSE: 5.4543, MAE: 4.5768
Starting fold 5...

[INFO 04-02 12:21:44] ax.service.ax_client: Completed trial 43 with data: {'avg_rmse_nonzero': 4.538136}.

Fold 5 - MSE: 4.6343, RMSE: 2.1527, MAE: 1.7351

Mean CV MSE: 23.6489, Mean CV RMSE: 4.5381, Mean CV MAE: 3.2221
Completed trial 43 with mean RMSE: 4.5381 ± 0.8738
Saved Ax client checkpoint

[INFO 04-02 12:21:50] ax.service.ax_client: Generated new trial 44 with parameters {'n_estimators': 6728, 'max_depth': 3, 'learning_rate': 0.3, 'subsample': 0.665374, 'colsample_bytree': 0.3, 'min_child_weight': 19, 'reg_alpha': 0.004505, 'reg_lambda': 1e-06, 'gamma': 1e-06, 'early_stopping_rounds': 12} using model BoTorch.

Starting trial 44 with parameters: {'n_estimators': 6728, 'max_depth': 3, 'learning_rate': 0.29999999999999993, 'subsample': 0.6653742682841116, 'colsample_bytree': 0.3, 'min_child_weight': 19, 'reg_alpha': 0.004504632495511154, 'reg_lambda': 1e-06, 'gamma': 1e-06, 'early_stopping_rounds': 12}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 41.7001, RMSE: 6.4576, MAE: 4.2052
Starting fold 2...
Fold 2 - MSE: 52.8915, RMSE: 7.2727, MAE: 4.5550
Starting fold 3...
Fold 3 - MSE: 7.0286, RMSE: 2.6512, MAE: 1.8649
Starting fold 4...
Fold 4 - MSE: 38.1664, RMSE: 6.1779, MAE: 4.8574
Starting fold 5...

[INFO 04-02 12:22:01] ax.service.ax_client: Completed trial 44 with data: {'avg_rmse_nonzero': 4.983714}.

Fold 5 - MSE: 5.5664, RMSE: 2.3593, MAE: 1.9748

Mean CV MSE: 29.0706, Mean CV RMSE: 4.9837, Mean CV MAE: 3.4915
Completed trial 44 with mean RMSE: 4.9837 ± 1.0287
Saved Ax client checkpoint

[INFO 04-02 12:22:09] ax.service.ax_client: Generated new trial 45 with parameters {'n_estimators': 4216, 'max_depth': 58, 'learning_rate': 0.005, 'subsample': 0.900376, 'colsample_bytree': 0.397674, 'min_child_weight': 20, 'reg_alpha': 2e-06, 'reg_lambda': 0.231363, 'gamma': 5.0, 'early_stopping_rounds': 14} using model BoTorch.

Starting trial 45 with parameters: {'n_estimators': 4216, 'max_depth': 58, 'learning_rate': 0.005, 'subsample': 0.9003763154750373, 'colsample_bytree': 0.3976740156472932, 'min_child_weight': 20, 'reg_alpha': 1.8394498462830192e-06, 'reg_lambda': 0.2313629726826233, 'gamma': 5.0, 'early_stopping_rounds': 14}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 38.0024, RMSE: 6.1646, MAE: 3.9451
Starting fold 2...
Fold 2 - MSE: 38.2856, RMSE: 6.1875, MAE: 3.8447
Starting fold 3...
Fold 3 - MSE: 7.7080, RMSE: 2.7763, MAE: 1.8418
Starting fold 4...
Fold 4 - MSE: 31.8833, RMSE: 5.6465, MAE: 4.7162
Starting fold 5...

[INFO 04-02 12:25:40] ax.service.ax_client: Completed trial 45 with data: {'avg_rmse_nonzero': 4.592067}.

Fold 5 - MSE: 4.7757, RMSE: 2.1853, MAE: 1.8231

Mean CV MSE: 24.1310, Mean CV RMSE: 4.5921, Mean CV MAE: 3.2342
Completed trial 45 with mean RMSE: 4.5921 ± 0.8723
Saved Ax client checkpoint

[INFO 04-02 12:25:48] ax.service.ax_client: Generated new trial 46 with parameters {'n_estimators': 2646, 'max_depth': 100, 'learning_rate': 0.005748, 'subsample': 0.962755, 'colsample_bytree': 0.821084, 'min_child_weight': 18, 'reg_alpha': 10.0, 'reg_lambda': 9.909195, 'gamma': 5.0, 'early_stopping_rounds': 37} using model BoTorch.

Starting trial 46 with parameters: {'n_estimators': 2646, 'max_depth': 100, 'learning_rate': 0.005748288999293121, 'subsample': 0.962755033491279, 'colsample_bytree': 0.8210837676954473, 'min_child_weight': 18, 'reg_alpha': 10.0, 'reg_lambda': 9.909195254563075, 'gamma': 5.0, 'early_stopping_rounds': 37}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 39.1450, RMSE: 6.2566, MAE: 4.0457
Starting fold 2...
Fold 2 - MSE: 39.8293, RMSE: 6.3110, MAE: 3.8055
Starting fold 3...
Fold 3 - MSE: 7.5732, RMSE: 2.7519, MAE: 1.9037
Starting fold 4...
Fold 4 - MSE: 31.1824, RMSE: 5.5841, MAE: 4.6177
Starting fold 5...

[INFO 04-02 12:30:00] ax.service.ax_client: Completed trial 46 with data: {'avg_rmse_nonzero': 4.638482}.

Fold 5 - MSE: 5.2381, RMSE: 2.2887, MAE: 1.9776

Mean CV MSE: 24.5936, Mean CV RMSE: 4.6385, Mean CV MAE: 3.2700
Completed trial 46 with mean RMSE: 4.6385 ± 0.8772
Saved Ax client checkpoint

[INFO 04-02 12:30:13] ax.service.ax_client: Generated new trial 47 with parameters {'n_estimators': 1952, 'max_depth': 13, 'learning_rate': 0.043818, 'subsample': 0.506743, 'colsample_bytree': 0.772926, 'min_child_weight': 18, 'reg_alpha': 0.173055, 'reg_lambda': 10.0, 'gamma': 0.003144, 'early_stopping_rounds': 15} using model BoTorch.

Starting trial 47 with parameters: {'n_estimators': 1952, 'max_depth': 13, 'learning_rate': 0.043817966989739054, 'subsample': 0.506742539984278, 'colsample_bytree': 0.7729256760649332, 'min_child_weight': 18, 'reg_alpha': 0.17305524649960058, 'reg_lambda': 10.0, 'gamma': 0.0031442675323793746, 'early_stopping_rounds': 15}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 36.7660, RMSE: 6.0635, MAE: 3.8026
Starting fold 2...
Fold 2 - MSE: 37.7000, RMSE: 6.1400, MAE: 3.7412
Starting fold 3...
Fold 3 - MSE: 6.9790, RMSE: 2.6418, MAE: 1.8076
Starting fold 4...
Fold 4 - MSE: 30.1178, RMSE: 5.4880, MAE: 4.5461
Starting fold 5...

[INFO 04-02 12:31:08] ax.service.ax_client: Completed trial 47 with data: {'avg_rmse_nonzero': 4.487385}.

Fold 5 - MSE: 4.4253, RMSE: 2.1036, MAE: 1.6863

Mean CV MSE: 23.1976, Mean CV RMSE: 4.4874, Mean CV MAE: 3.1167
Completed trial 47 with mean RMSE: 4.4874 ± 0.8748
Saved Ax client checkpoint

[INFO 04-02 12:31:20] ax.service.ax_client: Generated new trial 48 with parameters {'n_estimators': 2131, 'max_depth': 75, 'learning_rate': 0.005087, 'subsample': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 7, 'reg_alpha': 1e-06, 'reg_lambda': 10.0, 'gamma': 3.228892, 'early_stopping_rounds': 10} using model BoTorch.

Starting trial 48 with parameters: {'n_estimators': 2131, 'max_depth': 75, 'learning_rate': 0.0050870880788350765, 'subsample': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 7, 'reg_alpha': 1e-06, 'reg_lambda': 10.0, 'gamma': 3.2288918709282597, 'early_stopping_rounds': 10}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 38.6977, RMSE: 6.2207, MAE: 4.0454
Starting fold 2...
Fold 2 - MSE: 36.9137, RMSE: 6.0757, MAE: 3.7210
Starting fold 3...
Fold 3 - MSE: 7.0579, RMSE: 2.6567, MAE: 1.8954
Starting fold 4...
Fold 4 - MSE: 29.3559, RMSE: 5.4181, MAE: 4.5304
Starting fold 5...

[INFO 04-02 12:35:23] ax.service.ax_client: Completed trial 48 with data: {'avg_rmse_nonzero': 4.490921}.

Fold 5 - MSE: 4.3406, RMSE: 2.0834, MAE: 1.7135

Mean CV MSE: 23.2732, Mean CV RMSE: 4.4909, Mean CV MAE: 3.1812
Completed trial 48 with mean RMSE: 4.4909 ± 0.8810
Saved Ax client checkpoint

[INFO 04-02 12:35:31] ax.service.ax_client: Generated new trial 49 with parameters {'n_estimators': 9196, 'max_depth': 100, 'learning_rate': 0.005533, 'subsample': 0.5, 'colsample_bytree': 0.664999, 'min_child_weight': 2, 'reg_alpha': 2e-06, 'reg_lambda': 10.0, 'gamma': 4.4e-05, 'early_stopping_rounds': 47} using model BoTorch.

Starting trial 49 with parameters: {'n_estimators': 9196, 'max_depth': 100, 'learning_rate': 0.005532736790179309, 'subsample': 0.5, 'colsample_bytree': 0.6649985716733335, 'min_child_weight': 2, 'reg_alpha': 1.7197758905501837e-06, 'reg_lambda': 10.0, 'gamma': 4.4170405063101454e-05, 'early_stopping_rounds': 47}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 37.2575, RMSE: 6.1039, MAE: 3.9768
Starting fold 2...
Fold 2 - MSE: 35.7039, RMSE: 5.9753, MAE: 3.7409
Starting fold 3...
Fold 3 - MSE: 7.8471, RMSE: 2.8013, MAE: 2.2357
Starting fold 4...
Fold 4 - MSE: 27.2448, RMSE: 5.2197, MAE: 4.3348
Starting fold 5...

[INFO 04-02 12:49:27] ax.service.ax_client: Completed trial 49 with data: {'avg_rmse_nonzero': 4.466699}.

Fold 5 - MSE: 4.9881, RMSE: 2.2334, MAE: 1.9352

Mean CV MSE: 22.6083, Mean CV RMSE: 4.4667, Mean CV MAE: 3.2447
Completed trial 49 with mean RMSE: 4.4667 ± 0.8150
Saved Ax client checkpoint

[INFO 04-02 12:49:40] ax.service.ax_client: Generated new trial 50 with parameters {'n_estimators': 9664, 'max_depth': 3, 'learning_rate': 0.3, 'subsample': 0.600558, 'colsample_bytree': 0.534909, 'min_child_weight': 18, 'reg_alpha': 0.000867, 'reg_lambda': 0.263114, 'gamma': 0.00057, 'early_stopping_rounds': 50} using model BoTorch.

Starting trial 50 with parameters: {'n_estimators': 9664, 'max_depth': 3, 'learning_rate': 0.29999999999999993, 'subsample': 0.600557608132477, 'colsample_bytree': 0.5349086270247091, 'min_child_weight': 18, 'reg_alpha': 0.00086702369691489, 'reg_lambda': 0.26311413416033214, 'gamma': 0.0005697525407062307, 'early_stopping_rounds': 50}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 37.5796, RMSE: 6.1302, MAE: 4.0299
Starting fold 2...
Fold 2 - MSE: 48.6249, RMSE: 6.9732, MAE: 4.5415
Starting fold 3...
Fold 3 - MSE: 10.2627, RMSE: 3.2036, MAE: 2.2317
Starting fold 4...
Fold 4 - MSE: 36.2955, RMSE: 6.0246, MAE: 4.8823
Starting fold 5...

[INFO 04-02 12:50:02] ax.service.ax_client: Completed trial 50 with data: {'avg_rmse_nonzero': 4.995815}.

Fold 5 - MSE: 7.0097, RMSE: 2.6476, MAE: 1.9909

Mean CV MSE: 27.9545, Mean CV RMSE: 4.9958, Mean CV MAE: 3.5353
Completed trial 50 with mean RMSE: 4.9958 ± 0.8655
Saved Ax client checkpoint

[INFO 04-02 12:50:12] ax.service.ax_client: Generated new trial 51 with parameters {'n_estimators': 216, 'max_depth': 11, 'learning_rate': 0.005, 'subsample': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 12, 'reg_alpha': 0.012049, 'reg_lambda': 0.00453, 'gamma': 1e-06, 'early_stopping_rounds': 43} using model BoTorch.

Starting trial 51 with parameters: {'n_estimators': 216, 'max_depth': 11, 'learning_rate': 0.005, 'subsample': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 12, 'reg_alpha': 0.01204873459229495, 'reg_lambda': 0.004530041702304954, 'gamma': 1e-06, 'early_stopping_rounds': 43}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 37.0288, RMSE: 6.0851, MAE: 3.9940
Starting fold 2...
Fold 2 - MSE: 32.9717, RMSE: 5.7421, MAE: 3.7141
Starting fold 3...
Fold 3 - MSE: 7.3582, RMSE: 2.7126, MAE: 2.0841
Starting fold 4...
Fold 4 - MSE: 26.5492, RMSE: 5.1526, MAE: 4.2736
Starting fold 5...

[INFO 04-02 12:50:53] ax.service.ax_client: Completed trial 51 with data: {'avg_rmse_nonzero': 4.405897}.

Fold 5 - MSE: 5.4619, RMSE: 2.3371, MAE: 2.0291

Mean CV MSE: 21.8740, Mean CV RMSE: 4.4059, Mean CV MAE: 3.2190
Completed trial 51 with mean RMSE: 4.4059 ± 0.7845
Saved Ax client checkpoint

[INFO 04-02 12:51:09] ax.service.ax_client: Generated new trial 52 with parameters {'n_estimators': 1197, 'max_depth': 94, 'learning_rate': 0.005, 'subsample': 0.504172, 'colsample_bytree': 0.447171, 'min_child_weight': 7, 'reg_alpha': 6.6e-05, 'reg_lambda': 0.003236, 'gamma': 5.0, 'early_stopping_rounds': 46} using model BoTorch.

Starting trial 52 with parameters: {'n_estimators': 1197, 'max_depth': 94, 'learning_rate': 0.005, 'subsample': 0.5041715125464039, 'colsample_bytree': 0.4471706802015502, 'min_child_weight': 7, 'reg_alpha': 6.631444195758338e-05, 'reg_lambda': 0.003235868116415804, 'gamma': 5.0, 'early_stopping_rounds': 46}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 37.7412, RMSE: 6.1434, MAE: 4.0186
Starting fold 2...
Fold 2 - MSE: 36.0787, RMSE: 6.0066, MAE: 3.7150
Starting fold 3...
Fold 3 - MSE: 7.2321, RMSE: 2.6893, MAE: 1.8823
Starting fold 4...
Fold 4 - MSE: 28.0476, RMSE: 5.2960, MAE: 4.4082
Starting fold 5...

[INFO 04-02 12:54:29] ax.service.ax_client: Completed trial 52 with data: {'avg_rmse_nonzero': 4.437221}.

Fold 5 - MSE: 4.2063, RMSE: 2.0509, MAE: 1.5400

Mean CV MSE: 22.6612, Mean CV RMSE: 4.4372, Mean CV MAE: 3.1128
Completed trial 52 with mean RMSE: 4.4372 ± 0.8620
Saved Ax client checkpoint

[INFO 04-02 12:54:39] ax.service.ax_client: Generated new trial 53 with parameters {'n_estimators': 467, 'max_depth': 35, 'learning_rate': 0.3, 'subsample': 1.0, 'colsample_bytree': 0.3, 'min_child_weight': 20, 'reg_alpha': 1e-06, 'reg_lambda': 0.003401, 'gamma': 1e-06, 'early_stopping_rounds': 10} using model BoTorch.

Starting trial 53 with parameters: {'n_estimators': 467, 'max_depth': 35, 'learning_rate': 0.29999999999999993, 'subsample': 1.0, 'colsample_bytree': 0.3, 'min_child_weight': 20, 'reg_alpha': 1e-06, 'reg_lambda': 0.0034014779200019314, 'gamma': 1e-06, 'early_stopping_rounds': 10}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 44.6357, RMSE: 6.6810, MAE: 4.2421
Starting fold 2...
Fold 2 - MSE: 35.0814, RMSE: 5.9230, MAE: 3.6239
Starting fold 3...
Fold 3 - MSE: 8.4058, RMSE: 2.8993, MAE: 1.9153
Starting fold 4...
Fold 4 - MSE: 27.2306, RMSE: 5.2183, MAE: 4.2378
Starting fold 5...

[INFO 04-02 12:54:52] ax.service.ax_client: Completed trial 53 with data: {'avg_rmse_nonzero': 4.609718}.

Fold 5 - MSE: 5.4153, RMSE: 2.3271, MAE: 1.6296

Mean CV MSE: 24.1537, Mean CV RMSE: 4.6097, Mean CV MAE: 3.1297
Completed trial 53 with mean RMSE: 4.6097 ± 0.8521
Saved Ax client checkpoint

[INFO 04-02 12:55:06] ax.service.ax_client: Generated new trial 54 with parameters {'n_estimators': 207, 'max_depth': 100, 'learning_rate': 0.005075, 'subsample': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 18, 'reg_alpha': 4e-06, 'reg_lambda': 4e-06, 'gamma': 2e-06, 'early_stopping_rounds': 10} using model BoTorch.

Starting trial 54 with parameters: {'n_estimators': 207, 'max_depth': 100, 'learning_rate': 0.005075324895959914, 'subsample': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 18, 'reg_alpha': 3.664264820293871e-06, 'reg_lambda': 3.807276067258683e-06, 'gamma': 1.828567217354151e-06, 'early_stopping_rounds': 10}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 37.4990, RMSE: 6.1236, MAE: 3.9790
Starting fold 2...
Fold 2 - MSE: 32.6936, RMSE: 5.7178, MAE: 3.6520
Starting fold 3...
Fold 3 - MSE: 7.4419, RMSE: 2.7280, MAE: 2.1080
Starting fold 4...
Fold 4 - MSE: 26.3263, RMSE: 5.1309, MAE: 4.2441
Starting fold 5...

[INFO 04-02 12:55:41] ax.service.ax_client: Completed trial 54 with data: {'avg_rmse_nonzero': 4.42611}.

Fold 5 - MSE: 5.9057, RMSE: 2.4302, MAE: 2.1183

Mean CV MSE: 21.9733, Mean CV RMSE: 4.4261, Mean CV MAE: 3.2203
Completed trial 54 with mean RMSE: 4.4261 ± 0.7718
Saved Ax client checkpoint

[INFO 04-02 12:55:51] ax.service.ax_client: Generated new trial 55 with parameters {'n_estimators': 7325, 'max_depth': 3, 'learning_rate': 0.005, 'subsample': 1.0, 'colsample_bytree': 0.614181, 'min_child_weight': 1, 'reg_alpha': 10.0, 'reg_lambda': 0.287724, 'gamma': 5.0, 'early_stopping_rounds': 33} using model BoTorch.

Starting trial 55 with parameters: {'n_estimators': 7325, 'max_depth': 3, 'learning_rate': 0.005, 'subsample': 1.0, 'colsample_bytree': 0.6141805646914869, 'min_child_weight': 1, 'reg_alpha': 10.0, 'reg_lambda': 0.2877238630291143, 'gamma': 5.0, 'early_stopping_rounds': 33}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 37.3797, RMSE: 6.1139, MAE: 3.9034
Starting fold 2...
Fold 2 - MSE: 40.8822, RMSE: 6.3939, MAE: 3.7520
Starting fold 3...
Fold 3 - MSE: 8.8589, RMSE: 2.9764, MAE: 2.0595
Starting fold 4...
Fold 4 - MSE: 34.6802, RMSE: 5.8890, MAE: 4.8275
Starting fold 5...

[INFO 04-02 12:58:31] ax.service.ax_client: Completed trial 55 with data: {'avg_rmse_nonzero': 4.656952}.

Fold 5 - MSE: 3.6541, RMSE: 1.9116, MAE: 1.4987

Mean CV MSE: 25.0910, Mean CV RMSE: 4.6570, Mean CV MAE: 3.2082
Completed trial 55 with mean RMSE: 4.6570 ± 0.9225
Saved Ax client checkpoint

[INFO 04-02 12:58:46] ax.service.ax_client: Generated new trial 56 with parameters {'n_estimators': 561, 'max_depth': 72, 'learning_rate': 0.005, 'subsample': 0.5, 'colsample_bytree': 0.831018, 'min_child_weight': 11, 'reg_alpha': 1e-06, 'reg_lambda': 0.092707, 'gamma': 1.8e-05, 'early_stopping_rounds': 50} using model BoTorch.

Starting trial 56 with parameters: {'n_estimators': 561, 'max_depth': 72, 'learning_rate': 0.005, 'subsample': 0.5, 'colsample_bytree': 0.8310177323422584, 'min_child_weight': 11, 'reg_alpha': 1.2691200045752463e-06, 'reg_lambda': 0.0927070298140589, 'gamma': 1.7729986440845585e-05, 'early_stopping_rounds': 50}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 37.2410, RMSE: 6.1025, MAE: 3.9425
Starting fold 2...
Fold 2 - MSE: 34.7839, RMSE: 5.8978, MAE: 3.7262
Starting fold 3...
Fold 3 - MSE: 6.9712, RMSE: 2.6403, MAE: 1.8298
Starting fold 4...
Fold 4 - MSE: 28.1950, RMSE: 5.3099, MAE: 4.4596
Starting fold 5...

[INFO 04-02 13:00:29] ax.service.ax_client: Completed trial 56 with data: {'avg_rmse_nonzero': 4.432013}.

Fold 5 - MSE: 4.8820, RMSE: 2.2095, MAE: 1.9155

Mean CV MSE: 22.4146, Mean CV RMSE: 4.4320, Mean CV MAE: 3.1747
Completed trial 56 with mean RMSE: 4.4320 ± 0.8325
Saved Ax client checkpoint

[INFO 04-02 13:00:37] ax.service.ax_client: Generated new trial 57 with parameters {'n_estimators': 9163, 'max_depth': 3, 'learning_rate': 0.005, 'subsample': 1.0, 'colsample_bytree': 0.976514, 'min_child_weight': 1, 'reg_alpha': 10.0, 'reg_lambda': 1e-06, 'gamma': 2e-06, 'early_stopping_rounds': 50} using model BoTorch.

Starting trial 57 with parameters: {'n_estimators': 9163, 'max_depth': 3, 'learning_rate': 0.005, 'subsample': 1.0, 'colsample_bytree': 0.9765143630363413, 'min_child_weight': 1, 'reg_alpha': 10.0, 'reg_lambda': 1e-06, 'gamma': 2.2115461518183297e-06, 'early_stopping_rounds': 50}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 36.5656, RMSE: 6.0470, MAE: 3.8797
Starting fold 2...
Fold 2 - MSE: 43.7333, RMSE: 6.6131, MAE: 3.9597
Starting fold 3...
Fold 3 - MSE: 8.4225, RMSE: 2.9022, MAE: 1.8911
Starting fold 4...
Fold 4 - MSE: 36.9012, RMSE: 6.0746, MAE: 4.9927
Starting fold 5...

[INFO 04-02 13:06:37] ax.service.ax_client: Completed trial 57 with data: {'avg_rmse_nonzero': 4.697154}.

Fold 5 - MSE: 3.4185, RMSE: 1.8489, MAE: 1.3491

Mean CV MSE: 25.8082, Mean CV RMSE: 4.6972, Mean CV MAE: 3.2145
Completed trial 57 with mean RMSE: 4.6972 ± 0.9676
Saved Ax client checkpoint

[INFO 04-02 13:06:48] ax.service.ax_client: Generated new trial 58 with parameters {'n_estimators': 233, 'max_depth': 27, 'learning_rate': 0.033885, 'subsample': 0.793969, 'colsample_bytree': 1.0, 'min_child_weight': 4, 'reg_alpha': 1e-06, 'reg_lambda': 6.972256, 'gamma': 0.000505, 'early_stopping_rounds': 24} using model BoTorch.

Starting trial 58 with parameters: {'n_estimators': 233, 'max_depth': 27, 'learning_rate': 0.03388490285002263, 'subsample': 0.7939689678331315, 'colsample_bytree': 1.0, 'min_child_weight': 4, 'reg_alpha': 1e-06, 'reg_lambda': 6.972256360978679, 'gamma': 0.0005050842737829022, 'early_stopping_rounds': 24}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 37.0039, RMSE: 6.0831, MAE: 3.9771
Starting fold 2...
Fold 2 - MSE: 37.1337, RMSE: 6.0937, MAE: 3.7916
Starting fold 3...
Fold 3 - MSE: 8.7600, RMSE: 2.9597, MAE: 2.3885
Starting fold 4...
Fold 4 - MSE: 29.3683, RMSE: 5.4193, MAE: 4.5904
Starting fold 5...

[INFO 04-02 13:08:11] ax.service.ax_client: Completed trial 58 with data: {'avg_rmse_nonzero': 4.547562}.

Fold 5 - MSE: 4.7611, RMSE: 2.1820, MAE: 1.9221

Mean CV MSE: 23.4054, Mean CV RMSE: 4.5476, Mean CV MAE: 3.3340
Completed trial 58 with mean RMSE: 4.5476 ± 0.8254
Saved Ax client checkpoint

[INFO 04-02 13:08:22] ax.service.ax_client: Generated new trial 59 with parameters {'n_estimators': 1252, 'max_depth': 83, 'learning_rate': 0.06079, 'subsample': 0.802307, 'colsample_bytree': 0.974942, 'min_child_weight': 13, 'reg_alpha': 8.9e-05, 'reg_lambda': 10.0, 'gamma': 5e-06, 'early_stopping_rounds': 45} using model BoTorch.

Starting trial 59 with parameters: {'n_estimators': 1252, 'max_depth': 83, 'learning_rate': 0.06078982468755325, 'subsample': 0.8023074988224416, 'colsample_bytree': 0.9749416601492179, 'min_child_weight': 13, 'reg_alpha': 8.928234276900651e-05, 'reg_lambda': 10.0, 'gamma': 5.410125299705749e-06, 'early_stopping_rounds': 45}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 39.7982, RMSE: 6.3086, MAE: 4.0834
Starting fold 2...
Fold 2 - MSE: 40.4192, RMSE: 6.3576, MAE: 3.9551
Starting fold 3...
Fold 3 - MSE: 7.1414, RMSE: 2.6723, MAE: 1.9146
Starting fold 4...
Fold 4 - MSE: 30.7859, RMSE: 5.5485, MAE: 4.6561
Starting fold 5...

[INFO 04-02 13:09:37] ax.service.ax_client: Completed trial 59 with data: {'avg_rmse_nonzero': 4.53005}.

Fold 5 - MSE: 3.1089, RMSE: 1.7632, MAE: 1.3446

Mean CV MSE: 24.2507, Mean CV RMSE: 4.5300, Mean CV MAE: 3.1907
Completed trial 59 with mean RMSE: 4.5300 ± 0.9656
Saved Ax client checkpoint

[INFO 04-02 13:09:56] ax.service.ax_client: Generated new trial 60 with parameters {'n_estimators': 5965, 'max_depth': 100, 'learning_rate': 0.087466, 'subsample': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 20, 'reg_alpha': 0.001208, 'reg_lambda': 0.08909, 'gamma': 5.0, 'early_stopping_rounds': 50} using model BoTorch.

Starting trial 60 with parameters: {'n_estimators': 5965, 'max_depth': 100, 'learning_rate': 0.0874660763261133, 'subsample': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 20, 'reg_alpha': 0.0012078530733079565, 'reg_lambda': 0.08908952720575494, 'gamma': 5.0, 'early_stopping_rounds': 50}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 39.5117, RMSE: 6.2858, MAE: 4.0133
Starting fold 2...
Fold 2 - MSE: 44.0819, RMSE: 6.6394, MAE: 4.1191
Starting fold 3...
Fold 3 - MSE: 6.6112, RMSE: 2.5712, MAE: 1.8095
Starting fold 4...
Fold 4 - MSE: 30.7244, RMSE: 5.5430, MAE: 4.5768
Starting fold 5...

[INFO 04-02 13:10:40] ax.service.ax_client: Completed trial 60 with data: {'avg_rmse_nonzero': 4.706377}.

Fold 5 - MSE: 6.2123, RMSE: 2.4925, MAE: 1.9130

Mean CV MSE: 25.4283, Mean CV RMSE: 4.7064, Mean CV MAE: 3.2864
Completed trial 60 with mean RMSE: 4.7064 ± 0.9053
Saved Ax client checkpoint

[INFO 04-02 13:10:50] ax.service.ax_client: Generated new trial 61 with parameters {'n_estimators': 451, 'max_depth': 3, 'learning_rate': 0.186871, 'subsample': 0.561326, 'colsample_bytree': 0.305467, 'min_child_weight': 20, 'reg_alpha': 1e-06, 'reg_lambda': 10.0, 'gamma': 5.0, 'early_stopping_rounds': 10} using model BoTorch.

Starting trial 61 with parameters: {'n_estimators': 451, 'max_depth': 3, 'learning_rate': 0.1868706233115249, 'subsample': 0.5613258940229823, 'colsample_bytree': 0.3054674728665731, 'min_child_weight': 20, 'reg_alpha': 1e-06, 'reg_lambda': 10.0, 'gamma': 5.0, 'early_stopping_rounds': 10}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 38.9693, RMSE: 6.2425, MAE: 4.0177
Starting fold 2...
Fold 2 - MSE: 32.3874, RMSE: 5.6910, MAE: 3.3819
Starting fold 3...
Fold 3 - MSE: 7.6570, RMSE: 2.7671, MAE: 1.9136
Starting fold 4...
Fold 4 - MSE: 29.0895, RMSE: 5.3935, MAE: 4.4619
Starting fold 5...

[INFO 04-02 13:11:03] ax.service.ax_client: Completed trial 61 with data: {'avg_rmse_nonzero': 4.445901}.

Fold 5 - MSE: 4.5598, RMSE: 2.1354, MAE: 1.7609

Mean CV MSE: 22.5326, Mean CV RMSE: 4.4459, Mean CV MAE: 3.1072
Completed trial 61 with mean RMSE: 4.4459 ± 0.8317
Saved Ax client checkpoint

[INFO 04-02 13:11:14] ax.service.ax_client: Generated new trial 62 with parameters {'n_estimators': 8124, 'max_depth': 3, 'learning_rate': 0.218292, 'subsample': 0.5, 'colsample_bytree': 0.3, 'min_child_weight': 20, 'reg_alpha': 1e-06, 'reg_lambda': 10.0, 'gamma': 5.0, 'early_stopping_rounds': 20} using model BoTorch.

Starting trial 62 with parameters: {'n_estimators': 8124, 'max_depth': 3, 'learning_rate': 0.2182921614270319, 'subsample': 0.5, 'colsample_bytree': 0.3, 'min_child_weight': 20, 'reg_alpha': 1e-06, 'reg_lambda': 10.0, 'gamma': 5.0, 'early_stopping_rounds': 20}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 36.9058, RMSE: 6.0750, MAE: 3.9591
Starting fold 2...
Fold 2 - MSE: 49.3436, RMSE: 7.0245, MAE: 4.4221
Starting fold 3...
Fold 3 - MSE: 10.2192, RMSE: 3.1968, MAE: 2.1722
Starting fold 4...
Fold 4 - MSE: 29.7187, RMSE: 5.4515, MAE: 4.3738
Starting fold 5...

[INFO 04-02 13:11:34] ax.service.ax_client: Completed trial 62 with data: {'avg_rmse_nonzero': 4.750954}.

Fold 5 - MSE: 4.0281, RMSE: 2.0070, MAE: 1.4710

Mean CV MSE: 26.0431, Mean CV RMSE: 4.7510, Mean CV MAE: 3.2796
Completed trial 62 with mean RMSE: 4.7510 ± 0.9316
Saved Ax client checkpoint

[INFO 04-02 13:11:47] ax.service.ax_client: Generated new trial 63 with parameters {'n_estimators': 9471, 'max_depth': 88, 'learning_rate': 0.008849, 'subsample': 0.896461, 'colsample_bytree': 0.346331, 'min_child_weight': 1, 'reg_alpha': 1e-06, 'reg_lambda': 10.0, 'gamma': 0.000254, 'early_stopping_rounds': 40} using model BoTorch.

Starting trial 63 with parameters: {'n_estimators': 9471, 'max_depth': 88, 'learning_rate': 0.008848641034404256, 'subsample': 0.896460909307945, 'colsample_bytree': 0.3463305747845051, 'min_child_weight': 1, 'reg_alpha': 1e-06, 'reg_lambda': 10.0, 'gamma': 0.00025432733379015577, 'early_stopping_rounds': 40}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 37.7445, RMSE: 6.1437, MAE: 4.0370
Starting fold 2...
Fold 2 - MSE: 33.5166, RMSE: 5.7894, MAE: 3.6831
Starting fold 3...
Fold 3 - MSE: 10.1945, RMSE: 3.1929, MAE: 2.4576
Starting fold 4...
Fold 4 - MSE: 26.6668, RMSE: 5.1640, MAE: 4.2784
Starting fold 5...

[INFO 04-02 13:28:42] ax.service.ax_client: Completed trial 63 with data: {'avg_rmse_nonzero': 4.446865}.

Fold 5 - MSE: 3.7808, RMSE: 1.9444, MAE: 1.6401

Mean CV MSE: 22.3807, Mean CV RMSE: 4.4469, Mean CV MAE: 3.2192
Completed trial 63 with mean RMSE: 4.4469 ± 0.8072
Saved Ax client checkpoint

[INFO 04-02 13:28:53] ax.service.ax_client: Generated new trial 64 with parameters {'n_estimators': 4360, 'max_depth': 7, 'learning_rate': 0.3, 'subsample': 0.5, 'colsample_bytree': 0.878744, 'min_child_weight': 10, 'reg_alpha': 10.0, 'reg_lambda': 5.3e-05, 'gamma': 9e-06, 'early_stopping_rounds': 10} using model BoTorch.

Starting trial 64 with parameters: {'n_estimators': 4360, 'max_depth': 7, 'learning_rate': 0.29999999999999993, 'subsample': 0.5, 'colsample_bytree': 0.8787435134475466, 'min_child_weight': 10, 'reg_alpha': 10.0, 'reg_lambda': 5.268204374995844e-05, 'gamma': 9.126565834251148e-06, 'early_stopping_rounds': 10}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 38.4482, RMSE: 6.2007, MAE: 4.1338
Starting fold 2...
Fold 2 - MSE: 41.6522, RMSE: 6.4539, MAE: 4.0347
Starting fold 3...
Fold 3 - MSE: 8.3745, RMSE: 2.8939, MAE: 2.1606
Starting fold 4...
Fold 4 - MSE: 32.0198, RMSE: 5.6586, MAE: 4.6449
Starting fold 5...

[INFO 04-02 13:29:06] ax.service.ax_client: Completed trial 64 with data: {'avg_rmse_nonzero': 4.795082}.

Fold 5 - MSE: 7.6641, RMSE: 2.7684, MAE: 2.1816

Mean CV MSE: 25.6318, Mean CV RMSE: 4.7951, Mean CV MAE: 3.4311
Completed trial 64 with mean RMSE: 4.7951 ± 0.8122
Saved Ax client checkpoint

[INFO 04-02 13:29:21] ax.service.ax_client: Generated new trial 65 with parameters {'n_estimators': 9046, 'max_depth': 3, 'learning_rate': 0.161522, 'subsample': 0.5, 'colsample_bytree': 0.3, 'min_child_weight': 19, 'reg_alpha': 7e-06, 'reg_lambda': 2.837719, 'gamma': 5.0, 'early_stopping_rounds': 49} using model BoTorch.

Starting trial 65 with parameters: {'n_estimators': 9046, 'max_depth': 3, 'learning_rate': 0.16152238250612114, 'subsample': 0.5, 'colsample_bytree': 0.3, 'min_child_weight': 19, 'reg_alpha': 7.169353084013499e-06, 'reg_lambda': 2.837719281061234, 'gamma': 5.0, 'early_stopping_rounds': 49}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 37.1598, RMSE: 6.0959, MAE: 3.9866
Starting fold 2...
Fold 2 - MSE: 39.9775, RMSE: 6.3228, MAE: 3.8373
Starting fold 3...
Fold 3 - MSE: 8.8973, RMSE: 2.9828, MAE: 1.9897
Starting fold 4...
Fold 4 - MSE: 29.2382, RMSE: 5.4072, MAE: 4.3125
Starting fold 5...

[INFO 04-02 13:29:53] ax.service.ax_client: Completed trial 65 with data: {'avg_rmse_nonzero': 4.566236}.

Fold 5 - MSE: 4.0903, RMSE: 2.0225, MAE: 1.5358

Mean CV MSE: 23.8726, Mean CV RMSE: 4.5662, Mean CV MAE: 3.1324
Completed trial 65 with mean RMSE: 4.5662 ± 0.8692
Saved Ax client checkpoint

[INFO 04-02 13:30:10] ax.service.ax_client: Generated new trial 66 with parameters {'n_estimators': 142, 'max_depth': 46, 'learning_rate': 0.005, 'subsample': 0.706751, 'colsample_bytree': 1.0, 'min_child_weight': 20, 'reg_alpha': 5e-06, 'reg_lambda': 1.1e-05, 'gamma': 3.9e-05, 'early_stopping_rounds': 46} using model BoTorch.

Starting trial 66 with parameters: {'n_estimators': 142, 'max_depth': 46, 'learning_rate': 0.005, 'subsample': 0.7067509404073082, 'colsample_bytree': 1.0, 'min_child_weight': 20, 'reg_alpha': 4.554009308232171e-06, 'reg_lambda': 1.1433782915833515e-05, 'gamma': 3.858892345933954e-05, 'early_stopping_rounds': 46}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 37.3614, RMSE: 6.1124, MAE: 4.0163
Starting fold 2...
Fold 2 - MSE: 32.6107, RMSE: 5.7106, MAE: 3.7535
Starting fold 3...
Fold 3 - MSE: 7.8727, RMSE: 2.8058, MAE: 2.2731
Starting fold 4...
Fold 4 - MSE: 26.1941, RMSE: 5.1180, MAE: 4.2043
Starting fold 5...

[INFO 04-02 13:30:36] ax.service.ax_client: Completed trial 66 with data: {'avg_rmse_nonzero': 4.456427}.

Fold 5 - MSE: 6.4278, RMSE: 2.5353, MAE: 2.1817

Mean CV MSE: 22.0933, Mean CV RMSE: 4.4564, Mean CV MAE: 3.2858
Completed trial 66 with mean RMSE: 4.4564 ± 0.7473
Saved Ax client checkpoint

[INFO 04-02 13:30:47] ax.service.ax_client: Generated new trial 67 with parameters {'n_estimators': 2584, 'max_depth': 100, 'learning_rate': 0.043467, 'subsample': 0.734169, 'colsample_bytree': 1.0, 'min_child_weight': 20, 'reg_alpha': 8.911889, 'reg_lambda': 1e-06, 'gamma': 5.0, 'early_stopping_rounds': 50} using model BoTorch.

Starting trial 67 with parameters: {'n_estimators': 2584, 'max_depth': 100, 'learning_rate': 0.04346745131525448, 'subsample': 0.7341687434522921, 'colsample_bytree': 1.0, 'min_child_weight': 20, 'reg_alpha': 8.911889346018334, 'reg_lambda': 1e-06, 'gamma': 5.0, 'early_stopping_rounds': 50}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 36.3960, RMSE: 6.0329, MAE: 3.7734
Starting fold 2...
Fold 2 - MSE: 40.3564, RMSE: 6.3527, MAE: 3.8702
Starting fold 3...
Fold 3 - MSE: 7.8055, RMSE: 2.7938, MAE: 1.9444
Starting fold 4...
Fold 4 - MSE: 33.8784, RMSE: 5.8205, MAE: 4.8603
Starting fold 5...

[INFO 04-02 13:31:40] ax.service.ax_client: Completed trial 67 with data: {'avg_rmse_nonzero': 4.634039}.

Fold 5 - MSE: 4.7100, RMSE: 2.1703, MAE: 1.5973

Mean CV MSE: 24.6293, Mean CV RMSE: 4.6340, Mean CV MAE: 3.2091
Completed trial 67 with mean RMSE: 4.6340 ± 0.8881
Saved Ax client checkpoint

[INFO 04-02 13:31:46] ax.service.ax_client: Generated new trial 68 with parameters {'n_estimators': 2730, 'max_depth': 83, 'learning_rate': 0.008327, 'subsample': 0.511249, 'colsample_bytree': 0.434606, 'min_child_weight': 17, 'reg_alpha': 1.3e-05, 'reg_lambda': 2.5e-05, 'gamma': 1e-06, 'early_stopping_rounds': 46} using model BoTorch.

Starting trial 68 with parameters: {'n_estimators': 2730, 'max_depth': 83, 'learning_rate': 0.008327437453755662, 'subsample': 0.5112489857331046, 'colsample_bytree': 0.4346058590192687, 'min_child_weight': 17, 'reg_alpha': 1.283749216840907e-05, 'reg_lambda': 2.5458015433882155e-05, 'gamma': 1e-06, 'early_stopping_rounds': 46}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 36.9921, RMSE: 6.0821, MAE: 3.8390
Starting fold 2...
Fold 2 - MSE: 36.0872, RMSE: 6.0073, MAE: 3.7234
Starting fold 3...
Fold 3 - MSE: 7.3970, RMSE: 2.7197, MAE: 1.7934
Starting fold 4...
Fold 4 - MSE: 28.9646, RMSE: 5.3819, MAE: 4.5003
Starting fold 5...

[INFO 04-02 13:35:16] ax.service.ax_client: Completed trial 68 with data: {'avg_rmse_nonzero': 4.46287}.

Fold 5 - MSE: 4.5086, RMSE: 2.1234, MAE: 1.6049

Mean CV MSE: 22.7899, Mean CV RMSE: 4.4629, Mean CV MAE: 3.0922
Completed trial 68 with mean RMSE: 4.4629 ± 0.8475
Saved Ax client checkpoint

[INFO 04-02 13:35:36] ax.service.ax_client: Generated new trial 69 with parameters {'n_estimators': 2868, 'max_depth': 3, 'learning_rate': 0.040464, 'subsample': 1.0, 'colsample_bytree': 0.309866, 'min_child_weight': 2, 'reg_alpha': 10.0, 'reg_lambda': 0.015362, 'gamma': 5.0, 'early_stopping_rounds': 38} using model BoTorch.

Starting trial 69 with parameters: {'n_estimators': 2868, 'max_depth': 3, 'learning_rate': 0.04046384151749584, 'subsample': 1.0, 'colsample_bytree': 0.309866321009103, 'min_child_weight': 2, 'reg_alpha': 10.0, 'reg_lambda': 0.015362131264036237, 'gamma': 5.0, 'early_stopping_rounds': 38}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 37.0175, RMSE: 6.0842, MAE: 3.8705
Starting fold 2...
Fold 2 - MSE: 38.6572, RMSE: 6.2175, MAE: 3.6748
Starting fold 3...
Fold 3 - MSE: 9.7531, RMSE: 3.1230, MAE: 2.4033
Starting fold 4...
Fold 4 - MSE: 30.7804, RMSE: 5.5480, MAE: 4.5959
Starting fold 5...

[INFO 04-02 13:36:06] ax.service.ax_client: Completed trial 69 with data: {'avg_rmse_nonzero': 4.562087}.

Fold 5 - MSE: 3.3773, RMSE: 1.8377, MAE: 1.4023

Mean CV MSE: 23.9171, Mean CV RMSE: 4.5621, Mean CV MAE: 3.1894
Completed trial 69 with mean RMSE: 4.5621 ± 0.8810
Saved Ax client checkpoint

[INFO 04-02 13:36:18] ax.service.ax_client: Generated new trial 70 with parameters {'n_estimators': 9761, 'max_depth': 7, 'learning_rate': 0.010112, 'subsample': 0.573296, 'colsample_bytree': 0.460874, 'min_child_weight': 19, 'reg_alpha': 0.849987, 'reg_lambda': 0.000372, 'gamma': 2.7e-05, 'early_stopping_rounds': 42} using model BoTorch.

Starting trial 70 with parameters: {'n_estimators': 9761, 'max_depth': 7, 'learning_rate': 0.010112252265401137, 'subsample': 0.5732960561352389, 'colsample_bytree': 0.46087389615966456, 'min_child_weight': 19, 'reg_alpha': 0.8499866209490453, 'reg_lambda': 0.00037241789281478255, 'gamma': 2.6509640345045384e-05, 'early_stopping_rounds': 42}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 36.7498, RMSE: 6.0622, MAE: 3.8177
Starting fold 2...
Fold 2 - MSE: 37.0798, RMSE: 6.0893, MAE: 3.7320
Starting fold 3...
Fold 3 - MSE: 7.7500, RMSE: 2.7839, MAE: 1.8386
Starting fold 4...
Fold 4 - MSE: 29.5549, RMSE: 5.4364, MAE: 4.5367
Starting fold 5...

[INFO 04-02 13:39:19] ax.service.ax_client: Completed trial 70 with data: {'avg_rmse_nonzero': 4.493228}.

Fold 5 - MSE: 4.3862, RMSE: 2.0943, MAE: 1.5408

Mean CV MSE: 23.1042, Mean CV RMSE: 4.4932, Mean CV MAE: 3.0932
Completed trial 70 with mean RMSE: 4.4932 ± 0.8537
Saved Ax client checkpoint

[INFO 04-02 13:39:35] ax.service.ax_client: Generated new trial 71 with parameters {'n_estimators': 344, 'max_depth': 93, 'learning_rate': 0.005, 'subsample': 0.5, 'colsample_bytree': 0.84473, 'min_child_weight': 17, 'reg_alpha': 0.168547, 'reg_lambda': 0.002821, 'gamma': 1e-06, 'early_stopping_rounds': 33} using model BoTorch.

Starting trial 71 with parameters: {'n_estimators': 344, 'max_depth': 93, 'learning_rate': 0.005, 'subsample': 0.5, 'colsample_bytree': 0.8447301688876951, 'min_child_weight': 17, 'reg_alpha': 0.16854739772176777, 'reg_lambda': 0.0028207362444481387, 'gamma': 1e-06, 'early_stopping_rounds': 33}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 37.3881, RMSE: 6.1146, MAE: 3.9357
Starting fold 2...
Fold 2 - MSE: 33.7369, RMSE: 5.8084, MAE: 3.6539
Starting fold 3...
Fold 3 - MSE: 6.9228, RMSE: 2.6311, MAE: 1.9073
Starting fold 4...
Fold 4 - MSE: 27.3432, RMSE: 5.2291, MAE: 4.3501
Starting fold 5...

[INFO 04-02 13:40:30] ax.service.ax_client: Completed trial 71 with data: {'avg_rmse_nonzero': 4.426956}.

Fold 5 - MSE: 5.5303, RMSE: 2.3516, MAE: 2.0897

Mean CV MSE: 22.1843, Mean CV RMSE: 4.4270, Mean CV MAE: 3.1873
Completed trial 71 with mean RMSE: 4.4270 ± 0.8041
Saved Ax client checkpoint

[INFO 04-02 13:40:36] ax.service.ax_client: Generated new trial 72 with parameters {'n_estimators': 100, 'max_depth': 3, 'learning_rate': 0.094312, 'subsample': 0.542496, 'colsample_bytree': 0.913674, 'min_child_weight': 20, 'reg_alpha': 0.044752, 'reg_lambda': 10.0, 'gamma': 1e-06, 'early_stopping_rounds': 50} using model BoTorch.

Starting trial 72 with parameters: {'n_estimators': 100, 'max_depth': 3, 'learning_rate': 0.0943121620472355, 'subsample': 0.5424961242252859, 'colsample_bytree': 0.9136738898650708, 'min_child_weight': 20, 'reg_alpha': 0.04475155375192308, 'reg_lambda': 10.0, 'gamma': 1e-06, 'early_stopping_rounds': 50}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 36.2184, RMSE: 6.0182, MAE: 3.7484
Starting fold 2...
Fold 2 - MSE: 34.5655, RMSE: 5.8792, MAE: 3.5804
Starting fold 3...
Fold 3 - MSE: 7.7841, RMSE: 2.7900, MAE: 1.9615
Starting fold 4...
Fold 4 - MSE: 31.9483, RMSE: 5.6523, MAE: 4.6091
Starting fold 5...

[INFO 04-02 13:40:51] ax.service.ax_client: Completed trial 72 with data: {'avg_rmse_nonzero': 4.549441}.

Fold 5 - MSE: 5.7960, RMSE: 2.4075, MAE: 2.0904

Mean CV MSE: 23.2625, Mean CV RMSE: 4.5494, Mean CV MAE: 3.1979
Completed trial 72 with mean RMSE: 4.5494 ± 0.8008
Saved Ax client checkpoint

[INFO 04-02 13:41:02] ax.service.ax_client: Generated new trial 73 with parameters {'n_estimators': 8587, 'max_depth': 85, 'learning_rate': 0.036171, 'subsample': 0.500697, 'colsample_bytree': 1.0, 'min_child_weight': 1, 'reg_alpha': 0.031289, 'reg_lambda': 1e-06, 'gamma': 3.689327, 'early_stopping_rounds': 42} using model BoTorch.

Starting trial 73 with parameters: {'n_estimators': 8587, 'max_depth': 85, 'learning_rate': 0.036170838287740814, 'subsample': 0.5006971589867281, 'colsample_bytree': 1.0, 'min_child_weight': 1, 'reg_alpha': 0.031289427320735946, 'reg_lambda': 1e-06, 'gamma': 3.689327179170117, 'early_stopping_rounds': 42}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 36.7691, RMSE: 6.0637, MAE: 4.0703
Starting fold 2...
Fold 2 - MSE: 33.6195, RMSE: 5.7982, MAE: 3.5743
Starting fold 3...
Fold 3 - MSE: 37.3996, RMSE: 6.1155, MAE: 4.6124
Starting fold 4...
Fold 4 - MSE: 29.8012, RMSE: 5.4591, MAE: 4.4287
Starting fold 5...

[INFO 04-02 13:41:48] ax.service.ax_client: Completed trial 73 with data: {'avg_rmse_nonzero': 5.357894}.

Fold 5 - MSE: 11.2421, RMSE: 3.3529, MAE: 2.9025

Mean CV MSE: 29.7663, Mean CV RMSE: 5.3579, Mean CV MAE: 3.9176
Completed trial 73 with mean RMSE: 5.3579 ± 0.5146
Saved Ax client checkpoint

[INFO 04-02 13:42:00] ax.service.ax_client: Generated new trial 74 with parameters {'n_estimators': 221, 'max_depth': 24, 'learning_rate': 0.038949, 'subsample': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 13, 'reg_alpha': 1e-06, 'reg_lambda': 0.010341, 'gamma': 0.000141, 'early_stopping_rounds': 46} using model BoTorch.

Starting trial 74 with parameters: {'n_estimators': 221, 'max_depth': 24, 'learning_rate': 0.03894923271283722, 'subsample': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 13, 'reg_alpha': 1e-06, 'reg_lambda': 0.01034061286488772, 'gamma': 0.00014063677005096562, 'early_stopping_rounds': 46}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 40.8528, RMSE: 6.3916, MAE: 4.2428
Starting fold 2...
Fold 2 - MSE: 37.3706, RMSE: 6.1132, MAE: 3.6826
Starting fold 3...
Fold 3 - MSE: 8.1643, RMSE: 2.8573, MAE: 1.9423
Starting fold 4...
Fold 4 - MSE: 34.5825, RMSE: 5.8807, MAE: 4.8500
Starting fold 5...

[INFO 04-02 13:43:00] ax.service.ax_client: Completed trial 74 with data: {'avg_rmse_nonzero': 4.622769}.

Fold 5 - MSE: 3.5009, RMSE: 1.8711, MAE: 1.2878

Mean CV MSE: 24.8942, Mean CV RMSE: 4.6228, Mean CV MAE: 3.2011
Completed trial 74 with mean RMSE: 4.6228 ± 0.9386
Saved Ax client checkpoint

[INFO 04-02 13:43:10] ax.service.ax_client: Generated new trial 75 with parameters {'n_estimators': 6044, 'max_depth': 43, 'learning_rate': 0.005, 'subsample': 0.5, 'colsample_bytree': 0.3, 'min_child_weight': 19, 'reg_alpha': 3.4e-05, 'reg_lambda': 1.5e-05, 'gamma': 1e-06, 'early_stopping_rounds': 50} using model BoTorch.

Starting trial 75 with parameters: {'n_estimators': 6044, 'max_depth': 43, 'learning_rate': 0.005, 'subsample': 0.5, 'colsample_bytree': 0.3, 'min_child_weight': 19, 'reg_alpha': 3.4412178294728606e-05, 'reg_lambda': 1.4880140230674503e-05, 'gamma': 1e-06, 'early_stopping_rounds': 50}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 36.7537, RMSE: 6.0625, MAE: 3.7888
Starting fold 2...
Fold 2 - MSE: 36.7127, RMSE: 6.0591, MAE: 3.7100
Starting fold 3...
Fold 3 - MSE: 7.4280, RMSE: 2.7254, MAE: 1.7702
Starting fold 4...
Fold 4 - MSE: 28.9386, RMSE: 5.3795, MAE: 4.4843
Starting fold 5...

[INFO 04-02 13:48:49] ax.service.ax_client: Completed trial 75 with data: {'avg_rmse_nonzero': 4.474642}.

Fold 5 - MSE: 4.6084, RMSE: 2.1467, MAE: 1.7559

Mean CV MSE: 22.8883, Mean CV RMSE: 4.4746, Mean CV MAE: 3.1018
Completed trial 75 with mean RMSE: 4.4746 ± 0.8464
Saved Ax client checkpoint

[INFO 04-02 13:49:02] ax.service.ax_client: Generated new trial 76 with parameters {'n_estimators': 5239, 'max_depth': 99, 'learning_rate': 0.205578, 'subsample': 0.977395, 'colsample_bytree': 1.0, 'min_child_weight': 20, 'reg_alpha': 1e-06, 'reg_lambda': 1e-06, 'gamma': 0.000372, 'early_stopping_rounds': 10} using model BoTorch.

Starting trial 76 with parameters: {'n_estimators': 5239, 'max_depth': 99, 'learning_rate': 0.20557842418062613, 'subsample': 0.9773951244124603, 'colsample_bytree': 1.0, 'min_child_weight': 20, 'reg_alpha': 1e-06, 'reg_lambda': 1.144996917935099e-06, 'gamma': 0.00037202956943020737, 'early_stopping_rounds': 10}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 38.6420, RMSE: 6.2163, MAE: 4.0045
Starting fold 2...
Fold 2 - MSE: 38.8655, RMSE: 6.2342, MAE: 3.8132
Starting fold 3...
Fold 3 - MSE: 8.1520, RMSE: 2.8552, MAE: 2.0287
Starting fold 4...
Fold 4 - MSE: 29.9042, RMSE: 5.4685, MAE: 4.4164
Starting fold 5...

[INFO 04-02 13:49:22] ax.service.ax_client: Completed trial 76 with data: {'avg_rmse_nonzero': 4.722614}.

Fold 5 - MSE: 8.0596, RMSE: 2.8389, MAE: 2.4038

Mean CV MSE: 24.7247, Mean CV RMSE: 4.7226, Mean CV MAE: 3.3333
Completed trial 76 with mean RMSE: 4.7226 ± 0.7781
Saved Ax client checkpoint

[INFO 04-02 13:49:36] ax.service.ax_client: Generated new trial 77 with parameters {'n_estimators': 597, 'max_depth': 3, 'learning_rate': 0.20256, 'subsample': 0.932523, 'colsample_bytree': 1.0, 'min_child_weight': 20, 'reg_alpha': 6e-06, 'reg_lambda': 0.87215, 'gamma': 0.330923, 'early_stopping_rounds': 14} using model BoTorch.

Starting trial 77 with parameters: {'n_estimators': 597, 'max_depth': 3, 'learning_rate': 0.20256032387740835, 'subsample': 0.9325226065275773, 'colsample_bytree': 1.0, 'min_child_weight': 20, 'reg_alpha': 5.760246138315301e-06, 'reg_lambda': 0.8721500554839056, 'gamma': 0.3309227084546683, 'early_stopping_rounds': 14}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 36.8114, RMSE: 6.0672, MAE: 3.9478
Starting fold 2...
Fold 2 - MSE: 38.6449, RMSE: 6.2165, MAE: 3.9010
Starting fold 3...
Fold 3 - MSE: 12.5098, RMSE: 3.5369, MAE: 2.3381
Starting fold 4...
Fold 4 - MSE: 30.3162, RMSE: 5.5060, MAE: 4.4804
Starting fold 5...

[INFO 04-02 13:49:50] ax.service.ax_client: Completed trial 77 with data: {'avg_rmse_nonzero': 4.682879}.

Fold 5 - MSE: 4.3586, RMSE: 2.0877, MAE: 1.5363

Mean CV MSE: 24.5282, Mean CV RMSE: 4.6829, Mean CV MAE: 3.2407
Completed trial 77 with mean RMSE: 4.6829 ± 0.8060
Saved Ax client checkpoint

[INFO 04-02 13:49:59] ax.service.ax_client: Generated new trial 78 with parameters {'n_estimators': 8028, 'max_depth': 100, 'learning_rate': 0.062945, 'subsample': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 14, 'reg_alpha': 1e-06, 'reg_lambda': 3.901754, 'gamma': 1e-06, 'early_stopping_rounds': 39} using model BoTorch.

Starting trial 78 with parameters: {'n_estimators': 8028, 'max_depth': 100, 'learning_rate': 0.06294543993069986, 'subsample': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 14, 'reg_alpha': 1e-06, 'reg_lambda': 3.901754010775053, 'gamma': 1e-06, 'early_stopping_rounds': 39}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 38.0625, RMSE: 6.1695, MAE: 4.0696
Starting fold 2...
Fold 2 - MSE: 36.9496, RMSE: 6.0786, MAE: 3.7984
Starting fold 3...
Fold 3 - MSE: 7.6260, RMSE: 2.7615, MAE: 1.9531
Starting fold 4...
Fold 4 - MSE: 32.1361, RMSE: 5.6689, MAE: 4.6976
Starting fold 5...

[INFO 04-02 13:51:03] ax.service.ax_client: Completed trial 78 with data: {'avg_rmse_nonzero': 4.633345}.

Fold 5 - MSE: 6.1913, RMSE: 2.4882, MAE: 2.0687

Mean CV MSE: 24.1931, Mean CV RMSE: 4.6333, Mean CV MAE: 3.3175
Completed trial 78 with mean RMSE: 4.6333 ± 0.8254
Saved Ax client checkpoint

[INFO 04-02 13:51:11] ax.service.ax_client: Generated new trial 79 with parameters {'n_estimators': 10000, 'max_depth': 100, 'learning_rate': 0.005, 'subsample': 1.0, 'colsample_bytree': 0.3, 'min_child_weight': 1, 'reg_alpha': 1e-06, 'reg_lambda': 10.0, 'gamma': 1e-06, 'early_stopping_rounds': 50} using model BoTorch.

Starting trial 79 with parameters: {'n_estimators': 10000, 'max_depth': 100, 'learning_rate': 0.005, 'subsample': 1.0, 'colsample_bytree': 0.3, 'min_child_weight': 1, 'reg_alpha': 1e-06, 'reg_lambda': 10.0, 'gamma': 1e-06, 'early_stopping_rounds': 50}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 38.9842, RMSE: 6.2437, MAE: 4.1347
Starting fold 2...
Fold 2 - MSE: 34.8575, RMSE: 5.9040, MAE: 3.7383
Starting fold 3...
Fold 3 - MSE: 11.6570, RMSE: 3.4142, MAE: 2.5497
Starting fold 4...
Fold 4 - MSE: 27.7248, RMSE: 5.2654, MAE: 4.3217
Starting fold 5...

[INFO 04-02 14:26:45] ax.service.ax_client: Completed trial 79 with data: {'avg_rmse_nonzero': 4.555587}.

Fold 5 - MSE: 3.8045, RMSE: 1.9505, MAE: 1.6573

Mean CV MSE: 23.4056, Mean CV RMSE: 4.5556, Mean CV MAE: 3.2803
Completed trial 79 with mean RMSE: 4.5556 ± 0.8143
Saved Ax client checkpoint

[INFO 04-02 14:26:55] ax.service.ax_client: Generated new trial 80 with parameters {'n_estimators': 5141, 'max_depth': 9, 'learning_rate': 0.010567, 'subsample': 0.724129, 'colsample_bytree': 0.390827, 'min_child_weight': 20, 'reg_alpha': 0.003514, 'reg_lambda': 10.0, 'gamma': 4e-05, 'early_stopping_rounds': 13} using model BoTorch.

Starting trial 80 with parameters: {'n_estimators': 5141, 'max_depth': 9, 'learning_rate': 0.010567038812024617, 'subsample': 0.724129024849895, 'colsample_bytree': 0.3908270577862117, 'min_child_weight': 20, 'reg_alpha': 0.003514314308126823, 'reg_lambda': 10.0, 'gamma': 3.9698889945800916e-05, 'early_stopping_rounds': 13}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 37.0209, RMSE: 6.0845, MAE: 3.8253
Starting fold 2...
Fold 2 - MSE: 38.9774, RMSE: 6.2432, MAE: 3.8256
Starting fold 3...
Fold 3 - MSE: 7.0481, RMSE: 2.6548, MAE: 1.8256
Starting fold 4...
Fold 4 - MSE: 29.5435, RMSE: 5.4354, MAE: 4.4879
Starting fold 5...

[INFO 04-02 14:29:02] ax.service.ax_client: Completed trial 80 with data: {'avg_rmse_nonzero': 4.515624}.

Fold 5 - MSE: 4.6666, RMSE: 2.1602, MAE: 1.8581

Mean CV MSE: 23.4513, Mean CV RMSE: 4.5156, Mean CV MAE: 3.1645
Completed trial 80 with mean RMSE: 4.5156 ± 0.8747
Saved Ax client checkpoint

[INFO 04-02 14:29:12] ax.service.ax_client: Generated new trial 81 with parameters {'n_estimators': 780, 'max_depth': 57, 'learning_rate': 0.1086, 'subsample': 0.857656, 'colsample_bytree': 0.325334, 'min_child_weight': 1, 'reg_alpha': 0.006832, 'reg_lambda': 0.001843, 'gamma': 1.4e-05, 'early_stopping_rounds': 19} using model BoTorch.

Starting trial 81 with parameters: {'n_estimators': 780, 'max_depth': 57, 'learning_rate': 0.10859973586630361, 'subsample': 0.8576561871522075, 'colsample_bytree': 0.3253337231103219, 'min_child_weight': 1, 'reg_alpha': 0.006832197271926197, 'reg_lambda': 0.0018428254675354814, 'gamma': 1.3707877796376277e-05, 'early_stopping_rounds': 19}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 41.9083, RMSE: 6.4737, MAE: 4.3910
Starting fold 2...
Fold 2 - MSE: 37.4359, RMSE: 6.1185, MAE: 3.8088
Starting fold 3...
Fold 3 - MSE: 15.7925, RMSE: 3.9740, MAE: 2.5389
Starting fold 4...
Fold 4 - MSE: 30.2943, RMSE: 5.5040, MAE: 4.4831
Starting fold 5...

[INFO 04-02 14:29:52] ax.service.ax_client: Completed trial 81 with data: {'avg_rmse_nonzero': 4.832107}.

Fold 5 - MSE: 4.3696, RMSE: 2.0904, MAE: 1.5015

Mean CV MSE: 25.9602, Mean CV RMSE: 4.8321, Mean CV MAE: 3.3447
Completed trial 81 with mean RMSE: 4.8321 ± 0.8079
Saved Ax client checkpoint

[INFO 04-02 14:30:07] ax.service.ax_client: Generated new trial 82 with parameters {'n_estimators': 4880, 'max_depth': 3, 'learning_rate': 0.005, 'subsample': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 3, 'reg_alpha': 1.232394, 'reg_lambda': 0.013203, 'gamma': 1e-06, 'early_stopping_rounds': 37} using model BoTorch.

Starting trial 82 with parameters: {'n_estimators': 4880, 'max_depth': 3, 'learning_rate': 0.005, 'subsample': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 3, 'reg_alpha': 1.2323938478982484, 'reg_lambda': 0.013202658944329667, 'gamma': 1e-06, 'early_stopping_rounds': 37}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 37.0918, RMSE: 6.0903, MAE: 4.0061
Starting fold 2...
Fold 2 - MSE: 37.6882, RMSE: 6.1391, MAE: 3.7973
Starting fold 3...
Fold 3 - MSE: 10.3364, RMSE: 3.2150, MAE: 2.4702
Starting fold 4...
Fold 4 - MSE: 31.1888, RMSE: 5.5847, MAE: 4.5320
Starting fold 5...

[INFO 04-02 14:33:05] ax.service.ax_client: Completed trial 82 with data: {'avg_rmse_nonzero': 4.600026}.

Fold 5 - MSE: 3.8850, RMSE: 1.9710, MAE: 1.4646

Mean CV MSE: 24.0380, Mean CV RMSE: 4.6000, Mean CV MAE: 3.2541
Completed trial 82 with mean RMSE: 4.6000 ± 0.8482
Saved Ax client checkpoint

[INFO 04-02 14:33:13] ax.service.ax_client: Generated new trial 83 with parameters {'n_estimators': 9810, 'max_depth': 12, 'learning_rate': 0.006645, 'subsample': 0.824596, 'colsample_bytree': 0.3, 'min_child_weight': 11, 'reg_alpha': 10.0, 'reg_lambda': 1.258644, 'gamma': 1e-06, 'early_stopping_rounds': 46} using model BoTorch.

Starting trial 83 with parameters: {'n_estimators': 9810, 'max_depth': 12, 'learning_rate': 0.006644927448839933, 'subsample': 0.8245955016548915, 'colsample_bytree': 0.3, 'min_child_weight': 11, 'reg_alpha': 10.0, 'reg_lambda': 1.258644357666171, 'gamma': 1e-06, 'early_stopping_rounds': 46}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 39.9451, RMSE: 6.3202, MAE: 4.0617
Starting fold 2...
Fold 2 - MSE: 38.1899, RMSE: 6.1798, MAE: 3.7581
Starting fold 3...
Fold 3 - MSE: 7.1433, RMSE: 2.6727, MAE: 1.8495
Starting fold 4...
Fold 4 - MSE: 31.0341, RMSE: 5.5708, MAE: 4.6875
Starting fold 5...

[INFO 04-02 14:38:17] ax.service.ax_client: Completed trial 83 with data: {'avg_rmse_nonzero': 4.526282}.

Fold 5 - MSE: 3.5641, RMSE: 1.8879, MAE: 1.4278

Mean CV MSE: 23.9753, Mean CV RMSE: 4.5263, Mean CV MAE: 3.1569
Completed trial 83 with mean RMSE: 4.5263 ± 0.9338
Saved Ax client checkpoint

[INFO 04-02 14:38:29] ax.service.ax_client: Generated new trial 84 with parameters {'n_estimators': 2854, 'max_depth': 48, 'learning_rate': 0.014001, 'subsample': 0.808064, 'colsample_bytree': 0.3, 'min_child_weight': 20, 'reg_alpha': 7.41597, 'reg_lambda': 0.02067, 'gamma': 7e-06, 'early_stopping_rounds': 49} using model BoTorch.

Starting trial 84 with parameters: {'n_estimators': 2854, 'max_depth': 48, 'learning_rate': 0.014000964662003006, 'subsample': 0.8080641653027962, 'colsample_bytree': 0.3, 'min_child_weight': 20, 'reg_alpha': 7.415969776801425, 'reg_lambda': 0.02066961080659974, 'gamma': 6.931298326148314e-06, 'early_stopping_rounds': 49}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 37.9631, RMSE: 6.1614, MAE: 3.8672
Starting fold 2...
Fold 2 - MSE: 40.8274, RMSE: 6.3896, MAE: 3.9061
Starting fold 3...
Fold 3 - MSE: 7.3183, RMSE: 2.7052, MAE: 1.8154
Starting fold 4...
Fold 4 - MSE: 30.9718, RMSE: 5.5652, MAE: 4.6333
Starting fold 5...

[INFO 04-02 14:41:30] ax.service.ax_client: Completed trial 84 with data: {'avg_rmse_nonzero': 4.545066}.

Fold 5 - MSE: 3.6245, RMSE: 1.9038, MAE: 1.4484

Mean CV MSE: 24.1410, Mean CV RMSE: 4.5451, Mean CV MAE: 3.1341
Completed trial 84 with mean RMSE: 4.5451 ± 0.9332
Saved Ax client checkpoint

[INFO 04-02 14:41:44] ax.service.ax_client: Generated new trial 85 with parameters {'n_estimators': 9977, 'max_depth': 16, 'learning_rate': 0.015632, 'subsample': 0.511697, 'colsample_bytree': 0.3, 'min_child_weight': 20, 'reg_alpha': 2.3e-05, 'reg_lambda': 0.004199, 'gamma': 5.0, 'early_stopping_rounds': 10} using model BoTorch.

Starting trial 85 with parameters: {'n_estimators': 9977, 'max_depth': 16, 'learning_rate': 0.015631890680163428, 'subsample': 0.5116966020773396, 'colsample_bytree': 0.3, 'min_child_weight': 20, 'reg_alpha': 2.32790009104675e-05, 'reg_lambda': 0.004199372127688964, 'gamma': 5.0, 'early_stopping_rounds': 10}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 36.8175, RMSE: 6.0677, MAE: 3.8013
Starting fold 2...
Fold 2 - MSE: 33.4785, RMSE: 5.7861, MAE: 3.5160
Starting fold 3...
Fold 3 - MSE: 6.7262, RMSE: 2.5935, MAE: 1.6907
Starting fold 4...
Fold 4 - MSE: 28.1125, RMSE: 5.3021, MAE: 4.4210
Starting fold 5...

[INFO 04-02 14:42:42] ax.service.ax_client: Completed trial 85 with data: {'avg_rmse_nonzero': 4.397151}.

Fold 5 - MSE: 5.0012, RMSE: 2.2363, MAE: 1.8766

Mean CV MSE: 22.0272, Mean CV RMSE: 4.3972, Mean CV MAE: 3.0611
Completed trial 85 with mean RMSE: 4.3972 ± 0.8204
Saved Ax client checkpoint

[INFO 04-02 14:42:58] ax.service.ax_client: Generated new trial 86 with parameters {'n_estimators': 2126, 'max_depth': 18, 'learning_rate': 0.005, 'subsample': 0.5, 'colsample_bytree': 0.73685, 'min_child_weight': 1, 'reg_alpha': 1e-06, 'reg_lambda': 10.0, 'gamma': 0.337798, 'early_stopping_rounds': 16} using model BoTorch.

Starting trial 86 with parameters: {'n_estimators': 2126, 'max_depth': 18, 'learning_rate': 0.005, 'subsample': 0.5, 'colsample_bytree': 0.7368498634671808, 'min_child_weight': 1, 'reg_alpha': 1e-06, 'reg_lambda': 10.0, 'gamma': 0.3377984235685112, 'early_stopping_rounds': 16}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 38.2510, RMSE: 6.1847, MAE: 4.0281
Starting fold 2...
Fold 2 - MSE: 34.7715, RMSE: 5.8967, MAE: 3.6916
Starting fold 3...
Fold 3 - MSE: 7.1129, RMSE: 2.6670, MAE: 2.0762
Starting fold 4...
Fold 4 - MSE: 27.1031, RMSE: 5.2061, MAE: 4.3068
Starting fold 5...

[INFO 04-02 14:49:48] ax.service.ax_client: Completed trial 86 with data: {'avg_rmse_nonzero': 4.402537}.

Fold 5 - MSE: 4.2360, RMSE: 2.0581, MAE: 1.7473

Mean CV MSE: 22.2949, Mean CV RMSE: 4.4025, Mean CV MAE: 3.1700
Completed trial 86 with mean RMSE: 4.4025 ± 0.8533
Saved Ax client checkpoint

[INFO 04-02 14:50:02] ax.service.ax_client: Generated new trial 87 with parameters {'n_estimators': 786, 'max_depth': 87, 'learning_rate': 0.009936, 'subsample': 0.807116, 'colsample_bytree': 1.0, 'min_child_weight': 1, 'reg_alpha': 1e-06, 'reg_lambda': 10.0, 'gamma': 2e-05, 'early_stopping_rounds': 20} using model BoTorch.

Starting trial 87 with parameters: {'n_estimators': 786, 'max_depth': 87, 'learning_rate': 0.009935806084399463, 'subsample': 0.8071159563873567, 'colsample_bytree': 1.0, 'min_child_weight': 1, 'reg_alpha': 1e-06, 'reg_lambda': 10.0, 'gamma': 2.0317291370042564e-05, 'early_stopping_rounds': 20}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 37.6309, RMSE: 6.1344, MAE: 4.0389
Starting fold 2...
Fold 2 - MSE: 34.4391, RMSE: 5.8685, MAE: 3.7642
Starting fold 3...
Fold 3 - MSE: 10.1331, RMSE: 3.1832, MAE: 2.4777
Starting fold 4...
Fold 4 - MSE: 27.9358, RMSE: 5.2854, MAE: 4.4098
Starting fold 5...

[INFO 04-02 14:57:21] ax.service.ax_client: Completed trial 87 with data: {'avg_rmse_nonzero': 4.508058}.

Fold 5 - MSE: 4.2796, RMSE: 2.0687, MAE: 1.8092

Mean CV MSE: 22.8837, Mean CV RMSE: 4.5081, Mean CV MAE: 3.2999
Completed trial 87 with mean RMSE: 4.5081 ± 0.8002
Saved Ax client checkpoint

[INFO 04-02 14:57:37] ax.service.ax_client: Generated new trial 88 with parameters {'n_estimators': 2669, 'max_depth': 87, 'learning_rate': 0.3, 'subsample': 0.82563, 'colsample_bytree': 0.939543, 'min_child_weight': 20, 'reg_alpha': 1e-06, 'reg_lambda': 0.002559, 'gamma': 1e-06, 'early_stopping_rounds': 50} using model BoTorch.

Starting trial 88 with parameters: {'n_estimators': 2669, 'max_depth': 87, 'learning_rate': 0.29999999999999993, 'subsample': 0.8256299449190924, 'colsample_bytree': 0.9395427166004341, 'min_child_weight': 20, 'reg_alpha': 1e-06, 'reg_lambda': 0.002559422399107075, 'gamma': 1e-06, 'early_stopping_rounds': 50}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 40.9952, RMSE: 6.4028, MAE: 4.1383
Starting fold 2...
Fold 2 - MSE: 44.4814, RMSE: 6.6694, MAE: 4.4361
Starting fold 3...
Fold 3 - MSE: 7.8077, RMSE: 2.7942, MAE: 1.9077
Starting fold 4...
Fold 4 - MSE: 40.6916, RMSE: 6.3790, MAE: 5.1330
Starting fold 5...

[INFO 04-02 14:58:06] ax.service.ax_client: Completed trial 88 with data: {'avg_rmse_nonzero': 4.897255}.

Fold 5 - MSE: 5.0215, RMSE: 2.2409, MAE: 1.5268

Mean CV MSE: 27.7995, Mean CV RMSE: 4.8973, Mean CV MAE: 3.4284
Completed trial 88 with mean RMSE: 4.8973 ± 0.9768
Saved Ax client checkpoint

[INFO 04-02 14:58:17] ax.service.ax_client: Generated new trial 89 with parameters {'n_estimators': 595, 'max_depth': 43, 'learning_rate': 0.005, 'subsample': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 20, 'reg_alpha': 1e-06, 'reg_lambda': 3e-06, 'gamma': 0.037371, 'early_stopping_rounds': 12} using model BoTorch.

Starting trial 89 with parameters: {'n_estimators': 595, 'max_depth': 43, 'learning_rate': 0.005, 'subsample': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 20, 'reg_alpha': 1e-06, 'reg_lambda': 2.500334642714333e-06, 'gamma': 0.03737106408853911, 'early_stopping_rounds': 12}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 36.9219, RMSE: 6.0763, MAE: 3.8462
Starting fold 2...
Fold 2 - MSE: 33.9352, RMSE: 5.8254, MAE: 3.6196
Starting fold 3...
Fold 3 - MSE: 6.8431, RMSE: 2.6159, MAE: 1.7924
Starting fold 4...
Fold 4 - MSE: 28.4604, RMSE: 5.3348, MAE: 4.4704
Starting fold 5...

[INFO 04-02 14:59:38] ax.service.ax_client: Completed trial 89 with data: {'avg_rmse_nonzero': 4.431997}.

Fold 5 - MSE: 5.3245, RMSE: 2.3075, MAE: 2.0354

Mean CV MSE: 22.2970, Mean CV RMSE: 4.4320, Mean CV MAE: 3.1528
Completed trial 89 with mean RMSE: 4.4320 ± 0.8146
Saved Ax client checkpoint

[INFO 04-02 14:59:53] ax.service.ax_client: Generated new trial 90 with parameters {'n_estimators': 8767, 'max_depth': 94, 'learning_rate': 0.010399, 'subsample': 0.526225, 'colsample_bytree': 0.418818, 'min_child_weight': 2, 'reg_alpha': 3.654128, 'reg_lambda': 3e-06, 'gamma': 0.097836, 'early_stopping_rounds': 36} using model BoTorch.

Starting trial 90 with parameters: {'n_estimators': 8767, 'max_depth': 94, 'learning_rate': 0.01039887344182138, 'subsample': 0.5262249247408881, 'colsample_bytree': 0.41881783908300096, 'min_child_weight': 2, 'reg_alpha': 3.654128234922622, 'reg_lambda': 2.9852336073710706e-06, 'gamma': 0.09783622767882927, 'early_stopping_rounds': 36}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 36.1204, RMSE: 6.0100, MAE: 3.8935
Starting fold 2...
Fold 2 - MSE: 33.9852, RMSE: 5.8297, MAE: 3.7429
Starting fold 3...
Fold 3 - MSE: 11.9767, RMSE: 3.4607, MAE: 2.8614
Starting fold 4...
Fold 4 - MSE: 26.4344, RMSE: 5.1414, MAE: 4.3265
Starting fold 5...

[INFO 04-02 15:02:24] ax.service.ax_client: Completed trial 90 with data: {'avg_rmse_nonzero': 4.489484}.

Fold 5 - MSE: 4.0222, RMSE: 2.0055, MAE: 1.5955

Mean CV MSE: 22.5078, Mean CV RMSE: 4.4895, Mean CV MAE: 3.2840
Completed trial 90 with mean RMSE: 4.4895 ± 0.7669
Saved Ax client checkpoint

[INFO 04-02 15:02:35] ax.service.ax_client: Generated new trial 91 with parameters {'n_estimators': 9738, 'max_depth': 71, 'learning_rate': 0.3, 'subsample': 0.5, 'colsample_bytree': 0.324268, 'min_child_weight': 4, 'reg_alpha': 0.038042, 'reg_lambda': 10.0, 'gamma': 2e-06, 'early_stopping_rounds': 10} using model BoTorch.

Starting trial 91 with parameters: {'n_estimators': 9738, 'max_depth': 71, 'learning_rate': 0.29999999999999993, 'subsample': 0.5, 'colsample_bytree': 0.3242677473733417, 'min_child_weight': 4, 'reg_alpha': 0.03804241862090724, 'reg_lambda': 10.0, 'gamma': 2.363880830140814e-06, 'early_stopping_rounds': 10}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 41.3078, RMSE: 6.4271, MAE: 4.3610
Starting fold 2...
Fold 2 - MSE: 34.8733, RMSE: 5.9054, MAE: 3.5143
Starting fold 3...
Fold 3 - MSE: 7.7691, RMSE: 2.7873, MAE: 2.2193
Starting fold 4...
Fold 4 - MSE: 31.4065, RMSE: 5.6042, MAE: 4.6765
Starting fold 5...

[INFO 04-02 15:02:52] ax.service.ax_client: Completed trial 91 with data: {'avg_rmse_nonzero': 4.623101}.

Fold 5 - MSE: 5.7195, RMSE: 2.3916, MAE: 2.0472

Mean CV MSE: 24.2153, Mean CV RMSE: 4.6231, Mean CV MAE: 3.3636
Completed trial 91 with mean RMSE: 4.6231 ± 0.8429
Saved Ax client checkpoint

[INFO 04-02 15:03:04] ax.service.ax_client: Generated new trial 92 with parameters {'n_estimators': 9166, 'max_depth': 100, 'learning_rate': 0.005, 'subsample': 0.85021, 'colsample_bytree': 0.562841, 'min_child_weight': 10, 'reg_alpha': 7.279101, 'reg_lambda': 0.000795, 'gamma': 1e-06, 'early_stopping_rounds': 45} using model BoTorch.

Starting trial 92 with parameters: {'n_estimators': 9166, 'max_depth': 100, 'learning_rate': 0.005, 'subsample': 0.8502095760425502, 'colsample_bytree': 0.5628408775301279, 'min_child_weight': 10, 'reg_alpha': 7.2791006313649715, 'reg_lambda': 0.000794502747897849, 'gamma': 1e-06, 'early_stopping_rounds': 45}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 41.4862, RMSE: 6.4410, MAE: 4.1692
Starting fold 2...
Fold 2 - MSE: 37.6728, RMSE: 6.1378, MAE: 3.7417
Starting fold 3...
Fold 3 - MSE: 7.1399, RMSE: 2.6721, MAE: 1.8877
Starting fold 4...
Fold 4 - MSE: 31.7851, RMSE: 5.6378, MAE: 4.7351
Starting fold 5...

[INFO 04-02 15:09:08] ax.service.ax_client: Completed trial 92 with data: {'avg_rmse_nonzero': 4.586429}.

Fold 5 - MSE: 4.1758, RMSE: 2.0435, MAE: 1.6436

Mean CV MSE: 24.4519, Mean CV RMSE: 4.5864, Mean CV MAE: 3.2354
Completed trial 92 with mean RMSE: 4.5864 ± 0.9242
Saved Ax client checkpoint

[INFO 04-02 15:09:22] ax.service.ax_client: Generated new trial 93 with parameters {'n_estimators': 8687, 'max_depth': 77, 'learning_rate': 0.005, 'subsample': 0.608367, 'colsample_bytree': 0.588402, 'min_child_weight': 1, 'reg_alpha': 3.708213, 'reg_lambda': 0.004134, 'gamma': 0.002826, 'early_stopping_rounds': 15} using model BoTorch.

Starting trial 93 with parameters: {'n_estimators': 8687, 'max_depth': 77, 'learning_rate': 0.005, 'subsample': 0.6083668743869969, 'colsample_bytree': 0.588402223484239, 'min_child_weight': 1, 'reg_alpha': 3.708212587232052, 'reg_lambda': 0.00413363145111055, 'gamma': 0.0028264600029702155, 'early_stopping_rounds': 15}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 37.4720, RMSE: 6.1214, MAE: 3.9954
Starting fold 2...
Fold 2 - MSE: 33.8882, RMSE: 5.8214, MAE: 3.7242
Starting fold 3...
Fold 3 - MSE: 11.8621, RMSE: 3.4441, MAE: 2.8529
Starting fold 4...
Fold 4 - MSE: 27.4540, RMSE: 5.2397, MAE: 4.3920
Starting fold 5...

[INFO 04-02 15:14:26] ax.service.ax_client: Completed trial 93 with data: {'avg_rmse_nonzero': 4.511409}.

Fold 5 - MSE: 3.7267, RMSE: 1.9305, MAE: 1.5866

Mean CV MSE: 22.8806, Mean CV RMSE: 4.5114, Mean CV MAE: 3.3102
Completed trial 93 with mean RMSE: 4.5114 ± 0.7949
Saved Ax client checkpoint

[INFO 04-02 15:14:40] ax.service.ax_client: Generated new trial 94 with parameters {'n_estimators': 2129, 'max_depth': 41, 'learning_rate': 0.005, 'subsample': 0.887547, 'colsample_bytree': 1.0, 'min_child_weight': 19, 'reg_alpha': 0.00408, 'reg_lambda': 1e-06, 'gamma': 0.225267, 'early_stopping_rounds': 17} using model BoTorch.

Starting trial 94 with parameters: {'n_estimators': 2129, 'max_depth': 41, 'learning_rate': 0.005, 'subsample': 0.8875468943200719, 'colsample_bytree': 1.0, 'min_child_weight': 19, 'reg_alpha': 0.004080106904671908, 'reg_lambda': 1e-06, 'gamma': 0.22526682357226516, 'early_stopping_rounds': 17}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 38.2949, RMSE: 6.1883, MAE: 3.9710
Starting fold 2...
Fold 2 - MSE: 37.4616, RMSE: 6.1206, MAE: 3.8311
Starting fold 3...
Fold 3 - MSE: 8.2822, RMSE: 2.8779, MAE: 1.9427
Starting fold 4...
Fold 4 - MSE: 32.0907, RMSE: 5.6649, MAE: 4.7221
Starting fold 5...

[INFO 04-02 15:19:43] ax.service.ax_client: Completed trial 94 with data: {'avg_rmse_nonzero': 4.600486}.

Fold 5 - MSE: 4.6260, RMSE: 2.1508, MAE: 1.7175

Mean CV MSE: 24.1511, Mean CV RMSE: 4.6005, Mean CV MAE: 3.2369
Completed trial 94 with mean RMSE: 4.6005 ± 0.8641
Saved Ax client checkpoint

[INFO 04-02 15:19:55] ax.service.ax_client: Generated new trial 95 with parameters {'n_estimators': 6207, 'max_depth': 6, 'learning_rate': 0.257746, 'subsample': 0.5, 'colsample_bytree': 0.898191, 'min_child_weight': 20, 'reg_alpha': 0.000316, 'reg_lambda': 1e-06, 'gamma': 1e-06, 'early_stopping_rounds': 11} using model BoTorch.

Starting trial 95 with parameters: {'n_estimators': 6207, 'max_depth': 6, 'learning_rate': 0.2577456338574599, 'subsample': 0.5, 'colsample_bytree': 0.8981908596773508, 'min_child_weight': 20, 'reg_alpha': 0.0003159940125698916, 'reg_lambda': 1e-06, 'gamma': 1e-06, 'early_stopping_rounds': 11}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 37.7995, RMSE: 6.1481, MAE: 3.9600
Starting fold 2...
Fold 2 - MSE: 29.3159, RMSE: 5.4144, MAE: 3.3789
Starting fold 3...
Fold 3 - MSE: 11.1968, RMSE: 3.3462, MAE: 2.2232
Starting fold 4...
Fold 4 - MSE: 38.4562, RMSE: 6.2013, MAE: 5.2477
Starting fold 5...

[INFO 04-02 15:20:07] ax.service.ax_client: Completed trial 95 with data: {'avg_rmse_nonzero': 4.822412}.

Fold 5 - MSE: 9.0122, RMSE: 3.0020, MAE: 2.5960

Mean CV MSE: 25.1561, Mean CV RMSE: 4.8224, Mean CV MAE: 3.4812
Completed trial 95 with mean RMSE: 4.8224 ± 0.6893
Saved Ax client checkpoint

[INFO 04-02 15:20:21] ax.service.ax_client: Generated new trial 96 with parameters {'n_estimators': 4101, 'max_depth': 100, 'learning_rate': 0.005, 'subsample': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 20, 'reg_alpha': 5.887372, 'reg_lambda': 1e-06, 'gamma': 0.142102, 'early_stopping_rounds': 15} using model BoTorch.

Starting trial 96 with parameters: {'n_estimators': 4101, 'max_depth': 100, 'learning_rate': 0.005, 'subsample': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 20, 'reg_alpha': 5.887372426533622, 'reg_lambda': 1.3702333152680991e-06, 'gamma': 0.14210234237074756, 'early_stopping_rounds': 15}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 36.9628, RMSE: 6.0797, MAE: 3.7785
Starting fold 2...
Fold 2 - MSE: 36.3639, RMSE: 6.0302, MAE: 3.6443
Starting fold 3...
Fold 3 - MSE: 6.7784, RMSE: 2.6035, MAE: 1.7768
Starting fold 4...
Fold 4 - MSE: 28.8555, RMSE: 5.3717, MAE: 4.4920
Starting fold 5...

[INFO 04-02 15:24:07] ax.service.ax_client: Completed trial 96 with data: {'avg_rmse_nonzero': 4.444831}.

Fold 5 - MSE: 4.5750, RMSE: 2.1389, MAE: 1.7452

Mean CV MSE: 22.7071, Mean CV RMSE: 4.4448, Mean CV MAE: 3.0874
Completed trial 96 with mean RMSE: 4.4448 ± 0.8589
Saved Ax client checkpoint

[INFO 04-02 15:24:20] ax.service.ax_client: Generated new trial 97 with parameters {'n_estimators': 9671, 'max_depth': 42, 'learning_rate': 0.005, 'subsample': 0.580609, 'colsample_bytree': 0.898824, 'min_child_weight': 1, 'reg_alpha': 0.00023, 'reg_lambda': 10.0, 'gamma': 1e-06, 'early_stopping_rounds': 27} using model BoTorch.

Starting trial 97 with parameters: {'n_estimators': 9671, 'max_depth': 42, 'learning_rate': 0.005, 'subsample': 0.5806089994305945, 'colsample_bytree': 0.8988238087308104, 'min_child_weight': 1, 'reg_alpha': 0.00022984036260280437, 'reg_lambda': 10.0, 'gamma': 1e-06, 'early_stopping_rounds': 27}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 37.4681, RMSE: 6.1211, MAE: 4.0157
Starting fold 2...
Fold 2 - MSE: 34.2931, RMSE: 5.8560, MAE: 3.7253
Starting fold 3...
Fold 3 - MSE: 7.5483, RMSE: 2.7474, MAE: 2.1574
Starting fold 4...
Fold 4 - MSE: 27.4138, RMSE: 5.2358, MAE: 4.3155
Starting fold 5...

[INFO 04-02 15:45:35] ax.service.ax_client: Completed trial 97 with data: {'avg_rmse_nonzero': 4.410329}.

Fold 5 - MSE: 4.3733, RMSE: 2.0913, MAE: 1.7842

Mean CV MSE: 22.2193, Mean CV RMSE: 4.4103, Mean CV MAE: 3.1996
Completed trial 97 with mean RMSE: 4.4103 ± 0.8319
Saved Ax client checkpoint

[INFO 04-02 15:45:49] ax.service.ax_client: Generated new trial 98 with parameters {'n_estimators': 1444, 'max_depth': 60, 'learning_rate': 0.009547, 'subsample': 0.955612, 'colsample_bytree': 0.3, 'min_child_weight': 5, 'reg_alpha': 0.003167, 'reg_lambda': 1e-06, 'gamma': 5.0, 'early_stopping_rounds': 10} using model BoTorch.

Starting trial 98 with parameters: {'n_estimators': 1444, 'max_depth': 60, 'learning_rate': 0.009546624557508935, 'subsample': 0.9556117960382895, 'colsample_bytree': 0.3, 'min_child_weight': 5, 'reg_alpha': 0.003166810463352586, 'reg_lambda': 1.320720953369423e-06, 'gamma': 5.0, 'early_stopping_rounds': 10}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 37.9415, RMSE: 6.1597, MAE: 4.0537
Starting fold 2...
Fold 2 - MSE: 35.9470, RMSE: 5.9956, MAE: 3.6568
Starting fold 3...
Fold 3 - MSE: 8.2182, RMSE: 2.8667, MAE: 2.0530
Starting fold 4...
Fold 4 - MSE: 29.2937, RMSE: 5.4124, MAE: 4.5367
Starting fold 5...

[INFO 04-02 15:46:56] ax.service.ax_client: Completed trial 98 with data: {'avg_rmse_nonzero': 4.448088}.

Fold 5 - MSE: 3.2620, RMSE: 1.8061, MAE: 1.3854

Mean CV MSE: 22.9325, Mean CV RMSE: 4.4481, Mean CV MAE: 3.1371
Completed trial 98 with mean RMSE: 4.4481 ± 0.8870
Saved Ax client checkpoint

[INFO 04-02 15:47:07] ax.service.ax_client: Generated new trial 99 with parameters {'n_estimators': 7573, 'max_depth': 3, 'learning_rate': 0.005, 'subsample': 0.5, 'colsample_bytree': 0.978954, 'min_child_weight': 12, 'reg_alpha': 5.8e-05, 'reg_lambda': 1e-06, 'gamma': 0.000862, 'early_stopping_rounds': 50} using model BoTorch.

Starting trial 99 with parameters: {'n_estimators': 7573, 'max_depth': 3, 'learning_rate': 0.005, 'subsample': 0.5, 'colsample_bytree': 0.9789541194089539, 'min_child_weight': 12, 'reg_alpha': 5.801642038892301e-05, 'reg_lambda': 1e-06, 'gamma': 0.0008623561773663504, 'early_stopping_rounds': 50}
Using device: cuda
Starting fold 1...
Fold 1 - MSE: 36.8340, RMSE: 6.0691, MAE: 3.8568
Starting fold 2...
Fold 2 - MSE: 39.3644, RMSE: 6.2741, MAE: 3.9132
Starting fold 3...
Fold 3 - MSE: 8.0673, RMSE: 2.8403, MAE: 1.9161
Starting fold 4...
Fold 4 - MSE: 30.1692, RMSE: 5.4926, MAE: 4.5883
Starting fold 5...

[INFO 04-02 15:52:02] ax.service.ax_client: Completed trial 99 with data: {'avg_rmse_nonzero': 4.538462}.

Fold 5 - MSE: 4.0648, RMSE: 2.0161, MAE: 1.5896

Mean CV MSE: 23.7000, Mean CV RMSE: 4.5385, Mean CV MAE: 3.1728
Completed trial 99 with mean RMSE: 4.5385 ± 0.8807
Saved Ax client checkpoint

In [60]:
# Get best parameters after all trials
best_parameters, values = ax_client_xgb_dmax.get_best_parameters()
print(f"\n{'='*60}")
print("OPTIMIZATION COMPLETE")
print('='*60)
print(f"Best parameters: {best_parameters}")
print(f"Best Non-zero RMSE: {values[0]['avg_rmse_nonzero']:.4f}")

============================================================
OPTIMIZATION COMPLETE
============================================================
Best parameters: {'n_estimators': 9977, 'max_depth': 16, 'learning_rate': 0.015631890680163428, 'subsample': 0.5116966020773396, 'colsample_bytree': 0.3, 'min_child_weight': 20, 'reg_alpha': 2.32790009104675e-05, 'reg_lambda': 0.004199372127688964, 'gamma': 5.0, 'early_stopping_rounds': 10}
Best Non-zero RMSE: 4.3972