In [1]:
import pandas as pd
import numpy as np
import torch
import matplotlib.pyplot as plt
from CBFV import composition
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import re
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset
from xgboost import XGBRegressor
from sklearn.multioutput import MultiOutputRegressor
from ax.service.ax_client import AxClient, ObjectiveProperties

c:\Users\Chris\Documents\ML_Project\ML_GFA_env\Lib\site-packages\CBFV\composition.py:7: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources

In [2]:
class FlexibleNN(nn.Module):
    """
    A flexible neural network with configurable architecture for hyperparameter optimization.
    
    Parameters:
    -----------
    input_dim : int
        Number of input features (CBFV features)
    output_dim : int
        Number of output targets (phase fractions at selected temperatures)
    hidden_layers : list of int
        List of hidden layer sizes, e.g., [256, 128, 64]
    dropout_rate : float
        Dropout probability (0.0 to 1.0)
    dropout_type : str
        Type of dropout: 'standard', 'alpha' (for SELU), or 'none'
    activation : str
        Activation function: 'relu', 'leaky_relu', 'elu', 'selu', 'gelu', 'tanh'
    use_batch_norm : bool
        Whether to use batch normalization
    use_layer_norm : bool
        Whether to use layer normalization (alternative to batch norm)
    weight_decay : float
        L2 regularization strength (applied in optimizer, stored here for reference)
    nf_indices : list of int or None
        Indices of output columns that are phase fractions (NF). 
        These will have softmax applied so they sum to 1.
        If None, no softmax constraint is applied.
    output_columns : list of str or None
        Column names for outputs. If provided, NF columns are auto-detected
        by checking for 'NF_' prefix. Overrides nf_indices if both provided.
    """
    
    def __init__(
        self,
        input_dim,
        output_dim,
        hidden_layers=[256, 128, 64],
        dropout_rate=0.2,
        dropout_type='standard',
        activation='relu',
        use_batch_norm=False,
        use_layer_norm=False,
        weight_decay=0.0,
        nf_indices=None,
        output_columns=None
    ):
        super(FlexibleNN, self).__init__()
        
        self.weight_decay = weight_decay  # Store for optimizer configuration
        self.output_dim = output_dim
        
        # Determine NF indices (phase fractions that should sum to 1)
        if output_columns is not None:
            # Auto-detect NF columns from column names
            self.nf_indices = [i for i, col in enumerate(output_columns) if col.startswith('NF_')]
            self.df_indices = [i for i, col in enumerate(output_columns) if col.startswith('DF_')]
        elif nf_indices is not None:
            self.nf_indices = nf_indices
            self.df_indices = [i for i in range(output_dim) if i not in nf_indices]
        else:
            self.nf_indices = []
            self.df_indices = list(range(output_dim))
        
        # Build activation function
        activation_fn = self._get_activation(activation)
        
        # Build dropout layer
        dropout_layer = self._get_dropout(dropout_type, dropout_rate)
        
        # Build the network layers
        layers = []
        prev_dim = input_dim
        
        for hidden_dim in hidden_layers:
            # Linear layer
            layers.append(nn.Linear(prev_dim, hidden_dim))
            
            # Normalization (batch norm or layer norm, not both)
            if use_batch_norm:
                layers.append(nn.BatchNorm1d(hidden_dim))
            elif use_layer_norm:
                layers.append(nn.LayerNorm(hidden_dim))
            
            # Activation
            layers.append(activation_fn())
            
            # Dropout
            if dropout_layer is not None:
                layers.append(dropout_layer(dropout_rate))
            
            prev_dim = hidden_dim
        
        # Output layer (no activation, dropout, or normalization)
        layers.append(nn.Linear(prev_dim, output_dim))
        
        self.network = nn.Sequential(*layers)
    
    def _get_activation(self, activation):
        activations = {
            'relu': nn.ReLU,
            'leaky_relu': lambda: nn.LeakyReLU(0.1),
            'elu': nn.ELU,
            'selu': nn.SELU,
            'gelu': nn.GELU,
            'tanh': nn.Tanh,
            'sigmoid': nn.Sigmoid
        }
        if activation not in activations:
            raise ValueError(f"Unknown activation: {activation}. Choose from {list(activations.keys())}")
        return activations[activation]
    
    def _get_dropout(self, dropout_type, dropout_rate):
        if dropout_type == 'none' or dropout_rate == 0:
            return None
        elif dropout_type == 'standard':
            return nn.Dropout
        elif dropout_type == 'alpha':
            return nn.AlphaDropout  # For use with SELU activation
        else:
            raise ValueError(f"Unknown dropout type: {dropout_type}. Choose from ['standard', 'alpha', 'none']")
    
    def forward(self, x):
        raw_output = self.network(x)
        
        # If no NF indices, return raw output
        if len(self.nf_indices) == 0:
            return raw_output
        
        # Apply softmax to NF (phase fraction) outputs so they sum to 1
        output = raw_output.clone()
        
        # Extract NF outputs and apply softmax
        nf_outputs = raw_output[:, self.nf_indices]
        nf_normalized = torch.softmax(nf_outputs, dim=1)
        
        # Put normalized NF values back
        output[:, self.nf_indices] = nf_normalized
        
        return output
    
    def get_optimizer(self, optimizer_type='adam', lr=1e-3):
        """
        Get an optimizer with the configured weight decay (L2 regularization).
        """
        optimizers = {
            'adam': lambda: torch.optim.Adam(self.parameters(), lr=lr, weight_decay=self.weight_decay),
            'adamw': lambda: torch.optim.AdamW(self.parameters(), lr=lr, weight_decay=self.weight_decay),
            'sgd': lambda: torch.optim.SGD(self.parameters(), lr=lr, weight_decay=self.weight_decay, momentum=0.9),
            'rmsprop': lambda: torch.optim.RMSprop(self.parameters(), lr=lr, weight_decay=self.weight_decay)
        }
        if optimizer_type not in optimizers:
            raise ValueError(f"Unknown optimizer: {optimizer_type}. Choose from {list(optimizers.keys())}")
        return optimizers[optimizer_type]()


def train_epoch(model, train_loader, optimizer, criterion, device):
    """
    Train the model for one epoch.
    
    Returns:
    --------
    float : Average training loss for the epoch
    """
    model.train()
    total_loss = 0.0
    num_batches = 0
    
    for X_batch, y_batch in train_loader:
        X_batch, y_batch = X_batch.to(device), y_batch.to(device)
        
        optimizer.zero_grad()
        predictions = model(X_batch)
        loss = criterion(predictions, y_batch)
        loss.backward()
        optimizer.step()
        
        total_loss += loss.item()
        num_batches += 1
    
    return total_loss / num_batches


def evaluate_epoch(model, val_loader, criterion, device):
    """
    Evaluate the model on validation data.
    
    Returns:
    --------
    tuple : (average loss, predictions, targets)
    """
    model.eval()
    total_loss = 0.0
    total_samples = 0
    all_predictions = []
    all_targets = []
    
    with torch.no_grad():
        for X_batch, y_batch in val_loader:
            X_batch, y_batch = X_batch.to(device), y_batch.to(device)
            batch_size = X_batch.size(0)
            
            predictions = model(X_batch)
            loss = criterion(predictions, y_batch)
            
            # Weight loss by batch size for correct averaging
            total_loss += loss.item() * batch_size
            total_samples += batch_size
            
            all_predictions.append(predictions.cpu())
            all_targets.append(y_batch.cpu())
    
    # Weighted average loss (accounts for different batch sizes)
    avg_loss = total_loss / total_samples
    all_predictions = torch.cat(all_predictions, dim=0)
    all_targets = torch.cat(all_targets, dim=0)
    
    return avg_loss, all_predictions, all_targets


def train_model(
    model,
    X_train, y_train,
    X_val, y_val,
    epochs=100,
    batch_size=32,
    optimizer_type='adam',
    lr=1e-3,
    criterion=None,
    early_stopping_patience=None,
    verbose=True,
    device=None
):
    """
    Train the model for a specified number of epochs.
    
    Parameters:
    -----------
    model : FlexibleNN
        The neural network model
    X_train, y_train : array-like
        Training data
    X_val, y_val : array-like
        Validation data
    epochs : int
        Number of training epochs
    batch_size : int
        Batch size for training
    optimizer_type : str
        Type of optimizer ('adam', 'adamw', 'sgd', 'rmsprop')
    lr : float
        Learning rate
    criterion : nn.Module
        Loss function (default: MSELoss)
    early_stopping_patience : int or None
        Stop training if val loss doesn't improve for this many epochs
    verbose : bool
        Whether to print progress
    device : str or None
        Device to train on ('cuda', 'mps', 'cpu', or None for auto-detect)
    
    Returns:
    --------
    dict : Training history with train_losses, val_losses, best_epoch
    """
    # Auto-detect device
    if device is None:
        if torch.cuda.is_available():
            device = 'cuda'
        elif torch.backends.mps.is_available():
            device = 'mps'
        else:
            device = 'cpu'
    
    device = torch.device(device)
    model = model.to(device)
    
    # Default criterion
    if criterion is None:
        criterion = nn.MSELoss()
    
    # Convert data to tensors
    X_train_t = torch.FloatTensor(X_train.values if hasattr(X_train, 'values') else X_train)
    y_train_t = torch.FloatTensor(y_train.values if hasattr(y_train, 'values') else y_train)
    X_val_t = torch.FloatTensor(X_val.values if hasattr(X_val, 'values') else X_val)
    y_val_t = torch.FloatTensor(y_val.values if hasattr(y_val, 'values') else y_val)
    
    # Create data loaders
    train_dataset = TensorDataset(X_train_t, y_train_t)
    val_dataset = TensorDataset(X_val_t, y_val_t)
    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
    val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)
    
    # Get optimizer
    optimizer = model.get_optimizer(optimizer_type=optimizer_type, lr=lr)
    
    # Training history
    history = {
        'train_losses': [],
        'val_losses': [],
        'best_epoch': 0,
        'best_val_loss': float('inf')
    }
    
    # Early stopping
    patience_counter = 0
    best_model_state = None
    
    for epoch in range(epochs):
        # Train
        train_loss = train_epoch(model, train_loader, optimizer, criterion, device)
        
        # Evaluate
        val_loss, _, _ = evaluate_epoch(model, val_loader, criterion, device)
        
        history['train_losses'].append(train_loss)
        history['val_losses'].append(val_loss)
        
        # Track best model
        if val_loss < history['best_val_loss']:
            history['best_val_loss'] = val_loss
            history['best_epoch'] = epoch
            best_model_state = model.state_dict().copy()
            patience_counter = 0
        else:
            patience_counter += 1
        
        # Verbose output
        if verbose and (epoch % 10 == 0 or epoch == epochs - 1):
            print(f"Epoch {epoch+1}/{epochs} - Train Loss: {train_loss:.6f} - Val Loss: {val_loss:.6f}")
        
        # Early stopping
        if early_stopping_patience and patience_counter >= early_stopping_patience:
            if verbose:
                print(f"Early stopping at epoch {epoch+1}. Best epoch: {history['best_epoch']+1}")
            break
    
    # Restore best model
    if best_model_state is not None:
        model.load_state_dict(best_model_state)
    
    return history

In [9]:
def fourier_features(T, n_freqs=6):
    """
    Generate Fourier features for temperature values.
    
    Args:
        T: 1D tensor of temperature values (shape: [N])
        n_freqs: number of frequency components (produces 2*n_freqs features)
    
    Returns:
        2D tensor of shape [N, 2*n_freqs] where each row is the Fourier encoding
    """
    # Ensure T is 2D with shape [N, 1] for broadcasting
    if T.dim() == 1:
        T = T.unsqueeze(1)
    
    feats = []
    for k in range(n_freqs):
        freq = 2**k
        feats.append(torch.sin(2 * torch.pi * freq * T))
        feats.append(torch.cos(2 * torch.pi * freq * T))
    
    # Stack along dim=1 to get shape [N, 2*n_freqs]
    return torch.cat(feats, dim=1)

In [ ]:
#pick which flattened dataset to reshape for F(T) surrogate modeling
calphed_data = pd.read_csv(r'Data/F(Composition)_Data/calphad_alloys_train_opt.csv')

KeyboardInterrupt:

In [4]:

# Extract unique temperatures from column names
temp_pattern = re.compile(r'_T(\d+)C$')
temperatures = set()
for col in calphed_data.columns:
    match = temp_pattern.search(col)
    if match:
        temperatures.add(int(match.group(1)))

temperatures = sorted(temperatures)

# Extract unique phases (DF and NF prefixes)
phase_pattern = re.compile(r'^(DF|NF)_(.+?)_T\d+C$')
phases = set()
for col in calphed_data.columns:
    match = phase_pattern.match(col)
    if match:
        phases.add((match.group(1), match.group(2)))  # (prefix, phase_name)

phases = sorted(phases)

# Create new dataframe with alloy_string and temperature as rows
rows = []
for idx, row in calphed_data.iterrows():
    alloy = row['alloy_string']
    for temp in temperatures:
        new_row = {'alloy_string': alloy, 'temperature': temp}
        for prefix, phase in phases:
            col_name = f'{prefix}_{phase}_T{temp}C'
            if col_name in calphed_data.columns:
                new_col_name = f'{prefix}_{phase}'
                new_row[new_col_name] = row[col_name]
        rows.append(new_row)

# Create the reshaped dataframe
df_reshaped = pd.DataFrame(rows)

# Reorder columns to have alloy_string, temperature first, then sorted DF and NF columns
cols = ['alloy_string', 'temperature']
other_cols = [c for c in df_reshaped.columns if c not in cols]
other_cols.sort()
df_reshaped = df_reshaped[cols + other_cols]

print(f"Original shape: {calphed_data.shape}")
print(f"Reshaped shape: {df_reshaped.shape}")
print(f"Number of temperatures: {len(temperatures)}")
print(f"Temperatures: {temperatures[:5]}... to ...{temperatures[-5:]}")
df_reshaped.head(10)

NameError: name 'calphed_data' is not defined

In [ ]:
#choose where to save the reshaped dataset for F(T) surrogate modeling
df_reshaped.to_csv(r'Data/F(T)_Data/calphad_alloys_train_opt_reshaped.csv', index=False)

In [10]:
#load the reshaped dataset to confirm it was saved correctly
df_reshaped = pd.read_csv(r'Data/F(T)_Data/calphad_alloys_train_opt_reshaped.csv')
df_reshaped.head()

,alloy_string,temperature,DF_AG2CA,DF_AG3BE8,DF_AG3CA5,DF_AG3MG,DF_AG7CA2,DF_AG9CA2,DF_AGCA,DF_AGCA3,...,NF_YSI2_H,NF_YSI2_R,NF_ZINCBLENDE_B3,NF_ZR2SI,NF_ZR3SI,NF_ZR3SI2,NF_ZR5SI3,NF_ZR5SI4,NF_ZRSI,NF_ZRSI2
0,B22.00Co4.00Fe68.00Y6.00,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,B22.00Co4.00Fe68.00Y6.00,50,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,B22.00Co4.00Fe68.00Y6.00,100,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,B22.00Co4.00Fe68.00Y6.00,150,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,B22.00Co4.00Fe68.00Y6.00,200,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [11]:
# Extract alloy strings and create formula dataframe
formula_df = pd.DataFrame({'formula': df_reshaped['alloy_string']})
print(f"Formula dataframe shape: {formula_df.shape}")
formula_df.head()

Formula dataframe shape: (44982, 1)

                    formula
0  B22.00Co4.00Fe68.00Y6.00
1  B22.00Co4.00Fe68.00Y6.00
2  B22.00Co4.00Fe68.00Y6.00
3  B22.00Co4.00Fe68.00Y6.00
4  B22.00Co4.00Fe68.00Y6.00

In [12]:
# Generate Composition-Based Feature Vectors using CBFV
# CBFV expects 'formula' column and optionally a 'target' column
# Add a dummy target for featurization (we'll drop it after)
formula_df['target'] = 0

# Generate CBFVs using the magpie element property database
X, y, formulae, skipped = composition.generate_features(formula_df, elem_prop='magpie')
print(f"CBFV features shape: {X.shape}")
print(f"Number of skipped formulas: {len(skipped)}")
X.head()

Processing Input Data:   0%|          | 0/44982 [00:00<?, ?it/s]

Processing Input Data: 100%|██████████| 44982/44982 [00:01<00:00, 42352.21it/s]

	Featurizing Compositions...

Assigning Features...: 100%|██████████| 44982/44982 [00:01<00:00, 32762.55it/s]

	Creating Pandas Objects...
CBFV features shape: (44982, 132)
Number of skipped formulas: 0

,avg_Number,avg_MendeleevNumber,avg_AtomicWeight,avg_MeltingT,avg_Column,avg_Row,avg_CovalentRadius,avg_Electronegativity,avg_NsValence,avg_NpValence,...,mode_NValence,mode_NsUnfilled,mode_NpUnfilled,mode_NdUnfilled,mode_NfUnfilled,mode_NUnfilled,mode_GSvolume_pa,mode_GSbandgap,mode_GSmagmom,mode_SpaceGroupNumber
0,22.2,56.28,48.044699,1926.7,8.84,3.62,124.68,1.8416,2.0,0.22,...,8.0,0.0,0.0,4.0,0.0,4.0,10.73,0.0,2.110663,229.0
1,22.2,56.28,48.044699,1926.7,8.84,3.62,124.68,1.8416,2.0,0.22,...,8.0,0.0,0.0,4.0,0.0,4.0,10.73,0.0,2.110663,229.0
2,22.2,56.28,48.044699,1926.7,8.84,3.62,124.68,1.8416,2.0,0.22,...,8.0,0.0,0.0,4.0,0.0,4.0,10.73,0.0,2.110663,229.0
3,22.2,56.28,48.044699,1926.7,8.84,3.62,124.68,1.8416,2.0,0.22,...,8.0,0.0,0.0,4.0,0.0,4.0,10.73,0.0,2.110663,229.0
4,22.2,56.28,48.044699,1926.7,8.84,3.62,124.68,1.8416,2.0,0.22,...,8.0,0.0,0.0,4.0,0.0,4.0,10.73,0.0,2.110663,229.0

In [13]:
fourier_Temp_features = fourier_features(torch.tensor(df_reshaped['temperature'].values, dtype=torch.float32))
fourier_Temp_features_df = pd.DataFrame(
    fourier_Temp_features.numpy(),
    columns=[f'fourier_{i}' for i in range(fourier_Temp_features.shape[1])],
    index=df_reshaped.index
)

In [14]:
#change depending on which temp features to use

X_combined = pd.concat([X, fourier_Temp_features_df], axis=1)
print(f"X shape: {X_combined.shape}")
X_combined.head()

X shape: (44982, 144)

,avg_Number,avg_MendeleevNumber,avg_AtomicWeight,avg_MeltingT,avg_Column,avg_Row,avg_CovalentRadius,avg_Electronegativity,avg_NsValence,avg_NpValence,...,fourier_2,fourier_3,fourier_4,fourier_5,fourier_6,fourier_7,fourier_8,fourier_9,fourier_10,fourier_11
0,22.2,56.28,48.044699,1926.7,8.84,3.62,124.68,1.8416,2.0,0.22,...,0.000000,1.0,0.000000,1.0,0.000000,1.0,0.000000,1.0,0.000000,1.000000
1,22.2,56.28,48.044699,1926.7,8.84,3.62,124.68,1.8416,2.0,0.22,...,0.000012,1.0,0.000024,1.0,0.000047,1.0,0.000094,1.0,0.000188,1.000000
2,22.2,56.28,48.044699,1926.7,8.84,3.62,124.68,1.8416,2.0,0.22,...,0.000024,1.0,0.000047,1.0,0.000094,1.0,0.000188,1.0,0.000376,1.000000
3,22.2,56.28,48.044699,1926.7,8.84,3.62,124.68,1.8416,2.0,0.22,...,0.000096,1.0,0.000193,1.0,0.000385,1.0,0.000771,1.0,0.001541,0.999999
4,22.2,56.28,48.044699,1926.7,8.84,3.62,124.68,1.8416,2.0,0.22,...,0.000047,1.0,0.000094,1.0,0.000188,1.0,0.000376,1.0,0.000753,1.000000

In [15]:
# Create 5 CV groups by clustering similar alloys together
# Standardize features for clustering
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_combined)

# Use KMeans to group similar alloys into 5 clusters
kmeans = KMeans(n_clusters=5, random_state=42, n_init=10)
cv_groups = kmeans.fit_predict(X_scaled)

# Add group assignments to a dataframe for reference
cv_group_df = pd.DataFrame({
    'formula': formulae,
    'cv_group': cv_groups
})

print("CV Group distribution:")
print(cv_group_df['cv_group'].value_counts().sort_index())
print(f"\nTotal samples: {len(cv_groups)}")
cv_group_df.head(10)

CV Group distribution:
cv_group
0     7599
1    16014
2     6375
3    10200
4     4794
Name: count, dtype: int64

Total samples: 44982

                    formula  cv_group
0  B22.00Co4.00Fe68.00Y6.00         3
1  B22.00Co4.00Fe68.00Y6.00         3
2  B22.00Co4.00Fe68.00Y6.00         3
3  B22.00Co4.00Fe68.00Y6.00         3
4  B22.00Co4.00Fe68.00Y6.00         3
5  B22.00Co4.00Fe68.00Y6.00         3
6  B22.00Co4.00Fe68.00Y6.00         3
7  B22.00Co4.00Fe68.00Y6.00         3
8  B22.00Co4.00Fe68.00Y6.00         3
9  B22.00Co4.00Fe68.00Y6.00         3

In [16]:
#Create the y which is the phase information
y = df_reshaped.drop(columns=['alloy_string', 'temperature'])
print(f"Phase information shape: {y.shape}")
y.head()

Phase information shape: (44982, 1608)

,DF_AG2CA,DF_AG3BE8,DF_AG3CA5,DF_AG3MG,DF_AG7CA2,DF_AG9CA2,DF_AGCA,DF_AGCA3,DF_AGCD_ETA,DF_AGIN2,...,NF_YSI2_H,NF_YSI2_R,NF_ZINCBLENDE_B3,NF_ZR2SI,NF_ZR3SI,NF_ZR3SI2,NF_ZR5SI3,NF_ZR5SI4,NF_ZRSI,NF_ZRSI2
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [12]:
def evaluate_parameters_nn(parameters, batch_size=32, epochs=1000, verbose=True):
    
    # Extract hyperparameters from parameters dict with defaults
    batch_size = parameters.get('batch_size', batch_size)
    hidden_layers = parameters.get('hidden_layers', [256, 128, 64])
    dropout_rate = parameters.get('dropout_rate', 0.2)
    dropout_type = parameters.get('dropout_type', 'standard')
    activation = parameters.get('activation', 'relu')
    use_batch_norm = parameters.get('use_batch_norm', False)
    use_layer_norm = parameters.get('use_layer_norm', False)
    weight_decay = parameters.get('weight_decay', 0.0)
    optimizer_type = parameters.get('optimizer_type', 'adam')
    lr = parameters.get('lr', 1e-3)
    early_stopping_patience = parameters.get('early_stopping_patience', 10)

    # Auto-detect device
    if torch.cuda.is_available():
        device = torch.device('cuda')
    elif torch.backends.mps.is_available():
        device = torch.device('mps')
    else:
        device = torch.device('cpu')
    print(f"Using device: {device}")

    #copy the x and y data
    y_data = y.copy()
    x_data = X_combined.copy()

    # Get input and output dimensions
    input_dim = x_data.shape[1]
    output_dim = y_data.shape[1]
    print(f"Input dim: {input_dim}, Output dim: {output_dim}")

    # Store results for each fold
    fold_results = []
    all_test_predictions = []
    all_test_targets = []

    for test_group in range(5):  # 0-4 for 5 groups from KMeans
        print(f"\n{'='*50}")
        print(f"Fold {test_group}")
        print('='*50)
        
        # Get the split indexes for training and testing
        train_idx = cv_group_df['cv_group'] != test_group
        test_idx = cv_group_df['cv_group'] == test_group

        # Split the x and y data in train and test
        x_train = x_data.loc[train_idx]
        x_test = x_data.loc[test_idx]

        y_train = y_data.loc[train_idx]
        y_test = y_data.loc[test_idx]
        
        # Create train and validation data
        X_train, X_val, y_train, y_val = train_test_split(
            x_train, y_train, test_size=0.2, random_state=42
        )

        print(f"Train: {len(X_train)}, Val: {len(X_val)}, Test: {len(x_test)}")

        # Scale the x data
        scaler = StandardScaler()
        X_train_scaled = pd.DataFrame(scaler.fit_transform(X_train), columns=X_train.columns, index=X_train.index)
        X_val_scaled = pd.DataFrame(scaler.transform(X_val), columns=X_val.columns, index=X_val.index)
        x_test_scaled = pd.DataFrame(scaler.transform(x_test), columns=x_test.columns, index=x_test.index)

        #scale the y data
        y_scaler = StandardScaler()
        y_train_scaled = pd.DataFrame(y_scaler.fit_transform(y_train), columns=y_train.columns, index=y_train.index)
        y_val_scaled = pd.DataFrame(y_scaler.transform(y_val), columns=y_val.columns, index=y_val.index)
        y_test_scaled = pd.DataFrame(y_scaler.transform(y_test), columns=y_test.columns, index=y_test.index)

        # Convert DataFrames to PyTorch tensors
        X_train_t = torch.FloatTensor(X_train_scaled.values)
        y_train_t = torch.FloatTensor(y_train_scaled.values)
        X_val_t = torch.FloatTensor(X_val_scaled.values)
        y_val_t = torch.FloatTensor(y_val_scaled.values)
        X_test_t = torch.FloatTensor(x_test_scaled.values)
        y_test_t = torch.FloatTensor(y_test_scaled.values)

        # Create TensorDatasets
        train_dataset = TensorDataset(X_train_t, y_train_t)
        val_dataset = TensorDataset(X_val_t, y_val_t)
        test_dataset = TensorDataset(X_test_t, y_test_t)

        # Create DataLoaders
        # drop_last=True for train_loader to avoid batch size of 1 (causes BatchNorm to fail)
        train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, drop_last=True)
        val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)
        test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

        # Create the model with output_columns to auto-detect NF columns for softmax
        model = FlexibleNN(
            input_dim=input_dim,
            output_dim=output_dim,
            hidden_layers=hidden_layers,
            dropout_rate=dropout_rate,
            dropout_type=dropout_type,
            activation=activation,
            use_batch_norm=use_batch_norm,
            use_layer_norm=use_layer_norm,
            weight_decay=weight_decay,
            output_columns=y_data.columns.tolist()  # Auto-detect NF columns for softmax constraint
        ).to(device)

        # Get optimizer and criterion
        optimizer = model.get_optimizer(optimizer_type=optimizer_type, lr=lr)
        criterion = nn.MSELoss()

        # Training loop
        best_val_loss = float('inf')
        best_model_state = None
        patience_counter = 0
        train_losses = []
        val_losses = []

        for epoch in range(epochs):
            # Train
            train_loss = train_epoch(model, train_loader, optimizer, criterion, device)
            
            # Evaluate on validation
            val_loss, _, _ = evaluate_epoch(model, val_loader, criterion, device)
            
            train_losses.append(train_loss)
            val_losses.append(val_loss)
            
            # Track best model
            if val_loss < best_val_loss:
                best_val_loss = val_loss
                best_model_state = {k: v.cpu().clone() for k, v in model.state_dict().items()}
                patience_counter = 0
            else:
                patience_counter += 1
            
            # Verbose output
            if verbose and (epoch % 20 == 0 or epoch == epochs - 1):
                print(f"Epoch {epoch+1}/{epochs} - Train Loss: {train_loss:.6f} - Val Loss: {val_loss:.6f}")
            
            # Early stopping
            if early_stopping_patience and patience_counter >= early_stopping_patience:
                print(f"Early stopping at epoch {epoch+1}")
                break

        # Restore best model
        if best_model_state is not None:
            model.load_state_dict(best_model_state)
            model.to(device)

        # Evaluate on test set (scaled)
        test_loss_scaled, test_preds_scaled, test_targets_scaled = evaluate_epoch(model, test_loader, criterion, device)
        
        # Inverse transform predictions and targets to original scale
        test_preds_original = y_scaler.inverse_transform(test_preds_scaled.numpy())
        test_targets_original = y_scaler.inverse_transform(test_targets_scaled.numpy())
        
        # Get column names for separating DF (Driving Force) vs NF (Phase Fraction)
        col_names = y_data.columns.tolist()
        df_cols = [i for i, col in enumerate(col_names) if col.startswith('DF_')]
        nf_cols = [i for i, col in enumerate(col_names) if col.startswith('NF_')]
        
        # Calculate overall RMSE and MAE on original scale (all values)
        mse_original = np.mean((test_preds_original - test_targets_original) ** 2)
        rmse = np.sqrt(mse_original)
        mae = np.mean(np.abs(test_preds_original - test_targets_original))
        
        # Calculate metrics for non-zero targets only
        # Use a small threshold to handle floating point precision
        nonzero_threshold = 1e-6
        
        # Overall non-zero metrics
        nonzero_mask = np.abs(test_targets_original) > nonzero_threshold
        if np.any(nonzero_mask):
            nonzero_errors = test_preds_original[nonzero_mask] - test_targets_original[nonzero_mask]
            rmse_nonzero = np.sqrt(np.mean(nonzero_errors ** 2))
            mae_nonzero = np.mean(np.abs(nonzero_errors))
            n_nonzero = np.sum(nonzero_mask)
        else:
            rmse_nonzero, mae_nonzero, n_nonzero = 0.0, 0.0, 0
        
        # Calculate metrics for Driving Force columns (DF_) - non-zero only
        if df_cols:
            df_preds = test_preds_original[:, df_cols]
            df_targets = test_targets_original[:, df_cols]
            df_nonzero_mask = np.abs(df_targets) > nonzero_threshold
            if np.any(df_nonzero_mask):
                df_errors = df_preds[df_nonzero_mask] - df_targets[df_nonzero_mask]
                df_rmse = np.sqrt(np.mean(df_errors ** 2))
                df_mae = np.mean(np.abs(df_errors))
                n_df_nonzero = np.sum(df_nonzero_mask)
            else:
                df_rmse, df_mae, n_df_nonzero = 0.0, 0.0, 0
        else:
            df_rmse, df_mae, n_df_nonzero = 0.0, 0.0, 0
        
        # Calculate metrics for Phase Fraction columns (NF_) - non-zero only
        if nf_cols:
            nf_preds = test_preds_original[:, nf_cols]
            nf_targets = test_targets_original[:, nf_cols]
            nf_nonzero_mask = np.abs(nf_targets) > nonzero_threshold
            if np.any(nf_nonzero_mask):
                nf_errors = nf_preds[nf_nonzero_mask] - nf_targets[nf_nonzero_mask]
                nf_rmse = np.sqrt(np.mean(nf_errors ** 2))
                nf_mae = np.mean(np.abs(nf_errors))
                n_nf_nonzero = np.sum(nf_nonzero_mask)
            else:
                nf_rmse, nf_mae, n_nf_nonzero = 0.0, 0.0, 0
        else:
            nf_rmse, nf_mae, n_nf_nonzero = 0.0, 0.0, 0
        
        print(f"Overall (all)      - RMSE: {rmse:.4f}, MAE: {mae:.4f}")
        print(f"Overall (non-zero) - RMSE: {rmse_nonzero:.4f}, MAE: {mae_nonzero:.4f}  [{n_nonzero:,} values]")
        print(f"Driving Force (DF) - RMSE: {df_rmse:.4f}, MAE: {df_mae:.4f}  [{n_df_nonzero:,} non-zero values]")
        print(f"Phase Fraction (NF) - RMSE: {nf_rmse:.4f}, MAE: {nf_mae:.4f}  [{n_nf_nonzero:,} non-zero values]")

        # Store fold results
        fold_results.append({
            'fold': test_group,
            'best_val_loss': best_val_loss,
            'test_loss': mse_original,
            'test_rmse': rmse,
            'test_mae': mae,
            'rmse_nonzero': rmse_nonzero,
            'mae_nonzero': mae_nonzero,
            'df_rmse': df_rmse,
            'df_mae': df_mae,
            'nf_rmse': nf_rmse,
            'nf_mae': nf_mae,
            'train_losses': train_losses,
            'val_losses': val_losses
        })
        
        all_test_predictions.append(torch.FloatTensor(test_preds_original))
        all_test_targets.append(torch.FloatTensor(test_targets_original))

    # Summary across all folds
    print(f"\n{'='*50}")
    print("Cross-Validation Summary (non-zero targets only)")
    print('='*50)
    avg_test_loss = np.mean([r['test_loss'] for r in fold_results])
    avg_test_rmse = np.mean([r['test_rmse'] for r in fold_results])
    avg_test_mae = np.mean([r['test_mae'] for r in fold_results])
    avg_rmse_nonzero = np.mean([r['rmse_nonzero'] for r in fold_results])
    avg_mae_nonzero = np.mean([r['mae_nonzero'] for r in fold_results])
    std_test_loss = np.std([r['test_loss'] for r in fold_results])
    
    # Separate metrics for DF and NF (already non-zero)
    avg_df_rmse = np.mean([r['df_rmse'] for r in fold_results])
    avg_df_mae = np.mean([r['df_mae'] for r in fold_results])
    avg_nf_rmse = np.mean([r['nf_rmse'] for r in fold_results])
    avg_nf_mae = np.mean([r['nf_mae'] for r in fold_results])
    
    print(f"Overall (all values):")
    print(f"  Avg Test MSE: {avg_test_loss:.4f} (+/- {std_test_loss:.4f})")
    print(f"  Avg RMSE: {avg_test_rmse:.4f}, MAE: {avg_test_mae:.4f}")
    print(f"\nOverall (non-zero only):")
    print(f"  Avg RMSE: {avg_rmse_nonzero:.4f}, MAE: {avg_mae_nonzero:.4f}")
    print(f"\nDriving Force (DF, non-zero only):")
    print(f"  Avg RMSE: {avg_df_rmse:.4f}, MAE: {avg_df_mae:.4f}")
    print(f"\nPhase Fraction (NF, non-zero only):")
    print(f"  Avg RMSE: {avg_nf_rmse:.4f}, MAE: {avg_nf_mae:.4f}")

    return {
        'fold_results': fold_results,
        'avg_test_loss': avg_test_loss,
        'avg_test_rmse': avg_test_rmse,
        'avg_test_mae': avg_test_mae,
        'avg_rmse_nonzero': avg_rmse_nonzero,
        'avg_mae_nonzero': avg_mae_nonzero,
        'avg_df_rmse': avg_df_rmse,
        'avg_df_mae': avg_df_mae,
        'avg_nf_rmse': avg_nf_rmse,
        'avg_nf_mae': avg_nf_mae,
        'all_predictions': all_test_predictions,
        'all_targets': all_test_targets
    }

In [4]:
def evaluate_parameters_xgb(parameters, verbose=True):
    
    # Extract XGBoost hyperparameters from parameters dict with defaults
    n_estimators = parameters.get('n_estimators', 500)
    max_depth = parameters.get('max_depth', 6)
    learning_rate = parameters.get('learning_rate', 0.1)
    subsample = parameters.get('subsample', 0.8)
    colsample_bytree = parameters.get('colsample_bytree', 0.8)
    min_child_weight = parameters.get('min_child_weight', 1)
    reg_alpha = parameters.get('reg_alpha', 0.0)
    reg_lambda = parameters.get('reg_lambda', 1.0)
    gamma = parameters.get('gamma', 0.0)
    early_stopping_rounds = parameters.get('early_stopping_rounds', 20)

    # Copy the x and y data
    y_data = y.copy()
    x_data = X_combined.copy()

    # Get column names for separating DF (Driving Force) vs NF (Phase Fraction)
    col_names = y_data.columns.tolist()
    df_cols = [i for i, col in enumerate(col_names) if col.startswith('DF_')]
    nf_cols = [i for i, col in enumerate(col_names) if col.startswith('NF_')]

    # Store results for each fold
    fold_results = []
    all_test_predictions = []
    all_test_targets = []

    for test_group in range(5):  # 0-4 for 5 groups from KMeans
        print(f"\n{'='*50}")
        print(f"Fold {test_group}")
        print('='*50)
        
        # Get the split indexes for training and testing
        train_idx = cv_group_df['cv_group'] != test_group
        test_idx = cv_group_df['cv_group'] == test_group

        # Split the x and y data in train and test
        x_train = x_data.loc[train_idx]
        x_test = x_data.loc[test_idx]

        y_train = y_data.loc[train_idx]
        y_test = y_data.loc[test_idx]
        
        # Create train and validation data (for early stopping)
        X_train, X_val, y_train_split, y_val = train_test_split(
            x_train, y_train, test_size=0.2, random_state=42
        )

        print(f"Train: {len(X_train)}, Val: {len(X_val)}, Test: {len(x_test)}")

        # Scale the x data
        scaler = StandardScaler()
        X_train_scaled = pd.DataFrame(scaler.fit_transform(X_train), columns=X_train.columns, index=X_train.index)
        X_val_scaled = pd.DataFrame(scaler.transform(X_val), columns=X_val.columns, index=X_val.index)
        x_test_scaled = pd.DataFrame(scaler.transform(x_test), columns=x_test.columns, index=x_test.index)

        # Train one XGBRegressor per output column (manual multi-output)
        # This avoids the MultiOutputRegressor eval_set bug where full multi-column
        # y_val is passed to each single-output estimator
        estimators = []
        best_iters = []
        output_cols = y_train_split.columns.tolist()
        
        for col_idx, col_name in enumerate(output_cols):
            xgb_model = XGBRegressor(
                n_estimators=n_estimators,
                max_depth=max_depth,
                learning_rate=learning_rate,
                subsample=subsample,
                colsample_bytree=colsample_bytree,
                min_child_weight=min_child_weight,
                reg_alpha=reg_alpha,
                reg_lambda=reg_lambda,
                gamma=gamma,
                random_state=42,
                n_jobs=-1,
                verbosity=0,
                early_stopping_rounds=early_stopping_rounds,
                eval_metric='rmse',
                device='cuda',
                tree_method='hist',
            )
            
            xgb_model.fit(
                X_train_scaled, y_train_split[col_name],
                eval_set=[(X_val_scaled, y_val[col_name])],
                verbose=False,
            )
            
            estimators.append(xgb_model)
            best_iters.append(xgb_model.best_iteration)

        if verbose:
            print(f"Best iterations (min/mean/max): {min(best_iters)}/{np.mean(best_iters):.0f}/{max(best_iters)}")

        # Predict on test set (stack individual predictions)
        test_preds_original = np.column_stack([
            est.predict(x_test_scaled) for est in estimators
        ])
        test_targets_original = y_test.values

        # Calculate overall RMSE and MAE on original scale (all values)
        mse_original = np.mean((test_preds_original - test_targets_original) ** 2)
        rmse = np.sqrt(mse_original)
        mae = np.mean(np.abs(test_preds_original - test_targets_original))
        
        # Calculate metrics for non-zero targets only
        nonzero_threshold = 1e-6
        
        # Overall non-zero metrics
        nonzero_mask = np.abs(test_targets_original) > nonzero_threshold
        if np.any(nonzero_mask):
            nonzero_errors = test_preds_original[nonzero_mask] - test_targets_original[nonzero_mask]
            rmse_nonzero = np.sqrt(np.mean(nonzero_errors ** 2))
            mae_nonzero = np.mean(np.abs(nonzero_errors))
            n_nonzero = np.sum(nonzero_mask)
        else:
            rmse_nonzero, mae_nonzero, n_nonzero = 0.0, 0.0, 0
        
        # Calculate metrics for Driving Force columns (DF_) - non-zero only
        if df_cols:
            df_preds = test_preds_original[:, df_cols]
            df_targets = test_targets_original[:, df_cols]
            df_nonzero_mask = np.abs(df_targets) > nonzero_threshold
            if np.any(df_nonzero_mask):
                df_errors = df_preds[df_nonzero_mask] - df_targets[df_nonzero_mask]
                df_rmse = np.sqrt(np.mean(df_errors ** 2))
                df_mae = np.mean(np.abs(df_errors))
                n_df_nonzero = np.sum(df_nonzero_mask)
            else:
                df_rmse, df_mae, n_df_nonzero = 0.0, 0.0, 0
        else:
            df_rmse, df_mae, n_df_nonzero = 0.0, 0.0, 0
        
        # Calculate metrics for Phase Fraction columns (NF_) - non-zero only
        if nf_cols:
            nf_preds = test_preds_original[:, nf_cols]
            nf_targets = test_targets_original[:, nf_cols]
            nf_nonzero_mask = np.abs(nf_targets) > nonzero_threshold
            if np.any(nf_nonzero_mask):
                nf_errors = nf_preds[nf_nonzero_mask] - nf_targets[nf_nonzero_mask]
                nf_rmse = np.sqrt(np.mean(nf_errors ** 2))
                nf_mae = np.mean(np.abs(nf_errors))
                n_nf_nonzero = np.sum(nf_nonzero_mask)
            else:
                nf_rmse, nf_mae, n_nf_nonzero = 0.0, 0.0, 0
        else:
            nf_rmse, nf_mae, n_nf_nonzero = 0.0, 0.0, 0
        
        print(f"Overall (all)      - RMSE: {rmse:.4f}, MAE: {mae:.4f}")
        print(f"Overall (non-zero) - RMSE: {rmse_nonzero:.4f}, MAE: {mae_nonzero:.4f}  [{n_nonzero:,} values]")
        print(f"Driving Force (DF) - RMSE: {df_rmse:.4f}, MAE: {df_mae:.4f}  [{n_df_nonzero:,} non-zero values]")
        print(f"Phase Fraction (NF) - RMSE: {nf_rmse:.4f}, MAE: {nf_mae:.4f}  [{n_nf_nonzero:,} non-zero values]")

        # Store fold results
        fold_results.append({
            'fold': test_group,
            'test_loss': mse_original,
            'test_rmse': rmse,
            'test_mae': mae,
            'rmse_nonzero': rmse_nonzero,
            'mae_nonzero': mae_nonzero,
            'df_rmse': df_rmse,
            'df_mae': df_mae,
            'nf_rmse': nf_rmse,
            'nf_mae': nf_mae,
        })
        
        all_test_predictions.append(test_preds_original)
        all_test_targets.append(test_targets_original)

    # Summary across all folds
    print(f"\n{'='*50}")
    print("Cross-Validation Summary (non-zero targets only)")
    print('='*50)
    avg_test_loss = np.mean([r['test_loss'] for r in fold_results])
    avg_test_rmse = np.mean([r['test_rmse'] for r in fold_results])
    avg_test_mae = np.mean([r['test_mae'] for r in fold_results])
    avg_rmse_nonzero = np.mean([r['rmse_nonzero'] for r in fold_results])
    avg_mae_nonzero = np.mean([r['mae_nonzero'] for r in fold_results])
    std_test_loss = np.std([r['test_loss'] for r in fold_results])
    
    # Separate metrics for DF and NF (already non-zero)
    avg_df_rmse = np.mean([r['df_rmse'] for r in fold_results])
    avg_df_mae = np.mean([r['df_mae'] for r in fold_results])
    avg_nf_rmse = np.mean([r['nf_rmse'] for r in fold_results])
    avg_nf_mae = np.mean([r['nf_mae'] for r in fold_results])
    
    print(f"Overall (all values):")
    print(f"  Avg Test MSE: {avg_test_loss:.4f} (+/- {std_test_loss:.4f})")
    print(f"  Avg RMSE: {avg_test_rmse:.4f}, MAE: {avg_test_mae:.4f}")
    print(f"\nOverall (non-zero only):")
    print(f"  Avg RMSE: {avg_rmse_nonzero:.4f}, MAE: {avg_mae_nonzero:.4f}")
    print(f"\nDriving Force (DF, non-zero only):")
    print(f"  Avg RMSE: {avg_df_rmse:.4f}, MAE: {avg_df_mae:.4f}")
    print(f"\nPhase Fraction (NF, non-zero only):")
    print(f"  Avg RMSE: {avg_nf_rmse:.4f}, MAE: {avg_nf_mae:.4f}")

    return {
        'fold_results': fold_results,
        'avg_test_loss': avg_test_loss,
        'avg_test_rmse': avg_test_rmse,
        'avg_test_mae': avg_test_mae,
        'avg_rmse_nonzero': avg_rmse_nonzero,
        'avg_mae_nonzero': avg_mae_nonzero,
        'avg_df_rmse': avg_df_rmse,
        'avg_df_mae': avg_df_mae,
        'avg_nf_rmse': avg_nf_rmse,
        'avg_nf_mae': avg_nf_mae,
        'all_predictions': all_test_predictions,
        'all_targets': all_test_targets
    }

In [36]:
parameters = {
    'hidden_layers': [512, 1024],
    'use_batch_norm': True,
    'weight_decay': 1e-4,
    'lr': 1e-3,
    'early_stopping_patience': 15
}
results = evaluate_parameters_nn(parameters)

Using device: mps
Input dim: 133, Output dim: 1608

==================================================
Fold 0
==================================================
Train: 27825, Val: 6957, Test: 10200
Epoch 1/1000 - Train Loss: 0.370060 - Val Loss: 0.298181
Epoch 21/1000 - Train Loss: 0.275926 - Val Loss: 0.270464
Early stopping at epoch 35
Overall (all)      - RMSE: 2.8000, MAE: 0.6882
Overall (non-zero) - RMSE: 6.9376, MAE: 3.8382  [695,272 values]
Driving Force (DF) - RMSE: 7.0511, MAE: 3.9563  [673,018 non-zero values]
Phase Fraction (NF) - RMSE: 0.3351, MAE: 0.2660  [22,254 non-zero values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Epoch 1/1000 - Train Loss: 0.380447 - Val Loss: 0.333415
Epoch 21/1000 - Train Loss: 0.279063 - Val Loss: 0.270137
Early stopping at epoch 31
Overall (all)      - RMSE: 1.4986, MAE: 0.3088
Overall (non-zero) - RMSE: 5.8948, MAE: 2.9751  [1,235,656 values]
Driving Force (DF) - RMSE: 5.9624, MAE: 3.0364  [1,207,679 non-zero values]
Phase Fraction (NF) - RMSE: 0.4088, MAE: 0.3308  [27,977 non-zero values]

==================================================
Fold 2
==================================================
Train: 29906, Val: 7477, Test: 7599
Epoch 1/1000 - Train Loss: 0.401035 - Val Loss: 0.401363
Epoch 21/1000 - Train Loss: 0.302717 - Val Loss: 0.368746
Epoch 41/1000 - Train Loss: 0.302036 - Val Loss: 0.365468
Early stopping at epoch 42
Overall (all)      - RMSE: 1.9701, MAE: 0.6053
Overall (non-zero) - RMSE: 7.1462, MAE: 4.3373  [509,534 values]
Driving Force (DF) - RMSE: 7.2257, MAE: 4.4253  [498,341 non-zero values]
Phase Fraction (NF) - RMSE: 0.4910, MAE: 0.4208  [11,193 non-zero values]

==================================================
Fold 3
==================================================
Train: 30885, Val: 7722, Test: 6375
Epoch 1/1000 - Train Loss: 0.422793 - Val Loss: 0.346592
Epoch 21/1000 - Train Loss: 0.316056 - Val Loss: 0.312755
Early stopping at epoch 28
Overall (all)      - RMSE: 1.8125, MAE: 0.2720
Overall (non-zero) - RMSE: 5.8600, MAE: 2.3952  [410,105 values]
Driving Force (DF) - RMSE: 5.9386, MAE: 2.4496  [399,249 non-zero values]
Phase Fraction (NF) - RMSE: 0.4732, MAE: 0.3926  [10,856 non-zero values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Epoch 1/1000 - Train Loss: 0.442708 - Val Loss: 0.455127
Epoch 21/1000 - Train Loss: 0.336197 - Val Loss: 0.403963
Epoch 41/1000 - Train Loss: 0.334581 - Val Loss: 0.425369
Early stopping at epoch 45
Overall (all)      - RMSE: 1.1677, MAE: 0.3194
Overall (non-zero) - RMSE: 2.8908, MAE: 1.7714  [240,039 values]
Driving Force (DF) - RMSE: 2.9278, MAE: 1.8075  [233,863 non-zero values]
Phase Fraction (NF) - RMSE: 0.4303, MAE: 0.4042  [6,176 non-zero values]

==================================================
Cross-Validation Summary (non-zero targets only)
==================================================
Overall (all values):
  Avg Test MSE: 3.7231 (+/- 2.2323)
  Avg RMSE: 1.8498, MAE: 0.4387

Overall (non-zero only):
  Avg RMSE: 5.7459, MAE: 3.0634

Driving Force (DF, non-zero only):
  Avg RMSE: 5.8211, MAE: 3.1350

Phase Fraction (NF, non-zero only):
  Avg RMSE: 0.4277, MAE: 0.3629

In [16]:
# Define architecture presets mapping (all expanding for large output dim)
ARCHITECTURE_PRESETS = {
    # Single layer - direct expansion
    "single_256": [256],
    "single_512": [512],
    "single_1024": [1024],
    "single_2048": [2048],
    # Two layers - expanding
    "expand_2L_small": [256, 512],
    "expand_2L_medium": [512, 1024],
    "expand_2L_large": [1024, 2048],
    "expand_2L_xlarge": [512, 2048],
    # Three layers - expanding
    "expand_3L_small": [256, 512, 1024],
    "expand_3L_medium": [512, 1024, 2048],
    "expand_3L_large": [256, 1024, 2048],
    "expand_3L_gradual": [384, 768, 1536],
    # Four layers - expanding
    "expand_4L_small": [256, 512, 1024, 2048],
    "expand_4L_medium": [512, 768, 1024, 2048],
    "expand_4L_large": [256, 512, 1024, 4096],
    # Constant width (also good for large outputs)
    "constant_512": [512, 512],
    "constant_1024": [1024, 1024],
    "constant_2048": [2048, 2048],
    "constant_1024_3L": [1024, 1024, 1024],
}

ax_client = AxClient()
ax_client.create_experiment(
    name="NN opt CBFV f(T) Calphed",
    parameters=[
        {
            "name": "architecture",
            "type": "choice",
            "values": list(ARCHITECTURE_PRESETS.keys()),
            "is_ordered": False,
        },
        {
            "name": "dropout_rate",
            "type": "range",
            "bounds": [0.0, 0.5],
        },
        {
            "name": "activation",
            "type": "choice",
            "values": ["relu", "leaky_relu", "elu", "selu", "gelu"],
        },
        {
            "name": "normalization",
            "type": "choice",
            "values": ["none", "batch_norm", "layer_norm"],
        },
        {
            "name": "weight_decay",
            "type": "range",
            "bounds": [1e-6, 1e-2],
            "log_scale": True,
        },
        {
            "name": "lr",
            "type": "range",
            "bounds": [1e-5, 1e-2],
            "log_scale": True,
        },
        {
            "name": "optimizer_type",
            "type": "choice",
            "values": ["adam", "adamw"],
        },
        {
            "name": "batch_size",
            "type": "choice",
            "values": [32, 64, 128, 256],
        },
        {
            "name": "early_stopping_patience",
            "type": "range",
            "bounds": [10, 50],
            "value_type": "int",
        },
    ],
    objectives={"avg_rmse_nonzero": ObjectiveProperties(minimize=True)}
)

def evaluate_for_ax(parameterization):
    """Wrapper to convert Ax parameters to evaluate_parameters_nn format."""
    # Get hidden_layers from architecture preset
    architecture = parameterization["architecture"]
    hidden_layers = ARCHITECTURE_PRESETS[architecture]
    
    # Handle normalization choice
    normalization = parameterization["normalization"]
    use_batch_norm = normalization == "batch_norm"
    use_layer_norm = normalization == "layer_norm"
    
    # Handle dropout type based on activation
    activation = parameterization["activation"]
    dropout_type = "alpha" if activation == "selu" else "standard"
    
    # Build parameters dict
    parameters = {
        "hidden_layers": hidden_layers,
        "dropout_rate": parameterization["dropout_rate"],
        "dropout_type": dropout_type,
        "activation": activation,
        "use_batch_norm": use_batch_norm,
        "use_layer_norm": use_layer_norm,
        "weight_decay": parameterization["weight_decay"],
        "lr": parameterization["lr"],
        "optimizer_type": parameterization["optimizer_type"],
        "batch_size": parameterization["batch_size"],
        "early_stopping_patience": parameterization["early_stopping_patience"],
    }
    
    # Run evaluation
    results = evaluate_parameters_nn(parameters, verbose=False)
    
    # Calculate SEM (Standard Error of the Mean) from fold results
    # SEM = std / sqrt(n_folds)
    rmse_nonzero_values = [r["rmse_nonzero"] for r in results["fold_results"]]
    mean_rmse_nonzero = np.mean(rmse_nonzero_values)
    std_rmse_nonzero = np.std(rmse_nonzero_values, ddof=1)  # ddof=1 for sample std
    sem_rmse_nonzero = std_rmse_nonzero / np.sqrt(len(rmse_nonzero_values))
    
    # Return the objective with proper SEM for Bayesian optimization
    return {"avg_rmse_nonzero": (mean_rmse_nonzero, sem_rmse_nonzero)}

[INFO 02-17 08:41:18] ax.service.ax_client: Starting optimization with verbose logging. To disable logging, set the `verbose_logging` argument to `False`. Note that float values in the logs are rounded to 6 decimal points.
[INFO 02-17 08:41:18] ax.service.utils.instantiation: Inferred value type of ParameterType.STRING for parameter architecture. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\service\utils\instantiation.py:258: AxParameterWarning: `sort_values` is not specified for `ChoiceParameter` "architecture". Defaulting to `False` for parameters of `ParameterType` STRING. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  return ChoiceParameter(
[INFO 02-17 08:41:18] ax.service.utils.instantiation: Inferred value type of ParameterType.FLOAT for parameter dropout_rate. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
[INFO 02-17 08:41:18] ax.service.utils.instantiation: Inferred value type of ParameterType.STRING for parameter activation. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\service\utils\instantiation.py:258: AxParameterWarning: `is_ordered` is not specified for `ChoiceParameter` "activation". Defaulting to `False`  since the parameter is a string with more than 2 choices.. To override this behavior (or avoid this warning), specify `is_ordered` during `ChoiceParameter` construction. Note that choice parameters with exactly 2 choices are always considered ordered and that the user-supplied `is_ordered` has no effect in this particular case.
  return ChoiceParameter(
c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\service\utils\instantiation.py:258: AxParameterWarning: `sort_values` is not specified for `ChoiceParameter` "activation". Defaulting to `False` for parameters of `ParameterType` STRING. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  return ChoiceParameter(
[INFO 02-17 08:41:18] ax.service.utils.instantiation: Inferred value type of ParameterType.STRING for parameter normalization. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\service\utils\instantiation.py:258: AxParameterWarning: `is_ordered` is not specified for `ChoiceParameter` "normalization". Defaulting to `False`  since the parameter is a string with more than 2 choices.. To override this behavior (or avoid this warning), specify `is_ordered` during `ChoiceParameter` construction. Note that choice parameters with exactly 2 choices are always considered ordered and that the user-supplied `is_ordered` has no effect in this particular case.
  return ChoiceParameter(
c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\service\utils\instantiation.py:258: AxParameterWarning: `sort_values` is not specified for `ChoiceParameter` "normalization". Defaulting to `False` for parameters of `ParameterType` STRING. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  return ChoiceParameter(
[INFO 02-17 08:41:18] ax.service.utils.instantiation: Inferred value type of ParameterType.FLOAT for parameter weight_decay. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
[INFO 02-17 08:41:18] ax.service.utils.instantiation: Inferred value type of ParameterType.FLOAT for parameter lr. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
[INFO 02-17 08:41:18] ax.service.utils.instantiation: Inferred value type of ParameterType.STRING for parameter optimizer_type. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\service\utils\instantiation.py:258: AxParameterWarning: `is_ordered` is not specified for `ChoiceParameter` "optimizer_type". Defaulting to `True`  since there are exactly two choices.. To override this behavior (or avoid this warning), specify `is_ordered` during `ChoiceParameter` construction. Note that choice parameters with exactly 2 choices are always considered ordered and that the user-supplied `is_ordered` has no effect in this particular case.
  return ChoiceParameter(
c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\service\utils\instantiation.py:258: AxParameterWarning: `sort_values` is not specified for `ChoiceParameter` "optimizer_type". Defaulting to `False` for parameters of `ParameterType` STRING. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  return ChoiceParameter(
[INFO 02-17 08:41:18] ax.service.utils.instantiation: Inferred value type of ParameterType.INT for parameter batch_size. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\service\utils\instantiation.py:258: AxParameterWarning: `is_ordered` is not specified for `ChoiceParameter` "batch_size". Defaulting to `True`  since the parameter is not of type string.. To override this behavior (or avoid this warning), specify `is_ordered` during `ChoiceParameter` construction. Note that choice parameters with exactly 2 choices are always considered ordered and that the user-supplied `is_ordered` has no effect in this particular case.
  return ChoiceParameter(
c:\Users\Chris\pytorch_gpu\Lib\site-packages\ax\service\utils\instantiation.py:258: AxParameterWarning: `sort_values` is not specified for `ChoiceParameter` "batch_size". Defaulting to `True` for parameters of `ParameterType` INT. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  return ChoiceParameter(
[INFO 02-17 08:41:18] ax.service.utils.instantiation: Created search space: SearchSpace(parameters=[ChoiceParameter(name='architecture', parameter_type=STRING, values=['single_256', 'single_512', 'single_1024', 'single_2048', 'expand_2L_small', 'expand_2L_medium', 'expand_2L_large', 'expand_2L_xlarge', 'expand_3L_small', 'expand_3L_medium', 'expand_3L_large', 'expand_3L_gradual', 'expand_4L_small', 'expand_4L_medium', 'expand_4L_large', 'constant_512', 'constant_1024', 'constant_2048', 'constant_1024_3L'], is_ordered=False, sort_values=False), RangeParameter(name='dropout_rate', parameter_type=FLOAT, range=[0.0, 0.5]), ChoiceParameter(name='activation', parameter_type=STRING, values=['relu', 'leaky_relu', 'elu', 'selu', 'gelu'], is_ordered=False, sort_values=False), ChoiceParameter(name='normalization', parameter_type=STRING, values=['none', 'batch_norm', 'layer_norm'], is_ordered=False, sort_values=False), RangeParameter(name='weight_decay', parameter_type=FLOAT, range=[1e-06, 0.01], log_scale=True), RangeParameter(name='lr', parameter_type=FLOAT, range=[1e-05, 0.01], log_scale=True), ChoiceParameter(name='optimizer_type', parameter_type=STRING, values=['adam', 'adamw'], is_ordered=True, sort_values=False), ChoiceParameter(name='batch_size', parameter_type=INT, values=[32, 64, 128, 256], is_ordered=True, sort_values=True), RangeParameter(name='early_stopping_patience', parameter_type=INT, range=[10, 50])], parameter_constraints=[]).
[INFO 02-17 08:41:18] ax.modelbridge.dispatch_utils: Using Models.BOTORCH_MODULAR since there is at least one ordered parameter and there are fewer than 33 choices for unordered parameters.
[INFO 02-17 08:41:18] ax.modelbridge.dispatch_utils: Calculating the number of remaining initialization trials based on num_initialization_trials=None max_initialization_trials=None num_tunable_parameters=9 num_trials=None use_batch_trials=False
[INFO 02-17 08:41:18] ax.modelbridge.dispatch_utils: calculated num_initialization_trials=18
[INFO 02-17 08:41:18] ax.modelbridge.dispatch_utils: num_completed_initialization_trials=0 num_remaining_initialization_trials=18
[INFO 02-17 08:41:18] ax.modelbridge.dispatch_utils: `verbose`, `disable_progbar`, and `jit_compile` are not yet supported when using `choose_generation_strategy` with ModularBoTorchModel, dropping these arguments.
[INFO 02-17 08:41:18] ax.modelbridge.dispatch_utils: Using Bayesian Optimization generation strategy: GenerationStrategy(name='Sobol+BoTorch', steps=[Sobol for 18 trials, BoTorch for subsequent trials]). Iterations after 18 will take longer to generate due to model-fitting.

In [ ]:
# Run the Bayesian optimization loop
n_trials = 100  # Adjust based on your time budget

for i in range(n_trials):
    print(f"\n{'='*60}")
    print(f"Trial {i+1}/{n_trials}")
    print('='*60)
    
    parameters, trial_index = ax_client.get_next_trial()
    print(f"Parameters: {parameters}")
    
    try:
        result = evaluate_for_ax(parameters)
        ax_client.complete_trial(trial_index=trial_index, raw_data=result)
        print(f"Result: Non-zero RMSE = {result['avg_rmse_nonzero'][0]:.4f}")
    except Exception as e:
        print(f"Trial failed: {e}")
        ax_client.log_trial_failure(trial_index=trial_index)

# Get best parameters
best_parameters, values = ax_client.get_best_parameters()
print(f"\n{'='*60}")
print("OPTIMIZATION COMPLETE")
print('='*60)
print(f"Best parameters: {best_parameters}")
print(f"Best Non-zero RMSE: {values[0]['avg_rmse_nonzero']:.4f}")

In [ ]:

# Get best parameters
best_parameters, values = ax_client.get_best_parameters()
print(f"\n{'='*60}")
print("OPTIMIZATION COMPLETE")
print('='*60)
print(f"Best parameters: {best_parameters}")
print(f"Best Non-zero RMSE: {values[0]['avg_rmse_nonzero']:.4f}")

#Best parameters: {'dropout_rate': 0.2551544178277254, 'weight_decay': 9.945539915060379e-06, 'lr': 0.002343417645870794, 'optimizer_type': 'adamw', 'batch_size': 256, 'early_stopping_patience': 32, 'architecture': 'constant_2048', 'activation': 'elu', 'normalization': 'layer_norm'}
#Best Non-zero RMSE: 5.2790

In [17]:
ax_client_2 = AxClient()
ax_client_2.create_experiment(
    name="XGB opt CBFV f(T) Calphed",
    parameters=[
        {
            "name": "n_estimators",
            "type": "range",
            "bounds": [100, 10000],
            "value_type": "int",
        },
        {
            "name": "max_depth",
            "type": "range",
            "bounds": [3, 100],
            "value_type": "int",
        },
        {
            "name": "learning_rate",
            "type": "range",
            "bounds": [0.005, 0.3],
            "value_type": "float",
            "log_scale": True,
        },
        {
            "name": "subsample",
            "type": "range",
            "bounds": [0.5, 1.0],
            "value_type": "float",

        },
        {
            "name": "colsample_bytree",
            "type": "range",
            "bounds": [0.3, 1.0],
            "value_type": "float",
        },
        {
            "name": "min_child_weight",
            "type": "range",
            "bounds": [1, 20],
            "value_type": "int",
        },
        {
            "name": "reg_alpha",
            "type": "range",
            "bounds": [1e-6, 10.0],
            "value_type": "float",
            "log_scale": True,
        },
        {
            "name": "reg_lambda",
            "type": "range",
            "bounds": [1e-6, 10.0],
            "value_type": "float",
            "log_scale": True,
        },
        {
            "name": "gamma",
            "type": "range",
            "bounds": [1e-6, 5.0],
            "log_scale": True,
            "value_type": "float",
        },
        {
            "name": "early_stopping_rounds",
            "type": "range",
            "bounds": [10, 50],
            "value_type": "int",
        },
    ],
    objectives={"avg_rmse_nonzero": ObjectiveProperties(minimize=True)}
)

def evaluate_for_ax_xgb(parameterization):
    """Wrapper to convert Ax parameters to evaluate_parameters_xgb format."""
    parameters = {
        "n_estimators": parameterization["n_estimators"],
        "max_depth": parameterization["max_depth"],
        "learning_rate": parameterization["learning_rate"],
        "subsample": parameterization["subsample"],
        "colsample_bytree": parameterization["colsample_bytree"],
        "min_child_weight": parameterization["min_child_weight"],
        "reg_alpha": parameterization["reg_alpha"],
        "reg_lambda": parameterization["reg_lambda"],
        "gamma": parameterization["gamma"],
        "early_stopping_rounds": parameterization["early_stopping_rounds"],
    }

    # Run evaluation
    results = evaluate_parameters_xgb(parameters, verbose=False)

    # Calculate SEM (Standard Error of the Mean) from fold results
    rmse_nonzero_values = [r["rmse_nonzero"] for r in results["fold_results"]]
    mean_rmse_nonzero = np.mean(rmse_nonzero_values)
    std_rmse_nonzero = np.std(rmse_nonzero_values, ddof=1)
    sem_rmse_nonzero = std_rmse_nonzero / np.sqrt(len(rmse_nonzero_values))

    return {"avg_rmse_nonzero": (mean_rmse_nonzero, sem_rmse_nonzero)}

[INFO 03-31 11:02:47] ax.generation_strategy.dispatch_utils: Using Generators.BOTORCH_MODULAR since there is at least one ordered parameter and there are no unordered categorical parameters.
[INFO 03-31 11:02:47] ax.generation_strategy.dispatch_utils: Using Bayesian Optimization generation strategy: GenerationStrategy(name='Sobol+BoTorch', steps=[Sobol for 20 trials, BoTorch for subsequent trials]). Iterations after 20 will take longer to generate due to model-fitting.

In [ ]:
# Run the Bayesian optimization loop
n_trials = 100  # Adjust based on your time budget

for i in range(n_trials):
    print(f"\n{'='*60}")
    print(f"Trial {i+1}/{n_trials}")
    print('='*60)
    
    parameters, trial_index = ax_client_2.get_next_trial()
    print(f"Parameters: {parameters}")
    
    try:
        result = evaluate_for_ax_xgb(parameters)
        ax_client_2.complete_trial(trial_index=trial_index, raw_data=result)
        print(f"Result: Non-zero RMSE = {result['avg_rmse_nonzero'][0]:.4f}")
    except Exception as e:
        print(f"Trial failed: {e}")
        ax_client_2.log_trial_failure(trial_index=trial_index)
    
    # Save after each trial for safety
    ax_client_2.save_to_json_file(r"Ax_checkpoints\ax_client_XGB_CALPHAD_V2.json")

# Get best parameters
best_parameters, values = ax_client_2.get_best_parameters()
print(f"\n{'='*60}")
print("OPTIMIZATION COMPLETE")
print('='*60)
print(f"Best parameters: {best_parameters}")
print(f"Best Non-zero RMSE: {values[0]['avg_rmse_nonzero']:.4f}")

[INFO 03-31 11:02:49] ax.service.ax_client: Generated new trial 0 with parameters {'n_estimators': 5386, 'max_depth': 49, 'learning_rate': 0.17755, 'subsample': 0.88703, 'colsample_bytree': 0.832737, 'min_child_weight': 18, 'reg_alpha': 3.47402, 'reg_lambda': 2.3e-05, 'gamma': 0.003317, 'early_stopping_rounds': 47} using model Sobol.

============================================================
Trial 1/100
============================================================
Parameters: {'n_estimators': 5386, 'max_depth': 49, 'learning_rate': 0.17754980241486257, 'subsample': 0.8870299756526947, 'colsample_bytree': 0.8327370762825013, 'min_child_weight': 18, 'reg_alpha': 3.474019734047349, 'reg_lambda': 2.255409678626809e-05, 'gamma': 0.0033168085311114583, 'early_stopping_rounds': 47}

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599

In [ ]:
# Load the XGBoost Ax client from last save and continue optimization to 100 trials
ax_client_2 = AxClient.load_from_json_file("Ax_checkpoints/ax_client_xgb_calphad_fT.json")

completed_trials = len(ax_client_2.experiment.trials)
target_trials = 100
remaining_trials = target_trials - completed_trials

print(f"Loaded {completed_trials} completed trials from ax_client_xgb.json")
print(f"Remaining trials to reach {target_trials}: {remaining_trials}")

if remaining_trials > 0:
    for i in range(remaining_trials):
        current_trial = completed_trials + i + 1
        print(f"\n{'='*60}")
        print(f"Trial {current_trial}/{target_trials}")
        print('='*60)

        parameters, trial_index = ax_client_2.get_next_trial()
        print(f"Parameters: {parameters}")

        try:
            result = evaluate_for_ax_xgb(parameters)
            ax_client_2.complete_trial(trial_index=trial_index, raw_data=result)
            print(f"Result: Non-zero RMSE = {result['avg_rmse_nonzero'][0]:.4f}")
        except Exception as e:
            print(f"Trial failed: {e}")
            ax_client_2.log_trial_failure(trial_index=trial_index)

        # Save after each trial for safety
        ax_client_2.save_to_json_file("Ax_checkpoints/ax_client_xgb_calphad_fT.json")

    # Get best parameters after all trials
    best_parameters, values = ax_client_2.get_best_parameters()
    print(f"\n{'='*60}")
    print("OPTIMIZATION COMPLETE")
    print('='*60)
    print(f"Best parameters: {best_parameters}")
    print(f"Best Non-zero RMSE: {values[0]['avg_rmse_nonzero']:.4f}")
else:
    print("Already at or past 100 trials. No additional trials needed.")
    best_parameters, values = ax_client_2.get_best_parameters()
    print(f"Best parameters: {best_parameters}")
    print(f"Best Non-zero RMSE: {values[0]['avg_rmse_nonzero']:.4f}")

[INFO 03-11 06:07:53] ax.service.ax_client: Starting optimization with verbose logging. To disable logging, set the `verbose_logging` argument to `False`. Note that float values in the logs are rounded to 6 decimal points.

Loaded 28 completed trials from ax_client_xgb.json
Remaining trials to reach 100: 72

============================================================
Trial 29/100
============================================================

C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 595, 'max_depth': 3, 'learning_rate': 0.29999999999999993, 'subsample': 0.5, 'colsample_bytree': 0.3, 'min_child_weight': 1, 'reg_alpha': 10.0, 'reg_lambda': 1e-06, 'gamma': 2.3916869875492894, 'early_stopping_rounds': 10}

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Overall (all)      - RMSE: 1.3649, MAE: 0.3323
Overall (non-zero) - RMSE: 4.8783, MAE: 3.0690  [509,534 values]
Driving Force (DF) - RMSE: 4.9324, MAE: 3.1308  [498,341 non-zero values]
Phase Fraction (NF) - RMSE: 0.3947, MAE: 0.3189  [11,193 non-zero values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Overall (all)      - RMSE: 1.3861, MAE: 0.2387
Overall (non-zero) - RMSE: 5.4822, MAE: 2.8877  [1,235,656 values]
Driving Force (DF) - RMSE: 5.5450, MAE: 2.9476  [1,207,679 non-zero values]
Phase Fraction (NF) - RMSE: 0.3911, MAE: 0.3032  [27,977 non-zero values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Overall (all)      - RMSE: 0.9692, MAE: 0.1997
Overall (non-zero) - RMSE: 3.6037, MAE: 1.9007  [410,105 values]
Driving Force (DF) - RMSE: 3.6517, MAE: 1.9437  [399,249 non-zero values]
Phase Fraction (NF) - RMSE: 0.4223, MAE: 0.3227  [10,856 non-zero values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Overall (all)      - RMSE: 2.2328, MAE: 0.5780
Overall (non-zero) - RMSE: 6.1583, MAE: 3.5459  [695,272 values]
Driving Force (DF) - RMSE: 6.2590, MAE: 3.6547  [673,018 non-zero values]
Phase Fraction (NF) - RMSE: 0.3352, MAE: 0.2549  [22,254 non-zero values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Overall (all)      - RMSE: 1.2233, MAE: 0.3388
Overall (non-zero) - RMSE: 2.6283, MAE: 1.7709  [240,039 values]
Driving Force (DF) - RMSE: 2.6622, MAE: 1.8107  [233,863 non-zero values]
Phase Fraction (NF) - RMSE: 0.3195, MAE: 0.2611  [6,176 non-zero values]

==================================================
Cross-Validation Summary (non-zero targets only)
==================================================
Overall (all values):
  Avg Test MSE: 2.2412 (+/- 1.4160)
  Avg RMSE: 1.4353, MAE: 0.3375

Overall (non-zero only):
  Avg RMSE: 4.5502, MAE: 2.6348

Driving Force (DF, non-zero only):
  Avg RMSE: 4.6101, MAE: 2.6975

Phase Fraction (NF, non-zero only):
  Avg RMSE: 0.3726, MAE: 0.2922

[INFO 03-11 06:53:52] ax.service.ax_client: Completed trial 28 with data: {'avg_rmse_nonzero': (np.float64(4.550156), np.float64(0.638431))}.
[INFO 03-11 06:53:52] ax.service.ax_client: Saved JSON-serialized state of optimization to `ax_client_xgb.json`.

Result: Non-zero RMSE = 4.5502

============================================================
Trial 30/100
============================================================

C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 03-11 06:53:57] ax.service.ax_client: Generated new trial 29 with parameters {'n_estimators': 948, 'max_depth': 100, 'learning_rate': 0.010404, 'subsample': 0.5, 'colsample_bytree': 0.3, 'min_child_weight': 20, 'reg_alpha': 10.0, 'reg_lambda': 1e-06, 'gamma': 5.0, 'early_stopping_rounds': 29} using model BoTorch.

Parameters: {'n_estimators': 948, 'max_depth': 100, 'learning_rate': 0.010404308243843603, 'subsample': 0.5, 'colsample_bytree': 0.3, 'min_child_weight': 20, 'reg_alpha': 10.0, 'reg_lambda': 1e-06, 'gamma': 5.0, 'early_stopping_rounds': 29}

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Overall (all)      - RMSE: 1.1149, MAE: 0.2739
Overall (non-zero) - RMSE: 4.3886, MAE: 2.6647  [509,534 values]
Driving Force (DF) - RMSE: 4.4372, MAE: 2.7171  [498,341 non-zero values]
Phase Fraction (NF) - RMSE: 0.4246, MAE: 0.3327  [11,193 non-zero values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Overall (all)      - RMSE: 1.3493, MAE: 0.2147
Overall (non-zero) - RMSE: 5.6189, MAE: 2.8058  [1,235,656 values]
Driving Force (DF) - RMSE: 5.6833, MAE: 2.8635  [1,207,679 non-zero values]
Phase Fraction (NF) - RMSE: 0.3982, MAE: 0.3135  [27,977 non-zero values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Overall (all)      - RMSE: 0.7801, MAE: 0.1497
Overall (non-zero) - RMSE: 3.2962, MAE: 1.6806  [410,105 values]
Driving Force (DF) - RMSE: 3.3399, MAE: 1.7172  [399,249 non-zero values]
Phase Fraction (NF) - RMSE: 0.4281, MAE: 0.3357  [10,856 non-zero values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Overall (all)      - RMSE: 1.7825, MAE: 0.4896
Overall (non-zero) - RMSE: 5.6364, MAE: 3.2112  [695,272 values]
Driving Force (DF) - RMSE: 5.7285, MAE: 3.3094  [673,018 non-zero values]
Phase Fraction (NF) - RMSE: 0.3125, MAE: 0.2423  [22,254 non-zero values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Overall (all)      - RMSE: 0.7368, MAE: 0.2298
Overall (non-zero) - RMSE: 1.9819, MAE: 1.3474  [240,039 values]
Driving Force (DF) - RMSE: 2.0073, MAE: 1.3762  [233,863 non-zero values]
Phase Fraction (NF) - RMSE: 0.3050, MAE: 0.2555  [6,176 non-zero values]

==================================================
Cross-Validation Summary (non-zero targets only)
==================================================
Overall (all values):
  Avg Test MSE: 1.4785 (+/- 0.9685)
  Avg RMSE: 1.1527, MAE: 0.2715

Overall (non-zero only):
  Avg RMSE: 4.1844, MAE: 2.3419

Driving Force (DF, non-zero only):
  Avg RMSE: 4.2392, MAE: 2.3967

Phase Fraction (NF, non-zero only):
  Avg RMSE: 0.3737, MAE: 0.2959

[INFO 03-11 11:16:18] ax.service.ax_client: Completed trial 29 with data: {'avg_rmse_nonzero': (np.float64(4.184398), np.float64(0.701691))}.
[INFO 03-11 11:16:18] ax.service.ax_client: Saved JSON-serialized state of optimization to `ax_client_xgb.json`.

Result: Non-zero RMSE = 4.1844

============================================================
Trial 31/100
============================================================

C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 03-11 11:16:21] ax.service.ax_client: Generated new trial 30 with parameters {'n_estimators': 9611, 'max_depth': 100, 'learning_rate': 0.3, 'subsample': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 1, 'reg_alpha': 10.0, 'reg_lambda': 1e-06, 'gamma': 5.0, 'early_stopping_rounds': 50} using model BoTorch.

Parameters: {'n_estimators': 9611, 'max_depth': 100, 'learning_rate': 0.29999999999999993, 'subsample': 0.5, 'colsample_bytree': 1.0, 'min_child_weight': 1, 'reg_alpha': 10.0, 'reg_lambda': 1e-06, 'gamma': 5.0, 'early_stopping_rounds': 50}

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Overall (all)      - RMSE: 1.3699, MAE: 0.2860
Overall (non-zero) - RMSE: 4.7603, MAE: 2.8987  [509,534 values]
Driving Force (DF) - RMSE: 4.8131, MAE: 2.9562  [498,341 non-zero values]
Phase Fraction (NF) - RMSE: 0.4313, MAE: 0.3385  [11,193 non-zero values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Overall (all)      - RMSE: 1.4644, MAE: 0.2165
Overall (non-zero) - RMSE: 5.8961, MAE: 3.1622  [1,235,656 values]
Driving Force (DF) - RMSE: 5.9637, MAE: 3.2277  [1,207,679 non-zero values]
Phase Fraction (NF) - RMSE: 0.4268, MAE: 0.3347  [27,977 non-zero values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Overall (all)      - RMSE: 0.9593, MAE: 0.1387
Overall (non-zero) - RMSE: 3.8030, MAE: 1.9026  [410,105 values]
Driving Force (DF) - RMSE: 3.8537, MAE: 1.9453  [399,249 non-zero values]
Phase Fraction (NF) - RMSE: 0.4265, MAE: 0.3334  [10,856 non-zero values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Overall (all)      - RMSE: 2.2203, MAE: 0.5106
Overall (non-zero) - RMSE: 6.5258, MAE: 3.9037  [695,272 values]
Driving Force (DF) - RMSE: 6.6326, MAE: 4.0255  [673,018 non-zero values]
Phase Fraction (NF) - RMSE: 0.2979, MAE: 0.2209  [22,254 non-zero values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Overall (all)      - RMSE: 1.2880, MAE: 0.2806
Overall (non-zero) - RMSE: 2.3991, MAE: 1.6254  [240,039 values]
Driving Force (DF) - RMSE: 2.4301, MAE: 1.6624  [233,863 non-zero values]
Phase Fraction (NF) - RMSE: 0.2906, MAE: 0.2260  [6,176 non-zero values]

==================================================
Cross-Validation Summary (non-zero targets only)
==================================================
Overall (all values):
  Avg Test MSE: 2.3060 (+/- 1.3735)
  Avg RMSE: 1.4604, MAE: 0.2865

Overall (non-zero only):
  Avg RMSE: 4.6769, MAE: 2.6985

Driving Force (DF, non-zero only):
  Avg RMSE: 4.7386, MAE: 2.7634

Phase Fraction (NF, non-zero only):
  Avg RMSE: 0.3746, MAE: 0.2907

[INFO 03-11 12:28:54] ax.service.ax_client: Completed trial 30 with data: {'avg_rmse_nonzero': (np.float64(4.676868), np.float64(0.737013))}.
[INFO 03-11 12:28:54] ax.service.ax_client: Saved JSON-serialized state of optimization to `ax_client_xgb.json`.

Result: Non-zero RMSE = 4.6769

============================================================
Trial 32/100
============================================================

C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 03-11 12:28:58] ax.service.ax_client: Generated new trial 31 with parameters {'n_estimators': 138, 'max_depth': 3, 'learning_rate': 0.3, 'subsample': 0.982069, 'colsample_bytree': 0.3, 'min_child_weight': 20, 'reg_alpha': 10.0, 'reg_lambda': 1e-06, 'gamma': 5.0, 'early_stopping_rounds': 50} using model BoTorch.

Parameters: {'n_estimators': 138, 'max_depth': 3, 'learning_rate': 0.29999999999999993, 'subsample': 0.98206909287614, 'colsample_bytree': 0.3, 'min_child_weight': 20, 'reg_alpha': 10.0, 'reg_lambda': 1e-06, 'gamma': 5.0, 'early_stopping_rounds': 50}

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Overall (all)      - RMSE: 1.2734, MAE: 0.3200
Overall (non-zero) - RMSE: 4.7997, MAE: 3.0469  [509,534 values]
Driving Force (DF) - RMSE: 4.8529, MAE: 3.1075  [498,341 non-zero values]
Phase Fraction (NF) - RMSE: 0.4251, MAE: 0.3462  [11,193 non-zero values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Overall (all)      - RMSE: 1.3729, MAE: 0.2309
Overall (non-zero) - RMSE: 5.5407, MAE: 2.8746  [1,235,656 values]
Driving Force (DF) - RMSE: 5.6042, MAE: 2.9343  [1,207,679 non-zero values]
Phase Fraction (NF) - RMSE: 0.3867, MAE: 0.2963  [27,977 non-zero values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Overall (all)      - RMSE: 0.9384, MAE: 0.1896
Overall (non-zero) - RMSE: 3.6379, MAE: 1.8695  [410,105 values]
Driving Force (DF) - RMSE: 3.6864, MAE: 1.9111  [399,249 non-zero values]
Phase Fraction (NF) - RMSE: 0.4323, MAE: 0.3385  [10,856 non-zero values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Overall (all)      - RMSE: 1.9714, MAE: 0.5256
Overall (non-zero) - RMSE: 6.0751, MAE: 3.4809  [695,272 values]
Driving Force (DF) - RMSE: 6.1744, MAE: 3.5867  [673,018 non-zero values]
Phase Fraction (NF) - RMSE: 0.3597, MAE: 0.2823  [22,254 non-zero values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794

[INFO 03-11 13:36:08] ax.service.ax_client: Completed trial 31 with data: {'avg_rmse_nonzero': (np.float64(4.530591), np.float64(0.632614))}.
[INFO 03-11 13:36:08] ax.service.ax_client: Saved JSON-serialized state of optimization to `ax_client_xgb.json`.

Overall (all)      - RMSE: 1.1146, MAE: 0.3148
Overall (non-zero) - RMSE: 2.5995, MAE: 1.7878  [240,039 values]
Driving Force (DF) - RMSE: 2.6330, MAE: 1.8265  [233,863 non-zero values]
Phase Fraction (NF) - RMSE: 0.3719, MAE: 0.3220  [6,176 non-zero values]

==================================================
Cross-Validation Summary (non-zero targets only)
==================================================
Overall (all values):
  Avg Test MSE: 1.9032 (+/- 1.0484)
  Avg RMSE: 1.3341, MAE: 0.3162

Overall (non-zero only):
  Avg RMSE: 4.5306, MAE: 2.6119

Driving Force (DF, non-zero only):
  Avg RMSE: 4.5902, MAE: 2.6732

Phase Fraction (NF, non-zero only):
  Avg RMSE: 0.3951, MAE: 0.3171
Result: Non-zero RMSE = 4.5306

============================================================
Trial 33/100
============================================================

C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 03-11 13:36:11] ax.modelbridge.base: Untransformed parameter 0.004999999999999999 less than lower bound 0.005, clamping
[INFO 03-11 13:36:12] ax.service.ax_client: Generated new trial 32 with parameters {'n_estimators': 9597, 'max_depth': 100, 'learning_rate': 0.005, 'subsample': 0.5, 'colsample_bytree': 0.3, 'min_child_weight': 8, 'reg_alpha': 1e-06, 'reg_lambda': 1e-06, 'gamma': 0.0, 'early_stopping_rounds': 50} using model BoTorch.

Parameters: {'n_estimators': 9597, 'max_depth': 100, 'learning_rate': 0.005, 'subsample': 0.5, 'colsample_bytree': 0.3, 'min_child_weight': 8, 'reg_alpha': 1e-06, 'reg_lambda': 1e-06, 'gamma': 0.0, 'early_stopping_rounds': 50}

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Overall (all)      - RMSE: 1.1390, MAE: 0.3036
Overall (non-zero) - RMSE: 4.1600, MAE: 2.5670  [509,534 values]
Driving Force (DF) - RMSE: 4.2060, MAE: 2.6171  [498,341 non-zero values]
Phase Fraction (NF) - RMSE: 0.3910, MAE: 0.3342  [11,193 non-zero values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Overall (all)      - RMSE: 1.3465, MAE: 0.2198
Overall (non-zero) - RMSE: 5.5682, MAE: 2.8005  [1,235,656 values]
Driving Force (DF) - RMSE: 5.6320, MAE: 2.8578  [1,207,679 non-zero values]
Phase Fraction (NF) - RMSE: 0.4043, MAE: 0.3268  [27,977 non-zero values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Overall (all)      - RMSE: 0.7984, MAE: 0.1569
Overall (non-zero) - RMSE: 3.3342, MAE: 1.6682  [410,105 values]
Driving Force (DF) - RMSE: 3.3786, MAE: 1.7050  [399,249 non-zero values]
Phase Fraction (NF) - RMSE: 0.4106, MAE: 0.3140  [10,856 non-zero values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Overall (all)      - RMSE: 1.8593, MAE: 0.5256
Overall (non-zero) - RMSE: 5.6242, MAE: 3.2083  [695,272 values]
Driving Force (DF) - RMSE: 5.7162, MAE: 3.3065  [673,018 non-zero values]
Phase Fraction (NF) - RMSE: 0.3044, MAE: 0.2384  [22,254 non-zero values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Overall (all)      - RMSE: 0.7773, MAE: 0.2577
Overall (non-zero) - RMSE: 1.8952, MAE: 1.2692  [240,039 values]
Driving Force (DF) - RMSE: 1.9193, MAE: 1.2955  [233,863 non-zero values]
Phase Fraction (NF) - RMSE: 0.3161, MAE: 0.2750  [6,176 non-zero values]

==================================================
Cross-Validation Summary (non-zero targets only)
==================================================
Overall (all values):
  Avg Test MSE: 1.5618 (+/- 1.0485)
  Avg RMSE: 1.1841, MAE: 0.2927

Overall (non-zero only):
  Avg RMSE: 4.1164, MAE: 2.3026

Driving Force (DF, non-zero only):
  Avg RMSE: 4.1704, MAE: 2.3564

Phase Fraction (NF, non-zero only):
  Avg RMSE: 0.3653, MAE: 0.2977

[INFO 03-14 05:06:53] ax.service.ax_client: Completed trial 32 with data: {'avg_rmse_nonzero': (np.float64(4.116365), np.float64(0.704586))}.
[INFO 03-14 05:06:53] ax.service.ax_client: Saved JSON-serialized state of optimization to `ax_client_xgb.json`.

Result: Non-zero RMSE = 4.1164

============================================================
Trial 34/100
============================================================

C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 03-14 05:06:58] ax.modelbridge.base: Untransformed parameter 0.004999999999999999 less than lower bound 0.005, clamping
[INFO 03-14 05:06:58] ax.service.ax_client: Generated new trial 33 with parameters {'n_estimators': 251, 'max_depth': 3, 'learning_rate': 0.005, 'subsample': 0.5, 'colsample_bytree': 0.3, 'min_child_weight': 20, 'reg_alpha': 10.0, 'reg_lambda': 1e-06, 'gamma': 5.0, 'early_stopping_rounds': 20} using model BoTorch.

Parameters: {'n_estimators': 251, 'max_depth': 3, 'learning_rate': 0.005, 'subsample': 0.5, 'colsample_bytree': 0.3, 'min_child_weight': 20, 'reg_alpha': 10.0, 'reg_lambda': 1e-06, 'gamma': 5.0, 'early_stopping_rounds': 20}

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Overall (all)      - RMSE: 1.2501, MAE: 0.2701
Overall (non-zero) - RMSE: 5.6766, MAE: 3.2120  [509,534 values]
Driving Force (DF) - RMSE: 5.7397, MAE: 3.2758  [498,341 non-zero values]
Phase Fraction (NF) - RMSE: 0.4456, MAE: 0.3697  [11,193 non-zero values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Overall (all)      - RMSE: 1.3935, MAE: 0.2209
Overall (non-zero) - RMSE: 6.1212, MAE: 2.9536  [1,235,656 values]
Driving Force (DF) - RMSE: 6.1913, MAE: 3.0144  [1,207,679 non-zero values]
Phase Fraction (NF) - RMSE: 0.4094, MAE: 0.3288  [27,977 non-zero values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Overall (all)      - RMSE: 0.8554, MAE: 0.1707
Overall (non-zero) - RMSE: 3.7562, MAE: 1.8461  [410,105 values]
Driving Force (DF) - RMSE: 3.8062, MAE: 1.8864  [399,249 non-zero values]
Phase Fraction (NF) - RMSE: 0.4465, MAE: 0.3616  [10,856 non-zero values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Overall (all)      - RMSE: 1.5565, MAE: 0.4199
Overall (non-zero) - RMSE: 5.6315, MAE: 3.0117  [695,272 values]
Driving Force (DF) - RMSE: 5.7236, MAE: 3.1030  [673,018 non-zero values]
Phase Fraction (NF) - RMSE: 0.3205, MAE: 0.2513  [22,254 non-zero values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Overall (all)      - RMSE: 0.7082, MAE: 0.2282
Overall (non-zero) - RMSE: 2.3015, MAE: 1.6134  [240,039 values]
Driving Force (DF) - RMSE: 2.3310, MAE: 1.6476  [233,863 non-zero values]
Phase Fraction (NF) - RMSE: 0.3575, MAE: 0.3204  [6,176 non-zero values]

==================================================
Cross-Validation Summary (non-zero targets only)
==================================================
Overall (all values):
  Avg Test MSE: 1.4321 (+/- 0.7231)
  Avg RMSE: 1.1527, MAE: 0.2619

Overall (non-zero only):
  Avg RMSE: 4.6974, MAE: 2.5274

Driving Force (DF, non-zero only):
  Avg RMSE: 4.7584, MAE: 2.5854

Phase Fraction (NF, non-zero only):
  Avg RMSE: 0.3959, MAE: 0.3263

[INFO 03-14 07:41:43] ax.service.ax_client: Completed trial 33 with data: {'avg_rmse_nonzero': (np.float64(4.69741), np.float64(0.724045))}.
[INFO 03-14 07:41:43] ax.service.ax_client: Saved JSON-serialized state of optimization to `ax_client_xgb.json`.

Result: Non-zero RMSE = 4.6974

============================================================
Trial 35/100
============================================================

C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 205, 'max_depth': 3, 'learning_rate': 0.005, 'subsample': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 4, 'reg_alpha': 0.810711651143508, 'reg_lambda': 0.0008492517560534458, 'gamma': 0.0, 'early_stopping_rounds': 47}

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Overall (all)      - RMSE: 1.3070, MAE: 0.2784
Overall (non-zero) - RMSE: 5.7137, MAE: 3.2633  [509,534 values]
Driving Force (DF) - RMSE: 5.7771, MAE: 3.3282  [498,341 non-zero values]
Phase Fraction (NF) - RMSE: 0.4437, MAE: 0.3770  [11,193 non-zero values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Overall (all)      - RMSE: 1.4096, MAE: 0.2295
Overall (non-zero) - RMSE: 6.0389, MAE: 3.0853  [1,235,656 values]
Driving Force (DF) - RMSE: 6.1082, MAE: 3.1491  [1,207,679 non-zero values]
Phase Fraction (NF) - RMSE: 0.4096, MAE: 0.3285  [27,977 non-zero values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Overall (all)      - RMSE: 0.8977, MAE: 0.1721
Overall (non-zero) - RMSE: 3.7554, MAE: 1.9389  [410,105 values]
Driving Force (DF) - RMSE: 3.8054, MAE: 1.9819  [399,249 non-zero values]
Phase Fraction (NF) - RMSE: 0.4448, MAE: 0.3603  [10,856 non-zero values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Overall (all)      - RMSE: 1.7451, MAE: 0.4308
Overall (non-zero) - RMSE: 5.9348, MAE: 3.3615  [695,272 values]
Driving Force (DF) - RMSE: 6.0318, MAE: 3.4647  [673,018 non-zero values]
Phase Fraction (NF) - RMSE: 0.3110, MAE: 0.2406  [22,254 non-zero values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Overall (all)      - RMSE: 1.0212, MAE: 0.2741
Overall (non-zero) - RMSE: 2.6008, MAE: 1.8354  [240,039 values]
Driving Force (DF) - RMSE: 2.6343, MAE: 1.8753  [233,863 non-zero values]
Phase Fraction (NF) - RMSE: 0.3567, MAE: 0.3236  [6,176 non-zero values]

==================================================
Cross-Validation Summary (non-zero targets only)
==================================================
Overall (all values):
  Avg Test MSE: 1.7179 (+/- 0.7903)
  Avg RMSE: 1.2761, MAE: 0.2770

Overall (non-zero only):
  Avg RMSE: 4.8087, MAE: 2.6969

Driving Force (DF, non-zero only):
  Avg RMSE: 4.8714, MAE: 2.7598

Phase Fraction (NF, non-zero only):
  Avg RMSE: 0.3932, MAE: 0.3260

[INFO 03-14 10:21:06] ax.service.ax_client: Completed trial 34 with data: {'avg_rmse_nonzero': (np.float64(4.808711), np.float64(0.692273))}.
[INFO 03-14 10:21:06] ax.service.ax_client: Saved JSON-serialized state of optimization to `ax_client_xgb.json`.

Result: Non-zero RMSE = 4.8087

============================================================
Trial 36/100
============================================================

C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 03-14 10:21:12] ax.service.ax_client: Generated new trial 35 with parameters {'n_estimators': 9434, 'max_depth': 31, 'learning_rate': 0.027951, 'subsample': 0.963847, 'colsample_bytree': 0.3, 'min_child_weight': 18, 'reg_alpha': 1e-06, 'reg_lambda': 1e-06, 'gamma': 4.678371, 'early_stopping_rounds': 48} using model BoTorch.

Parameters: {'n_estimators': 9434, 'max_depth': 31, 'learning_rate': 0.027951005830790514, 'subsample': 0.9638468988756347, 'colsample_bytree': 0.3, 'min_child_weight': 18, 'reg_alpha': 1e-06, 'reg_lambda': 1e-06, 'gamma': 4.678371071580966, 'early_stopping_rounds': 48}

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Overall (all)      - RMSE: 1.1354, MAE: 0.2822
Overall (non-zero) - RMSE: 4.3537, MAE: 2.6309  [509,534 values]
Driving Force (DF) - RMSE: 4.4019, MAE: 2.6826  [498,341 non-zero values]
Phase Fraction (NF) - RMSE: 0.4067, MAE: 0.3272  [11,193 non-zero values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Overall (all)      - RMSE: 1.3473, MAE: 0.2184
Overall (non-zero) - RMSE: 5.5537, MAE: 2.8462  [1,235,656 values]
Driving Force (DF) - RMSE: 5.6173, MAE: 2.9047  [1,207,679 non-zero values]
Phase Fraction (NF) - RMSE: 0.4033, MAE: 0.3222  [27,977 non-zero values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Overall (all)      - RMSE: 0.8126, MAE: 0.1567
Overall (non-zero) - RMSE: 3.4129, MAE: 1.7043  [410,105 values]
Driving Force (DF) - RMSE: 3.4583, MAE: 1.7414  [399,249 non-zero values]
Phase Fraction (NF) - RMSE: 0.4283, MAE: 0.3383  [10,856 non-zero values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Overall (all)      - RMSE: 1.7879, MAE: 0.4888
Overall (non-zero) - RMSE: 5.6602, MAE: 3.1544  [695,272 values]
Driving Force (DF) - RMSE: 5.7528, MAE: 3.2507  [673,018 non-zero values]
Phase Fraction (NF) - RMSE: 0.3107, MAE: 0.2420  [22,254 non-zero values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Overall (all)      - RMSE: 0.7531, MAE: 0.2362
Overall (non-zero) - RMSE: 1.9875, MAE: 1.3364  [240,039 values]
Driving Force (DF) - RMSE: 2.0130, MAE: 1.3651  [233,863 non-zero values]
Phase Fraction (NF) - RMSE: 0.2994, MAE: 0.2529  [6,176 non-zero values]

==================================================
Cross-Validation Summary (non-zero targets only)
==================================================
Overall (all values):
  Avg Test MSE: 1.5057 (+/- 0.9589)
  Avg RMSE: 1.1673, MAE: 0.2765

Overall (non-zero only):
  Avg RMSE: 4.1936, MAE: 2.3344

Driving Force (DF, non-zero only):
  Avg RMSE: 4.2487, MAE: 2.3889

Phase Fraction (NF, non-zero only):
  Avg RMSE: 0.3697, MAE: 0.2965

[INFO 03-14 12:55:15] ax.service.ax_client: Completed trial 35 with data: {'avg_rmse_nonzero': (np.float64(4.193609), np.float64(0.689307))}.
[INFO 03-14 12:55:15] ax.service.ax_client: Saved JSON-serialized state of optimization to `ax_client_xgb.json`.

Result: Non-zero RMSE = 4.1936

============================================================
Trial 37/100
============================================================

C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 03-14 12:55:19] ax.modelbridge.base: Untransformed parameter 0.004999999999999999 less than lower bound 0.005, clamping
[INFO 03-14 12:55:19] ax.service.ax_client: Generated new trial 36 with parameters {'n_estimators': 10000, 'max_depth': 100, 'learning_rate': 0.005, 'subsample': 0.894546, 'colsample_bytree': 0.3, 'min_child_weight': 20, 'reg_alpha': 10.0, 'reg_lambda': 1e-06, 'gamma': 0.0, 'early_stopping_rounds': 50} using model BoTorch.

Parameters: {'n_estimators': 10000, 'max_depth': 100, 'learning_rate': 0.005, 'subsample': 0.8945459906465953, 'colsample_bytree': 0.3, 'min_child_weight': 20, 'reg_alpha': 10.0, 'reg_lambda': 1e-06, 'gamma': 0.0, 'early_stopping_rounds': 50}

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Overall (all)      - RMSE: 1.1198, MAE: 0.2828
Overall (non-zero) - RMSE: 4.2990, MAE: 2.6114  [509,534 values]
Driving Force (DF) - RMSE: 4.3466, MAE: 2.6623  [498,341 non-zero values]
Phase Fraction (NF) - RMSE: 0.4241, MAE: 0.3457  [11,193 non-zero values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Overall (all)      - RMSE: 1.3459, MAE: 0.2173
Overall (non-zero) - RMSE: 5.5455, MAE: 2.8231  [1,235,656 values]
Driving Force (DF) - RMSE: 5.6090, MAE: 2.8813  [1,207,679 non-zero values]
Phase Fraction (NF) - RMSE: 0.3904, MAE: 0.3110  [27,977 non-zero values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Overall (all)      - RMSE: 0.7922, MAE: 0.1524
Overall (non-zero) - RMSE: 3.3338, MAE: 1.6660  [410,105 values]
Driving Force (DF) - RMSE: 3.3781, MAE: 1.7027  [399,249 non-zero values]
Phase Fraction (NF) - RMSE: 0.4170, MAE: 0.3173  [10,856 non-zero values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Overall (all)      - RMSE: 1.7981, MAE: 0.4926
Overall (non-zero) - RMSE: 5.6523, MAE: 3.1848  [695,272 values]
Driving Force (DF) - RMSE: 5.7447, MAE: 3.2820  [673,018 non-zero values]
Phase Fraction (NF) - RMSE: 0.3133, MAE: 0.2443  [22,254 non-zero values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Overall (all)      - RMSE: 0.7324, MAE: 0.2353
Overall (non-zero) - RMSE: 1.9149, MAE: 1.2948  [240,039 values]
Driving Force (DF) - RMSE: 1.9393, MAE: 1.3220  [233,863 non-zero values]
Phase Fraction (NF) - RMSE: 0.3062, MAE: 0.2673  [6,176 non-zero values]

==================================================
Cross-Validation Summary (non-zero targets only)
==================================================
Overall (all values):
  Avg Test MSE: 1.4925 (+/- 0.9850)
  Avg RMSE: 1.1577, MAE: 0.2761

Overall (non-zero only):
  Avg RMSE: 4.1491, MAE: 2.3160

Driving Force (DF, non-zero only):
  Avg RMSE: 4.2036, MAE: 2.3701

Phase Fraction (NF, non-zero only):
  Avg RMSE: 0.3702, MAE: 0.2971

[INFO 03-16 17:48:43] ax.service.ax_client: Completed trial 36 with data: {'avg_rmse_nonzero': (np.float64(4.149097), np.float64(0.703155))}.
[INFO 03-16 17:48:43] ax.service.ax_client: Saved JSON-serialized state of optimization to `ax_client_xgb.json`.

Result: Non-zero RMSE = 4.1491

============================================================
Trial 38/100
============================================================

C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 03-16 17:48:50] ax.service.ax_client: Generated new trial 37 with parameters {'n_estimators': 10000, 'max_depth': 3, 'learning_rate': 0.3, 'subsample': 1.0, 'colsample_bytree': 0.3, 'min_child_weight': 20, 'reg_alpha': 1e-06, 'reg_lambda': 10.0, 'gamma': 0.0, 'early_stopping_rounds': 10} using model BoTorch.

Parameters: {'n_estimators': 10000, 'max_depth': 3, 'learning_rate': 0.29999999999999993, 'subsample': 1.0, 'colsample_bytree': 0.3, 'min_child_weight': 20, 'reg_alpha': 1e-06, 'reg_lambda': 10.0, 'gamma': 0.0, 'early_stopping_rounds': 10}

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Overall (all)      - RMSE: 1.3046, MAE: 0.3416
Overall (non-zero) - RMSE: 4.8775, MAE: 3.0191  [509,534 values]
Driving Force (DF) - RMSE: 4.9316, MAE: 3.0807  [498,341 non-zero values]
Phase Fraction (NF) - RMSE: 0.3597, MAE: 0.2757  [11,193 non-zero values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Overall (all)      - RMSE: 1.3972, MAE: 0.2482
Overall (non-zero) - RMSE: 5.5592, MAE: 2.9097  [1,235,656 values]
Driving Force (DF) - RMSE: 5.6229, MAE: 2.9701  [1,207,679 non-zero values]
Phase Fraction (NF) - RMSE: 0.3908, MAE: 0.3046  [27,977 non-zero values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Overall (all)      - RMSE: 0.9238, MAE: 0.2028
Overall (non-zero) - RMSE: 3.5183, MAE: 1.8508  [410,105 values]
Driving Force (DF) - RMSE: 3.5652, MAE: 1.8925  [399,249 non-zero values]
Phase Fraction (NF) - RMSE: 0.4177, MAE: 0.3165  [10,856 non-zero values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Overall (all)      - RMSE: 1.9092, MAE: 0.5277
Overall (non-zero) - RMSE: 6.1025, MAE: 3.4997  [695,272 values]
Driving Force (DF) - RMSE: 6.2023, MAE: 3.6074  [673,018 non-zero values]
Phase Fraction (NF) - RMSE: 0.3166, MAE: 0.2410  [22,254 non-zero values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Overall (all)      - RMSE: 1.1532, MAE: 0.3373
Overall (non-zero) - RMSE: 2.4551, MAE: 1.6883  [240,039 values]
Driving Force (DF) - RMSE: 2.4867, MAE: 1.7256  [233,863 non-zero values]
Phase Fraction (NF) - RMSE: 0.3437, MAE: 0.2732  [6,176 non-zero values]

==================================================
Cross-Validation Summary (non-zero targets only)
==================================================
Overall (all values):
  Avg Test MSE: 1.8965 (+/- 0.9495)
  Avg RMSE: 1.3376, MAE: 0.3315

Overall (non-zero only):
  Avg RMSE: 4.5025, MAE: 2.5935

Driving Force (DF, non-zero only):
  Avg RMSE: 4.5617, MAE: 2.6553

Phase Fraction (NF, non-zero only):
  Avg RMSE: 0.3657, MAE: 0.2822

[INFO 03-16 20:21:04] ax.service.ax_client: Completed trial 37 with data: {'avg_rmse_nonzero': (np.float64(4.502524), np.float64(0.669989))}.
[INFO 03-16 20:21:04] ax.service.ax_client: Saved JSON-serialized state of optimization to `ax_client_xgb.json`.

Result: Non-zero RMSE = 4.5025

============================================================
Trial 39/100
============================================================

C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 9453, 'max_depth': 7, 'learning_rate': 0.009981545305408745, 'subsample': 0.8685561185718842, 'colsample_bytree': 0.3, 'min_child_weight': 1, 'reg_alpha': 0.4068460840372521, 'reg_lambda': 10.0, 'gamma': 0.832834702920614, 'early_stopping_rounds': 10}

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Overall (all)      - RMSE: 1.1129, MAE: 0.2790
Overall (non-zero) - RMSE: 4.3604, MAE: 2.5646  [509,534 values]
Driving Force (DF) - RMSE: 4.4087, MAE: 2.6147  [498,341 non-zero values]
Phase Fraction (NF) - RMSE: 0.4056, MAE: 0.3341  [11,193 non-zero values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Overall (all)      - RMSE: 1.3243, MAE: 0.2129
Overall (non-zero) - RMSE: 5.5275, MAE: 2.8329  [1,235,656 values]
Driving Force (DF) - RMSE: 5.5908, MAE: 2.8911  [1,207,679 non-zero values]
Phase Fraction (NF) - RMSE: 0.3999, MAE: 0.3217  [27,977 non-zero values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Overall (all)      - RMSE: 0.7826, MAE: 0.1500
Overall (non-zero) - RMSE: 3.3075, MAE: 1.6346  [410,105 values]
Driving Force (DF) - RMSE: 3.3514, MAE: 1.6702  [399,249 non-zero values]
Phase Fraction (NF) - RMSE: 0.4227, MAE: 0.3272  [10,856 non-zero values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Overall (all)      - RMSE: 1.7229, MAE: 0.4712
Overall (non-zero) - RMSE: 5.5930, MAE: 3.0718  [695,272 values]
Driving Force (DF) - RMSE: 5.6845, MAE: 3.1657  [673,018 non-zero values]
Phase Fraction (NF) - RMSE: 0.2989, MAE: 0.2314  [22,254 non-zero values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Overall (all)      - RMSE: 0.7429, MAE: 0.2363
Overall (non-zero) - RMSE: 1.9517, MAE: 1.3097  [240,039 values]
Driving Force (DF) - RMSE: 1.9766, MAE: 1.3366  [233,863 non-zero values]
Phase Fraction (NF) - RMSE: 0.3303, MAE: 0.2911  [6,176 non-zero values]

==================================================
Cross-Validation Summary (non-zero targets only)
==================================================
Overall (all values):
  Avg Test MSE: 1.4250 (+/- 0.8885)
  Avg RMSE: 1.1371, MAE: 0.2699

Overall (non-zero only):
  Avg RMSE: 4.1480, MAE: 2.2827

Driving Force (DF, non-zero only):
  Avg RMSE: 4.2024, MAE: 2.3356

Phase Fraction (NF, non-zero only):
  Avg RMSE: 0.3715, MAE: 0.3011

[INFO 03-16 23:23:41] ax.service.ax_client: Completed trial 38 with data: {'avg_rmse_nonzero': (np.float64(4.148037), np.float64(0.691607))}.
[INFO 03-16 23:23:41] ax.service.ax_client: Saved JSON-serialized state of optimization to `ax_client_xgb.json`.

Result: Non-zero RMSE = 4.1480

============================================================
Trial 40/100
============================================================

C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 9660, 'max_depth': 43, 'learning_rate': 0.012957170994415991, 'subsample': 0.5394443941920213, 'colsample_bytree': 0.3, 'min_child_weight': 7, 'reg_alpha': 1e-06, 'reg_lambda': 10.0, 'gamma': 3.579441481143811, 'early_stopping_rounds': 50}

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Overall (all)      - RMSE: 1.1251, MAE: 0.2793
Overall (non-zero) - RMSE: 4.4507, MAE: 2.6571  [509,534 values]
Driving Force (DF) - RMSE: 4.5000, MAE: 2.7094  [498,341 non-zero values]
Phase Fraction (NF) - RMSE: 0.4130, MAE: 0.3281  [11,193 non-zero values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Overall (all)      - RMSE: 1.3398, MAE: 0.2153
Overall (non-zero) - RMSE: 5.5977, MAE: 2.8521  [1,235,656 values]
Driving Force (DF) - RMSE: 5.6619, MAE: 2.9108  [1,207,679 non-zero values]
Phase Fraction (NF) - RMSE: 0.4022, MAE: 0.3196  [27,977 non-zero values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Overall (all)      - RMSE: 0.7796, MAE: 0.1494
Overall (non-zero) - RMSE: 3.2975, MAE: 1.6416  [410,105 values]
Driving Force (DF) - RMSE: 3.3413, MAE: 1.6772  [399,249 non-zero values]
Phase Fraction (NF) - RMSE: 0.4253, MAE: 0.3320  [10,856 non-zero values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Overall (all)      - RMSE: 1.7543, MAE: 0.4786
Overall (non-zero) - RMSE: 5.6695, MAE: 3.1468  [695,272 values]
Driving Force (DF) - RMSE: 5.7622, MAE: 3.2430  [673,018 non-zero values]
Phase Fraction (NF) - RMSE: 0.3097, MAE: 0.2392  [22,254 non-zero values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Overall (all)      - RMSE: 0.7266, MAE: 0.2324
Overall (non-zero) - RMSE: 1.9596, MAE: 1.3199  [240,039 values]
Driving Force (DF) - RMSE: 1.9847, MAE: 1.3479  [233,863 non-zero values]
Phase Fraction (NF) - RMSE: 0.3036, MAE: 0.2571  [6,176 non-zero values]

==================================================
Cross-Validation Summary (non-zero targets only)
==================================================
Overall (all values):
  Avg Test MSE: 1.4548 (+/- 0.9339)
  Avg RMSE: 1.1451, MAE: 0.2710

Overall (non-zero only):
  Avg RMSE: 4.1950, MAE: 2.3235

Driving Force (DF, non-zero only):
  Avg RMSE: 4.2500, MAE: 2.3777

Phase Fraction (NF, non-zero only):
  Avg RMSE: 0.3708, MAE: 0.2952

[INFO 03-17 02:15:51] ax.service.ax_client: Completed trial 39 with data: {'avg_rmse_nonzero': (np.float64(4.195004), np.float64(0.70745))}.
[INFO 03-17 02:15:51] ax.service.ax_client: Saved JSON-serialized state of optimization to `ax_client_xgb.json`.

Result: Non-zero RMSE = 4.1950

============================================================
Trial 41/100
============================================================

C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 9619, 'max_depth': 88, 'learning_rate': 0.005, 'subsample': 0.9643046377421461, 'colsample_bytree': 0.6482810817569361, 'min_child_weight': 6, 'reg_alpha': 1e-06, 'reg_lambda': 3.760599636779563e-05, 'gamma': 1.214992432136106, 'early_stopping_rounds': 16}

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Overall (all)      - RMSE: 1.1911, MAE: 0.2802
Overall (non-zero) - RMSE: 4.1434, MAE: 2.5905  [509,534 values]
Driving Force (DF) - RMSE: 4.1893, MAE: 2.6414  [498,341 non-zero values]
Phase Fraction (NF) - RMSE: 0.3948, MAE: 0.3233  [11,193 non-zero values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Overall (all)      - RMSE: 1.4033, MAE: 0.2177
Overall (non-zero) - RMSE: 5.7055, MAE: 2.9938  [1,235,656 values]
Driving Force (DF) - RMSE: 5.7708, MAE: 3.0548  [1,207,679 non-zero values]
Phase Fraction (NF) - RMSE: 0.4479, MAE: 0.3612  [27,977 non-zero values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Overall (all)      - RMSE: 0.9393, MAE: 0.1402
Overall (non-zero) - RMSE: 3.8098, MAE: 1.7415  [410,105 values]
Driving Force (DF) - RMSE: 3.8606, MAE: 1.7801  [399,249 non-zero values]
Phase Fraction (NF) - RMSE: 0.4186, MAE: 0.3229  [10,856 non-zero values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Overall (all)      - RMSE: 2.0469, MAE: 0.5366
Overall (non-zero) - RMSE: 6.0022, MAE: 3.5763  [695,272 values]
Driving Force (DF) - RMSE: 6.1004, MAE: 3.6873  [673,018 non-zero values]
Phase Fraction (NF) - RMSE: 0.2925, MAE: 0.2174  [22,254 non-zero values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Overall (all)      - RMSE: 1.0420, MAE: 0.2642
Overall (non-zero) - RMSE: 2.1683, MAE: 1.4871  [240,039 values]
Driving Force (DF) - RMSE: 2.1963, MAE: 1.5203  [233,863 non-zero values]
Phase Fraction (NF) - RMSE: 0.2858, MAE: 0.2287  [6,176 non-zero values]

==================================================
Cross-Validation Summary (non-zero targets only)
==================================================
Overall (all values):
  Avg Test MSE: 1.9092 (+/- 1.1981)
  Avg RMSE: 1.3245, MAE: 0.2878

Overall (non-zero only):
  Avg RMSE: 4.3659, MAE: 2.4778

Driving Force (DF, non-zero only):
  Avg RMSE: 4.4235, MAE: 2.5368

Phase Fraction (NF, non-zero only):
  Avg RMSE: 0.3679, MAE: 0.2907

[INFO 03-17 07:19:09] ax.service.ax_client: Completed trial 40 with data: {'avg_rmse_nonzero': (np.float64(4.36585), np.float64(0.695))}.
[INFO 03-17 07:19:09] ax.service.ax_client: Saved JSON-serialized state of optimization to `ax_client_xgb.json`.

Result: Non-zero RMSE = 4.3659

============================================================
Trial 42/100
============================================================

C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 3282, 'max_depth': 22, 'learning_rate': 0.005, 'subsample': 0.78201895849602, 'colsample_bytree': 0.3, 'min_child_weight': 20, 'reg_alpha': 4.846849432071761e-05, 'reg_lambda': 1e-06, 'gamma': 0.0, 'early_stopping_rounds': 50}

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Overall (all)      - RMSE: 1.1416, MAE: 0.3009
Overall (non-zero) - RMSE: 4.1909, MAE: 2.5689  [509,534 values]
Driving Force (DF) - RMSE: 4.2372, MAE: 2.6191  [498,341 non-zero values]
Phase Fraction (NF) - RMSE: 0.3944, MAE: 0.3315  [11,193 non-zero values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Overall (all)      - RMSE: 1.3473, MAE: 0.2195
Overall (non-zero) - RMSE: 5.5646, MAE: 2.8064  [1,235,656 values]
Driving Force (DF) - RMSE: 5.6284, MAE: 2.8642  [1,207,679 non-zero values]
Phase Fraction (NF) - RMSE: 0.3911, MAE: 0.3138  [27,977 non-zero values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Overall (all)      - RMSE: 0.8034, MAE: 0.1587
Overall (non-zero) - RMSE: 3.3478, MAE: 1.6790  [410,105 values]
Driving Force (DF) - RMSE: 3.3923, MAE: 1.7162  [399,249 non-zero values]
Phase Fraction (NF) - RMSE: 0.4105, MAE: 0.3116  [10,856 non-zero values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Overall (all)      - RMSE: 1.8501, MAE: 0.5255
Overall (non-zero) - RMSE: 5.6502, MAE: 3.2402  [695,272 values]
Driving Force (DF) - RMSE: 5.7426, MAE: 3.3398  [673,018 non-zero values]
Phase Fraction (NF) - RMSE: 0.2967, MAE: 0.2288  [22,254 non-zero values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Overall (all)      - RMSE: 0.7721, MAE: 0.2536
Overall (non-zero) - RMSE: 1.9026, MAE: 1.2693  [240,039 values]
Driving Force (DF) - RMSE: 1.9268, MAE: 1.2955  [233,863 non-zero values]
Phase Fraction (NF) - RMSE: 0.3222, MAE: 0.2778  [6,176 non-zero values]

==================================================
Cross-Validation Summary (non-zero targets only)
==================================================
Overall (all values):
  Avg Test MSE: 1.5566 (+/- 1.0360)
  Avg RMSE: 1.1829, MAE: 0.2916

Overall (non-zero only):
  Avg RMSE: 4.1312, MAE: 2.3128

Driving Force (DF, non-zero only):
  Avg RMSE: 4.1855, MAE: 2.3669

Phase Fraction (NF, non-zero only):
  Avg RMSE: 0.3630, MAE: 0.2927

[INFO 03-18 12:34:27] ax.service.ax_client: Completed trial 41 with data: {'avg_rmse_nonzero': (np.float64(4.131198), np.float64(0.70519))}.
[INFO 03-18 12:34:27] ax.service.ax_client: Saved JSON-serialized state of optimization to `ax_client_xgb.json`.

Result: Non-zero RMSE = 4.1312

============================================================
Trial 43/100
============================================================

C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 03-18 12:34:30] ax.service.ax_client: Generated new trial 42 with parameters {'n_estimators': 10000, 'max_depth': 100, 'learning_rate': 0.3, 'subsample': 0.654119, 'colsample_bytree': 0.3, 'min_child_weight': 20, 'reg_alpha': 1e-06, 'reg_lambda': 10.0, 'gamma': 5.0, 'early_stopping_rounds': 50} using model BoTorch.

Parameters: {'n_estimators': 10000, 'max_depth': 100, 'learning_rate': 0.29999999999999993, 'subsample': 0.654118653954003, 'colsample_bytree': 0.3, 'min_child_weight': 20, 'reg_alpha': 1e-06, 'reg_lambda': 10.0, 'gamma': 5.0, 'early_stopping_rounds': 50}

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Overall (all)      - RMSE: 1.2257, MAE: 0.3009
Overall (non-zero) - RMSE: 4.4425, MAE: 2.7581  [509,534 values]
Driving Force (DF) - RMSE: 4.4916, MAE: 2.8118  [498,341 non-zero values]
Phase Fraction (NF) - RMSE: 0.4578, MAE: 0.3702  [11,193 non-zero values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Overall (all)      - RMSE: 1.3912, MAE: 0.2330
Overall (non-zero) - RMSE: 5.5273, MAE: 2.9051  [1,235,656 values]
Driving Force (DF) - RMSE: 5.5906, MAE: 2.9654  [1,207,679 non-zero values]
Phase Fraction (NF) - RMSE: 0.3932, MAE: 0.3031  [27,977 non-zero values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Overall (all)      - RMSE: 0.9111, MAE: 0.1810
Overall (non-zero) - RMSE: 3.5746, MAE: 1.8635  [410,105 values]
Driving Force (DF) - RMSE: 3.6222, MAE: 1.9048  [399,249 non-zero values]
Phase Fraction (NF) - RMSE: 0.4409, MAE: 0.3426  [10,856 non-zero values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Overall (all)      - RMSE: 1.8636, MAE: 0.5091
Overall (non-zero) - RMSE: 6.0839, MAE: 3.3461  [695,272 values]
Driving Force (DF) - RMSE: 6.1834, MAE: 3.4493  [673,018 non-zero values]
Phase Fraction (NF) - RMSE: 0.2962, MAE: 0.2259  [22,254 non-zero values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Overall (all)      - RMSE: 0.9921, MAE: 0.2730
Overall (non-zero) - RMSE: 2.4742, MAE: 1.7247  [240,039 values]
Driving Force (DF) - RMSE: 2.5060, MAE: 1.7623  [233,863 non-zero values]
Phase Fraction (NF) - RMSE: 0.3560, MAE: 0.3027  [6,176 non-zero values]

==================================================
Cross-Validation Summary (non-zero targets only)
==================================================
Overall (all values):
  Avg Test MSE: 1.7451 (+/- 0.9484)
  Avg RMSE: 1.2768, MAE: 0.2994

Overall (non-zero only):
  Avg RMSE: 4.4205, MAE: 2.5195

Driving Force (DF, non-zero only):
  Avg RMSE: 4.4787, MAE: 2.5787

Phase Fraction (NF, non-zero only):
  Avg RMSE: 0.3888, MAE: 0.3089

[INFO 03-18 13:49:52] ax.service.ax_client: Completed trial 42 with data: {'avg_rmse_nonzero': (np.float64(4.420479), np.float64(0.651757))}.
[INFO 03-18 13:49:53] ax.service.ax_client: Saved JSON-serialized state of optimization to `ax_client_xgb.json`.

Result: Non-zero RMSE = 4.4205

============================================================
Trial 44/100
============================================================

C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 488, 'max_depth': 100, 'learning_rate': 0.29999999999999993, 'subsample': 0.6651181354449768, 'colsample_bytree': 0.3, 'min_child_weight': 11, 'reg_alpha': 1e-06, 'reg_lambda': 0.0014910347292022893, 'gamma': 4.630079565747022, 'early_stopping_rounds': 10}

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Overall (all)      - RMSE: 1.2442, MAE: 0.2966
Overall (non-zero) - RMSE: 4.5503, MAE: 2.7976  [509,534 values]
Driving Force (DF) - RMSE: 4.6006, MAE: 2.8524  [498,341 non-zero values]
Phase Fraction (NF) - RMSE: 0.4449, MAE: 0.3560  [11,193 non-zero values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Overall (all)      - RMSE: 1.4247, MAE: 0.2378
Overall (non-zero) - RMSE: 5.5243, MAE: 2.8623  [1,235,656 values]
Driving Force (DF) - RMSE: 5.5876, MAE: 2.9216  [1,207,679 non-zero values]
Phase Fraction (NF) - RMSE: 0.3986, MAE: 0.3027  [27,977 non-zero values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Overall (all)      - RMSE: 0.9851, MAE: 0.1830
Overall (non-zero) - RMSE: 3.9201, MAE: 1.9285  [410,105 values]
Driving Force (DF) - RMSE: 3.9724, MAE: 1.9719  [399,249 non-zero values]
Phase Fraction (NF) - RMSE: 0.4322, MAE: 0.3347  [10,856 non-zero values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Overall (all)      - RMSE: 1.9355, MAE: 0.5131
Overall (non-zero) - RMSE: 5.9218, MAE: 3.2776  [695,272 values]
Driving Force (DF) - RMSE: 6.0186, MAE: 3.3780  [673,018 non-zero values]
Phase Fraction (NF) - RMSE: 0.3195, MAE: 0.2439  [22,254 non-zero values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Overall (all)      - RMSE: 0.9921, MAE: 0.2625
Overall (non-zero) - RMSE: 2.4581, MAE: 1.7223  [240,039 values]
Driving Force (DF) - RMSE: 2.4898, MAE: 1.7607  [233,863 non-zero values]
Phase Fraction (NF) - RMSE: 0.3234, MAE: 0.2670  [6,176 non-zero values]

==================================================
Cross-Validation Summary (non-zero targets only)
==================================================
Overall (all values):
  Avg Test MSE: 1.8557 (+/- 1.0238)
  Avg RMSE: 1.3163, MAE: 0.2986

Overall (non-zero only):
  Avg RMSE: 4.4749, MAE: 2.5177

Driving Force (DF, non-zero only):
  Avg RMSE: 4.5338, MAE: 2.5769

Phase Fraction (NF, non-zero only):
  Avg RMSE: 0.3837, MAE: 0.3009

[INFO 03-18 14:53:39] ax.service.ax_client: Completed trial 43 with data: {'avg_rmse_nonzero': (np.float64(4.474912), np.float64(0.615458))}.
[INFO 03-18 14:53:39] ax.service.ax_client: Saved JSON-serialized state of optimization to `ax_client_xgb.json`.

Result: Non-zero RMSE = 4.4749

============================================================
Trial 45/100
============================================================

C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 9737, 'max_depth': 100, 'learning_rate': 0.005, 'subsample': 0.6552133013332112, 'colsample_bytree': 0.39069865803619247, 'min_child_weight': 5, 'reg_alpha': 1e-06, 'reg_lambda': 4.0545254600039735, 'gamma': 0.4126215756204006, 'early_stopping_rounds': 39}

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Overall (all)      - RMSE: 1.1340, MAE: 0.2902
Overall (non-zero) - RMSE: 4.2168, MAE: 2.5717  [509,534 values]
Driving Force (DF) - RMSE: 4.2634, MAE: 2.6220  [498,341 non-zero values]
Phase Fraction (NF) - RMSE: 0.3986, MAE: 0.3337  [11,193 non-zero values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Overall (all)      - RMSE: 1.3403, MAE: 0.2143
Overall (non-zero) - RMSE: 5.5749, MAE: 2.8575  [1,235,656 values]
Driving Force (DF) - RMSE: 5.6387, MAE: 2.9158  [1,207,679 non-zero values]
Phase Fraction (NF) - RMSE: 0.4183, MAE: 0.3384  [27,977 non-zero values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Overall (all)      - RMSE: 0.8044, MAE: 0.1472
Overall (non-zero) - RMSE: 3.3785, MAE: 1.6542  [410,105 values]
Driving Force (DF) - RMSE: 3.4234, MAE: 1.6904  [399,249 non-zero values]
Phase Fraction (NF) - RMSE: 0.4185, MAE: 0.3245  [10,856 non-zero values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Overall (all)      - RMSE: 1.8291, MAE: 0.5095
Overall (non-zero) - RMSE: 5.6584, MAE: 3.2276  [695,272 values]
Driving Force (DF) - RMSE: 5.7509, MAE: 3.3265  [673,018 non-zero values]
Phase Fraction (NF) - RMSE: 0.3057, MAE: 0.2376  [22,254 non-zero values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Overall (all)      - RMSE: 0.7831, MAE: 0.2455
Overall (non-zero) - RMSE: 1.9131, MAE: 1.2888  [240,039 values]
Driving Force (DF) - RMSE: 1.9376, MAE: 1.3157  [233,863 non-zero values]
Phase Fraction (NF) - RMSE: 0.3131, MAE: 0.2695  [6,176 non-zero values]

==================================================
Cross-Validation Summary (non-zero targets only)
==================================================
Overall (all values):
  Avg Test MSE: 1.5376 (+/- 1.0046)
  Avg RMSE: 1.1782, MAE: 0.2813

Overall (non-zero only):
  Avg RMSE: 4.1483, MAE: 2.3200

Driving Force (DF, non-zero only):
  Avg RMSE: 4.2028, MAE: 2.3741

Phase Fraction (NF, non-zero only):
  Avg RMSE: 0.3708, MAE: 0.3007

[INFO 03-19 00:00:55] ax.service.ax_client: Completed trial 44 with data: {'avg_rmse_nonzero': (np.float64(4.148326), np.float64(0.703871))}.
[INFO 03-19 00:00:55] ax.service.ax_client: Saved JSON-serialized state of optimization to `ax_client_xgb.json`.

Result: Non-zero RMSE = 4.1483

============================================================
Trial 46/100
============================================================

C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 9149, 'max_depth': 37, 'learning_rate': 0.005, 'subsample': 0.5, 'colsample_bytree': 0.3, 'min_child_weight': 19, 'reg_alpha': 1e-06, 'reg_lambda': 10.0, 'gamma': 0.7351795972335836, 'early_stopping_rounds': 50}

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Overall (all)      - RMSE: 1.1278, MAE: 0.2901
Overall (non-zero) - RMSE: 4.3495, MAE: 2.6098  [509,534 values]
Driving Force (DF) - RMSE: 4.3977, MAE: 2.6608  [498,341 non-zero values]
Phase Fraction (NF) - RMSE: 0.4068, MAE: 0.3365  [11,193 non-zero values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Overall (all)      - RMSE: 1.3450, MAE: 0.2155
Overall (non-zero) - RMSE: 5.5949, MAE: 2.7950  [1,235,656 values]
Driving Force (DF) - RMSE: 5.6590, MAE: 2.8525  [1,207,679 non-zero values]
Phase Fraction (NF) - RMSE: 0.3950, MAE: 0.3156  [27,977 non-zero values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Overall (all)      - RMSE: 0.7744, MAE: 0.1518
Overall (non-zero) - RMSE: 3.2438, MAE: 1.6217  [410,105 values]
Driving Force (DF) - RMSE: 3.2869, MAE: 1.6569  [399,249 non-zero values]
Phase Fraction (NF) - RMSE: 0.4213, MAE: 0.3265  [10,856 non-zero values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Overall (all)      - RMSE: 1.7895, MAE: 0.5021
Overall (non-zero) - RMSE: 5.6404, MAE: 3.2123  [695,272 values]
Driving Force (DF) - RMSE: 5.7326, MAE: 3.3106  [673,018 non-zero values]
Phase Fraction (NF) - RMSE: 0.3093, MAE: 0.2401  [22,254 non-zero values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Overall (all)      - RMSE: 0.7666, MAE: 0.2482
Overall (non-zero) - RMSE: 1.9245, MAE: 1.2804  [240,039 values]
Driving Force (DF) - RMSE: 1.9491, MAE: 1.3072  [233,863 non-zero values]
Phase Fraction (NF) - RMSE: 0.3111, MAE: 0.2678  [6,176 non-zero values]

==================================================
Cross-Validation Summary (non-zero targets only)
==================================================
Overall (all values):
  Avg Test MSE: 1.4941 (+/- 0.9683)
  Avg RMSE: 1.1607, MAE: 0.2815

Overall (non-zero only):
  Avg RMSE: 4.1506, MAE: 2.3038

Driving Force (DF, non-zero only):
  Avg RMSE: 4.2051, MAE: 2.3576

Phase Fraction (NF, non-zero only):
  Avg RMSE: 0.3687, MAE: 0.2973

[INFO 03-19 12:23:04] ax.service.ax_client: Completed trial 45 with data: {'avg_rmse_nonzero': (np.float64(4.150635), np.float64(0.711444))}.
[INFO 03-19 12:23:04] ax.service.ax_client: Saved JSON-serialized state of optimization to `ax_client_xgb.json`.

Result: Non-zero RMSE = 4.1506

============================================================
Trial 47/100
============================================================

C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 9376, 'max_depth': 25, 'learning_rate': 0.005, 'subsample': 0.955518576668819, 'colsample_bytree': 0.3, 'min_child_weight': 20, 'reg_alpha': 1e-06, 'reg_lambda': 10.0, 'gamma': 0.0, 'early_stopping_rounds': 24}

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Overall (all)      - RMSE: 1.1348, MAE: 0.2936
Overall (non-zero) - RMSE: 4.2824, MAE: 2.5795  [509,534 values]
Driving Force (DF) - RMSE: 4.3298, MAE: 2.6298  [498,341 non-zero values]
Phase Fraction (NF) - RMSE: 0.4041, MAE: 0.3389  [11,193 non-zero values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Overall (all)      - RMSE: 1.3451, MAE: 0.2174
Overall (non-zero) - RMSE: 5.5510, MAE: 2.8120  [1,235,656 values]
Driving Force (DF) - RMSE: 5.6146, MAE: 2.8698  [1,207,679 non-zero values]
Phase Fraction (NF) - RMSE: 0.3957, MAE: 0.3177  [27,977 non-zero values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Overall (all)      - RMSE: 0.7890, MAE: 0.1547
Overall (non-zero) - RMSE: 3.3000, MAE: 1.6417  [410,105 values]
Driving Force (DF) - RMSE: 3.3438, MAE: 1.6778  [399,249 non-zero values]
Phase Fraction (NF) - RMSE: 0.4123, MAE: 0.3136  [10,856 non-zero values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Overall (all)      - RMSE: 1.7947, MAE: 0.5028
Overall (non-zero) - RMSE: 5.6659, MAE: 3.2015  [695,272 values]
Driving Force (DF) - RMSE: 5.7585, MAE: 3.2999  [673,018 non-zero values]
Phase Fraction (NF) - RMSE: 0.2937, MAE: 0.2249  [22,254 non-zero values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Overall (all)      - RMSE: 0.7473, MAE: 0.2435
Overall (non-zero) - RMSE: 1.9095, MAE: 1.2832  [240,039 values]
Driving Force (DF) - RMSE: 1.9339, MAE: 1.3099  [233,863 non-zero values]
Phase Fraction (NF) - RMSE: 0.3153, MAE: 0.2710  [6,176 non-zero values]

==================================================
Cross-Validation Summary (non-zero targets only)
==================================================
Overall (all values):
  Avg Test MSE: 1.4998 (+/- 0.9756)
  Avg RMSE: 1.1622, MAE: 0.2824

Overall (non-zero only):
  Avg RMSE: 4.1417, MAE: 2.3036

Driving Force (DF, non-zero only):
  Avg RMSE: 4.1961, MAE: 2.3575

Phase Fraction (NF, non-zero only):
  Avg RMSE: 0.3642, MAE: 0.2932

[INFO 03-22 02:20:22] ax.service.ax_client: Completed trial 46 with data: {'avg_rmse_nonzero': (np.float64(4.141748), np.float64(0.707816))}.
[INFO 03-22 02:20:22] ax.service.ax_client: Saved JSON-serialized state of optimization to `ax_client_xgb.json`.

Result: Non-zero RMSE = 4.1417

============================================================
Trial 48/100
============================================================

C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 03-22 02:20:27] ax.modelbridge.base: Untransformed parameter 0.004999999999999999 less than lower bound 0.005, clamping
[INFO 03-22 02:20:28] ax.service.ax_client: Generated new trial 47 with parameters {'n_estimators': 100, 'max_depth': 100, 'learning_rate': 0.005, 'subsample': 0.5, 'colsample_bytree': 0.3, 'min_child_weight': 2, 'reg_alpha': 1e-06, 'reg_lambda': 10.0, 'gamma': 0.0, 'early_stopping_rounds': 27} using model BoTorch.

Parameters: {'n_estimators': 100, 'max_depth': 100, 'learning_rate': 0.005, 'subsample': 0.5, 'colsample_bytree': 0.3, 'min_child_weight': 2, 'reg_alpha': 1e-06, 'reg_lambda': 10.0, 'gamma': 0.0, 'early_stopping_rounds': 27}

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Overall (all)      - RMSE: 1.3341, MAE: 0.2699
Overall (non-zero) - RMSE: 6.2920, MAE: 3.6780  [509,534 values]
Driving Force (DF) - RMSE: 6.3619, MAE: 3.7518  [498,341 non-zero values]
Phase Fraction (NF) - RMSE: 0.4585, MAE: 0.3905  [11,193 non-zero values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Overall (all)      - RMSE: 1.4650, MAE: 0.2345
Overall (non-zero) - RMSE: 6.5054, MAE: 3.1386  [1,235,656 values]
Driving Force (DF) - RMSE: 6.5800, MAE: 3.2037  [1,207,679 non-zero values]
Phase Fraction (NF) - RMSE: 0.4084, MAE: 0.3306  [27,977 non-zero values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Overall (all)      - RMSE: 0.9053, MAE: 0.1869
Overall (non-zero) - RMSE: 4.0295, MAE: 1.9740  [410,105 values]
Driving Force (DF) - RMSE: 4.0833, MAE: 2.0177  [399,249 non-zero values]
Phase Fraction (NF) - RMSE: 0.4475, MAE: 0.3654  [10,856 non-zero values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Overall (all)      - RMSE: 1.4046, MAE: 0.3186
Overall (non-zero) - RMSE: 5.9868, MAE: 2.9417  [695,272 values]
Driving Force (DF) - RMSE: 6.0847, MAE: 3.0305  [673,018 non-zero values]
Phase Fraction (NF) - RMSE: 0.3245, MAE: 0.2567  [22,254 non-zero values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Overall (all)      - RMSE: 0.6715, MAE: 0.2133
Overall (non-zero) - RMSE: 2.6476, MAE: 1.9023  [240,039 values]
Driving Force (DF) - RMSE: 2.6816, MAE: 1.9431  [233,863 non-zero values]
Phase Fraction (NF) - RMSE: 0.3800, MAE: 0.3560  [6,176 non-zero values]

==================================================
Cross-Validation Summary (non-zero targets only)
==================================================
Overall (all values):
  Avg Test MSE: 1.4339 (+/- 0.6725)
  Avg RMSE: 1.1561, MAE: 0.2446

Overall (non-zero only):
  Avg RMSE: 5.0923, MAE: 2.7269

Driving Force (DF, non-zero only):
  Avg RMSE: 5.1583, MAE: 2.7893

Phase Fraction (NF, non-zero only):
  Avg RMSE: 0.4038, MAE: 0.3399

[INFO 03-22 03:46:39] ax.service.ax_client: Completed trial 47 with data: {'avg_rmse_nonzero': (np.float64(5.092256), np.float64(0.753074))}.
[INFO 03-22 03:46:39] ax.service.ax_client: Saved JSON-serialized state of optimization to `ax_client_xgb.json`.

Result: Non-zero RMSE = 5.0923

============================================================
Trial 49/100
============================================================

C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 03-22 03:46:44] ax.modelbridge.base: Untransformed parameter 0.004999999999999999 less than lower bound 0.005, clamping
[INFO 03-22 03:46:44] ax.service.ax_client: Generated new trial 48 with parameters {'n_estimators': 6581, 'max_depth': 58, 'learning_rate': 0.005, 'subsample': 1.0, 'colsample_bytree': 0.3, 'min_child_weight': 17, 'reg_alpha': 10.0, 'reg_lambda': 10.0, 'gamma': 5.0, 'early_stopping_rounds': 10} using model BoTorch.

Parameters: {'n_estimators': 6581, 'max_depth': 58, 'learning_rate': 0.005, 'subsample': 1.0, 'colsample_bytree': 0.3, 'min_child_weight': 17, 'reg_alpha': 10.0, 'reg_lambda': 10.0, 'gamma': 5.0, 'early_stopping_rounds': 10}

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Overall (all)      - RMSE: 1.1185, MAE: 0.2663
Overall (non-zero) - RMSE: 4.5847, MAE: 2.7091  [509,534 values]
Driving Force (DF) - RMSE: 4.6354, MAE: 2.7625  [498,341 non-zero values]
Phase Fraction (NF) - RMSE: 0.4244, MAE: 0.3321  [11,193 non-zero values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Overall (all)      - RMSE: 1.3470, MAE: 0.2124
Overall (non-zero) - RMSE: 5.6269, MAE: 2.8326  [1,235,656 values]
Driving Force (DF) - RMSE: 5.6914, MAE: 2.8910  [1,207,679 non-zero values]
Phase Fraction (NF) - RMSE: 0.3978, MAE: 0.3140  [27,977 non-zero values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Overall (all)      - RMSE: 0.7909, MAE: 0.1463
Overall (non-zero) - RMSE: 3.3847, MAE: 1.6691  [410,105 values]
Driving Force (DF) - RMSE: 3.4297, MAE: 1.7054  [399,249 non-zero values]
Phase Fraction (NF) - RMSE: 0.4267, MAE: 0.3326  [10,856 non-zero values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Overall (all)      - RMSE: 1.7340, MAE: 0.4664
Overall (non-zero) - RMSE: 5.6882, MAE: 3.1691  [695,272 values]
Driving Force (DF) - RMSE: 5.7812, MAE: 3.2661  [673,018 non-zero values]
Phase Fraction (NF) - RMSE: 0.3053, MAE: 0.2346  [22,254 non-zero values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Overall (all)      - RMSE: 0.7071, MAE: 0.2189
Overall (non-zero) - RMSE: 1.9980, MAE: 1.3490  [240,039 values]
Driving Force (DF) - RMSE: 2.0236, MAE: 1.3780  [233,863 non-zero values]
Phase Fraction (NF) - RMSE: 0.3011, MAE: 0.2502  [6,176 non-zero values]

==================================================
Cross-Validation Summary (non-zero targets only)
==================================================
Overall (all values):
  Avg Test MSE: 1.4395 (+/- 0.9140)
  Avg RMSE: 1.1395, MAE: 0.2621

Overall (non-zero only):
  Avg RMSE: 4.2565, MAE: 2.3458

Driving Force (DF, non-zero only):
  Avg RMSE: 4.3123, MAE: 2.4006

Phase Fraction (NF, non-zero only):
  Avg RMSE: 0.3711, MAE: 0.2927

[INFO 03-22 07:20:40] ax.service.ax_client: Completed trial 48 with data: {'avg_rmse_nonzero': (np.float64(4.256489), np.float64(0.703421))}.
[INFO 03-22 07:20:40] ax.service.ax_client: Saved JSON-serialized state of optimization to `ax_client_xgb.json`.

Result: Non-zero RMSE = 4.2565

============================================================
Trial 50/100
============================================================

C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 10000, 'max_depth': 100, 'learning_rate': 0.21296828110387153, 'subsample': 0.5, 'colsample_bytree': 0.957618199092572, 'min_child_weight': 20, 'reg_alpha': 1e-06, 'reg_lambda': 1e-06, 'gamma': 5.0, 'early_stopping_rounds': 10}

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Overall (all)      - RMSE: 1.3454, MAE: 0.3164
Overall (non-zero) - RMSE: 4.6515, MAE: 2.9599  [509,534 values]
Driving Force (DF) - RMSE: 4.7031, MAE: 3.0186  [498,341 non-zero values]
Phase Fraction (NF) - RMSE: 0.4303, MAE: 0.3472  [11,193 non-zero values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Overall (all)      - RMSE: 1.4724, MAE: 0.2252
Overall (non-zero) - RMSE: 5.9499, MAE: 3.1679  [1,235,656 values]
Driving Force (DF) - RMSE: 6.0181, MAE: 3.2338  [1,207,679 non-zero values]
Phase Fraction (NF) - RMSE: 0.4167, MAE: 0.3237  [27,977 non-zero values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Overall (all)      - RMSE: 0.9678, MAE: 0.1556
Overall (non-zero) - RMSE: 3.6389, MAE: 1.8664  [410,105 values]
Driving Force (DF) - RMSE: 3.6874, MAE: 1.9082  [399,249 non-zero values]
Phase Fraction (NF) - RMSE: 0.4230, MAE: 0.3268  [10,856 non-zero values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Overall (all)      - RMSE: 2.2901, MAE: 0.5977
Overall (non-zero) - RMSE: 6.5281, MAE: 4.0852  [695,272 values]
Driving Force (DF) - RMSE: 6.6350, MAE: 4.2132  [673,018 non-zero values]
Phase Fraction (NF) - RMSE: 0.2952, MAE: 0.2147  [22,254 non-zero values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Overall (all)      - RMSE: 1.3127, MAE: 0.3311
Overall (non-zero) - RMSE: 2.4303, MAE: 1.6857  [240,039 values]
Driving Force (DF) - RMSE: 2.4618, MAE: 1.7239  [233,863 non-zero values]
Phase Fraction (NF) - RMSE: 0.2937, MAE: 0.2378  [6,176 non-zero values]

==================================================
Cross-Validation Summary (non-zero targets only)
==================================================
Overall (all values):
  Avg Test MSE: 2.3765 (+/- 1.4892)
  Avg RMSE: 1.4777, MAE: 0.3252

Overall (non-zero only):
  Avg RMSE: 4.6398, MAE: 2.7530

Driving Force (DF, non-zero only):
  Avg RMSE: 4.7010, MAE: 2.8195

Phase Fraction (NF, non-zero only):
  Avg RMSE: 0.3718, MAE: 0.2900

[INFO 03-22 09:10:10] ax.service.ax_client: Completed trial 49 with data: {'avg_rmse_nonzero': (np.float64(4.639756), np.float64(0.747186))}.
[INFO 03-22 09:10:10] ax.service.ax_client: Saved JSON-serialized state of optimization to `ax_client_xgb.json`.

Result: Non-zero RMSE = 4.6398

============================================================
Trial 51/100
============================================================

C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 9420, 'max_depth': 3, 'learning_rate': 0.005, 'subsample': 0.6321241451316487, 'colsample_bytree': 0.3, 'min_child_weight': 17, 'reg_alpha': 10.0, 'reg_lambda': 0.00016036981719125902, 'gamma': 3.475615202808982, 'early_stopping_rounds': 50}

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Overall (all)      - RMSE: 1.1886, MAE: 0.3003
Overall (non-zero) - RMSE: 4.5484, MAE: 2.9136  [509,534 values]
Driving Force (DF) - RMSE: 4.5988, MAE: 2.9717  [498,341 non-zero values]
Phase Fraction (NF) - RMSE: 0.4148, MAE: 0.3267  [11,193 non-zero values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Overall (all)      - RMSE: 1.3292, MAE: 0.2128
Overall (non-zero) - RMSE: 5.4977, MAE: 2.7201  [1,235,656 values]
Driving Force (DF) - RMSE: 5.5607, MAE: 2.7758  [1,207,679 non-zero values]
Phase Fraction (NF) - RMSE: 0.4013, MAE: 0.3150  [27,977 non-zero values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Overall (all)      - RMSE: 0.8004, MAE: 0.1542
Overall (non-zero) - RMSE: 3.3363, MAE: 1.6892  [410,105 values]
Driving Force (DF) - RMSE: 3.3806, MAE: 1.7260  [399,249 non-zero values]
Phase Fraction (NF) - RMSE: 0.4281, MAE: 0.3330  [10,856 non-zero values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Overall (all)      - RMSE: 1.9726, MAE: 0.5311
Overall (non-zero) - RMSE: 6.0582, MAE: 3.5388  [695,272 values]
Driving Force (DF) - RMSE: 6.1573, MAE: 3.6474  [673,018 non-zero values]
Phase Fraction (NF) - RMSE: 0.3248, MAE: 0.2538  [22,254 non-zero values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Overall (all)      - RMSE: 0.9590, MAE: 0.2862
Overall (non-zero) - RMSE: 2.1159, MAE: 1.4116  [240,039 values]
Driving Force (DF) - RMSE: 2.1431, MAE: 1.4421  [233,863 non-zero values]
Phase Fraction (NF) - RMSE: 0.3142, MAE: 0.2563  [6,176 non-zero values]

==================================================
Cross-Validation Summary (non-zero targets only)
==================================================
Overall (all values):
  Avg Test MSE: 1.7262 (+/- 1.1503)
  Avg RMSE: 1.2500, MAE: 0.2969

Overall (non-zero only):
  Avg RMSE: 4.3113, MAE: 2.4546

Driving Force (DF, non-zero only):
  Avg RMSE: 4.3681, MAE: 2.5126

Phase Fraction (NF, non-zero only):
  Avg RMSE: 0.3766, MAE: 0.2970

[INFO 03-22 16:03:51] ax.service.ax_client: Completed trial 50 with data: {'avg_rmse_nonzero': (np.float64(4.311326), np.float64(0.717136))}.
[INFO 03-22 16:03:51] ax.service.ax_client: Saved JSON-serialized state of optimization to `ax_client_xgb.json`.

Result: Non-zero RMSE = 4.3113

============================================================
Trial 52/100
============================================================

C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 03-22 16:03:57] ax.modelbridge.base: Untransformed parameter 0.004999999999999999 less than lower bound 0.005, clamping
[INFO 03-22 16:03:57] ax.service.ax_client: Generated new trial 51 with parameters {'n_estimators': 7373, 'max_depth': 3, 'learning_rate': 0.005, 'subsample': 0.504278, 'colsample_bytree': 0.311947, 'min_child_weight': 12, 'reg_alpha': 1e-06, 'reg_lambda': 1e-06, 'gamma': 0.422052, 'early_stopping_rounds': 13} using model BoTorch.

Parameters: {'n_estimators': 7373, 'max_depth': 3, 'learning_rate': 0.005, 'subsample': 0.5042779982806191, 'colsample_bytree': 0.31194745732264606, 'min_child_weight': 12, 'reg_alpha': 1e-06, 'reg_lambda': 1e-06, 'gamma': 0.42205213355076926, 'early_stopping_rounds': 13}

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Overall (all)      - RMSE: 1.2276, MAE: 0.3240
Overall (non-zero) - RMSE: 4.5950, MAE: 3.0002  [509,534 values]
Driving Force (DF) - RMSE: 4.6460, MAE: 3.0613  [498,341 non-zero values]
Phase Fraction (NF) - RMSE: 0.3566, MAE: 0.2797  [11,193 non-zero values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Overall (all)      - RMSE: 1.3392, MAE: 0.2180
Overall (non-zero) - RMSE: 5.5837, MAE: 2.7502  [1,235,656 values]
Driving Force (DF) - RMSE: 5.6477, MAE: 2.8068  [1,207,679 non-zero values]
Phase Fraction (NF) - RMSE: 0.3890, MAE: 0.3040  [27,977 non-zero values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Overall (all)      - RMSE: 0.8046, MAE: 0.1567
Overall (non-zero) - RMSE: 3.3496, MAE: 1.6812  [410,105 values]
Driving Force (DF) - RMSE: 3.3941, MAE: 1.7182  [399,249 non-zero values]
Phase Fraction (NF) - RMSE: 0.4190, MAE: 0.3217  [10,856 non-zero values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Overall (all)      - RMSE: 1.9732, MAE: 0.5454
Overall (non-zero) - RMSE: 6.0598, MAE: 3.5767  [695,272 values]
Driving Force (DF) - RMSE: 6.1589, MAE: 3.6877  [673,018 non-zero values]
Phase Fraction (NF) - RMSE: 0.2900, MAE: 0.2199  [22,254 non-zero values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Overall (all)      - RMSE: 0.9741, MAE: 0.3020
Overall (non-zero) - RMSE: 2.0648, MAE: 1.3536  [240,039 values]
Driving Force (DF) - RMSE: 2.0911, MAE: 1.3809  [233,863 non-zero values]
Phase Fraction (NF) - RMSE: 0.3717, MAE: 0.3205  [6,176 non-zero values]

==================================================
Cross-Validation Summary (non-zero targets only)
==================================================
Overall (all values):
  Avg Test MSE: 1.7580 (+/- 1.1414)
  Avg RMSE: 1.2637, MAE: 0.3092

Overall (non-zero only):
  Avg RMSE: 4.3306, MAE: 2.4724

Driving Force (DF, non-zero only):
  Avg RMSE: 4.3876, MAE: 2.5310

Phase Fraction (NF, non-zero only):
  Avg RMSE: 0.3653, MAE: 0.2891

[INFO 03-22 21:27:31] ax.service.ax_client: Completed trial 51 with data: {'avg_rmse_nonzero': (np.float64(4.330573), np.float64(0.732332))}.
[INFO 03-22 21:27:31] ax.service.ax_client: Saved JSON-serialized state of optimization to `ax_client_xgb.json`.

Result: Non-zero RMSE = 4.3306

============================================================
Trial 53/100
============================================================

C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 1783, 'max_depth': 27, 'learning_rate': 0.005, 'subsample': 0.8457364425464673, 'colsample_bytree': 0.3, 'min_child_weight': 8, 'reg_alpha': 0.05320549538587157, 'reg_lambda': 3.139976194794333, 'gamma': 3.7811190993063795, 'early_stopping_rounds': 50}

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Overall (all)      - RMSE: 1.1156, MAE: 0.2797
Overall (non-zero) - RMSE: 4.3128, MAE: 2.6067  [509,534 values]
Driving Force (DF) - RMSE: 4.3605, MAE: 2.6579  [498,341 non-zero values]
Phase Fraction (NF) - RMSE: 0.4089, MAE: 0.3292  [11,193 non-zero values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Overall (all)      - RMSE: 1.3406, MAE: 0.2155
Overall (non-zero) - RMSE: 5.5548, MAE: 2.8166  [1,235,656 values]
Driving Force (DF) - RMSE: 5.6185, MAE: 2.8743  [1,207,679 non-zero values]
Phase Fraction (NF) - RMSE: 0.4052, MAE: 0.3246  [27,977 non-zero values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Overall (all)      - RMSE: 0.7976, MAE: 0.1509
Overall (non-zero) - RMSE: 3.3752, MAE: 1.6736  [410,105 values]
Driving Force (DF) - RMSE: 3.4201, MAE: 1.7100  [399,249 non-zero values]
Phase Fraction (NF) - RMSE: 0.4257, MAE: 0.3325  [10,856 non-zero values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Overall (all)      - RMSE: 1.7745, MAE: 0.4897
Overall (non-zero) - RMSE: 5.5977, MAE: 3.1455  [695,272 values]
Driving Force (DF) - RMSE: 5.6892, MAE: 3.2416  [673,018 non-zero values]
Phase Fraction (NF) - RMSE: 0.3099, MAE: 0.2407  [22,254 non-zero values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Overall (all)      - RMSE: 0.7309, MAE: 0.2323
Overall (non-zero) - RMSE: 1.9415, MAE: 1.3034  [240,039 values]
Driving Force (DF) - RMSE: 1.9664, MAE: 1.3311  [233,863 non-zero values]
Phase Fraction (NF) - RMSE: 0.3010, MAE: 0.2563  [6,176 non-zero values]

==================================================
Cross-Validation Summary (non-zero targets only)
==================================================
Overall (all values):
  Avg Test MSE: 1.4722 (+/- 0.9537)
  Avg RMSE: 1.1519, MAE: 0.2736

Overall (non-zero only):
  Avg RMSE: 4.1564, MAE: 2.3092

Driving Force (DF, non-zero only):
  Avg RMSE: 4.2109, MAE: 2.3630

Phase Fraction (NF, non-zero only):
  Avg RMSE: 0.3701, MAE: 0.2967

[INFO 03-23 02:04:50] ax.service.ax_client: Completed trial 52 with data: {'avg_rmse_nonzero': (np.float64(4.156405), np.float64(0.691856))}.
[INFO 03-23 02:04:50] ax.service.ax_client: Saved JSON-serialized state of optimization to `ax_client_xgb.json`.

Result: Non-zero RMSE = 4.1564

============================================================
Trial 54/100
============================================================

C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 03-23 02:04:53] ax.modelbridge.base: Untransformed parameter 0.004999999999999999 less than lower bound 0.005, clamping
[INFO 03-23 02:04:53] ax.service.ax_client: Generated new trial 53 with parameters {'n_estimators': 9650, 'max_depth': 22, 'learning_rate': 0.005, 'subsample': 0.5, 'colsample_bytree': 0.989551, 'min_child_weight': 1, 'reg_alpha': 1e-06, 'reg_lambda': 10.0, 'gamma': 5.0, 'early_stopping_rounds': 50} using model BoTorch.

Parameters: {'n_estimators': 9650, 'max_depth': 22, 'learning_rate': 0.005, 'subsample': 0.5, 'colsample_bytree': 0.9895513501677723, 'min_child_weight': 1, 'reg_alpha': 1e-06, 'reg_lambda': 10.0, 'gamma': 5.0, 'early_stopping_rounds': 50}

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Overall (all)      - RMSE: 1.3360, MAE: 0.2890
Overall (non-zero) - RMSE: 4.5467, MAE: 2.7678  [509,534 values]
Driving Force (DF) - RMSE: 4.5971, MAE: 2.8225  [498,341 non-zero values]
Phase Fraction (NF) - RMSE: 0.4187, MAE: 0.3338  [11,193 non-zero values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Overall (all)      - RMSE: 1.4195, MAE: 0.2118
Overall (non-zero) - RMSE: 5.8637, MAE: 3.1155  [1,235,656 values]
Driving Force (DF) - RMSE: 5.9309, MAE: 3.1798  [1,207,679 non-zero values]
Phase Fraction (NF) - RMSE: 0.4285, MAE: 0.3400  [27,977 non-zero values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Overall (all)      - RMSE: 0.8222, MAE: 0.1264
Overall (non-zero) - RMSE: 3.3638, MAE: 1.6807  [410,105 values]
Driving Force (DF) - RMSE: 3.4085, MAE: 1.7175  [399,249 non-zero values]
Phase Fraction (NF) - RMSE: 0.4222, MAE: 0.3295  [10,856 non-zero values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Overall (all)      - RMSE: 2.0174, MAE: 0.5023
Overall (non-zero) - RMSE: 6.4272, MAE: 3.9036  [695,272 values]
Driving Force (DF) - RMSE: 6.5324, MAE: 4.0251  [673,018 non-zero values]
Phase Fraction (NF) - RMSE: 0.3041, MAE: 0.2293  [22,254 non-zero values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Overall (all)      - RMSE: 1.1285, MAE: 0.2711
Overall (non-zero) - RMSE: 2.2223, MAE: 1.5210  [240,039 values]
Driving Force (DF) - RMSE: 2.2510, MAE: 1.5549  [233,863 non-zero values]
Phase Fraction (NF) - RMSE: 0.2954, MAE: 0.2402  [6,176 non-zero values]

==================================================
Cross-Validation Summary (non-zero targets only)
==================================================
Overall (all values):
  Avg Test MSE: 1.9639 (+/- 1.1494)
  Avg RMSE: 1.3447, MAE: 0.2801

Overall (non-zero only):
  Avg RMSE: 4.4847, MAE: 2.5977

Driving Force (DF, non-zero only):
  Avg RMSE: 4.5439, MAE: 2.6599

Phase Fraction (NF, non-zero only):
  Avg RMSE: 0.3738, MAE: 0.2946

[INFO 03-23 08:37:04] ax.service.ax_client: Completed trial 53 with data: {'avg_rmse_nonzero': (np.float64(4.48474), np.float64(0.776326))}.
[INFO 03-23 08:37:04] ax.service.ax_client: Saved JSON-serialized state of optimization to `ax_client_xgb.json`.

Result: Non-zero RMSE = 4.4847

============================================================
Trial 55/100
============================================================

C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 9269, 'max_depth': 100, 'learning_rate': 0.005, 'subsample': 0.9720226401630122, 'colsample_bytree': 0.3, 'min_child_weight': 3, 'reg_alpha': 0.024493667248543037, 'reg_lambda': 0.00041823388747437194, 'gamma': 5.0, 'early_stopping_rounds': 50}

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Overall (all)      - RMSE: 1.1144, MAE: 0.2768
Overall (non-zero) - RMSE: 4.2965, MAE: 2.6084  [509,534 values]
Driving Force (DF) - RMSE: 4.3441, MAE: 2.6595  [498,341 non-zero values]
Phase Fraction (NF) - RMSE: 0.4082, MAE: 0.3294  [11,193 non-zero values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Overall (all)      - RMSE: 1.3349, MAE: 0.2163
Overall (non-zero) - RMSE: 5.5134, MAE: 2.8369  [1,235,656 values]
Driving Force (DF) - RMSE: 5.5766, MAE: 2.8951  [1,207,679 non-zero values]
Phase Fraction (NF) - RMSE: 0.4029, MAE: 0.3224  [27,977 non-zero values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Overall (all)      - RMSE: 0.8041, MAE: 0.1495
Overall (non-zero) - RMSE: 3.4011, MAE: 1.6740  [410,105 values]
Driving Force (DF) - RMSE: 3.4463, MAE: 1.7105  [399,249 non-zero values]
Phase Fraction (NF) - RMSE: 0.4264, MAE: 0.3339  [10,856 non-zero values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Overall (all)      - RMSE: 1.7814, MAE: 0.4875
Overall (non-zero) - RMSE: 5.4567, MAE: 3.0482  [695,272 values]
Driving Force (DF) - RMSE: 5.5459, MAE: 3.1411  [673,018 non-zero values]
Phase Fraction (NF) - RMSE: 0.3077, MAE: 0.2384  [22,254 non-zero values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Overall (all)      - RMSE: 0.7271, MAE: 0.2299
Overall (non-zero) - RMSE: 1.9320, MAE: 1.3037  [240,039 values]
Driving Force (DF) - RMSE: 1.9568, MAE: 1.3314  [233,863 non-zero values]
Phase Fraction (NF) - RMSE: 0.3015, MAE: 0.2558  [6,176 non-zero values]

==================================================
Cross-Validation Summary (non-zero targets only)
==================================================
Overall (all values):
  Avg Test MSE: 1.4745 (+/- 0.9607)
  Avg RMSE: 1.1524, MAE: 0.2720

Overall (non-zero only):
  Avg RMSE: 4.1200, MAE: 2.2942

Driving Force (DF, non-zero only):
  Avg RMSE: 4.1739, MAE: 2.3475

Phase Fraction (NF, non-zero only):
  Avg RMSE: 0.3693, MAE: 0.2960

[INFO 03-23 12:47:26] ax.service.ax_client: Completed trial 54 with data: {'avg_rmse_nonzero': (np.float64(4.119951), np.float64(0.673185))}.
[INFO 03-23 12:47:26] ax.service.ax_client: Saved JSON-serialized state of optimization to `ax_client_xgb.json`.

Result: Non-zero RMSE = 4.1200

============================================================
Trial 56/100
============================================================

C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 9432, 'max_depth': 14, 'learning_rate': 0.005, 'subsample': 1.0, 'colsample_bytree': 0.5342441053126649, 'min_child_weight': 13, 'reg_alpha': 1e-06, 'reg_lambda': 10.0, 'gamma': 3.617364135826017, 'early_stopping_rounds': 10}

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Overall (all)      - RMSE: 1.1537, MAE: 0.2743
Overall (non-zero) - RMSE: 4.3900, MAE: 2.6522  [509,534 values]
Driving Force (DF) - RMSE: 4.4386, MAE: 2.7046  [498,341 non-zero values]
Phase Fraction (NF) - RMSE: 0.4037, MAE: 0.3228  [11,193 non-zero values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Overall (all)      - RMSE: 1.3703, MAE: 0.2141
Overall (non-zero) - RMSE: 5.6904, MAE: 2.9419  [1,235,656 values]
Driving Force (DF) - RMSE: 5.7556, MAE: 3.0023  [1,207,679 non-zero values]
Phase Fraction (NF) - RMSE: 0.4196, MAE: 0.3361  [27,977 non-zero values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Overall (all)      - RMSE: 0.8250, MAE: 0.1379
Overall (non-zero) - RMSE: 3.4554, MAE: 1.6614  [410,105 values]
Driving Force (DF) - RMSE: 3.5013, MAE: 1.6977  [399,249 non-zero values]
Phase Fraction (NF) - RMSE: 0.4207, MAE: 0.3260  [10,856 non-zero values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Overall (all)      - RMSE: 1.8769, MAE: 0.5117
Overall (non-zero) - RMSE: 5.8993, MAE: 3.4413  [695,272 values]
Driving Force (DF) - RMSE: 5.9958, MAE: 3.5476  [673,018 non-zero values]
Phase Fraction (NF) - RMSE: 0.3004, MAE: 0.2265  [22,254 non-zero values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Overall (all)      - RMSE: 0.8472, MAE: 0.2399
Overall (non-zero) - RMSE: 2.0225, MAE: 1.3675  [240,039 values]
Driving Force (DF) - RMSE: 2.0485, MAE: 1.3974  [233,863 non-zero values]
Phase Fraction (NF) - RMSE: 0.2920, MAE: 0.2378  [6,176 non-zero values]

==================================================
Cross-Validation Summary (non-zero targets only)
==================================================
Overall (all values):
  Avg Test MSE: 1.6260 (+/- 1.0457)
  Avg RMSE: 1.2146, MAE: 0.2756

Overall (non-zero only):
  Avg RMSE: 4.2915, MAE: 2.4129

Driving Force (DF, non-zero only):
  Avg RMSE: 4.3480, MAE: 2.4699

Phase Fraction (NF, non-zero only):
  Avg RMSE: 0.3673, MAE: 0.2898

[INFO 03-23 16:49:30] ax.service.ax_client: Completed trial 55 with data: {'avg_rmse_nonzero': (np.float64(4.291523), np.float64(0.72108))}.
[INFO 03-23 16:49:30] ax.service.ax_client: Saved JSON-serialized state of optimization to `ax_client_xgb.json`.

Result: Non-zero RMSE = 4.2915

============================================================
Trial 57/100
============================================================

C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 7408, 'max_depth': 99, 'learning_rate': 0.20516702317833824, 'subsample': 1.0, 'colsample_bytree': 0.538611992593511, 'min_child_weight': 20, 'reg_alpha': 7.975110727724878, 'reg_lambda': 0.009791152443197318, 'gamma': 0.8399009696873575, 'early_stopping_rounds': 13}

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Overall (all)      - RMSE: 1.2029, MAE: 0.2729
Overall (non-zero) - RMSE: 4.4478, MAE: 2.7385  [509,534 values]
Driving Force (DF) - RMSE: 4.4971, MAE: 2.7926  [498,341 non-zero values]
Phase Fraction (NF) - RMSE: 0.4140, MAE: 0.3286  [11,193 non-zero values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Overall (all)      - RMSE: 1.4048, MAE: 0.2206
Overall (non-zero) - RMSE: 5.6991, MAE: 3.0031  [1,235,656 values]
Driving Force (DF) - RMSE: 5.7644, MAE: 3.0648  [1,207,679 non-zero values]
Phase Fraction (NF) - RMSE: 0.4356, MAE: 0.3424  [27,977 non-zero values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Overall (all)      - RMSE: 0.9457, MAE: 0.1501
Overall (non-zero) - RMSE: 3.8321, MAE: 1.8762  [410,105 values]
Driving Force (DF) - RMSE: 3.8832, MAE: 1.9184  [399,249 non-zero values]
Phase Fraction (NF) - RMSE: 0.4265, MAE: 0.3263  [10,856 non-zero values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Overall (all)      - RMSE: 1.9638, MAE: 0.5103
Overall (non-zero) - RMSE: 5.8472, MAE: 3.3219  [695,272 values]
Driving Force (DF) - RMSE: 5.9429, MAE: 3.4242  [673,018 non-zero values]
Phase Fraction (NF) - RMSE: 0.2979, MAE: 0.2266  [22,254 non-zero values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Overall (all)      - RMSE: 0.9805, MAE: 0.2577
Overall (non-zero) - RMSE: 2.3077, MAE: 1.6013  [240,039 values]
Driving Force (DF) - RMSE: 2.3374, MAE: 1.6361  [233,863 non-zero values]
Phase Fraction (NF) - RMSE: 0.3192, MAE: 0.2813  [6,176 non-zero values]

==================================================
Cross-Validation Summary (non-zero targets only)
==================================================
Overall (all values):
  Avg Test MSE: 1.8265 (+/- 1.0867)
  Avg RMSE: 1.2995, MAE: 0.2823

Overall (non-zero only):
  Avg RMSE: 4.4268, MAE: 2.5082

Driving Force (DF, non-zero only):
  Avg RMSE: 4.4850, MAE: 2.5672

Phase Fraction (NF, non-zero only):
  Avg RMSE: 0.3786, MAE: 0.3010

[INFO 03-23 18:43:09] ax.service.ax_client: Completed trial 56 with data: {'avg_rmse_nonzero': (np.float64(4.426805), np.float64(0.651191))}.
[INFO 03-23 18:43:09] ax.service.ax_client: Saved JSON-serialized state of optimization to `ax_client_xgb.json`.

Result: Non-zero RMSE = 4.4268

============================================================
Trial 58/100
============================================================

C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 9304, 'max_depth': 100, 'learning_rate': 0.0054633262443915896, 'subsample': 1.0, 'colsample_bytree': 0.3, 'min_child_weight': 1, 'reg_alpha': 10.0, 'reg_lambda': 0.000995061986414335, 'gamma': 0.8517546207220652, 'early_stopping_rounds': 10}

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Overall (all)      - RMSE: 1.1317, MAE: 0.2721
Overall (non-zero) - RMSE: 4.6132, MAE: 2.7156  [509,534 values]
Driving Force (DF) - RMSE: 4.6643, MAE: 2.7690  [498,341 non-zero values]
Phase Fraction (NF) - RMSE: 0.4256, MAE: 0.3407  [11,193 non-zero values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Overall (all)      - RMSE: 1.3292, MAE: 0.2140
Overall (non-zero) - RMSE: 5.5377, MAE: 2.8484  [1,235,656 values]
Driving Force (DF) - RMSE: 5.6011, MAE: 2.9069  [1,207,679 non-zero values]
Phase Fraction (NF) - RMSE: 0.4030, MAE: 0.3215  [27,977 non-zero values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Overall (all)      - RMSE: 0.8045, MAE: 0.1472
Overall (non-zero) - RMSE: 3.4671, MAE: 1.6726  [410,105 values]
Driving Force (DF) - RMSE: 3.5132, MAE: 1.7091  [399,249 non-zero values]
Phase Fraction (NF) - RMSE: 0.4256, MAE: 0.3293  [10,856 non-zero values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Overall (all)      - RMSE: 1.7163, MAE: 0.4645
Overall (non-zero) - RMSE: 5.4884, MAE: 3.0184  [695,272 values]
Driving Force (DF) - RMSE: 5.5781, MAE: 3.1103  [673,018 non-zero values]
Phase Fraction (NF) - RMSE: 0.3085, MAE: 0.2387  [22,254 non-zero values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Overall (all)      - RMSE: 0.7006, MAE: 0.2210
Overall (non-zero) - RMSE: 1.9394, MAE: 1.3040  [240,039 values]
Driving Force (DF) - RMSE: 1.9642, MAE: 1.3315  [233,863 non-zero values]
Phase Fraction (NF) - RMSE: 0.3079, MAE: 0.2653  [6,176 non-zero values]

==================================================
Cross-Validation Summary (non-zero targets only)
==================================================
Overall (all values):
  Avg Test MSE: 1.4263 (+/- 0.8863)
  Avg RMSE: 1.1365, MAE: 0.2638

Overall (non-zero only):
  Avg RMSE: 4.2092, MAE: 2.3118

Driving Force (DF, non-zero only):
  Avg RMSE: 4.2642, MAE: 2.3654

Phase Fraction (NF, non-zero only):
  Avg RMSE: 0.3741, MAE: 0.2991

[INFO 03-23 23:55:28] ax.service.ax_client: Completed trial 57 with data: {'avg_rmse_nonzero': (np.float64(4.209151), np.float64(0.68071))}.
[INFO 03-23 23:55:28] ax.service.ax_client: Saved JSON-serialized state of optimization to `ax_client_xgb.json`.

Result: Non-zero RMSE = 4.2092

============================================================
Trial 59/100
============================================================

C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 10000, 'max_depth': 3, 'learning_rate': 0.005, 'subsample': 0.5, 'colsample_bytree': 0.8464382264554648, 'min_child_weight': 20, 'reg_alpha': 1e-06, 'reg_lambda': 7.590018037419723e-05, 'gamma': 0.0, 'early_stopping_rounds': 50}

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Overall (all)      - RMSE: 1.3519, MAE: 0.3416
Overall (non-zero) - RMSE: 4.6783, MAE: 3.1255  [509,534 values]
Driving Force (DF) - RMSE: 4.7303, MAE: 3.1899  [498,341 non-zero values]
Phase Fraction (NF) - RMSE: 0.3278, MAE: 0.2574  [11,193 non-zero values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Overall (all)      - RMSE: 1.3985, MAE: 0.2287
Overall (non-zero) - RMSE: 5.7196, MAE: 2.9172  [1,235,656 values]
Driving Force (DF) - RMSE: 5.7852, MAE: 2.9778  [1,207,679 non-zero values]
Phase Fraction (NF) - RMSE: 0.3880, MAE: 0.3013  [27,977 non-zero values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Overall (all)      - RMSE: 0.8238, MAE: 0.1529
Overall (non-zero) - RMSE: 3.3180, MAE: 1.7669  [410,105 values]
Driving Force (DF) - RMSE: 3.3621, MAE: 1.8065  [399,249 non-zero values]
Phase Fraction (NF) - RMSE: 0.4135, MAE: 0.3124  [10,856 non-zero values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Overall (all)      - RMSE: 2.2348, MAE: 0.6084
Overall (non-zero) - RMSE: 6.5659, MAE: 4.1451  [695,272 values]
Driving Force (DF) - RMSE: 6.6734, MAE: 4.2754  [673,018 non-zero values]
Phase Fraction (NF) - RMSE: 0.2793, MAE: 0.2062  [22,254 non-zero values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Overall (all)      - RMSE: 1.3348, MAE: 0.3726
Overall (non-zero) - RMSE: 2.2650, MAE: 1.5667  [240,039 values]
Driving Force (DF) - RMSE: 2.2940, MAE: 1.6002  [233,863 non-zero values]
Phase Fraction (NF) - RMSE: 0.3557, MAE: 0.3018  [6,176 non-zero values]

==================================================
Cross-Validation Summary (non-zero targets only)
==================================================
Overall (all values):
  Avg Test MSE: 2.2476 (+/- 1.4481)
  Avg RMSE: 1.4288, MAE: 0.3408

Overall (non-zero only):
  Avg RMSE: 4.5094, MAE: 2.7043

Driving Force (DF, non-zero only):
  Avg RMSE: 4.5690, MAE: 2.7699

Phase Fraction (NF, non-zero only):
  Avg RMSE: 0.3528, MAE: 0.2758

[INFO 03-24 13:24:24] ax.service.ax_client: Completed trial 58 with data: {'avg_rmse_nonzero': (np.float64(4.509361), np.float64(0.78036))}.
[INFO 03-24 13:24:24] ax.service.ax_client: Saved JSON-serialized state of optimization to `ax_client_xgb.json`.

Result: Non-zero RMSE = 4.5094

============================================================
Trial 60/100
============================================================

C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 8637, 'max_depth': 35, 'learning_rate': 0.005, 'subsample': 0.5, 'colsample_bytree': 0.40109568066736245, 'min_child_weight': 1, 'reg_alpha': 0.490937128665333, 'reg_lambda': 9.547049696387044e-06, 'gamma': 0.0, 'early_stopping_rounds': 50}

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Overall (all)      - RMSE: 1.1271, MAE: 0.2872
Overall (non-zero) - RMSE: 4.0997, MAE: 2.5344  [509,534 values]
Driving Force (DF) - RMSE: 4.1450, MAE: 2.5838  [498,341 non-zero values]
Phase Fraction (NF) - RMSE: 0.3948, MAE: 0.3382  [11,193 non-zero values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Overall (all)      - RMSE: 1.3361, MAE: 0.2154
Overall (non-zero) - RMSE: 5.5133, MAE: 2.8551  [1,235,656 values]
Driving Force (DF) - RMSE: 5.5764, MAE: 2.9135  [1,207,679 non-zero values]
Phase Fraction (NF) - RMSE: 0.4165, MAE: 0.3360  [27,977 non-zero values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Overall (all)      - RMSE: 0.8209, MAE: 0.1474
Overall (non-zero) - RMSE: 3.4172, MAE: 1.6637  [410,105 values]
Driving Force (DF) - RMSE: 3.4627, MAE: 1.7003  [399,249 non-zero values]
Phase Fraction (NF) - RMSE: 0.4147, MAE: 0.3182  [10,856 non-zero values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Overall (all)      - RMSE: 1.8504, MAE: 0.5118
Overall (non-zero) - RMSE: 5.4642, MAE: 3.1317  [695,272 values]
Driving Force (DF) - RMSE: 5.5535, MAE: 3.2274  [673,018 non-zero values]
Phase Fraction (NF) - RMSE: 0.3042, MAE: 0.2376  [22,254 non-zero values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Overall (all)      - RMSE: 0.8057, MAE: 0.2476
Overall (non-zero) - RMSE: 1.9140, MAE: 1.2941  [240,039 values]
Driving Force (DF) - RMSE: 1.9384, MAE: 1.3205  [233,863 non-zero values]
Phase Fraction (NF) - RMSE: 0.3290, MAE: 0.2933  [6,176 non-zero values]

==================================================
Cross-Validation Summary (non-zero targets only)
==================================================
Overall (all values):
  Avg Test MSE: 1.5605 (+/- 1.0221)
  Avg RMSE: 1.1880, MAE: 0.2819

Overall (non-zero only):
  Avg RMSE: 4.0817, MAE: 2.2958

Driving Force (DF, non-zero only):
  Avg RMSE: 4.1352, MAE: 2.3491

Phase Fraction (NF, non-zero only):
  Avg RMSE: 0.3719, MAE: 0.3047

[INFO 03-25 12:00:08] ax.service.ax_client: Completed trial 59 with data: {'avg_rmse_nonzero': (np.float64(4.081663), np.float64(0.674596))}.
[INFO 03-25 12:00:08] ax.service.ax_client: Saved JSON-serialized state of optimization to `ax_client_xgb.json`.

Result: Non-zero RMSE = 4.0817

============================================================
Trial 61/100
============================================================

C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 9909, 'max_depth': 100, 'learning_rate': 0.11760796551470973, 'subsample': 0.5000018964793247, 'colsample_bytree': 0.31388129681458193, 'min_child_weight': 1, 'reg_alpha': 1e-06, 'reg_lambda': 10.0, 'gamma': 0.0, 'early_stopping_rounds': 12}

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Overall (all)      - RMSE: 1.1968, MAE: 0.2930
Overall (non-zero) - RMSE: 4.7459, MAE: 2.7472  [509,534 values]
Driving Force (DF) - RMSE: 4.7985, MAE: 2.8013  [498,341 non-zero values]
Phase Fraction (NF) - RMSE: 0.4014, MAE: 0.3376  [11,193 non-zero values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Overall (all)      - RMSE: 1.3526, MAE: 0.2187
Overall (non-zero) - RMSE: 5.6785, MAE: 2.9324  [1,235,656 values]
Driving Force (DF) - RMSE: 5.7435, MAE: 2.9925  [1,207,679 non-zero values]
Phase Fraction (NF) - RMSE: 0.4201, MAE: 0.3372  [27,977 non-zero values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Overall (all)      - RMSE: 0.8071, MAE: 0.1585
Overall (non-zero) - RMSE: 3.3775, MAE: 1.6682  [410,105 values]
Driving Force (DF) - RMSE: 3.4224, MAE: 1.7047  [399,249 non-zero values]
Phase Fraction (NF) - RMSE: 0.4175, MAE: 0.3233  [10,856 non-zero values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Overall (all)      - RMSE: 1.6605, MAE: 0.4599
Overall (non-zero) - RMSE: 5.6250, MAE: 3.0277  [695,272 values]
Driving Force (DF) - RMSE: 5.7169, MAE: 3.1200  [673,018 non-zero values]
Phase Fraction (NF) - RMSE: 0.3026, MAE: 0.2359  [22,254 non-zero values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Overall (all)      - RMSE: 0.7810, MAE: 0.2515
Overall (non-zero) - RMSE: 2.1127, MAE: 1.4884  [240,039 values]
Driving Force (DF) - RMSE: 2.1397, MAE: 1.5198  [233,863 non-zero values]
Phase Fraction (NF) - RMSE: 0.3403, MAE: 0.3013  [6,176 non-zero values]

==================================================
Cross-Validation Summary (non-zero targets only)
==================================================
Overall (all values):
  Avg Test MSE: 1.4561 (+/- 0.7996)
  Avg RMSE: 1.1596, MAE: 0.2763

Overall (non-zero only):
  Avg RMSE: 4.3079, MAE: 2.3728

Driving Force (DF, non-zero only):
  Avg RMSE: 4.3642, MAE: 2.4277

Phase Fraction (NF, non-zero only):
  Avg RMSE: 0.3764, MAE: 0.3071

[INFO 03-25 16:21:30] ax.service.ax_client: Completed trial 60 with data: {'avg_rmse_nonzero': (np.float64(4.307887), np.float64(0.688828))}.
[INFO 03-25 16:21:30] ax.service.ax_client: Saved JSON-serialized state of optimization to `ax_client_xgb.json`.

Result: Non-zero RMSE = 4.3079

============================================================
Trial 62/100
============================================================

C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 7927, 'max_depth': 4, 'learning_rate': 0.24849061960417632, 'subsample': 0.6331415719138807, 'colsample_bytree': 0.3, 'min_child_weight': 4, 'reg_alpha': 5.817582187807273, 'reg_lambda': 0.0012574013964286466, 'gamma': 3.086170664477629, 'early_stopping_rounds': 49}

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Overall (all)      - RMSE: 1.3927, MAE: 0.3353
Overall (non-zero) - RMSE: 4.8925, MAE: 3.0524  [509,534 values]
Driving Force (DF) - RMSE: 4.9468, MAE: 3.1137  [498,341 non-zero values]
Phase Fraction (NF) - RMSE: 0.4084, MAE: 0.3262  [11,193 non-zero values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Overall (all)      - RMSE: 1.3841, MAE: 0.2340
Overall (non-zero) - RMSE: 5.4666, MAE: 2.8831  [1,235,656 values]
Driving Force (DF) - RMSE: 5.5292, MAE: 2.9427  [1,207,679 non-zero values]
Phase Fraction (NF) - RMSE: 0.3994, MAE: 0.3061  [27,977 non-zero values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Overall (all)      - RMSE: 0.9549, MAE: 0.1941
Overall (non-zero) - RMSE: 3.5920, MAE: 1.8299  [410,105 values]
Driving Force (DF) - RMSE: 3.6398, MAE: 1.8708  [399,249 non-zero values]
Phase Fraction (NF) - RMSE: 0.4242, MAE: 0.3261  [10,856 non-zero values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Overall (all)      - RMSE: 2.1700, MAE: 0.5651
Overall (non-zero) - RMSE: 6.2646, MAE: 3.5305  [695,272 values]
Driving Force (DF) - RMSE: 6.3670, MAE: 3.6388  [673,018 non-zero values]
Phase Fraction (NF) - RMSE: 0.3310, MAE: 0.2544  [22,254 non-zero values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Overall (all)      - RMSE: 1.2479, MAE: 0.3321
Overall (non-zero) - RMSE: 2.6811, MAE: 1.7975  [240,039 values]
Driving Force (DF) - RMSE: 2.7157, MAE: 1.8370  [233,863 non-zero values]
Phase Fraction (NF) - RMSE: 0.3460, MAE: 0.3009  [6,176 non-zero values]

==================================================
Cross-Validation Summary (non-zero targets only)
==================================================
Overall (all values):
  Avg Test MSE: 2.2067 (+/- 1.3051)
  Avg RMSE: 1.4299, MAE: 0.3321

Overall (non-zero only):
  Avg RMSE: 4.5794, MAE: 2.6187

Driving Force (DF, non-zero only):
  Avg RMSE: 4.6397, MAE: 2.6806

Phase Fraction (NF, non-zero only):
  Avg RMSE: 0.3818, MAE: 0.3027

[INFO 03-25 19:06:49] ax.service.ax_client: Completed trial 61 with data: {'avg_rmse_nonzero': (np.float64(4.57936), np.float64(0.644344))}.
[INFO 03-25 19:06:49] ax.service.ax_client: Saved JSON-serialized state of optimization to `ax_client_xgb.json`.

Result: Non-zero RMSE = 4.5794

============================================================
Trial 63/100
============================================================

C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 9734, 'max_depth': 100, 'learning_rate': 0.007610534697335923, 'subsample': 0.5, 'colsample_bytree': 0.3, 'min_child_weight': 20, 'reg_alpha': 0.002262619280019564, 'reg_lambda': 10.0, 'gamma': 5.0, 'early_stopping_rounds': 10}

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Overall (all)      - RMSE: 1.1142, MAE: 0.2738
Overall (non-zero) - RMSE: 4.4646, MAE: 2.6727  [509,534 values]
Driving Force (DF) - RMSE: 4.5140, MAE: 2.7252  [498,341 non-zero values]
Phase Fraction (NF) - RMSE: 0.4200, MAE: 0.3345  [11,193 non-zero values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Overall (all)      - RMSE: 1.3500, MAE: 0.2129
Overall (non-zero) - RMSE: 5.6591, MAE: 2.8121  [1,235,656 values]
Driving Force (DF) - RMSE: 5.7240, MAE: 2.8699  [1,207,679 non-zero values]
Phase Fraction (NF) - RMSE: 0.3969, MAE: 0.3132  [27,977 non-zero values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Overall (all)      - RMSE: 0.7761, MAE: 0.1488
Overall (non-zero) - RMSE: 3.2833, MAE: 1.6489  [410,105 values]
Driving Force (DF) - RMSE: 3.3268, MAE: 1.6846  [399,249 non-zero values]
Phase Fraction (NF) - RMSE: 0.4267, MAE: 0.3341  [10,856 non-zero values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Overall (all)      - RMSE: 1.7339, MAE: 0.4832
Overall (non-zero) - RMSE: 5.5976, MAE: 3.1653  [695,272 values]
Driving Force (DF) - RMSE: 5.6891, MAE: 3.2621  [673,018 non-zero values]
Phase Fraction (NF) - RMSE: 0.3088, MAE: 0.2386  [22,254 non-zero values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Overall (all)      - RMSE: 0.7386, MAE: 0.2338
Overall (non-zero) - RMSE: 1.9767, MAE: 1.3347  [240,039 values]
Driving Force (DF) - RMSE: 2.0020, MAE: 1.3633  [233,863 non-zero values]
Phase Fraction (NF) - RMSE: 0.3009, MAE: 0.2518  [6,176 non-zero values]

==================================================
Cross-Validation Summary (non-zero targets only)
==================================================
Overall (all values):
  Avg Test MSE: 1.4436 (+/- 0.9101)
  Avg RMSE: 1.1425, MAE: 0.2705

Overall (non-zero only):
  Avg RMSE: 4.1962, MAE: 2.3267

Driving Force (DF, non-zero only):
  Avg RMSE: 4.2512, MAE: 2.3810

Phase Fraction (NF, non-zero only):
  Avg RMSE: 0.3707, MAE: 0.2945

[INFO 03-25 22:48:14] ax.service.ax_client: Completed trial 62 with data: {'avg_rmse_nonzero': (np.float64(4.196245), np.float64(0.704829))}.
[INFO 03-25 22:48:14] ax.service.ax_client: Saved JSON-serialized state of optimization to `ax_client_xgb.json`.

Result: Non-zero RMSE = 4.1962

============================================================
Trial 64/100
============================================================

C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
[INFO 03-25 22:48:18] ax.modelbridge.base: Untransformed parameter 0.004999999999999999 less than lower bound 0.005, clamping
[INFO 03-25 22:48:19] ax.service.ax_client: Generated new trial 63 with parameters {'n_estimators': 10000, 'max_depth': 83, 'learning_rate': 0.005, 'subsample': 1.0, 'colsample_bytree': 0.3, 'min_child_weight': 20, 'reg_alpha': 10.0, 'reg_lambda': 1e-06, 'gamma': 5.0, 'early_stopping_rounds': 10} using model BoTorch.

Parameters: {'n_estimators': 10000, 'max_depth': 83, 'learning_rate': 0.005, 'subsample': 1.0, 'colsample_bytree': 0.3, 'min_child_weight': 20, 'reg_alpha': 10.0, 'reg_lambda': 1e-06, 'gamma': 5.0, 'early_stopping_rounds': 10}

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Overall (all)      - RMSE: 1.1151, MAE: 0.2706
Overall (non-zero) - RMSE: 4.4361, MAE: 2.6612  [509,534 values]
Driving Force (DF) - RMSE: 4.4852, MAE: 2.7135  [498,341 non-zero values]
Phase Fraction (NF) - RMSE: 0.4239, MAE: 0.3334  [11,193 non-zero values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Overall (all)      - RMSE: 1.3496, MAE: 0.2145
Overall (non-zero) - RMSE: 5.6106, MAE: 2.8357  [1,235,656 values]
Driving Force (DF) - RMSE: 5.6749, MAE: 2.8941  [1,207,679 non-zero values]
Phase Fraction (NF) - RMSE: 0.3977, MAE: 0.3141  [27,977 non-zero values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Overall (all)      - RMSE: 0.8071, MAE: 0.1504
Overall (non-zero) - RMSE: 3.4505, MAE: 1.7131  [410,105 values]
Driving Force (DF) - RMSE: 3.4964, MAE: 1.7506  [399,249 non-zero values]
Phase Fraction (NF) - RMSE: 0.4262, MAE: 0.3324  [10,856 non-zero values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Overall (all)      - RMSE: 1.7693, MAE: 0.4792
Overall (non-zero) - RMSE: 5.6454, MAE: 3.1807  [695,272 values]
Driving Force (DF) - RMSE: 5.7377, MAE: 3.2781  [673,018 non-zero values]
Phase Fraction (NF) - RMSE: 0.3064, MAE: 0.2358  [22,254 non-zero values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Overall (all)      - RMSE: 0.7145, MAE: 0.2232
Overall (non-zero) - RMSE: 1.9772, MAE: 1.3305  [240,039 values]
Driving Force (DF) - RMSE: 2.0025, MAE: 1.3591  [233,863 non-zero values]
Phase Fraction (NF) - RMSE: 0.3014, MAE: 0.2503  [6,176 non-zero values]

==================================================
Cross-Validation Summary (non-zero targets only)
==================================================
Overall (all values):
  Avg Test MSE: 1.4714 (+/- 0.9511)
  Avg RMSE: 1.1511, MAE: 0.2676

Overall (non-zero only):
  Avg RMSE: 4.2240, MAE: 2.3442

Driving Force (DF, non-zero only):
  Avg RMSE: 4.2793, MAE: 2.3991

Phase Fraction (NF, non-zero only):
  Avg RMSE: 0.3711, MAE: 0.2932

[INFO 03-26 01:59:25] ax.service.ax_client: Completed trial 63 with data: {'avg_rmse_nonzero': (np.float64(4.223959), np.float64(0.694071))}.
[INFO 03-26 01:59:26] ax.service.ax_client: Saved JSON-serialized state of optimization to `ax_client_xgb.json`.

Result: Non-zero RMSE = 4.2240

============================================================
Trial 65/100
============================================================

C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 6091, 'max_depth': 88, 'learning_rate': 0.06577832377919177, 'subsample': 0.971949948820458, 'colsample_bytree': 0.43907307202057516, 'min_child_weight': 20, 'reg_alpha': 0.003725707152242448, 'reg_lambda': 3.6606733073648945, 'gamma': 0.0, 'early_stopping_rounds': 50}

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Overall (all)      - RMSE: 1.1955, MAE: 0.3084
Overall (non-zero) - RMSE: 4.1707, MAE: 2.6098  [509,534 values]
Driving Force (DF) - RMSE: 4.2169, MAE: 2.6612  [498,341 non-zero values]
Phase Fraction (NF) - RMSE: 0.3887, MAE: 0.3232  [11,193 non-zero values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Overall (all)      - RMSE: 1.3679, MAE: 0.2251
Overall (non-zero) - RMSE: 5.5995, MAE: 2.9032  [1,235,656 values]
Driving Force (DF) - RMSE: 5.6637, MAE: 2.9630  [1,207,679 non-zero values]
Phase Fraction (NF) - RMSE: 0.4054, MAE: 0.3223  [27,977 non-zero values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Overall (all)      - RMSE: 0.8477, MAE: 0.1591
Overall (non-zero) - RMSE: 3.4532, MAE: 1.7583  [410,105 values]
Driving Force (DF) - RMSE: 3.4991, MAE: 1.7974  [399,249 non-zero values]
Phase Fraction (NF) - RMSE: 0.4175, MAE: 0.3180  [10,856 non-zero values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Overall (all)      - RMSE: 1.9090, MAE: 0.5391
Overall (non-zero) - RMSE: 5.7674, MAE: 3.3114  [695,272 values]
Driving Force (DF) - RMSE: 5.8618, MAE: 3.4137  [673,018 non-zero values]
Phase Fraction (NF) - RMSE: 0.2902, MAE: 0.2197  [22,254 non-zero values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Overall (all)      - RMSE: 0.8902, MAE: 0.2691
Overall (non-zero) - RMSE: 2.0324, MAE: 1.3791  [240,039 values]
Driving Force (DF) - RMSE: 2.0584, MAE: 1.4087  [233,863 non-zero values]
Phase Fraction (NF) - RMSE: 0.3124, MAE: 0.2585  [6,176 non-zero values]

==================================================
Cross-Validation Summary (non-zero targets only)
==================================================
Overall (all values):
  Avg Test MSE: 1.6911 (+/- 1.0648)
  Avg RMSE: 1.2421, MAE: 0.3002

Overall (non-zero only):
  Avg RMSE: 4.2046, MAE: 2.3924

Driving Force (DF, non-zero only):
  Avg RMSE: 4.2600, MAE: 2.4488

Phase Fraction (NF, non-zero only):
  Avg RMSE: 0.3628, MAE: 0.2883

[INFO 03-26 17:36:12] ax.service.ax_client: Completed trial 64 with data: {'avg_rmse_nonzero': (np.float64(4.204648), np.float64(0.695435))}.

Result: Non-zero RMSE = 4.2046

[INFO 03-26 17:36:12] ax.service.ax_client: Saved JSON-serialized state of optimization to `ax_client_xgb.json`.

============================================================
Trial 66/100
============================================================

C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 220, 'max_depth': 100, 'learning_rate': 0.005, 'subsample': 1.0, 'colsample_bytree': 0.6331277562161708, 'min_child_weight': 20, 'reg_alpha': 1e-06, 'reg_lambda': 1e-06, 'gamma': 5.0, 'early_stopping_rounds': 23}

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Overall (all)      - RMSE: 1.1917, MAE: 0.2735
Overall (non-zero) - RMSE: 5.0330, MAE: 2.9465  [509,534 values]
Driving Force (DF) - RMSE: 5.0888, MAE: 3.0049  [498,341 non-zero values]
Phase Fraction (NF) - RMSE: 0.4184, MAE: 0.3471  [11,193 non-zero values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Overall (all)      - RMSE: 1.4024, MAE: 0.2272
Overall (non-zero) - RMSE: 6.0336, MAE: 3.0412  [1,235,656 values]
Driving Force (DF) - RMSE: 6.1027, MAE: 3.1038  [1,207,679 non-zero values]
Phase Fraction (NF) - RMSE: 0.4170, MAE: 0.3375  [27,977 non-zero values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Overall (all)      - RMSE: 0.8815, MAE: 0.1650
Overall (non-zero) - RMSE: 3.7455, MAE: 1.8468  [410,105 values]
Driving Force (DF) - RMSE: 3.7954, MAE: 1.8877  [399,249 non-zero values]
Phase Fraction (NF) - RMSE: 0.4279, MAE: 0.3424  [10,856 non-zero values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Overall (all)      - RMSE: 1.7235, MAE: 0.4495
Overall (non-zero) - RMSE: 5.8245, MAE: 3.2228  [695,272 values]
Driving Force (DF) - RMSE: 5.9197, MAE: 3.3216  [673,018 non-zero values]
Phase Fraction (NF) - RMSE: 0.3052, MAE: 0.2340  [22,254 non-zero values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Overall (all)      - RMSE: 0.8423, MAE: 0.2498
Overall (non-zero) - RMSE: 2.2996, MAE: 1.6260  [240,039 values]
Driving Force (DF) - RMSE: 2.3292, MAE: 1.6614  [233,863 non-zero values]
Phase Fraction (NF) - RMSE: 0.3201, MAE: 0.2845  [6,176 non-zero values]

==================================================
Cross-Validation Summary (non-zero targets only)
==================================================
Overall (all values):
  Avg Test MSE: 1.5688 (+/- 0.8379)
  Avg RMSE: 1.2083, MAE: 0.2730

Overall (non-zero only):
  Avg RMSE: 4.5872, MAE: 2.5366

Driving Force (DF, non-zero only):
  Avg RMSE: 4.6472, MAE: 2.5959

Phase Fraction (NF, non-zero only):
  Avg RMSE: 0.3777, MAE: 0.3091

[INFO 03-26 20:34:38] ax.service.ax_client: Completed trial 65 with data: {'avg_rmse_nonzero': (np.float64(4.587219), np.float64(0.698681))}.
[INFO 03-26 20:34:38] ax.service.ax_client: Saved JSON-serialized state of optimization to `ax_client_xgb.json`.

Result: Non-zero RMSE = 4.5872

============================================================
Trial 67/100
============================================================

C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 7664, 'max_depth': 100, 'learning_rate': 0.005, 'subsample': 1.0, 'colsample_bytree': 0.3, 'min_child_weight': 10, 'reg_alpha': 1e-06, 'reg_lambda': 1e-06, 'gamma': 0.0, 'early_stopping_rounds': 38}

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599
Overall (all)      - RMSE: 1.1186, MAE: 0.2902
Overall (non-zero) - RMSE: 4.1137, MAE: 2.5406  [509,534 values]
Driving Force (DF) - RMSE: 4.1592, MAE: 2.5902  [498,341 non-zero values]
Phase Fraction (NF) - RMSE: 0.3964, MAE: 0.3328  [11,193 non-zero values]

==================================================
Fold 1
==================================================
Train: 23174, Val: 5794, Test: 16014
Overall (all)      - RMSE: 1.3467, MAE: 0.2189
Overall (non-zero) - RMSE: 5.5456, MAE: 2.8213  [1,235,656 values]
Driving Force (DF) - RMSE: 5.6091, MAE: 2.8791  [1,207,679 non-zero values]
Phase Fraction (NF) - RMSE: 0.4035, MAE: 0.3257  [27,977 non-zero values]

==================================================
Fold 2
==================================================
Train: 30885, Val: 7722, Test: 6375
Overall (all)      - RMSE: 0.8063, MAE: 0.1549
Overall (non-zero) - RMSE: 3.3795, MAE: 1.6704  [410,105 values]
Driving Force (DF) - RMSE: 3.4245, MAE: 1.7072  [399,249 non-zero values]
Phase Fraction (NF) - RMSE: 0.4122, MAE: 0.3159  [10,856 non-zero values]

==================================================
Fold 3
==================================================
Train: 27825, Val: 6957, Test: 10200
Overall (all)      - RMSE: 1.8097, MAE: 0.5036
Overall (non-zero) - RMSE: 5.5756, MAE: 3.1245  [695,272 values]
Driving Force (DF) - RMSE: 5.6668, MAE: 3.2203  [673,018 non-zero values]
Phase Fraction (NF) - RMSE: 0.2956, MAE: 0.2266  [22,254 non-zero values]

==================================================
Fold 4
==================================================
Train: 32150, Val: 8038, Test: 4794
Overall (all)      - RMSE: 0.7443, MAE: 0.2422
Overall (non-zero) - RMSE: 1.8952, MAE: 1.2764  [240,039 values]
Driving Force (DF) - RMSE: 1.9194, MAE: 1.3028  [233,863 non-zero values]
Phase Fraction (NF) - RMSE: 0.3196, MAE: 0.2769  [6,176 non-zero values]

==================================================
Cross-Validation Summary (non-zero targets only)
==================================================
Overall (all values):
  Avg Test MSE: 1.5088 (+/- 0.9927)
  Avg RMSE: 1.1651, MAE: 0.2819

Overall (non-zero only):
  Avg RMSE: 4.1019, MAE: 2.2866

Driving Force (DF, non-zero only):
  Avg RMSE: 4.1558, MAE: 2.3399

Phase Fraction (NF, non-zero only):
  Avg RMSE: 0.3655, MAE: 0.2956

[INFO 03-30 07:40:00] ax.service.ax_client: Completed trial 66 with data: {'avg_rmse_nonzero': (np.float64(4.101928), np.float64(0.694536))}.

Result: Non-zero RMSE = 4.1019

[INFO 03-30 07:40:00] ax.service.ax_client: Saved JSON-serialized state of optimization to `ax_client_xgb.json`.

============================================================
Trial 68/100
============================================================

C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)
C:\Users\Chris\python\Lib\dataclasses.py:1581: RuntimeWarning: If using a 2-dim `batch_initial_conditions` botorch will default to old behavior of ignoring `num_restarts` and just use the given `batch_initial_conditions` by setting `raw_samples` to None.
  return obj.__class__(**changes)

Parameters: {'n_estimators': 9324, 'max_depth': 3, 'learning_rate': 0.005, 'subsample': 1.0, 'colsample_bytree': 0.7637803079838497, 'min_child_weight': 20, 'reg_alpha': 3.279445822794067e-05, 'reg_lambda': 1e-06, 'gamma': 5.0, 'early_stopping_rounds': 13}

==================================================
Fold 0
==================================================
Train: 29906, Val: 7477, Test: 7599

KeyboardInterrupt:

In [3]:
#load the ax client from last save and get best parameters
ax_client_2 = AxClient.load_from_json_file(r"Ax_checkpoints\ax_client_xgb_calphad_fT.json")


# Get best parameters
best_parameters, values = ax_client_2.get_best_parameters()
print(f"\n{'='*60}")
print("OPTIMIZATION COMPLETE")
print('='*60)
print(f"Best parameters: {best_parameters}")
print(f"Best Non-zero RMSE: {values[0]['avg_rmse_nonzero']:.4f}")

[ERROR 03-31 10:51:48] ax.storage.json_store.decoders: Transform LogIntToFloat has been deprecated and removed from Ax. We are unable to load this transform and will return the base `Transform` class instead. The models on the loaded generation strategy may not work correctly!
NoneType: None
[ERROR 03-31 10:51:48] ax.storage.json_store.decoders: Transform LogIntToFloat has been deprecated and removed from Ax. We are unable to load this transform and will return the base `Transform` class instead. The models on the loaded generation strategy may not work correctly!
NoneType: None
[ERROR 03-31 10:51:48] ax.storage.json_store.decoders: Transform LogIntToFloat has been deprecated and removed from Ax. We are unable to load this transform and will return the base `Transform` class instead. The models on the loaded generation strategy may not work correctly!
NoneType: None
[ERROR 03-31 10:51:48] ax.storage.json_store.decoders: Transform LogIntToFloat has been deprecated and removed from Ax. We are unable to load this transform and will return the base `Transform` class instead. The models on the loaded generation strategy may not work correctly!
NoneType: None
[ERROR 03-31 10:51:48] ax.storage.json_store.decoders: Transform LogIntToFloat has been deprecated and removed from Ax. We are unable to load this transform and will return the base `Transform` class instead. The models on the loaded generation strategy may not work correctly!
NoneType: None
[ERROR 03-31 10:51:48] ax.storage.json_store.decoders: Transform LogIntToFloat has been deprecated and removed from Ax. We are unable to load this transform and will return the base `Transform` class instead. The models on the loaded generation strategy may not work correctly!
NoneType: None
[ERROR 03-31 10:51:48] ax.storage.json_store.decoders: Transform LogIntToFloat has been deprecated and removed from Ax. We are unable to load this transform and will return the base `Transform` class instead. The models on the loaded generation strategy may not work correctly!
NoneType: None
[ERROR 03-31 10:51:48] ax.storage.json_store.decoders: Transform LogIntToFloat has been deprecated and removed from Ax. We are unable to load this transform and will return the base `Transform` class instead. The models on the loaded generation strategy may not work correctly!
NoneType: None
[ERROR 03-31 10:51:48] ax.storage.json_store.decoders: Transform LogIntToFloat has been deprecated and removed from Ax. We are unable to load this transform and will return the base `Transform` class instead. The models on the loaded generation strategy may not work correctly!
NoneType: None
[ERROR 03-31 10:51:48] ax.storage.json_store.decoders: Transform LogIntToFloat has been deprecated and removed from Ax. We are unable to load this transform and will return the base `Transform` class instead. The models on the loaded generation strategy may not work correctly!
NoneType: None
[ERROR 03-31 10:51:48] ax.storage.json_store.decoders: Transform LogIntToFloat has been deprecated and removed from Ax. We are unable to load this transform and will return the base `Transform` class instead. The models on the loaded generation strategy may not work correctly!
NoneType: None
[ERROR 03-31 10:51:48] ax.storage.json_store.decoders: Transform LogIntToFloat has been deprecated and removed from Ax. We are unable to load this transform and will return the base `Transform` class instead. The models on the loaded generation strategy may not work correctly!
NoneType: None
[ERROR 03-31 10:51:48] ax.storage.json_store.decoders: Transform LogIntToFloat has been deprecated and removed from Ax. We are unable to load this transform and will return the base `Transform` class instead. The models on the loaded generation strategy may not work correctly!
NoneType: None
[ERROR 03-31 10:51:48] ax.storage.json_store.decoders: Transform LogIntToFloat has been deprecated and removed from Ax. We are unable to load this transform and will return the base `Transform` class instead. The models on the loaded generation strategy may not work correctly!
NoneType: None
[ERROR 03-31 10:51:48] ax.storage.json_store.decoders: Transform LogIntToFloat has been deprecated and removed from Ax. We are unable to load this transform and will return the base `Transform` class instead. The models on the loaded generation strategy may not work correctly!
NoneType: None
[ERROR 03-31 10:51:48] ax.storage.json_store.decoders: Transform LogIntToFloat has been deprecated and removed from Ax. We are unable to load this transform and will return the base `Transform` class instead. The models on the loaded generation strategy may not work correctly!
NoneType: None
[ERROR 03-31 10:51:48] ax.storage.json_store.decoders: Transform LogIntToFloat has been deprecated and removed from Ax. We are unable to load this transform and will return the base `Transform` class instead. The models on the loaded generation strategy may not work correctly!
NoneType: None
[ERROR 03-31 10:51:48] ax.storage.json_store.decoders: Transform LogIntToFloat has been deprecated and removed from Ax. We are unable to load this transform and will return the base `Transform` class instead. The models on the loaded generation strategy may not work correctly!
NoneType: None
[ERROR 03-31 10:51:48] ax.storage.json_store.decoders: Transform LogIntToFloat has been deprecated and removed from Ax. We are unable to load this transform and will return the base `Transform` class instead. The models on the loaded generation strategy may not work correctly!
NoneType: None
[ERROR 03-31 10:51:48] ax.storage.json_store.decoders: Transform LogIntToFloat has been deprecated and removed from Ax. We are unable to load this transform and will return the base `Transform` class instead. The models on the loaded generation strategy may not work correctly!
NoneType: None
[ERROR 03-31 10:51:48] ax.storage.json_store.decoders: Transform LogIntToFloat has been deprecated and removed from Ax. We are unable to load this transform and will return the base `Transform` class instead. The models on the loaded generation strategy may not work correctly!
NoneType: None
[ERROR 03-31 10:51:48] ax.storage.json_store.decoders: Transform LogIntToFloat has been deprecated and removed from Ax. We are unable to load this transform and will return the base `Transform` class instead. The models on the loaded generation strategy may not work correctly!
NoneType: None
[ERROR 03-31 10:51:48] ax.storage.json_store.decoders: Transform LogIntToFloat has been deprecated and removed from Ax. We are unable to load this transform and will return the base `Transform` class instead. The models on the loaded generation strategy may not work correctly!
NoneType: None
[ERROR 03-31 10:51:48] ax.storage.json_store.decoders: Transform LogIntToFloat has been deprecated and removed from Ax. We are unable to load this transform and will return the base `Transform` class instead. The models on the loaded generation strategy may not work correctly!
NoneType: None
[ERROR 03-31 10:51:48] ax.storage.json_store.decoders: Transform LogIntToFloat has been deprecated and removed from Ax. We are unable to load this transform and will return the base `Transform` class instead. The models on the loaded generation strategy may not work correctly!
NoneType: None
[ERROR 03-31 10:51:48] ax.storage.json_store.decoders: Transform LogIntToFloat has been deprecated and removed from Ax. We are unable to load this transform and will return the base `Transform` class instead. The models on the loaded generation strategy may not work correctly!
NoneType: None
[ERROR 03-31 10:51:48] ax.storage.json_store.decoders: Transform LogIntToFloat has been deprecated and removed from Ax. We are unable to load this transform and will return the base `Transform` class instead. The models on the loaded generation strategy may not work correctly!
NoneType: None
[ERROR 03-31 10:51:48] ax.storage.json_store.decoders: Transform LogIntToFloat has been deprecated and removed from Ax. We are unable to load this transform and will return the base `Transform` class instead. The models on the loaded generation strategy may not work correctly!
NoneType: None
[ERROR 03-31 10:51:48] ax.storage.json_store.decoders: Transform LogIntToFloat has been deprecated and removed from Ax. We are unable to load this transform and will return the base `Transform` class instead. The models on the loaded generation strategy may not work correctly!
NoneType: None
[ERROR 03-31 10:51:48] ax.storage.json_store.decoders: Transform LogIntToFloat has been deprecated and removed from Ax. We are unable to load this transform and will return the base `Transform` class instead. The models on the loaded generation strategy may not work correctly!
NoneType: None
[ERROR 03-31 10:51:48] ax.storage.json_store.decoders: Transform LogIntToFloat has been deprecated and removed from Ax. We are unable to load this transform and will return the base `Transform` class instead. The models on the loaded generation strategy may not work correctly!
NoneType: None
[ERROR 03-31 10:51:48] ax.storage.json_store.decoders: Transform LogIntToFloat has been deprecated and removed from Ax. We are unable to load this transform and will return the base `Transform` class instead. The models on the loaded generation strategy may not work correctly!
NoneType: None
[ERROR 03-31 10:51:48] ax.storage.json_store.decoders: Transform LogIntToFloat has been deprecated and removed from Ax. We are unable to load this transform and will return the base `Transform` class instead. The models on the loaded generation strategy may not work correctly!
NoneType: None
[ERROR 03-31 10:51:48] ax.storage.json_store.decoders: Transform LogIntToFloat has been deprecated and removed from Ax. We are unable to load this transform and will return the base `Transform` class instead. The models on the loaded generation strategy may not work correctly!
NoneType: None
[ERROR 03-31 10:51:48] ax.storage.json_store.decoders: Transform LogIntToFloat has been deprecated and removed from Ax. We are unable to load this transform and will return the base `Transform` class instead. The models on the loaded generation strategy may not work correctly!
NoneType: None
[ERROR 03-31 10:51:48] ax.storage.json_store.decoders: Transform LogIntToFloat has been deprecated and removed from Ax. We are unable to load this transform and will return the base `Transform` class instead. The models on the loaded generation strategy may not work correctly!
NoneType: None
[ERROR 03-31 10:51:48] ax.storage.json_store.decoders: Transform LogIntToFloat has been deprecated and removed from Ax. We are unable to load this transform and will return the base `Transform` class instead. The models on the loaded generation strategy may not work correctly!
NoneType: None
[ERROR 03-31 10:51:48] ax.storage.json_store.decoders: Transform LogIntToFloat has been deprecated and removed from Ax. We are unable to load this transform and will return the base `Transform` class instead. The models on the loaded generation strategy may not work correctly!
NoneType: None
[ERROR 03-31 10:51:48] ax.storage.json_store.decoders: Transform LogIntToFloat has been deprecated and removed from Ax. We are unable to load this transform and will return the base `Transform` class instead. The models on the loaded generation strategy may not work correctly!
NoneType: None
[ERROR 03-31 10:51:48] ax.storage.json_store.decoders: Transform LogIntToFloat has been deprecated and removed from Ax. We are unable to load this transform and will return the base `Transform` class instead. The models on the loaded generation strategy may not work correctly!
NoneType: None
[ERROR 03-31 10:51:48] ax.storage.json_store.decoders: Transform LogIntToFloat has been deprecated and removed from Ax. We are unable to load this transform and will return the base `Transform` class instead. The models on the loaded generation strategy may not work correctly!
NoneType: None
[ERROR 03-31 10:51:48] ax.storage.json_store.decoders: Transform LogIntToFloat has been deprecated and removed from Ax. We are unable to load this transform and will return the base `Transform` class instead. The models on the loaded generation strategy may not work correctly!
NoneType: None
[ERROR 03-31 10:51:48] ax.storage.json_store.decoders: Transform LogIntToFloat has been deprecated and removed from Ax. We are unable to load this transform and will return the base `Transform` class instead. The models on the loaded generation strategy may not work correctly!
NoneType: None
[ERROR 03-31 10:51:48] ax.storage.json_store.decoders: Transform LogIntToFloat has been deprecated and removed from Ax. We are unable to load this transform and will return the base `Transform` class instead. The models on the loaded generation strategy may not work correctly!
NoneType: None
[ERROR 03-31 10:51:48] ax.storage.json_store.decoders: Transform LogIntToFloat has been deprecated and removed from Ax. We are unable to load this transform and will return the base `Transform` class instead. The models on the loaded generation strategy may not work correctly!
NoneType: None
[ERROR 03-31 10:51:48] ax.storage.json_store.decoders: Transform LogIntToFloat has been deprecated and removed from Ax. We are unable to load this transform and will return the base `Transform` class instead. The models on the loaded generation strategy may not work correctly!
NoneType: None
[ERROR 03-31 10:51:48] ax.storage.json_store.decoders: Transform LogIntToFloat has been deprecated and removed from Ax. We are unable to load this transform and will return the base `Transform` class instead. The models on the loaded generation strategy may not work correctly!
NoneType: None
[ERROR 03-31 10:51:48] ax.storage.json_store.decoders: Transform LogIntToFloat has been deprecated and removed from Ax. We are unable to load this transform and will return the base `Transform` class instead. The models on the loaded generation strategy may not work correctly!
NoneType: None
[ERROR 03-31 10:51:48] ax.storage.json_store.decoders: Transform LogIntToFloat has been deprecated and removed from Ax. We are unable to load this transform and will return the base `Transform` class instead. The models on the loaded generation strategy may not work correctly!
NoneType: None
[ERROR 03-31 10:51:48] ax.storage.json_store.decoders: Transform LogIntToFloat has been deprecated and removed from Ax. We are unable to load this transform and will return the base `Transform` class instead. The models on the loaded generation strategy may not work correctly!
NoneType: None
[ERROR 03-31 10:51:48] ax.storage.json_store.decoders: Transform LogIntToFloat has been deprecated and removed from Ax. We are unable to load this transform and will return the base `Transform` class instead. The models on the loaded generation strategy may not work correctly!
NoneType: None
[ERROR 03-31 10:51:48] ax.storage.json_store.decoders: Transform LogIntToFloat has been deprecated and removed from Ax. We are unable to load this transform and will return the base `Transform` class instead. The models on the loaded generation strategy may not work correctly!
NoneType: None
[ERROR 03-31 10:51:49] ax.storage.json_store.decoders: Transform LogIntToFloat has been deprecated and removed from Ax. We are unable to load this transform and will return the base `Transform` class instead. The models on the loaded generation strategy may not work correctly!
NoneType: None
[ERROR 03-31 10:51:49] ax.storage.json_store.decoders: Transform LogIntToFloat has been deprecated and removed from Ax. We are unable to load this transform and will return the base `Transform` class instead. The models on the loaded generation strategy may not work correctly!
NoneType: None
[ERROR 03-31 10:51:49] ax.storage.json_store.decoders: Transform LogIntToFloat has been deprecated and removed from Ax. We are unable to load this transform and will return the base `Transform` class instead. The models on the loaded generation strategy may not work correctly!
NoneType: None
[ERROR 03-31 10:51:49] ax.storage.json_store.decoders: Transform LogIntToFloat has been deprecated and removed from Ax. We are unable to load this transform and will return the base `Transform` class instead. The models on the loaded generation strategy may not work correctly!
NoneType: None
[ERROR 03-31 10:51:49] ax.storage.json_store.decoders: Transform LogIntToFloat has been deprecated and removed from Ax. We are unable to load this transform and will return the base `Transform` class instead. The models on the loaded generation strategy may not work correctly!
NoneType: None
[ERROR 03-31 10:51:49] ax.storage.json_store.decoders: Transform LogIntToFloat has been deprecated and removed from Ax. We are unable to load this transform and will return the base `Transform` class instead. The models on the loaded generation strategy may not work correctly!
NoneType: None
[ERROR 03-31 10:51:49] ax.storage.json_store.decoders: Transform LogIntToFloat has been deprecated and removed from Ax. We are unable to load this transform and will return the base `Transform` class instead. The models on the loaded generation strategy may not work correctly!
NoneType: None
[ERROR 03-31 10:51:49] ax.storage.json_store.decoders: Transform LogIntToFloat has been deprecated and removed from Ax. We are unable to load this transform and will return the base `Transform` class instead. The models on the loaded generation strategy may not work correctly!
NoneType: None
[ERROR 03-31 10:51:49] ax.storage.json_store.decoders: Transform LogIntToFloat has been deprecated and removed from Ax. We are unable to load this transform and will return the base `Transform` class instead. The models on the loaded generation strategy may not work correctly!
NoneType: None
[ERROR 03-31 10:51:49] ax.storage.json_store.decoders: Transform LogIntToFloat has been deprecated and removed from Ax. We are unable to load this transform and will return the base `Transform` class instead. The models on the loaded generation strategy may not work correctly!
NoneType: None
[ERROR 03-31 10:51:49] ax.storage.json_store.decoders: Transform LogIntToFloat has been deprecated and removed from Ax. We are unable to load this transform and will return the base `Transform` class instead. The models on the loaded generation strategy may not work correctly!
NoneType: None
[ERROR 03-31 10:51:49] ax.storage.json_store.decoders: Transform LogIntToFloat has been deprecated and removed from Ax. We are unable to load this transform and will return the base `Transform` class instead. The models on the loaded generation strategy may not work correctly!
NoneType: None
[ERROR 03-31 10:51:49] ax.storage.json_store.decoders: Transform LogIntToFloat has been deprecated and removed from Ax. We are unable to load this transform and will return the base `Transform` class instead. The models on the loaded generation strategy may not work correctly!
NoneType: None
[ERROR 03-31 10:51:49] ax.storage.json_store.decoders: Transform LogIntToFloat has been deprecated and removed from Ax. We are unable to load this transform and will return the base `Transform` class instead. The models on the loaded generation strategy may not work correctly!
NoneType: None
[ERROR 03-31 10:51:49] ax.storage.json_store.decoders: Transform LogIntToFloat has been deprecated and removed from Ax. We are unable to load this transform and will return the base `Transform` class instead. The models on the loaded generation strategy may not work correctly!
NoneType: None
[ERROR 03-31 10:51:49] ax.storage.json_store.decoders: Transform LogIntToFloat has been deprecated and removed from Ax. We are unable to load this transform and will return the base `Transform` class instead. The models on the loaded generation strategy may not work correctly!
NoneType: None

============================================================
OPTIMIZATION COMPLETE
============================================================
Best parameters: {'n_estimators': 9856, 'max_depth': 25, 'learning_rate': 0.005797910076787395, 'subsample': 0.5037925727665424, 'colsample_bytree': 0.4406051756814122, 'min_child_weight': 11, 'reg_alpha': 0.0010842902645472655, 'reg_lambda': 0.0007034128402734389, 'gamma': 1.3193826703354716, 'early_stopping_rounds': 49}
Best Non-zero RMSE: 4.3023