In [3]:
#this scripts uses calculated thermo cac equilibrium data to train ML models to predict D_max for different compositions. This uses CBFV as additional features.

In [13]:
#Import necessary libraries
import pandas as pd
import numpy as np
import torch
import matplotlib.pyplot as plt
from CBFV import composition
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import re
from ast import literal_eval
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset
from xgboost import XGBRegressor
from sklearn.multioutput import MultiOutputRegressor
from ax.service.ax_client import AxClient, ObjectiveProperties
from ax.core.arm import Arm
import ujson as js
from scipy.stats import sem

In [2]:
#according to the single tree notebook the best temperature ranges to utalize are: 2200, 1700, 2450, 2100, 2400, 1900, 1850
#according to the same notebook the NF or phase fraction features are ineffective at predicting D_max and thus will not be used

In [3]:
#pull training data
train_opt_CALPHAD_df = pd.read_csv(r"Data/F(Composition)_Data/CALPHAD_alloys_train_opt.csv")

#pull test data
test_CALPHAD_df = pd.read_csv(r"Data/F(Composition)_Data/CALPHAD_alloys_test.csv")


train_opt_CALPHAD_df.head()

,alloy_string,DF_AG2CA_T0C,DF_AG2CA_T1000C,DF_AG2CA_T100C,DF_AG2CA_T1050C,DF_AG2CA_T1100C,DF_AG2CA_T1150C,DF_AG2CA_T1200C,DF_AG2CA_T1250C,DF_AG2CA_T1300C,...,NF_ZRSI_T50C,NF_ZRSI_T550C,NF_ZRSI_T600C,NF_ZRSI_T650C,NF_ZRSI_T700C,NF_ZRSI_T750C,NF_ZRSI_T800C,NF_ZRSI_T850C,NF_ZRSI_T900C,NF_ZRSI_T950C
0,B22.00Co4.00Fe68.00Y6.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Cu47.00Nb11.00Ni8.00Si1.00Ti33.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,B6.00C15.00Co6.42Er0.75Fe57.82Mo14.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Be24.00Cu12.00Fe8.00Nb8.00Zr48.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Al10.00Ce60.00Cu20.00Ni10.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [4]:
#create the CBFV features for the training and test data
#start by pulling the formula column
train_opt_formula_df = pd.DataFrame({'formula': train_opt_CALPHAD_df['alloy_string']})
test_formula_df = pd.DataFrame({'formula': test_CALPHAD_df['alloy_string']})

#add a target column for CBFV api
train_opt_formula_df['target'] = 0
test_formula_df['target'] = 0

#use the CBFV api to create the features
train_opt_CBFV_df, _, train_opt_formulae, skipped_train = composition.generate_features(train_opt_formula_df, elem_prop='magpie')
test_CBFV_df, _, test_formulae, skipped_test = composition.generate_features(test_formula_df, elem_prop='magpie')


print(f"CBFV train features shape: {train_opt_CBFV_df.shape}, test features shape: {test_CBFV_df.shape}")
print(f"Number of skipped formulas: {len(skipped_train)}, {len(skipped_test)}")
train_opt_CBFV_df.head()

Processing Input Data: 100%|██████████| 882/882 [00:00<00:00, 27555.87it/s]

	Featurizing Compositions...

Assigning Features...: 100%|██████████| 882/882 [00:00<00:00, 27128.69it/s]

	Creating Pandas Objects...

Processing Input Data: 100%|██████████| 98/98 [00:00<00:00, 49026.93it/s]

	Featurizing Compositions...

Assigning Features...: 100%|██████████| 98/98 [00:00<00:00, 28005.85it/s]

	Creating Pandas Objects...
CBFV train features shape: (882, 132), test features shape: (98, 132)
Number of skipped formulas: 0, 0

,avg_Number,avg_MendeleevNumber,avg_AtomicWeight,avg_MeltingT,avg_Column,avg_Row,avg_CovalentRadius,avg_Electronegativity,avg_NsValence,avg_NpValence,...,mode_NValence,mode_NsUnfilled,mode_NpUnfilled,mode_NdUnfilled,mode_NfUnfilled,mode_NUnfilled,mode_GSvolume_pa,mode_GSbandgap,mode_GSmagmom,mode_SpaceGroupNumber
0,22.200000,56.280000,48.044699,1926.70000,8.840000,3.620000,124.680000,1.841600,2.000000,0.220000,...,8.0,0.0,0.0,4.0,0.0,4.0,10.730,0.0,2.110663,229.0
1,27.780000,55.100000,60.858759,1736.29190,7.980000,4.100000,143.910000,1.749000,1.420000,0.020000,...,11.0,1.0,0.0,0.0,0.0,1.0,11.070,0.0,0.000000,225.0
2,24.359036,58.662966,53.217519,2293.90019,8.946795,3.734973,123.841484,1.995602,1.859986,0.360036,...,8.0,0.0,0.0,4.0,0.0,4.0,10.730,0.0,2.110663,229.0
3,29.000000,53.040000,65.476074,1923.65240,4.760000,4.080000,146.560000,1.517600,1.800000,0.000000,...,4.0,0.0,0.0,8.0,0.0,8.0,23.195,0.0,0.000000,194.0
4,44.700000,35.200000,105.346294,1180.30100,6.300000,5.100000,173.300000,1.404000,1.800000,0.100000,...,4.0,0.0,0.0,9.0,13.0,22.0,37.240,0.0,0.000000,194.0

In [5]:
#filter the CALPHAD data to include only driving forces at the temepratures of interests
# Define the temperature ranges of interest
temperature_range = [2200, 1700, 2450, 2100, 2400, 1900, 1850]
temperature_range_str = [str(temp) for temp in temperature_range]

# Filter the columns to include only those with the specified temperature ranges and Df
filtered_CALPHAD_cols = [col for col in train_opt_CALPHAD_df.columns if any(temp in col for temp in temperature_range_str) and 'DF' in col]

print(f"Number of filtered CALPHAD columns: {len(filtered_CALPHAD_cols)}")

Number of filtered CALPHAD columns: 5628

In [ ]:
#combine the CBFV features with the filtered CALPHAD features for training and test data
X_train_opt = pd.concat([train_opt_CBFV_df, train_opt_CALPHAD_df[filtered_CALPHAD_cols]], axis=1)
X_test = pd.concat([test_CBFV_df, test_CALPHAD_df[filtered_CALPHAD_cols]], axis=1)

print(f"Combined train features shape: {X_train_opt.shape}, Combined test features shape: {X_test.shape}")

Combined train features shape: (882, 5760), Combined test features shape: (98, 5760)

In [9]:
#load the dmax json data and create y data
D_max_dict = js.load(open(r"Data\dmax_data.json", 'r'))

y_train_opt = [D_max_dict[formula] for formula in train_opt_CALPHAD_df['alloy_string']]
y_test = [D_max_dict[formula] for formula in test_CALPHAD_df['alloy_string']]

In [11]:
# Create 5 CV groups by clustering similar alloys together
# Standardize features for clustering
kmeans_scaler = StandardScaler()
kmeans_X_scaled = kmeans_scaler.fit_transform(X_train_opt)

# Use KMeans to group similar alloys into 5 clusters
kmeans = KMeans(n_clusters=5, random_state=42, n_init=10)
cv_groups = kmeans.fit_predict(kmeans_X_scaled)

# Add group assignments to a dataframe for reference
cv_group_df = pd.DataFrame({
    'formula': train_opt_CALPHAD_df['alloy_string'],
    'cv_group': cv_groups
})

print("CV Group distribution:")
print(cv_group_df['cv_group'].value_counts().sort_index())
print(f"\nTotal samples: {len(cv_groups)}")
cv_group_df.head(10)

CV Group distribution:
cv_group
0    512
1    146
2     86
3     96
4     42
Name: count, dtype: int64

Total samples: 882

                                 formula  cv_group
0               B22.00Co4.00Fe68.00Y6.00         0
1      Cu47.00Nb11.00Ni8.00Si1.00Ti33.00         0
2  B6.00C15.00Co6.42Er0.75Fe57.82Mo14.00         2
3      Be24.00Cu12.00Fe8.00Nb8.00Zr48.00         0
4           Al10.00Ce60.00Cu20.00Ni10.00         3
5            Cu20.00Gd10.00Mg65.00Ni5.00         1
6                  Ca55.00Cu20.00Mg25.00         1
7      Ag5.00Al12.50Cu15.00Fe5.00La62.50         3
8        B5.00C10.00Co35.00Fe40.00P10.00         2
9                  Ca55.00Mg20.00Zn25.00         1

In [28]:

# --- Flexible NN for D_max regression (5760 → 1) ---
class DmaxNet(nn.Module):
    def __init__(self, input_dim, hidden_layers, dropout_rate=0.3, activation="relu"):
        """
        Args:
            input_dim:      number of input features (5760)
            hidden_layers:  list of ints, e.g. [1024, 512, 256]
            dropout_rate:   dropout probability applied after each hidden layer
            activation:     "relu", "leaky_relu", "elu", or "selu"
        """
        super().__init__()
        act_fn = {"relu": nn.ReLU, "leaky_relu": nn.LeakyReLU,
                  "elu": nn.ELU, "selu": nn.SELU}[activation]

        layers = []
        prev = input_dim
        for units in hidden_layers:
            layers.append(nn.Linear(prev, units))
            layers.append(nn.BatchNorm1d(units))
            layers.append(act_fn())
            layers.append(nn.Dropout(dropout_rate))
            prev = units
        layers.append(nn.Linear(prev, 1))
        self.net = nn.Sequential(*layers)

    def forward(self, x):
        return self.net(x).squeeze(-1)


def train_one_epoch(model, loader, optimizer, criterion, device):
    """Train model for one epoch. Returns average training loss."""
    model.train()
    total_loss = 0.0
    n_batches = 0
    for xb, yb in loader:
        xb, yb = xb.to(device), yb.to(device)
        optimizer.zero_grad()
        loss = criterion(model(xb), yb)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
        n_batches += 1
    return total_loss / n_batches


def evaluate(model, loader, criterion, device):
    """Evaluate model on a loader. Returns average loss."""
    model.eval()
    total_loss = 0.0
    n_batches = 0
    with torch.no_grad():
        for xb, yb in loader:
            xb, yb = xb.to(device), yb.to(device)
            loss = criterion(model(xb), yb)
            total_loss += loss.item()
            n_batches += 1
    return total_loss / n_batches


def predict(model, loader, device):
    """Run inference on a loader. Returns (predictions, actuals) if labels exist, else just (predictions, None)."""
    model.eval()
    all_preds = []
    all_actuals = []
    has_labels = False
    with torch.no_grad():
        for batch in loader:
            if isinstance(batch, (list, tuple)) and len(batch) >= 2:
                xb, yb = batch[0], batch[1]
                has_labels = True
                all_actuals.append(yb.cpu().numpy())
            else:
                xb = batch[0] if isinstance(batch, (list, tuple)) else batch
            xb = xb.to(device)
            all_preds.append(model(xb).cpu().numpy())
    preds = np.concatenate(all_preds)
    actuals = np.concatenate(all_actuals) if has_labels else None
    return preds, actuals

In [29]:
#define the evaluate parameters function for the ax optimization loop of the dmax_nn model
def evaluate_parameters_NN_dmax(parameters):
    
    #break down the parameters
    batch_size = parameters.get("batch_size", 64)
    n_layers = parameters.get("n_layers", 3)
    layer_1_dim = parameters.get("layer_1_dim", 1024)
    layer_2_dim = parameters.get("layer_2_dim", 1024)
    layer_3_dim = parameters.get("layer_3_dim", 512)
    dropout_rate = parameters.get("dropout_rate", 0.3)
    activation = parameters.get("activation", "relu")
    lr = parameters.get("lr", 1e-3)
    weight_decay = parameters.get("weight_decay", 1e-4)
    patience = parameters.get("patience", 20)
    
    #combine layer dimensions into a list for the model
    hidden_layers = [layer_1_dim, layer_2_dim, layer_3_dim][:n_layers]
    
    # Auto-detect device
    if torch.cuda.is_available():
        device = torch.device('cuda')
    elif torch.backends.mps.is_available():
        device = torch.device('mps')
    else:
        device = torch.device('cpu')
    print(f"Using device: {device}")
    
    
    #copy the x and y data
    y_data = y_train_opt.copy()
    x_data = X_train_opt.copy()
    
    #initialize cross fold info
    all_fold_mse = []
    all_fold_rmse = []
    all_fold_mae = []
    
    for fold in range(1,6):
        print(f"Starting fold {fold}...")
        
        #Establish from the folds the train and test data
        X_fold_train = x_data[cv_groups != (fold-1)]
        y_fold_train = np.array(y_data)[cv_groups != (fold-1)]
        
        X_fold_test = x_data[cv_groups == (fold-1)]
        y_fold_test = np.array(y_data)[cv_groups == (fold-1)]
        
        #split the fold train data into train and validation data
        X_fold_train, X_fold_val, y_fold_train, y_fold_val = train_test_split(X_fold_train, y_fold_train, test_size=0.2, random_state=42)
        
        #scale the X_data
        Scaler_X_fold = StandardScaler()
        X_fold_train_scaled = Scaler_X_fold.fit_transform(X_fold_train)
        X_fold_val_scaled = Scaler_X_fold.transform(X_fold_val)
        X_fold_test_scaled = Scaler_X_fold.transform(X_fold_test)
        
        #Scale the y data
        Scaler_y_fold = StandardScaler()
        y_fold_train_scaled = Scaler_y_fold.fit_transform(y_fold_train.reshape(-1, 1)).flatten()
        y_fold_val_scaled = Scaler_y_fold.transform(y_fold_val.reshape(-1, 1)).flatten()
        y_fold_test_scaled = Scaler_y_fold.transform(y_fold_test.reshape(-1, 1)).flatten()
        
        #convert all data to tensors
        X_fold_train_tensor = torch.tensor(X_fold_train_scaled, dtype=torch.float32).to(device)
        y_fold_train_tensor = torch.tensor(y_fold_train_scaled, dtype=torch.float32).to(device)
        X_fold_val_tensor = torch.tensor(X_fold_val_scaled, dtype=torch.float32).to(device)
        y_fold_val_tensor = torch.tensor(y_fold_val_scaled, dtype=torch.float32).to(device)
        X_fold_test_tensor = torch.tensor(X_fold_test_scaled, dtype=torch.float32).to(device)
        y_fold_test_tensor = torch.tensor(y_fold_test_scaled, dtype=torch.float32).to(device)
        
        #convert tensors to datasets then dataloaders
        train_ds = TensorDataset(X_fold_train_tensor, y_fold_train_tensor)
        train_loader = DataLoader(train_ds, batch_size=batch_size, shuffle=True, generator=torch.Generator().manual_seed(42))
        val_ds = TensorDataset(X_fold_val_tensor, y_fold_val_tensor)
        val_loader = DataLoader(val_ds, batch_size=batch_size, shuffle=True, generator=torch.Generator().manual_seed(42)) 
        test_ds = TensorDataset(X_fold_test_tensor, y_fold_test_tensor)
        test_loader = DataLoader(test_ds, batch_size=batch_size, shuffle=False, generator=torch.Generator().manual_seed(42))    

        #initialize the model
        input_dim = X_fold_train_tensor.shape[1]
        model = DmaxNet(input_dim, hidden_layers, dropout_rate, activation).to(device)
        optimizer = torch.optim.Adam(model.parameters(), lr=lr, weight_decay=weight_decay)
        scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, patience=patience // 3, factor=0.5)
        criterion = nn.MSELoss()
        
        
        best_val_loss = float("inf")
        best_state = None
        wait = 0
        
        for epoch in range(1000):

            train_loss = train_one_epoch(model, train_loader, optimizer, criterion, device)
            val_loss = evaluate(model, val_loader, criterion, device)
            if epoch % 10 == 0:
                print(f"  Epoch {epoch}... Train Loss: {train_loss:.4f}, Val Loss: {val_loss:.4f}")
            scheduler.step(val_loss)
            
            if val_loss < best_val_loss:
                best_val_loss = val_loss
                best_state = {k: v.cpu().clone() for k, v in model.state_dict().items()}
                wait = 0
            else:
                wait += 1
                if wait >= patience:
                    break
        
        # Restore best model and evaluate on fold test set
        model.load_state_dict(best_state)
        
        #predict the fold test set and inverse transform the predictions and actuals back to original scale
        y_fold_test_pred_scaled, y_fold_test_actual_scaled = predict(model, test_loader, device)
        y_fold_test_pred = Scaler_y_fold.inverse_transform(y_fold_test_pred_scaled.reshape(-1, 1)).flatten()
        y_fold_test_actual = Scaler_y_fold.inverse_transform(y_fold_test_actual_scaled.reshape(-1, 1)).flatten()
        
        #calculate the fold mse, rmse, and mae and add to the list of fold metrics
        fold_mse = np.mean((y_fold_test_pred - y_fold_test_actual) ** 2)
        fold_rmse = np.sqrt(fold_mse)
        fold_mae = np.mean(np.abs(y_fold_test_pred - y_fold_test_actual))
        
        all_fold_mse.append(fold_mse)
        all_fold_rmse.append(fold_rmse)
        all_fold_mae.append(fold_mae)
        
        #print the fold metrics
        print(f"Fold {fold} - MSE: {fold_mse:.4f}, RMSE: {fold_rmse:.4f}, MAE: {fold_mae:.4f}")

    mean_rmse = np.mean(all_fold_rmse)
    mean_mse = np.mean(all_fold_mse)
    mean_mae = np.mean(all_fold_mae)
    print(f"\nMean CV MSE: {mean_mse:.4f}, Mean CV RMSE: {mean_rmse:.4f}, Mean CV MAE: {mean_mae:.4f}")
    return mean_rmse, sem(all_fold_rmse)

In [34]:
#initialize the ax client for the dmax_nn model
ax_client_dmax_nn = AxClient()
ax_client_dmax_nn.create_experiment(
    name="NN CBVF + CALPHAD to D_max Regression",
    parameters=[
        {
            "name": "dropout_rate",
            "type": "range",
            "bounds": [0.0, 0.5],
        },
        {
            "name": "activation",
            "type": "choice",
            "values": ["relu", "leaky_relu", "elu", "selu"],
            "is_ordered": False,
            "sort_values": False,
        },
        {
            "name": "weight_decay",
            "type": "range",
            "bounds": [1e-6, 1e-2],
            "log_scale": True,
        },
        {
            "name": "lr",
            "type": "range",
            "bounds": [1e-5, 1e-2],
            "log_scale": True,
        },
        {
            "name": "batch_size",
            "type": "choice",
            "values": [32, 64, 128, 256],
            "is_ordered": True,
            "sort_values": True,
        },
        {
            "name": "early_stopping_patience",
            "type": "range",
            "bounds": [10, 50],
            "value_type": "int",
        },
        {
            "name": "n_layers",
            "type": "choice",
            "values": [1, 2, 3],
            "value_type": "int",
            "is_ordered": True,
            "sort_values": True,
        },
        {
            "name": "hidden1",
            "type": "choice",
            "values": [128, 256, 512, 1024, 2048],
            "value_type": "int",
            "is_ordered": True,
            "sort_values": True,

        },
        {
            "name": "hidden2",
            "type": "choice",
            "values": [64, 128, 256, 512, 1024],
            "value_type": "int",
            "is_ordered": True,
            "sort_values": True,

        },
        {
            "name": "hidden3",
            "type": "choice",
            "values": [32, 64, 128, 256, 512],
            "value_type": "int",
            "is_ordered": True,
            "sort_values": True,
        }
        
    ],
    objectives={"avg_rmse_nonzero": ObjectiveProperties(minimize=True)}
)

[INFO 04-01 13:26:10] ax.service.utils.instantiation: Inferred value type of ParameterType.FLOAT for parameter dropout_rate. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
[INFO 04-01 13:26:10] ax.service.utils.instantiation: Inferred value type of ParameterType.STRING for parameter activation. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
[INFO 04-01 13:26:10] ax.service.utils.instantiation: Inferred value type of ParameterType.FLOAT for parameter weight_decay. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
[INFO 04-01 13:26:10] ax.service.utils.instantiation: Inferred value type of ParameterType.FLOAT for parameter lr. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
[INFO 04-01 13:26:10] ax.service.utils.instantiation: Inferred value type of ParameterType.INT for parameter batch_size. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
[INFO 04-01 13:26:10] ax.generation_strategy.dispatch_utils: Using Generators.BOTORCH_MODULAR since there are more ordered parameters than there are categories for the unordered categorical parameters.
[INFO 04-01 13:26:10] ax.generation_strategy.dispatch_utils: Using Bayesian Optimization generation strategy: GenerationStrategy(name='Sobol+BoTorch', steps=[Sobol for 20 trials, BoTorch for subsequent trials]). Iterations after 20 will take longer to generate due to model-fitting.

In [35]:
#Perform the ax optimization loop for the dmax_nn model

#initialize the save path for the dmax_nn ax client
ax_client_dmax_nn_save_path = r"Ax_checkpoints\ax_client_dmax_nn_checkpoint.json"

#check if there is an existing checkpoint and load it, otherwise start a new optimization loop
try:
    ax_client_dmax_nn = AxClient.load_from_json_file(filepath=ax_client_dmax_nn_save_path)
    print(f"Loaded existing Ax client checkpoint from {ax_client_dmax_nn_save_path}")
    
    completed_trials = len(ax_client_dmax_nn.experiment.trials)
    target_trials = 100
    remaining_trials = target_trials - completed_trials
    
    print(f"Loaded {completed_trials} completed trials from ax_client_dmax_nn.json")
    print(f"Remaining trials to reach {target_trials}: {remaining_trials}")
    
    for i in range(remaining_trials):
        parameters, trial_index = ax_client_dmax_nn.get_next_trial()
        print(f"\nStarting trial {trial_index} with parameters: {parameters}")
        mean_rmse, rmse_sem = evaluate_parameters_NN_dmax(parameters)
        ax_client_dmax_nn.complete_trial(trial_index=trial_index, raw_data={"avg_rmse_nonzero": (mean_rmse, rmse_sem)})
        print(f"Completed trial {trial_index} with mean RMSE: {mean_rmse:.4f} ± {rmse_sem:.4f}")
        
        # Save the Ax client state after each trial
        ax_client_dmax_nn.save_to_json_file(filepath=ax_client_dmax_nn_save_path)
        print(f"Saved Ax client checkpoint")
    
    
except Exception as e:
    print(f"No existing checkpoint found, starting new optimization loop. Error: {e}")
    
    for i in range(20):
        parameters, trial_index = ax_client_dmax_nn.get_next_trial()
        print(f"\nStarting trial {trial_index} with parameters: {parameters}")
        mean_rmse, rmse_sem = evaluate_parameters_NN_dmax(parameters)
        ax_client_dmax_nn.complete_trial(trial_index=trial_index, raw_data={"avg_rmse_nonzero": (mean_rmse, rmse_sem)})
        print(f"Completed trial {trial_index} with mean RMSE: {mean_rmse:.4f} ± {rmse_sem:.4f}")
        
        # Save the Ax client state after each trial
        ax_client_dmax_nn.save_to_json_file(filepath=ax_client_dmax_nn_save_path)
        print(f"Saved Ax client checkpoint")

[INFO 04-01 13:26:24] ax.service.ax_client: Generated new trial 0 with parameters {'dropout_rate': 0.138159, 'weight_decay': 7.5e-05, 'lr': 0.008774, 'batch_size': 64, 'early_stopping_patience': 23, 'n_layers': 1, 'hidden1': 1024, 'hidden2': 256, 'hidden3': 256, 'activation': 'elu'} using model Sobol.

No existing checkpoint found, starting new optimization loop. Error: [Errno 2] No such file or directory: 'Ax_checkpoints\\ax_client_dmax_nn_checkpoint.json'

Starting trial 0 with parameters: {'dropout_rate': 0.13815855979919434, 'weight_decay': 7.467031174271204e-05, 'lr': 0.008774111543992593, 'batch_size': 64, 'early_stopping_patience': 23, 'n_layers': 1, 'hidden1': 1024, 'hidden2': 256, 'hidden3': 256, 'activation': 'elu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 26.0981, Val Loss: 88.0684
  Epoch 10... Train Loss: 0.6335, Val Loss: 0.5501
  Epoch 20... Train Loss: 0.4567, Val Loss: 0.4609
  Epoch 30... Train Loss: 0.3889, Val Loss: 0.3258
  Epoch 40... Train Loss: 0.3790, Val Loss: 0.3279
  Epoch 50... Train Loss: 0.4004, Val Loss: 0.5174
  Epoch 60... Train Loss: 0.3747, Val Loss: 0.3247
Fold 1 - MSE: 40.0860, RMSE: 6.3314, MAE: 4.1950
Starting fold 2...
  Epoch 0... Train Loss: 24.9373, Val Loss: 9.8688
  Epoch 10... Train Loss: 0.4853, Val Loss: 0.8324
  Epoch 20... Train Loss: 0.6158, Val Loss: 0.7155
  Epoch 30... Train Loss: 0.3769, Val Loss: 0.6862
  Epoch 40... Train Loss: 0.3345, Val Loss: 0.6316
Fold 2 - MSE: 52.0598, RMSE: 7.2153, MAE: 5.3555
Starting fold 3...
  Epoch 0... Train Loss: 19.4158, Val Loss: 23.9600
  Epoch 10... Train Loss: 0.4851, Val Loss: 0.6123
  Epoch 20... Train Loss: 0.4175, Val Loss: 0.5245
  Epoch 30... Train Loss: 0.3780, Val Loss: 0.5186
  Epoch 40... Train Loss: 0.3183, Val Loss: 0.4711
  Epoch 50... Train Loss: 0.2837, Val Loss: 0.4373
  Epoch 60... Train Loss: 0.2825, Val Loss: 0.4141
  Epoch 70... Train Loss: 0.2345, Val Loss: 0.4812
  Epoch 80... Train Loss: 0.2541, Val Loss: 0.4013
  Epoch 90... Train Loss: 0.2456, Val Loss: 0.4274
Fold 3 - MSE: 136.2679, RMSE: 11.6734, MAE: 6.9418
Starting fold 4...
  Epoch 0... Train Loss: 19.2642, Val Loss: 15.9946
  Epoch 10... Train Loss: 0.4675, Val Loss: 0.4933
  Epoch 20... Train Loss: 0.3442, Val Loss: 0.5641
Fold 4 - MSE: 39.8024, RMSE: 6.3089, MAE: 4.8583
Starting fold 5...
  Epoch 0... Train Loss: 23.8162, Val Loss: 10.0997
  Epoch 10... Train Loss: 0.5083, Val Loss: 1.1363
  Epoch 20... Train Loss: 0.4272, Val Loss: 0.9753
  Epoch 30... Train Loss: 0.3367, Val Loss: 1.0141
  Epoch 40... Train Loss: 0.3334, Val Loss: 0.8701
  Epoch 50... Train Loss: 0.2885, Val Loss: 0.8272
  Epoch 60... Train Loss: 0.2919, Val Loss: 0.8178
  Epoch 70... Train Loss: 0.2919, Val Loss: 0.7970
  Epoch 80... Train Loss: 0.2693, Val Loss: 0.8270
  Epoch 90... Train Loss: 0.2972, Val Loss: 0.8302

[INFO 04-01 13:26:34] ax.service.ax_client: Completed trial 0 with data: {'avg_rmse_nonzero': 7.214929}.

  Epoch 100... Train Loss: 0.2602, Val Loss: 0.9052
Fold 5 - MSE: 20.6638, RMSE: 4.5457, MAE: 3.6555

Mean CV MSE: 57.7760, Mean CV RMSE: 7.2149, Mean CV MAE: 5.0012
Completed trial 0 with mean RMSE: 7.2149 ± 1.1959
Saved Ax client checkpoint

[INFO 04-01 13:26:34] ax.service.ax_client: Generated new trial 1 with parameters {'dropout_rate': 0.418507, 'weight_decay': 0.000791, 'lr': 3.9e-05, 'batch_size': 256, 'early_stopping_patience': 40, 'n_layers': 3, 'hidden1': 128, 'hidden2': 256, 'hidden3': 64, 'activation': 'relu'} using model Sobol.

Starting trial 1 with parameters: {'dropout_rate': 0.41850721929222345, 'weight_decay': 0.0007906991210102755, 'lr': 3.8611938154088066e-05, 'batch_size': 256, 'early_stopping_patience': 40, 'n_layers': 3, 'hidden1': 128, 'hidden2': 256, 'hidden3': 64, 'activation': 'relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 1.5016, Val Loss: 0.9092
  Epoch 10... Train Loss: 0.8517, Val Loss: 0.6455
  Epoch 20... Train Loss: 0.5654, Val Loss: 0.4630
  Epoch 30... Train Loss: 0.5200, Val Loss: 0.3922
  Epoch 40... Train Loss: 0.6138, Val Loss: 0.3756
  Epoch 50... Train Loss: 0.5554, Val Loss: 0.3212
  Epoch 60... Train Loss: 0.4120, Val Loss: 0.3038
  Epoch 70... Train Loss: 0.4480, Val Loss: 0.2830
  Epoch 80... Train Loss: 0.5169, Val Loss: 0.2679
  Epoch 90... Train Loss: 0.4641, Val Loss: 0.2776
Fold 1 - MSE: 38.5284, RMSE: 6.2071, MAE: 4.1389
Starting fold 2...
  Epoch 0... Train Loss: 1.1428, Val Loss: 1.0570
  Epoch 10... Train Loss: 0.7293, Val Loss: 0.6743
  Epoch 20... Train Loss: 0.4917, Val Loss: 0.6621
  Epoch 30... Train Loss: 0.5116, Val Loss: 0.6017
  Epoch 40... Train Loss: 0.4233, Val Loss: 0.5618
  Epoch 50... Train Loss: 0.4812, Val Loss: 0.5302
  Epoch 60... Train Loss: 0.5008, Val Loss: 0.5425
Fold 2 - MSE: 37.5769, RMSE: 6.1300, MAE: 3.7077
Starting fold 3...
  Epoch 0... Train Loss: 1.2067, Val Loss: 1.1314
  Epoch 10... Train Loss: 0.6660, Val Loss: 0.5708
  Epoch 20... Train Loss: 0.5151, Val Loss: 0.5119
  Epoch 30... Train Loss: 0.5335, Val Loss: 0.4450
  Epoch 40... Train Loss: 0.4421, Val Loss: 0.4532
  Epoch 50... Train Loss: 0.4863, Val Loss: 0.4209
  Epoch 60... Train Loss: 0.4233, Val Loss: 0.4254
  Epoch 70... Train Loss: 0.4097, Val Loss: 0.4282
Fold 3 - MSE: 52.6686, RMSE: 7.2573, MAE: 4.3495
Starting fold 4...
  Epoch 0... Train Loss: 1.1450, Val Loss: 0.6971
  Epoch 10... Train Loss: 0.6768, Val Loss: 0.4665
  Epoch 20... Train Loss: 0.5207, Val Loss: 0.4871
Fold 4 - MSE: 41.9313, RMSE: 6.4754, MAE: 5.3633
Starting fold 5...
  Epoch 0... Train Loss: 1.1648, Val Loss: 1.3999
  Epoch 10... Train Loss: 0.6592, Val Loss: 0.9956
  Epoch 20... Train Loss: 0.6135, Val Loss: 0.8983
  Epoch 30... Train Loss: 0.4752, Val Loss: 0.8416
  Epoch 40... Train Loss: 0.4545, Val Loss: 0.8415
  Epoch 50... Train Loss: 0.4690, Val Loss: 0.8223
  Epoch 60... Train Loss: 0.4473, Val Loss: 0.7529
  Epoch 70... Train Loss: 0.4356, Val Loss: 0.7464
  Epoch 80... Train Loss: 0.3641, Val Loss: 0.7781

[INFO 04-01 13:26:41] ax.service.ax_client: Completed trial 1 with data: {'avg_rmse_nonzero': 6.371635}.
[INFO 04-01 13:26:41] ax.service.ax_client: Generated new trial 2 with parameters {'dropout_rate': 0.354088, 'weight_decay': 0.005602, 'lr': 0.000326, 'batch_size': 128, 'early_stopping_patience': 31, 'n_layers': 2, 'hidden1': 256, 'hidden2': 64, 'hidden3': 256, 'activation': 'selu'} using model Sobol.

Fold 5 - MSE: 33.5043, RMSE: 5.7883, MAE: 5.2591

Mean CV MSE: 40.8419, Mean CV RMSE: 6.3716, Mean CV MAE: 4.5637
Completed trial 1 with mean RMSE: 6.3716 ± 0.2471
Saved Ax client checkpoint

Starting trial 2 with parameters: {'dropout_rate': 0.3540883050300181, 'weight_decay': 0.005601998534505785, 'lr': 0.00032633310703562705, 'batch_size': 128, 'early_stopping_patience': 31, 'n_layers': 2, 'hidden1': 256, 'hidden2': 64, 'hidden3': 256, 'activation': 'selu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 6.5500, Val Loss: 3.4903
  Epoch 10... Train Loss: 0.6908, Val Loss: 0.5732
  Epoch 20... Train Loss: 0.6045, Val Loss: 0.4151
  Epoch 30... Train Loss: 0.4973, Val Loss: 0.3947
  Epoch 40... Train Loss: 0.4580, Val Loss: 0.3814
  Epoch 50... Train Loss: 0.4720, Val Loss: 0.3800
Fold 1 - MSE: 40.9996, RMSE: 6.4031, MAE: 4.4291
Starting fold 2...
  Epoch 0... Train Loss: 4.1382, Val Loss: 0.7760
  Epoch 10... Train Loss: 0.6531, Val Loss: 1.0349
  Epoch 20... Train Loss: 0.4685, Val Loss: 0.7694
  Epoch 30... Train Loss: 0.4836, Val Loss: 0.7685
  Epoch 40... Train Loss: 0.4493, Val Loss: 0.7046
Fold 2 - MSE: 39.3620, RMSE: 6.2739, MAE: 3.8563
Starting fold 3...
  Epoch 0... Train Loss: 4.2881, Val Loss: 1.0359
  Epoch 10... Train Loss: 0.5876, Val Loss: 0.5269
  Epoch 20... Train Loss: 0.5235, Val Loss: 0.5403
  Epoch 30... Train Loss: 0.4699, Val Loss: 0.4006
  Epoch 40... Train Loss: 0.4166, Val Loss: 0.4477
  Epoch 50... Train Loss: 0.4003, Val Loss: 0.4335
  Epoch 60... Train Loss: 0.3652, Val Loss: 0.4337
Fold 3 - MSE: 63.1938, RMSE: 7.9495, MAE: 5.0159
Starting fold 4...
  Epoch 0... Train Loss: 4.8721, Val Loss: 0.8789
  Epoch 10... Train Loss: 0.5576, Val Loss: 0.5424
  Epoch 20... Train Loss: 0.4704, Val Loss: 0.6504
  Epoch 30... Train Loss: 0.4300, Val Loss: 0.4739
Fold 4 - MSE: 51.2446, RMSE: 7.1585, MAE: 5.0897
Starting fold 5...
  Epoch 0... Train Loss: 3.5803, Val Loss: 1.7861
  Epoch 10... Train Loss: 0.7263, Val Loss: 0.8646
  Epoch 20... Train Loss: 0.5460, Val Loss: 0.9582
  Epoch 30... Train Loss: 0.4718, Val Loss: 1.1481
  Epoch 40... Train Loss: 0.4381, Val Loss: 0.8281
  Epoch 50... Train Loss: 0.3623, Val Loss: 0.7947
Fold 5 - MSE: 9.6805, RMSE: 3.1114, MAE: 2.4333

Mean CV MSE: 40.8961, Mean CV RMSE: 6.1793, Mean CV MAE: 4.1648

[INFO 04-01 13:26:46] ax.service.ax_client: Completed trial 2 with data: {'avg_rmse_nonzero': 6.17927}.
[INFO 04-01 13:26:46] ax.service.ax_client: Generated new trial 3 with parameters {'dropout_rate': 0.073617, 'weight_decay': 3e-06, 'lr': 7e-05, 'batch_size': 32, 'early_stopping_patience': 13, 'n_layers': 1, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 32, 'activation': 'leaky_relu'} using model Sobol.

Completed trial 2 with mean RMSE: 6.1793 ± 0.8235
Saved Ax client checkpoint

Starting trial 3 with parameters: {'dropout_rate': 0.07361734146252275, 'weight_decay': 3.335971923525339e-06, 'lr': 6.99897586525519e-05, 'batch_size': 32, 'early_stopping_patience': 13, 'n_layers': 1, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 32, 'activation': 'leaky_relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 1.0745, Val Loss: 0.8571
  Epoch 10... Train Loss: 0.4194, Val Loss: 0.3547
  Epoch 20... Train Loss: 0.3771, Val Loss: 0.7079
  Epoch 30... Train Loss: 0.2825, Val Loss: 0.4063
Fold 1 - MSE: 48.3372, RMSE: 6.9525, MAE: 4.6657
Starting fold 2...
  Epoch 0... Train Loss: 1.0000, Val Loss: 1.4281
  Epoch 10... Train Loss: 0.3972, Val Loss: 0.5625
  Epoch 20... Train Loss: 0.2593, Val Loss: 0.4599
  Epoch 30... Train Loss: 0.2081, Val Loss: 0.4764
  Epoch 40... Train Loss: 0.2056, Val Loss: 0.4917
  Epoch 50... Train Loss: 0.1920, Val Loss: 0.4703
Fold 2 - MSE: 42.4887, RMSE: 6.5183, MAE: 3.9642
Starting fold 3...
  Epoch 0... Train Loss: 0.9921, Val Loss: 1.6885
  Epoch 10... Train Loss: 0.3971, Val Loss: 0.5774
  Epoch 20... Train Loss: 0.2736, Val Loss: 0.3915
  Epoch 30... Train Loss: 0.2478, Val Loss: 0.4320
  Epoch 40... Train Loss: 0.2383, Val Loss: 0.3813
  Epoch 50... Train Loss: 0.2026, Val Loss: 0.3574
  Epoch 60... Train Loss: 0.1976, Val Loss: 0.3598
  Epoch 70... Train Loss: 0.1796, Val Loss: 0.3306
  Epoch 80... Train Loss: 0.1717, Val Loss: 0.3313
  Epoch 90... Train Loss: 0.1774, Val Loss: 0.3376
Fold 3 - MSE: 58.5141, RMSE: 7.6494, MAE: 4.7893
Starting fold 4...
  Epoch 0... Train Loss: 0.9417, Val Loss: 1.4453
  Epoch 10... Train Loss: 0.3006, Val Loss: 0.7534
  Epoch 20... Train Loss: 0.1954, Val Loss: 0.4861
  Epoch 30... Train Loss: 0.1788, Val Loss: 0.4798
  Epoch 40... Train Loss: 0.1567, Val Loss: 0.5010
  Epoch 50... Train Loss: 0.1495, Val Loss: 0.4732
  Epoch 60... Train Loss: 0.1533, Val Loss: 0.4876
Fold 4 - MSE: 44.1285, RMSE: 6.6429, MAE: 5.4593
Starting fold 5...
  Epoch 0... Train Loss: 1.1141, Val Loss: 1.4889
  Epoch 10... Train Loss: 0.3572, Val Loss: 0.6662
  Epoch 20... Train Loss: 0.2429, Val Loss: 0.7084
  Epoch 30... Train Loss: 0.2258, Val Loss: 0.6350

[INFO 04-01 13:27:02] ax.service.ax_client: Completed trial 3 with data: {'avg_rmse_nonzero': 8.020006}.
[INFO 04-01 13:27:02] ax.service.ax_client: Generated new trial 4 with parameters {'dropout_rate': 0.047506, 'weight_decay': 2.6e-05, 'lr': 0.000823, 'batch_size': 128, 'early_stopping_patience': 38, 'n_layers': 3, 'hidden1': 256, 'hidden2': 512, 'hidden3': 512, 'activation': 'leaky_relu'} using model Sobol.

Fold 5 - MSE: 152.1973, RMSE: 12.3368, MAE: 11.1188

Mean CV MSE: 69.1331, Mean CV RMSE: 8.0200, Mean CV MAE: 5.9995
Completed trial 3 with mean RMSE: 8.0200 ± 1.0969
Saved Ax client checkpoint

Starting trial 4 with parameters: {'dropout_rate': 0.04750590957701206, 'weight_decay': 2.5574126909661948e-05, 'lr': 0.0008225891520342827, 'batch_size': 128, 'early_stopping_patience': 38, 'n_layers': 3, 'hidden1': 256, 'hidden2': 512, 'hidden3': 512, 'activation': 'leaky_relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 2.6309, Val Loss: 1.2526
  Epoch 10... Train Loss: 0.3814, Val Loss: 0.3735
  Epoch 20... Train Loss: 0.3090, Val Loss: 0.2843
  Epoch 30... Train Loss: 0.2752, Val Loss: 0.2952
  Epoch 40... Train Loss: 0.2474, Val Loss: 0.2865
  Epoch 50... Train Loss: 0.3070, Val Loss: 0.2635
  Epoch 60... Train Loss: 0.2462, Val Loss: 0.2465
  Epoch 70... Train Loss: 0.2270, Val Loss: 0.2701
Fold 1 - MSE: 46.6827, RMSE: 6.8325, MAE: 4.5006
Starting fold 2...
  Epoch 0... Train Loss: 1.9444, Val Loss: 0.7140
  Epoch 10... Train Loss: 0.2582, Val Loss: 0.6467
  Epoch 20... Train Loss: 0.2059, Val Loss: 0.3632
  Epoch 30... Train Loss: 0.2064, Val Loss: 0.3200
Fold 2 - MSE: 32.9145, RMSE: 5.7371, MAE: 3.5726
Starting fold 3...
  Epoch 0... Train Loss: 1.8015, Val Loss: 1.1624
  Epoch 10... Train Loss: 0.2552, Val Loss: 0.4975
  Epoch 20... Train Loss: 0.2082, Val Loss: 0.4136
  Epoch 30... Train Loss: 0.1877, Val Loss: 0.3399
  Epoch 40... Train Loss: 0.1664, Val Loss: 0.3429
  Epoch 50... Train Loss: 0.1546, Val Loss: 0.3393
  Epoch 60... Train Loss: 0.1518, Val Loss: 0.3394
Fold 3 - MSE: 18.2381, RMSE: 4.2706, MAE: 2.8592
Starting fold 4...
  Epoch 0... Train Loss: 2.1915, Val Loss: 0.6902
  Epoch 10... Train Loss: 0.2504, Val Loss: 0.4527
  Epoch 20... Train Loss: 0.1724, Val Loss: 0.6551
  Epoch 30... Train Loss: 0.1369, Val Loss: 0.3557
  Epoch 40... Train Loss: 0.1333, Val Loss: 0.4704
  Epoch 50... Train Loss: 0.1267, Val Loss: 0.3414
  Epoch 60... Train Loss: 0.1266, Val Loss: 0.3386
Fold 4 - MSE: 30.4814, RMSE: 5.5210, MAE: 4.4607
Starting fold 5...
  Epoch 0... Train Loss: 1.5357, Val Loss: 1.7165
  Epoch 10... Train Loss: 0.2922, Val Loss: 0.6778
  Epoch 20... Train Loss: 0.2467, Val Loss: 0.5932
  Epoch 30... Train Loss: 0.2435, Val Loss: 1.0790

[INFO 04-01 13:27:09] ax.service.ax_client: Completed trial 4 with data: {'avg_rmse_nonzero': 4.963898}.
[INFO 04-01 13:27:09] ax.service.ax_client: Generated new trial 5 with parameters {'dropout_rate': 0.266911, 'weight_decay': 0.000209, 'lr': 0.000176, 'batch_size': 32, 'early_stopping_patience': 19, 'n_layers': 2, 'hidden1': 2048, 'hidden2': 64, 'hidden3': 64, 'activation': 'selu'} using model Sobol.

  Epoch 40... Train Loss: 0.2087, Val Loss: 0.7596
Fold 5 - MSE: 6.0432, RMSE: 2.4583, MAE: 1.8974

Mean CV MSE: 26.8720, Mean CV RMSE: 4.9639, Mean CV MAE: 3.4581
Completed trial 4 with mean RMSE: 4.9639 ± 0.7469
Saved Ax client checkpoint

Starting trial 5 with parameters: {'dropout_rate': 0.26691109500825405, 'weight_decay': 0.00020913273450226142, 'lr': 0.00017635360474738633, 'batch_size': 32, 'early_stopping_patience': 19, 'n_layers': 2, 'hidden1': 2048, 'hidden2': 64, 'hidden3': 64, 'activation': 'selu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 2.4166, Val Loss: 2.0002
  Epoch 10... Train Loss: 0.6643, Val Loss: 0.5069
  Epoch 20... Train Loss: 0.5277, Val Loss: 0.5418
  Epoch 30... Train Loss: 0.4802, Val Loss: 0.3694
  Epoch 40... Train Loss: 0.4315, Val Loss: 0.3259
  Epoch 50... Train Loss: 0.4537, Val Loss: 0.3958
  Epoch 60... Train Loss: 0.4393, Val Loss: 0.3245
Fold 1 - MSE: 43.3380, RMSE: 6.5832, MAE: 4.4993
Starting fold 2...
  Epoch 0... Train Loss: 1.8678, Val Loss: 1.3982
  Epoch 10... Train Loss: 0.5530, Val Loss: 0.9102
  Epoch 20... Train Loss: 0.5140, Val Loss: 0.5736
  Epoch 30... Train Loss: 0.4731, Val Loss: 0.5592
  Epoch 40... Train Loss: 0.3737, Val Loss: 0.5315
  Epoch 50... Train Loss: 0.3228, Val Loss: 0.4847
  Epoch 60... Train Loss: 0.2948, Val Loss: 0.4740
Fold 2 - MSE: 53.8128, RMSE: 7.3357, MAE: 4.9387
Starting fold 3...
  Epoch 0... Train Loss: 1.8007, Val Loss: 1.1805
  Epoch 10... Train Loss: 0.5437, Val Loss: 0.5598
  Epoch 20... Train Loss: 0.4701, Val Loss: 0.5810
  Epoch 30... Train Loss: 0.3804, Val Loss: 0.5330
  Epoch 40... Train Loss: 0.3405, Val Loss: 0.4233
  Epoch 50... Train Loss: 0.3217, Val Loss: 0.4470
  Epoch 60... Train Loss: 0.3229, Val Loss: 0.4377
  Epoch 70... Train Loss: 0.2868, Val Loss: 0.4013
Fold 3 - MSE: 55.9121, RMSE: 7.4774, MAE: 4.6924
Starting fold 4...
  Epoch 0... Train Loss: 1.9723, Val Loss: 1.0756
  Epoch 10... Train Loss: 0.5158, Val Loss: 0.7337
  Epoch 20... Train Loss: 0.4344, Val Loss: 0.7055
  Epoch 30... Train Loss: 0.3675, Val Loss: 0.5298
  Epoch 40... Train Loss: 0.3132, Val Loss: 0.5498
  Epoch 50... Train Loss: 0.3077, Val Loss: 0.5204
  Epoch 60... Train Loss: 0.2308, Val Loss: 0.4875
  Epoch 70... Train Loss: 0.2172, Val Loss: 0.4817
Fold 4 - MSE: 36.8876, RMSE: 6.0735, MAE: 4.9316
Starting fold 5...
  Epoch 0... Train Loss: 1.5114, Val Loss: 1.4062
  Epoch 10... Train Loss: 0.6815, Val Loss: 1.1110
  Epoch 20... Train Loss: 0.4441, Val Loss: 0.8349
  Epoch 30... Train Loss: 0.3916, Val Loss: 0.7634
  Epoch 40... Train Loss: 0.3263, Val Loss: 0.8580
Fold 5 - MSE: 80.6274, RMSE: 8.9793, MAE: 8.2648

Mean CV MSE: 54.1156, Mean CV RMSE: 7.2898, Mean CV MAE: 5.4653

[INFO 04-01 13:27:33] ax.service.ax_client: Completed trial 5 with data: {'avg_rmse_nonzero': 7.289823}.
[INFO 04-01 13:27:33] ax.service.ax_client: Generated new trial 6 with parameters {'dropout_rate': 0.460244, 'weight_decay': 0.001079, 'lr': 0.003527, 'batch_size': 64, 'early_stopping_patience': 29, 'n_layers': 1, 'hidden1': 1024, 'hidden2': 128, 'hidden3': 128, 'activation': 'leaky_relu'} using model Sobol.

Completed trial 5 with mean RMSE: 7.2898 ± 0.4935
Saved Ax client checkpoint

Starting trial 6 with parameters: {'dropout_rate': 0.4602435170672834, 'weight_decay': 0.0010788575166543924, 'lr': 0.003526985518013465, 'batch_size': 64, 'early_stopping_patience': 29, 'n_layers': 1, 'hidden1': 1024, 'hidden2': 128, 'hidden3': 128, 'activation': 'leaky_relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 2.9024, Val Loss: 4.5391
  Epoch 10... Train Loss: 0.5119, Val Loss: 0.4074
  Epoch 20... Train Loss: 0.5007, Val Loss: 0.4349
  Epoch 30... Train Loss: 0.4024, Val Loss: 0.2692
  Epoch 40... Train Loss: 0.3086, Val Loss: 0.3032
  Epoch 50... Train Loss: 0.3511, Val Loss: 0.3755
  Epoch 60... Train Loss: 0.3155, Val Loss: 0.2706
  Epoch 70... Train Loss: 0.2912, Val Loss: 0.3611
Fold 1 - MSE: 41.0522, RMSE: 6.4072, MAE: 4.2689
Starting fold 2...
  Epoch 0... Train Loss: 4.5490, Val Loss: 1.8497
  Epoch 10... Train Loss: 0.4736, Val Loss: 0.7055
  Epoch 20... Train Loss: 0.4486, Val Loss: 0.5900
  Epoch 30... Train Loss: 0.5169, Val Loss: 0.7586
  Epoch 40... Train Loss: 0.3755, Val Loss: 0.6034
  Epoch 50... Train Loss: 0.2855, Val Loss: 0.5750
  Epoch 60... Train Loss: 0.2709, Val Loss: 0.3790
  Epoch 70... Train Loss: 0.3014, Val Loss: 0.3752
  Epoch 80... Train Loss: 0.2843, Val Loss: 0.3944
  Epoch 90... Train Loss: 0.2543, Val Loss: 0.3592
Fold 2 - MSE: 36.6146, RMSE: 6.0510, MAE: 3.5477
Starting fold 3...
  Epoch 0... Train Loss: 4.5264, Val Loss: 3.2435
  Epoch 10... Train Loss: 0.5007, Val Loss: 0.6618
  Epoch 20... Train Loss: 0.4245, Val Loss: 0.4991
  Epoch 30... Train Loss: 0.4186, Val Loss: 0.5086
  Epoch 40... Train Loss: 0.4092, Val Loss: 0.7101
  Epoch 50... Train Loss: 0.3119, Val Loss: 0.4494
  Epoch 60... Train Loss: 0.2797, Val Loss: 0.3821
  Epoch 70... Train Loss: 0.2804, Val Loss: 0.4701
  Epoch 80... Train Loss: 0.2453, Val Loss: 0.3585
Fold 3 - MSE: 114.4704, RMSE: 10.6991, MAE: 5.3710
Starting fold 4...
  Epoch 0... Train Loss: 3.6724, Val Loss: 1.2962
  Epoch 10... Train Loss: 0.4324, Val Loss: 0.4642
  Epoch 20... Train Loss: 0.4207, Val Loss: 0.5695
  Epoch 30... Train Loss: 0.3088, Val Loss: 0.3970
  Epoch 40... Train Loss: 0.2467, Val Loss: 0.4655
  Epoch 50... Train Loss: 0.2096, Val Loss: 0.3973
Fold 4 - MSE: 31.9371, RMSE: 5.6513, MAE: 4.4717
Starting fold 5...
  Epoch 0... Train Loss: 4.6613, Val Loss: 3.5705
  Epoch 10... Train Loss: 0.4932, Val Loss: 1.0458
  Epoch 20... Train Loss: 0.4006, Val Loss: 0.8311
  Epoch 30... Train Loss: 0.3768, Val Loss: 1.0641
  Epoch 40... Train Loss: 0.4164, Val Loss: 0.7610
  Epoch 50... Train Loss: 0.3151, Val Loss: 0.7727
  Epoch 60... Train Loss: 0.2897, Val Loss: 0.8899
  Epoch 70... Train Loss: 0.2939, Val Loss: 0.6829
  Epoch 80... Train Loss: 0.2432, Val Loss: 0.7783

[INFO 04-01 13:27:46] ax.service.ax_client: Completed trial 6 with data: {'avg_rmse_nonzero': 8.395189}.
[INFO 04-01 13:27:46] ax.service.ax_client: Generated new trial 7 with parameters {'dropout_rate': 0.24096, 'weight_decay': 2e-06, 'lr': 1.6e-05, 'batch_size': 256, 'early_stopping_patience': 47, 'n_layers': 3, 'hidden1': 128, 'hidden2': 512, 'hidden3': 64, 'activation': 'elu'} using model Sobol.

  Epoch 90... Train Loss: 0.2310, Val Loss: 0.7772
Fold 5 - MSE: 173.3798, RMSE: 13.1674, MAE: 11.8082

Mean CV MSE: 79.4908, Mean CV RMSE: 8.3952, Mean CV MAE: 5.8935
Completed trial 6 with mean RMSE: 8.3952 ± 1.5010
Saved Ax client checkpoint

Starting trial 7 with parameters: {'dropout_rate': 0.2409604243002832, 'weight_decay': 1.5689178098109729e-06, 'lr': 1.554030980730576e-05, 'batch_size': 256, 'early_stopping_patience': 47, 'n_layers': 3, 'hidden1': 128, 'hidden2': 512, 'hidden3': 64, 'activation': 'elu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 1.4869, Val Loss: 0.8746
  Epoch 10... Train Loss: 0.6153, Val Loss: 0.5180
  Epoch 20... Train Loss: 0.5973, Val Loss: 0.3517
  Epoch 30... Train Loss: 0.4400, Val Loss: 0.3813
  Epoch 40... Train Loss: 0.5443, Val Loss: 0.3608
Fold 1 - MSE: 39.5725, RMSE: 6.2907, MAE: 4.2515
Starting fold 2...
  Epoch 0... Train Loss: 1.0860, Val Loss: 0.9780
  Epoch 10... Train Loss: 0.6210, Val Loss: 0.6519
  Epoch 20... Train Loss: 0.4416, Val Loss: 0.6960
Fold 2 - MSE: 60.8647, RMSE: 7.8016, MAE: 5.9465
Starting fold 3...
  Epoch 0... Train Loss: 1.0903, Val Loss: 1.0638
  Epoch 10... Train Loss: 0.5449, Val Loss: 0.5485
  Epoch 20... Train Loss: 0.4759, Val Loss: 0.5075
  Epoch 30... Train Loss: 0.4885, Val Loss: 0.4767
  Epoch 40... Train Loss: 0.3881, Val Loss: 0.4729
  Epoch 50... Train Loss: 0.3609, Val Loss: 0.4870
  Epoch 60... Train Loss: 0.3727, Val Loss: 0.4361
  Epoch 70... Train Loss: 0.3980, Val Loss: 0.4412
  Epoch 80... Train Loss: 0.3453, Val Loss: 0.4387
Fold 3 - MSE: 57.7907, RMSE: 7.6020, MAE: 4.5842
Starting fold 4...
  Epoch 0... Train Loss: 1.1617, Val Loss: 0.6340
  Epoch 10... Train Loss: 0.5765, Val Loss: 0.5084
  Epoch 20... Train Loss: 0.4088, Val Loss: 0.5148
Fold 4 - MSE: 32.7550, RMSE: 5.7232, MAE: 4.3839
Starting fold 5...
  Epoch 0... Train Loss: 1.1102, Val Loss: 1.3357
  Epoch 10... Train Loss: 0.5660, Val Loss: 0.9738
  Epoch 20... Train Loss: 0.4891, Val Loss: 0.9636
  Epoch 30... Train Loss: 0.4413, Val Loss: 0.8996
  Epoch 40... Train Loss: 0.4332, Val Loss: 0.8701

[INFO 04-01 13:27:52] ax.service.ax_client: Completed trial 7 with data: {'avg_rmse_nonzero': 7.798571}.
[INFO 04-01 13:27:52] ax.service.ax_client: Generated new trial 8 with parameters {'dropout_rate': 0.210975, 'weight_decay': 7e-06, 'lr': 0.001467, 'batch_size': 128, 'early_stopping_patience': 39, 'n_layers': 1, 'hidden1': 128, 'hidden2': 256, 'hidden3': 32, 'activation': 'leaky_relu'} using model Sobol.

  Epoch 50... Train Loss: 0.4398, Val Loss: 0.8733
Fold 5 - MSE: 133.9895, RMSE: 11.5754, MAE: 10.7486

Mean CV MSE: 64.9945, Mean CV RMSE: 7.7986, Mean CV MAE: 5.9829
Completed trial 7 with mean RMSE: 7.7986 ± 1.0219
Saved Ax client checkpoint

Starting trial 8 with parameters: {'dropout_rate': 0.21097537502646446, 'weight_decay': 7.27096406893596e-06, 'lr': 0.00146733176713039, 'batch_size': 128, 'early_stopping_patience': 39, 'n_layers': 1, 'hidden1': 128, 'hidden2': 256, 'hidden3': 32, 'activation': 'leaky_relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 12.9073, Val Loss: 5.3679
  Epoch 10... Train Loss: 0.6121, Val Loss: 0.6810
  Epoch 20... Train Loss: 0.4276, Val Loss: 0.4443
  Epoch 30... Train Loss: 0.3751, Val Loss: 0.4216
  Epoch 40... Train Loss: 0.3207, Val Loss: 0.4000
  Epoch 50... Train Loss: 0.3473, Val Loss: 0.4224
Fold 1 - MSE: 41.3673, RMSE: 6.4317, MAE: 4.3620
Starting fold 2...
  Epoch 0... Train Loss: 10.0252, Val Loss: 11.3472
  Epoch 10... Train Loss: 0.4346, Val Loss: 1.0850
  Epoch 20... Train Loss: 0.3356, Val Loss: 0.7231
  Epoch 30... Train Loss: 0.3318, Val Loss: 0.7453
  Epoch 40... Train Loss: 0.2922, Val Loss: 0.6571
Fold 2 - MSE: 51.1040, RMSE: 7.1487, MAE: 5.1105
Starting fold 3...
  Epoch 0... Train Loss: 8.7081, Val Loss: 9.6931
  Epoch 10... Train Loss: 0.4354, Val Loss: 0.5988
  Epoch 20... Train Loss: 0.3316, Val Loss: 0.4704
  Epoch 30... Train Loss: 0.2816, Val Loss: 0.3725
  Epoch 40... Train Loss: 0.2365, Val Loss: 0.3774
  Epoch 50... Train Loss: 0.2180, Val Loss: 0.4250
  Epoch 60... Train Loss: 0.2074, Val Loss: 0.3644
Fold 3 - MSE: 88.6573, RMSE: 9.4158, MAE: 5.8756
Starting fold 4...
  Epoch 0... Train Loss: 7.5399, Val Loss: 20.3386
  Epoch 10... Train Loss: 0.4249, Val Loss: 0.4878
  Epoch 20... Train Loss: 0.3105, Val Loss: 0.6760
Fold 4 - MSE: 43.2114, RMSE: 6.5735, MAE: 5.0963
Starting fold 5...
  Epoch 0... Train Loss: 7.6652, Val Loss: 6.5479
  Epoch 10... Train Loss: 0.4512, Val Loss: 0.8149
  Epoch 20... Train Loss: 0.2991, Val Loss: 0.6505
  Epoch 30... Train Loss: 0.2717, Val Loss: 1.0033
  Epoch 40... Train Loss: 0.2746, Val Loss: 0.7547
Fold 5 - MSE: 8.7216, RMSE: 2.9532, MAE: 2.3103

Mean CV MSE: 46.6123, Mean CV RMSE: 6.5046, Mean CV MAE: 4.5509

[INFO 04-01 13:27:56] ax.service.ax_client: Completed trial 8 with data: {'avg_rmse_nonzero': 6.504607}.
[INFO 04-01 13:27:56] ax.service.ax_client: Generated new trial 9 with parameters {'dropout_rate': 0.494132, 'weight_decay': 0.007983, 'lr': 0.000216, 'batch_size': 32, 'early_stopping_patience': 17, 'n_layers': 2, 'hidden1': 512, 'hidden2': 256, 'hidden3': 512, 'activation': 'relu'} using model Sobol.

Completed trial 8 with mean RMSE: 6.5046 ± 1.0371
Saved Ax client checkpoint

Starting trial 9 with parameters: {'dropout_rate': 0.4941317141056061, 'weight_decay': 0.007982833514767852, 'lr': 0.0002158025837337766, 'batch_size': 32, 'early_stopping_patience': 17, 'n_layers': 2, 'hidden1': 512, 'hidden2': 256, 'hidden3': 512, 'activation': 'relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 1.0261, Val Loss: 0.7671
  Epoch 10... Train Loss: 0.6209, Val Loss: 0.4203
  Epoch 20... Train Loss: 0.5060, Val Loss: 0.4667
  Epoch 30... Train Loss: 0.5338, Val Loss: 0.3583
  Epoch 40... Train Loss: 0.4529, Val Loss: 0.3083
Fold 1 - MSE: 40.2462, RMSE: 6.3440, MAE: 4.3223
Starting fold 2...
  Epoch 0... Train Loss: 1.0959, Val Loss: 0.7586
  Epoch 10... Train Loss: 0.5940, Val Loss: 0.6665
  Epoch 20... Train Loss: 0.4702, Val Loss: 0.4852
  Epoch 30... Train Loss: 0.3722, Val Loss: 0.4637
  Epoch 40... Train Loss: 0.3478, Val Loss: 0.5091
  Epoch 50... Train Loss: 0.2829, Val Loss: 0.4519
  Epoch 60... Train Loss: 0.2902, Val Loss: 0.4256
  Epoch 70... Train Loss: 0.2938, Val Loss: 0.4225
  Epoch 80... Train Loss: 0.2981, Val Loss: 0.4164
  Epoch 90... Train Loss: 0.2917, Val Loss: 0.4004
  Epoch 100... Train Loss: 0.2562, Val Loss: 0.3981
  Epoch 110... Train Loss: 0.3057, Val Loss: 0.4121
  Epoch 120... Train Loss: 0.2705, Val Loss: 0.4365
  Epoch 130... Train Loss: 0.2958, Val Loss: 0.4345
Fold 2 - MSE: 42.8900, RMSE: 6.5490, MAE: 3.9360
Starting fold 3...
  Epoch 0... Train Loss: 1.0357, Val Loss: 1.0670
  Epoch 10... Train Loss: 0.5409, Val Loss: 0.4820
  Epoch 20... Train Loss: 0.4354, Val Loss: 0.4367
  Epoch 30... Train Loss: 0.3599, Val Loss: 0.4019
  Epoch 40... Train Loss: 0.3430, Val Loss: 0.4260
  Epoch 50... Train Loss: 0.3109, Val Loss: 0.3788
  Epoch 60... Train Loss: 0.2601, Val Loss: 0.3811
  Epoch 70... Train Loss: 0.2652, Val Loss: 0.3725
Fold 3 - MSE: 61.8110, RMSE: 7.8620, MAE: 4.2846
Starting fold 4...
  Epoch 0... Train Loss: 1.0184, Val Loss: 1.3698
  Epoch 10... Train Loss: 0.5337, Val Loss: 0.5188
  Epoch 20... Train Loss: 0.3806, Val Loss: 0.5109
  Epoch 30... Train Loss: 0.3392, Val Loss: 0.5168
  Epoch 40... Train Loss: 0.3045, Val Loss: 0.5206
Fold 4 - MSE: 36.2707, RMSE: 6.0225, MAE: 4.6919
Starting fold 5...
  Epoch 0... Train Loss: 1.0844, Val Loss: 1.5924
  Epoch 10... Train Loss: 0.5907, Val Loss: 0.9255
  Epoch 20... Train Loss: 0.4671, Val Loss: 0.6813
  Epoch 30... Train Loss: 0.3469, Val Loss: 0.6863

[INFO 04-01 13:28:19] ax.service.ax_client: Completed trial 9 with data: {'avg_rmse_nonzero': 5.996028}.
[INFO 04-01 13:28:19] ax.service.ax_client: Generated new trial 10 with parameters {'dropout_rate': 0.312403, 'weight_decay': 0.000545, 'lr': 0.001924, 'batch_size': 64, 'early_stopping_patience': 27, 'n_layers': 3, 'hidden1': 1024, 'hidden2': 64, 'hidden3': 64, 'activation': 'elu'} using model Sobol.

  Epoch 40... Train Loss: 0.3289, Val Loss: 0.7873
Fold 5 - MSE: 10.2566, RMSE: 3.2026, MAE: 2.5338

Mean CV MSE: 38.2949, Mean CV RMSE: 5.9960, Mean CV MAE: 3.9537
Completed trial 9 with mean RMSE: 5.9960 ± 0.7653
Saved Ax client checkpoint

Starting trial 10 with parameters: {'dropout_rate': 0.3124031717889011, 'weight_decay': 0.0005450049045275986, 'lr': 0.0019244930125581292, 'batch_size': 64, 'early_stopping_patience': 27, 'n_layers': 3, 'hidden1': 1024, 'hidden2': 64, 'hidden3': 64, 'activation': 'elu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 11.1328, Val Loss: 3.1723
  Epoch 10... Train Loss: 0.6126, Val Loss: 0.4909
  Epoch 20... Train Loss: 0.4588, Val Loss: 0.4060
  Epoch 30... Train Loss: 0.3991, Val Loss: 0.2818
  Epoch 40... Train Loss: 0.3446, Val Loss: 0.3024
  Epoch 50... Train Loss: 0.3572, Val Loss: 0.4959
  Epoch 60... Train Loss: 0.3427, Val Loss: 0.2854
Fold 1 - MSE: 49.7968, RMSE: 7.0567, MAE: 4.7553
Starting fold 2...
  Epoch 0... Train Loss: 9.4990, Val Loss: 5.9362
  Epoch 10... Train Loss: 0.5126, Val Loss: 0.9618
  Epoch 20... Train Loss: 0.4182, Val Loss: 0.5672
  Epoch 30... Train Loss: 0.3741, Val Loss: 0.5663
  Epoch 40... Train Loss: 0.3288, Val Loss: 0.5416
  Epoch 50... Train Loss: 0.2787, Val Loss: 0.5086
  Epoch 60... Train Loss: 0.2717, Val Loss: 0.3723
  Epoch 70... Train Loss: 0.2895, Val Loss: 0.3994
  Epoch 80... Train Loss: 0.2724, Val Loss: 0.4090
Fold 2 - MSE: 44.7605, RMSE: 6.6903, MAE: 3.9859
Starting fold 3...
  Epoch 0... Train Loss: 6.8573, Val Loss: 4.8087
  Epoch 10... Train Loss: 0.4562, Val Loss: 0.6194
  Epoch 20... Train Loss: 0.3780, Val Loss: 0.4982
  Epoch 30... Train Loss: 0.3317, Val Loss: 0.4856
  Epoch 40... Train Loss: 0.3020, Val Loss: 0.4087
  Epoch 50... Train Loss: 0.2567, Val Loss: 0.4221
  Epoch 60... Train Loss: 0.2535, Val Loss: 0.3994
  Epoch 70... Train Loss: 0.2243, Val Loss: 0.4230
  Epoch 80... Train Loss: 0.2362, Val Loss: 0.3587
  Epoch 90... Train Loss: 0.2237, Val Loss: 0.3656
Fold 3 - MSE: 98.5239, RMSE: 9.9259, MAE: 5.5036
Starting fold 4...
  Epoch 0... Train Loss: 8.7456, Val Loss: 5.4927
  Epoch 10... Train Loss: 0.5200, Val Loss: 0.4998
  Epoch 20... Train Loss: 0.3424, Val Loss: 0.5210
Fold 4 - MSE: 37.2024, RMSE: 6.0994, MAE: 4.8464
Starting fold 5...
  Epoch 0... Train Loss: 9.5457, Val Loss: 2.4957
  Epoch 10... Train Loss: 0.5299, Val Loss: 1.0059
  Epoch 20... Train Loss: 0.4405, Val Loss: 0.9974
  Epoch 30... Train Loss: 0.3639, Val Loss: 1.1041
  Epoch 40... Train Loss: 0.3060, Val Loss: 0.8723

[INFO 04-01 13:28:34] ax.service.ax_client: Completed trial 10 with data: {'avg_rmse_nonzero': 7.271291}.
[INFO 04-01 13:28:34] ax.service.ax_client: Generated new trial 11 with parameters {'dropout_rate': 0.029369, 'weight_decay': 3.4e-05, 'lr': 1.4e-05, 'batch_size': 256, 'early_stopping_patience': 50, 'n_layers': 1, 'hidden1': 256, 'hidden2': 1024, 'hidden3': 128, 'activation': 'relu'} using model Sobol.

Fold 5 - MSE: 43.3510, RMSE: 6.5841, MAE: 6.1230

Mean CV MSE: 54.7269, Mean CV RMSE: 7.2713, Mean CV MAE: 5.0429
Completed trial 10 with mean RMSE: 7.2713 ± 0.6810
Saved Ax client checkpoint

Starting trial 11 with parameters: {'dropout_rate': 0.02936879126355052, 'weight_decay': 3.364729114228847e-05, 'lr': 1.3771044115807327e-05, 'batch_size': 256, 'early_stopping_patience': 50, 'n_layers': 1, 'hidden1': 256, 'hidden2': 1024, 'hidden3': 128, 'activation': 'relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 1.3321, Val Loss: 0.8884
  Epoch 10... Train Loss: 0.5449, Val Loss: 0.5320
  Epoch 20... Train Loss: 0.3306, Val Loss: 0.3750
  Epoch 30... Train Loss: 0.2919, Val Loss: 0.4181
  Epoch 40... Train Loss: 0.2592, Val Loss: 0.3432
  Epoch 50... Train Loss: 0.3084, Val Loss: 0.3820
  Epoch 60... Train Loss: 0.2734, Val Loss: 0.3296
  Epoch 70... Train Loss: 0.2426, Val Loss: 0.3242
  Epoch 80... Train Loss: 0.3259, Val Loss: 0.3358
Fold 1 - MSE: 41.1361, RMSE: 6.4137, MAE: 4.4716
Starting fold 2...
  Epoch 0... Train Loss: 0.9673, Val Loss: 0.8744
  Epoch 10... Train Loss: 0.4054, Val Loss: 0.5666
  Epoch 20... Train Loss: 0.2521, Val Loss: 0.5561
  Epoch 30... Train Loss: 0.2688, Val Loss: 0.5061
  Epoch 40... Train Loss: 0.2204, Val Loss: 0.4996
  Epoch 50... Train Loss: 0.2408, Val Loss: 0.4896
  Epoch 60... Train Loss: 0.2409, Val Loss: 0.4797
  Epoch 70... Train Loss: 0.2453, Val Loss: 0.4802
  Epoch 80... Train Loss: 0.2258, Val Loss: 0.4879
  Epoch 90... Train Loss: 0.2483, Val Loss: 0.4830
Fold 2 - MSE: 31.7672, RMSE: 5.6362, MAE: 3.6820
Starting fold 3...
  Epoch 0... Train Loss: 1.5031, Val Loss: 1.1603
  Epoch 10... Train Loss: 0.3973, Val Loss: 0.5826
  Epoch 20... Train Loss: 0.2745, Val Loss: 0.4905
  Epoch 30... Train Loss: 0.2584, Val Loss: 0.4526
  Epoch 40... Train Loss: 0.2066, Val Loss: 0.4244
  Epoch 50... Train Loss: 0.2097, Val Loss: 0.4132
  Epoch 60... Train Loss: 0.1834, Val Loss: 0.4130
  Epoch 70... Train Loss: 0.1878, Val Loss: 0.3899
  Epoch 80... Train Loss: 0.1805, Val Loss: 0.3884
  Epoch 90... Train Loss: 0.1773, Val Loss: 0.3859
  Epoch 100... Train Loss: 0.1951, Val Loss: 0.3815
  Epoch 110... Train Loss: 0.1739, Val Loss: 0.3833
Fold 3 - MSE: 52.6414, RMSE: 7.2554, MAE: 4.4661
Starting fold 4...
  Epoch 0... Train Loss: 1.0224, Val Loss: 1.1386
  Epoch 10... Train Loss: 0.3844, Val Loss: 0.9615
  Epoch 20... Train Loss: 0.2488, Val Loss: 1.2140
Fold 4 - MSE: 61.4552, RMSE: 7.8393, MAE: 6.3284
Starting fold 5...
  Epoch 0... Train Loss: 0.9719, Val Loss: 1.3231
  Epoch 10... Train Loss: 0.3745, Val Loss: 0.9723
  Epoch 20... Train Loss: 0.2735, Val Loss: 0.8411
  Epoch 30... Train Loss: 0.2365, Val Loss: 0.7697
  Epoch 40... Train Loss: 0.2169, Val Loss: 0.7727
  Epoch 50... Train Loss: 0.1928, Val Loss: 0.7710

[INFO 04-01 13:28:40] ax.service.ax_client: Completed trial 11 with data: {'avg_rmse_nonzero': 7.927451}.
[INFO 04-01 13:28:40] ax.service.ax_client: Generated new trial 12 with parameters {'dropout_rate': 0.099449, 'weight_decay': 3e-06, 'lr': 0.004293, 'batch_size': 64, 'early_stopping_patience': 20, 'n_layers': 2, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 128, 'activation': 'selu'} using model Sobol.

  Epoch 60... Train Loss: 0.1820, Val Loss: 0.7419
Fold 5 - MSE: 156.0624, RMSE: 12.4925, MAE: 11.5680

Mean CV MSE: 68.6125, Mean CV RMSE: 7.9275, Mean CV MAE: 6.1032
Completed trial 11 with mean RMSE: 7.9275 ± 1.2008
Saved Ax client checkpoint

Starting trial 12 with parameters: {'dropout_rate': 0.09944870602339506, 'weight_decay': 2.6285444318480225e-06, 'lr': 0.004293222632331673, 'batch_size': 64, 'early_stopping_patience': 20, 'n_layers': 2, 'hidden1': 2048, 'hidden2': 1024, 'hidden3': 128, 'activation': 'selu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 85.1518, Val Loss: 129.8862
  Epoch 10... Train Loss: 1.1220, Val Loss: 0.6470
  Epoch 20... Train Loss: 0.6250, Val Loss: 0.5805
  Epoch 30... Train Loss: 0.5258, Val Loss: 0.4279
  Epoch 40... Train Loss: 0.4551, Val Loss: 0.3921
  Epoch 50... Train Loss: 0.4645, Val Loss: 0.6684
  Epoch 60... Train Loss: 0.3975, Val Loss: 0.3447
  Epoch 70... Train Loss: 0.3886, Val Loss: 0.3892
Fold 1 - MSE: 43.2644, RMSE: 6.5776, MAE: 4.5765
Starting fold 2...
  Epoch 0... Train Loss: 44.8011, Val Loss: 142.0683
  Epoch 10... Train Loss: 0.5664, Val Loss: 1.0784
  Epoch 20... Train Loss: 0.4578, Val Loss: 0.7524
  Epoch 30... Train Loss: 0.4089, Val Loss: 0.7181
  Epoch 40... Train Loss: 0.3637, Val Loss: 0.6601
Fold 2 - MSE: 48.0698, RMSE: 6.9332, MAE: 4.6849
Starting fold 3...
  Epoch 0... Train Loss: 49.7659, Val Loss: 128.5387
  Epoch 10... Train Loss: 0.6264, Val Loss: 0.8180
  Epoch 20... Train Loss: 0.4666, Val Loss: 0.6296
  Epoch 30... Train Loss: 0.3915, Val Loss: 0.5479
  Epoch 40... Train Loss: 0.3758, Val Loss: 0.4793
  Epoch 50... Train Loss: 0.3306, Val Loss: 0.4828
  Epoch 60... Train Loss: 0.3013, Val Loss: 0.4958
  Epoch 70... Train Loss: 0.2805, Val Loss: 0.5072
  Epoch 80... Train Loss: 0.2823, Val Loss: 0.4205
  Epoch 90... Train Loss: 0.2776, Val Loss: 0.4481
Fold 3 - MSE: 72.2086, RMSE: 8.4976, MAE: 5.1981
Starting fold 4...
  Epoch 0... Train Loss: 52.0545, Val Loss: 156.9288
  Epoch 10... Train Loss: 0.6786, Val Loss: 0.4975
  Epoch 20... Train Loss: 0.4483, Val Loss: 0.6193
  Epoch 30... Train Loss: 0.3639, Val Loss: 0.5727
Fold 4 - MSE: 37.4373, RMSE: 6.1186, MAE: 4.7436
Starting fold 5...
  Epoch 0... Train Loss: 45.7201, Val Loss: 106.5885
  Epoch 10... Train Loss: 0.6409, Val Loss: 1.2435
  Epoch 20... Train Loss: 0.4760, Val Loss: 1.0821
  Epoch 30... Train Loss: 0.3974, Val Loss: 1.0517
  Epoch 40... Train Loss: 0.5441, Val Loss: 0.9520
  Epoch 50... Train Loss: 0.3416, Val Loss: 0.8088
  Epoch 60... Train Loss: 0.3172, Val Loss: 0.8767
  Epoch 70... Train Loss: 0.3018, Val Loss: 0.8377
  Epoch 80... Train Loss: 0.3063, Val Loss: 0.8181

[INFO 04-01 13:28:52] ax.service.ax_client: Completed trial 12 with data: {'avg_rmse_nonzero': 6.166118}.
[INFO 04-01 13:28:52] ax.service.ax_client: Generated new trial 13 with parameters {'dropout_rate': 0.316535, 'weight_decay': 0.002073, 'lr': 3.1e-05, 'batch_size': 256, 'early_stopping_patience': 44, 'n_layers': 1, 'hidden1': 512, 'hidden2': 64, 'hidden3': 256, 'activation': 'leaky_relu'} using model Sobol.

Fold 5 - MSE: 7.3095, RMSE: 2.7036, MAE: 2.3487

Mean CV MSE: 41.6579, Mean CV RMSE: 6.1661, Mean CV MAE: 4.3104
Completed trial 12 with mean RMSE: 6.1661 ± 0.9535
Saved Ax client checkpoint

Starting trial 13 with parameters: {'dropout_rate': 0.3165346151217818, 'weight_decay': 0.0020733149031110037, 'lr': 3.073463859608142e-05, 'batch_size': 256, 'early_stopping_patience': 44, 'n_layers': 1, 'hidden1': 512, 'hidden2': 64, 'hidden3': 256, 'activation': 'leaky_relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 1.2833, Val Loss: 0.8324
  Epoch 10... Train Loss: 0.5039, Val Loss: 0.4266
  Epoch 20... Train Loss: 0.4132, Val Loss: 0.3295
  Epoch 30... Train Loss: 0.3125, Val Loss: 0.3813
  Epoch 40... Train Loss: 0.3202, Val Loss: 0.3071
  Epoch 50... Train Loss: 0.3384, Val Loss: 0.3241
  Epoch 60... Train Loss: 0.3379, Val Loss: 0.3100
Fold 1 - MSE: 38.6017, RMSE: 6.2130, MAE: 4.3865
Starting fold 2...
  Epoch 0... Train Loss: 1.0049, Val Loss: 0.8606
  Epoch 10... Train Loss: 0.3932, Val Loss: 0.6627
  Epoch 20... Train Loss: 0.2768, Val Loss: 0.6011
  Epoch 30... Train Loss: 0.3146, Val Loss: 0.5911
  Epoch 40... Train Loss: 0.2538, Val Loss: 0.5642
Fold 2 - MSE: 25.7127, RMSE: 5.0708, MAE: 3.5286
Starting fold 3...
  Epoch 0... Train Loss: 1.0006, Val Loss: 0.9056
  Epoch 10... Train Loss: 0.3825, Val Loss: 0.5094
  Epoch 20... Train Loss: 0.3174, Val Loss: 0.4658
  Epoch 30... Train Loss: 0.2896, Val Loss: 0.4049
  Epoch 40... Train Loss: 0.2457, Val Loss: 0.4293
  Epoch 50... Train Loss: 0.2555, Val Loss: 0.3950
Fold 3 - MSE: 64.2310, RMSE: 8.0144, MAE: 5.4528
Starting fold 4...
  Epoch 0... Train Loss: 1.1945, Val Loss: 0.7442
  Epoch 10... Train Loss: 0.4165, Val Loss: 0.4865
  Epoch 20... Train Loss: 0.2601, Val Loss: 0.4692
  Epoch 30... Train Loss: 0.2556, Val Loss: 0.5106
  Epoch 40... Train Loss: 0.2667, Val Loss: 0.4766
Fold 4 - MSE: 36.0839, RMSE: 6.0070, MAE: 4.9714
Starting fold 5...
  Epoch 0... Train Loss: 0.9860, Val Loss: 1.2168
  Epoch 10... Train Loss: 0.3942, Val Loss: 0.8705
  Epoch 20... Train Loss: 0.2986, Val Loss: 0.7310
  Epoch 30... Train Loss: 0.2788, Val Loss: 0.7098

[INFO 04-01 13:28:56] ax.service.ax_client: Completed trial 13 with data: {'avg_rmse_nonzero': 8.530607}.
[INFO 04-01 13:28:56] ax.service.ax_client: Generated new trial 14 with parameters {'dropout_rate': 0.377177, 'weight_decay': 0.000111, 'lr': 0.000649, 'batch_size': 128, 'early_stopping_patience': 33, 'n_layers': 2, 'hidden1': 256, 'hidden2': 128, 'hidden3': 32, 'activation': 'leaky_relu'} using model Sobol.

  Epoch 40... Train Loss: 0.2695, Val Loss: 0.7172
  Epoch 50... Train Loss: 0.2515, Val Loss: 0.7243
Fold 5 - MSE: 300.9470, RMSE: 17.3478, MAE: 15.2432

Mean CV MSE: 93.1153, Mean CV RMSE: 8.5306, Mean CV MAE: 6.7165
Completed trial 13 with mean RMSE: 8.5306 ± 2.2552
Saved Ax client checkpoint

Starting trial 14 with parameters: {'dropout_rate': 0.37717654602602124, 'weight_decay': 0.0001108021328665583, 'lr': 0.0006491418188901245, 'batch_size': 128, 'early_stopping_patience': 33, 'n_layers': 2, 'hidden1': 256, 'hidden2': 128, 'hidden3': 32, 'activation': 'leaky_relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 1.3926, Val Loss: 1.0967
  Epoch 10... Train Loss: 0.5260, Val Loss: 0.3804
  Epoch 20... Train Loss: 0.4218, Val Loss: 0.3215
  Epoch 30... Train Loss: 0.4334, Val Loss: 0.3731
  Epoch 40... Train Loss: 0.3390, Val Loss: 0.2791
Fold 1 - MSE: 45.5497, RMSE: 6.7491, MAE: 4.5215
Starting fold 2...
  Epoch 0... Train Loss: 1.7915, Val Loss: 0.7855
  Epoch 10... Train Loss: 0.4228, Val Loss: 0.7966
  Epoch 20... Train Loss: 0.3158, Val Loss: 0.4740
  Epoch 30... Train Loss: 0.3017, Val Loss: 0.3985
  Epoch 40... Train Loss: 0.2598, Val Loss: 0.5855
  Epoch 50... Train Loss: 0.2784, Val Loss: 0.4105
Fold 2 - MSE: 41.7601, RMSE: 6.4622, MAE: 3.7991
Starting fold 3...
  Epoch 0... Train Loss: 1.5768, Val Loss: 1.3540
  Epoch 10... Train Loss: 0.4213, Val Loss: 0.5632
  Epoch 20... Train Loss: 0.3048, Val Loss: 0.4709
  Epoch 30... Train Loss: 0.2737, Val Loss: 0.4231
  Epoch 40... Train Loss: 0.2444, Val Loss: 0.3718
  Epoch 50... Train Loss: 0.2523, Val Loss: 0.3940
Fold 3 - MSE: 41.2622, RMSE: 6.4236, MAE: 3.7091
Starting fold 4...
  Epoch 0... Train Loss: 1.5460, Val Loss: 0.5162
  Epoch 10... Train Loss: 0.4096, Val Loss: 0.3985
  Epoch 20... Train Loss: 0.2721, Val Loss: 0.5837
  Epoch 30... Train Loss: 0.2443, Val Loss: 0.3778
Fold 4 - MSE: 45.2325, RMSE: 6.7255, MAE: 4.9425
Starting fold 5...
  Epoch 0... Train Loss: 1.4396, Val Loss: 1.4010
  Epoch 10... Train Loss: 0.4941, Val Loss: 0.6535
  Epoch 20... Train Loss: 0.3293, Val Loss: 0.5684
  Epoch 30... Train Loss: 0.2670, Val Loss: 0.9759

[INFO 04-01 13:29:01] ax.service.ax_client: Completed trial 14 with data: {'avg_rmse_nonzero': 5.695637}.
[INFO 04-01 13:29:01] ax.service.ax_client: Generated new trial 15 with parameters {'dropout_rate': 0.159969, 'weight_decay': 1.6e-05, 'lr': 9.5e-05, 'batch_size': 32, 'early_stopping_patience': 10, 'n_layers': 3, 'hidden1': 1024, 'hidden2': 512, 'hidden3': 512, 'activation': 'leaky_relu'} using model Sobol.

  Epoch 40... Train Loss: 0.3012, Val Loss: 0.7711
Fold 5 - MSE: 4.4853, RMSE: 2.1179, MAE: 1.6029

Mean CV MSE: 35.6580, Mean CV RMSE: 5.6956, Mean CV MAE: 3.7150
Completed trial 14 with mean RMSE: 5.6956 ± 0.8969
Saved Ax client checkpoint

Starting trial 15 with parameters: {'dropout_rate': 0.15996870817616582, 'weight_decay': 1.554115902858659e-05, 'lr': 9.534694176544704e-05, 'batch_size': 32, 'early_stopping_patience': 10, 'n_layers': 3, 'hidden1': 1024, 'hidden2': 512, 'hidden3': 512, 'activation': 'leaky_relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 1.0896, Val Loss: 0.7058
  Epoch 10... Train Loss: 0.4313, Val Loss: 0.3080
  Epoch 20... Train Loss: 0.4247, Val Loss: 0.5604
  Epoch 30... Train Loss: 0.3435, Val Loss: 0.3196
Fold 1 - MSE: 42.6597, RMSE: 6.5314, MAE: 4.4030
Starting fold 2...
  Epoch 0... Train Loss: 0.9029, Val Loss: 0.7267
  Epoch 10... Train Loss: 0.4340, Val Loss: 0.5287
  Epoch 20... Train Loss: 0.3713, Val Loss: 0.4277
  Epoch 30... Train Loss: 0.2837, Val Loss: 0.4592
  Epoch 40... Train Loss: 0.2697, Val Loss: 0.4712
  Epoch 50... Train Loss: 0.2275, Val Loss: 0.4356
Fold 2 - MSE: 37.0832, RMSE: 6.0896, MAE: 3.7705
Starting fold 3...
  Epoch 0... Train Loss: 0.8616, Val Loss: 0.7696
  Epoch 10... Train Loss: 0.3542, Val Loss: 0.5212
  Epoch 20... Train Loss: 0.3075, Val Loss: 0.4282
  Epoch 30... Train Loss: 0.2606, Val Loss: 0.3611
  Epoch 40... Train Loss: 0.2544, Val Loss: 0.3980
  Epoch 50... Train Loss: 0.2246, Val Loss: 0.3858
Fold 3 - MSE: 38.5338, RMSE: 6.2076, MAE: 3.5669
Starting fold 4...
  Epoch 0... Train Loss: 0.8377, Val Loss: 0.8406
  Epoch 10... Train Loss: 0.3358, Val Loss: 0.7154
  Epoch 20... Train Loss: 0.2288, Val Loss: 0.8293
Fold 4 - MSE: 36.3348, RMSE: 6.0278, MAE: 4.4846
Starting fold 5...
  Epoch 0... Train Loss: 0.9069, Val Loss: 1.2035
  Epoch 10... Train Loss: 0.3912, Val Loss: 0.7812
  Epoch 20... Train Loss: 0.3200, Val Loss: 0.7864
  Epoch 30... Train Loss: 0.2601, Val Loss: 0.7242
  Epoch 40... Train Loss: 0.2492, Val Loss: 0.7801
  Epoch 50... Train Loss: 0.2542, Val Loss: 0.8115
  Epoch 60... Train Loss: 0.2403, Val Loss: 0.7114

[INFO 04-01 13:29:21] ax.service.ax_client: Completed trial 15 with data: {'avg_rmse_nonzero': 5.492281}.
[INFO 04-01 13:29:21] ax.service.ax_client: Generated new trial 16 with parameters {'dropout_rate': 0.181965, 'weight_decay': 0.002944, 'lr': 5.1e-05, 'batch_size': 128, 'early_stopping_patience': 15, 'n_layers': 2, 'hidden1': 1024, 'hidden2': 512, 'hidden3': 64, 'activation': 'elu'} using model Sobol.

Fold 5 - MSE: 6.7859, RMSE: 2.6050, MAE: 2.2679

Mean CV MSE: 32.2795, Mean CV RMSE: 5.4923, Mean CV MAE: 3.6986
Completed trial 15 with mean RMSE: 5.4923 ± 0.7270
Saved Ax client checkpoint

Starting trial 16 with parameters: {'dropout_rate': 0.18196521932259202, 'weight_decay': 0.0029440012197358948, 'lr': 5.097750430508125e-05, 'batch_size': 128, 'early_stopping_patience': 15, 'n_layers': 2, 'hidden1': 1024, 'hidden2': 512, 'hidden3': 64, 'activation': 'elu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 1.2194, Val Loss: 0.8103
  Epoch 10... Train Loss: 0.4713, Val Loss: 0.4359
  Epoch 20... Train Loss: 0.4138, Val Loss: 0.3606
  Epoch 30... Train Loss: 0.3639, Val Loss: 0.4568
Fold 1 - MSE: 43.7344, RMSE: 6.6132, MAE: 4.6427
Starting fold 2...
  Epoch 0... Train Loss: 0.9982, Val Loss: 0.7209
  Epoch 10... Train Loss: 0.3981, Val Loss: 0.8494
  Epoch 20... Train Loss: 0.3154, Val Loss: 0.5610
  Epoch 30... Train Loss: 0.2851, Val Loss: 0.5575
  Epoch 40... Train Loss: 0.2469, Val Loss: 0.7311
  Epoch 50... Train Loss: 0.2950, Val Loss: 0.5104
Fold 2 - MSE: 69.3289, RMSE: 8.3264, MAE: 6.6695
Starting fold 3...
  Epoch 0... Train Loss: 1.0125, Val Loss: 0.7767
  Epoch 10... Train Loss: 0.3769, Val Loss: 0.4552
  Epoch 20... Train Loss: 0.3550, Val Loss: 0.4928
  Epoch 30... Train Loss: 0.3031, Val Loss: 0.3680
  Epoch 40... Train Loss: 0.2751, Val Loss: 0.3768
  Epoch 50... Train Loss: 0.2516, Val Loss: 0.4040
  Epoch 60... Train Loss: 0.2554, Val Loss: 0.3696
Fold 3 - MSE: 74.3030, RMSE: 8.6199, MAE: 5.6800
Starting fold 4...
  Epoch 0... Train Loss: 1.1296, Val Loss: 0.5294
  Epoch 10... Train Loss: 0.3441, Val Loss: 0.4383
  Epoch 20... Train Loss: 0.2755, Val Loss: 0.6089
  Epoch 30... Train Loss: 0.2525, Val Loss: 0.4263
  Epoch 40... Train Loss: 0.2558, Val Loss: 0.5508
  Epoch 50... Train Loss: 0.2351, Val Loss: 0.3864
  Epoch 60... Train Loss: 0.2609, Val Loss: 0.4368
Fold 4 - MSE: 44.9298, RMSE: 6.7030, MAE: 5.5858
Starting fold 5...
  Epoch 0... Train Loss: 0.9411, Val Loss: 1.5788
  Epoch 10... Train Loss: 0.4016, Val Loss: 0.7819
  Epoch 20... Train Loss: 0.3258, Val Loss: 0.6349
  Epoch 30... Train Loss: 0.3133, Val Loss: 1.2720

[INFO 04-01 13:29:28] ax.service.ax_client: Completed trial 16 with data: {'avg_rmse_nonzero': 6.517464}.

  Epoch 40... Train Loss: 0.3011, Val Loss: 0.8879
Fold 5 - MSE: 5.4049, RMSE: 2.3248, MAE: 1.8559

Mean CV MSE: 47.5402, Mean CV RMSE: 6.5175, Mean CV MAE: 4.8868
Completed trial 16 with mean RMSE: 6.5175 ± 1.1250
Saved Ax client checkpoint

[INFO 04-01 13:29:28] ax.service.ax_client: Generated new trial 17 with parameters {'dropout_rate': 0.401983, 'weight_decay': 2e-06, 'lr': 0.007516, 'batch_size': 32, 'early_stopping_patience': 38, 'n_layers': 3, 'hidden1': 256, 'hidden2': 128, 'hidden3': 256, 'activation': 'leaky_relu'} using model Sobol.

Starting trial 17 with parameters: {'dropout_rate': 0.40198255935683846, 'weight_decay': 1.8176248482081898e-06, 'lr': 0.007515723010589701, 'batch_size': 32, 'early_stopping_patience': 38, 'n_layers': 3, 'hidden1': 256, 'hidden2': 128, 'hidden3': 256, 'activation': 'leaky_relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 2.8990, Val Loss: 5.9802
  Epoch 10... Train Loss: 0.5641, Val Loss: 0.4693
  Epoch 20... Train Loss: 0.5885, Val Loss: 0.7695
  Epoch 30... Train Loss: 0.4276, Val Loss: 0.3667
  Epoch 40... Train Loss: 0.3819, Val Loss: 0.3128
  Epoch 50... Train Loss: 0.4103, Val Loss: 0.4630
Fold 1 - MSE: 39.4900, RMSE: 6.2841, MAE: 4.2520
Starting fold 2...
  Epoch 0... Train Loss: 2.2218, Val Loss: 11.6677
  Epoch 10... Train Loss: 0.5403, Val Loss: 0.8418
  Epoch 20... Train Loss: 0.4148, Val Loss: 0.5138
  Epoch 30... Train Loss: 0.3414, Val Loss: 0.6064
  Epoch 40... Train Loss: 0.3724, Val Loss: 0.5263
  Epoch 50... Train Loss: 0.2534, Val Loss: 0.4022
Fold 2 - MSE: 39.3386, RMSE: 6.2720, MAE: 3.8474
Starting fold 3...
  Epoch 0... Train Loss: 2.4289, Val Loss: 1.8912
  Epoch 10... Train Loss: 0.6475, Val Loss: 0.6257
  Epoch 20... Train Loss: 0.3686, Val Loss: 0.4794
  Epoch 30... Train Loss: 0.3530, Val Loss: 0.4835
  Epoch 40... Train Loss: 0.2697, Val Loss: 0.4215
Fold 3 - MSE: 26.4516, RMSE: 5.1431, MAE: 3.5342
Starting fold 4...
  Epoch 0... Train Loss: 2.0336, Val Loss: 1.3935
  Epoch 10... Train Loss: 0.5498, Val Loss: 0.9628
  Epoch 20... Train Loss: 0.2828, Val Loss: 0.5197
  Epoch 30... Train Loss: 0.3007, Val Loss: 0.4754
  Epoch 40... Train Loss: 0.2154, Val Loss: 0.4835
Fold 4 - MSE: 27.7248, RMSE: 5.2654, MAE: 4.1562
Starting fold 5...
  Epoch 0... Train Loss: 2.1587, Val Loss: 2.2053
  Epoch 10... Train Loss: 0.5281, Val Loss: 1.0300
  Epoch 20... Train Loss: 0.4357, Val Loss: 0.8433
  Epoch 30... Train Loss: 0.2699, Val Loss: 0.7443
  Epoch 40... Train Loss: 0.3040, Val Loss: 0.7697
  Epoch 50... Train Loss: 0.2676, Val Loss: 0.8341
  Epoch 60... Train Loss: 0.2880, Val Loss: 0.7624
  Epoch 70... Train Loss: 0.3027, Val Loss: 0.7569
  Epoch 80... Train Loss: 0.2795, Val Loss: 0.7360

[INFO 04-01 13:29:53] ax.service.ax_client: Completed trial 17 with data: {'avg_rmse_nonzero': 5.15046}.
[INFO 04-01 13:29:53] ax.service.ax_client: Generated new trial 18 with parameters {'dropout_rate': 0.341531, 'weight_decay': 1.2e-05, 'lr': 6.7e-05, 'batch_size': 64, 'early_stopping_patience': 48, 'n_layers': 3, 'hidden1': 512, 'hidden2': 128, 'hidden3': 64, 'activation': 'selu'} using model Sobol.

Fold 5 - MSE: 7.7707, RMSE: 2.7876, MAE: 2.3734

Mean CV MSE: 28.1551, Mean CV RMSE: 5.1505, Mean CV MAE: 3.6326
Completed trial 17 with mean RMSE: 5.1505 ± 0.6379
Saved Ax client checkpoint

Starting trial 18 with parameters: {'dropout_rate': 0.3415313819423318, 'weight_decay': 1.2420565667216967e-05, 'lr': 6.668923920087367e-05, 'batch_size': 64, 'early_stopping_patience': 48, 'n_layers': 3, 'hidden1': 512, 'hidden2': 128, 'hidden3': 64, 'activation': 'selu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 1.2986, Val Loss: 0.6699
  Epoch 10... Train Loss: 0.8046, Val Loss: 0.4740
  Epoch 20... Train Loss: 0.5440, Val Loss: 0.3878
  Epoch 30... Train Loss: 0.6100, Val Loss: 0.3026
  Epoch 40... Train Loss: 0.4822, Val Loss: 0.2774
  Epoch 50... Train Loss: 0.5954, Val Loss: 0.4459
Fold 1 - MSE: 46.6178, RMSE: 6.8277, MAE: 4.6604
Starting fold 2...
  Epoch 0... Train Loss: 1.0272, Val Loss: 0.7450
  Epoch 10... Train Loss: 0.6285, Val Loss: 0.8800
  Epoch 20... Train Loss: 0.5446, Val Loss: 0.6257
  Epoch 30... Train Loss: 0.5165, Val Loss: 0.6827
  Epoch 40... Train Loss: 0.5193, Val Loss: 0.7072
Fold 2 - MSE: 59.0310, RMSE: 7.6832, MAE: 5.3994
Starting fold 3...
  Epoch 0... Train Loss: 1.2070, Val Loss: 0.8206
  Epoch 10... Train Loss: 0.5858, Val Loss: 0.5134
  Epoch 20... Train Loss: 0.5366, Val Loss: 0.5049
  Epoch 30... Train Loss: 0.4955, Val Loss: 0.4611
  Epoch 40... Train Loss: 0.4574, Val Loss: 0.4510
  Epoch 50... Train Loss: 0.4388, Val Loss: 0.4531
  Epoch 60... Train Loss: 0.4140, Val Loss: 0.4594
Fold 3 - MSE: 57.8073, RMSE: 7.6031, MAE: 4.5826
Starting fold 4...
  Epoch 0... Train Loss: 1.1532, Val Loss: 0.5856
  Epoch 10... Train Loss: 0.5950, Val Loss: 0.5321
  Epoch 20... Train Loss: 0.4990, Val Loss: 0.5806
  Epoch 30... Train Loss: 0.4667, Val Loss: 0.5176
Fold 4 - MSE: 43.3732, RMSE: 6.5858, MAE: 4.7683
Starting fold 5...
  Epoch 0... Train Loss: 1.1625, Val Loss: 1.4517
  Epoch 10... Train Loss: 0.6289, Val Loss: 0.9281

[INFO 04-01 13:30:04] ax.service.ax_client: Completed trial 18 with data: {'avg_rmse_nonzero': 6.713281}.
[INFO 04-01 13:30:04] ax.service.ax_client: Generated new trial 19 with parameters {'dropout_rate': 0.121392, 'weight_decay': 0.000136, 'lr': 0.000479, 'batch_size': 256, 'early_stopping_patience': 26, 'n_layers': 1, 'hidden1': 2048, 'hidden2': 512, 'hidden3': 512, 'activation': 'relu'} using model Sobol.

  Epoch 20... Train Loss: 0.5448, Val Loss: 0.9496
Fold 5 - MSE: 23.6836, RMSE: 4.8666, MAE: 3.7016

Mean CV MSE: 46.1026, Mean CV RMSE: 6.7133, Mean CV MAE: 4.6224
Completed trial 18 with mean RMSE: 6.7133 ± 0.5085
Saved Ax client checkpoint

Starting trial 19 with parameters: {'dropout_rate': 0.12139178533107042, 'weight_decay': 0.0001363615050625893, 'lr': 0.0004792096657206611, 'batch_size': 256, 'early_stopping_patience': 26, 'n_layers': 1, 'hidden1': 2048, 'hidden2': 512, 'hidden3': 512, 'activation': 'relu'}
Using device: cuda
Starting fold 1...
  Epoch 0... Train Loss: 13.2798, Val Loss: 19.8855
  Epoch 10... Train Loss: 0.8044, Val Loss: 0.6364
  Epoch 20... Train Loss: 0.4593, Val Loss: 0.4110
  Epoch 30... Train Loss: 0.4078, Val Loss: 0.3701
  Epoch 40... Train Loss: 0.3230, Val Loss: 0.3192
  Epoch 50... Train Loss: 0.3563, Val Loss: 0.3244
  Epoch 60... Train Loss: 0.3056, Val Loss: 0.2872
  Epoch 70... Train Loss: 0.3084, Val Loss: 0.3129
  Epoch 80... Train Loss: 0.3657, Val Loss: 0.3005
Fold 1 - MSE: 45.0119, RMSE: 6.7091, MAE: 4.5901
Starting fold 2...
  Epoch 0... Train Loss: 5.2275, Val Loss: 3.5796
  Epoch 10... Train Loss: 0.4576, Val Loss: 0.5918
  Epoch 20... Train Loss: 0.2946, Val Loss: 0.5255
  Epoch 30... Train Loss: 0.2774, Val Loss: 0.4769
  Epoch 40... Train Loss: 0.2330, Val Loss: 0.4674
  Epoch 50... Train Loss: 0.2594, Val Loss: 0.4679
  Epoch 60... Train Loss: 0.2534, Val Loss: 0.4711
Fold 2 - MSE: 36.9144, RMSE: 6.0757, MAE: 3.5701
Starting fold 3...
  Epoch 0... Train Loss: 6.4474, Val Loss: 5.8249
  Epoch 10... Train Loss: 0.4134, Val Loss: 0.5688
  Epoch 20... Train Loss: 0.2971, Val Loss: 0.4793
  Epoch 30... Train Loss: 0.2871, Val Loss: 0.4392
  Epoch 40... Train Loss: 0.2360, Val Loss: 0.4037
  Epoch 50... Train Loss: 0.2270, Val Loss: 0.4116
  Epoch 60... Train Loss: 0.2012, Val Loss: 0.3991
  Epoch 70... Train Loss: 0.2070, Val Loss: 0.4003
  Epoch 80... Train Loss: 0.2006, Val Loss: 0.4001
Fold 3 - MSE: 48.7084, RMSE: 6.9791, MAE: 4.1288
Starting fold 4...
  Epoch 0... Train Loss: 7.5966, Val Loss: 6.8391
  Epoch 10... Train Loss: 0.4364, Val Loss: 0.6400
  Epoch 20... Train Loss: 0.2739, Val Loss: 0.5203
  Epoch 30... Train Loss: 0.2447, Val Loss: 0.5285
  Epoch 40... Train Loss: 0.2261, Val Loss: 0.5123
Fold 4 - MSE: 46.8472, RMSE: 6.8445, MAE: 5.1469
Starting fold 5...
  Epoch 0... Train Loss: 6.1196, Val Loss: 2.7967
  Epoch 10... Train Loss: 0.4048, Val Loss: 0.8988
  Epoch 20... Train Loss: 0.2999, Val Loss: 0.8812
  Epoch 30... Train Loss: 0.2967, Val Loss: 0.8429
  Epoch 40... Train Loss: 0.2797, Val Loss: 0.8692
  Epoch 50... Train Loss: 0.2622, Val Loss: 0.8316
  Epoch 60... Train Loss: 0.2529, Val Loss: 0.8296
  Epoch 70... Train Loss: 0.2592, Val Loss: 0.8231

[INFO 04-01 13:30:09] ax.service.ax_client: Completed trial 19 with data: {'avg_rmse_nonzero': 6.136032}.

  Epoch 80... Train Loss: 0.2536, Val Loss: 0.8336
Fold 5 - MSE: 16.5788, RMSE: 4.0717, MAE: 2.7265

Mean CV MSE: 38.8121, Mean CV RMSE: 6.1360, Mean CV MAE: 4.0325
Completed trial 19 with mean RMSE: 6.1360 ± 0.5388
Saved Ax client checkpoint

In [36]:
# Get best parameters after all trials
best_parameters, values = ax_client_dmax_nn.get_best_parameters()
print(f"\n{'='*60}")
print("OPTIMIZATION COMPLETE")
print('='*60)
print(f"Best parameters: {best_parameters}")
print(f"Best Non-zero RMSE: {values[0]['avg_rmse_nonzero']:.4f}")

============================================================
OPTIMIZATION COMPLETE
============================================================
Best parameters: {'dropout_rate': 0.04750590957701206, 'weight_decay': 2.5574126909661948e-05, 'lr': 0.0008225891520342827, 'batch_size': 128, 'early_stopping_patience': 38, 'n_layers': 3, 'hidden1': 256, 'hidden2': 512, 'hidden3': 512, 'activation': 'leaky_relu'}
Best Non-zero RMSE: 4.9639

In [37]:
#evaluate the best parameters on the test set

# Auto-detect device
if torch.cuda.is_available():
    device = torch.device('cuda')
elif torch.backends.mps.is_available():
    device = torch.device('mps')
else:
    device = torch.device('cpu')
print(f"Using device: {device}")


#best parameters from the ax optimization loop
best_parameters_NN_dmax = {'dropout_rate': 0.04750590957701206, 'weight_decay': 2.5574126909661948e-05, 'lr': 0.0008225891520342827, 'batch_size': 128, 'early_stopping_patience': 38, 'n_layers': 3, 'hidden1': 256, 'hidden2': 512, 'hidden3': 512, 'activation': 'leaky_relu'}

#combine layer dimensions into a list for the model
hidden_layers = [best_parameters_NN_dmax["hidden1"], best_parameters_NN_dmax["hidden2"], best_parameters_NN_dmax["hidden3"]][:best_parameters_NN_dmax["n_layers"]]

#copy the x and y data
X_evaluate_train = X_train_opt.copy()
y_evaluate_train = y_train_opt.copy()
X_evaluate_test = X_test.copy() 
y_evaluate_test = y_test.copy()

#split the train data into train and validation data
X_evaluate_train, X_evaluate_val, y_evaluate_train, y_evaluate_val = train_test_split(X_evaluate_train, y_evaluate_train, test_size=0.2, random_state=42)

#scale the X_data
Scaler_X_evaluate = StandardScaler()
X_evaluate_train_scaled = Scaler_X_evaluate.fit_transform(X_evaluate_train)
X_evaluate_val_scaled = Scaler_X_evaluate.transform(X_evaluate_val)
X_evaluate_test_scaled = Scaler_X_evaluate.transform(X_evaluate_test)

#Scale the y data
Scaler_y_evaluate = StandardScaler()
y_evaluate_train_scaled = Scaler_y_evaluate.fit_transform(np.array(y_evaluate_train).reshape(-1, 1)).flatten()
y_evaluate_val_scaled = Scaler_y_evaluate.transform(np.array(y_evaluate_val).reshape(-1, 1)).flatten()
y_evaluate_test_scaled = Scaler_y_evaluate.transform(np.array(y_evaluate_test).reshape(-1, 1)).flatten()

#convert all data to tensors
X_evaluate_train_tensor = torch.tensor(X_evaluate_train_scaled, dtype=torch.float32).to(device)
y_evaluate_train_tensor = torch.tensor(y_evaluate_train_scaled, dtype=torch.float32).to(device)
X_evaluate_val_tensor = torch.tensor(X_evaluate_val_scaled, dtype=torch.float32).to(device)
y_evaluate_val_tensor = torch.tensor(y_evaluate_val_scaled, dtype=torch.float32).to(device)
X_evaluate_test_tensor = torch.tensor(X_evaluate_test_scaled, dtype=torch.float32).to(device)
y_evaluate_test_tensor = torch.tensor(y_evaluate_test_scaled, dtype=torch.float32).to(device)

#convert tensors to datasets then dataloaders
evaluate_train_ds = TensorDataset(X_evaluate_train_tensor, y_evaluate_train_tensor)
evaluate_train_loader = DataLoader(evaluate_train_ds, batch_size=best_parameters_NN_dmax["batch_size"], shuffle=True, generator=torch.Generator().manual_seed(42))
evaluate_val_ds = TensorDataset(X_evaluate_val_tensor, y_evaluate_val_tensor)
evaluate_val_loader = DataLoader(evaluate_val_ds, batch_size=best_parameters_NN_dmax["batch_size"], shuffle=True, generator=torch.Generator().manual_seed(42))
evaluate_test_ds = TensorDataset(X_evaluate_test_tensor, y_evaluate_test_tensor)
evaluate_test_loader = DataLoader(evaluate_test_ds, batch_size=best_parameters_NN_dmax["batch_size"], shuffle=False, generator=torch.Generator().manual_seed(42))


#initialize the model
input_dim = X_evaluate_train_tensor.shape[1]
model = DmaxNet(input_dim, hidden_layers, best_parameters_NN_dmax["dropout_rate"], best_parameters_NN_dmax["activation"]).to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=best_parameters_NN_dmax["lr"], weight_decay=best_parameters_NN_dmax["weight_decay"])
scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, patience=best_parameters_NN_dmax["early_stopping_patience"] // 3, factor=0.5)
criterion = nn.MSELoss()


best_val_loss = float("inf")
best_state = None
wait = 0

for epoch in range(1000):

    train_loss = train_one_epoch(model, evaluate_train_loader, optimizer, criterion, device)
    val_loss = evaluate(model, evaluate_val_loader, criterion, device)
    if epoch % 10 == 0:
        print(f"  Epoch {epoch}... Train Loss: {train_loss:.4f}, Val Loss: {val_loss:.4f}")
    scheduler.step(val_loss)
    
    if val_loss < best_val_loss:
        best_val_loss = val_loss
        best_state = {k: v.cpu().clone() for k, v in model.state_dict().items()}
        wait = 0
    else:
        wait += 1
        if wait >= best_parameters_NN_dmax["early_stopping_patience"]:
            break

# Restore best model and evaluate on fold test set
model.load_state_dict(best_state)

#predict the fold test set and inverse transform the predictions and actuals back to original scale
y_fold_test_pred_scaled, y_fold_test_actual_scaled = predict(model, evaluate_test_loader, device)
y_fold_test_pred = Scaler_y_evaluate.inverse_transform(y_fold_test_pred_scaled.reshape(-1, 1)).flatten()
y_fold_test_actual = Scaler_y_evaluate.inverse_transform(y_fold_test_actual_scaled.reshape(-1, 1)).flatten()

#calculate the fold mse, rmse, and mae and add to the list of fold metrics
fold_mse = np.mean((y_fold_test_pred - y_fold_test_actual) ** 2)
fold_rmse = np.sqrt(fold_mse)
fold_mae = np.mean(np.abs(y_fold_test_pred - y_fold_test_actual))

#print the fold metrics
print(f"Test Results - MSE: {fold_mse:.4f}, RMSE: {fold_rmse:.4f}, MAE: {fold_mae:.4f}")

Using device: cuda
  Epoch 0... Train Loss: 1.1115, Val Loss: 0.4326
  Epoch 10... Train Loss: 0.2897, Val Loss: 0.2981
  Epoch 20... Train Loss: 0.2083, Val Loss: 0.3740
  Epoch 30... Train Loss: 0.1810, Val Loss: 0.3133
  Epoch 40... Train Loss: 0.2194, Val Loss: 0.2810
  Epoch 50... Train Loss: 0.1621, Val Loss: 0.2938
  Epoch 60... Train Loss: 0.1547, Val Loss: 0.3356
  Epoch 70... Train Loss: 0.1568, Val Loss: 0.3038
  Epoch 80... Train Loss: 0.1598, Val Loss: 0.3353
Test Results - MSE: 8.6369, RMSE: 2.9389, MAE: 1.9647